### ISSUE TITLE
bokeh apps not running or unreachable

### ISSUE THREAD

**Issue by vincentschut** [dask/distributed#1027]
I cannot reach any of the bokeh apps anymore, neither from port 8787 nor from 8788. The page with the overview of the active apps is showing on both ports. But clicking on any of the app links (status, tasks, etc.) is unresponsive.

I think this is since I upgraded my dask/distributed to master yesterday. I'll try a downgrade once I have time and no urgent scheduled tasks anymore later today.

I have no idea how to debug this, unfortunately I'm no bokeh expert. Any hint is welcome.

**Comment by pitrou** [comment]
Did you upgrade Tornado as well?  Bokeh is currently incompatible with Tornado 4.5: https://github.com/bokeh/bokeh/issues/6152

**Comment by vincentschut** [comment]
tornado==4.4.2

**Comment by pitrou** [comment]
Can I ask exactly how you started Dask / distributed exactly, so I can try to reproduce?

**Comment by vincentschut** [comment]
I run this on GCE (Google Cloud Engine). 10.132.0.2 is the internal addres of the instance. For testing purposes, everything is running on the same instance. I tried without --host= parameter, effectively using 127.0.0.1, but that did not work, the workers could not see the scheduler. Something gcp related, probably.

start the scheduler:
`dask-scheduler --host=10.132.0.2`

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:     tcp://10.132.0.2:8786
distributed.scheduler - INFO -        http at:           10.132.0.2:9786
distributed.scheduler - INFO -       bokeh at:           10.132.0.2:8788
distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
```

start 2 8-process workers (one for network bound tasks, and one for cpu-bound tasks):
`dask-worker --nthreads=1 --nprocs=8 10.132.0.2:8786 --resources "NET=1"`
`dask-worker --nthreads=1 --nprocs=8 10.132.0.2:8786 --resources "CPU=1"`

**Comment by vincentschut** [comment]
It's not ip/firewall related. Running 'curl localhost:8787' on the same instance as the scheduler returns immediately with the 'Active Bokeh Applications' page, while running 'curl localhost:8787/status' gives a timeout.

**Comment by pitrou** [comment]
I cannot reproduce here. Can I ask you your Python version and detailed environment (`conda list` and/or `pip list`)?

**Comment by jsonjunky** [comment]
I have this problem. It seems bokeh does not run on the address of the scheduler it only runs on loopback. This is probably the problem.

**Comment by jsonjunky** [comment]
I reverted back to this and it works again:
 pip install -U tornado==4.3

**Comment by pitrou** [comment]
What about other Tornado versions (4.4, 4.4.1)? It would be nice to find out exactly where this started breaking for you.

**Comment by jsonjunky** [comment]
I can try the other versions. But it's easy enough to try yourself in a virtualenv and fully reproducible.

**Comment by bryevdv** [comment]
I have not seen any reports of problems with 4.4.2 and I am using it currently without any problem so if you can find some reproducible broken configuration with anything other than 4.5, it's probably worth an issue on the bokeh tracker.

**Comment by vincentschut** [comment]
See my initial report of this issue above, it was on tornado 4.4.2. I just downgraded to 4.3 and that indeed fixes it.
I presume this only is an issue if
1) you run this with another host ip than the default; and maybe only if:
2) the interface that you are accessing (the external ip) is isolated from the localhost/loopback ip.
I can check with 4.4 and 4.4.1 later.

**Comment by vincentschut** [comment]
tornado 4.4 works fine.

**Comment by vincentschut** [comment]
tornado 4.4.1 works fine too.

**Comment by vincentschut** [comment]
Hmm, 4.4.2 seems to work too now...?! Apparently there was something wrong with my pip3 freeze output or my python environment when reporting. It might have been 4.5 after all...? <confused...>

**Comment by bryevdv** [comment]
I've definitely thought I had some version of a thing installed when I actually had another version (mixup with different envs, etc). Glad its working. FYI there is a new conda package for `0.12.6` on the defaults channel landing today that excludes Tornado 4.5

**Comment by pitrou** [comment]
@vincentschut if you used both `pip` and `conda`, perhaps there were two versions of Tornado installed (one by each tool) at some point. It happened to me in the past.

**Comment by vincentschut** [comment]
Very well possible. I'll keep with tornado 4.4 for now, and test with 4.5 and bokeh 0.12.6 later. Thanks all for your input! I assume this ticket can be closed. Feel free to reopen when needed.

**Comment by kjam** [comment]
Hi @vincentschut, I had the same issue. I don't use conda (pip + venv + python 3.6) on Ubuntu. I also tried py3.4. I could not get bokeh apps working with following combinations:
tornado==4.4 
bokeh==0.12.(4,6)
distributed==0.16.(0-1) 

now working with:
tornado==4.3 
bokeh==0.12.4
distributed==0.16.0 

Let me know if you want any other details, cheers :)

**Comment by giantamoeba** [comment]
Same problem here with tornado 4.5.1, bokeh 0.12.5, and distributed 1.15.2

**Comment by pitrou** [comment]
@giantamoeba, you should downgrade Tornado to 4.4.3 until the issue is fixed on the Bokeh side.

**Comment by giantamoeba** [comment]
@pitrou just did that and it works

**Comment by bkyryliuk** [comment]
@mrocklin or @vincentschut   - can you please reopen this issue::
New release requires: tornado>=4.5.1
( http://matthewrocklin.com/blog/work/2017/09/24/dask-0.15.3)

But the workaround here works only with tornado==4.3

**Comment by mrocklin** [comment]
I think that if you just update bokeh everything should be fine

**Comment by bkyryliuk** [comment]
yeah, it worked, thanks !

**Comment by benjaminsingleton** [comment]
I'm running into a similar issue as described above so I figured I'd piggyback on this issue rather than create a new one.

After initiating a client, I can successfully load the following web pages:
- `http://127.0.0.1:8787/`
- `/counters`
- `/profile`
- `/status`
- `/system`
- `/workers`

However, I get `500: Internal Server Error` on the following pages with the detailed error below:
- `/tasks`
- `/events`
- `/stealing`

Error message:

```
tornado.application - ERROR - Uncaught exception GET /tasks (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/tasks', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8787', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:8787/', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\server\views\doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\server\views\session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\server\application_context.py", line 182, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\application\application.py", line 179, in initialize_document
    h.modify_document(doc)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\application\handlers\function.py", line 131, in modify_document
    self._func(doc)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\distributed\bokeh\scheduler.py", line 955, in tasks_doc
    sizing_mode='stretch_both')
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\distributed\bokeh\scheduler.py", line 586, in __init__
    clear_interval=clear_interval, **kwargs)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\distributed\bokeh\components.py", line 104, in __init__
    ResetTool(reset_size=False),
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\core\has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "C:\Users\ben\Continuum\Anaconda\lib\site-packages\bokeh\core\has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'reset_size' to ResetTool, possible attributes are js_event_callbacks, js_property_callbacks, name, subscribed_events or tags
```

Package versions:

```
dask=0.16.1
tornado=4.5.3
bokeh=0.12.14
distributed=1.20.2
```

**Comment by mrocklin** [comment]
You'll either have to move Bokeh back a version to 0.12.13 or wait a day
for dask to be released.  The recent Bokeh release (yesterday?) breaks
compatibility.

**Comment by benjaminsingleton** [comment]
@mrocklin Thanks, I can wait a day!

**Comment by mrocklin** [comment]
@bryevdv a long while ago someone made a bunch of bokeh plots for dask using older syntax that I've since been informed (by you) is less well supported.  At some point we should clean these up.

See https://github.com/dask/distributed/pull/1728/files

**Comment by bryevdv** [comment]
@mrocklin apologies, that option was cruft that should have been removed and deprecated along with the resize tool. I had thought at this point later that just removing it would not affect anyone adversely which is probably always a bad assumption. If it is possible to create some minimal script that could be run as a smoke test for dask usage I would be happy to integrate it into an "upstream" test build.

**Comment by jgerardsimcock** [comment]
I am encountering this problem with the following versions:

```
bokeh==0.12.16
dask==0.18.2
distributed=1.22.0
```

The `info` tab is the only tab that renders and it does display all the workers and I am able to click on each worker and view its logs.

**Comment by mrocklin** [comment]
The info tab is the only one that doesn't use websockets.  I suspect that
you are behind some sort of firewall that doesn't like websockets.

**Comment by mrocklin** [comment]
> Where can I learn more about this?

I don't have a good reference for you.  You might consult logs coming from
the developer console in your browser.   You might research on google about
web sockets and whatever systems you use around GKE.  You might ask
questions of the bokeh mailing list.  You might try to reduce the problem a
bit to see if you can reproduce it with a simpler bokeh server application,
or with anything else that uses websockets.

**Comment by BharatAD** [comment]
Hi I attempt to open the Bokeh web interface for my local dask distributed client via `http://localhost:8787/status`, and am prompted with the following error: This site can’t be reached localhost refused to connect.

My current versions of the relevant modules are:
dask==1.2.2
distributed==1.28.1
tornado==5.0
bokeh==0.12.13

**Comment by mrocklin** [comment]
I recommend trying two things:

1.  Upgrade bokeh (your version is quite old)
2.  Use `python -m http.server` to verify that your network permissions allow you to host websites locally.
