### ISSUE TITLE
Local cluster fails to close on Client.shutdown()

### ISSUE THREAD

**Issue by bschreck** [dask/distributed#1042]
I assume this is a bug but maybe it's what's supposed to happen. When I initialize a Client with no arguments (so that it initializes a LocalCluster as well), and then call shutdown(), the cluster does not shutdown properly. This is because the client shuts down it's IOLoop first, and then at the end tries to close the cluster. The cluster's close method checks if its IOLoop is running before actually closing.

However, moving the cluster.close() call to the start of Client.shutdown() does trick:

    def shutdown(self, timeout=10):
                if self.status == 'closed':
                    return
        # call this before closing loop (cluster runs on same ioloop as self)
        with ignoring(AttributeError):
            self.cluster.close()
        sync(self.loop, self._shutdown, fast=True)
        assert self.status == 'closed'
        ...

**Comment by mrocklin** [comment]
Not shutting down the cluster when calling Client().shutdown() seems like a
bug to me.  Any interest in submitting a PR?
