### ISSUE TITLE
1.16.2 Broken?

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#1056]
I've just upgraded to 1.16.2 on win64/py35 and am getting the below error when trying to run the scheduler:
```python-traceback
λ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
Traceback (most recent call last):
  File "C:\Python\envs\py-dev\Scripts\dask-scheduler-script.py", line 5, in <module>
    sys.exit(distributed.cli.dask_scheduler.go())
  File "C:\Python\envs\py-dev\lib\site-packages\distributed\cli\dask_scheduler.py", line 149, in go
    main()
  File "C:\Python\envs\py-dev\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python\envs\py-dev\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\envs\py-dev\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python\envs\py-dev\lib\site-packages\distributed\cli\dask_scheduler.py", line 108, in main
    from distributed.bokeh.scheduler import BokehScheduler
  File "C:\Python\envs\py-dev\lib\site-packages\distributed\bokeh\scheduler.py", line 51, in <module>
    with open(os.path.join(os.path.dirname(__file__), 'template.html')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python\\envs\\py-dev\\lib\\site-packages\\distributed\\bokeh\\template.html'
```

**Comment by dhirschfeld** [comment]
That file doesn't exist in my site-packages and neither do the templates directories under either bokeh/status or bokeh/workers

Is it an issue with the setup.py package_data?

**Comment by dhirschfeld** [comment]
Manually copying the 3 html files into my site-packages from GitHub does get things working again.

**Comment by mrocklin** [comment]
Thanks for the report @dhirschfeld .  This was an oversight when packaging.  Resolving now.  Will push an update to PyPI soon.

**Comment by mrocklin** [comment]
Hrm, when trying this out with a fresh environment, template.html *is* present when I install.  

```
conda create -n test-3 python
source activate test-3
pip install dask distributed bokeh tornado=4.4
```

I do run into the tornado 4.5 vs bokeh 0.12.5 issue but other than that things seem fine.

How are you installing @dhirschfeld ?

**Comment by mrocklin** [comment]
It looks like template.html is listed as package data

          package_data={ '': ['templates/index.html', 'template.html'], },

**Comment by TomAugspurger** [comment]
You might have to include it the MANIFEST.in as well. I've never really understood the rules for what gets included in which builds, but MANIFEST.in + package_data seems to work for source and binary distributions.

**Comment by mrocklin** [comment]
Yeah, so I went to go add the new template to the manifest and noticed that none of the template files were ever in the manifest.  I suspect that `package_data= ` is supposed to handle this.  We can add it as well of course, but it's odd.

@dhirschfeld to add to my "how did you install" question can I also ask "what version of pip/conda are you using?"

**Comment by dhirschfeld** [comment]
I did a contact install and am running the latest version of contact.

Away from my computer at the moment so can specify the exact version number.

**Comment by dhirschfeld** [comment]
NB: I also did a force re-install to eliminate the possibility of a borked install but that didn't help.

My next avenue of investigation would be to inspect the contents of the conda bz2 file to check they're missing in there. I won't be able to get around to that until the morning tho...

**Comment by mrocklin** [comment]
Were you conda installing with the conda-forge channel or from defaults?

**Comment by perryhook** [comment]
Coming from: https://github.com/dask/dask-yarn/issues/10
I am having a similar error with the bokeh template.html and Dask. Install info follows:

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.10
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/me/anaconda3  (writable)
    default environment : /home/me/anaconda3
       envs directories : /home/me/anaconda3/envs
          package cache : /home/me/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```
```$ conda create -n dask_test2 python=2.7
....
$ source activate dask_test2
(dask_test2) $ conda install dask distributed -c conda-forge
...
(dask_test2) $ pip install dask-yarn
...
Installing collected packages: lxml, py4j, knit, dask-yarn, sortedcollections
Successfully installed dask-yarn-0.1.1 knit-0.2 lxml-3.7.3 py4j-0.10.4 sortedcollections-0.5.3
(dask_test2) $ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from dask_yarn import YARNCluster
>>> nn = 'hdm01.my_company.com'
>>> rm = 'hdm03.my_company.com'
>>> cluster = YARNCluster(nn=nn, rm=rm, packages=['python=2.7',])
Exception AttributeError: "'LocalCluster' object has no attribute 'workers'" in <object repr() failed> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/envs/dask_test/lib/python2.7/site-packages/dask_yarn/core.py", line 39, in __init__
    self.local_cluster = LocalCluster(n_workers=0, scheduler_port=0, ip=ip)
  File "/home/me/anaconda3/envs/dask_test/lib/python2.7/site-packages/distributed/deploy/local.py", line 100, in __init__
    from distributed.bokeh.scheduler import BokehScheduler
  File "/home/me/anaconda3/envs/dask_test/lib/python2.7/site-packages/distributed/bokeh/scheduler.py", line 51, in <module>
    with open(os.path.join(os.path.dirname(__file__), 'template.html')) as f:
IOError: [Errno 2] No such file or directory: '/home/me/anaconda3/envs/dask_test/lib/python2.7/site-packages/distributed/bokeh/template.html'
```

**Comment by mrocklin** [comment]
@jcrist or @pitrou I suspect that you both know more about Python packaging than I do.  Any thoughts on this?

**Comment by TomAugspurger** [comment]
FWIW, I was able to verify that conda-build didn't pick up the `template.html` from the released version, but *did* pick it up after I added it to `MANIFEST.in`.

The file was included in both sdist and bdist_wheel on the released version (so the entry in MANIFEST.in wasn't needed for those).

**Comment by dhirschfeld** [comment]
...and my installed version was from conda-forge

**Comment by mrocklin** [comment]
Want to throw up a tiny PR @TomAugspurger or perhaps just push directly to master?

**Comment by TomAugspurger** [comment]
done in 3e875035b4146add9df71303b764e2aadf4ff91c (on master)

**Comment by dhirschfeld** [comment]
@TomAugspurger - how about the `index.html` files under [`bokeh/status/templates`](https://github.com/dask/distributed/blob/master/distributed/bokeh/status/templates/index.html) and [`bokeh/workers/templates`](https://github.com/dask/distributed/blob/master/distributed/bokeh/workers/templates/index.html)?

They're also missing from the [`conda-forge`](https://anaconda.org/conda-forge/distributed/1.16.2/download/win-64/distributed-1.16.2-py35_0.tar.bz2) package.

**Comment by mrocklin** [comment]
This is interesting because those have been around for a long time.  I wonder if how conda build packages things has changed?

**Comment by dhirschfeld** [comment]
If you go back to [`1.15.0`]() you can see they're also missing from the package there - https://anaconda.org/conda-forge/distributed/1.15.0/download/win-64/distributed-1.15.0-py35_0.tar.bz2

...maybe they've never been included in the Windows builds?

**Comment by dhirschfeld** [comment]
Also missing from `1.13.3` and from the official repos too.

I'm guessing that the fancy new web-display I'm seeing is just from me manually patching my install with the template files? If so, I apologize for ever doubting your web-design skills 😜

**Comment by mrocklin** [comment]
It's mostly just stock Bokeh styling.  Thank those folks.

**Comment by TomAugspurger** [comment]
We probably just want a recursive include then. I'm away from my computer right now, but I'll make a PR later unless someone beats me to it.

**Comment by dhirschfeld** [comment]
Couldn't figure out exactly why `package_data` is failing on Windows but there seems to be a fair bit of noise about it being fragile.

FWIW the advice in [this](https://blog.ionelmc.ro/presentations/packaging/#slide:1) presentation is to simply use `MANIFEST.in` with `include_package_data` instead of `package_data`

**Comment by dhirschfeld** [comment]
Since it seems this has been fixed I'll close this issue. If there are any further problems I can always open a new one...

**Comment by mrocklin** [comment]
Thank you for taking the time to report this @dhirschfeld .  I appreciate it.
