### ISSUE TITLE
PEP 479 compatibility

### ISSUE THREAD

**Issue by slavoutich** [dask/distributed#1069]
[PEP 479](https://www.python.org/dev/peps/pep-0479/) changes style of exit from a generator. Basically, instead of
```python
raise StopIteration
```
one should
```
return
```
Currently, in Python 3.6 `AsCompleted.batches()` generator causes:
> DeprecationWarning: generator 'AsCompleted.batches' raised StopIteration

In Python 3.7 this will be an error, not a warning.

**Comment by mrocklin** [comment]
Are you interested in submitting a fix @slavoutich ?

**Comment by slavoutich** [comment]
This should be done carefully, at least. First, I can't find supported Python versions. For example, my system Python 3.4.5 (Gentoo stable) does not yet have
 ```python
from __future__ import generator_stop
```
For newer ones everything should be probably OK.

Also, for now tests for master branch are freezing for me on: 
> distributed/distributed/bokeh/tests/test_application.py::test_BokehWebInterface 

Need to explore this.

**Comment by mrocklin** [comment]
Bokeh 0.12.5 and tornado 4.5 have a known compatibility issue.  I suggest downgrading tornado to 4.4 temporarily.

**Comment by mrocklin** [comment]
Dask.distributed supports Python 2.7+ and Python 3.4+

**Comment by slavoutich** [comment]
Should be like this, seems like tests for `as_completed` are passing for me. Let's check CI oppinion.

By the way, there is another `raise StopIteration` in `channels.py`, not sure whether it needs to be handled properly.
