### ISSUE TITLE
_reevaluate_occupancy_worker() resets processing estimate

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#1100]
This is an intermittent test failure:
https://travis-ci.org/dask/distributed/jobs/235929242#L1472-L1521

Basically, `transition_waiting_processing` updates `processing` with the expected task duration plus the estimated communication cost, but `_reevaluate_occupancy_worker` can run just after and reset the `processing` estimate to its former value from `task_duration`.

I admit I don't understand why `_reevaluate_occupancy_worker` does this. Why does it mutate `processing` at all? `processing` is already maintained in real time in various state transitions...

**Comment by pitrou** [comment]
Actually, even `occupancy` is already updated in other transitions.

**Comment by mrocklin** [comment]
Original PR here: https://github.com/dask/distributed/pull/1038

As estimated task durations change the values in processing do not change.  However this change was intentionally experimental.  There may be more work to do here.
