### ISSUE TITLE
Distributed Coordination Objects

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1106]
In https://github.com/dask/dask-glm/issues/57 there is now a need for a distributed multi-producer multi-consumer queue.  I suspect that it will be somewhat straightforward to implement this in a way similar to what was done for channels.  

However, one can imagine wanting other coordination objects (events, conditions, locks, etc.) in the future.  Is there anything we should be doing now to prepare for this sort of infrastructure in the future?  Are there ways to implement these all together that would benefit from planning or common development?

cc @pitrou

**Comment by pitrou** [comment]
I think the challenge for distributed coordination objects will be to reduce the number of roundtrips, so each of them might need a custom design to achieve that goal. As a point of comparison, `multiprocessing` implements all coordination objects using a single basic synchronization primitive (a semaphore), but may use several of them at once to implement certain objects.

**Comment by mrocklin** [comment]
It would also be convenient to have a random access data structure like a list or dict rather than a sequential and append-only data structure like a channel or queue.  A common pattern here would be to convert this into a dask.array or dask.dataframe to get a snapshot of a dynamically changing dataset.

**Comment by mrocklin** [comment]
I'm going to give this a shot.  In particular I plan to implement a distributed queue.

**Comment by mrocklin** [comment]
I've added queues and singleton variables
