### ISSUE TITLE
task state does not change from 'no-worker' after adding workers

### ISSUE THREAD

**Issue by cosminbasca** [dask/distributed#1116]
Hi, 

I ran into the following behavior with dask. Here are the steps:
1. start a scheduler
2. submit some tasks (task changed state from 'released' to 'no-worker')
3. add workers (distributed.scheduler - INFO - Register..., distributed.scheduler - INFO - Starting worker compute stream, ...)
sadly the tasks states do not change again and are therefore not executed. Is this expected behavior? If yes is there a way to get out of it aside from reverting steps 2 and 3 ?

Thanks! 
Cheers, C

**Comment by mrocklin** [comment]
Here is an attempt to reproduce that unfortunately works as expected. 

```python
In [1]: from dask.distributed import Client, LocalCluster
c
In [2]: cluster = LocalCluster(n_workers=0)
cl
In [3]: client = Client(cluster)

In [4]: future = client.submit(lambda x: x + 1, 10)

In [5]: future
Out[5]: <Future: status: pending, key: <lambda>-d21ef8db8c1b190978ddade90f7b24b7>

In [6]: cluster.scheduler.task_state
Out[6]: {'<lambda>-d21ef8db8c1b190978ddade90f7b24b7': 'no-worker'}

In [7]: cluster.start_worker()
Out[7]: <Nanny: tcp://127.0.0.1:44446, threads: 8>

In [8]: future
Out[8]: <Future: status: finished, type: int, key: <lambda>-d21ef8db8c1b190978ddade90f7b24b7>

In [9]: cluster.scheduler.task_state
Out[9]: {'<lambda>-d21ef8db8c1b190978ddade90f7b24b7': 'memory'}
```

Can you recommend a minimum fail case that is reproducible and exhibits the behavior you're experiencing?

**Comment by cosminbasca** [comment]
Hi @mrocklin, After digging a bit more through our code, I noticed that the task was bound to a specific worker, which incidentally was not restarted (instead a new one was). That explains why we saw that behavior. Thanks a lot for the super fast reply and help, dask.distributed is an awesome framework! 

Cheers,
C

**Comment by mrocklin** [comment]
Note that you can also bind tasks to IP-addresses or worker names.  You might want to give you worker a name like the following:

    dask-worker ... --name Alice

Then you can bind tasks to that name and it will remain valid even through a restart event.

    future = client.submit(func, *args, workers='Alice')

**Comment by cosminbasca** [comment]
Thanks for the tip, indeed a non-ip based naming strategy would have solved our problem.
