### ISSUE TITLE
Drop Python 3.4 and ZMQ testing?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1154]
Travis-ci seems to have slowed down a bit lately.  Perhaps we should remove some of the burden by no longer testing the Python 3.4 / ZMQ config.  Any thoughts or concerns?

**Comment by mrocklin** [comment]
We might also consider moving the HDFS tests to daily instead of every-commit.

**Comment by pitrou** [comment]
How are failures on daily tests notified?

**Comment by mrocklin** [comment]
I don't know.  I've never used this feature before.

**Comment by pitrou** [comment]
Python 3.4 testing was removed in PR #1157, ZMQ in PR #1160.
