### ISSUE TITLE
Intermittent 404's for documentation pages on https://distributed.readthedocs.io

### ISSUE THREAD

**Issue by jalessio** [dask/distributed#1156]
I was having trouble navigating through the documentation for this project because I kept getting 404's. I thought the docs were producing bad links, but I finally realized that distributed.readthedocs.io sometimes returns 200 and sometimes returns a 404 for the same URL! I realize this probably is an issue for [rtfd/readthedocs.org](https://github.com/rtfd/readthedocs.org) but reporting it here since it's most likely affecting your user base and maybe you have some way to force a rebuild or escalate the issue.

Example of 4 http requests to the same URL -- 2 succeed and 2 fail:
```
for i in {1..4}; do curl -I https://distributed.readthedocs.io/en/latest/locality.html; done
HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Date: Fri, 09 Jun 2017 19:29:21 GMT
Content-Type: text/html
Content-Length: 31954
Last-Modified: Thu, 08 Jun 2017 16:52:03 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "593980b3-7cd2"
X-Subdomain-TryFiles: True
X-Served: Nginx
X-Deity: web03
Accept-Ranges: bytes

HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Date: Fri, 09 Jun 2017 19:29:21 GMT
Content-Type: text/html
Content-Length: 31954
Last-Modified: Thu, 08 Jun 2017 16:52:03 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "593980b3-7cd2"
X-Subdomain-TryFiles: True
X-Served: Nginx
X-Deity: web03
Accept-Ranges: bytes

HTTP/1.1 404 Not Found
Server: nginx/1.10.0 (Ubuntu)
Vary: Accept-Encoding
Vary: Cookie, Accept-Language
Content-Type: text/html; charset=utf-8
Date: Fri, 09 Jun 2017 19:29:22 GMT
Transfer-Encoding: chunked
Content-Language: en
Connection: Keep-Alive
Set-Cookie: csrftoken=P84b4mnalTvv2gukwCbwVVsDIRczbBwE; expires=Fri, 08-Jun-2018 19:29:22 GMT; httponly; Max-Age=31449600; Path=/

HTTP/1.1 404 Not Found
Server: nginx/1.10.0 (Ubuntu)
Vary: Accept-Encoding
Vary: Cookie, Accept-Language
Content-Type: text/html; charset=utf-8
Date: Fri, 09 Jun 2017 19:29:22 GMT
Transfer-Encoding: chunked
Content-Language: en
Connection: Keep-Alive
Set-Cookie: csrftoken=AYZRJbVZBquUyqDO34fwcnoT290JhZTX; expires=Fri, 08-Jun-2018 19:29:22 GMT; httponly; Max-Age=31449600; Path=/
```

**Comment by kuanb** [comment]
And now as a GIF!

![kapture 2017-06-09 at 13 29 44](https://user-images.githubusercontent.com/6053396/26993403-bccb7a78-4d17-11e7-854f-dd4f8e62a1ae.gif)

**Comment by mrocklin** [comment]
Yes, this is also affecting dask/dask.  Related issue here: https://github.com/dask/dask/issues/2446

**Comment by mrocklin** [comment]
Do you have any thoughts on what might cause this?

**Comment by jalessio** [comment]
@mrocklin I'd wildly speculate some sort of caching snafu in their setup. This seems similar to rtfd/readthedocs.org/issues/2416 which was resolved without explanation so not much to go on there.

**Comment by mrocklin** [comment]
Other projects have reported having the same issues so it appears to be an issue upstream.  This seems to have resolved itself.
