### ISSUE TITLE
Memoryviews and compression

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1159]
Currently there are some issues with how we handle memoryviews.

1.  We assume that `len(mv) == mv.nbytes` in several places.  This is not the case for non-trivial shape or itemsize
2. We slice into memoryviews in at least one place (see `distributed/protocol/utils.py`), which is also not correct for non-trivial shape or itemsize
3.  To support these concerns the Numpy serialization code currently always produces memoryviews that have strides `(1,)`.  This loses important information that stops intelligent compression.

I think that ideally we would propagate itemsize and strides information on memoryviews until after we pass through compression.  Then we might consider flattening memoryviews before they enter the network layer (`tornado.iostream.IOStream.write`) or perhaps earlier.  https://stackoverflow.com/questions/44486048/how-to-flatten-a-memoryview

Currently things seem safe but inefficient when itemsize might be useful.

**Comment by mrocklin** [comment]
Regarding the use of strides/shape: geo-spatial data can compress better if you arrange nearby pixels together.  Pre-processing with a space-filling curve can do some good

**Comment by sjperkins** [comment]
Note that `memoryview`  doesn't have an `nbytes` member in python 2.7 (but does in python 3), so [this](https://github.com/dask/distributed/blob/647238ea39b0a935d15dc647bb999fd6c268a6b3/distributed/utils.py#L818-L823) code breaks.

**Comment by mrocklin** [comment]
@sjperkins can you recommend a solution for Python 2?

**Comment by mrocklin** [comment]
Also have you run into this in the wild?

**Comment by sjperkins** [comment]
> @sjperkins can you recommend a solution for Python 2?


Adding `memoryview` to the if statement fixed things, but given point (1) in the first post, I wouldn't assume this is necessarily the correct solution?

```python
 def nbytes(frame):
    """ Number of bytes of a frame or memoryview """
    if type(frame) in (bytes, buffer, memoryview):
        return len(frame)
    else:
        return frame.nbytes
```

> Also have you run into this in the wild?

@mrocklin I ran into this with a small test case on my Ubuntu 16.04 laptop on distributed 1.17.0 and python 2.7.13

**Comment by mrocklin** [comment]
What were you doing?  Are you passing memoryviews around explicitly or are they coming from a library like NumPy or Pandas?

**Comment by pitrou** [comment]
This should work on Python 2:
```
>>> a = np.arange(12).reshape((3,4))
>>> m = memoryview(a)
>>> m.nbytes
Traceback (most recent call last):
  File "<ipython-input-4-d5e4db371fc2>", line 1, in <module>
    m.nbytes
AttributeError: 'memoryview' object has no attribute 'nbytes'

>>> from functools import reduce
>>> from operator import mul
>>> m.shape
(3L, 4L)
>>> m.itemsize
8L
>>> reduce(mul, m.shape, m.itemsize)
96L
```

**Comment by pitrou** [comment]
(it also gives the same result as `nbytes` on non-contiguous arrays, which is the number of bytes spanned by the actual data, not the total size including holes)

**Comment by mrocklin** [comment]
@sjperkins any interest in submitting a PR?

**Comment by sjperkins** [comment]
> What were you doing? Are you passing memoryviews around explicitly or are they coming from a library like NumPy or Pandas?

Creating a bunch of `da.ones` arrays and then using `client.persist` on a LocalCluster.

**Comment by mrocklin** [comment]
That's surprising.  I thought that numpy tended to use buffers in Python 2

```python
In [1]: import numpy as np

In [2]: np.ones(10).data
Out[2]: <read-write buffer for 0x7f8109ebcc60, size 80, offset 0 at 0x7f80fbb00030>

In [3]: np.ones((10, 10)).data
Out[3]: <read-write buffer for 0x7f810a733a80, size 800, offset 0 at 0x7f80fbb08670>

In [4]: type(_)
Out[4]: buffer
```

**Comment by pitrou** [comment]
I'm almost certain that the "buffer" there is just an ephemeral view over the actual memory owned by Numpy.

**Comment by mrocklin** [comment]
Still though, how would the protocol get a memorview.  It knows how to handle these buffer object, even if they're just views over other objects.  Going to try to reproduce...

**Comment by mrocklin** [comment]
```python
In [1]: import numpy as np

In [2]: np.ones(10).data
Out[2]: <read-write buffer for 0x7f0a5c0abee0, size 80, offset 0 at 0x7f0a5c054930>

In [3]: from distributed.protocol import serialize, dumps

In [4]: from distributed.protocol import serialize, dumps, to_serialize

In [5]: x = np.ones(10)

In [6]: serialize(x)
Out[6]: 
({'dtype': (0, '<f8'),
  'lengths': [80],
  'shape': (10,),
  'strides': (8,),
  'type': 'numpy.ndarray'},
 [<read-write buffer for 0x7f0a54efe2b0, size 80, offset 0 at 0x7f0a560ecb30>])

In [7]: dumps({'x': to_serialize(x)})
Out[7]: 
['',
 '\x80',
 '\x83\xc4\x04keys\x91\x91\xc4\x01x\xc4\x07headers\x81\x91\xc4\x01x\x87\xc4\x05count\x01\xc4\x0bcompression\x91\xc0\xc4\x07lengths\x91P\xc4\x05dtype\x92\x00\xc4\x03<f8\xc4\x07strides\x91\x08\xc4\x05shape\x91\n\xc4\x04type\xc4\rnumpy.ndarray\xc4\x0bbytestrings\x90',
 <read-write buffer for 0x7f0a54ebbc60, size 80, offset 0 at 0x7f0a54e8f530>]

In [8]: from dask.distributed import Client

In [9]: client = Client(processes=False)

In [10]: import dask.array as da

In [11]: x = da.ones(10, chunks=(5,)).persist()

In [12]: x.compute()
Out[12]: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]: import sys; sys.version_info
Out[13]: sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)

In [14]: np.__version__
Out[14]: '1.13.0'
```

**Comment by mrocklin** [comment]
>  Creating a bunch of da.ones arrays and then using client.persist on a LocalCluster.

@sjperkins thank you so much for fixing this issue.  I'm currently trying to determine if this is critical enough to warrant a new micro-release.  I'm unable to reproduce your exception on my own.  Do you happen to have a reproducible example that would have failed on the current release?

**Comment by sjperkins** [comment]
> @sjperkins thank you so much for fixing this issue. I'm currently trying to determine if this is critical enough to warrant a new micro-release. I'm unable to reproduce your exception on my own. Do you happen to have a reproducible example that would have failed on the current release?

See attached: [memoryview_missing_nbytes.zip](https://github.com/dask/distributed/files/1073849/memoryview_missing_nbytes.zip)

**Comment by sjperkins** [comment]
Note that there are some arrays with zero dimensions in them, but commenting them out did not prevent the problem occurring.

**Comment by mrocklin** [comment]
This was helpful.  Thank you.  It looks like this problem only arises when
we are moving enough data around.

**Comment by mrocklin** [comment]
We now pass through dtype information.  We don't yet pass through strides.  I'll wait on strides until we have a concrete application that needs N-d compression.  Closing
