### ISSUE TITLE
Asyncio interface for Variable 

### ISSUE THREAD

**Issue by kszucs** [dask/distributed#1164]
I guess it's enough to wrap _get and _set with to_asyncio, just not sure how to handle the default client. Right now, AioClient can't be set as default.

Ideas?

**Comment by mrocklin** [comment]
Set the client explicitly?  Have AioClient claim the default client global slot?

**Comment by jakirkham** [comment]
This is now unnecessary given PR ( https://github.com/dask/distributed/pull/1458 ) is in, correct?
