### ISSUE TITLE
Calling get() on a variable returns a future which does not have the latest state

### ISSUE THREAD

**Issue by danielb2814** [dask/distributed#1180]
Simple. Submit a future and add it to a variable. Then, from another client "peek" at the variable, i.e. don't call result() just look at the state and see if it is finished by calling variable.get()

Behavior: sometimes the state is fresh while other times it takes long to actually get the latest state of the future. 

By calling result on the future everything is fine. However I can't block  and need to return. Only when the future is finished can the caller block to get the result.

`   def inc(self, x):
        return x + 1

    def dummy(self, x):
        pass

    def test_variables_2(self):
        with Client(cfg.current_config.DISTRIBUTED_SCHEDULER) as client:
            L = client.map(self.inc, range(1000))
            f = client.submit(self.dummy, L)

            v = Variable(name="var", client=client)
            v.set(f)

            client.compute(f)
    
        while True:
            with Client(cfg.current_config.DISTRIBUTED_SCHEDULER) as client:
                v = Variable(name="var", client=client)
                f = v.get()

                if f.status == 'finished':
                    break
                else:
                    print('not finished')
                    time.sleep(1)``
`

**Comment by mrocklin** [comment]
When the client first creates a future it doesn't yet have the status of that future.  It may take a few milliseconds as the client asks the scheduler for more information.  In your example you immediately check the status of the future directly after getting it you'll find that the client doesn't yet know the status.  If you wait a few milliseconds you'll find that everything is fine.  

Here is an example that tests this timing by waiting on the future.

```python
In [1]: from dask.distributed import Client, Variable, wait

In [2]: import time

In [3]: def inc(x):
   ...:     return x + 1
   ...: 
   ...: def dummy(x):
   ...:     pass
   ...: 
   ...: def test_variables_2():
   ...:     with Client('localhost:8786') as client:
   ...:         L = client.map(inc, range(1000))
   ...:         f = client.submit(dummy, L)
   ...: 
   ...:         v = Variable(name="var", client=client)
   ...:         v.set(f)
   ...: 
   ...:         client.compute(f)
   ...: 
   ...:     while True:
   ...:         with Client('localhost:8786') as client:
   ...:             v = Variable(name="var", client=client)
   ...:             f = v.get()
   ...:             start = time.time()
   ...:             wait(f)
   ...:             end = time.time()
   ...:             print("Duration", end - start)
   ...:             print("Status", f.status)
   ...:             

In [4]: test_variables_2()
Duration 0.3927021026611328
Status finished
Duration 0.0009415149688720703
Status finished
Duration 0.0009622573852539062
Status finished
Duration 0.004920244216918945
Status finished
Duration 0.0009350776672363281
Status finished
Duration 0.0010135173797607422
Status finished
Duration 0.0009930133819580078
Status finished
Duration 0.0025153160095214844
Status finished
Duration 0.0008144378662109375
Status finished
Duration 0.003805875778198242
Status finished
Duration 0.002122163772583008
Status finished
Duration 0.002368450164794922
Status finished
Duration 0.0009746551513671875
Status finished
Duration 0.0007257461547851562
Status finished
Duration 0.0020928382873535156
Status finished
Duration 0.002156496047973633
Status finished
```

**Comment by danielb2814** [comment]
thanks! waiting a bit does indeed bring the latest state. I will test a bit more to make sure.

**Comment by mrocklin** [comment]
We could consider sending the current status of the future when the user gets the future.  This would save a millisecond or two (which is non-trivial for some applications) and would avoid tricky situations like this.

**Comment by danielb2814** [comment]
I agree. I would expect get() to wait until the future status is retrieved and then return. I am now waiting 0.1 seconds after the get() and everything works fine. Are there scenarios where the scheduler response can be delayed significantly? 

If waiting a defined amount of time is the suggested solution we can easily close this issue.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/1185
