### ISSUE TITLE
Questions around emptying and resuming channels

### ISSUE THREAD

**Issue by MathMagique** [dask/distributed#1205]
Hi! I have workflow that is expected to have some side effects such as writing results into a database. Scheduling the necessary jobs using the `Client` is easy enough, but I do not want to keep my Python script/web request/whatever uses the `Client` running for as long as it takes to compute all jobs.

The [documentation](http://distributed.readthedocs.io/en/latest/channels.html) suggests to create a `Channel` and to append any future worth doing (even when no "real" client seems to care). I did that, and it works as expected.

However, this leads to the channel raking up more and more futures.
* Am I assuming correctly that the results associated with these futures will be kept in memory/on disk around the cluster?
* I cannot find a way to empty a channel, e.g., via `channel.reset()` or something similar.
* When I tried to reset the whole cluster with `client.restart()`, I noticed that channels are not emptied. Instead, the stored futures are listed with `status: pending`.

I also used `channel.stop()` in the (false) hope that it would clean off its contents. I had to realize, though, that I can no longer `append()` to the channel, getting a weirdly used `StopIteration` exception I would otherwise expect from a `next()` method. 
* Is there a way to resume a channel?
* Even after resetting the cluster with `cluster.restart()`, the channel appears to be `stopped`.

**Comment by MathMagique** [comment]
_Side remark that does not answer any of the questions above, but provides an alternative solution to the use case_

In the meantime, I also found out about `client.publish_dataset()` and [related functions](http://distributed.readthedocs.io/en/latest/publish.html), which seems better for my use case.

**Comment by mrocklin** [comment]
Yeah, channels aren't perfect for this use case.  It would be nice to have a fire-and-forget option for tasks, but this doesn't yet exist.

For the moment you might try Queues, which are probably a bit more sensible than Channels.  Once someone pulls an element from the queue it leaves the queue entirely.  You could even set up a long-running task to pull from the queue constantly.

```python
def pull_from_queue(name):
    with worker_client() as c:
        q = Queue(name, client=c)
        while True:
            q.get()

future = client.submit(pull_from_queue, queue_name)
```

This is still a bit of a hack, but should result in better behavior.

**Comment by MathMagique** [comment]
After playing around some, I noticed two issues with your suggestion:
* The watcher would never shut down
* The watcher itself needs to be kept alive to do the cleanup. Otherwise, tasks are kept alive by the queue indefinitely.

I slightly modified your code and came up with the following:

```
from dask.distributed import worker_client, Queue, wait
from distributed.client import Future

QUEUE_NAME_WATCHED = "watch this"
QUEUE_NAME_WATCHER = "I am watching"
 
def task_watcher(watched_queue_name, watcher_queue_name):
    with worker_client() as client:
        queue = Queue(watched_queue_name, client=client)
        keep_going = True
        while keep_going:
            item = queue.get()
            if isinstance(item, Future):
                wait(item)
            else:
                # remove element from queue #2 so the watcher result is not kept alive indefinitely
                watcher_queue = Queue(watcher_queue_name, client=client)
                watcher_queue.get()
                keep_going = False
 
futures = [... many futures ...]
 
# tell watcher to watch these futures
watched_queue = Queue(QUEUE_NAME_WATCHED, client)
for future in futures:
    watched_queue.put(future)
# add termination signal
watched_queue.put("exit")
 
# start the watcher and keep it alive by second queue
watcher = client.submit(task_watcher, QUEUE_NAME_WATCHED, QUEUE_NAME_WATCHER, pure=False)
watcher_queue = Queue(QUEUE_NAME_WATCHER, client)
watcher_queue.put(watcher)
```

Above code uses one queue to hold references to the tasks that need to be done. Another queue holds watchers that clean up the first queue. When a "kill" signal is encountered in queue 1, the watcher will stop cleaning queue 1 and remove one element from queue 2.

It is still hacky, but executes all tasks and cleans up all tasks after everything is done. But one should pray that there are no exceptions in the watcher code ;-)

**Comment by mrocklin** [comment]
> But one should pray that there are no exceptions in the watcher code ;-)

Long term I think it would be reasonable to mark futures as fire-and-forget, which might be cleaner from a user perspective.  I hope to have time to take a look at this in the moderate future.
