### ISSUE TITLE
Quieting down workers started from command line

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1216]
Can we add a command line option in cli/dask-worker to pass along `silence_logs = logging.CRITICAL`? The workers always output log-level info unless I hack this into `dask_worker.py`:

    if nanny:
        kwargs = {'worker_port': worker_port, 'silence_logs': logging.CRITICAL}
        t = Nanny

**Comment by mrocklin** [comment]
Yes, this seems like a reasonable thing to add to all of the command line
utilities.

**Comment by pitrou** [comment]
@adamklein, have you seen https://distributed.readthedocs.io/en/latest/configuration.html ? Would it solve your issue without requiring a command-line option?

**Comment by adamklein** [comment]
@pitrou Yes this works for the scheduler, but can't figure out how to do something similar for the workers. Does it perhaps make sense to introduce a worker configuration yaml file?

**Comment by mrocklin** [comment]
@adamklein the config file affects all Dask processes that have access to it, including both workers and schedulers.  My guess is that you are running a scheduler locally so it sees your local config file.  

Generally when deploying I find it annoying to also distribute config files.  Passing around command line arguments is often more convenient.

**Comment by adamklein** [comment]
The confusion may be that I was testing with a LocalCluster. The regular cluster logging works as expected.

**Comment by mrocklin** [comment]
See the silence_logs=False keyword to LocalCluster
