### ISSUE TITLE
bokeh "counters" tab is different from others

### ISSUE THREAD

**Issue by caseyjlaw** [dask/distributed#1222]
It seems that one of the tabs in the new bokeh status layout has an ill-defined tab. The pages defined [here](https://github.com/dask/distributed/blob/040011a5196972f61d9a7c7ad26ec81bc6f066f5/distributed/bokeh/worker.py#L35) differ from others. They also refer to pages that do not exist.

**Comment by mrocklin** [comment]
Good catch.  We share the `Counters` page between both the worker and scheduler.  It looks like we currently import the function that makes the document when instead we should import the class and recreate the `counters_doc` function in scheduler.py with the correct `template`.
