### ISSUE TITLE
Erroring on workers applying method over large Dask df

### ISSUE THREAD

**Issue by kuanb** [dask/distributed#1225]
## Sumary of issue
As a Dask dataframe scales in size, the `apply` appears to encounter errors that cause the `compute()` process to fail.

## Caveats
I have yet to devise a deterministic method of reliably producing these errors. That said, I have attempted to document, in detail, the conditions under which these errors occur and have identified aspects in the ordering of operations that enable to the error/s to occur more frequently.

I still suspect that this may be user error (my fault), but having exhausted all options I can readily think of, I wanted to share on GH Issues over SO on the off chance that there are issues outside of my/the user's control at play.

![image](https://user-images.githubusercontent.com/6053396/27758128-6ac4bf58-5dc2-11e7-8c94-e43a3f6e1408.png)
The documentation exists here, in this [GDoc](https://docs.google.com/spreadsheets/d/1e4_0X9BxH3japLu7Ax2ZtHbgP3WZ6enpGHDnEPQZ2D4/edit?usp=sharing).

The example method exists [here](https://gist.github.com/kuanb/75282d1ebe7f7996a132950ed6f9d87c).
The example method can be run with the following command: `time python test_dask.py {integer_desired_row_count_for_dfs}`

# What we are doing
If you look at the reference script, this is what is happening: Given 2 dataframes holding within them a geometry on each row, we want to find the distance from each geometry on the left df to each geometry on the right. This is an `n*n` problem, in which the resulting possible pairs scales exponentially with the number of rows in a given dataframe.

In our example, each dataframe is of the same height. For the purposes of this example, we convert a WKT geometry into WKB format and store that on each row of each column, one for the left and one for the right. They are to represent a unique geometry for each row in each dataframe.

Next, we convert the left dataframe to a Dask df, and the right regular Pandas df we merge onto the left ([this line](https://gist.github.com/kuanb/75282d1ebe7f7996a132950ed6f9d87c#file-example_parallelized_dask_geometry_operation-py-L45)), as per item 1 in the Joins Performance Tips ([here](http://dask.pydata.org/en/latest/dataframe-performance.html#joins)). We perform this merge through the introduce of a throwaway column on both dataframes set to the same value (this creates all possible relations between each row on each side, which creates a new table that is as tall as the produce of the height of the right and left table).

Now that we have the tall table of unique IDs for each geometry and their WKB representations, we can apply a method over each row. We do so by first grouping by the left df's id. This is so that the result will include distances to all other geometries from the right df, grouped by each row from the left.

# Resources being used
20 workers, spread across for machines, each m4.xlarge EC2 instances. The scheduler is provisioned with the same resource type as well.

# The errors we are seeing
If you look at the reference Google spreadsheet, I've essentially started with smaller initial dataframes (e.g. 2000 rows) and worked my way up in size. Under methodology changes, I basically switched between passing the Shapely objects (interpreted geometry strings) into the Pandas dataframe prior to the `apply()` operation or, later, within the applied method (so it takes the WKB string and converts that into a Shapely geometry object for each geometry in each row of each possible combination from the two dataframes).

Some interesting things we have noted about the errors: The are always 12 rows long in the worker logs. 

Example 1 features a column (`geometry_from`) that should be a WKT or WKB (depending on the version of the script) instead being an integer that matches the id column). It would appear that maybe, somehow, the column was swapped or misapplied (?).

Example 2 is very curious because the 11th row is only partly printed (and this happens consistently) before being randomly truncated and yet the logs continue normally after that. 

Example 3 is the one that I've anecdotally noted happens most often (though not today with this example script). This one is particularly confused because the key error is thrown and passed through to the user in the traceback, but nothing is logged by the scheduler or any of the workers.

Example 5 occured later in the day and only started after we switched to WKB format from WKT. I found this one extra interesting because there is no way that the `geometry_from` column could possibly be a WKT format in this operation because we load it in and convert it to WKB format prior to populating the Pandas dataframe with it. So this makes me think there is some confusion or somehow the old jobs are being confused or preserved with current jobs? `client.restart()` was used to purge old processes from the cluster so I'd be interested to learn what was happening here.

#### Final notes
Dask: 0.15.0 Distributed: 1.17.1 OS: Ubuntu 16.04.2 LTS
Versioning across workers/scheduler/etc should not be an issue - deployed Docker containers, so a standardized environment.

**Comment by mrocklin** [comment]
Thank you for the detailed report @kuanb .  Can I ask you for a bit more information?

1.  Can you include the error that you get, both locally and on the worker?
2.  Are you using Python 2 or 3?
3.  How large are your individual partitions?  How long does it take to call `pickle.dumps` on one of those partitions?

**Comment by kuanb** [comment]
Thanks - Answers out of order to get the short ones in before the long answers.

2. Using Py 3.5.2

3. The # of partitions is calculated on each run via the following:
```nparts = math.ceil(float(desired_len * desired_len)/max_df_height)```

Where I have had `max_df_height` set to 50,000. The idea was that the tall, joined dataframe should be divided enough times such that (assuming even division) there would be no resulting "partition" dataframe > 50,000 rows in length.

1. Sorry - I included that for Example 3A/B.
For all the errors from our consolidated logs for the scheduler + workers are included in the tabs on the linked Google spreadsheet (here: https://docs.google.com/spreadsheets/d/1e4_0X9BxH3japLu7Ax2ZtHbgP3WZ6enpGHDnEPQZ2D4/edit?usp=sharing).

There are two typical traceback patterns from local logs (left hand name is the Docker container name), that appear to correlate with the logs from  Example 1 and 2:
```
worker_1      | distributed.utils - ERROR - Could not find dependent ('ddf', 156).  Check worker logs
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 223, in f
worker_1      |     result[0] = yield make_coro()
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
worker_1      |     value = future.result()
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
worker_1      |     raise_exc_info(self._exc_info)
worker_1      |   File "<string>", line 4, in raise_exc_info
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
worker_1      |     yielded = self.gen.throw(*exc_info)
worker_1      |   File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1156, in _gather
worker_1      |     traceback)
worker_1      |   File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
worker_1      |     raise value
worker_1      | ValueError: Could not find dependent ('ddf', 156).  Check worker logs
```

and below (both would log this 3 times, which I assume reflects the default 3 retries setting):


```worker_1      | distributed.client - WARNING - Client report stream closed to scheduler
worker_1      | distributed.utils - ERROR - ('_groupby_slice_apply-2bec150d0370fa3203c677310d6a00ed', 6)
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1146, in _gather
worker_1      |     st = self.futures[key]
worker_1      | KeyError: "('_groupby_slice_apply-2bec150d0370fa3203c677310d6a00ed', 6)"
worker_1      |
worker_1      | During handling of the above exception, another exception occurred:
worker_1      |
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 223, in f
worker_1      |     result[0] = yield make_coro()
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
worker_1      |     value = future.result()
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
worker_1      |     raise_exc_info(self._exc_info)
worker_1      |   File "<string>", line 4, in raise_exc_info
worker_1      |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
worker_1      |     yielded = self.gen.throw(*exc_info)
worker_1      |   File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1152, in _gather
worker_1      |     None)
worker_1      |   File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
worker_1      |     raise value
worker_1      | concurrent.futures._base.CancelledError: ('_groupby_slice_apply-2bec150d0370fa3203c677310d6a00ed', 6)```

Example 5 started happening consistently towards the end of my session yesterday:
```Traceback (most recent call last):
  File "test_dask.py", line 66, in <module>
    res = distances.compute()
  File "/usr/local/lib/python3.5/site-packages/dask/base.py", line 97, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1764, in get
    results = self.gather(packed)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1263, in gather
    direct=direct)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 489, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/dask/dataframe/core.py", line 3101, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dask/dataframe/groupby.py", line 142, in _groupby_slice_apply
    return g.apply(func)
  File "/usr/local/lib/python3.5/site-packages/pandas/core/groupby.py", line 694, in apply
    return self._python_apply_general(f)
  File "/usr/local/lib/python3.5/site-packages/pandas/core/groupby.py", line 698, in _python_apply_general
    self.axis)
  File "/usr/local/lib/python3.5/site-packages/pandas/core/groupby.py", line 1611, in apply
    res = f(group)
  File "test_dask.py", line 55, in calc
    gl = wkb_loads(grouped_df.iloc[0].geometry_from)
  File "/usr/local/lib/python3.5/site-packages/shapely/wkb.py", line 16, in loads
    return reader.read(data)
  File "/usr/local/lib/python3.5/site-packages/shapely/geos.py", line 401, in read
    self._reader, c_char_p(data), c_size_t(len(data)))
TypeError: bytes or integer address expected instead of MultiPolygon instance```

I should note that when we replaced all the workers with fresh instances, the error from Example 5 was no longer occurring. Note that the only operation I ran on these workers during the course of the day was that linked Gist from the initial post.

**Comment by kuanb** [comment]
I reread you request and realize I did not correctly answer your request to use `dumps()`.

I ran the below operation on the result of the join to provide some description of the partition dfs:

```
def get_size_of(partition_df):
    # do some operation
    return some_measurement

res = joined.map_partitions(get_size_of).compute()
print(res)
```

### Here are the results:
Note: I used a 2000 length dataframe to get results faster, ran one with 5500 and everything looks the same, can rerun all on larger set if desired, went with shorter for expediency.

Get length of each df:
```
0     50000
1     50000
2     50000
...
79     50000
```

Get time it takes to `dumps` each:
```
0     0.000134
1     0.000155
2     0.000125
3     0.000157
4     0.000084
5     0.000110
6     0.000085
7     0.000109
8     0.000098
9     0.000060
10    0.000171
...
79    0.000139
```

**Comment by mrocklin** [comment]
I gave this a quick run on my local machine.  Here are some side-observations and thoughts:

1.  Dask is wildly over-estimating the nbytes size of geometries-in-pandas-dataframes.  The dashboard shows 10's of GBs of expected memory use while the OS-level monitors are reporting a much smaller value. Dask's heuristics to estimate memory use definitely aren't well tuned for object dtype columns that aren't strings.
2.  It seems unfortunate to use this much compute power on what appears to be a smallish dataset.  The `calc` computation seems to take a very long time.  In your shoes I might look to see if there are ways to speed it up before resorting to distributed computing.

Most relevant to your problem at hand though, the `geos` operations are taking a very long time and are holding onto the GIL.  This combination is hard to deal with from a concurrency perspective.  This means that even though Dask runs them in separate threads they still stop the rest of Dask's communication machinery from listening in, handling requests, etc on other threads.  While running your tasks its as though the Dask worker completely disappears from the network, only to come back after the computation finishes.

You can observe this if you install the `crick` library (on conda-forge or PyPI), navigate to the diagnostic server for one of the Dask workers, and look at the `Counters` page.  Here is a screenshot from one of my local workers

![image](https://user-images.githubusercontent.com/306380/27770903-d9bb7e30-5f14-11e7-951e-d55623f364d5.png)

If you look towards the lower left you'll see the "tick duration" plot.  This should be a histogram tightly centered around 20ms, which is an internal heartbeat that dask server keeps to test for exactly this sort of situation.  You'll see that the x-range goes all the way up to 6s, meaning that there were some periods of up to six seconds when Dask wasn't able to check in with itself.  This has been known to cause issues in the past because various timeouts from other peers will fail out.  See the following issues for possible solutions in the general case (although your case is harder):

1.  https://github.com/dask/distributed/issues/1215
2.  https://github.com/dask/distributed/issues/1214
3.  https://github.com/dask/distributed/issues/1213

For GIL-holding functions though just about the only thing we can really do on the Dask side is to massively increase timeouts.  The real solution here is to get the underlying library (it looks like `shapely`/`geos` in this case) to release the GIL while calling into C.

cc'ing @pitrou who has looked at similar issues.  I don't think there is anything for him to do here explicitly, but I thought he might find seeing this problem in the wild of interest.

**Comment by mrocklin** [comment]
Also, to be clear, this is a guess and not definitive.  Long-GIL-holding functions have been known to cause behavior like this.  That does not mean that something else is not also going on.

**Comment by kuanb** [comment]
Thanks for the thorough follow up, @mrocklin - really appreciate it. One way I think I can test this is to drop the `groupby` and try to avoid these costly GeoSeries distance calculations and instead only ever measure the distance from one geometry to the other it is paired with.

I assume that this will reduce the amount of time we are tied up in a Shapely method (maybe that's misguided). I'll work on that and report back here - thanks again.

**Comment by mrocklin** [comment]
Yes, if my hypothesis is correct then your errors should go away if you can reduce the time you spend in any single call to `wkg_load`.

**Comment by jorisvandenbossche** [comment]
I think GeoPandas could easily release the GIL on geo-operations, once https://github.com/geopandas/geopandas/issues/430 is tackled (=vectorized geos wrapper). Up to that point, there is not much sense in releasing the GIL in geos/shapely, as each of those single operations are still wrapped in a python object / called in a python for loop in GeoPandas.

**Comment by mrocklin** [comment]
In this particular case the individual function call `geos.WKBReader().read(data)` held the GIL for multiple seconds.  This goes beyond being a performance issue and starts being a stability issue for Dask.  I don't think that this particular issue should be resolved withing GeoPandas.  It needs to be resolved in whichever library is calling down to `geos` on any function that takes a non-trivial amount of time.

**Comment by pitrou** [comment]
What is `geos`? Are we talking about https://github.com/grst/geos?

**Comment by mrocklin** [comment]
https://trac.osgeo.org/geos/

**Comment by mrocklin** [comment]
But more generally: "some compiled C library linked to from a Python library in an era before people really cared about multi-threading in Python."

**Comment by jorisvandenbossche** [comment]
@mrocklin Ah, didn't read the full issue here, and assumed it was about the "costly GeoSeries distance calculations". For this, I think what I said above holds as typically the individual geos calls for single geom-geom distance calculation will be fast, but if you do this many times in a python loop it becomes slow, for which releasing the gil in the fast single calls will not help (but not an expert in that). 
But for something like a reader that takes more time, it certainly makes sense!

**Comment by mrocklin** [comment]
When looking into geopandas I was happy to see you investigating vectorization.  Any thoughts on if this might be responsible for the slow serialization times with pickle and how easy this would be to fix is so?  See header comment in https://github.com/geopandas/geopandas/issues/461 for example.

**Comment by adamklein** [comment]
@mrocklin I tried your suggestions here following our discussion on https://github.com/dask/distributed/pull/1201, and am also seeing a long tail in this plot:

![image](https://user-images.githubusercontent.com/869232/27802775-de90e91a-5ff3-11e7-9230-3c4eddb1ac0e.png)

Something similar might perhaps be the root cause of my timeout issue.

**Comment by kuanb** [comment]
If anyone's curious, here's a variation of the original script that flips the apply and groupby steps to enable the Shapely distance operations to be performed on piecemeal components of the dataset rather than very large GeoPandas GeoSeries: https://gist.github.com/kuanb/aea0af9f9a980df91a65826d194d4952

The crux of the modification is here:
```
def calc_distances(row):
    from_geom = loads(row['geometry_from'])
    to_geom = loads(row['geometry_to'])

    # get an array of distances from the GeoSeries comparison
    d = to_geom.distance(from_geom)

    # udpate the original row and return it
    row['distance'] = d
    return row

def summarize_distances(grouped):
    return np.array(grouped['distance'].values)

distances = (all_unique
                .apply(calc_distances, axis=1, meta=all_unique.loc[0])
                .drop(['value_from', 'value_to', 'geometry_from', 'geometry_to'], axis=1)
                .groupby('id_from').apply(summarize_distances))
```

**Comment by kuanb** [comment]
I wanted to follow up on my above idea that, if the issue was the time consuming Shapely/distance operation that was occuring in the applied function (with GeoSeries resulting from the `groupby` operation), then removing the `groupby` step and simply performing distance calculations that were from only one geometry to another geometry would circumvent this issue. I also removed passing through Shapely objects in Pandas dataframes and instead pass through strings and load them as Shapely geometries in each rowwise operation.

Below is a snippet of that step (you can see the whole script in the above comment):

```
def calc_distances(row):
    from_geom = loads(row['geometry_from'])
    to_geom = loads(row['geometry_to'])

    # get an array of distances from the GeoSeries comparison
    d = to_geom.distance(from_geom)

    # udpate the original row and return it
    row['distance'] = d
    return row

def summarize_distances(grouped):
    return np.array(grouped['distance'].values)

distances = (all_unique
                .apply(calc_distances, axis=1, meta=all_unique.loc[0])
                .drop(['value_from', 'value_to', 'geometry_from', 'geometry_to'], axis=1))

print('Beginning computation...')
computed = distances.compute()
print('Computation completed.')
print(computed.head(10))
```

My assumption would be that the process would be slower but not encounter the same problem. I also avoided the groupby step completely and just wanted to see if the `apply()` step would be able to execute successfully. Unforatunately, 100,000,000 rows (two 10k long dataframes), that same "Could not find dependent" error returns. Here is the traceback, locally:

```
$ time python test_dask.py 10000

Partitions: 2000
Beginning computation...

distributed.utils - ERROR - Could not find dependent ('assign-8e22812327e097546d36918e3ff74c83', 1584).  Check worker logs
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
    raise value

ValueError: Could not find dependent ('assign-8e22812327e097546d36918e3ff74c83', 1584).  Check worker logs

Traceback (most recent call last):
  File "test_dask.py", line 63, in <module>
    computed = distances.compute()
  File "/usr/local/lib/python3.5/site-packages/dask/base.py", line 97, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1764, in get
    results = self.gather(packed)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1263, in gather
    direct=direct)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 489, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "/usr/local/lib/python3.5/site-packages/six-1.10.0-py3.5.egg/six.py", line 686, in reraise
    raise value

ValueError: Could not find dependent ('assign-8e22812327e097546d36918e3ff74c83', 1584).  Check worker logs
```

And here are those worker logs, below (attemped a few times on different workers, resulting in same error):
```
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: distributed.worker - ERROR - Worker stream died during communication: tcp://10.0.0.148:40972 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: Traceback (most recent call last): 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/comm/tcp.py", line 160, in read 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     frame = yield stream.read_bytes(length) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     value = future.result() 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     raise_exc_info(self._exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "<string>", line 4, in raise_exc_info 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: tornado.iostream.StreamClosedError: Stream is closed 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: During handling of the above exception, another exception occurred: 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: Traceback (most recent call last): 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/worker.py", line 1589, in gather_dep 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     who=self.address) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     value = future.result() 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     raise_exc_info(self._exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "<string>", line 4, in raise_exc_info 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     yielded = self.gen.throw(*exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/core.py", line 475, in send_recv_from_rpc 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     result = yield send_recv(comm=comm, op=key, **kwargs) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     value = future.result() 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     raise_exc_info(self._exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "<string>", line 4, in raise_exc_info 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     yielded = self.gen.throw(*exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/core.py", line 310, in send_recv 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     response = yield comm.read() 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     value = future.result() 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     raise_exc_info(self._exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "<string>", line 4, in raise_exc_info 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     yielded = self.gen.throw(*exc_info) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/comm/tcp.py", line 166, in read 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     convert_stream_closed_error(e) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:   File "/usr/local/lib/python3.5/site-packages/distributed/comm/tcp.py", line 104, in convert_stream_closed_error 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates:     raise CommClosedError("%s: %s" % (exc.__class__.__name__, exc)) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: distributed.comm.core.CommClosedError: ConnectionResetError: [Errno 104] Connection reset by peer 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: distributed.worker - INFO - Can't find dependencies for key ('apply-e2822a499b43efe00d82019c048e976d', 53) 
Jul 05 12:00:37 ip-10-0-0-140 youthful_gates: distributed.worker - INFO - Dependent not found: ('assign-8e22812327e097546d36918e3ff74c83', 53) 2 .  Asking scheduler 
```

**Comment by jakirkham** [comment]
@kuanb, is this still an issue? If so, it would be good to know where things stand with a recent version of Dask + Distributed.

**Comment by kuanb** [comment]
@jakirkham thanks for checking in. I think we can close this. The work expanded beyond this ticket and involved a work on a separate branch of geopandas. I'll close this ticket.
