### ISSUE TITLE
Accept unicode or byte string keys on streams

### ISSUE THREAD

**Issue by nicoleepp** [dask/distributed#1230]
It would be great if the dask.distributed scheduler could accept byte or unicode keys and not just strings of type `str` as checked by `validate_key`.

This issue came up while integrating the dask.distributed scheduler with julia client/workers in https://github.com/invenia/DaskDistributedDispatcher.jl, since julia msgpack will encode strings as either byte strings or unicode strings. Currently, this integration will not be able to support python 3.5 since it adds a `bytes` class. Python 2 works since it treats byte strings as `str` types.

Sample error when using python 3.5:
```distributed.scheduler - ERROR - Unexpected key type <class 'bytes'> (value: b'Int64-4635863187378904022')```

**Comment by mrocklin** [comment]
Sure. I'll take a look at this tomorrow.   Thanks for bringing it up.  Is
there anything else we can do to assist Invenia?

**Comment by mrocklin** [comment]
I threw up an experimental PR here: https://github.com/dask/distributed/pull/1234

We'll see if anything breaks.  You might also consider resolving this on the Julia side.  Python's msgpack library added text-as-text a few years ago.  Msgpack itself apparently extended it's spec to include this.

**Comment by iamed2** [comment]
@mrocklin How about unicode keys? 

The `String` type in Julia is a unicode string, which would map to `unicode` in Python 2. Right now we use `String` in Julia in most cases except when dealing with `dask.distributed` keys, where we need to use byte arrays (ends up being an opaque `Vector{UInt8}` type). We can get this efficiently without copies but having byte arrays around instead of strings still makes the code harder to read and harder to debug.

**Comment by mrocklin** [comment]
First, have you considered just using Python 3?  Python 2 is near end-of-life.

**Comment by mrocklin** [comment]
Alternatively, you might submit a PR similar to #1234 that supports unicode keys in Python 2.  If it doesn't impact performance then I would have no issue merging such a PR.  I personally though am somewhat slammed.

**Comment by iamed2** [comment]
I tried in https://github.com/dask/distributed/pull/1328 but a bunch of tests started freezing
