### ISSUE TITLE
When Client imported a second time, calls to create Client hang

### ISSUE THREAD

**Issue by radiantone** [dask/distributed#1245]
Version 1.17.1

I finally found the hang situation I've been experiencing off and on. Dask 0.15.1

If I have these statements in a module.

from distributed import Client

c = Client("localhost:8786")
print c

then in a separate module, I have them again. The second call to "c = Client(....)" will hang indefinitely.
I then reduced this to just calling the import twice, then creating Client will hang.
Try this:
from distributed import Client
from distributed import Client
c = Client("localhost:8786")
print c

Is this expected behavior? Is the distributed module re-entrant?

**Comment by radiantone** [comment]
Here is a test that I can reproduce. It consists of two files: test1.py and test2.py

test1.py

`from distributed import Client
print "Creating first client"
# In fact, you don't even need to execute these two lines for the deadlock to occur
#c = Client("localhost:8786")
#print "First:",c

import test2
`

test2.py

`from distributed import Client
print "Creating second client."
c = Client("localhost:8786")
print "Second:",c
`

**Comment by mrocklin** [comment]
```
mrocklin@carbon:~$ cat test1.py 
from distributed import Client
import test2
mrocklin@carbon:~$ cat test2.py 
from distributed import Client
print("Creating client.")
c = Client("localhost:8786")
print("Client:", c)
mrocklin@carbon:~$ python test1.py 
Creating client.
Client: <Client: scheduler='tcp://localhost:8786' processes=0 cores=0>
mrocklin@carbon:~$ 
```

Can you verify that you have a scheduler running on `localhost:8786`?

**Comment by radiantone** [comment]
Yes. It's running. If I try to create a client in test1.py module it works fine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by radiantone** [comment]
In one terminal window, I run dask-scheduler in fresh virtualenv 'dask':

± |0.1.0 S:1 U:27 ?:2 ✗| → dask/bin/dask-scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:  tcp://192.168.1.249:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-HhSTif
distributed.scheduler - INFO - -----------------------------------------------

In separate window, I run my test, it hangs, then I hit ctrl-C

± |0.1.0 S:1 U:27 ?:2 ✗| → ../../../dask/bin/python test1.py 
Creating second client.
^CTraceback (most recent call last):
  File "test1.py", line 4, in <module>
    import test2
  File "/home/radiant/radiantfind/dockers/test/test/test2.py", line 5, in <module>
    c = Client("localhost:8786")
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/client.py", line 494, in __init__
    self.start(timeout=timeout)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/client.py", line 617, in start
    sync(self.loop, self._start, **kwargs)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 232, in sync
    e.wait(1000000)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
distributed.utils - ERROR - 'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/client.py", line 680, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/radiant/radiantfind/dask/local/lib/python2.7/site-packages/distributed/client.py", line 716, in _ensure_connected
    yield self.scheduler.identity()
AttributeError: 'NoneType' object has no attribute 'identity'

**Comment by radiantone** [comment]
I spawned a fresh ubuntu server in EC2 and created virtualenv and repeated above steps thinking maybe my system might be affecting this. Same result.

Last login: Sun Jul  9 23:23:56 2017 from 71.191.83.168
ubuntu@ip-10-186-18-141:~$ dask/bin/dask-scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:  tcp://10.186.18.141:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-4EtKTp
distributed.scheduler - INFO - -----------------------------------------------

.....

Last login: Sun Jul  9 23:23:59 2017 from 71.191.83.168
ubuntu@ip-10-186-18-141:~$ cp /tmp/test* .
ubuntu@ip-10-186-18-141:~$ dask/bin/python test1.py 
Creating second client.

*hangs*

**Comment by mrocklin** [comment]
Hrm interesting.  I *can* reproduce this on Python 2.  I tracked it down to the `tornado.TCPClient.connect` call in `distributed/comm/tcp.py` but am not sure why that's hanging.  This doesn't even seem to respond to a timeout

**Comment by radiantone** [comment]
I can try reverting back a few versions of Tornado.

**Comment by radiantone** [comment]
I tried various prior versions of tornado. Same result. However, 4.2.1 was the farthest back I could go and it still run. In that version, the dask-scheduler DOES show the client connection message, but the test1.py code still hangs. In tornado 4.5.1 I don't see the client connect message in dask-scheduler. HTH

**Comment by radiantone** [comment]
@mrocklin  Do you think there is a temporary workaround for this issue?

**Comment by mrocklin** [comment]
I don't currently know of a workaround.  I apologize I haven't had the time to look into this more deeply.
