### ISSUE TITLE
Allow worker client timeout configuration from command line

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1247]
Currently `worker_client` takes a `timeout` parameter that isn't used.  If my understanding is correct, `Client` has a default timeout of `timeout=5`, and when you launch a worker via command line (ie, via `cli/dask_worker.py`) you don't have access to change this timeout parameter. It would be great to be able to set it from the command line, and/or change this value in code at runtime.

**Comment by mrocklin** [comment]
I think that worker_client's timeout parameter is now used properly.  Can this be closed?
