### ISSUE TITLE
Unable to affect logging threshold from using configuration file

### ISSUE THREAD

**Issue by rcthomas** [dask/distributed#1257]
I am trying to adjust the logging threshold via the configuration file but I find that it does not seem to change the reporting level.  That is, I can set

    logging:
        distributed: critical

but I still see `INFO` messages from my scheduler, workers, etc.  Also, if I set the threshold to `DEBUG` I don't seem to see any messages from that level.  It does not matter if I set `distributed: critical` as above or explicitly set various `distributed.*` thresholds.

In all cases my application does everything else that I want, creates results, etc.  It's just the logging doesn't seem to respond to my configuration adjustments.

This happens if I place the configuration file in the default location, `~/.dask/config.yaml` and also if I set `DASK_CONFIG=$HOME/.dask/config.yaml`.  

This happens using Distributed 1.18.0 with Dask 0.15.1; my setup is a fresh Miniconda Python 3.6 install on Linux.  Suggestions on anything I should do to test/provide more info?

**Comment by rcthomas** [comment]
Silly me.  https://github.com/dask/distributed/blob/master/distributed/config.py#L136

**Comment by mrocklin** [comment]
Hrm, should we warn on this?

**Comment by rcthomas** [comment]
In the end it was a fairly obvious thing missing on my part, but I was imagining much more complicated reasons for why logging and configurations weren't working until I got a chance to take a deeper look.  A warning would have got me back on track much sooner, so I'd say yes.
