### ISSUE TITLE
Starting up web diagnostics in ipyparallel-based Dask Distributed cluster

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1268]
This is an issue of incomplete functionality when starting Dask Distributed on top of ipyparallel. Namely how to startup Bokeh and connect it to the Dask Distributed cluster. The code that does this in Dask Distributed is [here]( https://github.com/dask/distributed/blob/1.18.0/distributed/cli/dask_scheduler.py#L125-L132 ). This code in question could be copied over to ipyparallel. Though I guess there is a reasonable question as to whether this is really an implementation detail of Dask Distributed, which ipyparallel shouldn't get involved with. In this case, adding an API for it or adding it into an existing API would solve it. Opening the issue here to resolve where and how this should be fixed.

cc @mrocklin @minrk

**Comment by mrocklin** [comment]
I'm inclined to fix it in ipyparallel.  We tend to decide which sevices to add on a case-by-case basis based on the deployment strategy.  

The code to which @jakirkham has linked seems like the right logic to copy over if the Bokeh diagnostic servers are desired when running from `ipyparallel`

**Comment by jakirkham** [comment]
Any thoughts on this @minrk?

**Comment by minrk** [comment]
Adding an arg, or other passthrough stuff to ipyparallel makes sense to me.

**Comment by jakirkham** [comment]
Thanks @minrk. Could you please point out to me where you think the port should be specified for the Bokeh diagnostic viewer?

**Comment by GenevieveBuckley** [comment]
> I'm inclined to fix it in ipyparallel. We tend to decide which sevices to add on a case-by-case basis based on the deployment strategy.
> 
> The code to which @jakirkham has linked seems like the right logic to copy over if the Bokeh diagnostic servers are desired when running from `ipyparallel`

Ok then, I'll close this issue. Discussions can be moved over to [ipyparallel](https://github.com/ipython/ipyparallel).
