### ISSUE TITLE
dask-worker on ec2 instances connecting to scheduler outside ec2

### ISSUE THREAD

**Issue by bansalr** [dask/distributed#1281]
I would like to run dask-workers on ec2 instances as compute needs scale. The workers connect to a scheduler running on an non ec2 machine. 

The dask-workers see their ip as the internal ec2 ip. They connect to the scheduler running on the non-ec2 machine. However the workers specify their internal ec2 ip to the scheduler. The scheduler than tries to connect back on that internal ip which of course is not visible outside ec2. Confusion ensues.

The dask-ec2 program runs the scheduler internal to ec2. Any pointers way to solve this situation - scheduler running on an non-ec2 machine but workers running on ec2 instances - would be greatly appreciated. 

The goal here is to scale workers (on ec2) as compute needs scale by bringing up more instances.

Thanks!

**Comment by mrocklin** [comment]
You can specify the hostname by which the workers can identify themselves with the `--host` keyword.

More generally you can specify the network interface that the workers should use using the `--interface` keyword.  I would log onto an ec2 node, run `ifconfig` and try to find the external network interface and then add that flag when calling dask-worker

Here is the help string for reference

```
mrocklin@carbon:~$ dask-worker --help
Usage: dask-worker [OPTIONS] [SCHEDULER]

Options:
  --tls-ca-file PATH            CA cert(s) file for TLS (in PEM format)
  --tls-cert PATH               certificate file for TLS (in PEM format)
  --tls-key PATH                private key file for TLS (in PEM format)
  --worker-port INTEGER         Serving computation port, defaults to random
  --http-port INTEGER           Serving http port, defaults to random
  --nanny-port INTEGER          Serving nanny port, defaults to random
  --bokeh-port INTEGER          Bokeh port, defaults to 8789
  --bokeh / --no-bokeh          Launch Bokeh Web UI  [default: True]
  --host TEXT                   Serving host. Should be an ip address that is
                                visible to the scheduler and other workers.
                                See --interface.
  --interface TEXT              Network interface like 'eth0' or 'ib0'
  --nthreads INTEGER            Number of threads per process.
  --nprocs INTEGER              Number of worker processes.  Defaults to one.
  --name TEXT                   A unique name for this worker like 'worker-1'
  --memory-limit TEXT           Number of bytes before spilling data to disk.
                                This can be an integer (nbytes) float
                                (fraction of total memory) or 'auto'
  --reconnect / --no-reconnect  Reconnect to scheduler if disconnected
  --nanny / --no-nanny          Start workers in nanny process for management
  --pid-file TEXT               File to write the process PID
  --local-directory TEXT        Directory to place worker files
  --resources TEXT              Resources for task constraints like "GPU=2
                                MEM=10e9"
  --scheduler-file TEXT         Filename to JSON encoded scheduler
                                information. Use with dask-scheduler
                                --scheduler-file
  --death-timeout FLOAT         Seconds to wait for a scheduler before closing
  --bokeh-prefix TEXT           Prefix for the bokeh app
  --preload TEXT                Module that should be loaded by each worker
                                process like "foo.bar" or "/path/to/foo.py"
  --help                        Show this message and exit.
```

**Comment by bansalr** [comment]
Hi Matt, 
Thanks for the quick response.

I tried the --host and --interface, each and together. I tried to give it the public DNS name of the ec2 instance and the public ip.


Unfortunately, ec2 configuration does not allow this. The machine has the following ifconfig:

ens3      Link encap:Ethernet  HWaddr 02:af:62:2f:d9:43  
          inet addr:172.31.6.150  Bcast:172.31.15.255  Mask:255.255.240.0
          inet6 addr: fe80::af:62ff:fe2f:d943/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:629936 errors:0 dropped:0 overruns:0 frame:0
          TX packets:90485 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:910064408 (910.0 MB)  TX bytes:10210973 (10.2 MB)
(in addition to the loopback)

If I give it the public ip (54.xxx) then the worker tries to bind to that address and fails.
If I give it the public DNS name, on the ec2 network it resolves to the internal ip on which the worker is able to bind but when the worker connects to the scheduler and provides the internal ip, the scheduler of course cannot see.

Using the --interface has the same effect.  Clearly this is an ec2 peculiarity but GCE also has the same setup. 

We are mulling a solution with setting up an iptables rule but that is a ugly kludge or move the scheduler to an ec2 machine.

**Comment by mrocklin** [comment]
If you provide host or interface then the worker should report that address rather than its internal IP.

I am surprised that ifconfig has only a single entry.  I would expect a couple of entries, one for each network.

**Comment by bansalr** [comment]
This is the ec2 networking setup (believe it is similar for GCE and Azure but not confirmed):

[Public IPv4 Addresses and External DNS Hostnames
](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html)

> A public IP address is an IPv4 address that's reachable from the Internet. You can use public addresses for communication between your instances and the Internet.
> 
> Each instance that receives a public IP address is also given an external DNS hostname; for example, ec2-203-0-113-25.compute-1.amazonaws.com. We resolve an external DNS hostname to the public IP address of the instance outside the network of the instance, and to the private IPv4 address of the instance from within the network of the instance. The public IP address is mapped to the primary private IP address through network address translation (NAT). For more information about NAT, see RFC 1631: The IP Network Address Translator (NAT).

Now instead of giving it the hostname we give it the external IP but the worker is not able to bind to the external_ip:port on that machine since no interface exists with that IP. We could theoretically setup an firewall rule on that box but thats again kludgy. 

dask_scheduler could have an option to use the src address on the inbound worker connection to connect to _or_ the worker would have an option for an address to report to the scheduler but another address to bind on. Both are unsavory.

**Comment by mrocklin** [comment]
This is perhaps similar to the solution proposed in https://github.com/dask/distributed/pull/1278

**Comment by bansalr** [comment]
Thanks, Matt, I believe that would fix it, we will try it and report back.

**Comment by mrocklin** [comment]
This seems to be resolved
