### ISSUE TITLE
Non-deterministic task failure

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1300]
I don't, unfortunately, have a reproducible cut down example.

I have been experiencing intermittent task failures. The tasks themselves are deterministic, and so the failures are likely coming from some combination of dask-distributed, network environment, etc., and the error on the worker supports that idea.

Log extracts:
**Client logs**
```
distributed.client 2017-07-31 21:06:47 WARNING Couldn't gather keys {'pricer-74704d1e3fa1d866d1e23d9c9e4c9d04': ['tls://[redacted ip]:7971']}
distributed.client 2017-07-31 21:06:47 WARNING Couldn't gather keys {'pricer-74704d1e3fa1d866d1e23d9c9e4c9d04': ['tls://[redacted ip]:7971']}
```

**Worker logs**
```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10af3adb8>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/tcpserver.py", line 298, in <lambda>
    lambda f: f.result())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/comm/tcp.py", line 380, in _handle_stream
    address, self.contact_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/comm/tcp.py", line 408, in contact_address
    host, port = self.get_host_port()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/comm/tcp.py", line 389, in get_host_port
    self._check_started()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/comm/tcp.py", line 370, in _check_started
    raise ValueError("invalid operation on non-started TCPListener")
ValueError: invalid operation on non-started TCPListener
```

**Scheduler logs [Time codes off by an hour versus client]**
```
"Jul 31 20:06:14 instance-1 user: distributed.scheduler - INFO - Receive client connection: Client-b49678b5-762b-11e7-9739-406c8f10bf84" 
Jul 31 20:06:47 instance-1 user: distributed.scheduler - INFO - Remove worker tls://[redacted ip]:7971"  
"Jul 31 20:06:47 instance-1 user: distributed.scheduler - INFO - Removed worker tls://[redacted ip]:7971" 
Jul 31 20:06:47 instance-1 user: distributed.scheduler - ERROR - Workers don't have promised keys. This should never occur"  
Jul 31 20:06:47 instance-1 user: None
Jul 31 20:07:34 instance-1 user: distributed.comm.tcp - WARNING - Closing dangling stream in <TLS local=tls://10.154.0.2:47120 remote=tls://[redacted ip]:7971>
```
These task failures happen to about 10% of tasks. Curiously (and presumably relevantly), when I was inadvertently loading some threading code in the worker (a logger with a logutils.queue QueueHandler), failures shot up to around 80%. Hopefully this will suggest a potential cause to someone familiar with the relevant part of the distributed code?

Versions:
Python 2.7
dask==0.15.1
distributed==1.18.0 on client/worker
tornado==4.5.1

**Comment by mrocklin** [comment]
Can you say more about the kinds of features that you are using in Dask?  Dask.dataframe, the futures interface, get_client,etc..?

Can you try updating to distributed master and see if the problems persist.

**Comment by rbubley** [comment]
The dask features I'm using is just the simple futures interface, (no dask data structures, no worker-generated sub tasks or anything fancy), specifically using Client.map, as_completed, Client.gather and a few operations on the futures.

**Comment by mrocklin** [comment]
Were you able to test this on distributed master?

**Comment by rbubley** [comment]
Tried it with master (1.18.0+24.g89d10f5). I'm still seeing the problem, but now am getting warnings about long-running GIL-holding functions causing timeouts and instability. Maybe this is behind the problems I am seeing.

Incidentally, I have heterogenous workers, some MacOS and some Debian. For whatever reason, the problem only rears its head on the MacOS workers.

**Comment by mrocklin** [comment]
Perhaps the software environments are not identical?  Can you run `client.get_versions(check=True)`?

**Comment by rbubley** [comment]
The software environments aren't identical, but I don't think this is it:

1. Some of the workers are running a slightly different version of distributed (they have a #1278 cherry-pick.)
2. The client has numpy installed (but unused for this project) - neither scheduler nor worker have it installed.

I am still trying to fix the GIL-holding functions, and will see after that if the problem has gone away.

**Comment by mrocklin** [comment]
(Note that #1278 has been merged and included in the latest release)

**Comment by mrocklin** [comment]
Any updates on this?

**Comment by rbubley** [comment]
Since removing the GIL-holding functions, I haven't seen this problem. It may be that there is some race condition that doesn't rear its head in the absence of a GIL-holding function.
