### ISSUE TITLE
Non-deterministic double-scheduling of tasks?

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1305]
I was surprised by this behavior - is it intended? (This is running as of commit 3069df08787b8f262f2bfd43d7aa5690e6a186d8)

test.py:

	def print_statement(x):
		print("Got {}".format(x))
		return x

	def outer_runner(x):
		with worker_client() as client:
			futs = [client.submit(print_statement, i) for i in range(x)]
			results = client.gather(futs)
			return results

	def test_dask_double_schedule(cluster):
		with Client(cluster) as client:
			results = client.submit(outer_runner, 120).result()
			assert len(results) == 120

	if __name__ == '__main__':
		with LocalCluster(n_workers=6) as cluster:
			test_dask_double_schedule(cluster)

Then from command line:

	 $ for i in {1..10}; do ipython test.py | grep -c "Got"; done                                        
	120                                    
	120                                    
	120                                    
	140    # wat!?                                   
	120                                    
	120     

I thought it might be the `pure=True` param, but this doesn't have an effect (here it is with `pure=False`):

	$ for i in {1..10}; do ipython test.py | grep -c "Got"; done
	120
	120
	120
	120
	120
	120
	120
	120
	120
	139	# wat!?

**Comment by mrocklin** [comment]
This is my experience:

```
mrocklin@carbon:~/workspace/play$ python gh1305.py 
Got 6
Got 1
Got 0
Got 2
Got 3
Got 4
Got 5
Got 117
Got 118
Got 57
Got 53
Got 82
Got 28
Got 29
Got 93
Got 77
Got 75
Got 9
Got 103
Got 12
Got 74
Got 43
Got 25
Got 84
Got 60
Got 58
Got 72
Got 19
Got 83
Got 15
Got 54
Got 92
Got 63
Got 80
Got 24
Got 23
Got 52
Got 20
Got 99
Got 78
Got 17
Got 109
Got 38
Got 32
Got 89
Got 85
Got 33
Got 49
Got 27
Got 13
Got 34
Got 97
Got 68
Got 44
Got 51
Got 98
Got 104
Got 88
Got 64
Got 101
Got 48
Got 105
Got 69
Got 26
Got 73
Got 110
Got 113
Got 79
Got 106
Got 8
Got 11
Got 90
Got 114
Got 108
Got 119
Got 76
Got 116
Got 67
Got 18
Got 111
Got 102
Got 61
Got 95
Got 62
Got 56
Got 70
Got 14
Got 7
Got 21
Got 55
Got 39
Got 87
Got 96
Got 115
Got 59
Got 112
Got 41
Got 107
Got 94
Got 22
Got 16
Got 66
Got 47
Got 81
Got 86
Got 37
Got 71
Got 42
Got 91
Got 10
Got 36
Got 31
Got 35
Got 46
Got 65
Got 100
Got 50
Got 40
Got 30
Got 45

mrocklin@carbon:~/workspace/play$ cat gh1305.py 
from dask.distributed import Client, LocalCluster, worker_client

def print_statement(x):
	print("Got {}".format(x))
	return x


def outer_runner(x):
	with worker_client() as client:
		futs = [client.submit(print_statement, i) for i in range(x)]
		results = client.gather(futs)
		return results


def test_dask_double_schedule(cluster):
	with Client(cluster) as client:
		results = client.submit(outer_runner, 120).result()
		assert len(results) == 120


if __name__ == '__main__':
	with LocalCluster(n_workers=6) as cluster:
		test_dask_double_schedule(cluster)
```

**Comment by adamklein** [comment]
Looks like you can make it occur more often by doing this:

    def print_statement(x):
        import time
        import random
        time.sleep(random.random())
        print("Got {}".format(x))
        return x

**Comment by adamklein** [comment]
@mrocklin I see 120 lines there. So you're not getting a repro? If you put in the `sleep` as above, and loop through it maybe 20 times, you still always get 120?

**Comment by mrocklin** [comment]
With the added sleeps:

    mrocklin@carbon:~/workspace/play$ python gh1305.py  | wc -l
    123

The repetition is probably load balancing towards the end.  Dask currently feels free to run the same function multiple times.

**Comment by adamklein** [comment]
Ok, but if it's an impure function, are we sure we want to do that? Would it be possible to disable that through configuration?

**Comment by mrocklin** [comment]
If you're depending on side effects and need exactly once execution then no, we don't want to do this.  At the moment the Dask scheduler doesn't support this kind of operation.  We generally encourage people to use idempotent functions or functions without side effects.  This could change somewhat, but it would be yet-another-addition to the scheduler.

**Comment by xwang777** [comment]
I was also very frustrated by this duplicated task executions. I think the problem is due to non-atomic work stealing, as reported elsewhere (like https://github.com/dask/distributed/issues/847). I also bumped into frequent memory overrun problems. They're both related to the aggressive task scheduling and task stealing. 

In the end, I worked around both problems by keeping the running tasks to a limited number (e.g. same as number of cores). See https://stackoverflow.com/questions/45597047/nested-dask-compute-not-blocking/45622387#45622387. I'm not sure it'll guarantee to solve the duplicate execution problem, but so far I have not observed it anymore, I suppose task stealing does not run when each worker process has exactly one task to work with. 

I see the motivation of aggressive task scheduling, as explained in https://github.com/dask/distributed/issues/711, but IMHO lots of data engineering tasks need to write files or update DB, multiple concurrent runs is very counter-productive and should be avoided. These tasks also tend to be slow running jobs that take minutes to run, so the benefit of flooding workers with tasks seems to be negligible.

**Comment by mrocklin** [comment]
@xwang777 see https://github.com/dask/distributed/pull/1325 where we provide a config option to turn off work stealing.

**Comment by xwang777** [comment]
@mrocklin Thanks for your change. I'm still busy crunching through my data to get my day job done, but will try out the new option when having a chance.

**Comment by adamklein** [comment]
Can you apply this to a LocalCluster instance? If so, how? Otherwise, think we can close this out -

**Comment by mrocklin** [comment]
The config file is respected regardless of if you run with LocalCluster or `dask-foo`.  Is that the change that you are referring to?

**Comment by adamklein** [comment]
Closing as fixed - work stealing doesn't double-schedule any more...

**Comment by mrocklin** [comment]
Hooray!

**Comment by xwang777** [comment]
Super! Thanks for all the great work.
