### ISSUE TITLE
OOMKill of ipython kernel results in orphaned processes

### ISSUE THREAD

**Issue by pwaller** [dask/distributed#1322]
I'm using jupyter-notebook 5.0.0, ipython 6.1.0. Python3.5.1, distributed 1.18.0 and dask `0.15.1+33.gaafeedc`.

I'm working on fairly large datasets which I expect to graze the RAM ceiling. Under various circumstances, my ipython kernel crashes (for example, during an OOM).

This leaves me in a state with ~2 python processes per CPU core, e.g:

```
~$ ps aux | grep 8691
pwaller   8691  0.3  0.2 573092 41156 ?        Sl   12:47   0:14 /usr/bin/python3 -B -c from multiprocessing.forkserver import main; main(77, 85, ['distributed', 'pkg_resources'], **{'sys_path': [...]})
```

In sum, they remain taking 10GiB of resident memory indefinitely. I'm regularly finding myself in this situation of having to kill these processes. Is this normal?

Clearly, I also need to figure out why the kernel is crashing in the first place (it's OOMing, but why is still a mystery to me), but I do have an expectation that if it crashes there aren't large amounts of resources left tied up in this way.

Another key problem with this is that it is not clear that these resources are still tied up except that it results in more OOMs when I try to continue my analysis later (or unless I keep my eye on the memory usage constantly).

Apologies if I missed something obvious in the documentation.

**Comment by mrocklin** [comment]
cc @pitrou any thoughts on this (sorry to rely on you a bit lately)

**Comment by pitrou** [comment]
> This leaves me in a state with ~2 python processes per CPU core, e.g:

That sounds expected. It it not obvious for a child process to get notified when the parent dies, and there's no solution that I can immediately think of.

**Comment by mrocklin** [comment]
@pwaller you say that you have two subprocesses attached to a local IPython process.  Does this mean that you're using the local cluster, such as with `client = Client()`?

**Comment by pwaller** [comment]
@pitrou 
> It it not obvious for a child process to get notified when the parent dies, and there's no solution that I can immediately think of.

Two ideas:

* Pass a pipe to the child, have the child do a blocking read from the pipe (nothing ever writes). When the read completes, this indicates the parent process has gone, because there are no remaining writers on the write side.

* On Linux, `prctl(PR_SET_PDEATHSIG, ...)` in when the child starts can set a signal that the child receives when the parent exits. This does leave a race condition open between child start and calling `prctl`, though, and it's not portable. It does have an advantage that you can have the child process be killed at the same point in time as the parent, rather than having to wait for it to be scheduled, but this seems minor in our case.


---

@mrocklin 
> @pwaller you say that you have two subprocesses attached to a local IPython process. Does this mean that you're using the local cluster, such as with client = Client()?

Yes.

**Comment by mrocklin** [comment]
> Pass a pipe to the child, have the child do a blocking read from the pipe (nothing ever writes). When the read completes, this indicates the parent process has gone, because there are no remaining writers on the write side.


There appear to already be a couple of `multiprocessing.Queue` objects alive in the Nanny/Worker relationship.  I wonder if one of them could be reused for this.

@pwaller is this something that you're able to investigate and perhaps provide a small PR for?

**Comment by mrocklin** [comment]
@pwaller can we now close this?
