### ISSUE TITLE
Memory leaks during testing

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1323]
Our test suite seems to be leaking memory this is problematic both for running tests on travis-ci, which is somewhat memory constrained, and because it may imply a larger issue within Dask.  Leaks occur in two types:

1.  We seem to leak about a megabyte per test.  I suspect that this is just the scheduler hanging around.  To resolve this we would probably need to avoid all circular references.  The cost-to-benefit ratio here is somewhat high, especially because it is rare to create and destroy schedulers in practice.
2.  Some tests leak data. I think that this especially happens when repeated computation occurs due to work stealing.  A good example of this follows below:

```python
@gen_cluster(client=True, ncores=[('127.0.0.1', 1)] * 10)
def test_steal_when_more_tasks(c, s, a, *rest):
    s.extensions['stealing']._pc.callback_time = 20
    x = c.submit(mul, b'0', 100000000, workers=a.address)  # 100 MB
    yield _wait(x)
    s.task_duration['slowidentity'] = 0.2

    futures = [c.submit(slowidentity, x, pure=False, delay=0.2)
                for i in range(20)]
    yield gen.sleep(0.1)

    assert any(w.task_state for w in rest)
```
```
$ py.test  distributed/tests/test_steal.py::test_steal_when_more_tasks
distributed/tests/test_steal.py::test_steal_when_more_tasks
  /home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 1035 MB of memory
====================================== 1 passed, 1 warnings in 4.26 seconds =======================================
```

**Comment by mrocklin** [comment]
@pitrou if you have time, this issue has me concerned.  I wasn't able to track down the underlying issue after some time yesterday.

**Comment by pitrou** [comment]
> Our test suite seems to be leaking memory

By construction running the test suite will load more and more modules (the test modules but also the modules being exercised) in memory, so memory will grow regularly unless `py.test` tries hard to remove references to test modules after they finish executing.

IMO the way to assert that certain portions of the test suite leak memory should be to run a given test file multiple times using e.g. the [pytest-repeat plugin](https://pypi.python.org/pypi/pytest-repeat).

**Comment by pitrou** [comment]
Also, I'm curious how you measure memory consumption. RSS or VSZ?

**Comment by mrocklin** [comment]
Current code: https://github.com/dask/distributed/blob/master/distributed/utils_test.py#L491-L497

Currently this uses `psutil.virtual_memory().used`.  Although I've also used `psutil.Process().memory_info().rss` and gotten the same results.

**Comment by mrocklin** [comment]
The module-loading thought relates, I think, only to problem 1.  Problem 2 is, I think, entirely separate.  Some tests (like the test above) leak a full gigabyte of memory.

**Comment by pitrou** [comment]
Again, I would repeat the test in a loop to make sure it's not some memory fragmentation issue or the libc being slow to return memory to the OS.

**Comment by pitrou** [comment]
Also, I'm surprised `rss` would give the same results as `virtual_memory().used`.

**Comment by mrocklin** [comment]
```python
In [1]: import psutil

In [2]: from distributed.tests.test_steal import test_steal_when_more_tasks

In [3]: proc = psutil.Process()

In [4]: for i in range(5):
   ...:     test_steal_when_more_tasks()
   ...:     print(proc.memory_info())
   ...:     
/home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 1037 MB of memory
  warnings.warn("This test leaked %d MB of memory" % diff)
leaked memory 1037.86496 total leaked total 1038.348288
pmem(rss=1103867904, vms=2103443456, shared=17252352, text=4096, lib=0, data=1882456064, dirty=0)
/home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 1001 MB of memory
  warnings.warn("This test leaked %d MB of memory" % diff)
leaked memory 1001.525248 total leaked total 2039.873536
pmem(rss=2104889344, vms=3104526336, shared=17252352, text=4096, lib=0, data=2883538944, dirty=0)
/home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 1004 MB of memory
  warnings.warn("This test leaked %d MB of memory" % diff)
leaked memory 1004.929024 total leaked total 3044.80256
pmem(rss=3106045952, vms=4105564160, shared=17252352, text=4096, lib=0, data=3884576768, dirty=0)
/home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 997 MB of memory
  warnings.warn("This test leaked %d MB of memory" % diff)
leaked memory 997.072896 total leaked total 4041.875456
pmem(rss=4106985472, vms=5106585600, shared=17317888, text=4096, lib=0, data=4885598208, dirty=0)
/home/mrocklin/workspace/distributed/distributed/utils_test.py:531: UserWarning: This test leaked 999 MB of memory
  warnings.warn("This test leaked %d MB of memory" % diff)
leaked memory 999.616512 total leaked total 5041.491968
pmem(rss=5107941376, vms=6107627520, shared=17297408, text=4096, lib=0, data=5886640128, dirty=0)
```

**Comment by mrocklin** [comment]
I also put a `sleep(5)` in the for loop and observed the same effects.  

This test does produce some excess data due to work stealing.  We get two workers that work on the same task redundantly.  I wouldn't be surprised to have some excess work lying around for a little while.  I would expect it to be cleaned up though.

Hrm, I just tried changing `worker.executor.shutdown(wait=False)` to `wait=True` and this resolved the problem.  Perhaps when an executor shuts down uncleanly it leaves behind threads that are still holding onto intermediate results?

**Comment by mrocklin** [comment]
I'm going to try implementing a timeout argument for Executor.shutdown.

**Comment by pitrou** [comment]
>  Perhaps when an executor shuts down uncleanly it leaves behind threads that are still holding onto intermediate results?

The threads should exit eventually anyway. Are we using our own version of ThreadPoolExecutor?

**Comment by mrocklin** [comment]
We are, but I don't think we modify this section.  I tried adding a
join-with-timeout and there were still issues other places.  I'll throw up
a PR in a bit.

**Comment by pitrou** [comment]
Reading the code, I'm worried our subclassing relies on implementation details. How about instead copy/paste the entire thread pool implementation from CPython's git master? See https://github.com/python/cpython/blob/master/Lib/concurrent/futures/thread.py

**Comment by mrocklin** [comment]
Can you describe your concern about subclassing?

**Comment by pitrou** [comment]
You are redefining a private method and hoping that what your version does matches the semantics expected by the class (including the use of private attributes). That's a bit fragile.

**Comment by mrocklin** [comment]
Ah I see, you're concerned about the code being different in different versions of Python.  Yes, that makes sense to me.  Will change.

**Comment by mrocklin** [comment]
I was confused by this behavior of the concurrent.futures.ThreadPoolExecutor: https://stackoverflow.com/questions/45682646/why-does-concurrent-futures-increase-vms-memory

**Comment by mrocklin** [comment]
This seems to be under control for now.
