### ISSUE TITLE
HDFS testing infrastructure appears to be broken

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1335]
Current tests are failing, I suspect due to build infrastructure.  I've changed our travis-ci config to allow these failures for now.  

@martindurant do you have time to handle this? It's fine if not, I can look around for other help if you're otherwise occupied.

**Comment by martindurant** [comment]
Yes, I am rebuilding everything needed for lib/hdfs3, which is taking a very long time to get through conda-forge. Within a few days, should know for sure where we stand. In the meantime, I am also making a docker image that suits my dev/hadoop cycle better at mdurant/docker_images:hadoop , maybe better for testing.

**Comment by martindurant** [comment]
Fixed in hdfs3, but considering changes to docker testing image anyway.
