### ISSUE TITLE
Client cancel and close raise err message

### ISSUE THREAD

**Issue by jierice** [dask/distributed#1336]
If I use `client.cancel` to cancel a future and do `client.close()` , it will generate the following error message.
```
Exception ignored in : <bound method Future._del_ of <Future: status: cancelled, type: ndarry,key:...>>
Traceback (most recent call last):
  File ".../distributed/clinet.py",line 285, in __del__
  File ".../tornado/ioloop.py", line 939, in add_callback
TypeError: 'NoneType' object is not callable
```

**Comment by mrocklin** [comment]
My brief efforts to reproduce this failed.  Can I ask you for a minimal
failing example?

**Comment by mrocklin** [comment]
You might also want to try this out on git-master

**Comment by jierice** [comment]
Tried to reproduce but failed. I will close for now.
