### ISSUE TITLE
Import errors kill the workers

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1341]
As already mentioned in other places (e.g. https://github.com/dask/distributed/issues/344), submitting a task that imports absent module completely hangs the worker(s). This is actually pretty easy mistake to make and in most cases it completely shuts down the cluster. Is there a plan to make workers immune to this kind of errors?

**Comment by mrocklin** [comment]
I agree that this would be valuable to fix.  I don't currently know how to fix it easily.  This manifests itself as a failed read on a connection to the scheduler.  We can certainly log and report the failure, but we don't know what the scheduler wanted us to do, so it's hard to appropriately respond.

**Comment by konrad-roze** [comment]
Just from the user's perspective, I'd expect that in case of import exception in task that I submit the whole cluster job would fail, but leaving the workers operational to accept further tasks.

**Comment by mrocklin** [comment]
Yes, as a user myself I entirely agree with you

**Comment by konrad-roze** [comment]
Closing this one as it seems to be an inherent limitation. For the enterprise case it may be an issue unless we don't allow users to run their own code but rather provide a set of predefined jobs.
