### ISSUE TITLE
Multithreading pitfalls & thoughts

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1342]
Just wanted to consolidate my thoughts on solving multithreading issues in the past few days related to scikit-learn and dask. (Cross reference: https://github.com/scikit-learn/scikit-learn/issues/7346)

Basically, I was unaware until I thought deeply about what was happening that by launching tasks from tasks, I would wind up with concurrent execution of task threads within a single worker process even though I had set the number of worker threads to one. That is, several tasks would be queued up to run within a worker (having submitted their own tasks) and then all be released nearly simultaneously. So, I had to guard against this in user code.

The ideal behavior in my mind would be that when a task submits another task, it rips the stack and forms a continuation that is rescheduled (on the same thread pool), rather than seceding in a new thread from the thread pool. That way you can't inadvertently introduce multithreading by launching tasks from tasks. 

Perhaps another approach would be to use semaphores to ensure only N tasks are running concurrently on a worker with threadpool size N. I think you can ensure cluster liveness by always choosing the youngest tasks to acquire the semaphore.

cc @dlovell

**Comment by mrocklin** [comment]
Have you considered using `get_client` and `secede` separately rather than using `worker_client`?

http://dask.pydata.org/en/latest/futures.html#submit-tasks-from-tasks

`worker_client` does both.  If you do want to stay with `worker_client` then consider the `separate_thread=False` option.

**Comment by mrocklin** [comment]
Checking in here.  Is this still live?

**Comment by adamklein** [comment]
We can close this. I am still curious if there is a way to do cooperative multitasking on a single thread, perhaps by using the tornado event loop in my task so that I can choose to yield to another unit of work on the same thread that arrives via the scheduler. That would be cool.

**Comment by adamklein** [comment]
I'm going to reopen with an explanation of what I did to address my issues. Considering I am writing low-level threading logic, perhaps this sort of stuff ought to live in the `distributed` library proper.

I wrote a monitor object (the synchronization construct, i.e. a lock + wait set) so I could limit the threads executing my critical section of code to one. In my case, the critical section of code is effectively the whole of the task logic. When a worker starts a task, it waits to enter the monitor. It can re-enter the monitor any number of times, recording how many times it has (re)acquired the monitor. When the worker secedes its thread, it launches its tasks first, and then just before it awaits the results, it saves its monitor state (ie the reentrant count) and yields the monitor, allowing another worker thread to enter the monitor and proceed. When all the subtasks complete, before the task pulls any results, it re-acquires the monitor and restores its reentrant count; then, it pulls the results, and continues. When the task exits, it decrements the monitor count and if the count goes to zero, releases the monitor.

To me this was the least invasive way to achieve making tasks fully sequential per process, although possibly using a coroutines approach w/o seceding the worker thread may have worked (I didn't spend too much time here, because I didn't know how this would interact with distributed internals, ie how to pop additional tasks off the work queue).

If my approach were to live in the `distributed` library itself, maybe it could take the form of a `join` method complement to `secede`, where the current thread awaits a slot in the worker pool in order to proceed (at least in principal, if not in implementation specifics)

**Comment by mrocklin** [comment]
Something like `join` is feasible.  I'm curious about why you needed a counter.  Why wouldn't a straight lock (or `dask.utils.SerializableLock`) have worked?

**Comment by adamklein** [comment]
I need a counter because I need to reenter my critical section from the same thread multiple times, so i need to decrement that counter each time I leave the critical section (instead of releasing the lock on the first time leaving). It might not be relevant actually if the entirety of the task is considered the critical section (ie so it would only ever be entered/exited once by the relevant worker thread)

**Comment by adamklein** [comment]
`secede` and `rejoin` work well for me. closing.

**Comment by mrocklin** [comment]
Thanks!
