### ISSUE TITLE
Dataframe with columns is list

### ISSUE THREAD

**Issue by jonatasfreitasv** [dask/distributed#1346]
Hi guys!

I have a large dataframe (+100GB) with columns is a list, like:

[a, b, c, d, e, f]
[1, 2, 3, 4]

What is the best way to extract this values and put in a series or array ? like:

a
b
c
d
e
f

My mission is count of most common words, thx a lot!

I try this:

```python
a = []

for words in dataset.msg_splited.compute():
    for word in words:
        a.append(word)
```

**Comment by mrocklin** [comment]
> I have a large dataframe (+100GB) with columns is a list, like:

I'm sorry, I don't understand what you mean here.  Can you give a small example using pandas perhaps?
