### ISSUE TITLE
Check versions on connection

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1376]
A decent fraction of the errors that we see (15%?) are due to mismatched versions.  We might consider silently running `client.get_versions(check=True)` on startup and issuing a warning if things don't match well.

**Comment by jonnor** [comment]
Added a comment about one occurrence of this issue on the PR: https://github.com/dask/distributed/pull/1720#issuecomment-425733996

**Comment by costrouc** [comment]
Yes please this would be extremely helpful. When running dask on Kubernetes it is too easy to get a version mismatch from separate conda solves for each docker image (dask worker, dask scheduler, jupyterlab user) without pinning.

**Comment by jrbourbeau** [comment]
I think this was added in https://github.com/dask/distributed/pull/2627 and is included in `distributed >= 2.9.2`

**Comment by jrbourbeau** [comment]
Just confirmed that a warning is logged when there are package version mismatches (when using the current `distributed` master branch). For example:

```
distributed.worker - WARNING - Mismatched versions found

distributed
+---------------------------+---------------------------+
|                           | version                   |
+---------------------------+---------------------------+
| This Worker               | 2.11.0+21.g05ca3fb1.dirty |
| scheduler                 | 2.12.0                    |
| tcp://192.168.0.102:64357 | 2.11.0+21.g05ca3fb1.dirty |
+---------------------------+---------------------------+

msgpack
+---------------------------+---------+
|                           | version |
+---------------------------+---------+
| This Worker               | 0.6.1   |
| scheduler                 | 1.0.0   |
| tcp://192.168.0.102:64357 | 0.6.1   |
+---------------------------+---------+
```

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/2627
