### ISSUE TITLE
Statistical profiling 

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1379]
We can use `sys._current_frames()` to get the current activity of every thread executing in a worker's ThreadPoolExecutor..  We might poll these threads to find out what they're working on over time.  This might give us another view into performance that is somewhat orthogonal to the current (and well beloved) task stream plot.  We might visualize this either on a per-worker basis or on a full-cluster basis.  

This is like statistical profiling, except that now we want to do it on a distributed system, and over time.

This raises some interesting questions:

1.  How frequently should we poll?  
2.  How do we represent this information?  What is the right information to grab out of a frame object that people will want to see?
3.  What data structures can we use to hold this data that we can both merge together (from different workers) and also have some element of timeliness?  Users might ask "What has taken the most time overall?"  or "What have my workers been working on during the last minute?"
4.  How compact can we make this?  This is particularly relevant if we start to transfer it back to the scheduler.
5.  How do we visualize this data?  [Flame graphs](https://www.google.com/search?site=&tbm=isch&source=hp&biw=1970&bih=1025&btnG=Search&q=flame+graph&oq=xgboost&gs_l=img.3..0l5j0i24k1l5.468.1093.0.1217.8.8.0.0.0.0.105.465.4j2.6.0....0...1.1.64.img..2.6.457.0.HEbMRR-uZYg#imgrc=5Vx_tcU2LjRw6M:) are common but don't have any element of time, which we probably care about.

cc @llllllllll for thoughts on the right data to pull from frames (and general nerd sniping on efficient data structures for rolling statistical profiling)  (also cc @eriknw)

cc @adamklein for use cases

**Comment by vincentschut** [comment]
Just fyi, these might be inspirational (or not, or you might already know them, in that case: just ignore):

https://www.nylas.com/blog/performance/
https://github.com/joerick/pyinstrument
https://github.com/uber/pyflame

**Comment by mrocklin** [comment]
Those are handy links.  Thanks @vincentschut !

General thoughts after looking through them.

1.  Storing data as a tree probably makes sense, and allows for optional merging between threads, between workers and over time.
2.  What we want differs a bit from established approaches because we want to sample many threads, not the current thread (though sampling the current thread also isn't necessarily a bad idea).
3.  We may also want to record the task that is actively working on?  Although this might interfere with storing things intelligently in trees.

Also cc'ing @seibert .  Multi-threaded profiling and visualization may be of more general interest to his work as well.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/1387 for an initial approach.  Critical feedback welcome.

**Comment by jcrist** [comment]
I believe this was resolved in #1387. Closing.
