### ISSUE TITLE
Terminate workers when close to exceeding memory limits

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1393]
In order to avoid OOM errors with job schedulers we might pre-emptively kill our own workers.  This could be done by having the nanny process watch the memory usage of the worker process and if it reaches some limit, like 95% of expected use, it would pre-emptively send a SIGINT or SIGTERM signal.  

This would allow us to more cheaply restart the worker rather than having to wait for the job scheduler.

**Comment by mrocklin** [comment]
This might be an easy task if someone wants to get used to dask.distributed.

I would implement this in the following way:

1.  Create a keyword argument for an absolute maximum amount of bytes in `dask-worker` and trickle it down to Nanny
2.  Set up a PeriodicCallback when creating a Nanny that checks psutil and, if memory usage of our worker process is greater than that limit and if so, trigger `Nanny.restart`

**Comment by adamklein** [comment]
I think this is implemented and can close issue?

**Comment by mrocklin** [comment]
Indeed.
