### ISSUE TITLE
Use RSS or VMS to track memory?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1409]
We recently added mechanisms to track a worker's memory use in order to slow down or terminate that worker to avoid out-of-memory errors.  When tracking memory we can look at either RSS or VMS memory use.

```python
[1]: import psutil

In [2]: psutil.Process().memory_info()
Out[2]: pmem(rss=34463744, vms=289349632, shared=5316608, text=4096, lib=0, data=179593216, dirty=0)
```

Which should we be tracking?  What do job schedulers track?

VMS is a bit unfortunate in that it includes 300MB of Python and 600MB including numpy, pandas, etc. which are sometimes just forked from the main process.

RSS is a bit unfortunate in that it seems not to include data allocated by NumPy.

```python
In [3]: import numpy as np

In [4]: psutil.Process().memory_info()
Out[4]: pmem(rss=43642880, vms=358273024, shared=8069120, text=4096, lib=0, data=186109952, dirty=0)

In [5]: x = np.empty(int(1e9), dtype='u1')

In [6]: psutil.Process().memory_info()
Out[6]: pmem(rss=43642880, vms=1358274560, shared=8069120, text=4096, lib=0, data=1186111488, dirty=0)
```

Given this I think we have to use VMS.  I'm not very familiar with what is commonly tracked by job schedulers that might kill a job though, so I thought I'd put this up here for general comment.

cc @davidedelvento

**Comment by seibert** [comment]
VMS will unfortunately be very misleading with any process that uses CUDA.  When the CUDA driver is initialized, it expands the virtual memory space to allow GPU memory to be mapped into the process's memory space.  Example:
``` python
In [1]: import psutil

In [2]: psutil.Process().memory_info()
Out[2]: pmem(rss=30953472, vms=212426752, shared=8904704, text=4096, lib=0, data=99287040, dirty=0)

In [3]: import numba.cuda

In [4]: c = numba.cuda.get_current_device()  # trigger initialization of CUDA

In [5]: psutil.Process().memory_info()
Out[5]: pmem(rss=160231424, vms=22376509440, shared=111820800, text=4096, lib=0, data=22016393216, dirty=0)
```
The more GPU memory you have, the larger the effect.  I'm not sure how to work around this...

**Comment by mrocklin** [comment]
Are there cases other than CUDA where this occurs.

Do you have suggestions on how best to track memory use at the process level?

**Comment by martindurant** [comment]
Where on earth does numpy put its memory if not into RSS? I see the `data` field increases, what is that?

**Comment by xhochy** [comment]
Running with tools like LLVM's AddressSanitizer will also expand VMS to enormous amounts without actually allocating any memory.

**Comment by mrocklin** [comment]
OK, sounds like VMS is also complicated enough that it's difficult to rely upon.

@martindurant I hadn't noticed the data field.  Nice find.  Looking around for documentation on it now.

**Comment by mrocklin** [comment]
https://pythonhosted.org/psutil/#psutil.Process.memory_info

data (Linux, BSD): aka DRS (data resident set) the amount of physical memory devoted to other than executable code. It matches “top“‘s DATA column (see doc).

I'll try tests with rss + data and see how that goes.

**Comment by seibert** [comment]
That said, I think RSS is fine to use. The effect you saw above was caused by Linux kernel behavior where you can allocate new pages (increasing your virtual memory consumption), but those pages don't map to any physical memory until you write to them:
```
In [1]: import numpy, psutil

In [2]: psutil.Process().memory_info()
Out[2]: pmem(rss=45084672, vms=306991104, shared=16203776, text=4096, lib=0, data=104386560, dirty=0)

In [3]: x = numpy.empty(int(1e9), dtype='u1')

In [4]: psutil.Process().memory_info()
Out[4]: pmem(rss=45084672, vms=1306992640, shared=16203776, text=4096, lib=0, data=1104388096, dirty=0)

In [5]: x.fill(0)

In [6]: psutil.Process().memory_info()
Out[6]: pmem(rss=1045016576, vms=1306992640, shared=16203776, text=4096, lib=0, data=1104388096, dirty=0)
```

**Comment by seibert** [comment]
Note that RSS + DATA will have the same problem with CUDA.  I think just RSS is still your best option.

**Comment by martindurant** [comment]
So in the latter case, rss+data would apparently duplicate the memory use.
@seibert : I'm curious, if you allocate those pages with empty, but no system memory is consumed yet, what are you seeing when you access the contents for read?

**Comment by seibert** [comment]
Much to my surprise, reading these pages doesn't increase RSS, and I get back zeros.

**Comment by seibert** [comment]
This may be the explanation:
```
  Initially, an anonymous mapping only allocates virtual memory.  The new
  mapping starts with a redundant copy on write mapping of the zero page.
  (The zero page is a single page of physical memory filled with zeroes,
  maintained by the operating system.)  Every virtual page of the anonymous
  mapping is attached to this existing prezeroed page, so attempts to read
  from anywhere in the mapping return zeroed memory even though no new
  physical memory has been allocated to it yet.

  Attempts to write to the page trigger the normal copy-on-write mechanism in
  the page fault handler, allocating fresh memory only when needed to allow
  the write to proceed.  (Note, prezeroing optimizations change the
  implementation details here, but the theory's the same.)  Thus "dirtying"
  anonymous pages allocates physical memory, the actual allocation call only
  allocates virtual memory.
```
From: https://landley.net/writing/memory-faq.txt

**Comment by mrocklin** [comment]
OK, so my case of not seeing RSS rise was more a function of my use of empty (or zeros it turns out) rather than a real use case.

```python
In [1]: import psutil

In [2]: import numpy as np

In [3]: psutil.Process().memory_info()
Out[3]: pmem(rss=43540480, vms=366620672, shared=8032256, text=4096, lib=0, data=194457600, dirty=0)

In [4]: x = np.zeros(int(1e9), dtype='u1')

In [5]: psutil.Process().memory_info()
Out[5]: pmem(rss=43839488, vms=1366884352, shared=8069120, text=4096, lib=0, data=1194721280, dirty=0)

In [6]: y = np.ones(int(1e9), dtype='u1')

In [7]: psutil.Process().memory_info()
Out[7]: pmem(rss=1043877888, vms=2366885888, shared=8081408, text=4096, lib=0, data=2194722816, dirty=0)

In [8]: z = np.ones(int(1e9), dtype='u1')

In [9]: psutil.Process().memory_info()
Out[9]: pmem(rss=2043871232, vms=3366887424, shared=8081408, text=4096, lib=0, data=3194724352, dirty=0)
```
