### ISSUE TITLE
Splitting futures

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#1426]
Hello :-)
I would like to split a future containing a list of items into multiple futures where each future would contain one item (without transferring the data from workers to the scheduler). I'm dynamically generating unknown amounts of data from workers and they are expensive to transfer to scheduler, so I want to look at the amount of data generated from the worker, split it into parts and feed it back into the cluster as multiple jobs.

Future([a, b, c]) -> [Future(a), Future(b), Future(c)]

Example:
```python
# worker:
def worker(x):
    print(x)
    return [2, 3, 4]

# scheduler:
future = client.submit(worker, 1)
# future = future.result() -> this would work, but it transfers the data to scheduler
futures = client.map(worker, future)  
```
This example should print 1, 2, 3, 4 (in any order).
Is this possible in distributed?
I know that it could be done with worker_client, but that is awkward to use and doesn't fit my use case very much.
It could probably be enabled by this (https://github.com/dask/distributed/issues/1424).

**Comment by wgeul** [comment]
> Hello :-)
> I would like to split a future containing a list of items into multiple futures where each future would contain one item (without transferring the data from workers to the scheduler). I'm dynamically generating unknown amounts of data from workers and they are expensive to transfer to scheduler, so I want to look at the amount of data generated from the worker, split it into parts and feed it back into the cluster as multiple jobs.
> 
> Future([a, b, c]) -> [Future(a), Future(b), Future(c)]
> 
> Example:
> 
> ```python
> # worker:
> def worker(x):
>     print(x)
>     return [2, 3, 4]
> 
> # scheduler:
> future = client.submit(worker, 1)
> # future = future.result() -> this would work, but it transfers the data to scheduler
> futures = client.map(worker, future)  
> ```
> 
> This example should print 1, 2, 3, 4 (in any order).
> Is this possible in distributed?
> I know that it could be done with worker_client, but that is awkward to use and doesn't fit my use case very much.
> It could probably be enabled by this (#1424).

I would like to do the same as you're describing here, what was the outcome of this issue?

**Comment by mrocklin** [comment]
You may want to look at https://examples.dask.org/applications/evolving-workflows.html
