### ISSUE TITLE
Intermittent node connection

### ISSUE THREAD

**Issue by breisfeld** [dask/distributed#1433]
Hi,
I set up dask distributed on a cluster with about 10 nodes connected through a local network. This works great. When I add a node outside of the local network, the connection seems intermittent as indicated by the node appearing and disappearing rapidly on the web interface. This intermittency apparently leads to errors, resulting in the worker being killed:

distributed.scheduler.KilledWorker: ('read-block-1856000000-c834b43de2dac710e149a567863fd350', 'tcp://<node address>:37436'). 

I am able to ping the node from the scheduler and the scheduler from the node.

Any ideas on how to determine the cause of this issue and perhaps a strategy to remedy it?

Thank you for your help.

**Comment by mrocklin** [comment]
The `KilledWorker` error is designed to protect Dask against tasks that might kill workers, for example by allocating too much memory or segfaulting.  

How this works is that every time your worker dies unexpectedly we mark all tasks that were running on that worker at the time as suspicious.  If any task is marked suspicious three times then we no longer try to rerun that task, in case it might be doing something like segfaulting.

In your case this assessment is incorrect.  A simple way to resolve your problem would be to increase the allowed number of failures.  You can do this by changing the `allowed-failures` value in `~/.dask/config` or setting the following environment variable

    export DASK_ALLOWED_FAILURES=1000

**Comment by breisfeld** [comment]
Thank you! That does eliminate the error I've been seeing. 

Is there a way to know if my intermittent node is contributing to the computations at all?
Since this node has much greater computational capacity than the others, I would really like to incorporate it into the dask calculations.

**Comment by mrocklin** [comment]
You might be able to get a sense for this by checking the diagnostic
dashboard <http://distributed.readthedocs.io/en/latest/web.html>

**Comment by breisfeld** [comment]
That was helpful. I was able to identify and fix an issue with the iptables rules on the node in question.
