### ISSUE TITLE
Orphaned partitions on workers after client disconnected

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1434]
I'm running dask-distributed on EC2 cluster. Currently my job is failing and dask logs CancelledError message (reason for this is a separate issue that I haven't figured out yet). Long time after client is disconnected I am seeing messages like below in worker logs:

'2017-09-28 15:40:55' DEBUG    [PID-20690] distributed.worker future state: ('process_partition-96dcef2b22c9a98db97e0284da99c625', 113) - RUNNING

At the same time memory consumption on the workers seems high.
I'd expect that this should not happen and all partitions would be released once the client does not hold any future objects.

PS. I suspect that such orphaned data may be pushed out to disk (consuming storage), migrate to other workers when current worker is retired and cause all other issues on a cluster.

**Comment by mrocklin** [comment]
One possibility is that you have a task that is running forever.  Dask is unable to interrupt a task once it starts (interrupting a thread isn't possible in Python).

If you'd like to dive into the internals a bit then you might try commands like the following to understand the perceived state of all tasks in the cluster

```python
client.run_on_scheduler(lambda dask_scheduler: dask_scheduler.task_state)  # should return {} if no clients
client.run(lambda dask_worker: dask_worker.task_state)  # should return {'worker-addr': {}} if no clients
```

**Comment by konrad-roze** [comment]
I will investigate it further as you suggested. From the dashboard though seems like there's almost no CPU consumption on these workers.

**Comment by konrad-roze** [comment]
Looks like indeed this might be caused by some blocked or long running tasks. In this case it seems like an implementation error, but in general we can have SOME long running tasks. Job seems to be timing out and the criteria are not clear to me. I assume there are some timeouts involved. Can I somehow regulate these timeouts?

**Comment by mrocklin** [comment]
How is it timing out?  The task will be run in a separate thread.  Ideally the worker can continue operating during this period without issue.  There are no timeouts on task duration.

**Comment by konrad-roze** [comment]
What I mean is, on the client side I see CancelledError and dask job fails. If some worker tasks are looped infinitely then I'd expect job to stay around forever as well unless there is some timeout applied.. Just to clarify we're running on distributed scheduler and each worker host runs multiple independent worker processes.

**Comment by konrad-roze** [comment]
Just as a follow up to this one. The issue seems to have been caused by tasks hanging very long due to memory errors in our code. At the same time it's not clear why the job itself crashed and I will follow up on this as a separate issue.

**Comment by mrocklin** [comment]
Note that as of the last release dask workers now terminate themselves when they near specified memory limits.  See http://distributed.readthedocs.io/en/latest/worker.html#memory-management for more information.

**Comment by konrad-roze** [comment]
Thanks, yes, we have updated distributed to 1.19.2 and dask to 0.15.4. Is this out-of-memory restart indicated by some error messages in the logs?

**Comment by mrocklin** [comment]
logger.warn("Worker exceeded 95% memory budget.  Restarting")

**Comment by konrad-roze** [comment]
I can see maybe a single one of these. However I see these:
`distributed.worker Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.18 GB -- Worker memory limit: 1.97 GB`

**Comment by mrocklin** [comment]
Right, at 80% memory use dask workers stop accepting new tasks.  Your process is taking well above that, so they have stopped.  See http://distributed.readthedocs.io/en/latest/worker.html#memory-management

**Comment by konrad-roze** [comment]
Yes, seems that we have a memory leak, probably related to usage of subprocess. However aside from that, whole job fails with CancelledError while I'm monitoring progress. In scheduler logs I can see a corresponding message:
`distributed.diagnostics.progress A task was cancelled (finalize-384d27d9a294a3352d22000ac42c96d8), stopping progress`
Can this also be caused by workers running out of memory?
