### ISSUE TITLE
Too many open file descriptors when using worker_client() get_dataset on worker

### ISSUE THREAD

**Issue by bivald** [dask/distributed#1439]
Hi,

I've encountered a scenario where the Dask worker doesn't seem to close it's file descriptors. I'm guessing I'm doing something wrong, I just can't figure out what.

**This works**    
```
def x(y, i):
    with worker_client() as e:
        return {}

while True:
    start = time.time()
    client = Client('127.0.0.1:8786')
    
    a = client.submit(x, 'y', randint(0,1000000))
    res = a.result()
    
    del a
    end = time.time()
    print("Ran for %s" % (end-start))
    client.shutdown()
    del client
```

It will give you a output like so:

> Ran on 0.021483182907104492
> Ran on 0.019320011138916016
> Ran on 0.015393733978271484
> Ran on 0.013657808303833008
> Ran on 0.015842914581298828
> Ran on 0.016707897186279297

And even after thousands of invocations it still only consumes 40 FDs.

**This doesn't work (leaks)**
However, if I change that to a function that consumes a dataset:

```
def x2(y, i):
    with worker_client() as e:
        flights = e.get_dataset('flights')
        del flights
        return {}
```

It will consume at least 1 fd per query and doesn't appear to close them until I stop the worker. 

**Persisting the data**
I persist the data using:

```
from dask.distributed import Client
import dask.dataframe as dd

client = Client('127.0.0.1:8786')
df = dd.read_parquet('...')
df = client.persist(df, broadcast=True)
client.publish_dataset(flights=df)
```

I *think* I'm misusing or misunderstanding how to use the get_dataset from a function within a worker, can anyone point me in the right direction?

Using dask 0.15.3 and distributed 1.19.1 (both are the latest available on PyPi). I've tried it on Py3.6 on OS X and Py3.4 on Debian.

**Comment by mrocklin** [comment]
The leak is interesting.  I'm curious, does this still persist if you do the following?

```python
from dask.distributed import get_client
def x3(y, i):
    e = get_client()
    ...
```

I'm curious, why are you using get_dataset from within a worker?  This is a fairly advanced technique.  Are you sure that this is what you need?  What is your objective?

**Comment by bivald** [comment]
The same applies if I'm using:

```
def x2(y, i):
    e = get_client()
    flights = e.get_dataset('flights')
    return {}
```

Honestly I'm probably using it because I don't understand how I would do the basics 🙈 

The background is that I have a smaller-then-memory dataset which I publish as a dataset to distribute it to all workers at all times. Honestly I just want a Pandas DataFrame to be always available in my workers and then be able to run functions that uses that DataFrame. 

Can I simplify this?

It doesn't appear to the the client that is leaking (At least not using get_client only) but when I do get_dataset.

**Comment by mrocklin** [comment]
You can scatter concrete data (like in-memory pandas dataframes) to workers using the `scatter` method.

    future = client.scatter(my_pandas_dataframe, broadcast=True)

You can then use this future in any dask call (delayed, submit, etc.) and the worker will receive this future as the pandas dataframe.

**Comment by bivald** [comment]
I will try using scatter instead. Preferbly the client doesn't have to know the future (since it will be initiated by another client), but I'm pretty sure I can handle that with Variables. I will try - thank you :)

Do you want me to do a Minimal, Complete, and Verifiable example of this leak anyway? Or is it too obscure?

**Comment by mrocklin** [comment]
You can get very far with having only one client on your local machine, and never invoking clients from workers.  Invoking clients from workers is only necessary in very advanced situations.  If you haven't read it already, I recommend reading http://dask.pydata.org/en/latest/futures.html .

If you have an MCVE for the leak that would be useful, although this feature is infrequently enough used that I'm not personally likely to work to track down the leak any time in the near future.

**Comment by bivald** [comment]
Sorry, I'm haven't described my setup enough. There will be a web application (Flask based) with graphs that is powered by Dask, so there won't be any local machine. Just the Flask app communicating with my Dask workers.

**Comment by mrocklin** [comment]
The process running your flask app will likely create a client somewhere.  What I mean to say is that it is rare for workers to also have to have a client.  Multi-client setups are rare and only common in fairly advanced situations.

**Comment by bivald** [comment]
You are right of course, back to the drawing board for me 👍  Thank you so much for the pointers. I will possibly using "worker having a client" for the specific use case of a task submitting a task, but I know it's experimental so I'll try to do a up-front graph instead

**Comment by bivald** [comment]
👍 

I switched to using futures from the client and never invoking clients from the worker, and no leaks. Closing this.
