### ISSUE TITLE
Hashable variable for pure delayed

### ISSUE THREAD

**Issue by kszucs** [dask/distributed#1464]
How terrible idea would it be to implement `__hash__` on `Variable` class?
Passing a `Variable` to a pure delayed makes it unhashable resulting different keys.

I know that it's a mutable state (or side effect), but pure delayed already supports dictionaries as argument.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/961747/31427650-48463794-ae68-11e7-8ba3-0f405988fd96.png">

OTOH are the tasks correctly named? Shouldn't it be `say-hi` instead of greet?

**Comment by mrocklin** [comment]
What if the value of the variable changes between calling the delayed function and executing it?  Wouldn't we get possibly different results?

**Comment by kszucs** [comment]
Whose responsibility to ensure that? 

Is the following valid?
```py
@delayed(pure=True)
def randint():
    return random.randint()
```

**Comment by mrocklin** [comment]
> Is the following valid?

No.  `pure=` is more correctly "is deterministic based on inputs"

If dask schedulers see the same key twice they feel free to assume that computing that task will result in equivalent results.

**Comment by kszucs** [comment]
I see that is not deterministic, but that's my responsibility to not flag that function as a pure one.
Actually I want to use dask variables to provide feedback about the internal state of the computation inside a function, without influencing its result. 
This task might be fired by multiple clients, and It should be pure to avoid running multiple times simultaneously.

**Comment by mrocklin** [comment]
Unfortunately delayed doesn't allow you to specify exactly which inputs should affect the generated key.  

You could always specify a key explicitly using the `dask_key_name=` keyword (see delayed docstring)

**Comment by kszucs** [comment]
So, may I implement `__hash__` for Variable? :)

**Comment by mrocklin** [comment]
Variables are mutable, so no, I don't think it would be a good idea to provide consistent tokenization for them

**Comment by kszucs** [comment]
Okay, agree. Thanks!
