### ISSUE TITLE
Unpicklable objects

### ISSUE THREAD

**Issue by rmcgibbo** [dask/distributed#1471]
Is there any way to reliably use objects that cannot be pickled? I see stochastic errors like

```Traceback (most recent call last):
  File "/prefix//python/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
EOFError
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/prefix//python/distributed/protocol/core.py", line 122, in loads
    value = _deserialize(head, fs)
  File "/prefix//python/distributed/protocol/serialize.py", line 161, in deserialize
    return f(header, frames)
  File "/prefix//python/distributed/protocol/serialize.py", line 23, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/prefix//python/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
EOFError
distributed.comm.utils - ERROR - truncated data stream (2993989 bytes): [too large to display]
distributed.worker - ERROR - Worker stream died during communication: tcp://10.232.34.52:44587
```

these objects hold cuda device handles, and are pretty expensive to initialize, so I'd rather handle their initialization and migration manually. I set a bunch of these objects at the begininng of my workflow by `client.scatter`ing their inputs and then putting the constructor in a `delayed`, so it'll get executed on the `scatter`ed workers. Is there any way to mark these objects as unpicklable so that dask won't try to migrate them between workers?

**Comment by mrocklin** [comment]
Short answer is "no", there is not currently any way to handle unserializable data.

Often I avoid this problem by not allowing Dask to manage these objects.  For example I might create a function that allocates them if they don't exist and then stick them in some globally accessible spot.  I often use the dask worker itself for this.

```python
from dask.distributed import get_worker

def get_thing():
    worker = get_worker()
    try:
        return worker.my_special_thing
    except AttributeError:
        worker.my_special_thing = BuildThing()
        return worker.my_special_thing
```

And then I would use that function everywhere instead of the object.

It's a hack, but often an effective one

**Comment by mrocklin** [comment]
You could also make your object serializable.  Perhaps it would serialize to a connection string and then reinstantiate itself on deserialization.

**Comment by rmcgibbo** [comment]
Okay, cool. Thanks for the tip!

Can you give any advice on how to write dask code using these objects if they're not managed by dask? For example, each of my special things can compute an array of elements.

```
def compute_values(special_thing, x):
    return special_thing.array_of_expensive_values(x)
```


Currently, my (buggy, since they can't be pickled) code manages the computation by keeping a Delayed of each `special_thing`.

In order to call `compute_values` on _each_ of the N `special_thing`s across N dask-workers and concatenate the results (although without actually transferring any data), I do something like

```
def compute_all_values(delayed_special_things, x):
    x = delayed(x)
    name = 'compute-values-' + tokenze(delayed_special_things, x)
    for i, ev in enumerate(delayed_special_things):
        dsk[(name, i)] = (compute_values, ev.key, x.key) 
    return da.Array(dask=sharedict.merge(dsk, x.dask, *[ev.dask for ev in delayed_special_things]),
                    name=name, dtype=..., shape=..., chunks=...)
```

Do you have any advice on how to adapt this pattern (just `client.sync`?) to a situation in which the objects aren't managed by dask?

**Comment by rmcgibbo** [comment]
I guess this kind of thing works:
```
import numpy as np
import dask.array as da
from dask.distributed import Client


N_PER_WORKER = 10
def f(worker_index):
    return np.full(N_PER_WORKER, fill_value=worker_index, dtype=np.float64)

c = Client()
workers = list(c.get_versions()['workers'].keys())

name = 'name'
dsk = {(name, i): c.submit(f, i, workers=w) for i, w in enumerate(workers)}
arr = da.Array(dask=dsk, name=name, shape=(len(workers)*N_PER_WORKER,),
               chunks=(tuple(N_PER_WORKER for _ in workers),),
               dtype=np.float64)
```
