### ISSUE TITLE
Print newline after text progress bar completes

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1487]
In the notebook, when the text progress bar completes, it does not currently print a newline. The result is anything printed afterwards gets smashed into the same line against the progress bar. Further if additional text progress bars are created, they simply overwrite the previous text progress bar. This makes hard to tell how many steps have been completed in a computation. To fix these issues, it would be nice to print a newline right after the text progress bar completes.

**Comment by mrocklin** [comment]
You're talking about `dask.distributed.progress`, yes?  Not `dask.diagnostics.ProgressBar`?

I've never used the text progress bar in the notebook, instead preferring ipywidgets.  I'm curious, why do you find yourself using the text version?

Of course we should fix it regardless.

**Comment by jakirkham** [comment]
Correct.

Because we were unable to get the widgets to (optionally) block yet. We discussed this before, but a long time ago in issue ( https://github.com/dask/distributed/issues/926 ). May be worth revisiting that again at some point, but can't revisit it personally ATM.

Agreed. Think it should be easy to fix. Wouldn't mind taking a look if no one else does, but can't do it soon. So figured this issue should be mentioned before I forget. :)

**Comment by mrocklin** [comment]
Sounds good

**Comment by mrocklin** [comment]
I believe that this is now resolved.

**Comment by jakirkham** [comment]
Is there a PR with the fix somewhere?

**Comment by mrocklin** [comment]
Oh I'm sorry, I saw the "merged" PR link above and assumed that it was a dask issue.  I see now that this was a nanshe PR.

**Comment by jakirkham** [comment]
Sorry was just doing that for my own bookkeeping. Didn't mean to cause confusion.

**Comment by jakirkham** [comment]
Resolved in PR ( https://github.com/dask/distributed/pull/1976 ).
