### ISSUE TITLE
Versioning between Dask and Dask.distributed

### ISSUE THREAD

**Issue by sohaibiftikhar** [dask/distributed#1525]
Currently dask.distributed just expects the latest version of dask. It could be that some dask.distributed features depend on an older version of dask. It would be nice to have a matrix that specifies which version of dask should you build dask.distributed with. This may help make maintenance easier going forward.

**Comment by mrocklin** [comment]
Generally when we release we include version information in setup.py and conda metadata files.

**Comment by mrocklin** [comment]
I'm going to close this.  I don't think we should explicitly record version requirements outside of requirements.txt and conda/meta.yaml files and should instead trust dependency managers to handle this for us.
