### ISSUE TITLE
Python 3.5 tests failing on async for ... in as_completed 

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1529]
Test failures like the following are now occuring on travis-ci.  This appears to be independent of any code change on our side.  I suspect that a depdendency has change.

```
__________________________ test_asyncio_as_completed ___________________________
    @coro_test
    async def test_asyncio_as_completed():
        async with AioClient(processes=False) as c:
            futures = c.map(inc, range(10))
    
            results = []
>           async for future in as_completed(futures):
E           TypeError: 'async for' received an invalid object from __aiter__: as_completed
```

@pitrou do you know of anything that might have caused this?

**Comment by pitrou** [comment]
I suspect this is because of the Python 3.5.4->3.5.1 downgrade here:
https://travis-ci.org/dask/distributed/jobs/297677871#L763

The `__aiter__` expectations were changed in 3.5.2 as an emergency bugfix:
https://docs.python.org/3.6/reference/datamodel.html#asynchronous-iterators
