### ISSUE TITLE
Question: deallocating worker memory usage after task completion

### ISSUE THREAD

**Issue by dotsdl** [dask/distributed#154]
I recently had a scheduler and several workers active over the course of a day, taking tasks from executors in different python sessions. Although none of the functions I passed to `Executor.map` return any values, the memory footprint of the workers eventually climbed to the full memory of the server. It's not clear to me what was consuming all that memory; are the objects created during function execution still held in memory on the worker, in addition to the returned value?

Don't have time ATM to dig into why so much memory was being used myself, but wanted to bring it up in case the reason is already known.

**Comment by mrocklin** [comment]
Only the result of the function call is explicitly stored in the worker.  Python itself might hold onto things  between garbage collection calls or the operating system might not reclaim data until necessary.  

Did this problem rise to the level that it affected performance?  

I should ressurrect some old code that monitored memory usage on workers.  I'll put this on my TODO list for next week.

**Comment by dotsdl** [comment]
> Only the result of the function call is explicitly stored in the worker. Python itself might hold onto things between garbage collection calls or the operating system might not reclaim data until necessary.

Hmmm...I'll have to try and reproduce the issue again next week (prepping for a conference, so short on time now). Not sure what's happening here given that the functions return `None`, so result should be really light.

> Did this problem rise to the level that it affected performance?

Yeah, the server had dug well into its swap space, as its main memory was completely filled.

> I should ressurrect some old code that monitored memory usage on workers. I'll put this on my TODO list for next week.

Cool. I'm happy to try things out if you need. Can probably reproduce the issue pretty quickly during the conference some evening, so I'll try to do so when I can give it my attention.

**Comment by mrocklin** [comment]
If you have a reproducible example that would be super-helpful and would definitely help me to provide a speedier solution.

**Comment by dotsdl** [comment]
Alright; I'll try to make this happen between now and Wednesday.

**Comment by mrocklin** [comment]
@dotsdl thoughts on this issue?  

Note that, if you update `distributed` and have bokeh installed you'll get a nice little Web UI accessible at `scheduler-addr:8787/status` that might help to diagnose the issue.

**Comment by dotsdl** [comment]
Been using distributed in production the last week and haven't noticed this problem again, and the original issue I remember appearing after pretty haphazardly throwing things at the workers I had going. I'll close for now, but if I manage to come across this again with a reproducible example in hand I'll open it back up. Thanks!

**Comment by mrocklin** [comment]
Please do.  I'm sure we're not through finding bugs like this.  Feedback when things don't feel right is really valuable to help identify what to work on.
