### ISSUE TITLE
Env variables are shared between tasks

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1542]
We're using dask.distributed on an EC2 cluster with mutliple worker processes per host.
I've noticed that if I simply submit a delayed function with
```
import os
os.environ["XXX"] = "YYY"
```
then the env variable value is preserved and can be read by any other unrelated task. 
This seems potentially dangerous, e.g. with code/libraries that store credentials in environmental variables. In more common case one can simply break any future tasks that fall back to values stored in environmental variables.

**Comment by mrocklin** [comment]
Yes, OS-level environment variables have OS-level scope.  You should not use them if you want task-level scope.  I don't think that there is anything that Dask can do here to prevent access to shared resources like this.

**Comment by konrad-roze** [comment]
I see. This may be a limitation/security issue in case of multi-tenancy in an enterprise environment. One might mitigate it by hiding the API behind a service front end and allowing users to use only a set of predefined tasks.
