### ISSUE TITLE
Click UTF terminal issue

### ISSUE THREAD

**Issue by simone-codeluppi** [dask/distributed#1547]
Hi
I have been running dask-scheduler inside a tmux session with no problems. After restarting it during the day (no updates, same tmux session as before) I got this message:

```
Your terminal does not properly support unicode text required by command line
utilities running Python 3.  This is commonly solved by specifying encoding
environment variables, though exact solutions may depend on your system:

    $ export LC_ALL=C.UTF-8
    $ export LANG=C.UTF-8

For more information see: http://click.pocoo.org/5/python3/
```
I tried to fix the issue but it persist. Any idea why all of a sudden this requirement showed up?
Thanks

**Comment by mrocklin** [comment]
This requirement has been part of the `click` CLI library, and part of dask.distributed, for a long while.  If this changed suddenly then my guess is that it is a change in your environment.  There is, as far as I know, no recent change in the Dask codebase that would cause this to occur suddenly.  Regardless, the suggestions in the error message are useful and generally safe.

**Comment by martindurant** [comment]
As the referred link in the error message explains, the exact language for your system may be different, and the simple suggestions, which work for many systems, may not work for you. At issue, is the conversions of whatever was typed into the CLI as arguments into strings within the program.  Whether tmux accepts UTF8 characters depends on a set of configurations (e.g., ~/.tmux.conf and system language settings) and on the terminal that it is interacting with. And that's about the end of my knowledge on the subject!

**Comment by simone-codeluppi** [comment]
Thanks! Now it will sound crazy but I ssh'd again into the same account on the server but from a new IP and everything worked as before. No changes in the LC_ALL variable or tmux settings.
