### ISSUE TITLE
Catching ImportError for ssl-less environments?

### ISSUE THREAD

**Issue by metasyn** [dask/distributed#1569]
Hi Matthew, dask team,

I've been digging into dask recently and am super impressed. So, thanks for all the work you guys are putting into these awesome libraries. I was amazed at how easy it was to get setup.

I've been looking at ways to use dask in a project at work where SSL is intentionally disabled due to some federal compliance requirements. In this case, I have no SSL module (despite it being in the standard lib).

I noticed that tornado has a pattern to catch ssl import errors:

```
try:
    import ssl
except ImportError:
    # ssl is not available on Google App Engine.
    ssl = None
```
(https://github.com/tornadoweb/tornado/blob/0e869e3f4735685cb2460aac499b509e6f5cc58a/tornado/tcpserver.py#L32)

In this case, adding such a change would allow for us to use distributed despite not having access to the ssl module. If you think this is a reasonable request, I'd love to make a PR. If not, we can simply fork distributed since it is such a small change, however, I thought it wouldn't hurt to ask in case you find this small change amenable.

Best,
Xander

**Comment by mrocklin** [comment]
This seems fine to me.

**Comment by mrocklin** [comment]
A pull request would be most welcome
