### ISSUE TITLE
Entry points broken: install_signal_handlers() missing 1 required positional argument 'loop'

### ISSUE THREAD

**Issue by sscherfke** [dask/distributed#1572]
Some entry points (at least `dask-remote` and `dask-submit` call `install_signal_handlers()` without any arguments, so Python complains about the mission `loop` argument.

**Comment by mrocklin** [comment]
Yup, that looks like a bug.  These tools are pretty much unused and poorly tested.  We might consider removing them.  Any objection to this @hussainsultan ?
