### ISSUE TITLE
Undeserializable exception in Variable future

### ISSUE THREAD

**Issue by tdna** [dask/distributed#1578]
This code below throws Exception with message Undeserializable exception. But it should throw NameError instead.
Without sleep it works as expected.

distributed version: 1.20.0

```python
# Undeserializable exception

from time import sleep
from distributed import Client, Variable
from dask import delayed

client = Client()


@delayed
def f():
    fsdaf
    return 5

future = client.compute(f())
future_var = Variable()
future_var.set(future)
sleep(0.1)
future_var.get().result()
```

**Comment by mrocklin** [comment]
Thank you for the excellent bug report @tdna .  I can reproduce this locally.  I believe that it is resolved in https://github.com/dask/distributed/pull/1580

**Comment by tdna** [comment]
Thanks for the quick fix, looks good.
