### ISSUE TITLE
Adaptive can seek to scale up and down simultaneously

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1604]
I observed in logs some occasions where adaptive scales down the cluster and then soon after, scales back up again. 

Looking at the logic for when scaling up and scaling down can happen: 
* scale down :not all workers are processing, when workers are idle and memory is not an issue
* scale up; and when scaling up can happen (by default when  total_occupancy > 2* total_cores

it becomes apparent that both of these are satisfiable simultaneously, e.g.

Three tasks: two with occupancy 4 and one with occupancy 1, running on 4 cores:

* Core 1 : occupancy 4
* Core 2 : occupancy 4
* Core 3 : occupancy 1
* Core 4 : occupancy 0

In this scenario, both the scale_up criteria and the scale_down criteria are satisfied.

(There will be more subtle cases where the scale_up condition only becomes satisfied after a scale_down operation is completed, of course.)

**Comment by mrocklin** [comment]
Thanks for the well written issue.  Do you have any recommendations on how to refactor the Adaptive class?  Changes here would be welcome.

**Comment by rbubley** [comment]
There are two things to do, I think:

1. Detect if we are trying to scale_up and scale_down simultaneously (and if so, do neither).
I think it could most easily be down by changing should_scale_down to return true only if scheduler.workers_to_close was non-empty. Then explicitly test in `_adapt` whether should_scale_up and should_scale_down are both true.

2. Change the logic so that this doesn't occur with the default parameters
I think this one will be covered by a subsequent fix to #1605.

**Comment by mrocklin** [comment]
I believe that this has been resolved.  Closing.
