### ISSUE TITLE
scheduler.retire_workers can mark tasks on retired workers as suspicious_tasks

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1606]
For example, when Adaptive scales down workers, it calls `scheduler.retire_workers(remove=True, close_workers=True)`

`scheduler.remove_worker` has an argument, `safe=True` that would prevent this, and this is indeed used, but prior to this a call is made to `scheduler.close_worker`, which in turn calls `scheduler.remove_worker` without passing on the `safe=True` flag.

**Comment by mrocklin** [comment]
Thanks for reporting.   A fix would be welcome here.

**Comment by rbubley** [comment]
Closed via #1607
