### ISSUE TITLE
RuntimeError: Event loop is closed after running tests on Debian.

### ISSUE THREAD

**Issue by detrout** [dask/distributed#1620]
Hi,

For some reason when the tests finish running with Debian autopkgtests there's an exception that looks like its happening during cleanup. (Since the report of what tests passed happened).

distributed: 1.20.2
dask: 0.16.0
python: 3.6.4rc1

root@amarana:/tmp/autopkgtest.8SWqzJ/autopkgtest_tmp
```
============================== 4 tests deselected ==============================
 987 passed, 82 skipped, 4 deselected, 8 xfailed, 2 xpassed, 1 warnings in 417.17 seconds 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/distributed/deploy/local.py", line 237, in close
    self.loop.add_callback(self._stop_worker, w)
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 149, in add_callback
    functools.partial(stack_context.wrap(callback), *args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

autopkgtests is testing the installed package, and not running in the source tree.

I copied conftest.py from the source tree into a temporary directory and I'm rusing the following py.test command

```
LC_ALL=C.UTF-8 LANG=C.UTF-8 http_proxy= \
  $py $(which py.test-3)  -m "not avoid_travis" . /usr/lib/python3/dist-packages/distributed \
  --verbose -r s --timeout-method=thread --timeout=300 --durations=20
```

(The environment variables are for oddnesses of the test chroot and not likely to be relevant).

adding "." to before the path to the distributed install directory is so py.test picks up the conftest.py module.

My most successful workaround was to add this:

```
--- ../tree/distributed/deploy/local.py	2017-12-07 21:48:26.000000000 +0000
+++ /usr/lib/python3/dist-packages/distributed/deploy/local.py	2017-12-08 18:38:06.757564588 +0000
@@ -242,8 +242,10 @@
                     sleep(0.01)
             del self.workers[:]
             self._loop_runner.run_sync(self._close, callback_timeout=timeout)
             self._loop_runner.stop()
+        except RuntimeError as e:
+            logger.error("%s", e)
         finally:
             self.status = 'closed'
 
     @gen.coroutine
```

with that I get the result:

```
=============================== warnings summary ===============================
usr/lib/python3/dist-packages/distributed/tests/test_collections.py::test_rolling_sync
  /usr/lib/python3/dist-packages/dask/dataframe/rolling.py:152: UserWarning: DeprecationWarning: dd.rolling_mean is deprecated and will be removed in a future version, replace with df.rolling(...).mean(...)
    "df.rolling(...).{0}(...)").format(method_name))

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 4 tests deselected ==============================
 987 passed, 82 skipped, 4 deselected, 7 xfailed, 3 xpassed, 1 warnings in 409.13 seconds 
pbuilder@amarana:/tmp/autopkgtest.8SWqzJ/autopkgtest_tmp$
```

Is that a reasonable work around? Is this problem happening to anyone else?

**Comment by mrocklin** [comment]
Similar errors have popped up historically during tests, yes, but they typically only manifest themselves as annoying messages and don't actually cause tests to fail.

Your solution of catching the exception in `LocalCluster` seems reasonble to me, but we might defer to @pitrou , who has more experience here.  He may or may not be around until Monday.  Is this time sensitive for you?

**Comment by mrocklin** [comment]
Also, thanks for the excellent bug report!

**Comment by detrout** [comment]
I think it can wait until monday.

Another Debian developer asked me to update cloudpickle, and 0.5.2 caused some of dasks tests to fail....which encouraged me to update dask & distributed.

Things can usually wait a few days.

**Comment by detrout** [comment]
@mrocklin Hi, I was wondering if you have a chance to run the patch by your collaborator?

I'd love dask distributed to have a chance to start passing Debian CI tests.

https://ci.debian.net/packages/d/dask.distributed/unstable/amd64/

**Comment by mrocklin** [comment]
He hasn't responded to this github issue, so my guess is that he hasn't had time to look at this. 

Moving on, do you have any interest in submitting your proposed change as a pull request?

**Comment by detrout** [comment]
Sure I'd be quite happy to submit it as a pull request. I have a few other things I need to get done first, but I'll try to do it a bit later today.

**Comment by mrocklin** [comment]
Thanks!

**Comment by pitrou** [comment]
It is a logic error if we try to schedule a callback on a loop that's closed. So I suggest investigating why this happens, instead of muting the error.

**Comment by mrocklin** [comment]
> It is a logic error if we try to schedule a callback on a loop that's closed. So I suggest investigating why this happens, instead of muting the error.

You are likely the person who understands the current IOLoop best at the moment.  I'm not sure anyone other than you understands the workings of your `LoopRunner` work.

**Comment by mrocklin** [comment]
It looks like this is causing some pain for downstream package managers.  If you don't have time to handle this short term them I'm inclined to go ahead with converting the exception to a logging message.

**Comment by pitrou** [comment]
I don't think it's `LoopRunner`-related in itself. Judging by the exception ("Error in atexit._run_exitfuncs"), a LocalCluster seems to be closed after the test suite ends... which means some tests is leaking such a LocalCluster (I'm not extremely surprised, since the constant memory growth during the test suite has to come from somewhere :-)).

> It looks like this is causing some pain for downstream package managers.

I'm surprised by this. In either case, an error is logged or reported, but it doesn't change the test suite outcome (since the atexit error is ignored).

**Comment by pitrou** [comment]
In other words, the error is showing that the test suite is misbehaving in some way, and I don't think it's a good idea to hide it.

By the way, downstream packagers often patch packages, so Debian can apply a patch to silence the message if really required for packaging.

**Comment by detrout** [comment]
@pitrou Yes I could silence it in a Debian specific patch, but I wanted to check what you thought about the idea first.
