### ISSUE TITLE
Move worker_info onto WorkerState?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1641]
@pitrou I'm curious why you chose not to move worker metadata like this onto the WorkerState object?

**Comment by pitrou** [comment]
Just that it was not relevant for the immediate goal of trying to cythonize the scheduler, and did not present any obvious difficulties that deserved to be tackled up front :-) But, yes, we should probably do it anyway.

**Comment by pitrou** [comment]
This is fixed, no?
