### ISSUE TITLE
Logging formatting

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1650]
Currently our default logging format is as follows:

    %(name)s - %(levelname)s - %(message)s

This looks like the following:

```
distributed.scheduler - INFO - Starting worker compute stream, tcp://100.96.10.12:38938
distributed.scheduler - INFO - Register tcp://100.96.9.13:36728
distributed.scheduler - INFO - Starting worker compute stream, tcp://100.96.9.13:36728
```

Should we change this?  Options available here: https://docs.python.org/3/library/logging.html#logrecord-objects

**Comment by vincentschut** [comment]
I would love to see `%(asctime)s` included. Or maybe just make the log format configurable.

**Comment by mrocklin** [comment]
The log format is configurable with the `log-format` entry in the
config.yaml file

**Comment by vincentschut** [comment]
Ah, sorry, I must have missed that. Good to know!

**Comment by bachsh** [comment]
@mrocklin I think `asctime` should be included by default. Would that be ok if I submitted a PR on this?

**Comment by TomAugspurger** [comment]
I think the unknown here is how this will affect consumers of our logs. My
hope is that if people are relying on a specific formatting then they're
setting it rather than relying on the default. So overall I think a PR
updating this would be welcome.

**Comment by bachsh** [comment]
OK cool, can you guys think of something else that should be included in the log by default while we're at it?

**Comment by bachsh** [comment]
Issued a PR [here](https://github.com/dask/distributed/pull/3987) (probably the tiniest PR ever)
