### ISSUE TITLE
Work stealing is not happening when script is executed in spyder

### ISSUE THREAD

**Issue by daniel-sch** [dask/distributed#1654]
When the load on all workers is not evenly distributed, no work stealing is performed.

One way to provoke this, is to start new workers after the computations are started. Then the workers that start first will get all jobs assigned and all other workers will be idle. However, this is also happening if all workers get started in the beginning and the execution time of the jobs differs very much.

In the web interface, the idle and saturated workers are correctly displayed, but jobs are not redistributed.

I wrote a little MWE:
```
import time
import dask.multiprocessing
from dask.distributed import Client, LocalCluster
from _thread import start_new_thread

def execute():
    import time
    from dask.distributed import get_worker
    
    time.sleep(30)
    return get_worker().address
    

if __name__ == "__main__":
    cluster = LocalCluster(n_workers=1, threads_per_worker=1)
    client = Client(cluster)
    
    def start_workers():
        while True:
            time.sleep(20)
            cluster.start_worker(1)
            
    start_new_thread(start_workers, ())
    
    lazy_results = [dask.delayed(execute)() for i in range(5)]
    results = dask.compute(*lazy_results, get=client.get)
    print(results)

    cluster.close()
```
I use a fully updated version of Anaconda with Python 3.6 on Linux. The packages are installed in the following versions:

```
dask                      0.16.0           py36h73d177f_0
dask-core                 0.16.0           py36ha827fd6_0
dask-drmaa                0.1.0                     <pip>
distributed               1.20.2                   py36_0
```

The same problem also occurs on Windows 64bit (also fully updated Anaconda with Python 3.6).

Happy holidays and thanks for your help. Please let me know if you need any further information.

**Comment by mrocklin** [comment]
Unfortunately I am unable to reproduce.  Tasks seem to balance nicely during execution:

```
mrocklin@carbon:~/workspace/play$ python gh-1654.py 
('tcp://127.0.0.1:40283', 'tcp://127.0.0.1:41745', 'tcp://127.0.0.1:40965', 'tcp://127.0.0.1:41745', 'tcp://127.0.0.1:40965')
```

**Comment by rbubley** [comment]
Could be a race condition: stealing happens periodically, so it is theoretically possible to inspect before stealing has finished.

**Comment by daniel-sch** [comment]
@mrocklin OK this is really weird. When I run the python script directly, it works as expected. However when I start it in Spyder, I have the problem described above. Can you confirm this? Is there a possible explanation?

ipython also works fine btw.

@rbubley This unlikely, because this situation can persist over several hours.

**Comment by mrocklin** [comment]
My guess is that Spyder just runs a normal IPython console, so I would be surprised to see different results, but you might want to check in with them.  You might ensure that the environment is the same between your Spyder and IPython programs.

Regarding race conditions I agree.  Work stealing checks in every 100ms.  The tasks in the example here take 30s.

**Comment by daniel-sch** [comment]
Sorry for my late reply.

Can someone reproduce this in Spyder?

I don't have dask installed outside of Anaconda, so it pretty much has to use the same version.

They seem to have [some modifications](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/site/sitecustomize.py), but I'm not really sure what they do.

**Comment by daniel-sch** [comment]
I just did some more experiments: With a freshly installed (and not updated) version of Anaconda 5.0.0 it works fine:
```
Python 3.6.2 |Anaconda, Inc.| (default, Sep 22 2017, 02:03:08)
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

runfile('/home/schaeufele/dask_mwe.py', wdir='/home/schaeufele')
('tcp://127.0.0.1:37601', 'tcp://127.0.0.1:37601', 'tcp://127.0.0.1:43345', 'tcp://127.0.0.1:41159', 'tcp://127.0.0.1:41159')
```

The installed versions are

```
dask                      0.15.2           py36h9b48dc4_0
dask-core                 0.15.2           py36h0f988a8_0
distributed               1.18.3           py36h73cd4ae_0
```

Then after running `conda update dask` I have the versions shown above and also the bug described above.

Are there any other tests I could run?

**Comment by daniel-sch** [comment]
I just ran another `conda update --all` and this seems to have fixed the problem.

For reference, these versions seem to work:

```
dask                      0.17.2                   py36_0
dask-core                 0.17.2                   py36_0
distributed               1.21.6                   py36_0
spyder                    3.2.8                    py36_0
```

Closing as resolved.
