### ISSUE TITLE
Dask distributed client doesn't keep the connection alive

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1655]
We connect client machine to a distributed dask scheduler, submit a long running task graph and eventually call progress() to wait for completion.
In this case dask client doesn't seem to keep the connection alive.
If the connection goes through ELB or any other element that has an idle timeout, the connection is disconnected and the job is dropped (in case of ELB max timeout is 4000s).

**Comment by mrocklin** [comment]
By ELB do you mean Amazon's elastic load balancer?  

My guess is that you're suggesting a regular heartbeat from clients to the scheduler?

**Comment by konrad-roze** [comment]
Right, we're using the AWS ELB at the moment.
Something to keep the client connection alive would help.
So far we were able to mitigate it only by sending a small request to scheduler once in a while.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/1657

**Comment by konrad-roze** [comment]
We patched the code manually and it works for us. Thanks, waiting for official release.
