### ISSUE TITLE
Heterogenous python versions

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1656]
Referencing also #1107

It would be useful to be able to different versions of Python running on each of the Client, the Worker, and the Scheduler. This is for two reasons: (1) to ease a migration path from Python 2 to 3; (2) to keep the Client infrastructure on Python 2 (necessitated by other dependencies), whilst taking advantage of Python 3 features where all the actual work is done (i.e. Scheduler and Workers).

@mrocklin – would you support a PR enabling this?

From a preliminary look, it seems to me that it should mostly just work as long as we have a way of ensuring the serialisation protocol is cross-version compatible.

Potential interface would be to have a command-line option of  `--python27-compatible`.

**Comment by mrocklin** [comment]
I expect this to be very hard to do robustly.  The functions that the client serializes are expected to deserialize well on the workers.  This is hard to guarantee without equivalent versions.

There is room for version mismatch between the scheduler and the client/worker (they mostly only communicate through msgpack and large bytestrings), this doesn't seem to be what you're after though.

That being said, if you're able to acheive this cleanly that would certainly be welcome.  Standards would be fairly high here though.

**Comment by rbubley** [comment]
I'll start with ensuring Scheduler being on Python 3, with Client & Worker on 2.7, works, and then look into the more complex case.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/989

**Comment by GenevieveBuckley** [comment]
Dask no longer supports python 2.7, so I'm going to close this issue now.
