### ISSUE TITLE
Is it possible to edit a distributed array in place?

### ISSUE THREAD

**Issue by funnydevnull** [dask/distributed#1676]
This is actually two questions but I suspect they're closely related.  In #1675  I was asking about editing a dataset containing a distributed array using an in-place operation (e.g. `x2 += 1`) and the result seems to be that, despite the semantics, this is _not_ an in-place operation.  

A related issue I'm seeing is that if `x` is a distributed array then `x[0] += 1` gives me a `NotImplementedError` so it seems there is no way to assign to a single row.  Is this really the case?  If I have a 25 gb matrix in memory do I have to copy the entire array to edit one row?

**Comment by mrocklin** [comment]
Dask arrays are lazy.  The `x` variable is just a plan to create an array.  It does not refer to actual data in memory.  When you've said `x += 1` you're just changing the plan.  This doesn't allocate memory immediately.  Changing the plan to affect a small number of blocks remains efficient, even if you get an entirely new dask array.  

If you're running into a performance problem in practice then I encourage you to submit a minimal example and we can look into what's going on.

**Comment by funnydevnull** [comment]
Thanks for the response.  I should have been more clear.  In #1675 I was referring to a published dataset so `x` had already been persisted to the cluster (so the memory was already allocated).  I don't have code to demonstrate the problem yet because I'm still trying to evaluate if dask is the right solution to my problem before integrating it into my pipeline.  

The problem (I mentioned in #1675 ) is that I need to work with many large 2-d numpy arrays whose total size will possibly be close to my clusters overall memory.  In some cases even an individual matrix could be quite large -- possibly hundreds of gigabytes.  The kinds of operations I would like to perform on this matrix are e.g. computing row-wise inner products with some fixed test vectors and then determine the largest inner product.  Basically I'm computing vector similarity over a large number of vectors.

I already understand how to do the above but my question now is how I can update this huge matrix (after its been persisted)?  The matrices can be so large that I really don't want multiple copies of them in the cluster memory.  In general I expect I will mostly be appending to them (adding new rows) rather than modifying existing rows but in either case I would like to know if its possible to perform these operations without making a whole new copy of the matrix in the clusters memory.  

If you prefer I could write some sample code to demonstrate what I would like to happen but the real test would be to run it near the limit of available RAM to see how it behaves.  I could try some test operations myself but  I'm not sure how to track the underlying arrays being used in the dask worker (to distinguish between in-place vs copied modifications).

**Comment by mrocklin** [comment]
Assuming that you remove references to existing arrays as you make new ones
you won't have multiple copies around.  Dask also won't need to make a full
copy.  It will only need to modify the chunks of arrays that are modified.

**Comment by funnydevnull** [comment]
Ok I'll try experimenting a bit with an in-memory version to see how that works.  

For appending to an array I imagine I can do something like `x=concatenate(x, y)` and this would just append `y` to `x` without allocating new memory.  But if another client still has the data backing `x` loaded (because its published as a dataset) I guess this would generate a copy?

Regarding your last sentence, I don't even see a way to modify a chunk of an array?  The following code gives a `NotImplementedError`:

```
x=np.random.normal(0,1, (1000,100))
cx=da.from_array(x, (10,100))
cx[3] = np.random.normal(0,1, (100,))
```

What is the right way to modify/set a subset of the array?

**Comment by mrocklin** [comment]
> For appending to an array I imagine I can do something like x=concatenate(x, y) and this would just append y to x without allocating new memory. But if another client still has the data backing x loaded (because its published as a dataset) I guess this would generate a copy?

I recommend giving this a try and seeing how memory behaves.  I suspect that in practice things would work out ok.  There might be more python objects around but I think you'll probably be fine as far as numpy-level memory allocations go.

> Regarding your last sentence, I don't even see a way to modify a chunk of an array? The following code gives a NotImplementedError:

What I mean to say is that dask doesn't needlessly copy things around.  You should also be aware that the task/data model underlying dask arrays is immutable.  You should never try to modify memory in-place.  Dask graphs form a Merkle DAG, similar to git or other data structures that shared structure and accumulate new results.

In general we don't have a great API for modifying individual chunks.  You could hack around this with slicing and concatenating as you suggest above.

**Comment by funnydevnull** [comment]
Regarding your last comment: is there a way (hack?) to use slicing to modify a few rows of a matrix?   I guess I could just allocate a new array for the modified rows and then concatenate it together with slices of the old array to effectively modify a sub-array?

In any case, I think I have an idea of how to proceed (appending to an array is much more important in my current use case than updating).  I'll probably need my overall RAM to be at least 2-3x larger than my total dataset to give me some headroom.  I'll test the concatenation and make sure it works.

Btw my issues notwithstanding I'm very impressed and excited by dask so thanks so much for all your excellent work, writeups and talks!

**Comment by mrocklin** [comment]
I don't know of a convenient way to modify a few rows of a dask array today.
