### ISSUE TITLE
Workers and scheduler memory leak in executing client.get(dsk, keys) calls

### ISSUE THREAD

**Issue by wzhouhi** [dask/distributed#1677]
I am puzzled by seeing the memory of workers and schedulers keep increasing as I repeatedly executing the same dask graph tasks which does and return nothing. The following is the example code that demonstrated what I observed on both windows 10 and Ubuntu 16.4 environment with Dask version 0.16.0 and Distributed 1.20.2.

I have also tried to increase the iteration # and to see if the memory usage will plateau. The memory keeps increasing after running over an hour. I added in memory_limit and did observe spill to disk, but it still increases, and eventually at 80%, all the workers paused.

<pre>
import psutil
import gc
from distributed import Client, LocalCluster
import objgraph

def test():
    pass

dask_graph = {}
for i in range(10000):
    dask_graph['test' + str(i)] = (test,)
leaf_task_names = list(dask_graph.keys())
number_workers = 4

def profile_distributed_client():
    print("[MemUsage] Start: [%r] bytes" % psutil.Process().memory_info().rss)
    cluster = LocalCluster(n_workers=number_workers, diagnostics_port=None, threads_per_worker=1)
    distributed_dask_client = Client(cluster)
    for i in range(10):
        r = distributed_dask_client.get(dask_graph, leaf_task_names)
        del r
        print("[MemUsage] Iteration [%r] After get: [%r] bytes" % (i, psutil.Process().memory_info().rss))
        for j in range(number_workers):
            worker_pid = cluster.workers[j].pid
            print("    Worker [%r] After get: [%r] bytes" % (worker_pid, psutil.Process(worker_pid).memory_info().rss))

    distributed_dask_client.shutdown()
    print("[MemUsage] After shutdown: [%r] bytes" % psutil.Process().memory_info().rss)
    gc.collect()
    print("[MemUsage] After gc: [%r] bytes" % psutil.Process().memory_info().rss)

if __name__ == '__main__':
    print("Initial most common object types:")
    objgraph.show_most_common_types()
    profile_distributed_client()
    del dask_graph
    gc.collect()
    print("End most common object types:")
    objgraph.show_most_common_types()
    print("[MemUsage] before exit: [%r] bytes" % psutil.Process().memory_info().rss)

Output from Windows 10:

Initial most common object types:
tuple              14579
function           11248
dict               4311
weakref            2475
wrapper_descriptor 1557
list               1543
getset_descriptor  1482
set                1239
type               1210
method_descriptor  1122
[MemUsage] Start: [46084096] bytes
[MemUsage] Iteration [0] After get: [153083904] bytes
    Worker [16192] After get: [65331200] bytes
    Worker [16860] After get: [67719168] bytes
    Worker [12392] After get: [68812800] bytes
    Worker [13164] After get: [65585152] bytes
[MemUsage] Iteration [1] After get: [182837248] bytes
    Worker [16192] After get: [75833344] bytes
    Worker [16860] After get: [76779520] bytes
    Worker [12392] After get: [78532608] bytes
    Worker [13164] After get: [73388032] bytes
[MemUsage] Iteration [2] After get: [186929152] bytes
    Worker [16192] After get: [81362944] bytes
    Worker [16860] After get: [82903040] bytes
    Worker [12392] After get: [82624512] bytes
    Worker [13164] After get: [80363520] bytes
[MemUsage] Iteration [3] After get: [191123456] bytes
    Worker [16192] After get: [84746240] bytes
    Worker [16860] After get: [84713472] bytes
    Worker [12392] After get: [83869696] bytes
    Worker [13164] After get: [84520960] bytes
[MemUsage] Iteration [4] After get: [193150976] bytes
    Worker [16192] After get: [86671360] bytes
    Worker [16860] After get: [86933504] bytes
    Worker [12392] After get: [86794240] bytes
    Worker [13164] After get: [86818816] bytes
[MemUsage] Iteration [5] After get: [194064384] bytes
    Worker [16192] After get: [88727552] bytes
    Worker [16860] After get: [89186304] bytes
    Worker [12392] After get: [88817664] bytes
    Worker [13164] After get: [86294528] bytes
[MemUsage] Iteration [6] After get: [199094272] bytes
    Worker [16192] After get: [88031232] bytes
    Worker [16860] After get: [88625152] bytes
    Worker [12392] After get: [87339008] bytes
    Worker [13164] After get: [86831104] bytes
[MemUsage] Iteration [7] After get: [206618624] bytes
    Worker [16192] After get: [89591808] bytes
    Worker [16860] After get: [88694784] bytes
    Worker [12392] After get: [89337856] bytes
    Worker [13164] After get: [88109056] bytes
[MemUsage] Iteration [8] After get: [206761984] bytes
    Worker [16192] After get: [90300416] bytes
    Worker [16860] After get: [90673152] bytes
    Worker [12392] After get: [89759744] bytes
    Worker [13164] After get: [90083328] bytes
[MemUsage] Iteration [9] After get: [207097856] bytes
    Worker [16192] After get: [90968064] bytes
    Worker [16860] After get: [90386432] bytes
    Worker [12392] After get: [89907200] bytes
    Worker [13164] After get: [90902528] bytes
[MemUsage] After shutdown: [207040512] bytes
[MemUsage] After gc: [207040512] bytes
End most common object types:
dict               23040
list               20257
function           11579
_lru_list_elem     10000
tuple              5037
weakref            2608
wrapper_descriptor 1557
getset_descriptor  1503
set                1346
type               1227
[MemUsage] before exit: [202522624] bytes

Output from Ubuntu 16.4:

Initial most common object types:
tuple              14452
function           11227
dict               4313
weakref            2435
list               1532
wrapper_descriptor 1531
getset_descriptor  1389
set                1243
method_descriptor  1197
type               1195
[MemUsage] Start: [50782208] bytes
[MemUsage] Iteration [0] After get: [200302592] bytes
    Worker [240] After get: [62304256] bytes
    Worker [245] After get: [63025152] bytes
    Worker [244] After get: [61603840] bytes
    Worker [241] After get: [62545920] bytes
[MemUsage] Iteration [1] After get: [266018816] bytes
    Worker [240] After get: [68112384] bytes
    Worker [245] After get: [69439488] bytes
    Worker [244] After get: [67563520] bytes
    Worker [241] After get: [68415488] bytes
[MemUsage] Iteration [2] After get: [308994048] bytes
    Worker [240] After get: [72847360] bytes
    Worker [245] After get: [76128256] bytes
    Worker [244] After get: [73621504] bytes
    Worker [241] After get: [73084928] bytes
[MemUsage] Iteration [3] After get: [338800640] bytes
    Worker [240] After get: [75821056] bytes
    Worker [245] After get: [77201408] bytes
    Worker [244] After get: [74756096] bytes
    Worker [241] After get: [74829824] bytes
[MemUsage] Iteration [4] After get: [370651136] bytes
    Worker [240] After get: [77217792] bytes
    Worker [245] After get: [79712256] bytes
    Worker [244] After get: [78495744] bytes
    Worker [241] After get: [77680640] bytes
[MemUsage] Iteration [5] After get: [391639040] bytes
    Worker [240] After get: [79732736] bytes
    Worker [245] After get: [80519168] bytes
    Worker [244] After get: [82386944] bytes
    Worker [241] After get: [79298560] bytes
[MemUsage] Iteration [6] After get: [407281664] bytes
    Worker [240] After get: [82530304] bytes
    Worker [245] After get: [80920576] bytes
    Worker [244] After get: [83505152] bytes
    Worker [241] After get: [80257024] bytes
[MemUsage] Iteration [7] After get: [425746432] bytes
    Worker [240] After get: [83173376] bytes
    Worker [245] After get: [81825792] bytes
    Worker [244] After get: [84041728] bytes
    Worker [241] After get: [81874944] bytes
[MemUsage] Iteration [8] After get: [444891136] bytes
    Worker [240] After get: [83439616] bytes
    Worker [245] After get: [82096128] bytes
    Worker [244] After get: [84312064] bytes
    Worker [241] After get: [82038784] bytes
[MemUsage] Iteration [9] After get: [461164544] bytes
    Worker [240] After get: [83152896] bytes
    Worker [245] After get: [82096128] bytes
    Worker [244] After get: [84312064] bytes
    Worker [241] After get: [81874944] bytes
[MemUsage] After shutdown: [461217792] bytes
[MemUsage] After gc: [460808192] bytes
End most common object types:
dict               105042
tuple              104783
list               102028
OrderedDict        60202
function           11426
_lru_list_elem     10000
weakref            2495
wrapper_descriptor 1531
getset_descriptor  1401
set                1283
[MemUsage] before exit: [458768384] bytes
</pre>

**Comment by mrocklin** [comment]
Thank you for the excellent issue.  @pitrou noted that we were leaking objects in our test suite as well.  Your example is particularly interesting in the difference between windows and linux.  I would have expected similar behavior.

**Comment by pitrou** [comment]
Are you using the same Python version on Windows and Linux?

Can you try adding the following lines in your `.dask/config.yaml` and re-run the test?
```
transition-log-length: 10
log-length: 10
```

**Comment by wzhouhi** [comment]
You are absolutely right! I forgot I read through the code and noticed these settings and modified these two settings to 10 in the Windows .dask/config.yaml file. My bad. I reverted my changes and here is the result from running on Windows 10 and they are similar to the results with Linux.

<pre>
Initial most common object types:
tuple              14579
function           11248
dict               4311
weakref            2475
wrapper_descriptor 1557
list               1543
getset_descriptor  1482
set                1239
type               1210
method_descriptor  1122
[MemUsage] Start: [45580288] bytes
[MemUsage] Iteration [0] After get: [171425792] bytes
    Worker [12392] After get: [67756032] bytes
    Worker [384] After get: [67780608] bytes
    Worker [16364] After get: [67567616] bytes
    Worker [19612] After get: [66191360] bytes
[MemUsage] Iteration [1] After get: [224358400] bytes
    Worker [12392] After get: [77357056] bytes
    Worker [384] After get: [76779520] bytes
    Worker [16364] After get: [76967936] bytes
    Worker [19612] After get: [77877248] bytes
[MemUsage] Iteration [2] After get: [248262656] bytes
    Worker [12392] After get: [80936960] bytes
    Worker [384] After get: [80916480] bytes
    Worker [16364] After get: [79523840] bytes
    Worker [19612] After get: [80736256] bytes
[MemUsage] Iteration [3] After get: [257437696] bytes
    Worker [12392] After get: [83144704] bytes
    Worker [384] After get: [83779584] bytes
    Worker [16364] After get: [84443136] bytes
    Worker [19612] After get: [83492864] bytes
[MemUsage] Iteration [4] After get: [261472256] bytes
    Worker [12392] After get: [83787776] bytes
    Worker [384] After get: [84250624] bytes
    Worker [16364] After get: [84480000] bytes
    Worker [19612] After get: [83120128] bytes
[MemUsage] Iteration [5] After get: [263475200] bytes
    Worker [12392] After get: [87355392] bytes
    Worker [384] After get: [85139456] bytes
    Worker [16364] After get: [87785472] bytes
    Worker [19612] After get: [85360640] bytes
[MemUsage] Iteration [6] After get: [264699904] bytes
    Worker [12392] After get: [88866816] bytes
    Worker [384] After get: [87916544] bytes
    Worker [16364] After get: [89198592] bytes
    Worker [19612] After get: [87519232] bytes
[MemUsage] Iteration [7] After get: [265232384] bytes
    Worker [12392] After get: [88805376] bytes
    Worker [384] After get: [88969216] bytes
    Worker [16364] After get: [90415104] bytes
    Worker [19612] After get: [88985600] bytes
[MemUsage] Iteration [8] After get: [264527872] bytes
    Worker [12392] After get: [88330240] bytes
    Worker [384] After get: [89432064] bytes
    Worker [16364] After get: [89030656] bytes
    Worker [19612] After get: [88129536] bytes
[MemUsage] Iteration [9] After get: [272437248] bytes
    Worker [12392] After get: [89387008] bytes
    Worker [384] After get: [88166400] bytes
    Worker [16364] After get: [90124288] bytes
    Worker [19612] After get: [89436160] bytes
[MemUsage] After shutdown: [264609792] bytes
[MemUsage] After gc: [264609792] bytes
End most common object types:
tuple              104842
OrderedDict        60201
dict               20571
list               17356
function           11504
_lru_list_elem     10000
weakref            2610
wrapper_descriptor 1557
getset_descriptor  1503
set                1331
[MemUsage] before exit: [261091328] bytes
</pre>

**Comment by pitrou** [comment]
Also, which Python is this with?

**Comment by wzhouhi** [comment]
Wait, they are still not similar. I misread the results. In distributed/scheduler.py, the defaults for "transition-log-length" is 100000, and "log-length" is 10000.

And Python 3.5.2

**Comment by wzhouhi** [comment]
I looked at my packages settings on Windows and Ubuntu:

<pre>
On Windows:
bokeh                     0.12.13          py35h047fa9f_0
dask                      0.16.0                    &ltpip&gt
distributed               1.20.2                 &ltpip&gt
numpy                     1.11.2                   py35_0
pandas                    0.19.1              np111py35_0
python                    3.5.2                         0

On Ubuntu:
bokeh                     0.12.7                   py35_0
dask                      0.16.0           py35hcb8ecc8_0
dask-core                 0.16.0           py35hfc66869_0
distributed               1.20.2                   py35_0
numpy                     1.11.2                   py35_0
pandas                    0.19.1              np111py35_0
python                    3.5.2                         0
</pre>

**Comment by pitrou** [comment]
This seems more or less fixed by PR #1630:
```
[MemUsage] Start: [46997504] bytes
[MemUsage] Iteration [0] After get: [174440448] bytes
    Worker [8073] After get: [64720896] bytes
    Worker [8071] After get: [64155648] bytes
    Worker [8070] After get: [64712704] bytes
[MemUsage] Iteration [1] After get: [204365824] bytes
    Worker [8073] After get: [74313728] bytes
    Worker [8071] After get: [73834496] bytes
    Worker [8070] After get: [75853824] bytes
[MemUsage] Iteration [2] After get: [227106816] bytes
    Worker [8073] After get: [79925248] bytes
    Worker [8071] After get: [79446016] bytes
    Worker [8070] After get: [82010112] bytes
[MemUsage] Iteration [3] After get: [227319808] bytes
    Worker [8073] After get: [82743296] bytes
    Worker [8071] After get: [82546688] bytes
    Worker [8070] After get: [82960384] bytes
[MemUsage] Iteration [4] After get: [235118592] bytes
    Worker [8073] After get: [86724608] bytes
    Worker [8071] After get: [86515712] bytes
    Worker [8070] After get: [85065728] bytes
[MemUsage] Iteration [5] After get: [237400064] bytes
    Worker [8073] After get: [87531520] bytes
    Worker [8071] After get: [87031808] bytes
    Worker [8070] After get: [88801280] bytes
[MemUsage] Iteration [6] After get: [239509504] bytes
    Worker [8073] After get: [87531520] bytes
    Worker [8071] After get: [89186304] bytes
    Worker [8070] After get: [89600000] bytes
[MemUsage] Iteration [7] After get: [231239680] bytes
    Worker [8073] After get: [87785472] bytes
    Worker [8071] After get: [89448448] bytes
    Worker [8070] After get: [90402816] bytes
[MemUsage] Iteration [8] After get: [238522368] bytes
    Worker [8073] After get: [90476544] bytes
    Worker [8071] After get: [89448448] bytes
    Worker [8070] After get: [90402816] bytes
[MemUsage] Iteration [9] After get: [238522368] bytes
    Worker [8073] After get: [90476544] bytes
    Worker [8071] After get: [89694208] bytes
    Worker [8070] After get: [90656768] bytes
[MemUsage] After shutdown: [238710784] bytes
[MemUsage] After gc: [238710784] bytes
```

**Comment by wzhouhi** [comment]
Is this the result from running on Linux using the fixes in  PR #1630?

**Comment by pitrou** [comment]
> Is this the result from running on Linux using the fixes in PR #1630?

Yes.

**Comment by wzhouhi** [comment]
Looking at the PR #1630 changes, don't quite understand how these changes would fix the differences between running on Windows and Linux?

**Comment by pitrou** [comment]
I don't know why you are fixated over that difference. I'm simply saying that it fixes the memory leak in your script.

**Comment by wzhouhi** [comment]
Thanks for looking into this. Sorry I misunderstood. Are you saying the memory usage increase plateau even though it is bigger than when it is started?

**Comment by pitrou** [comment]
> Are you saying the memory usage increase plateau even though it is bigger than when it is started?

Basically that.

**Comment by wzhouhi** [comment]
I increased the iteration number and applied the changes in PR #1630 locally and let it run for longer time to see if memory increase does plateau or not. Here are the results. The memory seems still keep growing but at a slower rate. Also, I am thinking the memory usage should be more or less the same before exiting the main with when it is started for the shorter iteration numbers, since distributed client finished all the tasks.

<pre>
[MemUsage] Start: [45703168] bytes
[MemUsage] Iteration [0] After get: [167276544] bytes
    Worker [20180] After get: [66777088] bytes
    Worker [21816] After get: [68304896] bytes
    Worker [14708] After get: [67915776] bytes
    Worker [21156] After get: [68755456] bytes
[MemUsage] Iteration [1] After get: [213737472] bytes
    Worker [20180] After get: [78315520] bytes
    Worker [21816] After get: [78413824] bytes
    Worker [14708] After get: [77860864] bytes
    Worker [21156] After get: [78036992] bytes
[MemUsage] Iteration [2] After get: [233566208] bytes
    Worker [20180] After get: [81809408] bytes
    Worker [21816] After get: [80068608] bytes
    Worker [14708] After get: [85512192] bytes
    Worker [21156] After get: [83853312] bytes
[MemUsage] Iteration [3] After get: [239583232] bytes
    Worker [20180] After get: [90173440] bytes
    Worker [21816] After get: [85532672] bytes
    Worker [14708] After get: [89010176] bytes
    Worker [21156] After get: [83963904] bytes

[....snip....]

[MemUsage] Iteration [565] After get: [368762880] bytes
    Worker [20180] After get: [256671744] bytes
    Worker [21816] After get: [253972480] bytes
    Worker [14708] After get: [256933888] bytes
    Worker [21156] After get: [256126976] bytes
[MemUsage] Iteration [566] After get: [369487872] bytes
    Worker [20180] After get: [256671744] bytes
    Worker [21816] After get: [253755392] bytes
    Worker [14708] After get: [258777088] bytes
    Worker [21156] After get: [257081344] bytes
[MemUsage] Iteration [567] After get: [369352704] bytes
    Worker [20180] After get: [256360448] bytes
    Worker [21816] After get: [253394944] bytes
    Worker [14708] After get: [258822144] bytes
    Worker [21156] After get: [257118208] bytes
</pre>

**Comment by pitrou** [comment]
Thanks for the measurements. It's possible that there are sources of leaks left in the distributed source code. There may also be some memory fragmentation building up.

> Also, I am thinking the memory usage should be more or less the same before exiting the main with when it is started for the shorter iteration numbers, since distributed client finished all the tasks.

What do you mean? Which two numbers are you comparing?

**Comment by wzhouhi** [comment]
I was referring to the memory usage numbers in your earlier posted results when the iteration number was 10:

<pre>
[MemUsage] Start: [46997504] bytes
[---snip ---]
[MemUsage] After gc: [238710784] bytes
</pre>

**Comment by pitrou** [comment]
Well, first, the cluster isn't closed at that point, only the client. Second, due to the way memory management works, I wouldn't expect the visible memory usage (as reported by "RSS") to go all the way down to its initial value.

**Comment by wzhouhi** [comment]
When will the cluster be closed? In my example script, when it prints out the last MemUsage number right before exiting the main, is the cluster closed? Or do I miss the closing of cluster code in my example script?

<pre>
print("[MemUsage] before exit: [%r] bytes" % psutil.Process().memory_info().rss)
</pre>

I

**Comment by pitrou** [comment]
Ideally when `cluster` goes out of scope it should be closed, but I'm not sure what the cluster API promises here. @mrocklin may elaborate.

**Comment by wzhouhi** [comment]
Thanks for the recent pull request: https://github.com/dask/distributed/pull/1691. This seemed fixed the memory problem we are seeing in the worker processes.

**Comment by mrocklin** [comment]
I'm glad it was helpful.  Thank you for raising the issue.

**Comment by wzhouhi** [comment]
Just to be complete, we ended up using the async get and with the pull request patches on the distributed 1.20.2. The worker's memory are stable at around 80M.

Here is the exact code I am running:

```
def profile_distributed_client():
    number_workers = 4
    cluster = LocalCluster(n_workers=number_workers, diagnostics_port=None, threads_per_worker=1)
    distributed_dask_client = Client(cluster)
    i = 0
    while True:
        i += 1
        dask_graph = {}

        for j in range(10000):
            dask_graph['test' + str(j)] = (test,)
        leaf_task_names = list(dask_graph.keys())

        futures = distributed_dask_client.get(dask_graph, leaf_task_names, sync=False)

        future_count = 0
        for batch in as_completed(futures).batches():
            for future in batch:
                future_count += 1
                del future

        print("[MemUsage] Iteration [%r] After get: [%r] bytes" % (i, psutil.Process().memory_info().rss))
        for j in range(number_workers):
            worker_pid = cluster.workers[j].pid
            print("    Worker [%r] After get: [%r] bytes" % (
                worker_pid, psutil.Process(worker_pid).memory_info().rss))
```
