### ISSUE TITLE
Token based security for workers

### ISSUE THREAD

**Issue by yuvipanda** [dask/distributed#1686]
This came up when working with @mrocklin on daskernetes.

It'd be great if when launching the scheduler I can generate a cryptographically good-enough random token, and all workers then need to provide this token to connect. This allows us to use this as a simpler form of security (just disallow unauthenticated endpoints) than setting up a full blown mutually authenticated TLS setup.

**Comment by mrocklin** [comment]
cc @pitrou

**Comment by darenr** [comment]
Did anything ever come of this idea?

**Comment by mrocklin** [comment]
@darenr not that I know of.  I suspect that if someone chooses to work on this then they'll continue the conversation here.  I think that this would be a great feature!

**Comment by mrocklin** [comment]
cc @rcthomas @shreddd , you were asking about this.

@jcrist @jacobtomlinson do you have thoughts on how hard this would be to implement?

**Comment by jcrist** [comment]
I think this would have to be done somewhere in the comm protocol, but haven't thought too much about this.

FWIW in cases like this I usually mint self-signed certs and secure the cluster with TLS. In this case the certs function much like a token, but we can offload the security onto another system. If you're using token based security you're going to want to have encryption as well to not leak the token. Minting certs per cluster handles both these cases just fine.

**Comment by mrocklin** [comment]
Is this something that we should be providing automatically for users who are more security minded, but don't have a proper CA around?

**Comment by mrocklin** [comment]
(also, your response was exactly the suggestion of @rcthomas (NERSC) in a recent phone call)

**Comment by jcrist** [comment]
I'm not sure. Maybe a utility function for creating the certs. Moving certs around will also need to be done in a secure manner and would be backend specific. I think there's a way we could do this automatically for most backends (I at least know how to do this for dask-yarn and dask-kubernetes). Perhaps a `security` kwarg to a cluster manager:

```
security : bool or Security, optional
    A security object to use to secure the cluster with TLS.
    Set to True to have self-signed certs created automatically.
    Default is False for no TLS.
```

**Comment by mrocklin** [comment]
OK, so maybe we try this out for LocalCluster as an example.  Get the various cluster manager folks to sign off on it, and then raise an issue on each of the dask-foo repositories?

**Comment by jcrist** [comment]
Sure, we could do that.

**Comment by mrocklin** [comment]
@rcthomas you had some preferred way to generate certs.  Would you have time to share it here?

**Comment by jcrist** [comment]
This is what we use in dask-gateway: https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/tls.py

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyterhub/pull/2055 Is what we do in JupyterHub now

**Comment by jacobtomlinson** [comment]
https://github.com/LLNL/certipy looks awesome!

**Comment by rcthomas** [comment]
@mrocklin sorry, it was indeed certipy

**Comment by mrocklin** [comment]
@jcrist I think that a meeting or two ago you may have informally volunteered to investigate this.   Is this still something that you're interested in?

**Comment by jcrist** [comment]
Sorry, yes, hopefully will get to it by tomorrow.

**Comment by jcrist** [comment]
Done in #3164.
