### ISSUE TITLE
Worker memory leak when sending arrays to cluster

### ISSUE THREAD

**Issue by martin82** [dask/distributed#1689]
I'm having memory issues when sending arrays to a cluster. Running the following on a distributed dask cluster seems to lead to a memory leak on the unlucky worker targeted.

```
def leak():
    import numpy as np
    from dask.delayed import delayed
    x = np.ones(5e7, dtype = np.int8)
    def fun(x): return None
    dummy = delayed(fun)(x).compute()

from dask.distributed import Client
client = Client('scheduler:8786')
leak() # Leaks memory!
```

When running `leak()` repeatedly, http://scheduler:8687/workers shows steadily increasing figures in steps of ~50mb in the targeted workers memory column. If I repeat until I reach the workers specified memory limit (using --memory-limit 2GB in my case) I receive a warning in the workers log:
    `"distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.69 GB -- Worker memory limit: 2.00 GB"`

I'm on dask 0.16.1, distributed 1.20.2, Python 3.6.2 (OSX client) Python 3.6.3 (Linux scheduler and Linux workers). I tried from Python 3.6.3 Linux client as well with the same result.
Update: Also tried master branches, dask - 62e886b, distributed - 97b1774, with the same result, although with an additional "UserWarning: Large object of size 50.00 MB detected in task graph: ..." message.

**Comment by mrocklin** [comment]
When I run this example I get the following warning:

```python
/home/mrocklin/workspace/distributed/distributed/worker.py:737: UserWarning: Large object of size 50.00 MB detected in task graph: 
  (array([1, 1, 1, ..., 1, 1, 1], dtype=int8),)
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s))
```

This is warning you that giving large objects as direct arguments in the task graph is probably not the best way of moving them around.  You are encouraged to move large arrays around explicitly with scatter.

However, this still shouldn't leak.  My guess is that there is some caching or logging mechanism around that is holding onto things.

**Comment by mrocklin** [comment]
Thank you for the simple reproducible error.  This is very helpful.

**Comment by mrocklin** [comment]
This should be resolved in https://github.com/dask/distributed/pull/1691

**Comment by martin82** [comment]
I can confirm it's resolved in latest master. Thank you very much for your prompt attention!

As for the warning: my real use case is seeding a video file to decoder nodes that returns frames for further processing in a larger graph. Assuming the video is only available on the client, i.e. it cannot be loaded directly by the workers, I figured the cleanest way to feed the decoder nodes would be:

    from dask.delayed import delayed

    videofile_data = ...

    def feeder(x): return x
    videofile_data = delayed(feeder)(videofile_data)

    # Assuming 200 frames of video is optimally decoded using two workers
    def decode(x, startFrame, endFrame): 
        ...
        return decoded_frames
    decoded_0 = delayed(decoder)(videofile_data,   0, 100)
    decoded_1 = delayed(decoder)(videofile_data, 100, 200)

    # Join decoded_x and convert to a single dask.array and/or do further processing
    ...

Scattering the data to more workers than the optimal number of nodes needed for decoding seems wasteful, but using scatter while limiting the number of nodes receiving seems to force me into explicitly specifying the actual workers. This seems a bit convoluted compared to the variant above and undesirable if there is no other (performance?) benefits. In my case, communication between the client and the scheduler is also much slower than in between the scheduler / worker nodes, so the  `direct` parameter of `scatter` is of no use to me. As this often applies when the cluster is in a location separate from the client I assume this is a very common use case.

**Comment by mrocklin** [comment]
You might want to read through
https://stackoverflow.com/questions/45941528/how-to-efficiently-send-a-large-numpy-array-to-the-cluster-with-dask-array
.  If you have any further questions after reading then please ask.
