### ISSUE TITLE
Question: MPI for underlying communication?

### ISSUE THREAD

**Issue by dwhswenson** [dask/distributed#1692]
We're interested in developing a task scheduling system that uses MPI for the underlying communications. Would it be feasible to subclass/duck-type an MPI-based version of the Dask.distributed communication objects? (It looks from #776 like the idea isn't totally crazy.)

If it is feasible, we may have the programmers to do the actual implementation. But I figure it makes sense to ask here whether that approach would even make sense.

CC @ocaisa

**Comment by mrocklin** [comment]
There are two main answers to this question:

### You could subclass dask comms

You could make a new comms system as described here: http://distributed.readthedocs.io/en/latest/communications.html cc @pitrou .  I believe that @pelson had a start on this at one point.  Dask currently does this for TCP and for in-process communication with queues.

### Why?

Alternatively, one might ask the question of why do you want to do this?  Are you looking for increased bandwidth?  Decreased latency?  Easier deployment on MPI-enabled hardware?

There may be other solutions to all of these objectives.  You might want to start by stating your desired objective and work from there.

**Comment by ocaisa** [comment]
With regards to the second question, one of the things we would like to do is to be able to split `MPI_Comm_World` into a set of subcommunicators. The subcommunicator is then passed down to an MPI application with a Python API, the idea would be that the dask tasks only communicate within the group of roots of the subcommunicators. The goal would be to scale up the pool of available resources to a large partition on a big machine, cutting the resources up into chunks that are roughly the sweet-spot with respect to the scalability of the worker application.

Maybe this is already possible, we just don't have a lot of experience with Dask yet. Any advice would be very welcome!

**Comment by mrocklin** [comment]
I'll have to admit that I'm not familiar enough with MPI to recognize subcommunicators.  Would it be correct to say that you're mainly looking to use MPI here as a way to set up a collection of dask processes, but that you wouldn't necessarily mind if they used some other protocol (like TCP) when they actually did communication?  If so then I would just make an `mpi4py` application that started dask workers and connected them up to the scheduler.  

We did something like this in the `dask-mpi` command line executable: https://github.com/dask/distributed/blob/master/distributed/cli/dask_mpi.py

**Comment by ocaisa** [comment]
Not quite, we are looking at using MPI to split available HPC resources into `N` distinct sets, with each set of resources handling a single task. Each task can then use MPI to manage the resources of the set. When you do something like that in MPI you typically create another communicator that includes the `root` of each of the  `N` distinct sets and we thought that would be the way to handlle things. 

Having said that, your suggestions still probably works. We can create the distinct sets and just have the `root`s connect back to the scheduler, that should just mean being able to provide a different communicator at https://github.com/dask/distributed/blob/master/distributed/cli/dask_mpi.py#L14

**Comment by mrocklin** [comment]
Is there any additional conversation to be had here or should we close this?

**Comment by dwhswenson** [comment]
I think this can be closed. If anything else comes up later, we'll ask!

**Comment by ocaisa** [comment]
To open this up again, we've been looking into this more and now have a specific problem. The way an MPI code works, each MPI process in the group sees the same code but may take a different execution path based on what their `rank` in the group is. In our use case, we have a set of Dask workers and each worker is actually `rank 0` of a group of MPI processes. We need to take the Dask task at `rank 0` and replicate it across the entire group in order for them to "see" the same code and execute the task correctly.

Do you have any advice for how to approach this? Is this something that might map to some functionality already in Dask? I see two possible approaches at the moment:
- Add the additional processes to the worker pool but get the scheduler to clone the same task to the group of workers that make up the MPI group.
- Handle the cloning ourselves in a modified `dask_mpi.py` (probably with MPI calls)
Which do you think would be most straight-forward?

**Comment by mrocklin** [comment]
Generally speaking almost no one uses dask-mpi these days.  They just use their resource manager to launch dask-worker processes dynamically.  This has proven to be more flexible and more natural in essentially all cases.  We tend to recommend http://dask-jobqueue.readthedocs.io/en/latest/

Unfortunately I personally don't fully understand your objective, and so am unsure how best to help.  The dask-mpi script is fairly simple and follows the stardard SPMD approach.  My hope is that it should be easy for you to modify it if you do need to continue setting things up with MPI.

**Comment by ocaisa** [comment]
Ok, thanks for the advice, I wasn't aware of http://dask-jobqueue.readthedocs.io/en/latest/ and it might help with some of our workflow.

We will try to tackle the core MPI issue through the dask-mpi script then.
