### ISSUE TITLE
Inconsistency in using cytoolz rather than toolz

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1695]
In some files we try to `import cytoolz as toolz` before falling back to using `toolz`. 

In others, we just use `toolz` without trying to use `cytoolz`.

Should we not be consistent?

**Comment by mrocklin** [comment]
We prefer cytoolz for some functions if it's around.  We don't need it
though and can use toolz if that is all that is available.

**Comment by mrocklin** [comment]
Closing for now.  Please comment again if we should re-open this issue.

**Comment by rbubley** [comment]
My point was more that in various places, e.g. `distributed/distributed/utils_comm.py`, we just import from toolz rather than attempting to import cytoolz and (presumably) saving some cycles.

**Comment by eriknw** [comment]
One option is to import from `tlz`, which pulls most function from `cytoolz` if available, otherwise it uses `toolz`.
