### ISSUE TITLE
Querying state of a task future says it is pending when it is actually processing

### ISSUE THREAD

**Issue by nicolls1** [dask/distributed#1698]
Repro case:
Setup:
```dask-scheduler``` running in one terminal 
```dask-worker 192.168.1.88:8786``` running in another terminal
open python command line and run:
```
from dask.distributed import Client
dask_client = Client('192.168.1.88:8786')
def dask_function():
    print('dask function start')
    for i in range(30):
        import time; time.sleep(1)
        print(i)
    print('dask function end')
    return 0
f=dask_client.submit(dask_function, key='123')
f.status
```
f.status prints 'pending' yet in the worker node the count is being printed. I am relatively new to dask but I was expecting a 'processing' or 'running' state. The future is updated when the tasks is done to 'finished'.

**Comment by mrocklin** [comment]
Futures don't get updates about the scheduler or worker state of their task.  They only see pending, and final states like finished, erred, cancelled, lost, etc.  Keeping futures up-to-date with current progress would significantly increase network communication in some situations.  

You can query this directly using `run_on_scheduler` if you like.  I can imagine adding something like this to public API, something like `Client.who_has` or `Client.call_stacks`.  You might look at those if you're interested in submitting a PR to get out the full task state.


```python
In [1]: from dask.distributed import Client
In [2]: client = Client()
In [3]: future = client.submit(lambda x: x + 1, 10)
In [4]: client.run_on_scheduler(lambda dask_scheduler: dask_scheduler.tasks[futu
   ...: re.key])
Out[4]: <Task '<lambda>-b770f6fcfc401b7cadff2cd56eb16742' memory>
```

**Comment by nicolls1** [comment]
Thanks! Will look into what it would take to add something new.

**Comment by mrocklin** [comment]
Closing this for now.  Please let me know if you'd like to reopen discussion.
