### ISSUE TITLE
Problems with client.compute for multi-dimensional collections with resource

### ISSUE THREAD

**Issue by caseyjlaw** [dask/distributed#1702]
The instructions for [computing on collections](http://distributed.readthedocs.io/en/latest/resources.html) define a syntax for using specific resources, such as:
`z.compute(resources={tuple(y._keys()): {'GPU': 1}}, optimize_graph=False)`

It seems these instructions fail for collections that are multi-dimensional. For example:
```
> dd = delayed(np.random.randint)(0, 10, (10,10))
> arr = dask.array.from_delayed(dd, (10, 10), int)
> future = cl.compute(arr, resources={tuple(arr.__dask_keys__()): {'GPU': 1}}, optimize_graph=False)
TypeError: unhashable type: 'list'
```

This is fixed if the keys are indexed ndim-1 times:

```
> future = cl.compute(arr, resources={tuple(arr.__dask_keys__()[0]): {'READER': 1}}, optimize_graph=False)

> future
Out[35]: <Future: status: finished, type: ndarray, key: finalize-3bb181ad379f56fc58168aeb1b16f918>

> future.result()
Out[36]: 
array([[4, 8, 2, 9, 8, 2, 9, 4, 4, 2],
       [8, 1, 1, 5, 2, 0, 5, 4, 6, 3],
       [5, 3, 6, 3, 1, 6, 4, 3, 8, 5],
       [3, 8, 0, 6, 7, 2, 4, 8, 1, 0],
       [7, 0, 6, 8, 6, 9, 8, 2, 5, 1],
       [7, 0, 4, 1, 4, 8, 5, 9, 8, 9],
       [2, 9, 0, 3, 1, 5, 6, 5, 6, 3],
       [2, 5, 7, 2, 2, 2, 8, 2, 0, 4],
       [2, 6, 6, 0, 6, 3, 2, 0, 8, 6],
       [0, 8, 0, 3, 7, 3, 6, 6, 5, 1]])
```

Furthermore, it is possible to require ill-formatted resources that are silently ignored. Here is an example with a resource that does not exist (no 'GPU' set for workers in this case):

```
> future = cl.compute(arr, resources={arr: {'GPU': 1}}, optimize_graph=False)

> future
Out[41]: <Future: status: finished, type: ndarray, key: finalize-56585de7b2c9bd58e45431f2891ab592>

> future.result()
Out[42]: 
array([[2, 1, 3, 2, 9, 9, 1, 4, 8, 3],
       [2, 4, 5, 8, 3, 1, 3, 3, 7, 8],
       [0, 9, 0, 0, 0, 8, 7, 9, 0, 0],
       [5, 2, 6, 8, 8, 9, 4, 2, 4, 7],
       [9, 1, 4, 2, 2, 6, 3, 0, 0, 1],
       [5, 2, 1, 2, 9, 5, 8, 6, 4, 6],
       [9, 3, 4, 0, 4, 0, 5, 3, 9, 4],
       [6, 7, 0, 5, 7, 0, 2, 6, 6, 9],
       [1, 2, 5, 5, 7, 6, 5, 6, 5, 6],
       [7, 7, 5, 2, 0, 7, 5, 9, 5, 3]])
```

**Comment by mrocklin** [comment]
Yes, the `__dask_keys__()` of a dask array produces a numpy array of keys.  You probably want to use something like `.flatten()` on the result.

Your latter example with the silent failure is unfortunate.  If you have time and interest to submit a PR fixing this that would be welcome.

**Comment by caseyjlaw** [comment]
Fair enough. PR at #1706.
The `__dask_keys__()` are actually lists, but I've implemented a flattening. It needed to be done via a while loop to handle arbitrarily high number of dimensions.

**Comment by caseyjlaw** [comment]
I think you are right that this needs to be done on the user side. Closing.
