### ISSUE TITLE
Possible race condition on shutdown & heartbeat

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1711]
I've observed what I think is a race condition on LocalCluster shutdown if I first close all my clients and then proceed to shut down the local cluster (on lastest master). I see:

```
Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://...:48871' processes=4 cores=4>>
Traceback (most recent call last):
  File "lib/python3.5/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "src/distributed/distributed/client.py", line 826, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat'})
AttributeError: 'NoneType' object has no attribute 'send'
```

This disappears if I put in a guard in client.py:

```
    def _heartbeat(self):
        if self.scheduler_comm:
            self.scheduler_comm.send({'op': 'heartbeat'})
```

**Comment by mrocklin** [comment]
I'm curious, how easy is this to reproduce?

**Comment by adamklein** [comment]
I didn't try to make a small repro, and it looks like your MR fixes the issue. Would it be useful for me to do so still?

**Comment by mrocklin** [comment]
I believe that this is resolved and in master
