### ISSUE TITLE
Improve memory available detection

### ISSUE THREAD

**Issue by asyd** [dask/distributed#1712]
In https://github.com/dask/distributed/blob/5ef9c806bf341a4c06d17d24eb94838b307d4871/distributed/worker.py#L63 you use psutil to known the amount of memory available.

However, in the case of the worker is launched in a cgroup with a memory limitation (memory.limit_in_bytes) the value returned by psutil is the amount of the host, not the amount available in the cgroups, there fore the worker try to use more memory than it can and the linux kernel kill it.

**Comment by mrocklin** [comment]
You can solve this manually by telling dask workers to limit their memory usage with `--memory-limit NBYTES`

To make this more automatic is there a nice way to get the cgroups memory limit from python with a library like psutil?

**Comment by asyd** [comment]
I'm looking for it!

**Comment by mrocklin** [comment]
Any update here @asyd ?

**Comment by asyd** [comment]
Hi @mrocklin, 

what do you think about https://github.com/asyd/distributed/commit/e6f188331d711b1d8a27da314e1ca1abc57d00d0?

**Comment by mrocklin** [comment]
Interesting.  Is this accurate for all linux distributions, or do some systems behave differently?

**Comment by asyd** [comment]
Since it's a Linux kernel feature it should work on every linux distributions. 

However, while this workaround will work on my use case (worker runs inside a docker container) I need to improve it to check if the worker runs on root cgroup or a subone by checking `/prod/self/cgroup` but I wanted have feedbacks before
