### ISSUE TITLE
embarrasingly parallel computation, workers run out of memory

### ISSUE THREAD

**Issue by apatlpo** [dask/distributed#1717]
Hi,

I am trying to run embarrasingly parallel computation based on this [delayed example](https://dask.pydata.org/en/latest/use-cases.html#embarrassingly-parallel-computation). Each task consists in loading the data from a file, processing the data (and eventually storing a plot). Unfortunately, part of the processing leads to a fill up of workers memory, see this [notebook](https://github.com/apatlpo/iwave_sst/blob/master/hw/hw_cloudmask_print_dist.ipynb).

I should add that the part of the code that fills up memory is the following call:
```
    #cmask = coarsen(fmask, dl, chunks) # this fills up memory for >= 500 files
```

What are my options in such situation?

**Comment by mrocklin** [comment]
You can try to diagnose performance issues, perhaps with the dashboard:
http://distributed.readthedocs.io/en/latest/diagnosing-performance.html
Or you can try to create a minimal complete verifiable example to ask for
help here: https://stackoverflow.com/help/mcve

**Comment by apatlpo** [comment]
Ok, I'll try to work on that.

Meanwhile here is an outline of the code that creates the issue (see also [code](https://github.com/apatlpo/iwave_sst/blob/master/hw/utils.py):
```
#
def coarsen(fmask, dl, chunks=()):
    # change fmask xarray into a dataset and add 2D lon/lat variables
    
    # define a function that associates a unique indice to any lon/lat pair

    # use da.map_blocks

    # use da.histogramm with weights (fmask original values)

    # call .compute()

    # redo computation with weights of 1 in order to get the number of grid points per coarse grid cells

    # divide two histogram outputs

    # create a new xarray and place result of division there

    # return the xarray
```

What am I wondering is whether the inner calls to dask and xarray may interefere with the outter part of the code? I am not sure how I could test that. I'll think about it and get back to you.

**Comment by apatlpo** [comment]
I have some difficulty reproducing the error with a simpler example.
I tried for example to generate synthetic data instead of loading data from files but it does not lead to the failure described above.
I noticed the following warning in the worker log when the failure occurs:
```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 8.06 GB -- Worker memory limit: 10.00 GB
```

**Comment by apatlpo** [comment]
It seems the solution was to use chunks of finite size in the nested routine (coarsen). I have the feeling these finite chunks alleviate memory load on workers.

As an unrelated side note I also had an issue with repeating failures (`ValueError: Unknown element o
`) of matplotlib calls of this type:
```
ax = plt.axes(projection=ccrs.Geostationary(central_longitude=140.0))
```
whose following alternative seems to fix failures:
```
ax = fig.add_subplot(111, projection=ccrs.Geostationary(central_longitude=140.0))
```
