### ISSUE TITLE
Keys for futures generated by compute are not unique

### ISSUE THREAD

**Issue by nicolls1** [dask/distributed#1733]
When I generate a future by calling `dask_client.compute()` it has the same key for repetitive calls. Submit and some others have the 'pure' kwarg to set the key to be unique but I don't see a way of using something like that with compute.

I am doing some basic mappings on a bag and then submitting it to a cluster with compute. It looks like the futures get generated in the _graph_to_features function (https://github.com/dask/distributed/blob/master/distributed/client.py#L1941) in the name list. 

What are your thoughts on adding a 'pure' kwarg to compute and generating a uuid for each variable, as is done with other 'pure' calls, rather than tokenizing the variable?

**Comment by mrocklin** [comment]
Compute takes in a dask collection that already has a task graph with many
keys.  You'll have to handle this with the appropriate dask collection
(like array, dataframe, bag, or delayed) beforehand.

**Comment by nicolls1** [comment]
I see now, thanks! I was trying to do that with bags but now I realize using arrays over bag will make this a lot easier/possible
