### ISSUE TITLE
IPython test failures

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1740]
We've had an intermittent test failure for the IPython code for a long while.  Here is a traceback

```python
=================================== FAILURES ===================================
__________________________ test_start_ipython_remote ___________________________
loop = <tornado.platform.epoll.EPollIOLoop object at 0x7fd1842a12e8>
zmq_ctx = <zmq.sugar.context.Context object at 0x7fd165bc74a8>
    @pytest.mark.ipython
    @need_functional_ipython
    def test_start_ipython_remote(loop, zmq_ctx):
        from distributed._ipython_utils import remote_magic
        with cluster(1) as (s, [a]):
            with Client(s['address'], loop=loop) as e, mock_ipython() as ip:
                worker = first(e.ncores())
                ip.user_ns['info'] = e.start_ipython_workers(worker)[worker]
                remote_magic('info 1')  # line magic
>               remote_magic('info', 'worker')  # cell magic
distributed/tests/test_ipython.py:143: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
distributed/_ipython_utils.py:140: in remote_magic
    run_cell_remote(ip, kc, cell)
distributed/_ipython_utils.py:48: in run_cell_remote
    msg = kc.get_iopub_msg(timeout=OUTPUT_TIMEOUT)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/jupyter_client/client.py:81: in get_iopub_msg
    return self.iopub_channel.get_msg(*args, **kwargs)
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/jupyter_client/blocking/channels.py:50: in get_msg
    ready = self.socket.poll(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <zmq.sugar.socket.Socket object at 0x7fd165dceac8>, timeout = 10000
flags = 1
    def poll(self, timeout=None, flags=POLLIN):
        """poll the socket for events
    
            The default is to poll forever for incoming
            events.  Timeout is in milliseconds, if specified.
    
            Parameters
            ----------
            timeout : int [default: None]
                The timeout (in milliseconds) to wait for an event. If unspecified
                (or specified None), will wait forever for an event.
            flags : bitfield (int) [default: POLLIN]
                The event flags to poll for (any combination of POLLIN|POLLOUT).
                The default is to check for incoming events (POLLIN).
    
            Returns
            -------
            events : bitfield (int)
                The events that are ready and waiting.  Will be 0 if no events were ready
                by the time timeout was reached.
            """
    
        if self.closed:
>           raise ZMQError(ENOTSUP)
E           zmq.error.ZMQError: Operation not supported
```

@minrk any thoughts?

**Comment by minrk** [comment]
That the socket is closed is peculiar. I'll investigate.

**Comment by minrk** [comment]
Do you have a link to a failed run?

**Comment by mrocklin** [comment]
Not at the moment, but I'm sure I'll generate one soon :)

**Comment by mrocklin** [comment]
Here we go: https://travis-ci.org/dask/distributed/jobs/337550936

**Comment by minrk** [comment]
Thanks. I dug around, and noticed that there is a global cache of KernelClients that's never cleaned up, keyed per connection-info dict. My current hunch is that a collision occurs where ports get re-used and a stale Client gets picked up. I haven't been able to see how that would happen or trigger the failure myself, but #1743 should prevent that if it's really the case.

**Comment by mrocklin** [comment]
Still failing: https://travis-ci.org/dask/distributed/jobs/338531698

**Comment by minrk** [comment]
Hrm. That's too bad, but I'm not entirely surprised. In the tests, are workers and the scheduler run in threads or processes?

I'm trying to get at why the socket would be closed. The main such cause I can think of is if something is calling `zmq.Context.instance().destroy()`. This *is* called in the tests, but I can only find it in the zmq_ctx fixture, which destroys the context at the end of the test. If a client were reused across tests, that would result in this behavior.

What's very strange, however, is that the error is in the *second* call to remote_magic with the same worker in both failures. That means that the first execution succeeds, but the second *immediately following* fails with a closed socket. And it's the IOPub socket, not the shell, so not all sockets are closed, just the one. I don't really understand how that could happen unless another thread somewhere is calling `zmq.Context.instance().destroy()`, or something similar. Maybe `IOLoop.close(all_fds=True)`, but that would be weird, too.

Is there any chance that there are workers that are being torn down in background threads while these tests are running?

**Comment by mrocklin** [comment]
These particular tests have the scheduler and workers running in separate
processes.  We definitely do call IOLoop.close(all_fds=True) when we clean
up the test.

Workers from other tests should have finished their teardown process
already, but this is complex enough that I wouldn't be entirely surprised
to know that there were some lingering threads or processes.  Those would,
I believe, be in separate IOLoops though.

**Comment by jakirkham** [comment]
IPython support was reworked recently ( https://github.com/dask/distributed/pull/4530 ). Also don't think we have seen this one in a while. Going to go ahead and close. Can open a new issue if it starts failing again
