### ISSUE TITLE
More convenient way to create the scheduler-file

### ISSUE THREAD

**Issue by jhamman** [dask/distributed#1741]
The concept of a "scheduler file" is a nice, convenient way to share scheduler information when working on a system where you won't know the scheduler address a priori. I would like to suggest a simple method, probably on `Client`, that creates such a "scheduler file" with a simple interface like this:

```Python
from distributed import Client
client = Client()
client.to_scheduler_file('path-to-a-file.json')
```

then from another session one could easily connect to that same set of resources via:

```Python
from distributed import Client
client = Client(scheduler_file='path-to-a-file.json')
```

Under the hood this would just be something like 

```Python
json.dump(client.scheduler_info(), 'path-to-a-file.json', indent=2)
```

**Comment by mrocklin** [comment]
I'm curious, do you find yourself doing the `json.dump` solution today?

**Comment by jhamman** [comment]
Yes - to some extent. I basically went searching for either a spec for the scheduler file and discovered that there really isn't a standard way for creating these files.

https://github.com/dask/distributed/blob/3e1094fe7e6ea3960bccc29770a5d92844cdd073/distributed/scheduler.py#L1031-L1034

Fuller context is that I'd like to easily and programmatically share an autoscaling PBSCluster/scheduler between a number of applications. Dumping the scheduler info to a file seems like a pretty clean way to share this information.

**Comment by mrocklin** [comment]
I agree that we need to make it more clear how to build these files,
including possibly providing a convenience function.

Short-term I have a slight preference to have someone try this out with the
manual process and see how it goes.  I suspect that that will inform the
creation of such a function.

**Comment by jhamman** [comment]
Fair enough, I'll give it a test run and report back. I'd also be keen to make this contribution myself if it seems to work.

**Comment by jhamman** [comment]
Just a quick report back. I've been using the following snippit all week with a fair bit of success: 

```Python
from distributed import Client
import json

client = Client(...)

with open('~/workdir/scheduler_file.json', 'w') as f:
    json.dump(client.scheduler_info(), f, indent=2)
```

This has allowed me to run a single adaptive cluster from one Jupyter Notebook and programmatically attach to it from various other notebooks.

**Comment by mrocklin** [comment]
@jhamman if you'd like to submit a PR for a function to write this to a file I'd be open to it.

**Comment by jhamman** [comment]
@mrocklin - see #1778
