### ISSUE TITLE
client.restart error message

### ISSUE THREAD

**Issue by jbusecke** [dask/distributed#1750]
I am experiencing an error when trying to restart a dask.distributed client.

executing `client.restart()` often results in this warning message

```
distributed.client - ERROR - Restart timed out after 5.000000 seconds
```
I am not quite able to pinpoint when and why this happens. By restarting the client several times (and restarting the jupyter notebook kernel) I am usually able to get this message to disappear. 

Is this something to worry about? 
Could the default time out time perhaps be increased?

I am using dask version '0.16.0'

**Comment by mrocklin** [comment]
You might try `client.restart(timeout=None)`

Or you might try updating to the latest versions of dask and distributed

    pip install dask distributed

**Comment by mrocklin** [comment]
Did updating resolve this problem?

**Comment by jbusecke** [comment]
I checked on two different clusters with the newest distributed version and the problem does not occur anymore. I will go ahead and close this. Many thanks.
