### ISSUE TITLE
Exception: AttributeError("'OpenFile' object has no attribute 'fs'",)

### ISSUE THREAD

**Issue by seyyedmohammad** [dask/distributed#1751]
Hello, 
I got this error when dask-worker running on another machine, but dask-worker in localhost run properly.

I read simple .csv file from localhost and learn model with dask.xgboost .

Tanks.

> distributed.worker - WARNING -  Compute Failed
Function:  read_block_from_file
args:      (<dask.bytes.core.OpenFile object at 0x7f2efc0796d0>, 29888000000, 64000000, '\n')
kwargs:    {}
Exception: AttributeError("'OpenFile' object has no attribute 'fs'",)
>

**Comment by mrocklin** [comment]
What are your versions of the `dask` and `distributed` libraries?

```python
import dask
dask.__version__

import distributed
distributed.__version__
```

**Comment by seyyedmohammad** [comment]
dask = 0.16.1
distributed = 1.20.2

**Comment by mrocklin** [comment]
Can you verify that your workers are under the same version?  You can check this with a client

```python
client = Client(...)
client.get_versions(check=True)
```

**Comment by seyyedmohammad** [comment]
I got this error:

> 
Traceback (most recent call last):
  File "temp.py", line 3, in <module>
    client.get_versions(check=True)
  File "/usr/local/lib/python2.7/dist-packages/distributed/client.py", line 2861, in get_versions
    "%s" % ('\n\n'.join(errs)))
ValueError: Mismatched versions found

bokeh
+--------------------------+---------+
|                          | version |
+--------------------------+---------+
| client                   | None    |
| tcp://172.21.50.10:25219 | 0.12.0  |
+--------------------------+---------+

dask
+--------------------------+---------+
|                          | version |
+--------------------------+---------+
| client                   | 0.16.1  |
| tcp://172.21.50.10:25219 | 0.17.0  |
+--------------------------+---------+

distributed
+--------------------------+---------+
|                          | version |
+--------------------------+---------+
| client                   | 1.20.2  |
| tcp://172.21.50.10:25219 | 1.21.0  |
+--------------------------+---------+

numpy
+--------------------------+-----------+
|                          | version   |
+--------------------------+-----------+
| client                   | 1.11.1rc1 |
| tcp://172.21.50.10:25219 | 1.14.0    |
+--------------------------+-----------+

>

**Comment by mrocklin** [comment]
It looks like your workers and client are using different versions of
Dask.  They will have to match for things to work.

**Comment by seyyedmohammad** [comment]
ok, I got it. 
Thanks.

**Comment by jgerardsimcock** [comment]
I am getting a similar attribute error: `AttributeError("'NoneType' object has no attribute 'get'")`

My versions of bokeh are different. Would these different bokeh versions also cause this error?
