### ISSUE TITLE
Should Adaptive clusters cleanup workers on close

### ISSUE THREAD

**Issue by jhamman** [dask/distributed#1759]
I'm wondering if it is possible to implement an `Adaptive` cluster such that workers are cleaned up when the cluster and/or scheduler is stopped. The use case here is using an adaptive cluster with a [PBS job queue](https://github.com/pangeo-data/pangeo/blob/master/pangeo/jobqueue.py) where jobs can be orphaned when the cluster is shut down before the wall time of the workers run out.

xref: https://github.com/pangeo-data/pangeo/issues/85

**Comment by mrocklin** [comment]
Ideally the scheduler does this when/if it shuts down cleanly.  If it's getting killed by a job scheduler then this won't happen. 

Typically the solution to this is to start the workers with `--death-timeout 60` so that they kill themselves if they don't hear from a scheduler in 60 seconds.

**Comment by jhamman** [comment]
That should do actually.

Just so I know, what are the kill directives that will shut the scheduler down cleanly? On PBS:

> A batch job being deleted by a server will be sent a SIGTERM signal following by a	SIGKILL	signal.

**Comment by mrocklin** [comment]
Sorry, I take it back, basic closing of the scheduler doesn't kill the workers.  This would need to be done explicitly.  You could do this with something like the following

```python
def close_at_shutdown(dask_scheduler):
    import atexit
    @atexit.register
    def f():
        dask_scheduler.retire_workers(workers=dask_scheduler.workers, close_workers=True)

client.run(close_at_shutdown)
```

Although there is probably a race condition there to see if the ioloop is closed or not.

**Comment by mrocklin** [comment]
I would just use the death-timeout.  It seems to be the solution that makes it to production the most often.

**Comment by jhamman** [comment]
Thanks @mrocklin. I think this will do.
