### ISSUE TITLE
distributed.asyncio.AioClient seems to be broken

### ISSUE THREAD

**Issue by basnijholt** [dask/distributed#1762]
I am trying to execute `distributed.asyncio.AioClient()` inside a notebook and expect a future will be returned. However, it appears to be stuck forever. 

When I interrupt the kernel I get the following traceback:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-544e7a0bbcaa> in <module>()
      1 import distributed.asyncio
----> 2 distributed.asyncio.AioClient()

/opt/conda/lib/python3.6/site-packages/distributed/asyncio.py in __init__(self, *args, **kwargs)
     96         loop = asyncio.get_event_loop()
     97         ioloop = BaseAsyncIOLoop(loop)
---> 98         super().__init__(*args, loop=ioloop, asynchronous=True, **kwargs)
     99 
    100     def __enter__(self):

/opt/conda/lib/python3.6/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, **kwargs)
    553                                      io_loop=self.loop)
    554 
--> 555         self.start(timeout=timeout)
    556 
    557         from distributed.recreate_exceptions import ReplayExceptionClient

/opt/conda/lib/python3.6/site-packages/distributed/client.py in start(self, **kwargs)
    668             self._started = self._start(**kwargs)
    669         else:
--> 670             sync(self.loop, self._start, **kwargs)
    671 
    672     def __await__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    250     else:
    251         while not e.is_set():
--> 252             e.wait(1000000)
    253     if error[0]:
    254         six.reraise(*error[0])

/opt/conda/lib/python3.6/threading.py in wait(self, timeout)
    549             signaled = self._flag
    550             if not signaled:
--> 551                 signaled = self._cond.wait(timeout)
    552             return signaled
    553 

/opt/conda/lib/python3.6/threading.py in wait(self, timeout)
    297             else:
    298                 if timeout > 0:
--> 299                     gotit = waiter.acquire(True, timeout)
    300                 else:
    301                     gotit = waiter.acquire(False)

KeyboardInterrupt: 

distributed.utils - ERROR - sync() called from thread of running loop
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 235, in f
    raise RuntimeError("sync() called from thread of running loop")
RuntimeError: sync() called from thread of running loop
```

This part `sync(self.loop, self._start, **kwargs)` seems like it should not be executed. Also `self.asynchronous=True`, which seems incorrect.

`await`ing the `AioClient()` also doesn't work for me.

I've tried it on a colleagues computer (@jbweston), our [Jupyterhub](https://hub.docker.com/r/quantumtinkerer/research/), and on my MacOS machine, all with the same result.

With distributed version 1.20.2 and dask version 0.16.1.

@mrocklin asked me to ping @kszucs.

**Comment by mrocklin** [comment]
It's also worth noting that when tornado 5.0 is released (beta is out now) the tornado IOLoop will be the same as the asyncio event loop, so the need for AioClient should go away at that time.

**Comment by kszucs** [comment]
@basnijholt could You try with `1.20.1`? My colleague has pinned `1.20.1` in our deployment, probably because of this issue.

@mrocklin When can we expect the tornado release? :)

**Comment by mrocklin** [comment]
I don't know, you'd have to ask the tornado devs

**Comment by mrocklin** [comment]
@basnijholt are you able to provide a minimal example for this?

**Comment by basnijholt** [comment]
The minimal example is literally running the following code in a notebook:

```python
import distributed.asyncio
distributed.asyncio.AioClient()
```

@kszucs unfortunately, the problem doesn't disappear when I install `1.20.1`.

**Comment by kszucs** [comment]
@basnijholt `AioClient`'s loop conflicts with jupyter's one, outside of the notebook it works. 

I suggest to use `Client(asynchronous=True)` with the default tornado loop and await/async syntax instead of `AioClient` in the notebook - until we fix it. 
Later You can just switch to AioClient outside of the notebook.

**Comment by jbweston** [comment]
@kszucs, @basnijholt forgot to say that we are using the notebook's `asyncio` integration:

```
%gui asyncio
#new cell
import distributed.asyncio
distributed.asyncio.AioClient()
```

so I don't reckon the call to `AioClient()` should block, because after `%gui asyncio` cells are executed inside the `asyncio` event loop.

Does this sound correct?

**Comment by jbweston** [comment]
> I suggest to use Client(asynchronous=True) with the default tornado loop and await/async syntax instead of AioClient in the notebook 

Unfortunately we need the Client to be running on the `asyncio` event loop, as we need to `await` on it from within `asyncio` `Task`s

**Comment by basnijholt** [comment]
> I don't know, you'd have to ask the tornado devs

I've [asked on Gitter](https://gitter.im/tornadoweb/tornado?at=5a92b595888332ee3acc99a5)
> Ben Darnell @bdarnell Feb 25 14:09
@basnijholt early march, so within a few weeks

**Comment by jakirkham** [comment]
Well Tornado 5 has since been released and [running these lines]( https://github.com/dask/distributed/issues/1762#issuecomment-367278120 ) in a Jupyter Notebook on Python 3 with recent versions of all dependencies now seems to work fine. Good to close?

**Comment by kszucs** [comment]
Probably we should remove `AioClient` too.

**Comment by jakirkham** [comment]
That seems reasonable. Want to open a PR?

Are you using `Client(asynchronous=True)` these days?

**Comment by kszucs** [comment]
See Matthew's [comment](https://github.com/dask/distributed/issues/1762#issuecomment-365621681), I haven't tried it though.
