### ISSUE TITLE
dask-distributed citation in paper

### ISSUE THREAD

**Issue by simone-codeluppi** [dask/distributed#1764]
Hi
I am writing a scientific paper and because dask-distributed contributed in making the analysis possible I would like to include a citation. Any idea on what should I cite?
Thanks a lot!

**Comment by mrocklin** [comment]
Hi @simone-codeluppi , 

Thanks for your citation.  Please see http://dask.pydata.org/en/latest/cite.html

**Comment by simone-codeluppi** [comment]
Hi
Thanks!!

Simone
