### ISSUE TITLE
Ability to pin down all ports?

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#177]
Folks, 

I am using the pip installable version of distributed and the nanny defaults to a random port, even if the --port option is used. This interferes with locked down environments where I need to have a known set of ports open for a service.

Could we have a "nanny-port"option on dworker?

Nathan

**Comment by mrocklin** [comment]
Yup, that makes sense.  I'll do this tomorrow and issue a bugfix release (was planning to anyway.)

**Comment by nfaggian** [comment]
Excellent!
