### ISSUE TITLE
dask distributed ssh error

### ISSUE THREAD

**Issue by asqhaqs** [dask/distributed#1791]
I am setting up a cluster for running image analysis (moving from MPI to Dask and Dask.distributed) with 4 nodes(10.3.10.{31,32,33}) using SSH. I run the command line

$dask-ssh 10.3.10.{31,32,33}

which comes from https://distributed.readthedocs.io/en/latest/setup.html
but then I meet this error as follow:

---------------------------------------------------------------
                 Dask.distributed v1.19.3

Worker nodes:
  0: 10.3.10.31
  1: 10.3.10.32
  2: 10.3.10.33

scheduler node: 10.3.10.31:8786
---------------------------------------------------------------

[ scheduler 10.3.10.31:8786 ] : /root/miniconda3/envs/cubeenv/bin/python -m distributed.cli.dask_scheduler --port 8786
[ worker 10.3.10.32 ] : /root/miniconda3/envs/cubeenv/bin/python -m distributed.cli.dask_worker 10.3.10.31:8786 --nthreads 0 --nprocs 1 --host 10.3.10.32
[ worker 10.3.10.31 ] : /root/miniconda3/envs/cubeenv/bin/python -m distributed.cli.dask_worker 10.3.10.31:8786 --nthreads 0 --nprocs 1 --host 10.3.10.31
[ worker 10.3.10.33 ] : /root/miniconda3/envs/cubeenv/bin/python -m distributed.cli.dask_worker 10.3.10.31:8786 --nthreads 0 --nprocs 1 --host 10.3.10.33
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - -----------------------------------------------
[ worker 10.3.10.32 ] : distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.10.32:34463'
[ worker 10.3.10.33 ] : distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.10.33:43416'
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO -   Scheduler at:     tcp://10.3.10.31:8786
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO -        http at:                     :9786
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO -       bokeh at:                     :8787
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-6r74cbrs
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - -----------------------------------------------
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - Register tcp://10.3.10.33:46526
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - Register tcp://10.3.10.32:41717
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - Starting worker compute stream, tcp://10.3.10.32:41717
[ scheduler 10.3.10.31:8786 ] : distributed.scheduler - INFO - Starting worker compute stream, tcp://10.3.10.33:46526
[ worker 10.3.10.31 ] : distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.10.31:38305'
[ worker 10.3.10.32 ] : distributed.worker - INFO -       Start worker at:     tcp://10.3.10.32:41717
[ worker 10.3.10.32 ] : distributed.worker - INFO -          Listening to:     tcp://10.3.10.32:41717
[ worker 10.3.10.32 ] : distributed.worker - INFO -              nanny at:           10.3.10.32:34463
[ worker 10.3.10.32 ] : distributed.worker - INFO -              bokeh at:            10.3.10.32:8789
[ worker 10.3.10.32 ] : distributed.worker - INFO - Waiting to connect to:      tcp://10.3.10.31:8786
[ worker 10.3.10.32 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.32 ] : distributed.worker - INFO -               Threads:                         16
[ worker 10.3.10.32 ] : distributed.worker - INFO -                Memory:                   33.54 GB
[ worker 10.3.10.32 ] : distributed.worker - INFO -       Local Directory: /root/dask-worker-space/worker-454h81bj
[ worker 10.3.10.32 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.32 ] : distributed.worker - INFO -         Registered to:      tcp://10.3.10.31:8786
[ worker 10.3.10.32 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.33 ] : distributed.worker - INFO -       Start worker at:     tcp://10.3.10.33:46526
[ worker 10.3.10.33 ] : distributed.worker - INFO -          Listening to:     tcp://10.3.10.33:46526
[ worker 10.3.10.33 ] : distributed.worker - INFO -              nanny at:           10.3.10.33:43416
[ worker 10.3.10.33 ] : distributed.worker - INFO -              bokeh at:            10.3.10.33:8789
[ worker 10.3.10.33 ] : distributed.worker - INFO - Waiting to connect to:      tcp://10.3.10.31:8786
[ worker 10.3.10.33 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.33 ] : distributed.worker - INFO -               Threads:                         16
[ worker 10.3.10.33 ] : distributed.worker - INFO -                Memory:                   33.54 GB
[ worker 10.3.10.33 ] : distributed.worker - INFO -       Local Directory: /root/dask-worker-space/worker-uuc6blqt
[ worker 10.3.10.33 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.33 ] : distributed.worker - INFO -         Registered to:      tcp://10.3.10.31:8786
[ worker 10.3.10.33 ] : distributed.worker - INFO - -------------------------------------------------
[ worker 10.3.10.33 ] : distributed.core - WARNING - Event loop was unresponsive for 1.70s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
[ worker 10.3.10.32 ] : distributed.core - WARNING - Event loop was unresponsive for 1.70s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
**[ worker 10.3.10.33 ] : tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa427566048>, <tornado.concurrent.Future object at 0x7fa427562198>)
[ worker 10.3.10.33 ] : Traceback (most recent call last):
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback
[ worker 10.3.10.33 ] :     ret = callback()
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
[ worker 10.3.10.33 ] :     return fn(*args, **kwargs)
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
[ worker 10.3.10.33 ] :     future.result()
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
[ worker 10.3.10.33 ] :     raise_exc_info(self._exc_info)
[ worker 10.3.10.33 ] :   File "<string>", line 4, in raise_exc_info
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/tornado/gen.py", line 1069, in run
[ worker 10.3.10.33 ] :     yielded = self.gen.send(value)
[ worker 10.3.10.33 ] :   File "/root/miniconda3/envs/cubeenv/lib/python3.5/site-packages/distributed/worker.py", line 237, in heartbeat
[ worker 10.3.10.33 ] :     self.periodic_callbacks['heartbeat'].callback_time = response['heartbeat-interval'] * 1000
[ worker 10.3.10.32 ] : KeyError: 'heartbeat-interval'**

I want to what is the meaning of KeyError: 'heartbeat-interval'?

**Comment by mrocklin** [comment]
My guess is that you have different versions of dask on your different machines.

**Comment by mrocklin** [comment]
Any update on this?  Was this the problem?

**Comment by asqhaqs** [comment]
Sorry for late response
your answer is right and this problem has been solved, thanks very much!

**Comment by mrocklin** [comment]
Thanks for checking back in!
