### ISSUE TITLE
Clear task memory without deleting future

### ISSUE THREAD

**Issue by wtbarnes** [dask/distributed#1799]
I have large number of tasks I submit to the scheduler and each of these does some operation and then saves a numpy array to a file. I then have a single tasks that takes a list of all these files and assembles them into a single HDF5 file.

For each of the compute-and-save tasks, I would like to clear the memory used by that task (as the result is now saved to a file), but keep the Future returned by this task because this list of Futures is passed to the "assemble" function at the end after the large number of small tasks have finished.

Is there a way to release the memory used in each of these small tasks while still holding on to the future? The docs on [managing memory](http://distributed.readthedocs.io/en/latest/memory.html) seem to imply that the only way to do this is by cancelling the task.

## Pseudocode Example
```python
import numpy as np
import distributed
client = Client()

def compute_and_save(i):
    # compute some relatively small array arr
    fn = f'filename_{i}.txt'
    np.save(fn, arr)

def assemble_big_file(filenames):
    with open('myhdf5_file.h5','w') as hf:
        for f in filenames:
            # read file f
            # write file f to hf

iterable = np.arange(1000)
filenames_future = client.map(compute_and_save, iterable)
future = client.submit(assemble_big_file, filenames_future)
```

**Comment by mrocklin** [comment]
If the future is just holding onto a filename then I wouldn't expect it to
be very large in memory.  Dask will automatically clear any unneeded
intermediate value for which there is not a future.  Python will
automatically GC any object that was ephemerally created within your task
that was not returned.

**Comment by wtbarnes** [comment]
Ok. That's the behavior I would expect, but I think for some reason it is holding onto the intermediate result. Watching the distributed Dashboard (and top in the terminal), I see my memory usage steadily increase as each of the small tasks is run.

One reason is that the my function for each small task optionally does return the actual array,

```python
def compute_and_save(i, save_to_file=True):
    # compute some relatively small array arr
    if save_to_file:
        fn = f'filename_{i}.txt'
        np.save(fn, arr)
        return fn
    else:
        return arr
```

Is it possible that Dask looks at the function, sees two return statements, and decides to keep both `fn` and `arr` in memory because it cannot determine which will actually be returned by the function?

**Comment by mrocklin** [comment]
Dask does not look at the function.  It just runs it.  It's just normal
Python.

**Comment by mrocklin** [comment]
Any updates here?

You might also consider looking at the dashboard info pages to see all of the various pieces of data that the workers are holding onto explicitly and their expected size.

**Comment by wtbarnes** [comment]
Sorry I've not followed up on this. I will try to get around to looking at it again in the next day or two. Thanks for the tip re: the dashboard info pages.

**Comment by wtbarnes** [comment]
I think the original problem I encountered here was specific to my code and not an issue with Dask/distributed so I'm closing this issue.
