### ISSUE TITLE
Collect and send AWS credentials

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#180]
As we improve S3 support we might consider how best to send AWS credentials from a client machine with a local `.boto` or `.aws` file to the workers asked to do the actual reading from S3.

One approach would be to scrape the local file and propagate the existing `s3pars` dict that we use within the `read_block_from_s3` call run on each worker.  This is a bit tricky because, at the moment, we'll be sending credentials in the clear.  Presumably we could resolve this by relying on Tornado's built-in encryption features (how expensive is this?)

Is there a better way to do this?  Presumably this is a common problem.

Does AWS support the generation of short-term tokens to read that we should be passing around instead of the full credential?

**Comment by mrocklin** [comment]
Any thoughts on the right way to do this @martindurant ?

**Comment by martindurant** [comment]
A couple of thoughts:
- config files can of course be securely passed around using SSH (i.e., as part of provisioning)
- EC2 nodes will look for IAM roles to connect with, which can be configured as part of their launch (I don't know much about this)
- as described here http://boto3.readthedocs.org/en/latest/reference/services/sts.html the following code may be exactly the thing we need:
```python
boto3.client('sts').get_session_token(DurationSeconds=3600)
```
At the moment if you try to provide a SessionToken to S3FileSystem, it will get passed through to the Config object (and raise an error) instead of used in authentication.

**Comment by mrocklin** [comment]
The token indeed sounds very nice.  Presumably we would pass this as a parameter to our `distributed.s3.read_block_from_s3` function?

**Comment by martindurant** [comment]
Actually, it worked immediately (from one machine):
```
out = boto3.client('sts').get_session_token(DurationSeconds=3600)['Credentials']
s3 = S3FileSystem(key=out['AccessKeyId'], secret=out['SecretAccessKey'], aws_session_token=out['SessionToken'], anon=False)
s3.ls('')
```

**Comment by martindurant** [comment]
Yes, pass the temporary credentials around as s3pars

**Comment by mrocklin** [comment]
This is one of those things where I suspect you have more experience than I.  If it is easy for you to put up a small PR with this I'd be grateful.

**Comment by martindurant** [comment]
https://github.com/dask/s3fs/pull/28 in s3fs to call the temporary credentials. I think it belongs there. Unfortunately, it doesn't seem to work with moto, so I've marked the test xfail for now.

I have a simple change in distributed.s3.read_bytes to use this, but I'm not sure whether we want to force this on users or make it optional. Already we have the ability to pass s3fs objects to read_csv and read_bytes; as well as s3pars to both those _and_ to the new s3fss created on the workers.

**Comment by martindurant** [comment]
So sorry, this pushed into master - can you repair, please? https://github.com/dask/distributed/commit/af8f939dd496b3106be0b575d3fe8b51874658dd

**Comment by mrocklin** [comment]
Changing history on master is sufficiently dangerous that I suggest we don't attempt it.  I suggest that we just build on top of it.

**Comment by martindurant** [comment]
Recommend to close. 
The situation now is that a delegate token is produced if explicit key/secret were used, otherwise the env variables, config files or IAM roles are expected to be correctly in place for every worker.
