### ISSUE TITLE
The client.gather() error:       IndexError: tuple index out of range

### ISSUE THREAD

**Issue by asqhaqs** [dask/distributed#1805]
I am setting up a cluster for 3 nodes(10.3.10.{31,32,33}) using SSH.  The scheduler and worker works well , but when I try a  simple  example  shown on  http://dask.pydata.org/en/latest/futures.html  (the follow is code)

client = Client('127.0.0.1:8786') 
a = client.submit(add, 1, 2)
b = client.submit(add, 10, 20)
c = client.submit(add, a, b)
client.gather(c) 

I meet the error as follow:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-9d5d93790822> in <module>()
      3 b = client.submit(add, 10, 20)
      4 c = client.submit(add, a, b)
----> 5 client.gather(c)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1476             return self.sync(self._gather, futures, errors=errors,
   1477                              direct=direct, local_worker=local_worker,
-> 1478                              asynchronous=asynchronous)
   1479 
   1480     @gen.coroutine

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    601             return future
    602         else:
--> 603             return sync(self.loop, func, *args, **kwargs)
    604 
    605     def __repr__(self):

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    251             e.wait(10)
    252     if error[0]:
--> 253         six.reraise(*error[0])
    254     else:
    255         return result[0]

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
    685             raise value.with_traceback(tb)
--> 686         raise value
    687 
    688 else:

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/utils.py in f()
    235             yield gen.moment
    236             thread_state.asynchronous = True
--> 237             result[0] = yield make_coro()
    238         except Exception as exc:
    239             logger.exception(exc)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1053 
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1354                             six.reraise(type(exception),
   1355                                         exception,
-> 1356                                         traceback)
   1357                     if errors == 'skip':
   1358                         bad_keys.add(key)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

<ipython-input-4-a74cc296e40c> in add()
      3 
      4 def add(x, y):
----> 5     return x + y
      6 a = client.submit(inc, 10)  # calls inc(10) in background thread or process
      7 b = client.submit(inc, 20)

IndexError: tuple index out of range

and the logs of the scheduler and worker is  as follow:
10.3.10.31(shceduler)
![sche](https://user-images.githubusercontent.com/14349360/36948857-bf76d1be-201b-11e8-84d2-3cc19352a5be.png)

10.3.10.32(worker)

![worker1](https://user-images.githubusercontent.com/14349360/36948863-c91253c4-201b-11e8-9504-306300fd1334.png)

10.3.10.33(worker)

![worker2](https://user-images.githubusercontent.com/14349360/36948872-d940e6d4-201b-11e8-9ba0-0494729c8b20.png)

**Comment by mrocklin** [comment]
Unfortunately this seems to work fine for me:

```python
In [1]: from dask.distributed import Client

In [2]: client = Client()

In [3]: def add(x, y):
   ...:     return x + y
   ...: 

In [4]: a = client.submit(add, 1, 2)
   ...: b = client.submit(add, 10, 20)
   ...: c = client.submit(add, a, b)
   ...: client.gather(c)
   ...: 
Out[4]: 33
```

**Comment by asqhaqs** [comment]
Yes it also work for me by using  
"client = Client()"
![result](https://user-images.githubusercontent.com/14349360/36949265-e35dcb3c-2020-11e8-9ef2-027a68e4b873.png)

but when I use  client = Client('127.0.0.1:8786')   it will be error
![result2](https://user-images.githubusercontent.com/14349360/36949308-67c7280a-2021-11e8-9fac-b56631f8ce74.png)

I don't know what's the difference between  the two functions

**Comment by mrocklin** [comment]
My guess is that there is something wrong with your environment.  I
recommend client.get_versions(check=True)

**Comment by asqhaqs** [comment]
yes some package versions are incongruous so I update these package,
the result of client.get_versions(check=True) is shown as follow

{'client': {'host': [('python', '3.6.4.final.0'),
('python-bits', 64),
('OS', 'Linux'),
('OS-release', '3.10.0-327.28.3.el7.x86_64'),
('machine', 'x86_64'),
('processor', 'x86_64'),
('byteorder', 'little'),
('LC_ALL', 'None'),
('LANG', 'en_US.UTF-8'),
('LOCALE', 'en_US.UTF-8')],
'packages': {'optional': [('numpy', '1.14.1'),
('pandas', '0.22.0'),
('bokeh', '0.12.14'),
('lz4', '0.10.1'),
('blosc', None)],
'required': [('dask', '0.17.1'),
('distributed', '1.21.1'),
('msgpack', '0.5.5'),
('cloudpickle', '0.5.2'),
('tornado', '4.5.3'),
('toolz', '0.8.2')]}},
'scheduler': {'host': [['python', '3.6.4.final.0'],
['python-bits', 64],
['OS', 'Linux'],
['OS-release', '3.10.0-327.28.3.el7.x86_64'],
['machine', 'x86_64'],
['processor', 'x86_64'],
['byteorder', 'little'],
['LC_ALL', 'None'],
['LANG', 'en_US.UTF-8'],
['LOCALE', 'en_US.UTF-8']],
'packages': {'optional': [['numpy', '1.14.1'],
['pandas', '0.22.0'],
['bokeh', '0.12.14'],
['lz4', '0.10.1'],
['blosc', None]],
'required': [['dask', '0.17.1'],
['distributed', '1.21.1'],
['msgpack', '0.5.5'],
['cloudpickle', '0.5.2'],
['tornado', '4.5.3'],
['toolz', '0.8.2']]}},
'workers': {'tcp://10.3.10.32:45917': {'host': [['python', '3.5.4.final.0'],
['python-bits', 64],
['OS', 'Linux'],
['OS-release', '3.10.0-327.28.3.el7.x86_64'],
['machine', 'x86_64'],
['processor', 'x86_64'],
['byteorder', 'little'],
['LC_ALL', 'None'],
['LANG', 'en_US.UTF-8'],
['LOCALE', 'en_US.UTF-8']],
'packages': {'optional': [['numpy', '1.14.1'],
['pandas', '0.22.0'],
['bokeh', '0.12.14'],
['lz4', '0.10.1'],
['blosc', None]],
'required': [['dask', '0.17.1'],
['distributed', '1.21.1'],
['msgpack', '0.5.5'],
['cloudpickle', '0.5.2'],
['tornado', '4.5.3'],
['toolz', '0.8.2']]}},
'tcp://10.3.10.33:41451': {'host': [['python', '3.5.4.final.0'],
['python-bits', 64],
['OS', 'Linux'],
['OS-release', '3.10.0-327.28.3.el7.x86_64'],
['machine', 'x86_64'],
['processor', 'x86_64'],
['byteorder', 'little'],
['LC_ALL', 'None'],
['LANG', 'en_US.UTF-8'],
['LOCALE', 'en_US.UTF-8']],
'packages': {'optional': [['numpy', '1.14.1'],
['pandas', '0.22.0'],
['bokeh', '0.12.14'],
['lz4', '0.10.1'],
['blosc', None]],
'required': [['dask', '0.17.1'],
['distributed', '1.21.1'],
['msgpack', '0.5.5'],
['cloudpickle', '0.5.2'],
['tornado', '4.5.3'],
['toolz', '0.8.2']]}}}}
----------------------------------------------------------------------------------------------------------

and I think the the problem of version has been solved，  
but I still meet this error although this error log is different from the before   (also I  cant submit other task on the distributed environment)
and the logs is shown as follow:

IndexError Traceback (most recent call last)
in ()
7 b = client.submit(add, 10, 20)
8 c = client.submit(add, a, b)
----> 9 client.gather(c)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
1476 return self.sync(self._gather, futures, errors=errors,
1477 direct=direct, local_worker=local_worker,
-> 1478 asynchronous=asynchronous)
1479
1480 @gen.coroutine

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
601 return future
602 else:
--> 603 return sync(self.loop, func, *args, **kwargs)
604
605 def repr(self):

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
251 e.wait(10)
252 if error[0]:
--> 253 six.reraise(*error[0])
254 else:
255 return result[0]

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
684 if value.traceback is not tb:
685 raise value.with_traceback(tb)
--> 686 raise value
687
688 else:

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/utils.py in f()
235 yield gen.moment
236 thread_state.asynchronous = True
--> 237 result[0] = yield make_coro()
238 except Exception as exc:
239 logger.exception(exc)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/gen.py in run(self)
1053
1054 try:
-> 1055 value = future.result()
1056 except Exception:
1057 self.had_exception = True

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
236 if self._exc_info is not None:
237 try:
--> 238 raise_exc_info(self._exc_info)
239 finally:
240 self = None

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/tornado/gen.py in run(self)
1061 if exc_info is not None:
1062 try:
-> 1063 yielded = self.gen.throw(*exc_info)
1064 finally:
1065 # Break up a reference to itself

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
1354 six.reraise(type(exception),
1355 exception,
-> 1356 traceback)
1357 if errors == 'skip':
1358 bad_keys.add(key)

/root/miniconda3/envs/cubeenv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
683 value = tp()
684 if value.traceback is not tb:
--> 685 raise value.with_traceback(tb)
686 raise value
687

in add()
1
2 def add(x, y):
----> 3 return x + y
4
5

IndexError: tuple index out of range

**Comment by mrocklin** [comment]
Understood.  Unfortunately I'm unable to reproduce this problem on any machine to which I have access, so I'm not sure how best to help.  My guess is that the problem lies somewhere in your machines and how things are set up, but I'm afraid I don't know how to go about diagnosing this.  I apologize I'm unable to offer you a ready solution.

**Comment by asqhaqs** [comment]
may it be this problem?
the python version of my work node is 3.5  and  my scheduler node's python version is 3.6

**Comment by mrocklin** [comment]
That should be fine, but it's worth trying

**Comment by asqhaqs** [comment]
Yes I got it ,that is because of this reason

**Comment by mrocklin** [comment]
Excellent, I'm glad to hear that you have resolved this

**Comment by asqhaqs** [comment]
and I will aslo thanks for your patient response
