### ISSUE TITLE
Cannot properly upload files with multiple modules or modules with an underscore in their name

### ISSUE THREAD

**Issue by awroe** [dask/distributed#1819]
When using the client.upload_file method to upload an egg file, the upload fails if the name of the module and resulting egg file contain an underscore character. In addition, only the package whose name matches the name of the egg file is imported and reloaded.

For example, if you make an egg file from a module "test_module",

`client.upload_file("test_module-1.0-py3.6.egg") `

attempts to import and then reload a module "test-module" (and then fails as a result), even though the original module was "test_module".

In addition it does not appear import any other modules in this egg file.

This appears to be down to the implementation of the import_file method in utils.py (called from the worker). 

This uses pkg_resources.find_distributions to get the project_name from the egg file, and then assumes that this project name is the name of the module to import and reload later. However, the package name has had 'safe_name' called on it when it was created, which converts any non alpha-numeric characters into hyphens.

**Comment by mrocklin** [comment]
Thank you for the excellent bug report and the diagnosis.  I agree that this seems like an important bug to fix.  Do you have any interest in taking this a step further and submitting a PR with a patch?

**Comment by awroe** [comment]
I don't know much about the python internals, so I don't know exactly how to fix this (though there's a method called walk_packages that looks promising). If I get some time I will try and look at a patch.

**Comment by mrocklin** [comment]
@awroe have you had time to investigate a fix for this?  No worries if not, just checking in.

**Comment by awroe** [comment]
Sorry, not had any time so far.

**Comment by charmoniumQ** [comment]
[Line of code in question](https://github.com/dask/distributed/blob/b36e87d14e75c0cbdd0e3292ac65db2a836f74bd/distributed/utils.py#L1044)

[`top_level.txt`](https://setuptools.readthedocs.io/en/latest/formats.html#top-level-txt-conflict-management-metadata) has the top-level package names. If you want to import beyond that, you could iterate over [`SOURCES.txt`](https://setuptools.readthedocs.io/en/latest/formats.html#sources-txt-source-files-manifest).
