### ISSUE TITLE
Client fails to submit graph with None value due to get_dependencies input cleaning

### ISSUE THREAD

**Issue by dancollins34** [dask/distributed#1821]
This should be a valid call:

```python
from distributed import Client

if __name__ == "__main__":
    client = Client()
    x= client.get({"a": None}, "a")  # x should be None
```

However, it fails at line 1994 of client.py:

```python
for k, v in dsk3.items():
    dependencies[k] |= get_dependencies(dsk3, task=v)
```

Because get_dependencies, seeing that the value of key= and task= are None raises an exception.  I'd propose replacing this with:

```python
for k, v in dsk3.items():
    if v is not None:
        dependencies[k] |= get_dependencies(dsk3, task=v)
```

**Comment by dancollins34** [comment]
This may require a bit more work, as making this change then throws TypeErrors on workers

**Comment by mrocklin** [comment]
Generally it sounds like we should test `None` values more explicitly.  There might be a few places in the system that get tripped up by this.  In other cases use a `'--no-default--'` sentinel value for situations like this.

**Comment by jrbourbeau** [comment]
@dancollins34 this no longer seems to be an issue on the current `master` branch:

```python
In [1]: from distributed import Client

In [2]: client = Client()

In [3]: x = client.get({"a": None}, "a")

In [4]: type(x)
Out[4]: NoneType
```

Is it safe to close this issue?

**Comment by jrbourbeau** [comment]
Closing as the originally posted issue appears to be resolves. @dancollins34 please feel free to re-open this issue if this is not the case. Thanks!
