### ISSUE TITLE
Memory leak(?)

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#1824]
[EDIT: Looks like the issue is unrelated to queues so I reduced further the example and updated the title]

I've been trying to debug an apparent memory leak and I managed to reduce it to the following example:

```python
import gc
import time
import distributed
import memory_profiler

def run_forever(timeout=30):
    while True:
        consume(timeout)

@memory_profiler.profile(precision=2)
def consume(timeout):
    time.sleep(timeout)
    gc.collect()

if __name__ == '__main__':
    client = distributed.Client()
    run_forever()
```

### Observations:
- The memory profiler reports a ~0.5MB increase on every iteration.
- The amount of allocated memory correlates positively with the timeout. Thus reducing the number of calls by providing a longer timeout does not help.
- `gc.collect()` has no effect.
- The overall effect on memory usage (at least for the original code, not sure about the reduced example) is a steady increase until the max allocated size is reached, then a sawtooth-shaped wave for a few times and finally a flat line at the max size. At this point the program apparently becomes unresponsive, without throwing a `MemoryError` or exiting in any way.
![memory](https://user-images.githubusercontent.com/291289/37176952-9d362e70-2326-11e8-9841-8e52c11e40fc.png)

### Versions
- python 3.6.4
- distributed 1.20.2
- memory-profiler 0.50.0

**Comment by gsakkis** [comment]
I ran the example with different `distributed` versions:
- The latest (1.21.3) has more or less the same behavior.
- 1.20.1 seems to leak too but at a lower pace (0.2MB vs 0.5+MB for 1.20.2 or later)

**Comment by mrocklin** [comment]
This is also informative:

```python

import gc
import time
import distributed
import weakref

import memory_profiler

def run_forever(timeout=30):
    while True:
        consume(timeout)


last = weakref.WeakValueDictionary()

@memory_profiler.profile(precision=2)
def consume(timeout):
    time.sleep(timeout)
    gc.collect()
    print('-------------------------------------------------------')
    for obj in gc.get_objects():
        if id(obj) not in last:
            try:
                last[id(obj)] = obj
            except TypeError:
                pass
            else:
                print(obj)


if __name__ == '__main__':
    client = distributed.Client()
    run_forever()
```

**Comment by gsakkis** [comment]
I tried some changes to the original code and lo and behold, the memory reaches a significantly lower plateau at ~2.4GB (down from 8+ GB).
![memory-fixed](https://user-images.githubusercontent.com/291289/37220940-d9795060-23d0-11e8-90e8-e2fe2860b71e.png)

The pertinent changes were:

- Upgraded dask from from 0.16.1 to 0.17.1
- Upgraded distributed from 1.20.2 to 1.21.2
- Removed a `client.run(_monkeypatch_dask_dataframe_parquet)` call at initialization, where `_monkeypatch_dask_dataframe_parquet` was monkeypatching Dask 0.16.1 with the fix of https://github.com/dask/dask/pull/3142/.

So I'm guessing that the posted example also plateaus sooner or later without growing indefinitely. 

Thanks for looking into it, feel free to close the issue. Still curious whether the cause was a bug in dask and/or distributed fixed recently, or the `client.run()` call to apply the monkeypatching.
