### ISSUE TITLE
Workers handling more tasks than they should.

### ISSUE THREAD

**Issue by sheridp** [dask/distributed#1844]
I might be confused as to how dask.distributed should be working, but I am starting the worker with 
`--nthreads 1 --nprocs 1` so that it can only work on one task at a time.  Nonetheless, I see that if I submit more tasks than I have workers, some workers will be running multiple tasks simultaneously.  Really not sure how this is possible unless these parameters are being ignored.
My tasks have side effects to the filesystem so I can verify that all tasks are starting simultaneously.

**Comment by mrocklin** [comment]
A worker with one thread will, under normal operation, only execute a single task at a time.  Underneath we're using a mostly-standard `concurrent.futures.ThreadPoolExecutor` with the number of threads that you have specified.

I recommend trying to construct a minimal example that demonstrates your issue.

**Comment by sheridp** [comment]
Here is a minimal example

```
from distributed import Client
client = Client('scheduler:8786')
print(client) 
# <Client: scheduler='tcp://172.19.0.2:8786' processes=1 cores=1>

def test():
    import time
    import datetime
    start = datetime.datetime.now()
    time.sleep(10)
    return start

futures = []
for _ in range(3):
    futures.append(client.submit(test))

print(client.gather(futures))

#[datetime.datetime(2018, 3, 19, 23, 47, 16, 34867),
#datetime.datetime(2018, 3, 19, 23, 47, 16, 34867),
#datetime.datetime(2018, 3, 19, 23, 47, 16, 34867)]
```

I would have thought the start times would be spaced out by 10 seconds each since there is 1 worker with 1 thread and each task takes ~10s to complete

**Comment by sheridp** [comment]
It looks like my nthreads argument is being accepted:
```
worker_1     | distributed.worker - INFO -       Start worker at:     tcp://172.19.0.3:41363
worker_1     | distributed.worker - INFO -          Listening to:     tcp://172.19.0.3:41363
worker_1     | distributed.worker - INFO -              nanny at:           172.19.0.3:44705
worker_1     | distributed.worker - INFO -              bokeh at:            172.19.0.3:8789
worker_1     | distributed.worker - INFO - Waiting to connect to:       tcp://scheduler:8786
worker_1     | distributed.worker - INFO - -------------------------------------------------
worker_1     | distributed.worker - INFO -               Threads:                          1
worker_1     | distributed.worker - INFO -                Memory:                    8.33 GB
worker_1     | distributed.worker - INFO -       Local Directory:      /home/worker-hg6j_2fa
```

**Comment by mrocklin** [comment]
In this case all three of those futures is the same.  By default dask assumes that a function called on the same arguments will produce the same result.  Try the same thing but with `client.submit(test, pure=False)`


```python
from distributed import Client
client = Client(threads_per_worker=1, n_workers=1)

def test():
    import time
    import datetime
    start = datetime.datetime.now()
    time.sleep(10)
    return start

futures = []
for _ in range(3):
    futures.append(client.submit(test, pure=False))
futures
client.gather(futures)
```

```
[datetime.datetime(2018, 3, 19, 20, 6, 50, 261526),
 datetime.datetime(2018, 3, 19, 20, 7, 0, 271792),
 datetime.datetime(2018, 3, 19, 20, 7, 10, 287537)]
```

**Comment by sheridp** [comment]
I found the source of my problem:  my function used a worker_client() context, causing it to secede from the the thread executor pull.

**Comment by mrocklin** [comment]
That would do it

On Tue, Mar 20, 2018 at 11:53 PM, Patrick Sheridan <notifications@github.com
