### ISSUE TITLE
Scheduler workers and Cluster workers desynchronise

### ISSUE THREAD

**Issue by mattilyra** [dask/distributed#1857]
There is an issue with Adaptive cluster deployments with the `scheduler.workers` and `cluster.workers` desynchronising.  This is likely related to #1674 as I saw those same errors in the logs when this happens. I haven't nailed down exactly why this happens and how to reproduce it, but my test env was running an adaptive `LocalCluster` in a docker container.

It seems to be the case that docker kills worker processes that don't fit onto the container anymore, the scheduler correctly removes them from its copy of `workers` but the `cluster` instance doesn't. This results in `scale_up` not doing anything anymore, as the `cluster` instance still thinks there are plenty of workers left in the cluster although these worker are long gone from the scheduler.

This is not only an issue with `LocalCluster` though, as any cluster deployment where the workers' tcp stream suddenly closes should experience the same issues.

It isn't clear however where the issue lies and how widespread it is, so some work needs to be done to isolate the problem.

**Comment by mattilyra** [comment]
This was tested on the current upstream HEAD

**Comment by mrocklin** [comment]
Yeah, I think that in some of the other cluster implementations we've stopped trusting the local accounting of workers from the cluster's perspective.  There are certainly problems with this though as it misses workers that are in the process of being spun up.

**Comment by mattilyra** [comment]
The `scale_up` issue actually seems to have been fixed two weeks ago by calculating the difference between desired and actual workers from the ones the scheduler know about not the ones local cluster has.

**Comment by mrocklin** [comment]
I'm inclined to close this for now.  I agree that cluster objects should ideally have a way to track workers that are in the process of spinning up, this probably has to happen in all of the downstream cluster manager libraries though.
