### ISSUE TITLE
RTD failing

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1859]
Appears that RTD has been failing for 3wks. Seems to be getting hung up on Python 3 syntax when building on Python 2. Not sure what caused the change as the previous passing build also built on Python 2. In any event, might be worth just building the docs with Python 3 if possible to avoid issues like this.

Previous: https://readthedocs.org/projects/distributed/builds/6832897/
Next: https://readthedocs.org/projects/distributed/builds/6834955/

**Comment by mrocklin** [comment]
I changed it to 3.x.  It looks like there are still failures though.

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/distributed/commit/ff62d2c3add44071c04073ea071c3969547377a9
