### ISSUE TITLE
Workers perpetually restarting with LocalCluster on Windows 

### ISSUE THREAD

**Issue by krishnand** [dask/distributed#1879]
I'm trying to execute a simple LocalCluster sample on my Windows env and run into errors of this kind: 

distributed.nanny - WARNING - Worker process 162408 was killed by signal 15
distributed.nanny - WARNING - Restarting worker

Here's the sample:
```python
from distributed import Client, LocalCluster

def inc(x):    
    return x + 1

if __name__ == '__main__':
    cluster = LocalCluster()
    client = Client(cluster)
    f = client.submit(inc, 1)
    print(f.result())
```

Env details:
**Windows 10 (v 1709)**

C:\WINDOWS\system32>python -V
**Python 3.5.2 :: Continuum Analytics, Inc.**

C:\WINDOWS\system32>pip freeze | grep dask
**dask==0.17.2**

C:\WINDOWS\system32>pip freeze | grep distributed
**distributed==1.21.4**

Is this a known issue?

**Comment by mrocklin** [comment]
No.  This is not known.  Can i ask you to try this under git master?

    pip install git+https://github.com/dask/distributed.git --upgrade --no-deps

Also, can you create your LocalCluster with the following:

    LocalCluster(silence_logs=False)

and report back what it returns during a few of the restart cycles?

**Comment by krishnand** [comment]
The logs aren't too useful and show pretty much the same info over multiple restart cycles --
[log.txt](https://github.com/dask/distributed/files/1864425/log.txt). I have multiple envs on my machine and both 1.21.3 and 1.21.4 seem to have this bug. **Importantly, the upgrade works!** and do not see this issue anymore.  If I may, what in the new build fixes this issue?

**Comment by mrocklin** [comment]
Thank you for checking.  This is valuable information.  The likely fix was
https://github.com/dask/distributed/pull/1865

I'll be releasing a new version with this update sometime soon.

**Comment by krishnand** [comment]
Great. So this was the Nanny process itself being timed-out... Is this more pronounced on Win systems due to process creation being more expensive than forks on UNIX/Linux?

**Comment by mrocklin** [comment]
Yes, that was my thought as well.  It is also being reported by other users
on large HPC systems that also have long startup times.

**Comment by krishnand** [comment]
Thanks for quick turnaround! I will close this issue now and upgrade as new build becomes available.
