### ISSUE TITLE
get_dataset raises KeyError or NameError

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1881]
Depending on the particular circumstance, which I haven't fully narrowed down yet, it appears `get_dataset` will raise either a `KeyError` or `NameError`. Would be nice if one of these was picked and standardized around.

**Comment by mrocklin** [comment]
Why was this closed?

**Comment by jakirkham** [comment]
I was mistaken as far as where the exception was coming from. Sorry for the noise.
