### ISSUE TITLE
Numeric environment variable configuration is broken

### ISSUE THREAD

**Issue by Spacerat** [dask/distributed#1884]
I recently found that a pipeline was throwing this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/utils.py", line 623, in log_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/distributed/scheduler.py", line 1591, in remove_worker
    if ts.suspicious > self.allowed_failures:
TypeError: '>' not supported between instances of 'int' and 'str'
```
The environment variable `DASK_ALLOWED_FAILURES=20` had been set. In a new terminal I ran the following:
```pya
>>> LocalCluster().scheduler.allowed_failures
'20'
```
There appears to be nothing in the code which ensures that the type of a configuration variable conforms to the expected type.

I'd be happy to submit a PR to fix this but I'm not really sure what form it should take. Some ideas:
1. Remove environment variable configuration completely (it doesn't seem to be documented?)
2. Use `pyyaml` to interpret environment variables the same way yaml interprets them
    - (introduces are hard dependency on `pyyaml`)
3. Approximate the above by just automatically casting all env var config variables to ints where possible
4. Make a `get_config` which casts its return value to be the same type as the provided default; replace `config.get` everywhere. e.g.
```py
def get_config(key, default=None):
    if default is not None:
        return type(default)(config.get(key, default=default))
    return config.get(key)
```
5. Change the `config` dict to be an instance of a subclass of dict which has `get()` overridden to behave as suggested above
6. Change `config.py` to use the example `yaml` file to correctly cast all config variables
7. Cast variables correctly at the point of `get` everywhere
    - e.g. `ALLOWED_FAILURES = int(config.get('allowed-failures', 3))`

I think I'd probably go with 3, which seems like the lowest impact solution.

Of course, the workaround for now is to just use a yaml configuration file.

**Comment by mrocklin** [comment]
Yes, this seems like a good summary of the problem and of possible solutions.  I agree that option 3 is a nice place to start.  I might add the request that we also support floats, perhaps with an approach like the following:

```python
def parse(x):
    try:
        x = float(x)
    except ValueError:
        return x
    if int(x) == x:
        return int(x)
    else:
        return x
```

> I'd be happy to submit a PR to fix this ...

Thank you for being willing to help here.  That would be quite welcome.

I also wouldn't be surprised if we eventually establish a more thorough configuration system.  Until then this would be a very welcome addition.

**Comment by Spacerat** [comment]
Sounds good! I made a PR #1885 which supports floats and also booleans.
