### ISSUE TITLE
Option to shutdown adaptive cluster

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1898]
During shutdown of a cluster, sometimes the adaptive portion springs back to life and requests workers. To workaround that, have started calling `cluster._adaptive.stop()` as a hack as that appears to close out the existing adaptive instance. However it would be nice if there was a more standard way to handle this as part of cluster shutdown. Thoughts on how this should be done?

**Comment by mrocklin** [comment]
Perhaps we could register the Adaptive object as an extension with the Scheduler.  Then if we implement a `.teardown` method it will be called as part of the closing process.  

```python
    def close(...):
        ...
        for ext in self.extensions:
            with ignoring(AttributeError):
                ext.teardown()
```

This creates a circular reference, but that's probably ok.  We'll also want to remove adaptive from Scheduler.extensions if it goes away (or is replaced by another adaptive object)

**Comment by jakirkham** [comment]
Are you planning on removing or replacing Adaptive somehow?

**Comment by mrocklin** [comment]
What I meant was that whenever you call `cluster.adapt()` you currently create a new `Adaptive` object.  We want to avoid accumulating many Adaptive object in Scheduler.extensions

**Comment by jakirkham** [comment]
Ah ok. Thanks for clarifying.

**Comment by jakirkham** [comment]
What if we add a `close` method to `Cluster`?

**Comment by mrocklin** [comment]
That would be fine.  We would have to add super calls to the downstream
implementations, but this is probably a good idea regardless.
