### ISSUE TITLE
HPC cluster workers preload file not found

### ISSUE THREAD

**Issue by wielrenner** [dask/distributed#1915]
I'm launching multiple (in this case 40, but it doesn't matter) DASK workers at the same time on a HPC using a job scheduler. They start running almost at the same time and are preloading the same dask_preload.py file. Some (approximately half of them) workers die immediately with the following error, the others start up correctly:

```
Traceback (most recent call last):
  File "/python_virtualenv/bin/dask-worker", line 11, in <module>
    sys.exit(go())
  File "/python_virtualenv/lib/python2.7/site-packages/distributed/cli/dask_worker.py", line 252, in go
    main()
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/python_virtualenv/lib/python2.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/python_virtualenv/lib/python2.7/site-packages/distributed/preloading.py", line 32, in validate_preload_argv
    preload_modules = _import_modules(ctx.params.get("preload"))
  File "/python_virtualenv/lib/python2.7/site-packages/distributed/preloading.py", line 92, in _import_modules
    module = import_file(name)[0]
  File "/python_virtualenv/lib/python2.7/site-packages/distributed/utils.py", line 1003, in import_file
    os.remove(cache_file)
OSError: [Errno 2] No such file or directory: 'dask_preload.pyc'
```

I can schedule workers to start 1 at a time. But first I want to know if it is possible to fix this within the scheduler code itself?

Btw. If I start 1 worker, it is able to load the dask_preload.py file.

**Comment by mrocklin** [comment]
Interesting!  My first guess would be some sort of race condition with the file system and the Python import system?  I would be curious to know if this issue persists in Python 3.

**Comment by wielrenner** [comment]
Python 3 gives me an error alike the one of Python 2. 
`FileNotFoundError: [Errno 2] No such file or directory: '/hpc/data/ada4euv/users/wroosmal/csi_ada/ada_lib/doc/hpc/__pycache__/dask_preload.cpython-35.pyc'`

**Comment by mrocklin** [comment]
OK, not fixed in Python 2 then.  Again, my guess is something related to
slow/inconsistent network file system and race conditions with Python
imports.

@pitrou might find this problem interesting (though he may not have the
time to actually solve it)

**Comment by pitrou** [comment]
This looks like a benign case of race condition in https://github.com/dask/distributed/blob/master/distributed/utils.py#L1000-L1003.

Just replace:
```python
if os.path.exists(cache_file):
    os.remove(cache_file)
```
with:
```python
try:
    os.remove(cache_file)
except OSError:
    pass  # ignore "file not found"
```
(you can refine the exception check by querying errno)

**Comment by mrocklin** [comment]
Ah, I'm glad to see this.  I'm curious though, what happens if someone gives us a pyc file directly?  Should we only be removing this file if they ask us to import a `.py` file?

**Comment by pitrou** [comment]
What would be the case for giving us a pyc file? I think the only reason for that would be proprietary software where the source code isn't supplied, in which case you probably don't want to remove the pyc file :-)

**Comment by mrocklin** [comment]
Great.  Just checking :)  Thanks for the quick answer @pitrou !

**Comment by wielrenner** [comment]
Is this something to change in a next release? Or a custom change specific to this use case?

**Comment by mrocklin** [comment]
Yes, what @pitrou proposes is an easy fix.  I have a fix locally that I'll
push up in a bit.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/pull/1921

**Comment by mrocklin** [comment]
This should now be resolved.  Thanks all @wielrenner and @pitrou for reporting and diagnosing this!
