### ISSUE TITLE
http module disappeared

### ISSUE THREAD

**Issue by farquet** [dask/distributed#1916]
Hello,
Upgrading to the latest versions of distributed (and dask), the whole http module has disappeared. I cannot find the HTTPScheduler anywhere else. Is this change documented somewhere ?
```
    from distributed.http import HTTPScheduler
E   ImportError: No module named http
```
I upgraded from distributed 1.19.3 to distributed 1.21.6.
Thanks

**Comment by mrocklin** [comment]
That's true, we removed it a while ago.  Some of the routes are still
available here: http://localhost:8787/json/index.html

**Comment by farquet** [comment]
So what is the new approach to get an HTTPScheduler ?

**Comment by mrocklin** [comment]
There is none.  It was removed.  I apologize if I wasn't sufficiently clear about that above.  We tend to serve JSON routes directly from the bokeh scheduler. If there was some route that you are missing in particular then you might consider raising an issue about it or, better yet, take a look at the code below and see if you're willing to submit a PR.

https://github.com/dask/distributed/blob/9678c1448b7d86185e368bf4960633b16ea636f6/distributed/bokeh/scheduler_html.py#L143-L166

**Comment by farquet** [comment]
Alright. I got your point.
Thanks !
