### ISSUE TITLE
Progressbar on list of delayed objects 

### ISSUE THREAD

**Issue by alvarouc** [dask/distributed#1918]
I have a list of delayed objects in "scores". Following the documentation, I should be able to do 
```
from dask import compute, persist
from dask.distributed import progress
...
x = persist(scores)  # start computation in the background
progress(x)  # watch progress
scores = compute(x[0])[0]
```

The problem is that the progress bar in the terminal shows a 100% bar immediately. I can observe with the dashboard that the computation is still going for about 10 minutes. 

Am I doing something wrong here? The docs are not explicit for the list of delayed objects.

**Comment by mrocklin** [comment]
Perhaps they are already in memory?  If you call x[0].compute() does it
return immediately?

**Comment by mrocklin** [comment]
Can I ask you for a reproducible example?  Just something that someone can
copy-paste to reproduce the problem.  Perhaps you could construct a
function that uses time.sleep rather than your actual computation.

**Comment by alvarouc** [comment]
```
from dask import compute, persist, delayed
from dask.distributed import progress, Client
from time import sleep


@delayed
def task(delay):
    sleep(delay)
    return delay


if __name__ == '__main__':
    client = Client('20670:8786')  # Change accordingly
    scores = [task(x) for x in range(1, 20)]
    x = persist(scores)  # start computation in the background
    progress(x)  # watch progress
    scores = compute(x)  # wait until completed
    print('Done')

```

**Comment by mrocklin** [comment]
In this case I think you want the following:

    x = persist(*scores)  # start computation in the background

Persist takes many arguments.  It currently doesn't dive into each element of a list, though perhaps it should.

**Comment by mrocklin** [comment]
@martindurant if you're around an interested this would be useful to solve.  The change probably needs to be made in `distributed/client.py:Client.persist`.  We should verify that this *would* work with the local scheduler as well (I suspect that it does).

**Comment by mrocklin** [comment]
@alvarouc thank you for the reproducible example by the way!  It was very helpful to quickly identify the problem.

**Comment by martindurant** [comment]
The error appears to be in `dask.persist`; if you call `persist(scores)`, this does not call `client.persist` at all, but `persist(*scores)` does. `client.persist` works with either `scores` or `*scores`.
