### ISSUE TITLE
DASK distributed import Client error (ImportError: cannot import name future_set_exc_info)

### ISSUE THREAD

**Issue by NatLun091238** [dask/distributed#1924]
Hi! Along the line of "Import error in `dask-scheduler` #1120", there is another problem. I use Datalab instance on Google cloud platform (GCP). For DASK installation I use the following command in a cell:
`!pip install dask[complete] distributed --upgrade `
Installation goes well and I can verify it:
`!dask-scheduler ` which produce an output:

`distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-XAWu9a
distributed.scheduler - INFO - -----------------------------------------------
`

On the other hand, I get 

` ImportError: cannot import name future_set_exc_info` pointing to
`100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
 101                                 future_add_done_callback, future_set_result_unless_cancelled)`

when I call `from distributed import Client`..........
Any ideas how to solve this???

**Comment by mrocklin** [comment]
If you are able to provide a minimal example and full traceback that would make it easier to understand your situation.

**Comment by NatLun091238** [comment]
I run this
`# coding: utf-8

# In[ ]:


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import pandas as pd, tensorflow as tf, numpy as np
from google.datalab import Context
import google.datalab.ml as ml
import google.datalab.storage as storage
import random, string
import datetime as dt
import time
import shutil

try:
  from StringIO import StringIO
except ImportError:
  from io import BytesIO as StringIO

tf.logging.set_verbosity(tf.logging.ERROR) 
print("Using TensorFlow version %s" % (tf.__version__))


# In[6]:


get_ipython().system('pip install dask[complete] distributed --upgrade')


# In[ ]:


get_ipython().system('dask-scheduler')


# In[7]:


import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import dask as dask
from dask import compute, persist
from distributed import Client
import dask.dataframe as dd

client = Client()
client
`
The output after `# In[6]:
get_ipython().system('pip install dask[complete] distributed --upgrade')`
is : 
`Collecting dask[complete]
  Downloading https://files.pythonhosted.org/packages/1d/f1/700c604af030d9b256a6590adf56cadd174c30c8ac6f555daf0e3023d294/dask-0.17.2-py2.py3-none-any.whl (582kB)
    100% |████████████████████████████████| 583kB 966kB/s eta 0:00:01
Collecting distributed
  Downloading https://files.pythonhosted.org/packages/39/e8/7453e61bbee910aa91936743d6782a2108c28d9945f5f61cf801b485b5fa/distributed-1.21.6-py2.py3-none-any.whl (458kB)
    100% |████████████████████████████████| 460kB 1.3MB/s eta 0:00:01
Collecting numpy>=1.10.4; extra == "complete" (from dask[complete])
  Downloading https://files.pythonhosted.org/packages/76/4d/418dda252cf92bad00ab82d6b2a856e7843b47a5c2f084aed34b14b67d64/numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 45kB/s  eta 0:00:01
Collecting toolz>=0.7.3; extra == "complete" (from dask[complete])
Requirement already up-to-date: pandas>=0.19.0; extra == "complete" in /usr/local/envs/py2env/lib/python2.7/site-packages (from dask[complete])
Collecting cloudpickle>=0.2.1; extra == "complete" (from dask[complete])
  Downloading https://files.pythonhosted.org/packages/aa/18/514b557c4d8d4ada1f0454ad06c845454ad438fd5c5e0039ba51d6b032fe/cloudpickle-0.5.2-py2.py3-none-any.whl
Collecting partd>=0.3.8; extra == "complete" (from dask[complete])
  Downloading https://files.pythonhosted.org/packages/4a/ca/207a28fd81111f6a88e79a006745ff432b9cae850fbafa27486e98d459da/partd-0.3.8-py2.py3-none-any.whl
Collecting tblib (from distributed)
  Downloading https://files.pythonhosted.org/packages/4a/82/1b9fba6e93629a8557f9784cd8f1ae063c8762c26446367a6764edd328ce/tblib-1.3.2-py2.py3-none-any.whl
Collecting six (from distributed)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: click>=6.6 in /usr/local/envs/py2env/lib/python2.7/site-packages (from distributed)
Collecting tornado>=4.5.1 (from distributed)
Collecting sortedcontainers (from distributed)
  Downloading https://files.pythonhosted.org/packages/ea/67/c76c354ff30a689aeb2c75c4d383ae618c27fc2180d313f387f8918a3429/sortedcontainers-1.5.9-py2.py3-none-any.whl
Requirement already up-to-date: singledispatch; python_version < "3.4" in /usr/local/envs/py2env/lib/python2.7/site-packages (from distributed)
Collecting psutil (from distributed)
Collecting zict>=0.1.3 (from distributed)
  Downloading https://files.pythonhosted.org/packages/5d/c9/eddd6c9a7ebd65fc799f9b87e56b45599a4e35d66e3da2722d7fc2a89f1f/zict-0.1.3-py2.py3-none-any.whl
Collecting msgpack-python (from distributed)
Collecting futures; python_version < "3.0" (from distributed)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting python-dateutil (from pandas>=0.19.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |████████████████████████████████| 215kB 2.8MB/s eta 0:00:01
Collecting pytz>=2011k (from pandas>=0.19.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 1.2MB/s eta 0:00:01
Collecting locket (from partd>=0.3.8; extra == "complete"->dask[complete])
Requirement already up-to-date: backports-abc>=0.4 in /usr/local/envs/py2env/lib/python2.7/site-packages (from tornado>=4.5.1->distributed)
Collecting heapdict (from zict>=0.1.3->distributed)
Installing collected packages: numpy, tblib, six, futures, tornado, cloudpickle, sortedcontainers, psutil, heapdict, zict, msgpack-python, toolz, distributed, locket, partd, dask, python-dateutil, pytz
  Found existing installation: numpy 1.14.0
    Uninstalling numpy-1.14.0:
      Successfully uninstalled numpy-1.14.0
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: futures 3.0.5
    Uninstalling futures-3.0.5:
      Successfully uninstalled futures-3.0.5
  Found existing installation: tornado 4.4.2
    Uninstalling tornado-4.4.2:
      Successfully uninstalled tornado-4.4.2
  Found existing installation: psutil 4.3.0
    Uninstalling psutil-4.3.0:
      Successfully uninstalled psutil-4.3.0
  Found existing installation: toolz 0.8.2
    Uninstalling toolz-0.8.2:
      Successfully uninstalled toolz-0.8.2
  Found existing installation: dask 0.17.1
    Uninstalling dask-0.17.1:
      Successfully uninstalled dask-0.17.1
  Found existing installation: python-dateutil 2.5.0
    Uninstalling python-dateutil-2.5.0:
      Successfully uninstalled python-dateutil-2.5.0
  Found existing installation: pytz 2016.7
    Uninstalling pytz-2016.7:
      Successfully uninstalled pytz-2016.7
Successfully installed cloudpickle-0.5.2 dask-0.17.2 distributed-1.21.6 futures-3.2.0 heapdict-1.0.0 locket-0.2.0 msgpack-python-0.5.6 numpy-1.14.2 partd-0.3.8 psutil-5.4.5 python-dateutil-2.7.2 pytz-2018.4 six-1.11.0 sortedcontainers-1.5.9 tblib-1.3.2 toolz-0.9.0 tornado-5.0.2 zict-0.1.3
You are using pip version 9.0.1, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

The output after `# In[ ]:
get_ipython().system('dask-scheduler')` is :

`distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-Sd8lAU
distributed.scheduler - INFO - -----------------------------------------------
`

Finaly, the output after `# In[7]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import dask as dask
from dask import compute, persist
from distributed import Client
import dask.dataframe as dd

client = Client()
client` is
`ImportErrorTraceback (most recent call last)
<ipython-input-7-a8cd9af45e9a> in <module>()
      5 import dask as dask
      6 from dask import compute, persist
----> 7 from distributed import Client
      8 import dask.dataframe as dd
      9 

/usr/local/envs/py2env/lib/python2.7/site-packages/distributed/__init__.py in <module>()
      2 
      3 from .config import config
----> 4 from .core import connect, rpc
      5 from .deploy import LocalCluster, Adaptive
      6 from .diagnostics import progress

/usr/local/envs/py2env/lib/python2.7/site-packages/distributed/core.py in <module>()
     14 from toolz import assoc
     15 
---> 16 from tornado import gen
     17 from tornado.ioloop import IOLoop
     18 from tornado.locks import Event

/usr/local/envs/py2env/lib/python2.7/site-packages/tornado/gen.py in <module>()
     98 import types
     99 
--> 100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
    101                                 future_add_done_callback, future_set_result_unless_cancelled)
    102 from tornado.ioloop import IOLoop

ImportError: cannot import name future_set_exc_info
`

**Comment by mrocklin** [comment]
It looks like you're having trouble importing tornado?

You might want to try just the following:

    from tornado import gen

If so then I suspect that this is some packaging issue, possibly due to how you installed with `os.system('pip install ...')`.  My hope would be that Google Datalab has better solutions somewhere to help you manage your environment and software libraries.  It might be worth verifying with them that the way you're installing packages is best.

**Comment by NatLun091238** [comment]
Thank you so much. Indeed, that's the case. `from tornado import gen` results in 
`ImportErrorTraceback (most recent call last)
<ipython-input-10-7aafe5d43cd7> in <module>()
----> 1 from tornado import gen

/usr/local/envs/py2env/lib/python2.7/site-packages/tornado/gen.py in <module>()
     98 import types
     99 
--> 100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
    101                                 future_add_done_callback, future_set_result_unless_cancelled)
    102 from tornado.ioloop import IOLoop

ImportError: cannot import name future_set_exc_info`

Another thing, Datalab has tornado-4.4.2 installed, but DASK requires  tornado-5.0.2. Could this mismatch lead to the error shown above??

**Comment by mrocklin** [comment]
Dask.distributed requires tornado 4.5 or greater.  But no, the error that
you're seeing is likely something different.  I recommend looking through
datalab docs on how to install or upgrade libraries in your user
environment.  They *should* have a nice solution to this somewhere, but
unfortunately I'm not very familiar with their service.

**Comment by NatLun091238** [comment]
It seems like we found rather stable solution which doesn't interfere with existing datalab dask installation. We run an external script doing:
`!pip install tornado==4.5.1 distributed==1.21 dask-ml[complete]`
and restarting current server on GCP and then verifying installation. After that all packages need for development are available. It's not a best way of solving the problem, but it works for us.
