### ISSUE TITLE
Non-deterministic "Couldn't gather keys" warning

### ISSUE THREAD

**Issue by knkski** [dask/distributed#1933]
Related to #1932, in that both of these issues will occur in the same script.

I've got a script that looks something like this:

```python
import itertools

from distributed import Client

def multiply(n):
    if n == 5764:
        raise ValueError('5764 is a bad number!')

    return n * 2

def chunks(iterable, chunk_size):
    iterable = iter(iterable)
    chunk = list(itertools.islice(iterable, chunk_size))
    while chunk:
        yield chunk
        chunk = list(itertools.islice(iterable, chunk_size))

def run():
    client = Client()

    print('Starting.')

    for i, chunk in enumerate(chunks(range(10_000), 5000)):
        print(f'Processing chunk #{i}.')
        futures = [client.submit(multiply, nums) for nums in chunk]

        client.gather(futures, errors='skip')

    print('Done.')

if __name__ == '__main__':
    run()
```

Where `range(10_000)` is actually an iterator reading chunks of lines from a file, and multiply is transforming those chunks into something that is then stored in a database. The `if n == 5764: raise ValueError('5764 is a bad number!')` bit is just so that exactly one error is thrown, to demonstrate that the resulting non-deterministic error message is odd.

Running the above script sometimes results in output like this:

```
Starting.
Processing chunk #0.
Processing chunk #1.
distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (5764)
kwargs:    {}
Exception: ValueError('5764 is a bad number!',)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:62788: 5764 is a bad number!
distributed.client - WARNING - Couldn't gather keys {'multiply-5fa51d35f2029544cde8a9495f63be5e': [], 'multiply-e34b9cd8354b6b107491affa58dd2662': [], 'multiply-bae01f52f83e12cbaa50d9d9a89e1a7f': [], ... snip hundreds of keys ...}
Done.
```

And sometimes results in output like this:

```
Starting.
Processing chunk #0.
Processing chunk #1.
distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (5764)
kwargs:    {}
Exception: ValueError('5764 is a bad number!',)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:62730: 5764 is a bad number!
Done.
```

The warning doesn't seem to happen for smaller batch sizes (or it's at least much harder to trigger). I see that there's a call to `self._send_to_scheduler` for the failed keys, so I'm wondering if the listed keys are actually failing, or if they're just getting rescheduled and running normally. If the keys are getting rescheduled and run properly, would it make sense to change the warning message to be something like `Couldn't gather keys, rescheduling: <list of keys>`?

**Comment by mrocklin** [comment]
If the keys are getting rescheduled and run properly, would it make sense to change the warning message to be something like `Couldn't gather keys, rescheduling: <list of keys>`?

Yes, that would make sense.  Any interest in submitting a small PR with this change?

**Comment by knkski** [comment]
@mrocklin: Sure, submitted #1942 👍

**Comment by Mehroz01** [comment]
@mrocklin  
i am using tpot on iris dataset .I have clone distributed from https://github.com/dask/distributed 
but i am getting this error .kindly gives some suggestion or which package i should upgrade 

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function score at 0x7f8faae448c8>, (Pipeline(memory=None,
     steps=[('kneighborsclassifier', KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=100, p=2,
           weights='distance'))]), 0.0006704740226268768), (<function cv_extract at 0x7f8faae442f0>, <dask_ml.model_selection.methods.CVCache object at 0x7f8f9c631278>, array([[6.5, 2.8, 4.6, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.2, 5. , 1.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.9, 3.1, 5.4, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [7.7, 2.8,
kwargs:    {}
Exception: ValueError('Expected n_neighbors <= n_samples,  but n_samples = 88, n_neighbors = 100',)
