### ISSUE TITLE
Best way to slice array inside future object

### ISSUE THREAD

**Issue by CJ-Wright** [dask/distributed#1938]
I'm starting to use streamz with the dask distributed extension. I've ran into the issue that some of my code needs to slice the arrays or otherwise access the arrays which have been scattered onto the cluster. However, whenever I try to do this (either by `array[slice]` or `array == 0`) it seems that the slices/attributes of the future object are computed. What is the best way to tell the system that I want the data from the actual array itself without forcing the result to block everything?

**Comment by CJ-Wright** [comment]
I think that may work. I'll just need to change everything that internally uses `[a: b]` syntax over to `getitem`. 

This issue was cropping up inside other functions I had written, eg `future = client.submit(my_function, future)` where `my_function` included some slicing of the array. This would fail because it would attempt to perform the slice (or get an object attribute (like the shape of the array)) on the future object rather than the array the future represented.

**Comment by mrocklin** [comment]
If you're submitting the function my_function on a future then that
function should receive the concrete numpy array referred to by the future.

**Comment by CJ-Wright** [comment]
Thank you very much for the help!

I was able to find the problem, it is/was on the streamz side so I'll try to put in a PR there.
