### ISSUE TITLE
getting NoneType errors using dask delayed with rpy2

### ISSUE THREAD

**Issue by DavisTownsend** [dask/distributed#1939]
I am getting 
distributed.scheduler - ERROR - error from worker 'NoneType' object does not support item assignment
errors when using dask delayed with rpy2 and more than 1 core.
When I use the same code with only 1 core it runs correctly. 

I've created a mcve of the issue here:  https://stackoverflow.com/questions/50050598/how-to-use-dask-delayed-with-rpy2

**Comment by DavisTownsend** [comment]
I'm not exactly sure how to recreate the issue without using the library. It only relies on the forecast package in R which is a very popular library, and I assume the interaction is where this issue is arising.  I've used this same workflow successfully for https://facebook.github.io/prophet/docs/quick_start.html which is implemented using Pystan so I would think pushing out computation to other engines generally works, the idea is it only needs to process each time series independently.

**Comment by TomAugspurger** [comment]
If you delay a function that returns a simple R vector, does the issue
persist?

**Comment by TomAugspurger** [comment]
Just trying to narrow down where the issue is at.

**Comment by DavisTownsend** [comment]
So with new function:
`def r_vecs(time_series):
    
    rdata=ts(time_series,frequency=12)
    
    return rdata`
I ran without dask delayed and it worked
Using dask delayed I get error:
NotImplementedError: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'

**Comment by DavisTownsend** [comment]
So I created new function:

```
def r_vecs(time_series):
    
    rdata=ts(time_series,frequency=12)
    
    return rdata
```
works:

```
output_fc_R = []
for i in df:
    forecasted_series = r_vecs(df[i])
    output_fc_R.append(forecasted_series)
    
output_fc_R
```

does not work:

```
output_fc_R = []
for i in df:
    forecasted_series = dask.delayed(r_vecs)(df[i])
    output_fc_R.append(forecasted_series)
    
total = dask.delayed(output_fc_R).compute()
```

**Comment by TomAugspurger** [comment]
In case the stackoverflow post is deleted, could you include the code to generate a small `df`. I don't think it needs to be as large as the one on stackoverflow (or does it?)

What library provides `ts`?

**Comment by DavisTownsend** [comment]
yeah I'll edit it also to reflect this exact error. It was just big to see if it was actually operating correctly in parallel if you get the error to go away. 

ts(): https://www.rdocumentation.org/packages/stats/versions/3.4.3/topics/ts
is part of the core R library

**Comment by mrocklin** [comment]
I recommend including the full traceback from the worker if possible.

**Comment by DavisTownsend** [comment]
Okay I've figured out a workaround so we can close this issue now if you want. 

I'm not sure why this is the case, but if I call the forecast fit and predict methods in an R function (so computation is all done within R) instead of evaluating the string in python then it works with dask delayed, I just tested it using 6 cores, timed at 23 seconds vs 1 min 45 seconds with 1 core. And on cadvisor all 6 cores of my machine were running

This is the code for the R function for reference:

```
import pandas as pd
import numpy as np
import dask
from dask.distributed import Client, LocalCluster
import rpy2.robjects as robjects
from rpy2.robjects.packages import importr
ts=robjects.r('ts')
from rpy2.robjects import pandas2ri
#forecast package
forecast=importr('forecast')
#pandas2ri.activate()
cluster = LocalCluster()
client = Client(cluster)

rows = 24
ncolumns = 5
column_names = ['ts1','ts2','ts3','ts4','ts5']
df = pd.DataFrame(np.random.randint(0,10000,size=(rows, ncolumns)), columns=column_names)
df_date_index = pd.date_range(end='2018-04-01', periods=rows, freq='MS')
df.index = df_date_index

model='ets(rdata)'
conf_level=80.0
forecast_periods = 18
rstring="""
 function(rdata){
 library(forecast)
 fitted_model<-%s
 forecasted_data<-forecast(fitted_model,h=%s,level=c(%s))
 predicted_series<-forecasted_data$mean
 predicted_series
 }
""" % (model,forecast_periods,conf_level)

rfunc=robjects.r(rstring)

rdata=ts(df.ts1.values,frequency=12)
r_df=rfunc(rdata)

forecast_series=pandas2ri.ri2py(r_df)
pd.Series(forecast_series)
```

I basically wrapped that code into my new forecast_R function
I'll post the full code to the SO post, and I'm working on a full fledged dask forecasting tutorial for something similar that will go into detail on all of this
