### ISSUE TITLE
Scaling cluster prints 'Hello'

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#1956]
The LocalCluster object displays a widget in the notebook. Clicking "scale" on the manual scaling panel causes "Hello!" to be printed into the output part of the same cell.

**Comment by mrocklin** [comment]
https://github.com/dask/distributed/pull/1957

**Comment by jakirkham** [comment]
Appears to be solved. Good to close?

**Comment by mrocklin** [comment]
Thanks for the reminder
