### ISSUE TITLE
Migrate dask-ssh to separate subpackage

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1960]
The deploy/ssh module has been around for a long while.  Today most functionality like this gets moved out to external packages.  It might be best to do the same with a new dask-ssh package.

**Comment by jakirkham** [comment]
Possibly `dask-mpi` too (maybe even more so).

**Comment by jcrist** [comment]
dask-mpi has been split off, and #2497 duplicates this issue (and is more active). Closing.
