### ISSUE TITLE
Handling exceptions in queues

### ISSUE THREAD

**Issue by knkski** [dask/distributed#1968]
I have code that looks something like this:

```python
import itertools
from queue import Queue
from distributed import Client


def extract(i):
    if i == 23:
        raise ValueError('i cannot be 23')
    return i


def transform(i):
    if i == 45:
        raise ValueError('i cannot be 45')
    return i


def load(i):
    if i == 67:
        raise ValueError('i cannot be 67')
    return i


def chunks(iterable, chunk_size):
    iterable = iter(iterable)
    chunk = list(itertools.islice(iterable, chunk_size))
    while chunk:
        yield chunk
        chunk = list(itertools.islice(iterable, chunk_size))


def main():
    client = Client()
    input_queue = Queue()
    remote_queue = client.scatter(input_queue)
    extract_queue = client.map(extract, remote_queue)
    transform_queue = client.map(transform, extract_queue)
    load_queue = client.map(load, transform_queue)
    result_queue = client.gather(load_queue)

    for i, chunk in enumerate(chunks(range(100), 10)):
        count = len(chunk)

        for item in chunk:
            input_queue.put(item)

        for _ in range(count):
            result_queue.get()


if __name__ == '__main__':
    main()
```

Where `range(100)` is in reality an iterable of records that I'd like to load into the database, and `if i == 67: ...` bits represent validation logic that raises errors to signal an invalid record.

The problem I've got is that the script will hang unless I convert the `ValueErrors` to something like printing out the error and using `None` as a sentinel value and have a `if i is None: return None` in all downstream functions. This is due to `result_queue.get()` blocking and waiting for the values that errored out, which makes sense. I'm wondering if there's a way to do something akin to this that I'm not seeing:

```python
for i, chunk in enumerate(chunks(range(100), 10)):
    results, errors = input_queue.put_blocking(chunk)
```

If not, is that something that would be possible for `distributed` to do? At the bottom of http://distributed.readthedocs.io/en/latest/queues.html, I see `This isn’t a proper streaming system. There is no support outside of what you see here. In particular there are no policies for dropping data, joining over time windows, etc..`, and I'm wondering if this is what is meant by dropping data, and if there's plans to support this use case or not, or if there's alternatives that would work instead.

**Comment by mrocklin** [comment]
The only robust real-time API for dask currently is the concurrent futures API, which is a bit lower level.

A higher level API that likely does what you want is available at http://streamz.readthedocs.io/en/latest/ , but it is beta-quality.

If you have a free 40m you might find this talk explaining everything to be of interest: https://youtu.be/7i4Gcb_-fNU

**Comment by knkski** [comment]
Good to know. I'll close this ticket in favor of watching the `streamz` one. Thanks!
