### ISSUE TITLE
Client.close raises StreamClosedError

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1969]
Appears the running `Client.close` consistently runs into some sort of hang up (shown below). This happens in Distributed 1.21.8, but not in Distributed 1.21.6. Context for this provided in the linked Gist, which contains the Jupyter Notebook it showed up in and the environment. 

```python
Exception ignored in: <generator object add_client at 0x11e4d1f10>
RuntimeError: generator ignored GeneratorExit
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/distributed/comm/tcp.py", line 179, in read
    n_frames = yield stream.read_bytes(8)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/distributed/comm/tcp.py", line 200, in read
    convert_stream_closed_error(self, e)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

ref: https://gist.github.com/jakirkham/b9c75e2f7fabdee5f19db8cc3bff0d9e
ref: https://github.com/dask/distributed/issues/1963

**Comment by macks22** [comment]
I'm getting the same.

Versions:
```
dask-0.17.4
distributed-1.21.8
tornado-5.0.2
```

Minimum example:
```
import time
from dask.distributed import Client, as_completed


def square(i):
    return i ** 2

with Client(n_workers=2) as client:
    futures = [client.submit(square, i) for i in range(10)]
    for f, result in as_completed(futures, with_results=True):
        print(result)
        time.sleep(0.1)  # just to make it more obvious what's happening

    time.sleep(1)
```

```
Exception ignored in: <generator object add_client at 0x120368258>
RuntimeError: generator ignored GeneratorExit
[ERROR][2018-05-08 15:33:24,001]: Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/Users/vru959/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 179, in read
    n_frames = yield stream.read_bytes(8)
  File "/Users/vru959/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vru959/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/vru959/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 200, in read
    convert_stream_closed_error(self, e)
  File "/Users/vru959/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

**Comment by jakirkham** [comment]
So there are other cases where `StreamClosedError` does get raised. They do need to be fixed. This issue is just showing that now simply calling `close` will trigger a `StreamClosedError`. I think you have found a different case where this occurs, @macks22. So it would be reasonable to move your use case to it's own issue. Does that sound reasonable?

**Comment by jakirkham** [comment]
Ok, thanks for clarifying. :)

**Comment by jakirkham** [comment]
Thanks for the reminder.

Have not had time to look into the cause (or fix it) personally. Though can confirm this issue is still present with Distributed 1.22.1 (latest).

**Comment by cicdw** [comment]
I dug into this a little bit and it looks like this might be caused by [this line](https://github.com/dask/distributed/blob/master/distributed/utils.py#L409) which is triggered by [stopping the LoopRunner attached to the LocalCluster](https://github.com/dask/distributed/blob/master/distributed/deploy/local.py#L294).

**Comment by mrocklin** [comment]
Yeah, so what happens here is that the IOLoop stops, this severs a bunch of connections, and they raise errors.  In many cases these are caught appropriately, but in some they aren't. 

Pragmatically this may be resolved for this particular issue here: https://github.com/dask/distributed/pull/2237

The connection that was complaining was the Client's connection to the scheduler.  We now wait a little bit of time to see if the scheduler's "all finished now" message arrives in time, which results in a quieter experience, at least in the example provided here.

**Comment by zoj613** [comment]
Im facing this problem with `distributed==2022.9.1` and dask. Any workaround I can emply to silence these errors after calling `client.gather` successfully?
