### ISSUE TITLE
Documenting CLIs

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#1975]
This is partially inspired by PR ( https://github.com/dask/dask/pull/3476 ).

Would be nice if we included the CLI options in our docs. One nice option to do this easily without going out-of-date is using [sphinxcontrib-autoprogram]( https://pythonhosted.org/sphinxcontrib-autoprogram/ ). There may be other good options. Would also be good to determine how we would want to lay this out.

**Comment by mrocklin** [comment]
I agree that this would be useful.

Also, FWIW I've slowed down my maintenance of this project's docs,
preferring instead to work in dask.pydata.org when possible.  I wonder if
the CLI docs could go in http://dask.pydata.org/en/latest/setup/cli.html as
well

**Comment by jakirkham** [comment]
As long as Distributed is available when the docs are built with RTD, sure. There is a question of what happens if the CLIs change here in a non-released version. Less clear what happens if a user builds locally without Distributed being available.

We could also just link out from those docs to whatever page we create here. It might be far enough into the weeds that this is ok. Plus wouldn't expect this would get much maintenance.
