### ISSUE TITLE
KeyError following nanny-killed worker 

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1984]
Using the latest code for dask & distributed (although this symptom goes back awhile).

When I lose a worker in a complex and data-heavy dynamic task submission workflow b/c of memory limits (so nanny kills worker), an error often bubbles up to the gathering (worker) client that looks like this:

```
 Traceback (most recent call last):
   File "distributed/distributed/client.py", line 1409, in _gather
     st = self.futures[key]
 KeyError: '<task name>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...", line 135, in gather
    return _client.gather(futures)
  File " distributed/client.py", line 1542, in gather
    asynchronous=asynchronous)
  File " distributed/client.py", line 642, in sync
    return sync(self.loop, func, *args, **kwargs)
  File " distributed/utils.py", line 253, in sync
    six.reraise(*error[0])
  File " envs/a2/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File " distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File " envs/a2/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File " envs/a2/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File " envs/a2/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File " distributed/client.py", line 1415, in _gather
    None)
  File " envs/a2/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
concurrent.futures._base.CancelledError: <task name>
```

(EDIT: "During handling of the above exception, another exception occurred:" is because I catch and raise)

Is this expected? The error makes it hard to understand what is going on (ie, I don't think the task failed, per se, but rather its worker died, and for some reason the system seems unable to recover). Or does it smell like a race condition?

**Comment by mrocklin** [comment]
Just checking to make sure I understand, is this happening on a client within a worker as it shuts down?  Or is it happening on another client that happens to be gathering that key.

It looks like the future was cancelled or released during a gather, which is odd in normal execution, but I suppose feasible if another client were to actively cancel it.

**Comment by mrocklin** [comment]
Actually, the future would have to be lost in a race between calling `wait` and it running on the IOLoop.  It's not clear to me how to construct a situation that would do this frequently.  I'm curious how regularly this is occurring for you @adamklein

**Comment by adamklein** [comment]
So it sounds like a race & not expected. I can make this happen every time.  I might spend a bit more time trying to create a reproducible example since I know how valuable that is. 

> Or is it happening on another client that happens to be gathering that key.

Yes.

> I suppose feasible if another client were to actively cancel it.

I think the worker that has computed the task result dies (killed by nanny) in the middle of streaming the results back to the gathering worker client. I'm working on at least upping the logging level to see if I can get a seconds of the timing of events.

**Comment by adamklein** [comment]
I've been unable to recreate in a simple example, where I always see a KilledWorkerr exception like I expect. For whatever reason my actual situation always produces a CancelledError wrapping a KeyError.

However, I changed my logic to do this:

    results = gather(futures, errors='skip')
    if len(results) < len(futures):
        for f in futures:
            if f.status == 'error':
                 exc, tb = f.exception(), f.traceback()
                 desc = ''.join(traceback.format_exception(type(exc), exc, tb))
                 print('Error in {}: {}'.format(f.key, desc)

And lo and behold, I get the much desired result:

    ERROR in <task name>: distributed.scheduler.KilledWorker: ('<task name>', 'tcp://<ip address>:38459')

which I can live with. but it leaves open the question of why manually traversing the futures yields a better error than the gather with errors='raise' ... sorry I can't reproduce easily :/

**Comment by adamklein** [comment]
Closing, as I'm no longer convinced there's an actual issue here.
