### ISSUE TITLE
Dask Distribute Example Error

### ISSUE THREAD

**Issue by FranklinRay** [dask/distributed#1994]
I set up Dask Distributed. 
My cluster has three server, 10.27.88.97 scheduler \10.27.10.92 woker \ 10.27.88.67 woker.
When i run code like:
`from dask.distributed import Client`
`client = Client('10.27.88.97:8786')`
`def square(x):`
`    return x ** 2`
`A = client.map(square, range(10))`
`total = client.submit(sum, A)`
`print total.result()`

It has an type error like 
> TypeError: ('Long error message', '(\'range() integer end argument expected, got list.\', <function _make_skel_func at 0x7fa6935ca500>, (<code object square at 0x7fa679f381b0, file "<ipython-input-67-506eeda4a75b>", line 1>, [], {\'__builtins__\': {\'bytearray\': <type \'bytearray\'>, \'IndexError\': <type \'exceptions.IndexError\'>, \'all\': <built-in function all>, \'help\': Type help() for interactive help, or help(object) for help about object., \'vars\': <built-in function vars>, \'SyntaxError\': <type \'exceptions.SyntaxError\'>, \'unicode\': <type \'unicode\'>, \'UnicodeDecodeError\': <type \'exceptions.UnicodeDecodeError\'>, \'memoryview\': <type \'memoryview\'>, \'isinstance\': <built-in function isinstance>, \'copyright\': Copyright (c) 2001-2016 Python Software Foundation.\nAll Rights Reserved.\n\nCopyright (c) 2000 BeOpen.com.\nAll Rights Reserved.\n\nCopyright (c) 1995-2001 Corporation for National Research Initiatives.\nAll Rights Reserved.\n\nCopyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.\nAll Rights Reserved., \'NameError\': <type \'e')

But when i run the code in the scheduler, it works well.
I use anacoda2 to configure my environment。 I use python 2.7, dask 0.15.2, distributed 1.18.1.
Wish someone can help me, thanks.

**Comment by mrocklin** [comment]
I suspect that you have different versions on your different computers.

I recommend trying the following operation

```python
client.get_versions(check=True)
```

**Comment by FranklinRay** [comment]
Thanks a lot. The problem coursed by different versions
