### ISSUE TITLE
Testing for non standard pythons

### ISSUE THREAD

**Issue by mariusvniekerk** [dask/distributed#1998]
It would be handy to test dask on some non standard python implementations.  Notable ones are probably pypy and pypy3 (maybe jytyhon?).  These should not block pull requests but it would be handy to have something to look at prior to cutting a release.

Suggestions?

**Comment by GenevieveBuckley** [comment]
This has been open for a while now without much discussion. Given the lack of interest from the broader community, I'm going to close this issue. Thanks @mariusvniekerk!
