### ISSUE TITLE
Rename Distributed

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#20]
`Distributed` is arguably an overly broad term.  It would be nice to give this project a more specific name.

### Reasons to rename

Within just-python this term makes sense, and fits nicely into the `threading` and `multiprocessing` library names.  However, if we consider other things one can do in a distributed way (like data storage) or distributed libraries within other languages (like Hadoop), calling a project "distributed" seems like we're claiming too much conceptual space.

I would like to move this repository over to the `blaze` org soon.  Ideally this happens at the same time as the renaming to reduce confusion.

### Some seeds

*  distributed is lightweight
*  distributed is good at complex data analysis, not databases or trivial munging
*  distributed has low-latency 
*  distributed responds robustly to stimuli 
*  distributed is good for ad-hoc computations that don't fit into typical map/reduce models
*  distributed is a Python library (is there an attractive term for a swarm of fast twitchy snakes?)

### Restrictions for any name

Should be easy to type.  Must be available on PyPI.  Must not conflict with another name for another project in another language.  Must not conflict with a copyrighted/trademarked term.

**Comment by jcrist** [comment]
I like "Rhumba". A group of rattlesnakes is called a rhumba. It's also a dance that requires a good connection between partners to be done well.

**Comment by mdboom** [comment]
It's *almost* a name clash with some sort of mainframe dashboard software from IBM: http://www-304.ibm.com/partnerworld/gsd/solutiondetails.do?solution=49749&expand=true

I highly recommend watching the video there if you're nostalgic for CRTs and Post-It notes.

**Comment by mdboom** [comment]
Also taken on PyPI: https://pypi.python.org/pypi/rhumba/0.1.0  :frowning:

**Comment by jreback** [comment]
``krait`` or ``kraits`` -> https://en.wikipedia.org/wiki/Bungarus

**Comment by jreback** [comment]
``venom``

**Comment by jreback** [comment]
``braid``

**Comment by mrocklin** [comment]
Oh man, I like those ideas.

**Comment by jreback** [comment]
though as others have mentioned ``distributed`` is quite nice :)

**Comment by mrocklin** [comment]
Thoughts on the name `twitch`?  I've been thinking about names centered around the idea of rapid response.  This is because distributed is largely an event driven system that responds to external stimuli and also because it is low latency.

Twitch is taken on PyPI, but it's largely unused.  I suspect we could claim it if we ask the right people.  Alternatively, other names around responding rapidly to signals/stimuli might be an interesting source of names.

**Comment by mrocklin** [comment]
More names

Helm, bridge (I like helm but it's sort of taken on pypi, translations here are good though (ror in Danish))
Any small fast bird
Cortex
MC
Quarterback
Admiral/captain/

**Comment by hussainsultan** [comment]
[Takt] (https://en.wikipedia.org/wiki/Takht_(music))

**Comment by mrocklin** [comment]
Concise, easy to type, free on PyPI, clever/obscure meaning, and a bit fun.  I like it.

**Comment by hainm** [comment]
I am +1 for `twitch`

And how's about 

- ripple
- epoch
- aurora
- lagoon
- lilt

**Comment by mrocklin** [comment]
@hainm can you give your motivation behind words like lagoon?

**Comment by hainm** [comment]
@mrocklin honesty there is no motivation behind. (I guess just like python or hadoop :D).

**Comment by mrocklin** [comment]
We seem to have settled on just calling this project `dask.distributed` which feels like a decent compromise.  Closing.
