### ISSUE TITLE
Proxying dask ui for workers?

### ISSUE THREAD

**Issue by mariusvniekerk** [dask/distributed#2002]
Would it be possible to have the dask ui act as a proxy forwarding the ui pages of the various workers?

It would make monitoring a larger dask deploy easier if only the scheduler ui needs firewall punching.

**Comment by mrocklin** [comment]
I agree that this would be useful.  I personally don't know much about this
space to be able to comment intelligently on it.

**Comment by mrocklin** [comment]
Closing in favor of https://github.com/dask/distributed/issues/2160
