### ISSUE TITLE
Making `Cluster`'s `scale_up`/`scale_down` methods coroutines

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#2004]
In Distributed's `Adaptive` class, there are calls to Cluster implementations of [`scale_up`]( https://github.com/dask/distributed/blob/1.21.8/distributed/deploy/adaptive.py#L285 ) and [`scale_down`]( https://github.com/dask/distributed/blob/1.21.8/distributed/deploy/adaptive.py#L235 ) from within coroutines. While it would be possible to call these as coroutines in some cases (as is [the case in `dask-drmaa`]( https://github.com/dask/dask-drmaa/blob/0.2.1/dask_drmaa/core.py#L305-L313 )), this appears to not be part of [`Adaptive`'s spec for its cluster instance]( https://github.com/dask/distributed/blob/1.21.8/distributed/deploy/adaptive.py#L65-L68 ) nor is part of the [`Cluster`'s spec]( https://github.com/dask/distributed/blob/1.21.8/distributed/deploy/cluster.py#L22-L28 ). A cursory glance at `dask-jobqueue` suggests [it doesn't use coroutines either]( https://github.com/dask/dask-jobqueue/blob/0.1.1/dask_jobqueue/core.py#L224-L231 ). Considering it would be possible to make `scale_up` and `scale_down` coroutines and these would fit nicely within the `Adaptive` model, could we consider migrating in that direction?

**Comment by mrocklin** [comment]
Currently they can be coroutines or not coroutines, which I like

https://github.com/dask/distributed/blob/34f7cd5c20cba24a3b585f445c14ca8f72e4a2ed/distributed/deploy/adaptive.py#L235-L237

**Comment by mrocklin** [comment]
Closing this for now.  Feel free to reopen if the question persists.
