### ISSUE TITLE
output of the workers of dask.distributed seems corrupted

### ISSUE THREAD

**Issue by pierreglaser** [dask/distributed#2015]
Hello, 
So I tried a toy example using dask.distributed, and when submitting 2 identical function calls, 
one of them has its output never printed:
```
import time
from dask.distributed import Client,LocalCluster,as_completed


def f(x):
    print('sleeping for {} seconds'.format(x))
    time.sleep(x)
    return x


if __name__=='__main__':
    n_jobs=2
    client = Client(n_workers=2,processes=True,threads_per_worker=1)

    # Send out several computations
    futures = [client.submit(f, x) for x in [1,2,2,3]]
    scores=[]
    for future in as_completed(futures):
        scores.append(future.result())
    print(scores)

```

which outputs 
```
sleeping for 3 seconds
sleeping for 2 seconds
sleeping for 1 seconds
[2, 2, 3, 1]
```

So it seems that altough all function calls are indeed executed, one of the two "sleeping for 2 seconds" 
disappears for some reasons. 

I installed dask and dask distributed using pip on a isolated virtualenv, using python 3.5.4
```
click==6.7
cloudpickle==0.5.3
dask==0.17.5
distributed==1.21.8
HeapDict==1.0.0
msgpack==0.5.6
psutil==5.4.5
six==1.11.0
sortedcontainers==2.0.2
tblib==1.3.2
toolz==0.9.0
tornado==5.0.2
xgboost==0.7
zict==0.1.3
```

Is this the expected behavior?

**Comment by mrocklin** [comment]
By default Dask deduplicates function calls with the same arguments.  If two people submit functions `f(2)` then dask will only run that function once.  You can opt-out of this behavior with the `pure=False` keyword.

    future = client.submit(f, 2, pure=False)

**Comment by pierreglaser** [comment]
Thank you very much, closing the issue then!
