### ISSUE TITLE
Unable to run worker_client command with client.run or even using client.submit in loop without setting pure=False

### ISSUE THREAD

**Issue by ameetshah1983** [dask/distributed#2022]
I am running some simple tests to try out worker_client usage and found that the following example simply hangs and dask status dashboard also does not show any running tasks:

```
def test_func():
    from distributed import worker_client, rejoin
    x = None
    y = None
    with worker_client() as client:
        x = client.id
   rejoin()    
    with worker_client() as client1:
        y = client1.status 
    rejoin()
    return x, y
```

**Example 1**
client.run(test_func)  # Gives error AttributeError: 'thread._local' object has no attribute 'executor' but works when using separate_thread=False is used instead of rejoin()
**Example 2**
for i in range(100):
    cl.submit(test_func).result()    # hangs and does not appear in dashboard unless pure=False is set

**Comment by mrocklin** [comment]
worker_client is meant to be used in tasks, not the run function.  Please consider [get_client](http://dask.pydata.org/en/latest/futures.html#distributed.get_client) instead.  You also don't need to rejoin if you haven't seceded.  If you're using worker_client then it will handle both for you.

If multiple function calls are made with the same inputs then they are assumed to have the same output, and so are only run once.  You're correct that pure=False is a way to avoid this behavior.

**Comment by mrocklin** [comment]
Are there any further questions here?  I'm going to close for now.  Please let me konw if there is something concrete to handle here.
