### ISSUE TITLE
scattering and submitting in a function results in status canceled if task raises exception

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2039]
We have a set up where we have an object that has a run function. The object can be large so we wrote a submit function which scatters the object and then submit a task that calls run on the scattered object. We noticed an odd behavior where if the task results in an exception it is treated as cancelled as opposed to error. If we run the same code inline (as opposed to in our submit function) we get status error as expected.

Repro:

```python
import distributed
import uuid

cluster = distributed.LocalCluster(n_workers=2)
dask_client = distributed.Client(cluster)

class BadItem():
    def run(self):
        raise Exception('lol')
        
def do_stuff():
    key = 'my_key-{}'.format(uuid.uuid4()) 
    fut1 = dask_client.scatter(BadItem())
    fut2 = dask_client.submit(lambda x: x.run(), fut1, key=key)
    return fut2

fut2 = do_stuff()
time.sleep(1)
print(fut2.status)
```
Returns 'cancelled'

However, inlining returns 'error' as expected:

```python
import distributed
import uuid

cluster = distributed.LocalCluster(n_workers=2)
dask_client = distributed.Client(cluster)

class BadItem():
    def run(self):
        raise Exception('lol')
  
key = 'my_key-{}'.format(uuid.uuid4()) 
fut1 = dask_client.scatter(BadItem())
fut2 = dask_client.submit(lambda x: x.run(), fut1, key=key)
time.sleep(1)
print(fut2.status)
```

**Comment by adamklein** [comment]
(The difference being that the returned future from the scatter doesn't get un-reference-counted / deleted in the inlined version)

**Comment by wyegelwel** [comment]
I found PR #1366. Is this considered a feature?

**Comment by mrocklin** [comment]
This behaves sensibly for me today

```python
In [1]: import distributed
   ...: import uuid
   ...: 
   ...: cluster = distributed.LocalCluster(n_workers=2)
   ...: dask_client = distributed.Client(cluster)
   ...: 
   ...: class BadItem():
   ...:     def run(self):
   ...:         raise Exception('lol')
   ...:         
   ...: def do_stuff():
   ...:     key = 'my_key-{}'.format(uuid.uuid4()) 
   ...:     fut1 = dask_client.scatter(BadItem())
   ...:     fut2 = dask_client.submit(lambda x: x.run(), fut1, key=key)
   ...:     return fut2
   ...: 
   ...: fut2 = do_stuff()
   ...: distributed.wait(fut2)
   ...: print(fut2.status)
   ...: 
distributed.worker - WARNING -  Compute Failed
Function:  <lambda>
args:      (<__main__.BadItem object at 0x7fa3a460a1d0>)
kwargs:    {}
Exception: Exception('lol',)

error
```

Perhaps it was fixed?

**Comment by wyegelwel** [comment]
Yes you're right. This was fixed when you fixed #2038. The intent for #2038 was to capture that:
 (1) when you scatter and then raise you get the unexpected cancelled state
 (2) as_completed doesn't return cancelled futures

It looks like you fixed (1) (thanks again!). From the PR #1366, is it correct to believe that (2) is a feature of dask?

Also, let me know if we should move this discussion somewhere else since this issue is fixed

**Comment by mrocklin** [comment]
Yes, I think that that sounds right.  For behavior I would recommend checking what concurrent.futures does.  I suspect that they also skip cancelled futures.

There is no better place to discuss this than here.

**Comment by wyegelwel** [comment]
I may be mis-reading it, but it looks like concurrent.futures includes cancelled in their implementation of as_completed from a quick read of the docs. https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed it says "Returns an iterator over the Future instances (possibly created by different Executor instances) given by fs that yields futures as they complete (finished or were cancelled)." 

To the deeper question, I find the dask behavior unexpected as my mental model is that cancelled is a "completed" state. Was the intent of #1366 to mirror concurrent.futures (I see the comment in the pr) or was there something else going on?

**Comment by mrocklin** [comment]
The intent was to match concurrent futures behavior

**Comment by mrocklin** [comment]
If it doesn't match then this should be considered a bug, and a pull
request fixing the behavior would be welcome

**Comment by wyegelwel** [comment]
Ok, I will open another issue for further discussion
