### ISSUE TITLE
as_completed using with_results option hangs getting next future if future errored

### ISSUE THREAD

**Issue by rwedge** [dask/distributed#2065]
I ran into an issue where failed tasks were causing my code to hang waiting for `as_completed` to return the next result.  Here's an example of the scenario: 
```
from dask.distributed import Client
from dask.distributed import as_completed


client = Client()

def error_out():
    raise RuntimeError()

future = client.submit(error_out)
iterator = as_completed([future], with_results=True)
iterator.next()
```

**Comment by mrocklin** [comment]
We could also add an `errors='raise'/'return'` keyword to `as_completed`.

**Comment by mrocklin** [comment]
@rwedge is this something that you would be interested in contributing?

**Comment by rwedge** [comment]
I can take a shot at it once it's decided how to handle the exception

**Comment by mrocklin** [comment]
I think that the `errors=` keyword is likely a sensible choice.  We can leave this for a day to see if others come by with suggestions or concerns.  Also, do you have thoughts on the matter?

**Comment by rwedge** [comment]
The `errors=` keyword seems reasonable.  This keyword determines how errors encountered while gathering results are handled, right?  I think the documentation should be clear about which errors the keyword is referring to.

**Comment by rwedge** [comment]
Instead of a try-except, would it be sufficient to use raiseit=False and then in raise the error in ``__next__`` or ``next_batch``?  
```
        if self.with_results:
                result = yield future._result(raiseit=False)
```
This could handle an error raised if there was an future with an 'error' status but an unexpected exception might still cause a hang.
