### ISSUE TITLE
The msgpack from pandas does not have dumps function

### ISSUE THREAD

**Issue by spacelis** [dask/distributed#207]
Hi,

I have a problem of using distributed (1.9.1) on Python 2.7.11 along with pandas 0.18.0 as the pandas implementation of msgpack does not have the API of dumps(). I am wondering whether it is better to use msgpack-python as the main implementation.

Thanks.

**Comment by mrocklin** [comment]
Can you run the following?

```python
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: u'0.18.0'

In [3]: pd.msgpack.dumps
Out[3]: <function pandas.msgpack.packb>

In [4]: pd.msgpack.loads
Out[4]: <function pandas.msgpack._unpacker.unpackb>

In [5]: import sys

In [6]: sys.version_info
Out[6]: sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)
```

**Comment by spacelis** [comment]
Hi,

Sorry, my env was massed up. Everything seems fine.

Thank you.

**Comment by mrocklin** [comment]
Thanks for raising the issue regardless.  More bug issues are definitely welcome.
