### ISSUE TITLE
Dashboard's index links incorrect with nbserverproxy

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#2081]
When using `nbserverproxy` to proxy the Dask Distributed Dashboard, the URLs in the application list on the index page don't seem to be correctly generated as relative links of the proxy URL. This is demonstrated in the screenshot below where the mouse over URL does not prefix the URL with `http://localhost:8889/proxy/8787`.

<details>
<summary>Screenshot Proxy Dropped:</summary>

<img width="1552" alt="screen shot 2018-06-28 at 14 24 39" src="https://user-images.githubusercontent.com/3019665/42053248-0e884422-7adf-11e8-8d6a-1fd4c3c241d9.png">

</details>

<br>

Contrast this to the menubar above any of the apps where the proxy URL is respected. This is the case for all of the apps in the menubar and persists even when changing the app viewed.

<details>
<summary>Screenshot Proxy Included:</summary>

<img width="1552" alt="screen shot 2018-06-28 at 14 28 01" src="https://user-images.githubusercontent.com/3019665/42053431-81203094-7adf-11e8-92f4-88c2ba5670d4.png">

</details>

<br>

It seems that in most cases users set the `--bokeh-prefix` CLI argument or using `service_kwargs` in Python. However neither of these approaches really work for `nbserverproxy` as the prefix is dependent on the port the Dashboard gets hosted on, which we don't know at the time we would be setting the prefix.

Unclear on the history behind this issue or where would be the best place to try to improve things (Distributed or Bokeh). So open to suggestions on how best to improve this.

Started the notebook with `jupyter notebook`. Other details for the MRE shown above.

<details>
<summary>Jupyter notebook:</summary>

Contained one cell with this content.

```python
import distributed
c = distributed.Client()
c
```

</details>

<br>

<details>
<summary>Environment:</summary>

```yaml
name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - bokeh=0.12.16=py36_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - click=6.7=py_1
  - cloudpickle=0.5.3=py_0
  - cytoolz=0.9.0.1=py36_0
  - dask=0.18.1=py_0
  - dask-core=0.18.1=py_0
  - decorator=4.3.0=py_0
  - distributed=1.22.0=py36_0
  - entrypoints=0.2.3=py36_1
  - heapdict=1.0.0=py36_0
  - html5lib=1.0.1=py_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - libgfortran=3.0.0=0
  - libsodium=1.0.16=0
  - locket=0.2.0=py36_1
  - markupsafe=1.0=py36_0
  - mistune=0.8.3=py36_1
  - msgpack-python=0.5.6=py36h2d50403_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - nbserverproxy=0.8.3=py36_0
  - ncurses=5.9=10
  - notebook=5.5.0=py36_0
  - numpy=1.14.5=py36_blas_openblashd3ea46f_200
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - packaging=17.1=py_0
  - pandas=0.23.1=py36_0
  - pandoc=2.2.1=hde52d81_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - partd=0.3.8=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.6=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.2.0=py36_0
  - python=3.6.5=1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - readline=7.0=0
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - sortedcontainers=2.0.4=py36_0
  - sqlite=3.20.1=2
  - tblib=1.3.2=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zict=0.1.3=py_0
  - zlib=1.2.11=h470a237_3
  - libgfortran-ng=3.0.1=h93005f0_2
```

</details>

**Comment by mrocklin** [comment]
I just ignore the index page and things tend to work well.  I wouldn't mind
if people fixed this of course.

**Comment by jakirkham** [comment]
Sure using the status page works fine.

It's just unfortunate that the index page in it's current state is not generally usable as soon any sort of proxying like this or the situation described in issue ( https://github.com/dask/distributed/issues/2073 ) come into play.

Given the problem outlined above, @bryevdv, do you have any suggestions for us? Is it possible to get relative links on the index page somehow?

**Comment by bryevdv** [comment]
> Is it possible to get relative links on the index page somehow?

I don't really use the index page at all. If others have strong opinions about how it should work or what it should present, I'm happy to consider and help get PRs merged.

**Comment by mrocklin** [comment]
It sounds like someone should submit a PR to bokeh that removes leading
slashes on the index page.

**Comment by mrocklin** [comment]
Closing here.  @jakirkham if you'd still like to see this resolved then I recommend posting something upstream.

**Comment by jakirkham** [comment]
Hmm...is it not possible for us to disable this page on our own?

**Comment by mrocklin** [comment]
I don't know

**Comment by bryevdv** [comment]
https://bokeh.pydata.org/en/latest/docs/reference/command/subcommands/serve.html

> This index can be disabled with the --disable-index option

**Comment by mrocklin** [comment]
Does that have a Python keyword equivalent?

**Comment by bryevdv** [comment]
`use_index` as per the documentation

https://bokeh.pydata.org/en/latest/docs/reference/server/tornado.html

**Comment by jakirkham** [comment]
Where would this keyword go in our code?

**Comment by mrocklin** [comment]
in distributed/bokeh/core.py::Server

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L356-L357 

>   Any remaining keyword arguments will be passed as-is to ``BokehTornado``.

**Comment by jakirkham** [comment]
Thanks. Added PR ( https://github.com/dask/distributed/pull/2241 ) to simply disable it.
