### ISSUE TITLE
Overcoming HPC restrictions

### ISSUE THREAD

**Issue by kristofarkas** [dask/distributed#2082]
The HPC that we work on has a number of restrictions that make the current suggested deployment of workers impractical (referring to `dask-jobqueue`), in particular:
- we are restricted to max 4 running jobs at any time
- 6h+ wall time only accessible with 313+ nodes (and jobs with 3000+ nodes are prioritised; can we do this with dask.distributed)

To my understanding `dask-jobqueue` is not able to submit multiple workers under 1 `qsub` command, true?

Experimenting with `dask-mpi`seems to work, but not sure about where to place to the scheduler: on login node, on MOM node or on compute node? 

I would like to submit my jobs to the scheduler *before* they go through the queue (which could be days). What is the best way to do this? Scheduler on login node + `fire_and_forget`? Another problem might be that long running processes on login nodes get shut down after some time. Can I restart a scheduler and connect to already running workers?

Finally a node on this HPC has 16 cores and a GPU. My workload requires a GPU and some cores (probably won’t use all 16 at any time). How do I tell Dask that the job that I will run has these requirements, and that it *shouldn’t* place more of these on the same node? Set the “GPU” resource?

**Comment by mrocklin** [comment]
Yes, dask-mpi seems like a sensible solution here.  

Alternatively you could also build a job script that created a dask-scheduler and many dask-workers manually.  That same script might also include your client code so that it runs at the same time.  You could do the same thing by modifying the dask-mpi MPI4Py program.

**Comment by kristofarkas** [comment]
What if I would like to have a jupyter lab interface to this? Otherwise how could I get the monitoring/status features of the scheduler?

**Comment by kristofarkas** [comment]
What if I start a scheduler on the login node therefore having interactive access to it. This scheduler doesn't have any workers yet though. Then I submit a job with `dask-mpi --no-scheduler` to get my workers on compute nodes connected to the scheduler on the login node.

While the job waits in the queue can I submit programs to the scheduler (that has no workers yet) and let it wait until the job starts and the workers connect?

Another reason I would like to have a jupyter lab interface is to monitor the programs, once the jobs start running.

**Comment by mrocklin** [comment]
Yeah, that's fine.  I thought that you mentioned that you have a time limit
for interactive jobs and that they might not be around when the workers
arrive.

**Comment by mrocklin** [comment]
It doesn't seem like there is a specific active issue here and conversation has stalled.  Closing.
