### ISSUE TITLE
as_completed drops cancelled futures instead of treating them as completed

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2089]
Dask's as_completed started dropping cancelled futures from PR #1366 . The original intent was to mirror concurrent.futures as_completed api, but it seems (from the docs, worth confirming) that concurrent.futures includes cancelled futures in the list returned. See https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed it says "Returns an iterator over the Future instances (possibly created by different Executor instances) given by fs that yields futures as they complete (finished or were cancelled)."

Discussion about the behavior took place in #2039 

The desired behavior is that successful, error and cancelled futures are all returned by as_completed in the order they reach that state which mirrors the concurrent.futures behavior (according to the docs!)

**Comment by wyegelwel** [comment]
Ok, I confirmed concurrent.futures behaves as expected:

```python
In [26]: from concurrent.futures import ThreadPoolExecutor, as_completed
    ...: import time
    ...: 
    ...: def sleep(sleep_s):
    ...:     if sleep_s == 5:
    ...:         raise Exception('testing error too')
    ...:     time.sleep(sleep_s)
    ...:     return sleep_s
    ...: 
    ...: with ThreadPoolExecutor(max_workers=5) as executor:
    ...:     futs = [executor.submit(sleep, sleep_s) for sleep_s in range(10, 1, -1)]
    ...:     print('Future cancelled? ', futs[-1].cancel())
    ...:     completed = as_completed(futs)
    ...:     completed = list(completed)
    ...: completed
    ...: 
Future cancelled?  True
Out[26]: 
[<Future at 0x7f56dc08c128 state=finished returned int>,
 <Future at 0x7f56dc0a3630 state=finished raised Exception>,
 <Future at 0x7f56dc0a3be0 state=finished returned int>,
 <Future at 0x7f56dc2e9dd8 state=finished returned int>,
 <Future at 0x7f56dc2d4c50 state=cancelled>,
 <Future at 0x7f56dc08c278 state=finished returned int>,
 <Future at 0x7f56dc2bbeb8 state=finished returned int>,
 <Future at 0x7f56dc2d4780 state=finished returned int>,
 <Future at 0x7f56dc0a30b8 state=finished returned int>]
```

**Comment by mrocklin** [comment]
I appreciate it.  Do you have any interest in submitting a patch for the
corrected behavior?  The relevant code is here:

https://github.com/dask/distributed/blob/f7c8f339412764367bcd42e01347a80fb25b9822/distributed/client.py#L3489
