### ISSUE TITLE
Build a Dask Proxy Server

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2102]
In #2043 @jcrist mentions the possible need to proxy Dask communications across some sort of gateway server 

![](https://user-images.githubusercontent.com/2783717/41182090-d402f554-6b39-11e8-979c-8ebd842a133d.jpeg)

I suspect that one way to do this is to build the following:

1.  A new lightweight `Server` class (this is a superclass of `Scheduler` and `Worker`) that accepts connections from the outside world that also contain connection information for addresses within its network, and then opens another connection to that local address.
2.  A new Dask Comm (like `tcp://`, `tls://` or `inproc://`) that includes both addresses `proxy://proxy-address::protected-address` so that components like the client don't really need to think about the proxy, except by providing such an address

My guess is that people interested in looking at this should probably start first with the [distributed Comms documentation](http://distributed.readthedocs.io/en/latest/communications.html).  First looking at how to build a proxy Comm and Listener classes in an isolated setting, presumably a `gen_test` style test somewhat like the following:

```python
from distributed.core import Server, connect
from distributed.utils_test import gen_test

def echo(comm, x):
    return x

@gen_test()
def test_proxy():
    server = Server({'echo': echo})
    server.listen(8000)

    myProxyServer = ProxyServer()
    myProxyServer.listen(8001)

    comm = yield connect('proxy://tcp://localhost:8001::tcp://localhost:8000'))

    yield comm.write({'op': 'echo', 'x': 'hello!'})
    response = yield comm.read()
    assert response == 'hello!'
```

cc @pitrou and @jcrist

**Comment by mrocklin** [comment]
@pitrou if you have time to look this over and provide any guidance or warnings that would likely be useful for whoever builds this.

**Comment by dhirschfeld** [comment]
I'm interested in this as I'm currently spinning up dask clusters on an HPC grid. Currently the HPC nodes are accessible from the enterprise network so users just connect directly to the node, but that may not always be the case. My thought here was to use [`nbserverproxy`](https://github.com/jupyterhub/nbserverproxy) as we're using JupyterHub and the JupyterHub node will always be available from the enterprise network.

**Comment by aterrel** [comment]
Sorry for the drive by comment. Did this ever get built? If so where should I look and if not is it something that a novice like me could contribute?

**Comment by jcrist** [comment]
Something similar to this lives at https://github.com/jcrist/dask-gateway. Think of it like jupyterhub (or Livy) but for dask. It provides a centrally managed server for starting/stopping/scaling dask clusters, as well as proxies for both the schedulers and dashboards. It currently works, but needs more work before I'd recommend it. Is this something you have a use case for?

**Comment by aterrel** [comment]
yes basically we have an api that spawns work and I would rather have something like this that can do a 202 polling interface rather than hang while dask does the work.

**Comment by jcrist** [comment]
The main problem `dask-gateway` is trying to solve is:

- Firewall between users (the `dask.distributed.Client` object) and clusters (`dask-scheduler` and `dask-worker` processes). With the gateway only 2 ports need to be open (one for the scheduler proxy, and one for the web proxy), all communication happens along these ports, and is secured via TLS.
- Central management of multiple dask clusters. This will allow for admin set policies (max resource usage, cluster lifetime, etc...). It also avoids the need to provide increased user permissions for other systems (e.g. users don't need to have direct permission to start kubernetes pods).

If your problem doesn't fall into either of these categories, perhaps there's a simpler method you could use? This would provide a pollable api for knowing when a cluster is up, but its not the only method.

**Comment by jcrist** [comment]
With the work in dask-gateway (almost ready for initial release), I'm going to close this issue. For future reference:

- dask-gateway repo: https://github.com/jcrist/dask-gateway
- docs: https://jcrist.github.io/dask-gateway/
