### ISSUE TITLE
Add support for wait(FIRST_COMPLETED)

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2108]
Concurrent futures [wait](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.wait) supports FIRST_COMPLETED, FIRST_EXCEPTION, and ALL_COMPLETED. It appears Dask only supports ALL_COMPLETED at the moment. There are many applications that are much easier to write with the wait(FIRST_COMPLETED) primitive as opposed to other primitives provided.

**Comment by mrocklin** [comment]
Agreed.  This would be a good thing for someone to implement if they have the time.  One approach might be to use `as_completed` to help solve this problem.
