### ISSUE TITLE
rpy2 in Dask cluster example

### ISSUE THREAD

**Issue by tsktsktsk123** [dask/distributed#2119]
Hello,

I've written a snippet of Python code that enables running R code in a Dask cluster. I'd like to contribute this snippet (made a bit more tidy and with comments) to your example page and I was wondering if you guys would like such an example. If so, I'd be happy to spend some hours cleaning up the example and enlighting the requirements and setup this example ran in.

## The snippet that works:
```
import pandas as pd
import numpy as np
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
from dask.distributed import Client

pandas2ri.activate()

def perform_r_ops(df):
    rstring="""
        library("forecast")
        library("tseries")
        function(df){{
            data = ts(df$data, frequency = 5)
            fit <- auto.arima(data)
            fit
        }}
    """
    rfunc=ro.r(rstring) #Pass R code
    rdf = pandas2ri.DataFrame(df) #Create R dataframe
    r_df = rfunc(df) #Pass Dataframe
    coef = np.array(r_df.rx('coef')) #Extract values
    return coef

def get_df(): #Generate dummy data
    c = 1000
    df = pd.DataFrame((np.random.random((c - 1)) * 0.05) * np.sin(range(1, c))).dropna()
    df.columns = ['data']
    return df

args = [get_df() for _ in range(100)] #Generate argument list

client = Client('tcp://localhost:8786')
futures = client.scatter(args, broadcast=True) #Spread data
A = client.map(perform_r_ops, futures) #Perform R code operations

results = [result.result() for result in A] #Gather results
pd.DataFrame(results).head() #Show results
```
## Requirements:
- Dask cluster with:
1. R installed and on PATH
2. rpy2 installed in the relevant Python environment 
3. Required R libraries installed

I ran this example on a 3 node cluster with each 2 cores and 4gb ram.

Love to hear from you. Also thanks for creating Dask, it's really nice.

**Comment by mrocklin** [comment]
I agree that an example using R and Dask would likely be very valuable.
Any interest in adding this to the dask-examples repository?  We've started
keeping runnable examples there:
https://github.com/dask/dask-examples#contributing

**Comment by tsktsktsk123** [comment]
Thanks for the link. I was looking for it but wasn't sure where to put it exactly. I'll write something up this week.
