### ISSUE TITLE
Spawned processes not stopped with parent

### ISSUE THREAD

**Issue by koverholt** [dask/distributed#212]
If I start `dworker --nprocs 4`, then `kill -9 [pid]` on the parent process, the 4 child processes continue to run. This also happens with `dscheduler` and the spawned `bokeh` server process.

Usually this comes up when I am running `dscheduler` or `dworker` with Supervisor, and I restart the parent processes, and end up with lots of `dworker` and `bokeh` processes. But I can also reproduce this on my laptop.

**Comment by mrocklin** [comment]
We start worker processes as follows:

```python
proc = multiprocessing.Process(...)
proc.daemon = True
proc.start()
```

We start the bokeh server using `subprocess.Popen`

Does anyone know best practices here?  My first instinct would be to ask on stackoverflow.

**Comment by koverholt** [comment]
I was able to fix this for my use case with supervisor using the `stopasgroup` program setting , which

> causes supervisor to send the stop signal to the whole process group.

This works for me, but I'll leave this open in case there is a different way to start the parent processes in which this might be a problem for other use cases.

**Comment by mrocklin** [comment]
For now I'm going to claim that we're doing everything as nicely as we can on the Dask side.  I think that responding well to SIGKILL has to involve a bit of work on the deployment side, such as the solution that @koverholt suggests.  I'm not sure what else can be done here.  Closing for now.
