### ISSUE TITLE
Worker exceeded 95% memory budget.  Restarting

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2130]
We are experiencing an issue where our distributed workers are being killed when they exceed their memory limit.

From the documentation it suggests that setting the `--memory-limit` flag sets the `Number of bytes before spilling data to disk`. So I'm slightly confused why the worker is restarting instead of paging to disk when the limit is reached.

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://100.97.248.36:42465'
distributed.worker - INFO -       Start worker at:  tcp://100.97.248.36:34437
distributed.worker - INFO -          Listening to:  tcp://100.97.248.36:34437
distributed.worker - INFO -              nanny at:        100.97.248.36:42465
distributed.worker - INFO - Waiting to connect to:   tcp://100.97.252.8:37343
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.00 GB
distributed.worker - INFO -       Local Directory: /home/jovyan/dask-worker-space/worker-i47r_7ng
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://100.97.252.8:37343
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - WARNING - Worker exceeded 95% memory budget.  Restarting
distributed.nanny - WARNING - Worker process 27 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
```

We are creating the workers using [dask-kubernetes](https://github.com/dask/dask-kubernetes) with a memory request set to `3GB`, and memory limit set to `4GB`. Then the `--memory-limit` flag is set to `3GB`.

**Comment by jacobtomlinson** [comment]
cc @niallrobinson

**Comment by mrocklin** [comment]
Yeah, that phrasing is outdated.  The best resource today is probably here:
http://distributed.readthedocs.io/en/latest/worker.html#memory-management

I recommend setting memory-limit to your total available memory and then
tweak the various policies (spill, pause, terminate) in your dask
configuration

**Comment by jacobtomlinson** [comment]
Thanks for that reference! That's really useful. I wish I had simply read further down the page 😄.

From reading more I imagine we are experiencing one of the problems which means the workers are not accurately estimating their memory usage (big graphs, custom objects, etc). 

Am I correct in thinking that the worker will estimate how much memory is being used and will spill anything over 60% to disk. But it does not spill the graph etc and it is likely that our workers are taking up the other 35% with that kind of stuff and then getting killed?

**Comment by mrocklin** [comment]
For the 60% mark they are measuring stuff using the (possibly incorrect)
sizeof function but for the 70%, 80%, and 95% marks they're using psutil.

Also, the graphs on the worker don't tend to take up too much.

The workers don't have any control over running functions or data
transfer.  If your tasks generate GB-sized intermediates then this could
blow up memory before the worker has a chance to pause.

**Comment by jacobtomlinson** [comment]
Ok thanks! It's a shame things die when run this way. When running things on my laptop my memory simply pages when it runs out, rather than things being killed.

Given this is expected behaviour I'll close this issue shortly. But before I do, do you have any suggestions on what we can do next?

Thoughts are:
 - Adjust config (but in what way?)
 - Increase memory on workers
 - Refactor code to use smaller intermediate chunks

**Comment by mrocklin** [comment]
It depends on why memory is increasing like that.  I might try to
investigate what might be happening on a worker by looking at the size of
objects being stored, maybe running a memory profiler on the functions
being run to see how much of a jump they create, etc..  That might tell you
if using a smaller chunk-size / total memory ratio would be helpful.

You can always turn off the restart functionality if you want, but
Kubernetes will probably kill your pod instead of Dask

**Comment by jacobtomlinson** [comment]
Ok thanks we'll look into it!

**Comment by BharatAD** [comment]
Hi with reference to the above discussion, would you be able to supply documentation as to how i might be able to lower the chunksize/total memory ratio?

**Comment by TomAugspurger** [comment]
That depends on how you're using dask. All the collections have parameters
to controls chunks / partitions.

With dask.delayed or the Futures API, you can get smaller chunks by making
the batches of input data smaller.

**Comment by Wapiti08** [comment]
sorry, I used venv, I did not find the configuration yaml in any part. Anyone had this issue before? Thanks
