### ISSUE TITLE
FIFO priority not being respected with delayed functions

### ISSUE THREAD

**Issue by kkraus14** [dask/distributed#2136]
I'm chaining together a bunch of delayed functions and then submitting them to the scheduler in one call via a loop, when calling `client.persist` I set `fifo_timeout='0ms'` figuring that it would prioritize the first iteration of the loop over subsequent iterations. This is not the occurring behavior where the later tasks in the first iteration's graph end up being stalled by early tasks in later iterations' graphs.

For example I'm doing something similar to the following:

```
futures = []
for i in range(10):
    df = dd.read_csv('some/path/based/on/'+str(i))
    df = some_other_function(df)
    df = df.repartition(npartitions=1).to_delayed()[0]
    df = delayed(my_func)(df)
    df = delayed(another_func)(df)
    futures.append(client.persist(df, optimize_graph=False, fifo_timeout="0ms"))

wait(futures)
```

And the `my_func` and `another_func` tasks end up being stalled by later iterations read_csv tasks. Any ideas?

**Comment by kkraus14** [comment]
Regarding the side note: before the delayed I repartition to a single partition to essentially convert to a pandas dataframe for feeding into my next function. Is this still bad practice?

I tried with priorities as well and still the same results as above. If I run with just a single iteration instead of my range it finishes in around ~1 minute, but if I run multiple it takes 20+ minutes before I see any repartition task start .

**Comment by mrocklin** [comment]
> Regarding the side note: before the delayed I repartition to a single partition to essentially convert to a pandas dataframe for feeding into my next function. Is this still bad practice?

Totally fine.  I just wanted to make sure that you were comfortable with everything coming into one partition.  In many workloads people try to avoid this. I'll assume that you know what you're doing here.

> I tried with priorities as well and still the same results as above. If I run with just a single iteration instead of my range it finishes in around ~1 minute, but if I run multiple it takes 20+ minutes before I see any repartition task start .

Given the information above I'm not sure how best to help.  My recommendation would be to look at the diagnostic dashboard and try to see if some insight about what is happening comes from that.  If you're able to produce an example that others can run locally that would probably help.

**Comment by kkraus14** [comment]
> Totally fine. I just wanted to make sure that you were comfortable with everything coming into one partition. In many workloads people try to avoid this. I'll assume that you know what you're doing here.

Yep, feeding the pandas dataframe into PyGDF where having a bunch of small dataframes be converted will lead to thrashing and poor utilization on the GPU.

> Given the information above I'm not sure how best to help. My recommendation would be to look at the diagnostic dashboard and try to see if some insight about what is happening comes from that. If you're able to produce an example that others can run locally that would probably help.

I'll create a minimal reproducible example in the near future once this demo is behind me. The premise though is that say 95% of the time is spent in doing read_csv and other typical data prep functions, and then my delayed functions are 5% of the time, I would want them to overlap when data prep is done for each iteration so I can free resources such as GPU memory when they're done as opposed to the data prep for each iteration finishing around the same time and all of the tasks waiting on GPU resources to run.
