### ISSUE TITLE
Dashboard page loads but none of tabs display any information

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/distributed#2137]
I am not sure if this is related to #1875 or perhaps something to do with Bokeh. I am able to create workers, perform my computation and get my results. Everything is fine there. The dashboard does load but the tabs display empty pages. The `info` tab does display information. 

<img width="1432" alt="screen shot 2018-07-20 at 1 38 46 pm" src="https://user-images.githubusercontent.com/6101444/43029477-515675ea-8c22-11e8-994f-451b492fe326.png">

<img width="950" alt="screen shot 2018-07-20 at 1 39 51 pm" src="https://user-images.githubusercontent.com/6101444/43029489-6aaa2924-8c22-11e8-8590-7870594f475c.png">

```
{'scheduler': {'host': (('python', '3.6.4.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.14.22+'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')),
  'packages': {'required': (('dask', '0.18.1'),
    ('distributed', '1.22.0'),
    ('msgpack', '0.5.6'),
    ('cloudpickle', '0.5.3'),
    ('tornado', '5.1'),
    ('toolz', '0.9.0')),
   'optional': (('numpy', '1.14.2'),
    ('pandas', '0.23.3'),
    ('bokeh', '0.12.15'),
    ('lz4', '1.1.0'),
    ('blosc', '1.4.4'))}}
```

I am also running `dask_kubernetes v0.4.0`

**Comment by MRichards99** [comment]
@jgerardsimcock I'm having similar issues, can you describe how you solved the problem?

**Comment by TomAugspurger** [comment]
@MRichards99 you might check the debug console in you browser. Sometimes there are warnings there about blocked websocket connections.

**Comment by MRichards99** [comment]
I was using Konqueror on X2Go Client. This is the only browser available on the machine I'm testing on (part of a cluster service). Forwarded the port to my local machine and viewed the page on Chrome, works perfectly. Moral is, Dask dashboard doesn't display at all (only the tab labels) on Konqueror. Hardly the highest priority in browser support I expect!

**Comment by martindurant** [comment]
Maybe ask on the bokeh issue tracker about Konqueror support
