### ISSUE TITLE
PyCharm Debugger Conflict

### ISSUE THREAD

**Issue by jamesstidard** [dask/distributed#2139]
Hi,

Using a async client in PyCharm in debug mode appears to hang. It seems distributed and PyCharm might be somehow interfering with each other.

I have [opened a issue](https://youtrack.jetbrains.com/issue/PY-30922) on PyCharm's bug tracker, though thought I'd post on here as well just incase there are any insights that could help this be resolved.

Thanks.

**Comment by rbubley** [comment]
There was a similar issue a while ago: #1174

**Comment by jamesstidard** [comment]
@rbubley ah, my mistake - missed that issue (only searched open issues). Knowing it's multiprocessing module and not distributed is good to know though. I'll add that to the PyCharm ticket.
