### ISSUE TITLE
Question: Is there an upper limit on number of workers?

### ISSUE THREAD

**Issue by venabled** [dask/distributed#214]
I'm getting a thread.error when using a gather operation on a large number of nodes. Might be related to the environment I'm operating in. Here's the stack trace: 

```
Traceback (most recent call last):
  File "/home/venabled/pysrc/navfeatdb/bin/distributed_air_extract.py", line 137, in <module>
    kp_list = executor.gather(r)
  File "/home/venabled/anaconda2/lib/python2.7/site-packages/distributed/executor.py", line 745, in gather
    return sync(self.loop, self._gather, futures, errors=errors)
  File "/home/venabled/anaconda2/lib/python2.7/site-packages/distributed/utils.py", line 108, in sync
    raise result[0]
thread.error: can't start new thread
```

**Comment by mrocklin** [comment]
I haven't run into this before.  A quick look around stackoverflow implies that this might be OS dependent.  Any chance you're on Windows?

You could try `import threading; threading.active_count()` to see how many threads are active.  If there are thousands of active threads then there is likely some bug within `dask.distributed`.  If there are only a handful then it might be best to handle this with system settings.

Can I ask how many nodes you're using?  Have you been doing anything else prior to this operation that might be peculiar?  

Are you gathering an iterator or Queue rather than a list of futures or a dask collection?

**Comment by venabled** [comment]
Gathering a list of futures generated from a map: 

```
        r = executor.map(my_func, odDicts, pure=False)
        kp_list = executor.gather(r)
```

Failed using 1000 nodes, works using < 100. Will try logging into an interactive shell and check out the active thread count.

**Comment by mrocklin** [comment]
It could be that you're receiving an error passed down from the Scheduler process as well, which is more likely to be under heavy load than the Executor.

Perhaps you're running into open file limits?  Each connection to a worker takes up a few sockets, each of which is an active open system file.  Linux usually sets user open file limits to 1024 by default.  This can be set much higher.

I'm not an expert on this, but if this is an issue you might want to check out the `lsof` and `ulimit` commands.

**Comment by mrocklin** [comment]
Any news on this @venabled ?  

Note that if you're using `dcluster` that *is* using a thread per node.  You might want to try setting up the dworkers with whatever system you use to launch jobs on your cluster.

**Comment by venabled** [comment]
We can probably close this for now, I do *think* the issue is a result of launching dcluster within the Torque execution environment which was throwing the issue. 

I've reworked my Torque / PBS launch script to iterate through each of the nodes and launch dworker.

I'm horrible at shell scripting, but this has been working for me on Torque/PBS:

```#!/bin/bash
#PBS -l select=xx:ncpus=yy:mpiprocs=1
#PBS -l walltime=00:30:00
#PBS -q queue
#PBS -m be
#PBS -j oe
#PBS -S /bin/bash

echo "number of nodes"
export PBS_NUM_NODES=`wc -l ${PBS_NODEFILE} | cut -f1 -d" "`
echo $PBS_NUM_NODES
echo "===================="
echo "ssh into each node"

#====================================================================
scheduler_node=$(head -1 $PBS_NODEFILE)
hostIndex=0
for host in `cat $PBS_NODEFILE`; do
    echo "Working on $host ...."
    if [ "$hostIndex" = "0" ]; then
        echo "run dscheduler"
        ssh $host dscheduler --port=8786 &
        sleep 5
    else
        echo "run dworker"
        ssh $host dworker --nprocs 1 --nthreads 1  $scheduler_node:8786 &
        sleep 1
    fi
    hostIndex="1"
done

echo "====-get to work-===="

ssh $scheduler_node
python distributed_executor.py
exit
```

**Comment by mrocklin** [comment]
Is there a way to tell Torque/PBS to run `dworker` itself, rather than running a shell and then ssh-ing into each machine?

**Comment by toniatop** [comment]
It is surely late and probably not usefule, but the answer to your question is (in theory) yes. One could use:
    pbsdsh -v bash -l dask-worker scheduler
to launch as many workers as cores available across all nodes
