### ISSUE TITLE
test_workspace_concurrency failing regularly

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2155]
We've started to see failures in `test_diskutils.py::test_workspace_concurrency` that I'm unable to understand

```
_________________________ test_workspace_concurrency __________________________
Traceback (most recent call last):
  File "C:\projects\distributed\distributed\tests\test_diskutils.py", line 260, in test_workspace_concurrency
    _test_workspace_concurrency(tmpdir, 2.0, 6)
  File "C:\projects\distributed\distributed\tests\test_diskutils.py", line 255, in _test_workspace_concurrency
    assert n_purged >= 0.5 * n_created > 0
AssertionError: assert 0 >= (0.5 * 1200)
```

cc @pitrou , author of that test, in case he's able to explain what is going on

**Comment by mrocklin** [comment]
Oh, I should point out that this is really only regularly failing on windows

**Comment by pitrou** [comment]
Can you pinpoint to a specific commit?

**Comment by mrocklin** [comment]
Not yet, no.  "Regularly failing" is a probably too strong to use here.
"Fails intermittently, but relatively frequently" would be better.

**Comment by mrocklin** [comment]
I agree that running this in a for loop on a Windows VM and doing git
bisect would be a good approach to isolate things.  I was hoping that you
might be able to provide some information before doing that, especially
because I'm unlikely to get to this near term.

I've xfailed this short term in
https://github.com/dask/distributed/pull/2152

**Comment by fjetter** [comment]
We've seen this popping up occasionally again on OSX
