### ISSUE TITLE
--memory-limit is per process, not per invocation of dask-worker.

### ISSUE THREAD

**Issue by rainwoodman** [dask/distributed#2166]
After connecting the workers to the scheduler, it appears that dask-worker forked nprocs processes, and each has the limit given by the --memory-limit passed to dask-worker.

The documentation wasn't very clear about this, and it was suggested nprocs is semantically equivalent to nthreads [1] which implied the memory-limit per forked process to be 1 / nprocs of the --memory-limit argument. Perhaps the current behavior shall be changed to make processes more equivalent to threads, or the document may need to be clarified that the limit is per process, not per invocation of dask-worker.

[1] https://distributed.readthedocs.io/en/latest/worker.html#thread-pool

**Comment by mrocklin** [comment]
I agree that the `--nprocs` parameter is a bit confusing, especially with
the interactions with `--memory-limit`.  I still have to check what the
behavior is each time when using this parameter.  As always, the challenge
to changing a parameter like this is doing it in a clean way that doesn't
break existing deployments.  Suggestions on the right path towards
something more sensible would be welcome.

**Comment by rainwoodman** [comment]
There is a way to make sense of this without breaking current deployments: just state clearly the memory limit is per process, not per invocation of dask-worker. I think we do need to make clear that the number of  invocations of dask-worker differs from number of worker processes. I can file a PR.

**Comment by lesteve** [comment]
I think his one has been closed by #2173.

@rainwoodman note you need to put the magical words (e.g. close #issueNumber) in the PR description to have the issue closed automatically when the PR is merged. Putting the magical words in a comment inside the PR does now work unfortunately ...
