### ISSUE TITLE
support of http file system to reading multiple files through glob

### ISSUE THREAD

**Issue by detectivebag** [dask/distributed#2174]
hi,

experts, first thanks for creating dask!

Recently I am working on a none hdfs system that holds many files through http service.

I would like to do something like

```python
import dask.bag as db
js = db.read_text("http://xxx-host:8000/q_*.gz")
```

it will raise `NotImplementedError`, I wonder what kinds of effort would I take to implement this?
The file `dask/bytes/http.py` does not implement glob.

Or do you have any other concern?

Thanks!

**Comment by martindurant** [comment]
There is no general way to query an HTTP server for a list of possible end-points. In certain limited cases it may be possible (swagger, ftp-on-http?), but we wouldn't know beforehand what the style remote service was.

**Comment by martindurant** [comment]
If you have a HDFS system backing the HTTP, can you can webHDFS calls to generate the list of files?

**Comment by mrocklin** [comment]
@martindurant should this be closed?
