### ISSUE TITLE
Implement collective communication strategies

### ISSUE THREAD

**Issue by stsievert** [dask/distributed#2178]
Perhaps using MPI (ref #2177).

<img width="457" alt="screen shot 2018-08-09 at 7 45 08 pm" src="https://user-images.githubusercontent.com/1320475/43932999-ac4cf248-9c36-11e8-8225-accfe48d0cdf.png">

from https://pytorch.org/tutorials/intermediate/dist_tuto.html#collective-communication

**Comment by mrocklin** [comment]
Why not just use MPI?

How would these fit into the existing task scheduling system?

What would happen if a worker died during one of these?

etc..

My initial reaction is that I think that these are good ideas, but probably
not a great fit for Dask.

**Comment by stsievert** [comment]
> Why not just use MPI?

Why use MPI? Performance might be better but the Dask's usability isn't there.

> What would happen if a worker died during one of these?

Good question.

> How would these fit into the existing task scheduling system?

I started to implement this between different `Worker`s, but held off on it. I had a basic all-gather working where I sent n<sup>2</sup> point-to-point communications. I think the implementation was something like

``` python
class Worker:
    def __init__(self, worker_id, num_workers=4):
        self.worker_id = worker_id
        self.num_workers = num_workers
        self.msgs = {}

    def get_msg(self):
        ...
        return msg

    def send(self, worker):
        worker.recv(self.get_msg(), sender=self.worker_id)

    def recv(self, msg, sender=0):
        self.msgs[sender] = msg

def all_gather(workers):
    futures = []
    for w1 in workers:
        for w2 in workers:
            futures += [w1.send(w2)]
    [f.result() for f in futures]

if __name__ == "__main__":
    client = Client()
    futures = client.map(Workers, range(4), actor=True)
    workers = [f.result() for f in futures]

    all_gather(workers)
```

**Comment by mrocklin** [comment]
To be clear for others, I think that @stsievert is referring to his own
actor class called Worker, not Dask workers.

**Comment by mrocklin** [comment]
Closing as out of scope.
