### ISSUE TITLE
serialization error

### ISSUE THREAD

**Issue by petacube** [dask/distributed#2179]
I am running the following task code (with distributed bag over ndjson files
(one json record per line) eg
{'a':1}
{'b:2}

 import dask
import dask.bag as db
from dask.distributed import Client
import pandas as pd
import my_user_function
import sys
from pyarrow import hdfs as HdfsClient
 
dask_scheduler = sys.argv[1]
client=Client(dask_scheduler)
 
dask.config.set(hdfs_driver='pyarrow')
 
# Using libhdfs
host= ‘some_host’
 
# port set to 0 indicates default port
port=8020
username = None
driver='libhdfs'
 
fs = HdfsClient.connect(host=host, port=port, user=username, driver=driver)
hdfs_path=“some hdfs path“
file_list = fs.ls(hdfs_path)
 
file_list=[file_list[0]]
 
for fname in file_list:
    fname = "hdfs://@" + host + ":" + str(port) + fname
    print(fname)
    b = db.read_text(fname).map(my_user_function)
    list_of_df  = b.compute()
    final_df = pd.concat(list_of_df,axis=0)
    final_df.to_csv("ready_to_load/sample.csv",index=False)
 

distributed.protocol.pickle - INFO - Failed to serialize (<function reify at 0x7fffeb9d5158>, (<function map_chunk at 0x7fffeb9d5488>, <function json_to_df at 0x7fff7d822488>, [(<function file_to_blocks at 0x7fffeb9d5d90>, <dask.bytes.core.OpenFile object at 0x7fff7c680828>)], None, {})). Exception: no default __reduce__ due to non-trivial __cinit__
distributed.protocol.core - CRITICAL - Failed to Serialize

**Comment by petacube** [comment]
did anybody ever tested dask bag with ndjson? is this format problem or some other issue?

**Comment by petacube** [comment]
in local mode (non-distributed dask bag,  without hdfs (with files in local fs). everything works fine)

**Comment by mrocklin** [comment]
Any update on this @petacube ?

**Comment by petacube** [comment]
its been resolved. I am still struggling with workflow but I am way beyond the serialization error
