### ISSUE TITLE
[Feature] Add Kudu FS support

### ISSUE THREAD

**Issue by frol** [dask/distributed#218]
[Kudu](http://getkudu.io/) is a "super-fast columnar storage" (I haven't compared it myself, so I quote the official site) written in C++. It aims to fill the gap between HDFS Parquet and HBase featuring high throughput (for batch processing) and low latency (for random access). There is an official Kudu Python client: https://github.com/cloudera/kudu/tree/master/python.

**Comment by mrocklin** [comment]
Is this something that you would actively use if implemented or is this just in the "that would be a nice idea" stage?

**Comment by mrocklin** [comment]
Does the Kudu Python API tell us the machines on which various partitions of data live?  This can be useful for data locality.

**Comment by frol** [comment]
@mrocklin We are starting a new project at our company, so we are on a stage of evaluating new perspective tools, and Dask+distributed+Kudu seems to be the best combo for us (we have tried to push PySpark and HDFS, but it didn't go too well because of a latency, and JVM drives me crazy).

**Comment by frol** [comment]
@mrocklin Unfortunatelly, it seems that Python API doesn't provide such interfaces yet. I have only found the [C++ internals](https://github.com/cloudera/kudu/blob/7f3691a826b9d27199319409f8d721ec1d08a8ba/src/kudu/master/master_service.cc#L207), and [Java client support](https://github.com/cloudera/kudu/blob/7f3691a826b9d27199319409f8d721ec1d08a8ba/java/kudu-client/src/main/java/org/kududb/client/LocatedTablet.java#L39).

**Comment by mrocklin** [comment]
I'll raise an issue in Kudu then

**Comment by frol** [comment]
Thank you! Please, post the issue link here for tracking.

**Comment by mrocklin** [comment]
https://issues.apache.org/jira/browse/KUDU-1401

**Comment by toddlipcon** [comment]
Todd from the Kudu team here. If either of you is interested in helping on the Python client side for Kudu, we'd love the assistance - most of us on the team are relative newbies when it comes to Python so help would be appreciated.

**Comment by mrocklin** [comment]
Closing this as out of scope for now.  I think we should reopen once Python support in Kudu is further along.  Even then, this is the sort of thing that should probably be driven by actual users, rather than speculation.

**Comment by mrocklin** [comment]
u

**Comment by frol** [comment]
Just for your info, Kudu Python client got improved significantly with Kudu 1.1 release (it is claimed that [it reached C++/Java parity](http://mail-archives.apache.org/mod_mbox/kudu-dev/201611.mbox/%3CCAGaaj_VKfB4mhu6eExHCWo0%3D6Qd0HFWy7bg9e39JgOaFPGJ1nQ%40mail.gmail.com%3E)), and the Kudu roadmap for 1.2 includes the integration with Pandas and PySpark.

> Even then, this is the sort of thing that should probably be driven by actual users, rather than speculation.

I believe, FS support can be implemented as plugins, but Kudu might be a good mainstream solution for the type of workload used in Dask. Is there a recommended production ready distributed storage for Dask? CSV/TSV files on HDFS/S3/NFS?

**Comment by mrocklin** [comment]
I'm very glad to see Kudu fully support Python.  If you're interested in taking on Kudu+Dask integration then let me know and I'll try to find some time to support.

> Is there a recommended production ready distributed storage for Dask? CSV/TSV files on HDFS/S3/NFS?

For Dask, no, because the broad variety of ways in which Dask is used in practice probably preclude a single recommendation.  For example many people use NetCDF for their Dask.array data while others use company-internal formats for tabluar data on S3.

For Dask.dataframe specifically (perhaps the intent of your question) I'm now recommending Parquet which seems to work well in master and should be out in the next release, hopefully within a week from today.
