### ISSUE TITLE
docs: Setup network -> Using AWS broken link

### ISSUE THREAD

**Issue by VMois** [dask/distributed#2192]
# Description
I have found a broken link in docs.

# Steps to reproduce
Go to "Setup network", then "Using AWS" section and click on "Cloud Deployments", it shows page not found.

# Proper behavior
Click on "Cloud Deployments" link should redirect to this page - https://dask.pydata.org/en/latest/setup/cloud.html

# Solutions
Fix typos in line *200* and *203* in **setup.rst** file.

**Comment by mrocklin** [comment]
Thanks for the bug report @VMois .  Would you be interested in submitting a fix?

**Comment by VMois** [comment]
Yes, of course.
