### ISSUE TITLE
Graph Dashboard really small?

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#2194]
Appears the Distributed Dashboard's Graph plugin has shrunk. Not totally sure what happened as it didn't use to be this way.

<img width="1329" alt="screen shot 2018-08-19 at 18 49 19" src="https://user-images.githubusercontent.com/3019665/44314015-b6d1ba80-a3e0-11e8-9083-09f12c9aba8b.png">

**Comment by mrocklin** [comment]
Yup.  That's a problem with bokeh 0.13.0.  It's reported upstream and they
say that they'll handle it in the next release.  Until then I recommend
going backto 0.12

**Comment by dhirschfeld** [comment]
Also mentioned in https://github.com/dask/distributed/pull/2123#issuecomment-405823539 but it's good to have this in it's own separate issue.

**Comment by jakirkham** [comment]
Ah ok. Thanks for the info. Is there an upstream issue?
