### ISSUE TITLE
Dashboard exception logged when transitioning in the dashboard

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#2195]
Guessing this is probably already known and is likely related to Bokeh 0.13.0 changes, but just wanted to document this here. When transitioning between different panels(?)/apps(?) in the dashboard, am seeing the following error logged.

```python
Exception ignored in: <bound method GraphPlot.__del__ of <distributed.bokeh.scheduler.GraphPlot object at 0x2b133391f828>>
Traceback (most recent call last):
  File "/opt/conda3/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 744, in __del__
    self.scheduler.remove_plugin(self.layout)
  File "/opt/conda3/lib/python3.6/site-packages/distributed/scheduler.py", line 2120, in remove_plugin
    self.plugins.remove(plugin)
ValueError: list.remove(x): x not in list
```

**Comment by jakirkham** [comment]
Seeing this with Bokeh 0.12.16 as well. In particular seeing this when trying to load the graph panel.

**Comment by mrocklin** [comment]
Yeah, there is some fancy logic in the GraphLayout plugin that looks to be
incorrect.  The intent behind that code was to avoid keeping the
graphlayout plugin around unnecessarily, and to avoid having more than one
active at a time.  It's clearly misbehaving though.

If anyone has the time to take a look at this that would be very welcome.
