### ISSUE TITLE
troubleshooting dask-worker to dask-scheduler connectivity

### ISSUE THREAD

**Issue by petacube** [dask/distributed#2206]
it would be helpful if dask worker has verbose mode so i can see which port its trying to open/connect.
i am trying to to troubleshoot situation when dask-worker hangs after printing "starting nanny on"

**Comment by petacube** [comment]
i traced the hanging to work-area being either corrupted or lacking disk space. once i had removed it in $HOME/dask-worker-space everything went back to normal.

**Comment by mrocklin** [comment]
Thank you for tracking this down and for informing others about the
solution.  I appreciate it.
