### ISSUE TITLE
unexpected keyword argument "Worker"

### ISSUE THREAD

**Issue by petacube** [dask/distributed#2207]
I have installed the latest distribued 1.22.0 from github
when i run dask-worker i get the following error

type error _run got an unexpected keyword argument Worker
line 174 in _run distributed/process.py

curious if anybody saw it before

**Comment by martindurant** [comment]
`Worker` is a new (internal) keyword when the nanny starts a process. That you are seeing this suggests that the `dask-worker` and the subprocess it in turn is calling are in different environments somehow.

**Comment by petacube** [comment]
i had removed the git version of distributed and installed one from conda and everything is back to normal.
