### ISSUE TITLE
bag  read_lines - all the processing happens on one node

### ISSUE THREAD

**Issue by petacube** [dask/distributed#2210]
Dask team, 
I am trying to process a giant (40GB) text file where each line is a json structure with variable number of columns some of which are overlapping. 

the code i had wrote to process that computes list of pandas df from each line, then computes common columns, extracts common columns from all the dataframes and finally concatenates them into single dataframe.  
when i am running code on the cluster i see that all the processing 95% of cpu concentrates on one thread in single node and the rest of workers are 3% utilized.  my understanding that dask read_lines distributes processing of lines evenly across the workers, is that not the case? 
is there a way to ship chunk of lines to each worker instead of line at time?

here my code below

```
client=Client(dask_scheduler)
hdfs = HDFileSystem(host=host, port=port)
file_list=hdfs.ls(hdfs_folder)

for fname in file_list:
    hdfs_fname = "hdfs://@" + host + ":" + str(port) + fname
    print(hdfs_fname)
    b = db.read_text(hdfs_fname).map(json_to_df)
    
    compute_graph  = client.compute(b)
    list_of_df = client.gather(compute_graph)

    # compute common columns
    list_of_columns = list(map(lambda d: d.columns, list_of_df))
    common_columns = list(reduce(lambda l1,l2: set(l1).intersection(set(l2)),list_of_columns))

    # drop dups
    dup_cols= list(set(reduce(operator.concat, map(lambda l: get_dups_in_list(l),list_of_columns))))
    
    final_common_columns = list(set(common_columns).difference(set(dup_cols)))
    list_of_df_cleaned = list(map(lambda d: d[final_common_columns], list_of_df))


#    common_size=mode(list((map(lambda x: x.shape[1], b))))
#    df_cleaned = list(filter(lambda d: d.shape[1] == common_size, list_of_df))
    final_df = pd.concat(list_of_df_cleaned,axis=0)
    final_df.to_csv(os.path.join("ready_to_load", os.path.basename(fname) + ".csv"),index=False)
```

**Comment by guillaumeeb** [comment]
I'm not sure I understand your workflow enough, but looking at your code example, the only operation that could be distributed is : 

```python
b = db.read_text(hdfs_fname).map(json_to_df)
compute_graph  = client.compute(b)
```
Second line from above code runs your json_to_df function in parallel, and then gather all the result in one place. But maybe you're already aware of this? Is this where your bottleneck is?

**Comment by petacube** [comment]
yes I see that first part with bag reading the file is bottleneck, does not matter how many workers I throw at the problem. it seems to run first part on single reader

**Comment by petacube** [comment]
here is some more benchmarking. 
this code with a small 2mb ndjson file running serially - 8s. 
dask distributed with 8 threads - 32s.

**Comment by martindurant** [comment]
What is your worker setup (processes, threads)?
Which hdfs driver are you using?

**Comment by petacube** [comment]
hdfs driver I am using is hdf3. for benchmarking I had used local Hadoop install on Mac (brew install Hadoop). I have tried with 8 processes or 1 process 8 threads - same thing. I was able to improve performance a little bit by changing client.gather to client.persist. and compressing the input file. still the main issue is that performance does not scale with number of workers/threads. I have benchmarked reading the entire file through Hadoop fs -cat | wc -l and and dask bag.read_text.count
- both show same timing of 0.1s so its parallel calculation that not happening is my conclusion.

**Comment by petacube** [comment]
finally got some parallel speed-up. I had to use blocksize parameter to match max Len of line and use 8 processes instead of 8 threads.

**Comment by mrocklin** [comment]
For threads/processes you may want to read through the documentation on scheduling http://dask.pydata.org/en/latest/scheduling.html

It's odd to see a compute call within a for loop

```python
for fname in file_list:
    hdfs_fname = "hdfs://@" + host + ":" + str(port) + fname
    print(hdfs_fname)
    b = db.read_text(hdfs_fname).map(json_to_df)
    
    compute_graph  = client.compute(b)
    list_of_df = client.gather(compute_graph)
```

It's more common to see people build up a larger graph and then compute it all at once in parallel.  If each of your files was small relative to the default blocksize then this would explain things.

**Comment by petacube** [comment]
the input files are large - 30-40gb each. for ndjson (line-json)  file format - its an enormous size. I wanted to process one file at time in case of processing errors I could fix the code and continue from the file that failed to process.

**Comment by mrocklin** [comment]
How many partitions does your bag have?  What does the dashboard look like?

**Comment by petacube** [comment]
I am using dask bag read_lines . it does not let me specify number of partitions 
I am using blocksize of 4000 which is max length of line. 
the number of lines is 25 Million.

I have about 12 machines, each running 30 worker processes , 128gb each machine

**Comment by mrocklin** [comment]
You can investigate the number of partitions of your bag by looking at the
npartitions attribute, or by looking at its repr.

I recommend looking at the diagnostic dashboard to get a better sense of
what is happening.  See
http://dask.pydata.org/en/latest/diagnostics-distributed.html

**Comment by petacube** [comment]
well after. several hours of processing the dask client gets killed
inside this code 
 b = db.read_text(hdfs_fname,blocksize=4000).map(json_to_df)
    
    compute_graph  = client.persist(b)
    progress(compute_graph)

**Comment by mrocklin** [comment]
Unfortunately there isn't enough information here for us to help you efficiently.  As stated before.  I recommend looking at the dashboard.

Is there anything else to be done here?

**Comment by petacube** [comment]
<img width="1069" alt="status" src="https://user-images.githubusercontent.com/30301994/44728024-6c6bd000-aaa9-11e8-993b-c2e0a99f6790.png">

**Comment by petacube** [comment]
<img width="940" alt="workers" src="https://user-images.githubusercontent.com/30301994/44728043-78579200-aaa9-11e8-8ff8-f5017d6a4e93.png">

**Comment by mrocklin** [comment]
Looks like a quiet cluster.  Nothing is computing.

**Comment by petacube** [comment]
its def consuming 60gb of ram on the client at least
**could it be that dask bag read_text hdfs interface is trying to read entire file into memory before distributing lines to workers**? I had assumed read_text is reading file line by line but in hdf3 documentation I won't see that option.

**Comment by mrocklin** [comment]
>  could it be that dask bag read_text hdfs interface is trying to read
entire file into memory before distributing lines to workers

No

I suspect that you just aren't connected to your cluster, so nothing is
happening.

**Comment by petacube** [comment]
I am def connected to the cluster here is the relevant code again. 
cluster aggregate memory is 1.2TB of RAM, 500cpus. 
its processing a single 30gb file json file and runs out of memory on the client... 

dask_scheduler = sys.argv[1]
client=Client(dask_scheduler)

# Using libhdfs                                                                                                                                                                                                                               
                                                                                                                                                                                                                     
host="some_Remote_host"
# port set to 0 indicates default port                                                                                                                                                                                                        
port=8020                                                                                                                                                                                                      
hdfs_folder="/user/test"

hdfs = HDFileSystem(host=host, port=port)
file_list=hdfs.ls(hdfs_folder)

for fname in file_list:
    start_time = time.time()
    hdfs_fname = "hdfs://@" + host + ":" + str(port) + fname
    print(hdfs_fname)
    b = db.read_text(hdfs_fname,blocksize=4000).map(json_to_df)

    compute_graph  = client.persist(b)
    progress(compute_graph)

    end_time = time.time()
    elapsed = end_time - start_time
    print("time to convert file to list of dfs in dask memory is " + str(elapsed))
    sys.stdout.flush()


    start_time = time.time()
    list_of_df = client.gather(compute_graph)

**Comment by mrocklin** [comment]
Your blocksize is 4kB, which is probably far smaller than you want. I
suspect that your bag has many millions of partitions and so overhead is
huge.

**Comment by petacube** [comment]
@mrocklin I was trying to match unit of computation which a single line. but you are right - once I have changed a blocksize to 100mb I see all cpus being used 100%. on the entire cluster and memory usage in client being fairly small. I guess if block sizes are small metadata size surges and that what leads my client app to run out of memory

**Comment by mrocklin** [comment]
Looks like this has been resolved.  Closing.
