### ISSUE TITLE
Computation on large array halts at 99%

### ISSUE THREAD

**Issue by guidocioni** [dask/distributed#2212]
Sorry for posting here but I didn't find any other relevant discussion and thought this was the most appropriate place for clarifications. I've been using Dask and distributed only for a few weeks so I'm still kind of a newbie..please be merciful!

We're trying to compute some statistics on an extremely large dataset. I'm talking individual netcdf files with 20 million points, and 20 timesteps spread across multiple folders. Of course normal approaches don't work with this dataset. That's why I tried to use Dask on our cluster. My approach is the following.

1. Define the cluster and start the jobs
```python
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(queue=mypartition, project=myproject, cores=36, memory='64 GB', walltime="2:00:00")
cluster.scale(20)
```
2. Connect to the cluster
```python
from dask.distributed import Client,progress
client = Client(cluster)
``` 
3. Do some computation
``` python
filenames=[]
for folder in folders:
    filenames=filenames+(sorted(glob(main_folder+folder+'/DATA/'+file_prefix+'_'+domain+'*')))
temps=[Dataset(fn).variables[variable] for fn in filenames]
arrays=[da.from_array(t, chunks=(chunk_time,chunk_space)) for t in temps]
var=da.concatenate(arrays, axis=0)
```
At this point I have a variable shaped like this 
`dask.array<concatenate, shape=(17075, 22282304), dtype=float32, chunksize=(100, 1114115)>`
I know...it's enormous.
Next step is to compute the mean.
```python
mean=var.mean()
mean=mean.persist()
```
This works. If I do `progress(mean)` I can see the progress bar slowly reaching 100% (takes about 40 mins). However at 99% the progress halts and does not finish. In the logs I get a lots of warning `event loop was unresponsive in Worker for 7.05s.  This is often caused by long-running GIL-holding functions or moving large chunks of data.` although I don't know whether this is just a non-relevant warning.

I also get this error 

```python
Traceback (most recent call last):
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/distributed/worker.py", line 2179, in execute
    data = {k: self.data[k] for k in self.dependencies[key]}
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/distributed/worker.py", line 2179, in <dictcomp>
    data = {k: self.data[k] for k in self.dependencies[key]}
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/zict/buffer.py", line 72, in __getitem__
    raise KeyError(key)
KeyError: 'array-original-7d089656d31ff648f3680bb6bfcaea6c'
tornado.application - ERROR - Exception in callback <functools.partial object at 0x2b1f87e283c0>
raceback (most recent call last):
  File "/sw/rhel6-x64/python/python-2.7.12-gcc49/lib/python2.7/site-packages/tornado-4.5.1-py2.7-linux-x86_64.egg/tornado/    ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/sw/rhel6-x64/python/python-2.7.12-gcc49/lib/python2.7/site-packages/tornado-4.5.1-py2.7-linux-x86_64.egg/tornado/    stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/sw/rhel6-x64/python/python-2.7.12-gcc49/lib/python2.7/site-packages/tornado-4.5.1-py2.7-linux-x86_64.egg/tornado/    ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/sw/rhel6-x64/python/python-2.7.12-gcc49/lib/python2.7/site-packages/tornado-4.5.1-py2.7-linux-x86_64.egg/tornado/    concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/sw/rhel6-x64/python/python-2.7.12-gcc49/lib/python2.7/site-packages/tornado-4.5.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/distributed/worker.py", line 2179, in execute
    data = {k: self.data[k] for k in self.dependencies[key]}
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/distributed/worker.py", line 2179, in <dictcomp>
    data = {k: self.data[k] for k in self.dependencies[key]}
  File "/home/mpim/m300382/.local/lib/python2.7/site-packages/zict/buffer.py", line 72, in __getitem__
    raise KeyError(key)
```

I've tried working on a smaller dataset by selecting only some filenames and obtaining a variable which has a slightly smaller time dimension (something like 1000 instead than 17075). In this case, instead, using the same method everything works! I get to 100% and if I do `print(mean.compute())` I can indeed see the result of the computation.

So...am I doing something wrong in my workflow or the data is simply too large to analyze? I've tried modifying the chunk but I don't really know what they are supposed to be to optimize the execution. 

Any help is appreciated.

**Comment by petacube** [comment]
I am guessing one of the netcdf files is corrupt - maybe dimension values in it are not matching the types in in other netcdf files . the chunk sizes are decent in my opinion  - 100mb. see if you can validate the types of dimensions.

**Comment by guidocioni** [comment]
I've just checked and it looks like they are all the same in dimensions, dimension types, names... The only difference is that for one of the cases I have far more time steps per file since that simulation was performed with a finer output time step. 

Furthermore, when you concatenate I'm pretty sure it should spit any error regarding mismatching dimensions/types. 

I may now try to compute everything excluding that case, maybe that is the culprit.

**Comment by mrocklin** [comment]
I don't know any reason why this would happen.  In your situation I would
investigate the situation further with the diagnostic dashboard.
http://dask.pydata.org/en/latest/diagnostics-distributed.html

**Comment by guidocioni** [comment]
Hello,
it took me quite a while to get the dashboard to work as I had to tunnel through multiple machines but here we go... 
Today the same happened. After a computation successfully finished  I launched another one with .persist() and at the end the process halted like this.

![screen shot 2018-08-28 at 12 29 08](https://user-images.githubusercontent.com/12760310/44717719-16edee00-aabe-11e8-8cb1-550020aa83a1.png)
![screen shot 2018-08-28 at 12 29 14](https://user-images.githubusercontent.com/12760310/44717723-1bb2a200-aabe-11e8-9f80-4ecf4249a4e8.png)

Taking a look at the worker tabs it looks like some of them are still doing computations. 

![screen shot 2018-08-28 at 12 29 29](https://user-images.githubusercontent.com/12760310/44717739-2bca8180-aabe-11e8-9e11-56749501f05d.png)

But going into the log of those two workers with pending jobs I'm greeted with these messages:

````python
distributed.worker - ERROR - ('memory', 'waiting') 
Traceback (most recent call last): File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 1814, in gather_dep self.transition_dep(dep, 'waiting') File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 1383, in transition_dep func = self._dep_transitions[start, finish] KeyError: ('memory', 'waiting')

distributed.worker - ERROR - 'array-original-65778dc6b776f4af2db1141d523cdd2b' Traceback (most recent call last): File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 2179, in execute data = {k: self.data[k] for k in self.dependencies[key]} File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 2179, in <dictcomp> data = {k: self.data[k] for k in self.dependencies[key]} File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/zict/buffer.py", line 72, in __getitem__ raise KeyError(key) KeyError: 'array-original-65778dc6b776f4af2db1141d523cdd2b'

distributed.worker - ERROR - 'array-original-65778dc6b776f4af2db1141d523cdd2b' Traceback (most recent call last): File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 2179, in execute data = {k: self.data[k] for k in self.dependencies[key]} File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/distributed/worker.py", line 2179, in <dictcomp> data = {k: self.data[k] for k in self.dependencies[key]} File "/work/mh0731/m300382/conda_envs/my_env/lib/python2.7/site-packages/zict/buffer.py", line 72, in __getitem__ raise KeyError(key) KeyError: 'array-original-65778dc6b776f4af2db1141d523cdd2b'
````

**Comment by mrocklin** [comment]
I believe that that error may be fixed in master.  Is it easy for you to
try to upgrade and see if that resolves things?

pip install git+https://github.com/dask/distributed.git --upgrade

**Comment by guidocioni** [comment]
being right now on conda I think it may be possible to try the master in a virtual env. Is there an equivalent of `pip install git+https://github.com/dask/distributed.git --upgrade` in conda?

**Comment by mrocklin** [comment]
It's the same.  You can use pip in conda environments.

**Comment by guidocioni** [comment]
Ok sry I thought it was going to screw up something with conda as I installed dask through conda.

**Comment by guidocioni** [comment]
I'm back with  some updates.
I finally managed to run dask using a single job and multiple nodes instead that with dask-jobqueue which is more flexible but causes me to go over the limit of maximum concurrent jobs on the machine. The way I've done it is simply `srun -l --cpu_bind=threads --distribution=block:cyclic --propagate=STACK /work/mh0731/m300382/conda_envs/dask/bin/dask-mpi` and then connect to the scheduler address with `Client('scheduler address)`.

Scheduler: tcp://10.50.41.63:8786  Dashboard: http://10.50.41.63:8787/status | Cluster  Workers: 31 Cores: 2232  Memory: 2.08 TB
-- | --

I'm using the master version of distributed. Looks like everything's running but I think I'm getting a strange behaviour. If you look a the status page of the GUI you can clearly see that there are cores doing nothing. 
![interface_gui mov](https://user-images.githubusercontent.com/12760310/44787819-7f110280-ab98-11e8-9d79-3efefef41df0.gif)
Is it maybe because I'm using too much cores which are not able to efficiently comunicate? I can add more statistics if required. To me it also looks like the transfer of chunks are taking way too long.

In the meantime, although everything's running and it looks like it's computing, the workers are spitting out a lot of errors. Not sure why these are not causing a crash. 

![log mov](https://user-images.githubusercontent.com/12760310/44787558-cba80e00-ab97-11e8-98c1-631426afa6c8.gif)

**Comment by mrocklin** [comment]
Looking at the top-right plot it seems like all of the workers have
something to work on.

The central task stream plot only shows the last 1000 tasks, so may not
give you the full picture.  I recommend looking at the tasks page which
updates less frequently, but includes the last 100,000 tasks and so will be
more filled in.

Thank you for reporting the errors on the worker.

**Comment by guidocioni** [comment]
Thanks for taking a look into this. 

As said,  given that I'm not used to interpret the diagnostic, it can be that there are no problems and this is what a normal computation is supposed to look like. Anyway, as long as the computation are not failing I'm happy with the setup :)

**Comment by mrocklin** [comment]
The worker issue is resolved (though without tests) here:
https://github.com/dask/distributed/pull/2217

I recommend looking at the tasks page (there is a link in the navbar) to
verify that things look ok.

The docs have a 20 minute screencast about the dashboard that might be
helpful:
http://dask.pydata.org/en/latest/diagnostics-distributed.html#dashboard

**Comment by mrocklin** [comment]
Anything else here?  I'm going to close.  If there are still issues then please speak up.  You may also want to try the latest release available with both pip and conda
