### ISSUE TITLE
resilience of dask ML computations

### ISSUE THREAD

**Issue by markbudiak** [dask/distributed#2219]
Hi,
I want to use dask to paralyze my computations on a cluster network with two workers - one is less powerful but highly reliable and the second one is very powerful but less reliable meaning that the worker might stop working suddenly from time to time.

I want to perform extensive gridsearch. The scheduler sends tasks to the workers. But suddenly the powerful worker has stopped. Nothing happens because scheduler redirects the tasks to remaining worker and the tasks that were ran by the powerful worker are going to be recomputed on the remaining worker right?

In such cases, is there a way how to avoid recomputing these results? like saving the intermediate results on the actor that is assembling and evaluating the results? 
Who is actually assembling and evaluating the grid search tasks and picking the best parameter set? Is it Client or scheduler or worker?

**Comment by markbudiak** [comment]
I am using dask_ml.model_selection.GridSearchCV.
My observation:
Setup: 2 doceker container - scheduler and worker.
I sent the computation from client. I kept running it for some time (half of the time that the computation runs) and then I turned off the worker. Then I started it again and I saw in the worker outputs that it is recomputing the tasks again. Then I tried to get more accurate results by observing the number of tasks on the scheduler. I wrote a plugin for the scheduler where I implemented add_worker and remove_worker methods and every time a worker was added and removed I printed out the number of tasks on the scheduler. However, in my case, the number did not change. It was always the same. 
Is there a better way how to observe current number of tasks on the scheduler?
What I also observed is that the number of tasks was 15 but I was doing grid search over one parameter with 2 possible values and CV was set to 3 so there should be just 6 tasks not 15. Is it possible that client outsources the evaluation of the results to the worker too and therefore there was more tasks?
If it is doing so, is it possible to tell scheduler that such evaluation tasks should be run on another worker?

**Comment by markbudiak** [comment]
Actually, looking at the console gives a nice overview. There is of course more number of tasks because there are more tasks added to it not just pure computation like cv-split, cv-parameters, cv-results, best-estimator and so on ... which makes 15 tasks in total.

Here is a screenshot of the task stream (it is just a simple task - here on one worker. It is just for simplicity. In real world scenario there are around 1000 tasks):
![screenshot from 2018-08-30 10-58-28](https://user-images.githubusercontent.com/5913311/44841760-63fbcc80-ac44-11e8-855d-ef513788689d.png)
The green boxes are actual computations. The cyan colored boxes are cv-results and cv-best-params tasks. Dark Blue color is fitting again the best estimator.

- I think now I understand the flow of tasks in my case and the question is: is it possible to force cv-results, cv-best-params and the best estimator refitting tasks to run on a specific worker?
- What is still unclear to me is that if one computation is done and the results are already available then the worker just stores them locally until cv-results and cv-best-params tasks are called. Then when another worker is executing cv-results and cv-best-params tasks it asks other workers for the results and they send him the results. The question is: is it possible to save somewhere these results so that in case of failure they will not get lost or to send them periodically to the worker that is going to execute cv-results and cv-best-params tasks?

**Comment by mrocklin** [comment]
> is it possible to force cv-results, cv-best-params and the best estimator refitting tasks to run on a specific worker?

You can specify `workers=` when you call compute/persist, but you would need to specify all of the keys individually.  I think that pragmatically the answer to this today is "no".

> The question is: is it possible to save somewhere these results so that in case of failure they will not get lost or to send them periodically to the worker that is going to execute cv-results and cv-best-params tasks?

Short answer is "no", this isn't easy to do without a lot of work.

Anything else @markbudiak ?
