### ISSUE TITLE
Add shutdown function to register_worker_callbacks

### ISSUE THREAD

**Issue by guillaumeeb** [dask/distributed#2224]
As mentionned in #2140, this could be useful to add the possibility to register one or several function to be run when workers stop. This should follow the work done in #2201.

This issue is mainly a reminder to complete the created interface.

**Comment by 1234sv** [comment]
Hi, is there any patch submitted further on this?

**Comment by mrocklin** [comment]
See docs here: https://docs.dask.org/en/latest/setup/custom-startup.html#worker-lifecycle-plugins
