### ISSUE TITLE
Dashboard shows work being done on incorrect cores after update to 0.19?

### ISSUE THREAD

**Issue by TAdeJong** [dask/distributed#2225]
Bit of a low priority issue this, but a funny one. 
I run a `map_blocks` of a numba compiled function on a local distributed scheduler running 8 processes. 
Before updating to version 0.19, all work showed up in the dashboard Task Stream, nicely distributed over the cores.
After updating however it looks like this:
![dashboard](https://user-images.githubusercontent.com/6816964/44988404-d9400800-af8a-11e8-8953-fa98ca7daeed.PNG)
That is, it seems that all tasks get progressively more rendered on the lowest thread/core, instead of where they actually run/complete, as completion time and CPU usage stayed roughly the same.
Also note the 6-fold overlay suggesting one worker is working on 6 jobs at once.

As mentioned, not high priority, but a weird regression I noted after updating.

**Comment by mrocklin** [comment]
That is odd.  Thank you for mentioning it.  Are you able to replicate it
consistently?  If so, do you have something that you can share?  That's
probably the first step in tracking down and solving the problem.

**Comment by TAdeJong** [comment]
OK, I do not have time for a thorough MWE, so I have a somewhat contrived example as I mostly copied it from existing code:

```
from dask.distributed import Client
import dask.array as da
import numpy as np
import numba

client = Client('localhost:8786')

@numba.jit(nopython=True, nogil=True)
def getShiftedDifferences(data, template):
    N, M = len(data), len(template)
    res = np.empty((N-M, M))
    for i in range(N-M):
        slicenorm = 0
        for j in range(M):
            slicenorm += data[i+j]**2
            res[i, j] = (template[j] - data[i+j])**2
        res[i, :] = res[i, :] / slicenorm

    return res.sum(axis=1)

@numba.jit(nopython=True, nogil=True)
def getShiftedDifferences_block(data, template):
    N, M = data.shape[:2]
    res = np.empty((N, M, data.shape[2]-len(template)))
    for i in range(N):
        for j in range(M):
            res[i, j, :] = getShiftedDifferences(data[i, j, :], template)
    return res

#Or really just some other data
D = da.ones((1000,1000,200), chunks=(80,80,-1))
T = np.random.random(20)

X = da.map_blocks(getShiftedDifferences_block,
                             D,
                             T,
                             chunks=D.chunks[:2] + ((D.chunks[2][0]-len(T),),),
                             dtype=D.dtype)
X.compute()
```
yields a profile like this:
![dashboard2](https://user-images.githubusercontent.com/6816964/44993858-5f187f00-af9c-11e8-81bd-0424b1d68804.PNG)
While the task manager shows all cores busy.

**Comment by mrocklin** [comment]
If you remove Numba does the problem persist?

**Comment by TAdeJong** [comment]
@mrocklin : Yes, the problem persists if I remove `numba` and replace the top function by something returning `np.zeros()`.

**Comment by mrocklin** [comment]
@TAdeJong if you have the time to investigate this further that would be *very* helpful.  It would be good to track this down.  I tried your example and replacing the top function with the following:

```python
@numba.jit(nopython=True, nogil=True)
def getShiftedDifferences(data, template):
    N, M = len(data), len(template)
    res = np.zeros((N-M, M))
    return res.sum(axis=1)
```

But I wasn't able to reproduce the issue.

**Comment by TAdeJong** [comment]
I will try to replicate this on another machine in the next few days, although my issue with `argmin` is a bit more blocking to me.

**Comment by mrocklin** [comment]
Fixed in https://github.com/dask/distributed/pull/2238
