### ISSUE TITLE
Problem with worker registration after ``client.restart()``

### ISSUE THREAD

**Issue by alorenzo175** [dask/distributed#2229]
I've been having trouble with distributed 1.23.0 calling ``client.restart()``on a cluster. The worker nanny successfully stops and starts the worker but the registration message never makes it to the scheduler. This is all happening on a kubernetes cluster and I haven't been able to reproduce the problem locally. 

I have traced the problem back to the changes in #2170. In python 3, the registration message is now always offloaded to the ``distributed.comm.utils._offload_executor``. After a worker restart, it seems that the daemon threads of the ThreadPoolExecutor are stopped when ``_to_frames``is sent to the execution queue. ``_to_frames``then just sits in the queue and isn't processed while the restart/registration times out. I think this is likely the same issue that causes the adaptive test to fail on python 2.7. I haven't been able to figure out what the problem with the ``_offload_executor``is or how to resolve it, so maybe someone else has an idea of what might cause this behavior?

Versions:
distributed 1.23.0
python 3.6.5
dask 0.19.0

**Comment by jrbourbeau** [comment]
Checking in here. It's been a while since this issue saw any activity. @alorenzo175 are you still running into this issue, or is it safe to close?

**Comment by alorenzo175** [comment]
I no longer work on the codebase that this issue came up in, but I do think it was resolved at some point.
