### ISSUE TITLE
Identity management / impersonation 

### ISSUE THREAD

**Issue by dcieslak19973** [dask/distributed#2246]
Would like to see if there’s a way to support the following scenario:

A. A dask cluster running on N nodes each running as a non-human user (e.g. dask-svc)
B. Human users running python programs from their desktops as a human user (e.g. myuser), connecting to the cluster described above.

Currently, it seems that work sent from myuser to the cluster executes on the cluster machines as dask-svc. This, in itself, may be fine. However, there may be cases where the code executing on the cluster needs to access a database, where the preference would be to present the myuser identity to the database rather than the dask-svc identity.

Ideally, this would be done through something like Kerberos tickets. This would require the dask-svc identity to have special privileges as far as impersonation goes.

**Comment by mrocklin** [comment]
I agree that this is a valid use case.  Typically it has been handled outside of Dask, by having another system capable of impersonation start up dask workers on the fly.

**Comment by mrocklin** [comment]
For now I think that I'm going to close this as out of scope.  This should be handled by whatever launches dask.
