### ISSUE TITLE
Allow for overriding the limit for truncating exceptions

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2248]
Currently, distributed will truncate an exception if it is longer than 1000 characters (lines?) https://github.com/dask/distributed/blob/dbb529ba6c0acb03fb915eec4c1ff846bb2c8c72/distributed/core.py#L843 

From a user perspective this is very jarring because it makes debugging nearly impossible and it isn't obvious dask is the one truncating the error. Googling for "Long error message" doesn't yield anything useful. Having a way to override the limit (and informing the user how to do that in the error message) would make it possible for users to proceed when this problem occurs.

**Comment by mrocklin** [comment]
Making that configurable makes sense to me.  We should probably put an
entry under `distributed.worker.maximum-error-length` or something similar
(See http://dask.pydata.org/en/latest/configuration.html).  Would you be
interested in making this change and submitting a pull request?

**Comment by mrocklin** [comment]
@wyegelwel is this something that you're able to contribute?

**Comment by OliverHofkens** [comment]
A quick scan through the code shows that this has been implemented in the meantime.
`truncate_exception` is only used once, and the `n` parameter is fetched from the `distributed.admin.max-error-length` config option:

https://github.com/dask/distributed/blob/4e2c1b36a9cfb7df092f47ca604511319cbeab52/distributed/core.py#L1195-L1199

I believe this issue can be closed 🎉

**Comment by fjetter** [comment]
Thanks for catching this @OliverHofkens
