### ISSUE TITLE
Bokeh Task Stream doesn't get cleared after a client.restart()

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#2253]
As it says in the title. Ideally for me a `client.restart()` would clear the previous tasks.

If the current behaviour is as intended I'm fine with that, I'm just opening this issue in case the current behaviour isn't intended.

**Comment by mrocklin** [comment]
I'm curious, why would it be ideal for you to have client.restart clear
previous tasks?

**Comment by mrocklin** [comment]
Historically I've found it convenient to see what happened in previous runs
on the larger /tasks view.

**Comment by dhirschfeld** [comment]
Isn't that what happens by default, if you don't reset your cluster? i.e. If you want the task history, don't reset your cluster; if you want a clean history call reset?

Is there some usecase where you would want to reset the cluster but still keep the task history?

**Comment by mrocklin** [comment]
The actual scheduler state is indeed reset, it's just the history that is
kept around.  It doesn't affect performance to keep history around.

Perhaps I should ask, why do you want to explicitly clear that history?

**Comment by dhirschfeld** [comment]
Just that it can clutter the task view with history I don't care about - e.g.
![image](https://user-images.githubusercontent.com/881019/45655074-acaaf500-bb21-11e8-828a-463392eb8eaf.png)

I want to see what happened in my most recent run but because the old run is kept around each task in the task stream appears infinitesimally small making it hard to extract any useful information visually.

**Comment by dhirschfeld** [comment]
...just realised I can use the box zoom to get the view I want.

Also, it's a bit strange - sometimes a run will immediately show me a blown up view of just the latest tasks and sometimes it includes the history with all the whitespace. Since I can just zoom it doesn't matter much.

**Comment by dhirschfeld** [comment]
Since it seem this is intended I'll close this.
