### ISSUE TITLE
client.cluster == None when Client() instantiated with scheduler address

### ISSUE THREAD

**Issue by mturok** [dask/distributed#2266]
Hi,

It seems that client.cluster isn't populated when Client() is instantiated with a scheduler address and not a cluster object.

Is there a way to get a handle to the cluster itself from the scheduler in a clean way?

(This is really related to other issues about being able to cleanly shut down a cluster from a client:  https://github.com/dask/distributed/issues/1085)

Michael

**Comment by mrocklin** [comment]
Short answer is no.  Cluster objects are not strictly required to use Dask,
nor are they guaranteed to exist on the same machine.  In principle the
client only ever talks to the scheduler.  I suspect that you may be
interested in https://github.com/dask/distributed/issues/2235
