### ISSUE TITLE
Is possible to adding dinamically workers during the execution of scheduler ? 

### ISSUE THREAD

**Issue by giuseppe1993** [dask/distributed#2269]
Hello, I was trying dask on a cluster.
In this cluster the number of nodes can increase or decrease during the resolution of problem. 
Is possible doing this with dask ?

**Comment by VMois** [comment]
Yes, it's possible. The preferable way of setting up Dask cluster is using Kubernetes cluster.

This is a few links to help you:
- https://github.com/dask/dask-kubernetes (for dynamic Kubernetes Dask cluster)
- https://dask.pydata.org/en/latest/setup/kubernetes-helm.html (for static Kubernetes Dask cluster)
- https://github.com/VMois/dask-k8s-chart (it's Helm chart for setting up dynamic Kubernetes cluster, work is based on two above repositories, now, it's under active development)

BTW, I think, for this type of question is better to use StackOverflow.

**Comment by giuseppe1993** [comment]
Thank you very much for helping. 
I apologize for posting the problem here, with this I close the issue goodbye

**Comment by mrocklin** [comment]
FWIW, kubernetes is only one way, not necessarily the preferred way.  My
experience is that groups don't have the ability to choose their cluster
manager.  It is usually chosen for them.
