### ISSUE TITLE
Expose graph_to_future method

### ISSUE THREAD

**Issue by bmaisonn** [dask/distributed#2271]
Hi,
I'm using the Client.get method to compute graphs. However i'd like to integrate progress widgets in jupyter notebook.
The progress utilities all assumes that we have futures in input.
I see in code a private method _graph_to_future that can be used to transform graph to future.
Is it possible to make it part of the API ?

**Comment by mrocklin** [comment]
I'm curious, how would you use `_graph_to_futures` if it was public?  

Why is this necessary in order to get progress bars?

Have you considered using the `sync=False` keyword in `Client.get`?  (see docstring or source)

**Comment by mrocklin** [comment]
That looks like you don't have ipywidgets configured correctly.  My guess
is that you're using JupyterLab and haven't installed the notebook
extension. Just a guess though.

**Comment by bmaisonn** [comment]
Indeed, it's working fine now. Thx for your help!
