### ISSUE TITLE
import collision with resource module

### ISSUE THREAD

**Issue by jamesstidard** [dask/distributed#2280]
Just spent a while debugging why my distributed client stopped working. There seems to be some namespace collision between distributed and the package using distributed.

My application has a module named "resource", and when present, will cause a `AttributeError: module 'resource' has no attribute 'getrlimit` on loading a async client (and probably in other use-cases).

I've zipped up an example project which will produce the error when run.

It uses `pipenv`, so you should just be able to `pipenv sync` then `pipenv run python example/main.py`.

[example.zip](https://github.com/dask/distributed/files/2434819/example.zip)

**Comment by mrocklin** [comment]
Yeah, distributed uses the resource standard library.  There isn't much we
can do about this.  You should probably avoid name conflicts with the
Python standard library

https://docs.python.org/3/library/resource.html

**Comment by jamesstidard** [comment]
@mrocklin Oh, I had never ran across resource before in the standard library. Okie doke, adding an underscore I guess :).

Thanks again.
