### ISSUE TITLE
Native distributed dataset storage/loading without resort to another hop

### ISSUE THREAD

**Issue by HiddenPython** [dask/distributed#2294]
First, thank you very much for building Dask Distributed, one of the *best* Python data analytics tool since sliced bread/ Pandas!

I know it can currently load dataset distributedly either through shared storage, such as NFS, or through another distributed file system, such as HDFS. But both approaches involve extra setups, extra hops and even reduced performance in the case of NFS, where all data are loaded from the same IO channel. It would be great if each worker can load part of the dataset (some path glob) local to it and make it a distributed in-memory dataset as normal for further processing. In the same way, users can request workers to save a distributed in-memory dataset in each worker to local disk in the format of either flat text (e.g. csv) or binary (e.g. bcolz) files as standard, which can then be loaded by the workers later on.

I would image this functionality would be beneficial to many users and release them from the burden to setup, run and maintain a heavy HDFS cluster. In addition, I feel it should be relatively straightforward to implement too. What do you guys think of the idea?

**Comment by mrocklin** [comment]
Storing data on local nodes is definitely possible, and something that we've seen some groups do in the past.  They usually have to create some system to track which files got stored where and then be sure to launch dask workers in those locations when they want to retrieve that data.

The wide variety in how people deploy Dask clusters makes it a bit tricky to codify some practice like this in the codebase itself.  

Did you have a design or change in particular that you wanted to propose?

**Comment by mrocklin** [comment]
I think that you could probably do this today using a bit of code on the
client side and the Client.run command.  I don't think that this would need
to be integrated into a scheduler (which is good, because any change there
is pretty expensive and hard to get past review).  I'm curious, is there
anything stopping you from prototyping this sort of thing today outside of
dask as an additional module?  You might also want to look into
implementing this API:
http://docs.dask.org/en/latest/remote-data-services.html

**Comment by HiddenPython** [comment]
I can see it's possible to get worker - filelist mapping with Client.run, but it's not obvious to me that how to ask each worker to load different files and then combine them to a dataset? I guess combine can be done with dd.concat, but not sure about the load part.

**Comment by mrocklin** [comment]
You can specify specific workers for specific tasks with the workers= keyword.  See http://distributed.dask.org/en/latest/locality.html

In general I think that this is probably out of scope to be placed into the scheduler code itself.  It's not so much a question of latency as it is of code maintenance costs.  There haven't been enough people who care about fashioning their own distributed file system for Dask that we're likely to want to take this on internally.  

I think that the right path forward here is to use exisitng Dask APIs to build this out as an external package, and then if it proves useful to many people then we would consider rolling into the main codebase.  Closing for now.  Feel free to ask for it to be reopened if you feel strongly about this topic.
