### ISSUE TITLE
worker.memory_limit documentation

### ISSUE THREAD

**Issue by louisabraham** [dask/distributed#2296]
I think the [Worker documentation](http://distributed.dask.org/en/latest/worker.html#distributed.worker.Worker) is not very clear on the `memory_limit`.

    memory_limit: int, float, string

        Number of bytes of memory that this worker should use. Set to zero for no limit. Set to ‘auto’ for 60% of memory use. Use strings or numbers like 5GB or 5e9

The default argument is 'auto', which is not indicated in the doc.
https://github.com/dask/distributed/blob/ae964e70ce2965d9478dcc94abb90a8ff0a0f643/distributed/worker.py#L84-L92

Another problem is that I don't know where the 60% ratio comes from.
According to `parse_memory_limit`, it uses a fraction of the total memory proportional to the number of cores used.

https://github.com/dask/distributed/blob/ae964e70ce2965d9478dcc94abb90a8ff0a0f643/distributed/worker.py#L2880-L2893

**Comment by mrocklin** [comment]
Thanks for raising this issue @louisabraham .  What changes would you recommend?

**Comment by louisabraham** [comment]
I don't know where the error is: should the code allocate 60% of memory with option 'auto' or should we correct the wrong doc?

**Comment by quasiben** [comment]
I think this issue has been resolved in latest worker:
https://github.com/dask/distributed/blob/master/distributed/worker.py#L231

However, docs need to be rebuilt and deployed again for the change to be updated
