### ISSUE TITLE
import error in to_hdf for dataframes

### ISSUE THREAD

**Issue by Norhk** [dask/distributed#2309]
I am trying to store a distributed dataframe to hdf. Dies with:

    ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing
However,

    from pandas.io import pytables

works.

**Comment by mrocklin** [comment]
Perhaps not all of your workers have pytables installed?

You might want to run client.get_versions(check=True)

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if still a problem.
