### ISSUE TITLE
Is bandwidth meant to be hard-coded for work stealing?

### ISSUE THREAD

**Issue by nontrivial** [dask/distributed#2312]
The network bandwidth parameter is hard-coded in [stealing.py](https://github.com/dask/distributed/blob/master/distributed/stealing.py):
`BANDWIDTH = 100e6`
as opposed to in [scheduler.py](https://github.com/dask/distributed/blob/master/distributed/scheduler.py) where it is set by the config:
`BANDWIDTH = dask.config.get('distributed.scheduler.bandwidth')`
Is there any particular reason it is hard-coded for work-stealing?

**Comment by mrocklin** [comment]
Nope, probably just history.  Switching that to pull from the config would
be good if you're interested in submitting a small pull request.

**Comment by quasiben** [comment]
I believe this was fixed in https://github.com/dask/distributed/pull/2658 where the bandwidth is now pulled from dask.config .  Closing
