### ISSUE TITLE
KeyError: 'register-client'

### ISSUE THREAD

**Issue by suraj-deshmukh** [dask/distributed#2322]
I have two ec2 instances. dask-scheduler is running on one server and worker on another server. When i try below code from scheduler server,

    from distributed import Client
    c = Client('tcp://172.31.32.107:35386')

i get key error message on worker server as shown below.

    distributed.core - WARNING - No handler register-client found in Worker
    Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/distributed/core.py", line 327, in handle_comm
        handler = self.handlers[op]
    KeyError: 'register-client'

![worker](https://user-images.githubusercontent.com/14833831/47564244-eac9de80-d941-11e8-91cc-54b5d34e8e0b.png)

![scheduler](https://user-images.githubusercontent.com/14833831/47564256-f74e3700-d941-11e8-88f9-dba331cf23ff.png)

please check worker and scheduler screenshots for more information.
Note: I am very much new to dask and distributed framework.

**Comment by mrocklin** [comment]
It looks like a client is trying to connect to a worker process rather than
the scheduler

**Comment by suraj-deshmukh** [comment]
yes it was my mistake. Thank you. I am closing the issue.
