### ISSUE TITLE
from dask.distributed import Client throws the error : NameError: name 'StopAsyncIteration' is not defined

### ISSUE THREAD

**Issue by samsonpaturi** [dask/distributed#2324]
I am trying to follow the example: http://matthewrocklin.com/blog/work/2017/03/28/dask-xgboost I installed the dask[complete]. I have an aws emr cluster with one master and 2 core nodes. I launch a Jupyter notebook off the master (after ssh-ing into it). After the installing the dask package (also uninstalled and force reinstalled multiple times), unable to import the Client method from dask.distributed. Get the following error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-bbc1745feb2a> in <module>()
----> 1 from dask.distributed import *

/usr/local/lib/python3.4/site-packages/dask/distributed.py in <module>()
      3 
      4 try:
----> 5     from distributed import *
      6 except ImportError:
      7     msg = ("Dask's distributed scheduler is not installed.\n\n"

/usr/local/lib/python3.4/site-packages/distributed/__init__.py in <module>()
      1 from __future__ import print_function, division, absolute_import
      2 
----> 3 from . import config
      4 from dask.config import config
      5 from .actor import Actor, ActorFuture

/usr/local/lib/python3.4/site-packages/distributed/config.py in <module>()
      9 import yaml
     10 
---> 11 from .compatibility import logging_names
     12 
     13 config = dask.config.config

/usr/local/lib/python3.4/site-packages/distributed/compatibility.py in <module>()
     76     ConnectionRefusedError = ConnectionRefusedError
     77     FileExistsError = FileExistsError
---> 78     StopAsyncIteration = StopAsyncIteration
     79 
     80     def isqueue(o):

NameError: name 'StopAsyncIteration' is not defined

Also verified that dask-scheduler is running 
[hadoop@ip-10-192-33-210 ~]$ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://10.192.33.210:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-kiR9SY
distributed.scheduler - INFO - -----------------------------------------------

**Comment by mrocklin** [comment]
Python 3.4 is not supported.  I recommend updating to at least 3.5 or
downgrading to 2.7

**Comment by samsonpaturi** [comment]
Yup! I downgraded to 2.7 and its working. General usage question : is dask able to accept pandas objects (lists, series, sets etc)? I saw that it does not have problems with lists and series but there are some set operations that throw the error: Not implemented ...

**Comment by mrocklin** [comment]
yes
