### ISSUE TITLE
Bokeh 404, no errors

### ISSUE THREAD

**Issue by heartburn-jackson** [dask/distributed#2338]
Hi, I recently installed distributed from the conda-forge project (I'm on distributed 1.23.3, bokeh 0.13.0, RHEL 7.5), but am having some issues displaying the bokeh dashboard. Dask appears to start up with no issues/errors, but I'm seeing a 404 when trying to connect to the bokeh server:
![image](https://user-images.githubusercontent.com/44812132/48078364-e5289000-e1ae-11e8-853f-9ab8efa51fa9.png)

![image](https://user-images.githubusercontent.com/44812132/48078847-cd054080-e1af-11e8-8486-fd14f2643d36.png)

![image](https://user-images.githubusercontent.com/44812132/48078860-d393b800-e1af-11e8-9492-d234b7838ec5.png)

I also ran a few tests to make sure my environment is set up correctly. I was able to bokeh serve the sliders.py script at my-ip:8787 and can connect to this with no issues from my local pc, so it doesn't look like I'm running into bokeh or firewall issues:
![image](https://user-images.githubusercontent.com/44812132/48078265-ad214d00-e1ae-11e8-9dbf-1182f2bcace2.png)

I also set the DASK_CONFIG env variable to ~/.config/dask/ to force this config file to be used, and specified my-ip:8787/status as the dashboard link, but still no luck. Has anyone else encountered this issue?

**Comment by jbusecke** [comment]
I am having the same issue on a system running the following versions:
```
dask                      0.20.0                     py_0    conda-forge
dask-core                 0.20.0                     py_0    conda-forge
dask-jobqueue             0.4.1                      py_0    conda-forge
bokeh                     1.0.1                 py36_1000    conda-forge
```
On another cluster I am having no problems with the dashboard using these versions:
```
dask                      0.19.0                     py_0    conda-forge
dask-core                 0.19.0                     py_0    conda-forge
dask-jobqueue             0.3.0                      py_0    conda-forge
bokeh                     0.13.0                   py36_0    conda-forge
```
So could there be an issue with the recent version of dask or bokeh?

**Comment by mrocklin** [comment]
I'm not yet able to reproduce this locally.  I recommend producing a
minimal conda environment file that reproduces the failure.

**Comment by mikewheel** [comment]
I experienced the same issue on the following versions:
`dask                      0.20.0                   py36_0
dask-core                 0.20.0                   py36_0
distributed               1.24.0                   py36_0
bokeh                     0.13.0                   py36_0`

It appears that the top-level route 'localhost:8787' is no longer available for some reason.  When I navigate to 'localhost:8787/status' however I am able to see the dashboard and navigate to the other pages from there. I think it could just be that the bokeh menu page is gone for some reason, not that the entire dashboard is broken.

**Comment by mrocklin** [comment]
Ah yes, that's true

**Comment by mrocklin** [comment]
https://github.com/dask/distributed/issues/2359
