### ISSUE TITLE
Clean client history/memory without restarting the client

### ISSUE THREAD

**Issue by lanougue** [dask/distributed#2340]
Looking to #2328, is there a way to clean (wipe) client history without using client.restart() ?
With many workers (280 in my case) I always get a timeout error from workers when calling client.restart()
It also takes a (very) long time to initiate all workers so it would be nice to be able to avoid it.

Thus, it could be very useful if there was a way to clean the informations stored by the client without restarting it. At least a workaround ?

**Comment by mrocklin** [comment]
I don't know of a way, but I encourage you to look into how it could be done

**Comment by lanougue** [comment]
Not so easy to look into, but I'll give a try.
After some other tests it seems that even doing client.restart() do not clean client and/or scheduler "history".
Do you know where "history" is stored in the client and/or the scheduler object ?

Any chance that this issue is be linked to #1866 ?

**Comment by mrocklin** [comment]
I guess it depends on what you mean by "history"

**Comment by lanougue** [comment]
After doing some calculation and erasing all variables that contains the results, the memory used by the process running the client, do not come back to its initial level. Closing totally the client and restarting a new client make the memory come back to its inital level. I thus suspect that some information (that I call "history") is strored in some way by the client and/or the scheduler. 
For instance, in #2253 you mentioned that some Bokeh task stream is kept available even after restarting the client.

So, I'm looking a way to make the client/scheduler coming back to the initial stage (at least in terms of used memory) without having to totally kill the client and restart a new one.

**Comment by mrocklin** [comment]
There is certainly plenty of state in both, but there aren't many
particularly long unbounded historical data structures.  Those that do
exist hold small amounts of data (like log messages).  I don't think that
they are likely candidates to identify memory leaks.

**Comment by mrocklin** [comment]
But of course I could be wrong and encourage you to investigate things here.

**Comment by lanougue** [comment]
I will look into that but I wonder if this little amounts of data can not become huge when having large number of workers.
On the HPC I have, I usually use 560 workers (20 nodes with 28 cpus/process each). Only starting the workers takes more than 10 minutes... I set up the timeout limit to 15 minutes in order to have the first worker still running when the last one is ready.

**Comment by lanougue** [comment]
Any idea where these logs messages are stored ?

**Comment by mrocklin** [comment]
I recommend looking at scheduler.py and grepping for `self.*log`

The ten minute startup time sounds like it's probably something else.  My
first guess would be a backed up queue or a file system bogged down by
Python imports, but that's another issue, and my guess is that it's
unrelated to Dask.  You might consider contacting your system
administrators.

**Comment by lanougue** [comment]
Thanks a lot,
I will report back later on both issues...

**Comment by lanougue** [comment]
I finally found that my problem of memory is a hardware problem on the HPC I use. I close this issue for now.
