### ISSUE TITLE
Build Comm for ucx-py

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2344]
The [ucx-py](https://github.com/Akshay-Venkatesh/ucx-py) library provides Python bindings for the [openucx](http://www.openucx.org/) library, which wraps around lower level high performance networking solutions like Infiniband and others.

There appears to be an asyncio compatible implemenation in ucx-py in development branches.  [Here is an example](https://github.com/Akshay-Venkatesh/ucx-py/blob/listen-accept-future-cleanup/tests/test-duality.py).  It would be interesting to implement the Dask Comm API on top of this interface, both as a possible future high-performance networking solution for Dask, and to help drive development upstream in ucx-py.  

On the Dask side this is motivated by a few things:

1.  We can possibly drastically reduce our latency.  Early ucxpy benchmarks show 20us inter-node latencies on nice networks.  We currently operate at a few milliseconds (though some of this is serialization, etc..)
2.  We can possibly offload socket handling from Python.  Dask stress benchmarks show that we can spend a lot of time in Python's `socket.send`.  Ideally we can offload this to ucxpy running in another native thread.  
3.  UCX can also handle GPU-GPU direct communications, though I would recommend that we handle that only after we get something basic working

For someone looking to solve this problem I recommend looking at the following resources:

1.  The [Communications documentation](https://distributed.readthedocs.io/en/latest/communications.html)
2.  [Current implementations](https://github.com/dask/distributed/tree/master/distributed/comm), notably [TCP/TLS](https://github.com/dask/distributed/blob/master/distributed/comm/tcp.py) and [inproc](https://github.com/dask/distributed/blob/master/distributed/comm/inproc.py) (uses Tornado queues)
3. An abandoned [PR implementing comms for asyncio](https://github.com/dask/distributed/pull/2165)

From an API perspective we would want to be able to do the following:

    dask-scheduler --host ucx://localhost
    Scheduler started at ucx://localhost

    >>> client = Client('ucx://localhost')

ucx-py is experimental and undergoing pretty heavy churn.  My guess is that the work proposed in this issue would live in a development branch for a while until ucx-py stabilized a bit.  Starting this early though will probably be important in order to get ucx-py to stable point.

cc @TomAugspurger @Akshay-Venkatesh

**Comment by jhamman** [comment]
I get a 404 on https://github.com/Akshay-Venkatesh/ucx-py. Is this a private repo?

**Comment by mrocklin** [comment]
Hrm, could be.  My apologies to @Akshay-Venkatesh if so .  Akshay, please let me know if I should delete this issue from history.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin It's private at the moment. I think you can keep the issue. Let me get back to you whether we plan to keep the repo private.

**Comment by quasiben** [comment]
@mrocklin I think we can close this issue

**Comment by mrocklin** [comment]
Thanks @quasiben
