### ISSUE TITLE
Feature request: Private cluster using TLS client authentication

### ISSUE THREAD

**Issue by rzuidhof** [dask/distributed#2347]
Would it be possible to limit access to a certain Dask TLS cluster to a single client certificate?

Motivation: In the case where each user has a client certificate created by the same CA there is no user separation possible because each user can connect to any Dask cluster. 

The workaround is to use a separate CA per user which is currently not possible for Dask on Yarn.

**Comment by jcrist** [comment]
> Would it be possible to limit access to a certain Dask TLS cluster to a single client certificate?

Yes, but currently you'd have to ensure they don't share the same CA (as you mentioned above). Right now I'd handle this by using the `cryptography` library to create temporary self-signed certificate/key pairs to use every time you create a new cluster (see https://cryptography.io/en/latest/x509/tutorial/#creating-a-self-signed-certificate). These are cheap to create, and as long as their distribution is secure there should be no security risk. This is how skein (the library that backs dask-yarn) secures its communication.

> The workaround is to use a separate CA per user which is currently not possible for Dask on Yarn.

I don't understand this statement, why is this not currently possible? Do you mean that tls configuration is not exposed in `dask-yarn`?

**Comment by rzuidhof** [comment]
It is indeed related to the configuration options on Dask Yarn worker nodes.

**Comment by mrocklin** [comment]
Checking in here.  Was there any conclusion as to what should be done?

**Comment by rzuidhof** [comment]
My request was based on a situation where each user would received a pre-generated set of certificates issued by a central CA. But since there is a workaround by generating a CA for each user don't waste your precious development time on this feature request. Matthew's idea is even better, Dask clusters are ephemeral so why not automatically generate a set of certificates each time a cluster is created and TLS is enabled, or just the first time a user creates a cluster.
