### ISSUE TITLE
Support different usernames when starting an SSH cluster

### ISSUE THREAD

**Issue by suvayu** [dask/distributed#2350]
I wanted to start an SSH cluster where my username is not same on all the nodes.  It would be great if this was supported.  The most obvious way to configure this would be to allow specifying hosts as `user@hostname`, either on the command line, or the hosts file.

**Comment by mrocklin** [comment]
Seems reasonable to me.  Is this something that you would like to work on?

**Comment by suvayu** [comment]
Sure!  With some guidance of course :)
