### ISSUE TITLE
Multiple asynchronous jobs at the same time cause issues

### ISSUE THREAD

**Issue by OliverHofkens** [dask/distributed#2354]
I'm trying to use Dask in an asynchronous context, preferably with asyncio. I'm pretty new to both Dask and asyncio so forgive me if I made an obvious mistake. My first attempt uses the `AioClient` and everything gets stuck in some sort of deadlock:

Minimal reproducible example with `AioClient`:
```python
import asyncio
import uuid

from distributed.asyncio import AioClient


def main():
    asyncio.run(schedule_some_tasks(3))


async def schedule_some_tasks(n_tasks: int):
    tasks = []
    for _ in range(n_tasks):
        key = f'result{str(uuid.uuid4())}'
        graph = {key: (sum, (1, 1))}

        task = asyncio.create_task(schedule_task(graph, key))
        tasks.append(task)

    results = await asyncio.gather(*tasks)
    return results


async def schedule_task(graph: dict, key: str):
    async with AioClient('localhost:8786') as c:
        res = await c.get(graph, [key])

    return res


if __name__ == "__main__":
    main()
```

Executing this script hangs forever. Hitting `Ctrl-C` shows a trace as follows:

``` 
File "distributed/asyncio.py", line 25, in convert
    return to_asyncio_future(fn(*args, **kwargs))
  File "distributed/client.py", line 665, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "distributed/utils.py", line 275, in sync
    e.wait(10)
  File "python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
```

I read the discussions about `AioClient` possibly being deprecated now that Tornado uses asyncio. So I tried the script above, replacing the `AioClient` with `Client(..., asynchronous=True)`. In that case, all tasks cancel at once (`concurrent.futures._base.CancelledError
` without further info).

Any ideas?

**Comment by mrocklin** [comment]
@OliverHofkens first, why are you trying to use dask with asyncio?  What actual problem are you trying to solve?

**Comment by OliverHofkens** [comment]
@mrocklin Long story short: I'm building a job queue that schedules work on a Dask cluster. So messages representing all kinds of job graphs enter the queue from different sources, and a listener parses incoming messages and schedules them as graphs on the cluster (trough the `Client.get()` API). 
I'm trying to use `asyncio` because I'd like to submit graphs asynchronously, e.g. a long-running job (on the dask side) should not block the message handling.

**Comment by mrocklin** [comment]
You may not need asyncio for this.
http://docs.dask.org/en/latest/futures.html

**Comment by OliverHofkens** [comment]
The futures work like a charm, thanks for helping out!
