### ISSUE TITLE
What is the correct way to ensure that the master/worker would never fail?

### ISSUE THREAD

**Issue by suraj-deshmukh** [dask/distributed#2370]
This is not an issue but rather a open question. I have written an application to crawl hundreds of websites parallelly  using Scrapy spider. I have a master slave distributed system on aws. Everything works superfine and till date i did not encountered any failure of workers ec2 instances and master machine. 

But I am wondering what could be the possible causes of failures of master node as well as worker nodes and what preventive measures should be applied in order to ensure that master or worker node would never fail while computation.

**Comment by mrocklin** [comment]
Nodes can fail.  Ideally you would make sure that your scheduler process is
on a node that is less likely to go down, but placing workers on cheaper
spot instances is fine.

If the node hosting scheduler process goes down then you would want to
bring up that scheduler process somewhere else and then resubmit work.
Typically people deploy Dask with resource managers like Kubernetes or Yarn
to ensure that a scheduler continues to live somewhere.  This doesn't stop
you from having to resubmit work though.
