### ISSUE TITLE
Distributed statistical profiler in web ui not showing profiling information

### ISSUE THREAD

**Issue by PGryllos** [dask/distributed#2380]
I am trying to understand why when trying to read multiple relatively large parquet files (~500mb) the execution fails, usually with OutOfMemory error. 

I have a large dataset consisting of ~100 parquet files that I am trying to process in a relatively large machine (70GB ram, 36 cores); when trying to read multiple files the total bytes stored exceeds the total memory of my machine and the whole computation fails; if I try to load smaller part of the files the workers get killed because at some point they exceed the memory threshold; regardless of what combinations of memory limits, number of workers  and thresholds I have tried; 

So I have the suspicion that somewhere there is a memory leakage; Trying to use the profiler on the webui though doesn't give any results;I see nothing on the actual profiling dashboard. The activity over time is working but no information plotted on the profiling dashboard. Do you have any idea what may be wrong? (potentially missing some package?) or do you have any other suggestions for debugging? 

Any help would be extremely appreciated :)

**Comment by PGryllos** [comment]
It was my mistake, the information was there but all contained in one green box

**Comment by mrocklin** [comment]
:)
