### ISSUE TITLE
sizeof not working for dicts, iterables or class instances, breaking shuffle optimization

### ISSUE THREAD

**Issue by Zahlii** [dask/distributed#2389]
Hello,

Dask distributed does not calculate the correct size for dictionaries and always returns 240 bytes for any dictionary. I guess this is the problem why in my use case (functions relying on large dicts), the scheduler is unable to optimize the correct shuffling of data to workers.

Example:
https://repl.it/repls/GlassFinancialDatabases

**Comment by mdwint** [comment]
I was facing the same issue. After checking the Dask codebase, I found you can register a custom sizeof handler as follows: 

```python
from dask.sizeof import getsizeof, sizeof

@sizeof.register(dict)
def sizeof_python_dict(d):
    return (
        getsizeof(d) + sum(map(getsizeof, d.keys())) + sum(map(getsizeof, d.values()))
    )
```

**Comment by mrocklin** [comment]
There is a non-trivial overhead to traverse into all dictionaries/tuples/lists, but maybe it is safe to do this for containers that are small, like length 5 or less?

**Comment by mrocklin** [comment]
Closed by https://github.com/dask/dask/pull/5578
