### ISSUE TITLE
max_map_len problem in the latest `msgpack` library (version==0.6.0)

### ISSUE THREAD

**Issue by ZhuozhaoLi** [dask/distributed#2392]
The default `max_map_len` in the latest `msgpack` (version 0.6.0) is 32768, which limits the length of input in `client.map()` to this value. I need to roll back to `msgpack==0.5.6` to solve this problem

`File "/lib/python3.6/site-packages/distributed/protocol/core.py", line 197, in loads_msgpack
    return msgpack.loads(payload, use_list=False, **msgpack_raw_false)
  File "msgpack/_unpacker.pyx", line 187, in msgpack._cmsgpack.unpackb
ValueError: 40000 exceeds max_map_len(32768)`

**Comment by mrocklin** [comment]
Interesting.  I have not seen this before.  I'm curious, do you know what
caused this?  Do you have any recommendations on how to resolve it?

**Comment by ZhuozhaoLi** [comment]
> Interesting. I have not seen this before. I'm curious, do you know what caused this? Do you have any recommendations on how to resolve it?

Like I said, it was caused by the default value change of `max_map_len` in the latest version (0.6.0) of `msgpack`. See here: https://github.com/msgpack/msgpack-python/blob/b1d658e7a0aed4e723f9b6b238cc9f2f876e54d7/msgpack/fallback.py#L256.
I think you can reproduce this error if you update `msgpack` to 0.6.0 and try a `client.map` with more than 32768 inputs.

However, in `msgpack=0.5.6`, the value was `2**31-1` -- it is sufficiently large. So I think a quick way is to put `msgpack==0.5.6` in your `requirement.txt`?
