### ISSUE TITLE
Automate setup of distributed from cluster scheduler nodes file

### ISSUE THREAD

**Issue by ijstokes** [dask/distributed#24]
We had a request today (and in fact I've heard this from a few other people) to have a way to support the automatic generation of configuration files for Python parallel computing frameworks based on the "nodes" files produced and dropped into the "node 0" (sometimes called "rank 0") master node when scheduled through a batch scheduler.

It seems like this is the kind of thing that `magpie` might do: https://github.com/chu11/magpie

It would be nice to have that capability for our distributed computing libraries.

**Comment by mrocklin** [comment]
Hi @ijstokes sorry for letting this slip through.  If I understand you correctly you're asking for configuration files that help to deploy on various grid-computing systems like SGE or Condor.  Is that correct?  I'm not sure I understand the idea of a nodes file.

Generally speaking I agree that deployment of distributed is likely to be a major bottleneck to adoption and needs to be addressed well.

**Comment by mrocklin** [comment]
Closing soon if no response.

**Comment by minrk** [comment]
I expect this is referring to something like the [mpi hostfile](https://www.open-mpi.org/faq/?category=running#mpirun-hostfile). Such a file for distributed might look something like:

```ini
host0.name scheduler
host1.name workers=5
host2.name workers=3
```

which is passed to a script that launches the scheduler on host0, five workers on host1, and 3 on host2.

**Comment by mrocklin** [comment]
Such a thing already exists (but untested/documented) for the `dcluster` executable.

**Comment by minrk** [comment]
Then I'd guess you can close (or better yet, close the issue with a docs PR).
