### ISSUE TITLE
openssl 1.1.1 requires RSA keys be >= 2048 bits.

### ISSUE THREAD

**Issue by detrout** [dask/distributed#2405]
HI, I was (finally) trying to update the Debian package and the tests failed because the test keys are now too short.

```
==================================== ERRORS ====================================
__________________ ERROR collecting comm/tests/test_comms.py ___________________
/usr/lib/python3/dist-packages/distributed/comm/tests/test_comms.py:59: in <module>
    tls_kwargs = dict(listen_args={'ssl_context': get_server_ssl_context()},
/usr/lib/python3/dist-packages/distributed/utils_test.py:1367: in get_server_ssl_context
    ctx.load_cert_chain(get_cert(certfile), get_cert(keyfile))
E   ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3486)
=========================== short test summary info ======================
```

The relevant chunk from the Debian news is:

```
  Following various security recommendations, the default minimum TLS version
  has been changed from TLSv1 to TLSv1.2. Mozilla, Microsoft, Google and Apple
  plan to do same around March 2020.

  The default security level for TLS connections has also be increased from
  level 1 to level 2. This moves from the 80 bit security level to the 112 bit
  security level and will require 2048 bit or larger RSA and DHE keys, 224 bit
  or larger ECC keys, and SHA-2.

  The system wide settings can be changed in /etc/ssl/openssl.cnf. Applications
  might also have a way to override the defaults.
```

I'm assuming that'll means problems with the small keys will start showing up elsewhere in a bit.

**Comment by mrocklin** [comment]
Hi @detrout .  Thank you as always for handling the debian packaging. 

These certs are just used for testing.  We're not using them for any kind of secure operation (or any operation at all really).  This may not be an operational bug.

That being said, it might be easier to fix on our end rather than have Debian silence warnings.  @mariusvniekerk is this an easy thing for someone to do?  (My knowledge of certs is low).

**Comment by detrout** [comment]
My temptation was just to regenerate the certs with a larger keysize to make openssl more cooperative.

If the certs are just testing self signed certs with nothing special going on and the "private" key included in the repository I could probably even generate new ones.

I was just hoping you had a script to make them.

**Comment by mrocklin** [comment]
Regenerating them sounds fine to me.  I don't personally have such a
script, but would be happy if someone else were to do
this.  @mariusvniekerk seems the most likely to handle this today, but I
know that he's also somewhat busy.

**Comment by detrout** [comment]
Pull request generated.

Would you prefer one issue per failure or one issue listing them all?

Also best wishes at your new position.
