### ISSUE TITLE
client jobs submitted to LocalCluster(processes=True) only run on one process.

### ISSUE THREAD

**Issue by goraj** [dask/distributed#2406]
The following snippet returns the same pid for all four jobs. If this is desired behavior how can I make sure that all jobs are ran on different processes and GILs?

I run into issues when using scikit-learn and LocalCluster as shown here: [https://github.com/scikit-learn/scikit-learn/issues/12751](https://github.com/scikit-learn/scikit-learn/issues/12751)
```
In [3]: dask.__version__
Out[3]: '1.0.0'

In [4]: import distributed

In [5]: distributed.__version__
Out[5]: '1.25.0'
```

```
from dask.distributed import Client
from dask_jobqueue import SGECluster
from distributed.deploy.local import LocalCluster

import time
import os

def do_process():
    time.sleep(10)
    return os.getpid()


if __name__ == '__main__': 
    n_process = 4
    cluster = LocalCluster(processes=True, 
                           silence_logs=False,
                           threads_per_worker=1,
                           n_workers=n_process)
        
    with Client(cluster) as client:
        pool = []    
        for x in range(n_process):
            print(x)
            pool.append(client.submit(do_process))
    
        result = client.gather(pool)
        print(f'result: {result}')
        import IPython
        IPython.embed()
```

**Comment by goraj** [comment]
@mrocklin thank you, that did the trick. 

On a side-note:
When using joblib in Dask workers (running as processes) it seems like that their LokyBackend.effective_n_jobs will detect Dask worker processes incorrectly as nested loops due to ```isinstance(threading.current_thread(), threading._MainThread)```.

Would it be enough to check for 'DASK_PARENT' in os.enviroment as a fix? Maybe you can comment on that.

**Comment by mrocklin** [comment]
I'm not sure I understand your comment about an environment variable or the Loky issue (I'm not deeply familiar with Joblib internals).  It might be worth asking a joblib dev?

**Comment by goraj** [comment]
Thank you @mrocklin. I will, issue can be closed then!
