### ISSUE TITLE
After freezing with PyInstaller, app that uses dask.distributed.Client crashes

### ISSUE THREAD

**Issue by janroden** [dask/distributed#2416]
Hi, 
I'm trying to freeze a Python app that uses Dask.distributed with PyInstaller.

The not frozen version of the app runs fine. 
But the frozen version of the app crashes, showing the following error:
```
13:07:47,039 - STDERR - ERROR - Exception ignored in:
13:07:47,040 - STDERR - ERROR - <object repr() failed>
13:07:47,040 - STDERR - ERROR - Traceback (most recent call last):
13:07:47,040 - STDERR - ERROR -   File "C:\Users\...\dependencies_windows\Anaconda3\lib\site-packages\distributed\deploy\local.py", line 340, in __del__
13:07:47,041 - STDERR - ERROR - self.close()
13:07:47,041 - STDERR - ERROR -   File "C:\Users\...\dependencies_windows\Anaconda3\lib\site-packages\distributed\deploy\local.py", line 280, in close
13:07:47,041 - STDERR - ERROR - self.scheduler.clear_task_state()
13:07:47,041 - STDERR - ERROR - AttributeError
13:07:47,041 - STDERR - ERROR - :
13:07:47,041 - STDERR - ERROR - 'LocalCluster' object has no attribute 'scheduler'
```
The part of the app that uses Dask.distributed is of the form:
```python
from dask.distributed import Client

client = Client(processes=False)

futures = []
for i in range(10): 
    other_futures = [client.submit( crunch_1, some_input[i, j]) for j in range(10)]
    futures.append( client.submit( crunch_2, other_futures))

results = client.gather(futures)
```
Platform: Windows 10, 64-bit 
Python: 3.6.7, 64-bit (Anaconda)
Dask.distributed: 1.25.0
PyInstaller: 3.4.dev0+ab8fd9753

I would appreciate any hints on how to make this work with PyInstaller. Thank you!

**Comment by mrocklin** [comment]
Unfortunately I'm not familiar with PyInstaller.  It might be wise for you
to try to get someone familiar with PyInstaller to help you with your
problem.

**Comment by janroden** [comment]
Ok. Thanks a lot for the fast response. I'll ask at the PyInstaller GitHub repo.

Thanks
