### ISSUE TITLE
map and fire_and_forget

### ISSUE THREAD

**Issue by sebhahn** [dask/distributed#2424]
Is it possible to use `fire_and_forget` for `map` instead of `submit`? 

In my particular case I'd like to map a list of arguments to the same function, but nothing is returned since each task writes its own file. I also noticed that memory consumption is quite high even though I delete all variables in my function. Does it help to use `future.cancel()` to free up memory in an `as_completed` loop?

**Comment by mrocklin** [comment]
Yes, you can use `fire_and_forget` on any list of Future objects.  It doesn't matter if these came from map or submit.  If you're running into a particular issue where this isn't being respected then a minimal fail case would be helpful.

> I also noticed that memory consumption is quite high even though I delete all variables in my function. Does it help to use future.cancel() to free up memory in an as_completed loop?

As mentioned in http://distributed.dask.org/en/latest/memory.html dask holds onto data if there are active futures pointing to that data.  You may want to do the following:

```python
futures = client.map(...)
seq = as_completed(futures)
del futures # <<-- note that otherwise you still have a list of futures that will stay in memory
for future in seq:
    ...
```

**Comment by sebhahn** [comment]
Ok thanks I'll test
