### ISSUE TITLE
[ worker node1 ] : /usr/bin/python2: No module named distributed.cli

### ISSUE THREAD

**Issue by seraphzl** [dask/distributed#2439]
Hi,
Error when using dask-ssh. Dask have been installed on 3 nodes with pip. The screen output is as follows:

[root@Centos7 dask]# dask-ssh node0 node1 node2

---------------------------------------------------------------
                 Dask.distributed v1.25.1

Worker nodes:
  0: node0
  1: node1
  2: node2

scheduler node: node0:8786
---------------------------------------------------------------

[ worker node2 ] : /usr/bin/python2 -m distributed.cli.dask_worker node0:8786 --nthreads 0 --nprocs 1  --host node2 --memory-limit auto 
[ worker node1 ] : /usr/bin/python2 -m distributed.cli.dask_worker node0:8786 --nthreads 0 --nprocs 1  --host node1 --memory-limit auto 
[ scheduler node0:8786 ] : /usr/bin/python2 -m distributed.cli.dask_scheduler --port 8786
[ worker node0 ] : /usr/bin/python2 -m distributed.cli.dask_worker node0:8786 --nthreads 0 --nprocs 1  --host node0 --memory-limit auto 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/distributed/deploy/ssh.py", line 169, in async_ssh
    channel.send(b'\x03')  # Ctrl-C
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 767, in send
    return self._send(s, m)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1133, in _send
    raise socket.error('Socket is closed')
error: Socket is closed

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/distributed/deploy/ssh.py", line 169, in async_ssh
    channel.send(b'\x03')  # Ctrl-C
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 767, in send
    return self._send(s, m)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1133, in _send
    raise socket.error('Socket is closed')
error: Socket is closed

[ scheduler node0:8786 ] : distributed.scheduler - INFO - -----------------------------------------------
[ scheduler node0:8786 ] : distributed.scheduler - INFO - Clear task state
[ scheduler node0:8786 ] : distributed.scheduler - INFO -   Scheduler at:     tcp://10.0.86.13:8786
[ scheduler node0:8786 ] : distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-vpaoiP
[ scheduler node0:8786 ] : distributed.scheduler - INFO - -----------------------------------------------
[ scheduler node0:8786 ] : distributed.scheduler - INFO - Register tcp://10.0.86.13:43050
[ scheduler node0:8786 ] : distributed.scheduler - INFO - Starting worker compute stream, tcp://10.0.86.13:43050
[ scheduler node0:8786 ] : distributed.core - INFO - Starting established connection
[ worker node0 ] : distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.86.13:43610'
[ worker node0 ] : distributed.worker - INFO -       Start worker at:     tcp://10.0.86.13:43050
[ worker node0 ] : distributed.worker - INFO -          Listening to:     tcp://10.0.86.13:43050
[ worker node0 ] : distributed.worker - INFO -              nanny at:           10.0.86.13:43610
[ worker node0 ] : distributed.worker - INFO - Waiting to connect to:           tcp://node0:8786
[ worker node0 ] : distributed.worker - INFO - -------------------------------------------------
[ worker node0 ] : distributed.worker - INFO -               Threads:                          8
[ worker node0 ] : distributed.worker - INFO -                Memory:                    8.37 GB
[ worker node0 ] : distributed.worker - INFO -       Local Directory:        /root/worker-9tNAKi
[ worker node0 ] : distributed.worker - INFO - -------------------------------------------------
[ worker node0 ] : distributed.worker - INFO -         Registered to:           tcp://node0:8786
[ worker node0 ] : distributed.worker - INFO - -------------------------------------------------
[ worker node0 ] : distributed.core - INFO - Starting established connection
[ worker node1 ] : /usr/bin/python2: No module named distributed.cli
[ worker node1 ] : remote process exited with exit status 1
[ worker node2 ] : /usr/bin/python2: No module named distributed.cli
[ worker node2 ] : remote process exited with exit status 1

**Comment by mrocklin** [comment]
My guess is that you haven't installed the `distributed` library on those
nodes
