### ISSUE TITLE
dask-scheduler does not launch Bokeh

### ISSUE THREAD

**Issue by dirkpetersen** [dask/distributed#2443]
I am seeing this starting with distributed 1.21.8 and bokeh 1.0.1 but also with the very latest versions. Starting dask-scheduler will not start bokeh any more. We are using our own compiled Python 3.6.7 and install all packages via pip. I tested it with the latest Anaconda Python 3.7 and that works fine so it seems to be an issue with our Python install ..  

```
petersen@koshuf0:~$ dask-scheduler --port 12121 --bokeh-port 12122 --host $SLURMD_NODENAME --pid-file dask-scheduler.pid
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://172.30.1.100:12121
distributed.scheduler - INFO - Local Directory: /loc/scratch/27074823/scheduler-xu5904ps
distributed.scheduler - INFO - -----------------------------------------------
Connection to koshu-login closed by remote host.
```

below Scheduler at:  I should be seeing 

```
distributed.scheduler - INFO -       bokeh at:      172.30.1.100:12122
```

but it is not there and bokeh is not started, there are no errors in the log. I would be grateful for any hint . There does not seem to be a --verbose or --debug option for dask-scheduler ?

**Comment by mrocklin** [comment]
My first guess is that bokeh version 1.0.1 isn't compatible with your
version of distributed.  I encourage you to update to the latest release.

**Comment by mrocklin** [comment]
If bokeh can't be imported then there is no message.  See
distributed/cli/dask_scheduler.py

If bokeh can be imported, but the service fails to start, then we raise a
warning.  See distributed/scheduler.py::Scheduler.start_services

**Comment by dirkpetersen** [comment]
How about this ?

```
        #with ignoring(ImportError):
        try:
            from distributed.bokeh.scheduler import BokehScheduler
            services[('bokeh', bokeh_port)] = (BokehScheduler,
                                               {'prefix': bokeh_prefix})
            print(error.message)
        except ImportError as error:
            logger.info('bokeh import error: %s' % error)

```

will result in 

```
petersen@koshuf0:/home…es/distributed$ dask-scheduler --port 12121 --bokeh-port 21122 --show --host $SLURMD_NODENAME --pid-file dask-scheduler.pid
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - bokeh import error: libtiff.so.5: cannot open shared object file: No such file or directory
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://172.30.1.100:12121
distributed.scheduler - INFO - Local Directory: /loc/scratch/27074830/scheduler-ovibbh3q
distributed.scheduler - INFO - -----------------------------------------------

```
I can send a pull request

**Comment by mrocklin** [comment]
What if the user doesn't have bokeh installed?  Do they get a confusing
error message?

**Comment by dirkpetersen** [comment]
or better:

```
        try:
            import blablabla
            from distributed.bokeh.scheduler import BokehScheduler
            services[('bokeh', bokeh_port)] = (BokehScheduler,
                                               {'prefix': bokeh_prefix})
        except ImportError as error:
            if str(error).startswith('No module named'):
                logger.info('error: Bokeh is not installed')
            else:
                logger.info('bokeh import error: %s' % error)
```

```
dask-scheduler --port 12121 --bokeh-port 21122 --show --host $SLURMD_NODENAME --pid-file dask-scheduler.pid
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - error: Bokeh is not installed
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://172.30.1.100:12121
distributed.scheduler - INFO - Local Directory: /loc/scratch/27074830/scheduler-glqpzhog
distributed.scheduler - INFO - -----------------------------------------------

```

**Comment by mrocklin** [comment]
I suspect that even that message will confuse users who don't know what's
going on.  It contains the word "error" which is scary if you're coming at
the project for the first time.  A new user won't have any context for what
bokeh is or why their system is erring because of it.

**Comment by dirkpetersen** [comment]
Call it something like info : web console not loaded. I am working with new users all the time and the examples and hpc wrapper scripts we use print explicitly the url to  the web management interface . To my users this is a very integral and valuable part of dask and if it is not loaded dask is not functional as far is the user is concerned and we will get a ticket about it.  I agree that the term bokeh is confusing, perhaps use even different command options that clarify what it is for,eg —webui-port instead of —bokeh-port

**Comment by mrocklin** [comment]
A line like the following might be nice?

    distributed.scheduler - INFO - Web dashboard not loaded.  Unable to import bokeh

I also agree about removing the use of `bokeh` in the CLI options.  We would need to deprecate this smoothly if we do it.

**Comment by blazespinnaker** [comment]
I was getting this error - " Web dashboard not loaded.  Unable to import bokeh".   It's not clear from reading the documentation on how to get more information on what's causing this. I agree with the above that dask is impaired without the web dashboard as I don't know if or how my workers are being utilized properly.  Is there a verbose logging option I've missed?   

I was able to fix it by going python3 -m pip install "dask[complete]"  again.  I guess I must have ran something which clobbered a version of something.

**Comment by mrocklin** [comment]
Everything is fine.  If you want the dashboard (which is useful) then you'll have to install the additional library `bokeh` for visualization

    pip install bokeh

or

    conda install bokeh
