### ISSUE TITLE
Add Network send/recv to web UI plot

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#245]
It would be nice to see network activity over time.

We already capture this data in the same way we capture the CPU/Memory data that we already plot, so the job of figuring out how to move the data into the `ColumnDataSource` isn't hard.  What *is* tricky is that we don't have a percentage, but instead have actual MB/s bandwidth counts.  We would have to add a second Y-axis (this is doable) and think a bit about how best to set the axes.

This might be an interesting task for anyone looking to get into the Bokeh Web UI, notably @martindurant

**Comment by martindurant** [comment]
Typical is to plot the percentage from peak (on the same axis scale), but include a label/legend saying what the peak was. 
A second axes with transfer bandwidth, auto-scaled (to sensible boundaries), is totally doable too.
