### ISSUE TITLE
distributed==1.24.0 dask==0.20.0 crashes

### ISSUE THREAD

**Issue by psthiagu** [dask/distributed#2455]
I am trying to install PyBNF (python3.7) which uses the distributed package (1.24.0 dask==0.20.0).
It throws up an error message generated by the call to distributed. I am attaching the error message generated when I run python with:
import distributed
distributed.Client()
It will be great if you can help.
[dist_error.txt](https://github.com/dask/distributed/files/2743479/dist_error.txt)

Best,
Thiagu
psthiagu@gmail.com

**Comment by emitra17** [comment]
PyBNF developer here. I should add from our issue discussion that the user is trying to run distributed on ubuntu on windows10 (windows subsystem for linux).

**Comment by mrocklin** [comment]
It looks like there is some oddity with forkserver, which isn't too surprising given the Windows connection.

I recommend setting the multiprocessing context to "spawn", which should make Windows happier.  You can do this in Python code with the following lines

```python
import dask
dask.config.set({'distributed.worker.multiprocessing-method': 'spawn'})
```

Or by including the following value in a dask config file, probably living in `~/.config/dask/...`

```yaml
distributed:
  worker:
    multiprocessing-method: spawn
```

You can learn more about setting configuration at http://docs.dask.org/en/latest/configuration.html

**Comment by psthiagu** [comment]
Unfortunately neither fix works. But thanks for giving it a go.
I have contacted the WSL team. They are looking into it.

**Comment by mrocklin** [comment]
There are several other ways to create a Dask client/cluster.  For example you might ...

-  Use only the local scheduler
-  Use the local distributed scheduler, but with `processes=False`
-  Set up your cluster by hand with the `dask-scheduler` and `dask-worker` commands

I would be surprised if one of those options didn't work.

See http://docs.dask.org/en/latest/scheduling.html for more information about different schedulers

**Comment by psthiagu** [comment]
Will try them out, thanks.

**Comment by mrocklin** [comment]
Any update here?

**Comment by psthiagu** [comment]
Sorry. Should have closed this.   The Microsoft team couldn't help. I now
have dual boot system with Ubuntu and windows 10. Dask works fine under
Ubuntu.

**Comment by CJ-Wright** [comment]
xrefs: 
https://github.com/microsoft/WSL/issues/3935
https://github.com/microsoft/WSL/issues/3764
https://github.com/microsoft/WSL/issues/4604

**Comment by matthewgson** [comment]
> It looks like there is some oddity with forkserver, which isn't too surprising given the Windows connection.
> 
> I recommend setting the multiprocessing context to "spawn", which should make Windows happier. You can do this in Python code with the following lines
> 
> ```python
> import dask
> dask.config.set({'distributed.worker.multiprocessing-method': 'spawn'})
> ```
> 
> Or by including the following value in a dask config file, probably living in `~/.config/dask/...`
> 
> ```yaml
> distributed:
>   worker:
>     multiprocessing-method: spawn
> ```
> 
> You can learn more about setting configuration at http://docs.dask.org/en/latest/configuration.html

I was having the same issue with my windows workstation with WSL(ubuntu), and I confirm that this worked for me. However it generates some error messages like below:

```distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available```

**Comment by mrocklin** [comment]
We're moving towards making spawn the default in https://github.com/dask/distributed/pull/3461 so the default experience may become a bit smoother.

I don't have any particular information to give about the `protocol not available` message.  That seems concerning.  Perhaps TCP sockets in WSL don't support timeouts?
