### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by sdorgancs** [dask/distributed#2463]
I think there is an error in the documentation of Client:
http://distributed.dask.org/en/latest/client.html
Section Concurrent.futures
```python
>>> x.result()
11
```

should be
```python
>>> y.result()
11
```
Am I wrong?

**Comment by TomAugspurger** [comment]
I think the example is correct, but confusing.

`y = client.submit(inc, x)` is showing that we can submitting Futures as arguments to functions (`x` is a Future).

Then we move on to the "gathering results" section. Now both `x` and `y` are Futures.

```
>>> x = client.submit(inc, 10)
>>> x.result()
11

>>> y = client.submit(inc, x)
>>> y.result()
12
```

How about we re-arrange things to show things in this order

1. A basic `client.submit` and `client.map` with concrete arguments (`10`, `range(1000)`)

```python
>>> def inc(x):
        return x + 1

>>> x = client.submit(inc, 10)
>>> x
<Future - key: inc-e4853cffcc2f51909cdb69d16dacd1a5>

>>> L = client.map(inc, range(1000))
>>> L
[<Future - key: inc-e4853cffcc2f51909cdb69d16dacd1a5>,
 <Future - key: inc-...>,
 <Future - key: inc-...>,
 <Future - key: inc-...>, ...]
```

2. Gathering results

```
>>> x.result()
11

>>> client.gather(L)
[1, 2, 3, 4, 5, ...]
```

3. Using `Future`s as arguments

```python
>>> y = client.submit(inc, x)      # Submit on x, a Future
>>> total = client.submit(sum, L)  # Map on L, a list of Futures
>>> y.result()
12
```

Does that make sense?

**Comment by sdorgancs** [comment]
Perfectly, I read to fast and I miss the purpose of using a future as input. 
Thanks for you clear answer!

**Comment by arpit1997** [comment]
@TomAugspurger Can I make a PR for it?

**Comment by TomAugspurger** [comment]
That’d be great.

**Comment by TomAugspurger** [comment]
Yeah, I think that'd be great.
