### ISSUE TITLE
Dask divide by zero and import error

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#249]
I cloned and installed distributed from master (1.9.5) and when I try to `import distributed` it gives me the following error (it cannot import istask from dask):
`ImportError: cannot import name istask`

I tried reinstalling both dask and distributed, but it didn't work.

Also when I run dworker or dscheduler it gives me this warning:
```/usr/local/lib/python2.7/dist-packages/dask-0.8.2-py2.7.egg/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  or not np.allclose(np.divide(1, .5, dtype='i8'), 2)```

Do you have any idea what might be the cause? :-)
This error also appeared during dask installation with setuptools, do you think that it could be related?

```Exception in thread Thread-5 (most likely raised during interpreter shutdown):Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers  File "/usr/lib/python2.7/threading.py", line 763, in run
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 357, in _handle_tasks
Exception TypeError: TypeError("'NoneType' object does not support item deletion",)<type 'exceptions.TypeError'>: 'NoneType' object is not callable
 in <Finalize object, dead> ignored```

**Comment by mrocklin** [comment]
Hi @Kobzol can you say a bit more about how you installed distributed?  Normally if you install with any normal channel (pip, conda, setup.py) it will install dask for you.

**Comment by Kobzol** [comment]
I cloned distributed master branch using git and then ran `sudo python setup.py install`. I wanted the newest version, that's why I didn't use pip.

**Comment by mrocklin** [comment]
I recommend `pip install git+https://github.com/dask/{dask,distributed}.git --upgrade`

**Comment by mrocklin** [comment]
In either case it should be installing dask.  Can you verify that `from dask import istask` works?

**Comment by Kobzol** [comment]
I tried your suggestion and upgraded it from GitHub. `from dask import istask` works, but it still gives me this warning when importing `distributed`: ```/usr/local/lib/python2.7/dist-packages/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  or not np.allclose(np.divide(1, .5, dtype='i8'), 2)```

**Comment by mrocklin** [comment]
This error is coming from numpy.  Try updating numpy

**Comment by Kobzol** [comment]
Thank you, that did the trick :-) I installed it on a fresh system, so there were old versions of Python libraries. Sorry for bothering you.

**Comment by mrocklin** [comment]
No worries.  It's a bit tricky.  It would be nice if we could depend on newer versions of NumPy, but some of our downstream dependencies are still fairly conservative about newer versions.  Hence the annoying warnings.  We could do a better job of reraising those warnings to point people in the right direction.
