### ISSUE TITLE
pickle5 support

### ISSUE THREAD

**Issue by tjb900** [dask/distributed#2495]
Hi!  Not really an issue, just a query with the aim of avoiding duplicated work.  Our use case for distributed involves keys whose values are often lists of or dicts of (lists of, or dicts of, etc) numpy arrays, and unfortunately the current serialization scheme - while fantastic for numpy arrays not embedded in other objects - does not handle these nested structures particularly well.

Now that numpy 1.16 is out, the pickle5 protocol, and its backport (https://github.com/pitrou/pickle5-backport) would seem to provide a very elegant solution to efficiently communicating these kinds of structures by passing the large data arrays as out-of-band data that doesn't need to be embedded into the pickle bytestream.

Is work already underway somewhere on some remote branch to integrate this into distributed?  If not, would such a PR be welcome? or should we wait for more experienced hands to tackle it?

Thanks in advance!

**Comment by mrocklin** [comment]
No work is currently underway.  I have no particular objection to pickle5
support.  In principle it sounds like a nice idea.

**Comment by mrocklin** [comment]
Fine to keep it open

**Comment by jakirkham** [comment]
Reopening as I'd like us to track this as part of extending the work already done in PR ( https://github.com/dask/distributed/pull/3784 ) to other Python versions.

**Comment by jakirkham** [comment]
Before adding this to Dask we would need pickle5 support in cloudpickle. A fair bit of work has been done in PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ) to handle that. Much thanks to @pierreglaser for making that possible!

**Comment by jacobtomlinson** [comment]
@jakirkham is this now resolved with #3784?

**Comment by jakirkham** [comment]
No this is something different. It would require PR ( https://github.com/dask/distributed/pull/3849 ) and PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ) (plus a release of cloudpickle) to resolve.

**Comment by jakirkham** [comment]
Alright I think PR ( https://github.com/dask/distributed/pull/3849 ) should be ready for review. Please let me know what you think 🙂
