### ISSUE TITLE
Do not default to cwd for dask-worker-space

### ISSUE THREAD

**Issue by samcmill** [dask/distributed#2496]
Should not assume that cwd is writable.  For instance, when running in read-only containers such as Singularity.

The default value should be a directory specifically purposed for temporary files.  `/tmp`, `$TMPDIR`, or even better, something like `tempfile.mkdtemp`.

Related: https://github.com/LiberTEM/LiberTEM/issues/80

**Comment by jakirkham** [comment]
One can override this by running `dask.config.set("temporary-directory", "<path>")` or changing [this line]( https://github.com/dask/dask/blob/c743feab0a92d20e248d32e97dcfbe567f4dfbd0/dask/dask.yaml#L1 ) in `~/.config/dask/dask.yaml`.

**Comment by jakirkham** [comment]
Should add unfortunately many systems use [`tmpfs`]( https://en.wikipedia.org/wiki/Tmpfs ) for things like `/tmp`. So this winds up being in-memory data as to actually being on disk. Given this, when Dask tries to spill in-memory data to disk it will write to this `tmpfs` backed storage, which is still in-memory meaning it not only fails to free up memory, but may use up additional memory causing workers to crash.

**Comment by jakirkham** [comment]
It seems like documentation on `"temporary-directory"` is a bit spotty (despite it being used everywhere). Given this is a common configuration need (even outside of this use case), maybe just having some docs on this parameter would be useful.

**Comment by jrbourbeau** [comment]
https://docs.dask.org/en/latest/setup/hpc.html#local-storage is the only place in the docs that I could find where `temporary-directory` is discussed. Any improvements in documentation are certainly welcome. Do you have any suggestions as to where this documentation should be added?

Perhaps we update the `local_directory` docstring parameter to mention `temporary-directory`:

https://github.com/dask/distributed/blob/dedcb1350e6106a21ddcdad1edaa94b346b3e9d8/distributed/worker.py#L491

**Comment by jakirkham** [comment]
Nice find! Not sure why I didn't see that when searching.

It might make sense to have a general config page. This could overview things like `temporary-directory`, which are useful in a variety of contexts.

**Comment by jrbourbeau** [comment]
There's an existing issue for that (xref https://github.com/dask/dask/issues/4286) which I believe coincidentally got picked up this week and is currently in progress

**Comment by jakirkham** [comment]
Great! In that case, should we close this out and track there?

**Comment by jrbourbeau** [comment]
Yeah, sounds good
