### ISSUE TITLE
Bokeh Dashboard - Task Stream stops working after an extended period of time

### ISSUE THREAD

**Issue by birdsarah** [dask/distributed#2501]
This has happened to me a few times.

I have a 30 worker cluster, it's been up for a while doing lots of different things. At some point, the task stream plot just gives up and doesn't render anything.  You can see in the screenshot below that the other plots are ticking along nicely.

![screenshot from 2019-02-01 18-28-38](https://user-images.githubusercontent.com/1796208/52156739-b2782180-264f-11e9-9bf7-683a7302a314.png)

The tasks tab (which takes a long time to load presumably does to the fact that i've done a lot of jobs over time) looks like this:

![screenshot from 2019-02-01 18-32-45](https://user-images.githubusercontent.com/1796208/52156757-db98b200-264f-11e9-819d-186067066a65.png)

There is the following error in the console, but I suspect it's unrelated and is just a bokeh artifact from me loading the page.

![screenshot from 2019-02-01 18-34-25](https://user-images.githubusercontent.com/1796208/52156809-1b5f9980-2650-11e9-880d-303c821a79be.png)

**Comment by mrocklin** [comment]
Anything in the scheduler logs?

**Comment by birdsarah** [comment]
I can't see. My cluster was started with dask-yarn.

**Comment by birdsarah** [comment]
It's not a big deal. If you leave me notes of things to setup / configure when I start my next cluster I can post back when/if it happens again with more details. Of course my current rather intense workload will be dying off in a bit so it may be a while before i reproduce.

I'm on EMR. Latest versions of everything (cluster was built a couple of days ago).

**Comment by mrocklin** [comment]
There may be a way to get logs from your cluster object.  I would look for
a logs method

**Comment by birdsarah** [comment]
If there is it isn't documented and I can't see it in the code either. Any thoughts @jcrist?

**Comment by jcrist** [comment]
There is no logs method. You can see live logs via the YARN web ui (see https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-web-interfaces.html and https://jcrist.github.io/skein/web-ui.html). To get logs from stopped applications, run `yarn logs -applicationId <your application id>`.

**Comment by birdsarah** [comment]
OKAY cool. It's happened again and I've made my way to skein web ui and through that to hadoop ui.  Poking around i'm seeing logs but nothing looks relevant or like a bokeh error / info. Any pointers on where to look?

**Comment by mrocklin** [comment]
I would expect some log to come from distributed.bokeh.  It would probably
be pretty obvious though.  If nothing is happening then I'm not sure.

**Comment by jbusecke** [comment]
I am encountering the same issue with a `LocalCluster` on a remote server. Where do I find the logs? I have checked these at `localhost:xxxx/info/main/logs.html` and they show nothing special:

```
distributed.scheduler - INFO - Clear task state

distributed.scheduler - INFO - Scheduler at: tcp://127.0.0.1:34458

distributed.scheduler - INFO - bokeh at: 127.0.0.1:6657

distributed.scheduler - INFO - Register tcp://127.0.0.1:40071

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:40071

distributed.scheduler - INFO - Register tcp://127.0.0.1:42353

distributed.scheduler - INFO - Register tcp://127.0.0.1:33325

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:42353

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:33325

distributed.scheduler - INFO - Register tcp://127.0.0.1:37151

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:37151

distributed.scheduler - INFO - Register tcp://127.0.0.1:35367

distributed.scheduler - INFO - Register tcp://127.0.0.1:35153

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:35367

distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:35153

distributed.scheduler - INFO - Receive client connection: Client-1a043cb8-40fc-11e9-8be5-246e96ad1c18
```

**Comment by mrocklin** [comment]
If you're starting a LocalCluster then try the silence_logs= keyword

**Comment by simaster123** [comment]
Was this solved?  It happens to me as well and I'm also not seeing anything in the logs that points to a cause.

**Comment by birdsarah** [comment]
Nope. Still happens to me all the time.

**Comment by simaster123** [comment]
Actually, here is an error in my scheduler readout that might be connected to the issue:

distributed.utils - ERROR - 'start'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/distributed/utils.py", line 713, in log_errors
    yield
  File "/usr/local/lib/python3.7/dist-packages/distributed/bokeh/components.py", line 542, in update
    ts = metadata["keys"][self.key]
KeyError: 'start'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f8a22ba8d68>>, <Future finished exception=KeyError('start')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/document/document.py", line 1112, in _with_self_as_curdoc
    return f()
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/document/document.py", line 1125, in invoke
    return f(*args, **kwargs)
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/document/document.py", line 915, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/distributed/bokeh/components.py", line 564, in <lambda>
    self.doc().add_next_tick_callback(lambda: self.update(prof, metadata))
  File "/home/dan/.local/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 97, in func
    return input_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/distributed/bokeh/components.py", line 542, in update
    ts = metadata["keys"][self.key]
KeyError: 'start'

**Comment by mrocklin** [comment]
Hrm, that traceback seems to be related to the profile plot, not the task stream plot.  It still looks like it's worth tracking down, but doesn't seem related to this issue.

**Comment by mrocklin** [comment]
If anyone is able to provide a minimal reproducible example here that would be welcome.  Ideally this would be a small set of steps to reproduce the issue.

**Comment by simaster123** [comment]
I was unable to reproduce the issue with a couple attempts at creating a minimal reproducible example.  But, it happens regularly with my real code.  Is there a way to view and/or enable verbose logs from bokeh and the code that creates the task stream?

**Comment by quasiben** [comment]
@simaster123 you can set the log level in dask config file:
http://docs.dask.org/en/latest/configuration.html#yaml-files

**Comment by simaster123** [comment]
Thanks, @quasiben.  I uncommented the logging section in the distributed.yaml file and changed bokeh to info (I also tried debug), but I'm not seeing any additional logging information.  Am I doing something wrong?

  logging:
     #distributed: info
     #distributed.client: warning
     bokeh: info
     # http://stackoverflow.com/questions/21234772/python-tornado-disable-logging-to-stderr
     #tornado: critical
     #tornado.application: error

**Comment by davidbrochart** [comment]
I set up an example where it happens quite often, you can run it on Pangeo's binder:
http://binder.pangeo.io/v2/gh/davidbrochart/pangeo-streamflow/master
And execute the `notebooks/dask_stream_bug.ipynb` notebook. I'm not sure you can see the issue locally, but you can try by setting `is_pangeo_data=False`:
https://github.com/davidbrochart/pangeo-streamflow
