### ISSUE TITLE
full garbage collection

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/distributed#2502]
As I need to apply, over an xarray dataset, a function, that can't be vectorized I'm testing the possibility to use futures to get the calculation done.  
To avoid an overproduction of futures I'm working by row and, within the row, I split pixels in groups by the number of core I've. 
To create the futures I'm using the coordinate pixel pairs with the function passed as argument.  
Another approach would be to stack the array, use a delayed approach, and unstack the results but I prefer the other approach as it was more similar to what I was doing with the previews version that was based on  MPI.  
Within this context I'm facing a problem with the garbage collector,no matter how is configured my system I always end up with this error:
`distributed.utils_perf - WARNING - full garbage collections took xx% CPU time recently (threshold: 10%)`

I've tested on both windows/linux machine (python 3.6) with the latest version of distributed, xarray, pandas 0.23.4:

Following some suggestion founded here I tested:
- threads approach (1 thread per worker)
- increase of memory (on the linux machine I've 128 giga of ram)
- increase of the target memory up to 0.95 and false for all the other parameters.
- force the gc.collection
- cleaning signal to all the workers at the end of each row process
- decrease the number of workers

sooner or later the message always appeared according to the ram you have or the array dimension

here the code I'm using:
  ```
def function(chunk, **kwargs):

    rowi = kwargs.pop('data', '')
    parameter = kwargs.pop('parameter', '')

    chunk_out = pd.DataFrame(index=rowi.time, columns=pd.DataFrame(chunk)[1])

    try:
        for i in chunk:
            ts = rowi.isel(dict([('y', i[1])])).to_series().astype(float)
            # ----- substitute algorithm -----
            ts += parameter
            chunk_out[i[1]] = ts
            # ----- substitute algorithm -----
            del ts
            gc.collect()
    except:
        pass

    return chunk_out


def main():

    # Data creation
    times = pd.date_range('2000-01-01', periods=500) # to stress more the system just increase the period value
    x = range(3)
    y = range(int(14e1))
    cube = xr.DataArray(np.random.rand(len(times), len(x), len(y)), coords=[times, x, y], dims=['time', 'x', 'y'])
    pixels_pairs = np.argwhere(cube.isel(time=0).values)

    # Client
    client = Client(processes=False, n_workers=1, threads_per_worker=1)

    for row_idx in cube.x.values:
        row = cube.isel(dict([('x', row_idx)])).persist()

        px_list = [ith for ith in pixels_pairs if ith[0] == row_idx]
        output_carrier = pd.DataFrame(index=cube.time, columns=cube.y)

        chunks = np.array_split(px_list, multiprocessing.cpu_count()*4)
        rowi = client.scatter(row, broadcast=True)
        futures = client.map(function, chunks, **{'data': rowi, 'multiplier': 10})

        for future, result in as_completed(futures, with_results=True):
            output_carrier.update(result)
            del future, result
            gc.collect()

        cube[:, row_idx] = output_carrier.values```

**Comment by mrocklin** [comment]
> distributed.utils_perf - WARNING - full garbage collections took xx% CPU time recently (threshold: 10%)

Note that this isn't an error.  It's just saying that you're spending a bunch of time in GC.  My guess is that this is caused by a bunch of slicing and such, but I'm not sure.

**Comment by PhenoloBoy** [comment]
I wrongly pose the entire question.Is it possible that garbage collection is so heavy that's the reason I get 
this error ?
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:41356 remote=tcp://127.0.0.1:41498>

**Comment by mrocklin** [comment]
I doubt it, but it's possible.

Also, just to point out, that also isn't an error.  It's just a warning.
The logs will warn about any negative event, but some of those events may
not stop Dask from running correctly.  I encourage you to distinguish
between "warning" and "error"

**Comment by PhenoloBoy** [comment]
My apology, you are fully right. Is there any way to set a higher threshold value for the garbage collection?
