### ISSUE TITLE
Deprecate dask-mpi within this project and point to the dask-mpi package

### ISSUE THREAD

**Issue by costrouc** [dask/distributed#2516]
The dask_mpi cli provided with distributed requires mpi4py but it is not listed https://github.com/dask/distributed/blob/master/distributed/cli/dask_mpi.py#L4

**Comment by mrocklin** [comment]
cc @kmpaul @andersy005 

It would be good to add a warning to the dask-mpi CLI command in this project and point instead to the standalone dask-mpi project.

**Comment by kmpaul** [comment]
@mrocklin What is the dask-approved way of throwing a deprecation warning?  With `warnings.warn` package?  With `logging.warn`?  If `logging` is the preferred method, is there a particular logger that I should use?

**Comment by mrocklin** [comment]
I would use warnings.warn

**Comment by kmpaul** [comment]
Should this issue be closed?

**Comment by jrbourbeau** [comment]
Closing as a deprecation warning for `dask-mpi` in this project was added in #2522
