### ISSUE TITLE
LocalCluster may overallocate memory

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#2536]
On a VM with 16GB of total memory:
- `Client(n_workers=1)` allocates 16GB for a single spawned worker
- `Client(n_workers=2)` allocates 8GB for each of the two spawned workers
- `Client(n_workers=4)` allocates 4GB for each of the four spawned workers
So far so good but
- `Client(n_workers=3)` allocates 8GB for each of the three spawned workers

Even worse, in the latter case there's no `MemoryError` or `KilledWorker` when the workers do end up needing more than the total memory. Instead the whole VM becomes unresponsive and has to be rebooted (couldn't even ssh to it).

**Comment by mrocklin** [comment]
Thanks for the bug report @gsakkis I agree that we could probably do better here.

I believe that we're in a case where two reasonable-sounding heuristics are conflicting with each other.

One is here, where we figure out how many threads we should give to each worker given the number of desired processes:

https://github.com/dask/distributed/blob/78a1a347b84ce6835e5b49e4b0a83236cf35a20a/distributed/deploy/local.py#L110-L112

The other is here, where we have workers select an amount of memory proportional to the number of threads that they have received:

https://github.com/dask/distributed/blob/78a1a347b84ce6835e5b49e4b0a83236cf35a20a/distributed/worker.py#L2630-L2634

The simplest solution is, I think, to modify the first heuristic to replace `ceil` with `floor`.  The negative consequence of this choice is that we would undersaturate our CPU if the user selected a number of workers that didn't evenly device the number of logical cores.  This is a less-bad fate than running out of memory though, as you've experienced.

Any interest in making this change?

**Comment by gsakkis** [comment]
I'm kinda confused about the logic here; shouldn't the memory per process worker be just `TOTAL_MEMORY / num_processes`? Or `TOTAL_MEMORY / num_threads`  if it needs to be allocated per thread (by the way I thought `threads_per_worker` was applicable only if you instantiate a LocalCluster with `processes=False`, not always) ? In that case the first heuristic could stay as is, e.g. 2 threads per worker for `n_workers=3` = 6 threads in total, with each thread taking 1/6th of `TOTAL_MEMORY`.

**Comment by mrocklin** [comment]
LocalCluster doesn't currently specify memory_limit (though it could) it
only specifies threads, which it oversubscribes.  If not given an explicit
memory limit then dask workers look at the total memory and multiply that
by the number of threads they've been told to start divided by the number
of logical cores.
