### ISSUE TITLE
Require Tornado 5.0+ ?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2538]
Should we start requiring Tornado 5.0+ ?

This would help us to avoid some recent issues like https://github.com/dask/distributed/issues/2506 (this has come up in a couple other issues as well), but Tornado 5.0 is less than a year old.

I asked briefly on the Jupyter gitter chat, and got a rough go-ahead from them: https://gitter.im/jupyter/jupyter?at=5c61ac46dc3f0523cc99d32c

I would be very interested in hearing from people for whom updating to 5.0+ would be a challenge.

**Comment by mrocklin** [comment]
This is done

**Comment by jakirkham** [comment]
Yeah, this makes even more sense with Tornado 6 released. Inevitably we will probably have to take on some workarounds for Tornado 5 and 6 to play nicely. ( https://github.com/dask/distributed/issues/2547 ) Dropping Tornado 4 should only make this easier.
