### ISSUE TITLE
Can LocalCluster be in a context?

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/distributed#2545]
It doesn't seem like it's possible to use `with LocalCluster()`, instead an explicit close is required.

**Comment by CMCDragonkai** [comment]
Even calling `cluster.close()` can still sometimes result in:

```
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:37456 remote=tcp://127.0.0.1:35009>
```

**Comment by CMCDragonkai** [comment]
Seems like this is related to this: https://github.com/dask/distributed/issues/2507

**Comment by mrocklin** [comment]
In what way does `with LocalCluster()` not work for you?  Is it just the closing dangling stream warning, or is there something else going on?

Here's my experience.

```python
In [1]: from dask.distributed import LocalCluster

In [2]: with LocalCluster():
   ...:     pass
   ...:

In [3]:
Do you really want to exit ([y]/n)? ^D
(dev) MROCKLIN-MLT:dask mrocklin$
```

**Comment by CMCDragonkai** [comment]
Yes I realised, it's a #2507 problem. It's the warning that's confusing.
