### ISSUE TITLE
KilledWorker exception should include worker name

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#2549]
If we don't include the worker name alongside the 'tcp://' address in the exception object, it's hard to get that info otherwise (that I can tell) since the worker has been removed from the scheduler.

Will you accept a PR to add that to the KilledWorker exception? Also, any reason that KilledWorker takes args (instead of kwargs), as in:

```
KilledWorker(k, address)
```

Can we make kwargs to identify these arguments?

cc @plbertrand @wyegelwel

**Comment by mrocklin** [comment]
Sorry for the long delay in this.  Including a worker name seems sensible to me.

It's a little bit odd because a `KilledWorker` error is often caused by many workers failing rather than just one.

**Comment by plbertrand** [comment]
I agree it's a little odd in that regard but the scheduler does not seem to keep the history of the task. The reason I'm adding this information is to help find the process that has the logs for the failed task in our Mesos environment. Having only the ip and the port makes it hard to find it.

I also tried to attach the whole worker state to the exception but it seems to fail to pickle on Python 2.7,

If there is a history of workers for a given task, I'm happy to attach it to the exception as opposed to the last failed worker. What are your thoughts?
