### ISSUE TITLE
Bokeh warning from get_task_stream.

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2560]
```
/home/nfs/an.taugspurger/miniconda3/envs/ucx-dev-test/lib/python3.7/site-packages/bokeh/io/saving.py:126: UserWarning: save() called but no resources were supplied and output_file(...) was never called, defaulting to resources.CDN
  warn("save() called but no resources were supplied and output_file(...) was never called, defaulting to resources.CDN")
         Took 14.14s
```

To avoid the warning, we need to pass a `resources=` to https://github.com/dask/distributed/blob/fb30c33562862f30864456766424b44a3e91aa5b/distributed/client.py#L3590

The bokeh default of `resources=resources.CDN` seems good, but I don't think we should warn.

I could imagine making this configurable, for when you want to view the bokeh plot behind a firewall that doesn't have access to bokeh's CDN. To make it configureable, we'll need to add a `resoruces` keyword to `Client.get_task_stream`  and `distributed.get_task_stream`. Is there a potential ambiguity with the name resources? I could imagine "resources"? http://distributed.dask.org/en/latest/resources.html?highlight=resources#worker-resources Maybe call it `bokeh_resources` to be safe.

**Comment by mrocklin** [comment]
That seems reasonable to me

**Comment by jakirkham** [comment]
Saw this recently. Tom's suggestion also seems reasonable to me.

**Comment by jakirkham** [comment]
It looks like [Bokeh's default is `INLINE`]( https://github.com/bokeh/bokeh/blob/d53cfcc92bc5cf8b13dd59ed6d31ae2bb2c6be65/bokeh/io/saving.py#L65-L67 ). Am I missing something?

**Comment by prasunanand** [comment]
I am working on it.

**Comment by jrbourbeau** [comment]
Great, thanks @prasunanand. I think we want to have a call to `output_file` before `save`, like is done here:

https://github.com/dask/distributed/blob/b0c000883eb10d4801b967fe348c4d6281ca3f1d/distributed/scheduler.py#L5097-L5098
