### ISSUE TITLE
Starting kernel event loops

### ISSUE THREAD

**Issue by AakashGfude** [dask/distributed#2567]
Hi, While executing julia code written in ipynb files through dask `client` ,  I get `starting kernel event loops` in my terminal. Not that it causes any errors but I am just curious when does this happen. It does not happen with Python though. Could not find a proper reason for this.

![image](https://user-images.githubusercontent.com/6542997/54499806-f6a65380-4969-11e9-810a-6c052d8878cb.png)

**Comment by mrocklin** [comment]
Hi @AakashGfude , thanks for the issue.  I don't recognize that message unfortunately.  I suspect that it's coming from somewhere in IJulia.  I'm not sure how best to help you here.

**Comment by AakashGfude** [comment]
@mrocklin thanks for the info. Just to take advantage of your expertise. This message must be printed from the dask code right? based on some configuration of Ijulia.

**Comment by mrocklin** [comment]
> This message must be printed from the dask code right?

I don't know.  It could be printed from anything.

**Comment by AakashGfude** [comment]
@mrocklin Alright. Thanks
