### ISSUE TITLE
Feature to forward logs (in a streaming manner) to the client

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/distributed#2569]
I understand that other logging issues (#1288) and  and questions on SO have basically said that logs are intended to be captured by the cluster management system.

My argument is that  distributed job logs should be separate from the worker logs. The former is about what is happening to the distributed graph processing. The latter is about what is happening to the worker. The former has context relevant to the client and the distributed job scheduler. The latter has context relevant to the cluster manager.

So I'd like the ability to keep logs relevant to the cluster manager managed by the cluster manager. But job logs should be handled by dask specifically and then be "redirectable", either to another log management system. But the default I think should be that it forwards it back to the client (and also outputs to whatever local stream as well).

Right now when I use dask client, it executes then gives me back futures. What if it also gave back a stream that I could just print out the logs. I noticed that Dask distributed already supports queues, but that for in-band data, and this is an out-of-band data stream back to the client.

**Comment by CMCDragonkai** [comment]
Is there a way for workers to establish a communication object with the client? In the client I could run a separate TCP thread server to listen on connections and then make workers connect to that to send logs. But I'm wondering if I could instead get a "channel" within the same communication system that dask is using between clients and workers so that way this could be used when the client is blocked by NAT.

**Comment by mrocklin** [comment]
You might look at dask's PubSub system.

http://docs.dask.org/en/latest/futures.html#coordination-primitives

**Comment by CMCDragonkai** [comment]
In this case the client is a subscriber and the workers are publishing.

**Comment by mrocklin** [comment]
OK

**Comment by mrocklin** [comment]
Anything else here?

**Comment by CMCDragonkai** [comment]
I'll try this and let you know.
