### ISSUE TITLE
Reaping stray process  & Future finished result=None

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/distributed#2574]
At the end of a long, successful, process I get back this warning and then a long list of errors. 
I'm working over a distributed approach where I'm creating and collecting futures. 
Warnings are in the same number as the workers but errors are much more. 
```
distributed.process - WARNING - reaping stray process <Process(Process-4, started daemon)>
distributed.process - WARNING - reaping stray process <Process(Process-3, started daemon)>
distributed.process - WARNING - reaping stray process <Process(Process-2, started daemon)>
distributed.process - WARNING - reaping stray process <Process(Process-1, started daemon)>
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000001D827237378>, <Future finished result=None>)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tresei\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Anaconda3\envs\tresei\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Anaconda3\envs\tresei\lib\site-packages\distributed\scheduler.py", line 1800, in <lambda>
    lambda _: self.cancel_key(key, client, retries - 1))
  File "C:\Anaconda3\envs\tresei\lib\site-packages\distributed\scheduler.py", line 1796, in cancel_key
    cs = self.clients[client]
KeyError: 'Client-d76678be-4b23-11e9-b0b4-30e171cd71c3' 
...
```
the note "Future finished result=None" sounds to me that there was a problem in the algorithm and some futures get stuck without sending back anything to the client; when the client is closed all this pendant futures are drop and I get back the error.
My deductions are correct? if so, is any way to roll back from the future to know the request that created it? or to check if the client is keeping some pending future ? 
I'm working on a localcluster running over a Python 3.6 (Anaconda) Win10 x64.

**Comment by mrocklin** [comment]
Hi @PhenoloBoy .  My apologies for the late response.   Are you able to provide a minimal example?  That would help to isolate the issue.

**Comment by PhenoloBoy** [comment]
Hi @mrocklin, 

never apology. Working on it... not easy ... I'm able to replicate the warning but not yet the Error.
