### ISSUE TITLE
Is it possible to suppress distributed.utils perf WARNINGS?

### ISSUE THREAD

**Issue by kindjacket** [dask/distributed#2576]
I am getting a lot of ```distributed.utils_perf - WARNING - full garbage collections took x% CPU time recently (threshold: 10%)``` warnings. Is it possible to suppress these as it is clogging up my logging?

**Comment by mrocklin** [comment]
You can control logging using the normal Python logging module approach.  

In principle we could make some of the parameters around the GCDiagnostics module configurable.  If you have time to investigate that that would be welcome.

**Comment by mrocklin** [comment]
My apologies for the late response

**Comment by kindjacket** [comment]
I'll dig into it and update here. Thanks @mrocklin

**Comment by goldenbull** [comment]
my simple solution:

create a simple python script `dask_preload.py`
```python
import logging
logger = logging.getLogger("distributed.utils_perf")
logger.setLevel(logging.ERROR)
```

start `dask-worker` from command line:
`dask-worker --preload dask_preload <scheduler-server>:8786`
