### ISSUE TITLE
Client reconnect should have a timeout

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#2582]
Currently if a scheduler goes down, but the client isn't closed, the client will keep trying to connect to the scheduler address forever. This should probably have a timeout - maybe the same timeout as the initial connect (`distributed.timeouts.connect`)?

Relevant code:

https://github.com/dask/distributed/blob/b36e87d14e75c0cbdd0e3292ac65db2a836f74bd/distributed/client.py#L871-L876

**Comment by mrocklin** [comment]
The client keeps around the timeout provided at initialization at `self._timeout`.  This defaults to `defaults.timeouts.connect`.  Would that work?

**Comment by jcrist** [comment]
Yeah, that'd be good. I'll try to get a PR up for this sometime soon.
