### ISSUE TITLE
Requires internet connection

### ISSUE THREAD

**Issue by jseabold** [dask/distributed#259]
I was surprised that `dscheduler` and even `dscheduler --help` require an internet connection. Maybe a try/except around `global_ip` that falls back to localhost with a warning? Things should still work locally right?

**Comment by mrocklin** [comment]
Sure, I see a couple of options

1.  Add a timeout to get_ip
2.  Don't call `get_ip` at all if the user supplies a hostname/ip

Thoughts?  Preferences?

**Comment by mrocklin** [comment]
I've gone ahead and done both in https://github.com/dask/distributed/pull/261
