### ISSUE TITLE
Executor.map on Iterator hangs

### ISSUE THREAD

**Issue by amosonn** [dask/distributed#260]
The helper thread spawned when Executor.map is invoked on an Iterator never puts a StopIteration into the queue, so the iterator returned (queue_to_iterator) blocks indefinitely.
I will attach a pull request with a test which shows this and a fix (the same fix, btw, is already implemented in scatter, which follows the same pattern).

Note that without the bugfix, the test hangs, and because it is blocking in multithreading, a timeout on the event loop doesn't help. I hope to reimplement this with coroutines and PR soon.

**Comment by mrocklin** [comment]
Great.  Looking forward to the PR and thank you regardless for the bug report.
