### ISSUE TITLE
Confusing behavior from cancelling a running future

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2617]
I stumbled on unexpected behavior when I tried to cancel a running task. Specifically, the task was marked as cancelled, removed from the scheduler state info but it kept running. From the comment on https://stackoverflow.com/questions/49203128/how-do-i-stop-a-running-task-in-dask it appears this is expected behavior that is hard to workaround from a framework perspective in Dask. While the task continuing to run was unexpected, it became worse because new tasks were scheduled to the worker running the cancelled task. The scheduler thought the worker was free to run the task (because the scheduler removed the cancelled task from the processing list) but  the worker simply put it in its queue.

I think given that this is behavior we need to accept from the framework level, it would be more user friendly to either raise an exception when a user tries to cancel a running task, or, issue a warning the task is running and not stopped from running, mark all dependencies as cancelled because the task is canceled and maintain the reference to it running so that the system doesn't get into a split brain between the scheduler and worker where the scheduler thinks the worker is free but the worker isn't free.

**Comment by mrocklin** [comment]
Something like that makes sense to me

(sorry for the long delay in response)

**Comment by bybyte** [comment]
Relatedly, is it possible to obtain a reference to the associated request? The same way one can get a reference to the worker by calling dask.distributed.worker.get_worker(). 

This way, I could check if the request was cancelled from within the job itself and terminate if that was the case.

**Comment by martindurant** [comment]
I'm pretty sure that no :|  Perhaps to do that kind of thing, you'd want a different communication primitive instead of cancel, like pub-sub, so you can inform your jobs that you would like them to close.

**Comment by bybyte** [comment]
Thank you. Would you be able to point me to an example of how to use pub-sub? 

Is it possible to subscribe to a cancellation too? That is not a deal breaker but would definitely be nice.

**Comment by martindurant** [comment]
You would be looking [here](https://docs.dask.org/en/latest/futures.html#coordination-primitives) in the docs (but not queues, which are being deprecated), or possibly [actors](http://distributed.dask.org/en/latest/actors.html)

> Is it possible to subscribe to a cancellation

Not without writing your own scheduler plugin.

**Comment by martindurant** [comment]
(sorry for the confusion)

**Comment by bybyte** [comment]
I was able to use pub-sub to send termination requests. Thanks! 

Do I need to worry about memory leaks? For example, if I publish something when there is at least a subscriber, but that subscriber never "get" and gets garbage-collected, will the data that was published be garbage collected as well -- since nothing will ever expect to retrieve it anymore?

Thank you!

**Comment by mrocklin** [comment]
Data will only stay around if there is a reference to it

**Comment by wwoods** [comment]
What do we think about this pattern for long-running, cancellable tasks?

```python
import dask.distributed as d
client = d.Client()

def run_until_cancelled(self_var):
    self_future = self_var.get(10)  # Raises TimeoutError if the initial set fails, or other error
    self_var.delete()  # Prevent memory leaks
    while not self_future.cancelled():
        # Do piece of long-running work
        pass

v = d.Variable()
v.set(client.submit(run_until_cancelled, v))
```

My biggest concern about this pattern was the race condition where `v` wouldn't get set when something bad happens between the `client.submit` and `v.set` calls; however, it appears that dask helpfully does NOT return `None`, but blocks on an unset variable. Since that's the case, it seems to work fairly well. It lets a task be aware of its own cancellation status, and abort appropriately. Also, nothing has to keep track of `v` since all information is ultimately stored in the task. Since it is ephemeral, the task itself deletes the variable after getting the value.

**Comment by martindurant** [comment]
There is no conceptual problem with what you are doing; however, each time you check the variable, you are hitting the scheduler - which could be a problem at scale. I'm not actually certain if the future you create would necessarily cancel.

The following, instead, checks that the current task is still in the worker's execution pipeline; a cancel will tell the worker to stop thinking about the task (and it would normally just stop of its own accord, eventually).

```python
def run_check():
    w = dask.distributed.get_worker()
    while True:
        try:
            t = w.tasks[w.get_current_task()]
        except KeyError as e:
            # graceful exit
            break
        pass
```
(where `pass` is the work to be done per cycle)

**Comment by jrbourbeau** [comment]
Closing as it looks like the outstanding questions here have been answered. Feel free to open a new issue if this isn't the case

**Comment by wwoods** [comment]
Note for anyone who finds this in the future:

As of some time before now, the run_check function has changed slightly:

```python
def run_check():
    w = dask.distributed.get_worker()
    try:
        t = w.tasks[w.get_current_task()]
        # Tasks no longer removed; also check if in a cancellation state
        if t.state.startswith('cancel'):
            return True
    except KeyError:
        return True
    # Not cancelled or forgotten
    return False
```
