### ISSUE TITLE
`distributed.worker.cache` can use a lot of memory

### ISSUE THREAD

**Issue by SeventeenPelicans** [dask/distributed#2621]
Currently, `distributed.worker` has a module level cache that is populated by `dumps_function`:

```python

cache = dict()


def dumps_function(func):
    """ Dump a function to bytes, cache functions """
    try:
        result = cache[func]
    except KeyError:
        result = pickle.dumps(func)
        if len(result) < 100000:
            cache[func] = result
    except TypeError:
        result = pickle.dumps(func)
    return result
```

This seems useful in the majority of use cases to avoid re-pickling everything constantly. In my use cases, I'm using dask to run a large number of functions in order to do some optimisation (the workflow is I send off a bunch of tasks, and then add new tasks as I receive back results via `as_completed`). As these functions are almost never the same, this cache can get quite large. It's also not that necessary for my use case since I'm rarely dumps-ing the same function twice. It would be useful if this cache had a configurable max size, or some other configuration that achieves the goal of limiting how much memory this cache can use.

**Comment by mrocklin** [comment]
Something like the following might help: https://github.com/dask/distributed/pull/2623

We could also put these values in configuration.  No strong thoughts from me.

**Comment by SeventeenPelicans** [comment]
Thanks @mrocklin, this seems like a good solution. I'm not overly concerned with how / if this thing is configured, so long as there's some reasonable limit on how big the cache can get.
