### ISSUE TITLE
Unexpected `CancelledFuture` error

### ISSUE THREAD

**Issue by cicdw** [dask/distributed#2628]
Over at https://github.com/PrefectHQ/prefect/issues/943 we're running into a very interesting situation; we believe we know how to fix it in our own codebase, but I'd like to understand whether this is a fundamentally bad Dask pattern or whether this is a bug.  

In short, we are using multiple `worker_client`s and `fire_and_forget`, and are seeing `CancelledFuture` errors in very unexpected circumstances.  These errors seem to only occur in _very_ specific circumstances, but not otherwise.

To reproduce, start a local cluster:
```
dask-scheduler
dask-worker --nanny --nthreads 3 127.0.0.1:8786
```

and run this script (basically a distillation of how we're using Dask in our pipeline):
```python
from distributed import Client, fire_and_forget, worker_client

def inc(x):
    return x + 1

def dec(x):
    return x - 1

def mapper(fn, arr):
    with worker_client(separate_thread=True) as client:
        futures = client.map(fn, arr, pure=False)
    fire_and_forget(futures)
    return futures

def waiter(futs):
    with worker_client(separate_thread=True) as client:
        return client.gather(futs)

def pipeline(fn, arr):
    futs = mapper(fn, arr)
    return waiter(futs)

with Client(address='localhost:8786') as client:
    f = client.submit(pipeline, inc, list(range(100)))
    fire_and_forget(f) # this appears to be irrelevant
    g = client.submit(pipeline, dec, list(range(100)))
    fire_and_forget(g) # this appears to be irrelevant
    val = client.gather([f,g])
```
and you _should_ get a `CancelledError`.

Notes:
- if you write the logs from the scheduler and worker to a file, the error doesn't seem to occur
- if you run this twice, the error won't occur; it seems to only occur whenever the scheduler, worker and python process are all "fresh"
- this is on `distributed.__version__` = 1.26.1
- it appears to be threading related (running with 1 thread doesn't reproduce)

It seems that removing the `fire_and_forget` call inside `mapper` fixes the situation.

**cc:** @jlowin

**Comment by martindurant** [comment]
I can confirm that I see a CancelledError when running the script.
If I change the one line as follows
```
def mapper(fn, arr):
    with worker_client(separate_thread=True) as client:
        futures = client.map(fn, arr, pure=False)
        fire_and_forget(futures)  # <- added indent
    return futures
```
Then I no longer see the problem. I guess the firing was happening after the futures no longer had the client available by which they were made.

**Comment by jlowin** [comment]
Hey Martin,

I was also hoping that would solve it, but unfortunately I do see the `CancelledError` even with the indent.

The confusing thing about this error (to me, at least!) is it only happens the FIRST time that BOTH the worker AND the scheduler are running. Subsequent calls work fine.

For me personally, I run `dask-scheduler` in one terminal; `dask-worker --nanny --nthreads 3 127.0.0.1:8786` in a second terminal; and then run the script in a third. Any time I kill both the scheduler and worker, then restart them, I can recreate the error by running the script. Subsequent executions work fine.

**Comment by martindurant** [comment]
huh, ok - managed to see it with the indent too (but not every time I restarted everything)

**Comment by martindurant** [comment]
I can't say exactly why this is happening without some further digging - those futures still point to existing tasks at the time of gathering (I tried making inc/dec take longer); but no, I don't think this is the intent of fire_and_forget:

> The results will not be kept in memory after the task completes (unless
    there is an active future) so this is only useful for tasks that depend on
    side effects.

What you really want, is to make sure that your task results are referenced by some client even after they are done, so that they can be fetched later. You could do that with `publish_dataset`, maybe, but this doesn't seem like the right way either

```
def mapper(fn, arr):
    with worker_client(separate_thread=True) as client:
        futures = client.map(fn, arr, pure=False)
        client.publish_dataset(**{fn.__name__: futures})
    return fn.__name__

def waiter(name):
    with worker_client(separate_thread=True) as client:
        futs = client.get_dataset(name)
        return client.gather(futs)

def pipeline(fn, arr):
    name = mapper(fn, arr)
    return waiter(name)
```
(here, the latest future set for a given function name stays alive forever)

**Comment by jlowin** [comment]
True --> our objective is to submit futures with one client and retrieve them with another, which (generally speaking) works fine as long as we work around #2227 by using fire-and-forget to persist the future and request its value from the scheduler explicitly.

**Comment by cicdw** [comment]
Ok so, it seems that `fire_and_forget` was sort of a red herring; ultimately the problem is what @jlowin mentioned above: we want to resolve futures created by one client with another client.  We used `fire_and_forget` to ensure the scheduler kept those futures alive, but it doesn't help us resolve them by other clients (hence the `CancelledError` which is really just a symptom of the client not having that future).

It would be amazing if we could "tag" a future somehow to let the scheduler know we fully intend to resolve it in the future with another client.

**Comment by mrocklin** [comment]
Have you seen Variables, Queues and Pub/Sub?

https://docs.dask.org/en/latest/futures.html#coordination-primitives

**Comment by jlowin** [comment]
Thanks Matt -- we've actually been experimenting with them since last night! Cleanly resolve this example, but we're still looking at the best way to implement it more generally.

**Comment by mrocklin** [comment]
They are all fairly similar in how they're implemented.  Queues are probably the cleanest.  It would be straightforward, I think, to add other coordination primitives to Dask, should you all be interested.  These could live within the main project, or probably outside as well if you wanted to manage and evolve them yourselves.

**Comment by cicdw** [comment]
I think I can close this, because ultimately the error arises from sharing futures between clients and is therefore not a bug, just something we have to work around in our specific use case.  Thanks all for the help and insight!

**Comment by mrocklin** [comment]
Well, sharing futures between clients should be supported (with various
constraints).  If there is a genuine bug here I'd be interested in seeing
it resolved.

**Comment by cicdw** [comment]
Fair; the only thing that still leaves me suspicious is the fact that this always seem to run fine on the _second_ run, but not always on the _first_ run.  Not sure if there's a bug in there, or if that's just coincidence.

I think a full description of what client / future-sharing setup we're trying to achieve is beyond the scope of this issue, but I'd be happy to share it if anyone is interested in digging into the Prefect code base :)
