### ISSUE TITLE
Question: Documentation of best practices when combining Numba with Dask

### ISSUE THREAD

**Issue by hoangthienan95** [dask/distributed#2641]
Hi there,

Is there a place where I could find best practices/patterns/anti-patterns when using Numba with Dask to boost performance? A lot of the time they are mutually exclusive (dataframes only work with Dask) or complement each other (use numba `jit` on functions then `map_partition`/`apply` with Dask), but it seems like when dealing with numpy array/collections there's alot of overlapping functionality. I wonder if other people have tested to see in which situation you prioritize one or the other.

**Comment by mrocklin** [comment]
cc @jcrist who has significant experience with both.

A broader question though is where we would put this kind of cross-project documentation.  It's not clear to me that we have a good place for this outside of blogposts today.

**Comment by hoangthienan95** [comment]
My dream is Dask, Numba, along with other optimizing/scaling tools, and packages that have these as dependencies all share a website that has a matrix where each cell is a link to tips/tricks of using two tools in combination with each other. People visiting this site can discover what other libraries use Dask in cool ways (TPOT, Prefect etc).

**Comment by mrocklin** [comment]
I agree that that would be great.  That's probably out of scope for this issue tracker though (the people here are unlikely to take on the thing that you suggest).  Unfortunately I don't know of a good place to discuss this with all of the relevant people that would be necessary to create such a thing.

**Comment by hoangthienan95** [comment]
Thank you for the prompt reply. Maybe when I become moderately proficient in both I'll take a stab at it! Just struggled for a few hours with Numba to do the simplest thing.

Please keep up the good work!
