### ISSUE TITLE
Profiling data for the client process

### ISSUE THREAD

**Issue by stuarteberg** [dask/distributed#2643]
The dashboard profile graphs are very useful for understanding my workers' performance.  Is it possible to get (and visualize) profiling data for the main (scheduler) process, too?

**Edit:** As explained below, I meant to ask about the *client* process, not the *scheduler* process.
**Edit:** Scheduler profiling is discussed in dask/distributed#1907

**Comment by martindurant** [comment]
Making the profiler generally accessible would be very useful, I would like to make it happen.

**Comment by mrocklin** [comment]
Fixed in https://github.com/dask/distributed/pull/2482
