### ISSUE TITLE
deploying with dask-ssh fails on distributed 1.27.1

### ISSUE THREAD

**Issue by bybyte** [dask/distributed#2645]
After updating to distributed 1.27.1 I cannot deploy using dask-ssh. 

Here I report part of the output of running "dask-ssh localhost" on the terminal. I believe one fo the scripts (maybe deploy/ssh.py) is somehow being passed None in place of "distributed.cli.dask_worker". 

Deploying the scheduler and workers individually with dask-scheduler and dask-worker still works for me. 

> --------------------------------------------------------------- 
> 
>                  Dask.distributed v1.27.1
> 
> Worker nodes:
>   0: localhost
> 
> scheduler node: localhost:8786
> --------------------------------------------------------------- 
> 
> 
> [ worker localhost ] : /home/xyz/anaconda2/bin/python -m None localhost:8786 --nthreads 0 --host localhost --memory-limit auto
> [ scheduler localhost:8786 ] : /home/xyz/anaconda2/bin/python -m distributed.cli.dask_scheduler --port 8786
> Exception in thread Thread-2:
> Traceback (most recent call last):
> ...
> [ scheduler localhost:8786 ] : distributed.scheduler - INFO - -----------------------------------------------
> [ worker localhost ] : /home/xyz/anaconda2/bin/python: No module named None
> [ worker localhost ] : remote process exited with exit status 1

**Comment by martindurant** [comment]
I don't yet know why the default changed, but the following does work
```
dask-ssh localhost --remote-dask-worker distributed.cli.dask_worker
```

**Comment by martindurant** [comment]
in c94cde1f7f5bc06ae57a303f7345635e323dad21 the default was set to `None`, where previously this could not be changed at all.

**Comment by bybyte** [comment]
Great -- thanks for the quick reply and fix!
