### ISSUE TITLE
Pytest 4 deprecation warning on pytest.config

### ISSUE THREAD

**Issue by QuLogic** [dask/distributed#2669]
When running pytest 4.4.1, it triggers several deprecation warnings from this line in the test suite:
```
  /builddir/build/BUILD/distributed-1.27.1/distributed/utils_test.py:786: PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.
    if not pytest.config.getoption("--runslow"):
```

**Comment by mrocklin** [comment]
I've been seeing that as well.  I don't know immediately how to solve it.
If anyone has suggestions, they would be welcome.

**Comment by QuLogic** [comment]
I guess something like [this pytest example](https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option).
