### ISSUE TITLE
pass a reference to a future to a worker

### ISSUE THREAD

**Issue by jamesdanged** [dask/distributed#2674]
Is there a way to pass a future to a worker as a reference, instead of as a result? I'd like to have the worker submit its own tasks from inside of a task to a client obtained by `get_client`. 

As an example:
* `fut1` points to a large dataset that has been loaded on `worker1`
* `worker2` will run some task `train_model`
*  `train_model` runs `get_client` and then runs `submit` to the client to run a task: `client.submit(get_minibatch, fut1)` 

Passing `fut1` directly to `train_model` would cause the entire dataset to be marshalled onto `worker1` when all I want is a minibatch from it.

**Comment by mrocklin** [comment]
This might help:
http://docs.dask.org/en/latest/futures.html#coordination-primitives

**Comment by jamesdanged** [comment]
Yes, thank you! Queues and global variables will work perfectly.
