### ISSUE TITLE
Performance study of distributed scheduling overhead

### ISSUE THREAD

**Issue by elliottslaughter** [dask/distributed#2681]
I've been working on a study of the scheduling overhead of various task-based systems, including Dask. I'm wondering: (a) would people here be interested in seeing my results, and (b) if so where should I post them? I'd also be happy to get any feedback on the code and methodology itself, but I think it would be good to resolve (a) and (b) first.

One concern is that the draft of the paper I've written up is currently under submission at a double-blind venue. I am quite happy to send it to people privately, but at the present time I'd prefer not to post it in a public location. I'm open to suggestions here, email or whatever is an acceptable method as long as the paper remains private until its final publication.

**Comment by mrocklin** [comment]
I'd be quite interested in seeing this.  Email is my username at Gmail.

**Comment by elliottslaughter** [comment]
Sent. If anyone else is interested I'd be happy to send additional copies. My email can be found in `git log` on any of the repos I contribute to.

**Comment by GenevieveBuckley** [comment]
@elliottslaughter - out of interest is your paper published publicly now? If so, perhaps you can point us to the DOI

**Comment by GenevieveBuckley** [comment]
Thanks Elliott, very interesting!
