### ISSUE TITLE
Dashboard: tasks and memory charts have quietly changed into histograms

### ISSUE THREAD

**Issue by birdsarah** [dask/distributed#2691]
I am seeing this regularly but not reproduceably (sorry).

Note the tasks and memory plots on the left are oriented incorrectly and have odd axes.

![Screenshot from 2019-05-13 14-13-40](https://user-images.githubusercontent.com/1796208/57647767-7545f880-7589-11e9-9226-ea3b2be252f5.png)

**Comment by mrocklin** [comment]
When you have a larger number of workers they turn into histograms.  Visual
design or bokeh help here would be welcome :)

**Comment by birdsarah** [comment]
Ah! Suggestions for things that could be implemented:

* heading add (Histogram)
* alter the color slightly so it's clearly something new (e.g. two different shades of blue)
* axes labels

**Comment by mrocklin** [comment]
No obligation, but if you (or anyone else who happens by) wants to give
this a shot, the code is here:

https://github.com/dask/distributed/blob/3142dda225baaf1db0b8c73f240f7fad8941fc1e/distributed/bokeh/scheduler.py#L210-L241

**Comment by mathdugre** [comment]
I can work on this if no one else is

**Comment by mrocklin** [comment]
That would be very welcome @mathdugre !

**Comment by mathdugre** [comment]
Is there an easy way to test the dashboard with a large amount of workers?

**Comment by mrocklin** [comment]
```python
from dask.distributed import LocalCluster
cluster = LocalCluster(processes=False, threads_per_worker=1, n_workers=60)
```

Or temporarily change this number 50

https://github.com/dask/distributed/blob/bb80c5e997d020c5b472819fd0751c8234d2b8cc/distributed/bokeh/scheduler.py#L1442-L1456

**Comment by mathdugre** [comment]
I am not sure to understand what should be changed about the axis.

Is it about the label or the styling?

**Comment by birdsarah** [comment]
Yes, I would suggest adding a label to y-axis. It is normally just a worker, so the label "worker" would be good. When it switches to a histogram I would suggest "frequency."
