### ISSUE TITLE
Computing delayed None fails

### ISSUE THREAD

**Issue by alex-marty** [dask/distributed#2696]
I regularly find myself delaying data. I encountered an issue when delaying None: it works fine with simple dask schedulers like processes, but fails with distributed, at least with a local cluster:

```
from dask import delayed
from dask.distributed import Client, LocalCluster

client = Client(LocalCluster())

x = delayed(12)
x.compute(scheduler="processes")  # Returns: 12
x.compute(scheduler=client)  # Returns: 12

y = delayed(None)
y.compute(scheduler="processes")  # Returns: None
y.compute(scheduler=client)  # Error: TypeError: 'NoneType' object is not callable
```

Passing the delayed value as an input to a delayed function yields the same behavior:

```
delayed(str)(y).compute(scheduler="processes")  # Returns: 'None'
delayed(str)(y).compute(scheduler=client)  # Error: TypeError: 'NoneType' object is not callable
```

For now, the workaround I use for the purpose of my project is to detect and replace None values with a delayed function that returns None:

```
def none_func():
    return None

z = delayed(none_func)()
z.compute(scheduler="processes")  # Returns: None
z.compute(scheduler=client)  # Returns: None
```

But I would be happy to switch back to simpler code.

**Comment by quasiben** [comment]
I'm not totally sure what is happening here but `yield None`, which eventually happens down in the tornado world, is [special](http://www.tornadoweb.org/en/stable/gen.html#tornado.gen.moment).

**Comment by mrocklin** [comment]
Interesting.  Thanks for the excellent reproducible example @alex-marty .  I'll take a look later today.

> I'm not totally sure what is happening here but yield None, which eventually happens down in the tornado world, is special.

Also interesting.  I'll keep that in mind as I play around.

**Comment by mrocklin** [comment]
Resolved in https://github.com/dask/distributed/pull/2697

**Comment by alex-marty** [comment]
Awesome, thanks @mrocklin!

**Comment by mrocklin** [comment]
You did most of the work in isolating the problem.  I really appreciate the effort you put in in creating a minimal example.
