### ISSUE TITLE
Pan tool is enabled in progress dashboard window

### ISSUE THREAD

**Issue by birdsarah** [dask/distributed#2698]
I would think all tools should be off to prevent this:

![Screenshot from 2019-05-14 14-41-04](https://user-images.githubusercontent.com/1796208/57727192-72650980-7656-11e9-8624-b86cc84d8c07.png)
![Screenshot from 2019-05-14 14-40-53](https://user-images.githubusercontent.com/1796208/57727193-72650980-7656-11e9-97d7-27681031cdc8.png)

**Comment by mrocklin** [comment]
+1 from me

**Comment by mrocklin** [comment]
@mathdugre, any interest?

**Comment by mathdugre** [comment]
@birdsarah I'm not sure I understand the issue. Is it the progress bar being in the wrong location?

**Comment by mrocklin** [comment]
Apparently it is possible for the user to move the progress bar plot.  @birdsarah is saying that this is probably because the figure for the progress plot has the "pan" tool enabled.  Probably that figure should have no tools enabled, except for maybe the "hover" tool.

**Comment by mathdugre** [comment]
Oh I get it! There is the same behaviour for the histograms when there are a lot of workers (>= 50). Should I fix this one as well?

Also the histogram don't have hover activated. Should I activate it at the same time? I can open another issue if needed.

**Comment by mrocklin** [comment]
I agree with you that we probably shouldn't have "pan" on the histograms.
Yes, it would be good to remove that.

We would only add a hover tool to histograms if there was information that
we wanted to communicate when the user hovered their mouse over a bar.  I
can't think of any information that is important to communicate right now,
but if you think of something that would be useful then yes, that might be
helpful.

However, if you're looking for more work, I suspect that there are more
productive things to do.  @birdsarah has been good about mentioning some
concerns with the dashboard.  I wonder if she has any more?

**Comment by mathdugre** [comment]
For the hover I was thinking of showing the actual number since it might be hard to see the actual number of workers. However as you said it is probably not critical.

I will only disable the "pan" tool for now.
