### ISSUE TITLE
System page on dashboard regularly awkward

### ISSUE THREAD

**Issue by birdsarah** [dask/distributed#2710]
I often end up in an aspect ratio where the system page of the dashboard looks like this:

![Screenshot from 2019-05-18 12-28-41](https://user-images.githubusercontent.com/1796208/57973071-a139f300-7968-11e9-92d4-0705c697a22b.png)

Bokeh's layout has had a big overhaul of late, maybe there's an opportunity to take advantage and get a more robust layout with less code. I would suggest a grid of four plots should always be fine.

**Comment by mrocklin** [comment]
cc @mathdugre , who has been looking into Bokeh plotting issues recently.  (though it looks like this one might be more serious than the previous two).

**Comment by mathdugre** [comment]
Hi @mrocklin, I would definitely like to work on this. Will give it a shot during the week :)
