### ISSUE TITLE
Persist-call ignores assigned worker resources

### ISSUE THREAD

**Issue by Spiegel0** [dask/distributed#2716]
When ```.persist(resources={...})``` is called on a Dask DataFrame, the specified resources will be ignored for scheduling. In particular, no task in the corresponding dashboard pages will outline the resources. In my setup, the following example triggers the issue (using python 3.6 and distributed 1.28.1):

```python
import pandas as pd

import dask.dataframe as dd
from dask.distributed import Client


def test_resources():
    client = Client(n_workers=1, resources={"MyRes": 1000})

    test_input_frame = dd.from_pandas(pd.DataFrame({"A": [1, 2], "B": [3, 4]}), npartitions=1)
    test_output_frame = test_input_frame.apply(lambda row: row.sum(), axis=1)

    output = test_output_frame.persist(resources={"MyRes": 1})
    print(output)

    # The task pages of the dashboard do not display the resource dependencies.
    input("Press any key to exit...")
    client.close()


if __name__ == '__main__':
    test_resources()
```

I quickly ran the debugger on the Dask distributed code and discovered that in ```client.Client._graph_to_futures(...)```, ```self._expand_resources(...)``` returns a dict where the keys are tuples identifying the task. When I manually convert the keys to their string representation, i.e. call:
```python
resources = {tokey(k): v for k,v in resources.items()}
```
after ```_expand_resources(...)```, the task dashboard will display the associated resources. (But I don't know whether converting the keys will have any other side effects)

**Comment by TomAugspurger** [comment]
Sorry for the lack of response here. Can you try your example (which was great btw) on distributed master? This may be fixed. Locally, I see

<img width="953" alt="Screen Shot 2019-05-28 at 6 35 29 AM" src="https://user-images.githubusercontent.com/1312546/58475154-cec62f80-8112-11e9-9ca7-dc96d6c43985.png">

**Comment by jakirkham** [comment]
@Spiegel0, have you had a chance to restest this on `master`? Please let us know if there is a way to help.

**Comment by Spiegel0** [comment]
Thank you very much for your response! I tried the example on distributed master (commit d202e62) but the issue is still there. In my worker's page, the resources are also listed but on the task's page, they are not:
![2019-05-29-worker-screenshot](https://user-images.githubusercontent.com/8793444/58623614-a97e2080-82ce-11e9-8928-8e9e1c8bdb94.png)
![2019-05-29-task-screenshot](https://user-images.githubusercontent.com/8793444/58623622-adaa3e00-82ce-11e9-9ad2-2411582f3abb.png)

When I apply the described line, the task's page expectedly shows the following resource restriction:
![2019-05-29-task-screenshot-resource_restriction](https://user-images.githubusercontent.com/8793444/58624759-46da5400-82d1-11e9-83c4-c13a415babb7.png)

I'll create a brief pull-request to better describe my changes.
