### ISSUE TITLE
Info Page for Worker Dashboard returns 404

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#2722]
The info page (/info/main/workers.html) on for the worker dashboard is not working currently returns 404.   After https://github.com/dask/distributed/pull/2715 is merged we should track down the error and fix

**Comment by mrocklin** [comment]
Also, I suspect, with the profile page

**Comment by birdsarah** [comment]
Just need to switch "status" for "main"

Also suggest improving the link text from "bokeh" to "worker dashboard"
