### ISSUE TITLE
what is default site of dask logging file

### ISSUE THREAD

**Issue by jmsking** [dask/distributed#2736]
i want to know where is the default saving site of logging file in dask, and i have configure the distributed.yaml in ~/.dask.

**Comment by mrocklin** [comment]
Dask workers log to stdout.  Most cluster managers (yarn, kubernetes, slurm, pbs) will then take this and write it to some file, but that depends on the cluster manager.  If you're running things manually then you might want to redirect output to a file yourself.

**Comment by jakirkham** [comment]
Does that answer your question, @jmsking? If so, would you be ok with closing this?

**Comment by jmsking** [comment]
Ok, Thanks so much
