### ISSUE TITLE
store plots from /status page 

### ISSUE THREAD

**Issue by kindjacket** [dask/distributed#2753]
Firstly this is a great project, and I have a lot of appreciation for the work done here.

I'm using dask distributed (v1.28.1) to run multiple simulations (heavy numpy) in parallel across each core on a large machine.

The process begins by starting a local cluster 
```    
cluster = LocalCluster(n_workers=dask_workers, processes=True)
dask_client = Client(cluster)
```
After the simulations are done it kills the local cluster.

Sadly this means I lose all the `/status` plots that are very useful for diagnosing perf issues. Yes, I can view it live. Instead, I'd like to run it and then go through the plots after the fact to diagnose problem areas.

Is this bad design with dask distributed? Should I create the cluster separately and leave it running? Or is there an easy way to store the HTML bokeh charts for visualization after the fact?

**Comment by TomAugspurger** [comment]
You can get the task stream from
https://distributed.dask.org/en/latest/api.html#distributed.Client.get_task_stream
.

I suspect we'd be open to similar methods for other parts of the dashboard.

**Comment by mrocklin** [comment]
See the commit referenced above ^

**Comment by kindjacket** [comment]
@mrocklin, @TomAugspurger - this is perfect, thank you for such a fast response!  The task stream and profiler were what I was looking for. Closing 👍
