### ISSUE TITLE
BokehRuntimeWarnings after #2747

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2754]
After https://github.com/dask/distributed/pull/2747, I see warnings like

```
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('address', 4), ('dashboard_host', 4), ('dashboard_port', 4), ('nbytes', 4), ('nbytes-color', 4), ('nbytes-half', 4), ('nbytes_text', 4), ('nprocessing', 4), ('nprocessing-color', 4), ('nprocessing-half', 4), ('worker', 2), ('y', 4)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('address', 4), ('dashboard_host', 4), ('dashboard_port', 4), ('nbytes', 4), ('nbytes-color', 4), ('nbytes-half', 4), ('nbytes_text', 4), ('nprocessing', 4), ('nprocessing-color', 4), ('nprocessing-half', 4), ('worker', 2), ('y', 4)
```

probably something with https://github.com/dask/distributed/pull/2747/files#diff-bb0ae02b02c7f964b31a044e6dc83b19L1336

**Comment by mrocklin** [comment]
I'll take a look.  Thanks for raising Tom.

**Comment by ewa** [comment]
Is this still an outstanding issue?  I get get this error while running dask in Jupyter lab, without having consciously requested anything to do with Bokeh or visualization, and I'm at a bit of a loss.

**Comment by quasiben** [comment]
Yes, this is being tracked here: https://github.com/dask/distributed/issues/8022
