### ISSUE TITLE
get_deps fails if any task's value is None

### ISSUE THREAD

**Issue by caseyclements** [dask/distributed#2756]
Consider this simple graph. 

```
dsk = {'two': 2,
       'four': (pow, 'two', 'two'),
       'none': None,
      }

print(dask.get(dsk, keys=list(dsk.keys())))  # (2, 4, None)
print(dask.core.get_dependencies(dsk, key='none'))  # set()
print(dask.core.get_dependencies(dsk, task=dsk['none']))  # ValueError: Provide either key or task
```
Obviously, get_dependencies(dsk, key='none') should be an empty set, and it is.
If one instead passes get_dependencies(dsk, task=dsk['none'], the task is None, and it raises an exception.

This arises when one asks for dask.core.get_deps(dsk) as it calls the following
 
`dependencies = {k: get_dependencies(dsk, task=v) for k, v in dsk.items()}`

It succeeds if this line is rewritten,

`dependencies = {k: get_dependencies(dsk, k) for k in dsk}`

Should I submit a PR?

**Comment by caseyclements** [comment]
Related to #1821

**Comment by jrbourbeau** [comment]
@caseyclements a PR for this is welcome. To follow up on https://github.com/dask/distributed/issues/1821#issuecomment-371266316, I'd recommend defining a `no_default = '__no_default__'` variable to use here in place of a default value of `None`. For an example of this usage, see how the `no_default` variable is used in https://github.com/dask/dask/blob/master/dask/dataframe/core.py

**Comment by martindurant** [comment]
@caseyclements , did you submit a PR for this, or do you intend to?
