### ISSUE TITLE
Key Error:'Distributed'

### ISSUE THREAD

**Issue by BharatAD** [dask/distributed#2762]
After previously experiencing troubles along the lines of #1120, I performed cli installation via pip install dask[complete] which reinstalled dask.distributed.

Currently, when i attempt 
`from dask.distributed import Client`

I get the following error:
`
 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-fb3d5117b89b> in <module>()
      3 from tqdm import tqdm
      4 import dask.dataframe as dd
----> 5 from dask.distributed import Client

D:\Anaconda\lib\site-packages\dask\distributed.py in <module>()
      3 
      4 try:
----> 5     from distributed import *
      6 except ImportError:
      7     msg = ("Dask's distributed scheduler is not installed.\n\n"

D:\Anaconda\lib\site-packages\distributed\__init__.py in <module>()
      3 from . import config
      4 from dask.config import config
----> 5 from .actor import Actor, ActorFuture
      6 from .core import connect, rpc
      7 from .deploy import LocalCluster, Adaptive

D:\Anaconda\lib\site-packages\distributed\actor.py in <module>()
      2 import functools
      3 
----> 4 from .client import Future, default_client
      5 from .compatibility import get_thread_identity, Queue
      6 from .protocol import to_serialize

D:\Anaconda\lib\site-packages\distributed\client.py in <module>()
     45 from tornado.queues import Queue
     46 
---> 47 from .batched import BatchedSend
     48 from .utils_comm import (
     49     WrappedKey,

D:\Anaconda\lib\site-packages\distributed\batched.py in <module>()
      8 from tornado.ioloop import IOLoop
      9 
---> 10 from .core import CommClosedError
     11 from .utils import parse_timedelta
     12 

D:\Anaconda\lib\site-packages\distributed\core.py in <module>()
     18 
     19 from .compatibility import get_thread_identity
---> 20 from .comm import (
     21     connect,
     22     listen,

D:\Anaconda\lib\site-packages\distributed\comm\__init__.py in <module>()
     20 
     21 
---> 22 _register_transports()

D:\Anaconda\lib\site-packages\distributed\comm\__init__.py in _register_transports()
     16 
     17 def _register_transports():
---> 18     from . import inproc
     19     from . import tcp
     20 

D:\Anaconda\lib\site-packages\distributed\comm\inproc.py in <module>()
     13 
     14 from ..compatibility import finalize
---> 15 from ..protocol import nested_deserialize
     16 from ..utils import get_ip
     17 

D:\Anaconda\lib\site-packages\distributed\protocol\__init__.py in <module>()
      3 from functools import partial
      4 
----> 5 from .compression import compressions, default_compression
      6 from .core import dumps, loads, maybe_compress, decompress, msgpack
      7 from .serialize import (

D:\Anaconda\lib\site-packages\distributed\protocol\compression.py in <module>()
    105 
    106 
--> 107 default = dask.config.get("distributed.comm.compression")
    108 if default != "auto":
    109     if default in compressions:

D:\Anaconda\lib\site-packages\dask\config.py in get(key, default, config)
    426         k = canonical_name(k, result)
    427         try:
--> 428             result = result[k]
    429         except (TypeError, IndexError, KeyError):
    430             if default is not no_default:

KeyError: 'distributed'
`

**Comment by quasiben** [comment]
I suspect you still have a corrupted installation can you report back the contents of `~/.config/dask` .  `~/` is the home directory, which for you, might be C:/User/USERNAME or something like that

**Comment by BharatAD** [comment]
Hi you were right, after succesful re-installation, the client is initializing fine.
