### ISSUE TITLE
Futures get cancelled after closing client

### ISSUE THREAD

**Issue by scganterh** [dask/distributed#2766]
Hi,

I need to access the future's state after closing the client. But after closing it, all futures are cancelled, even if they already finished successfully. Is there a reason for that? Can I get the task status in some other way?

Here is a minimal example of my problem:

```python
from dask.distributed import Client

def my_task():
    return 'success!'

client = Client('tcp://xyz:8786')
future = client.submit(my_task)

future.result()
```
'success!'

```python
future
```
<b>Future: my_task</b> <font color="gray">status: </font><font color="black">finished</font>, <font color="gray">type: </font>str, <font color="gray">key: </font>my_task-124c458d922cfecf64955e8b8b5151ed

```python
client.close()
future
```
<b>Future: my_task</b> <font color="gray">status: </font><font color="black">cancelled</font>, <font color="gray">type: </font>str, <font color="gray">key: </font>my_task-124c458d922cfecf64955e8b8b5151ed

Thanks!

**Comment by mrocklin** [comment]
This is expected behavior.  See http://distributed.dask.org/en/latest/memory.html

You can use mechanisms like fire_and_forget, queues, variables, or other coordination primitives to keep futures alive.  https://docs.dask.org/en/latest/futures.html#coordination-primitives

There is also Client.datasets

**Comment by martindurant** [comment]
@scganterh , is that sufficient explanation? I will close this issue if I don't hear otherwise.

**Comment by scganterh** [comment]
Yes, that's sufficient, thank you.
