### ISSUE TITLE
Costarting a dask-scheduler and workers along the Python script in a single job script

### ISSUE THREAD

**Issue by basnijholt** [dask/distributed#2769]
## Question
Is it possible to start a multi node executor from within a jobscript where a Python script is called that has to connect to the excutor?

## Example
For example, this is possible with a `mpi4py.futures. MPIPoolExecutor` like:
```
#!/bin/bash
#SBATCH --job-name adaptive-scheduler-100
#SBATCH --ntasks 60
#SBATCH --output adaptive-scheduler-100-%A.out
#SBATCH --no-requeue

mpiexec -n $SLURM_NTASKS python -m mpi4py.futures run_learner.py  # this script uses `MPIPoolExecutor`
```
However, I cannot use the `MPIPoolExecutor` for my application (see below).
I believe this should be doable with `distributed` too, something like:
```
#!/bin/bash
#SBATCH --job-name adaptive-scheduler-100
#SBATCH --ntasks 60
#SBATCH --output adaptive-scheduler-100-%A.out

temp_scheduler=$(mktemp)
rm $temp_scheduler

srun --n-tasks=1 dask-scheduler --scheduler-file=$temp_scheduler &
srun --n-tasks=58 dask-worker --scheduler-file=$temp_scheduler &  # somehow connect to the scheduler
srun --n-tasks=1 python run_learner.py --scheduler-file=$temp_scheduler &  # this script uses `distributed.Client`
wait
```

This doesn't completely work, unfortunately.

## Why (context)
I wrote a tool called [`adaptive-scheduler`](http://adaptive-scheduler.readthedocs.io) that manages creating and running job scripts for running simulations using the [Adaptive package](http://adaptive.readthedocs.io) on 10k-50k cores. I am using `mpi4py.futures. MPIPoolExecutor`, because I want a executor that I can just start in the same job script as where I run the Python code. However, I am having issues because code that already uses MPI doesn't work with the `MPIPoolExecutor` I am trying to do a similar thing with `distributed` (or [`ipyparallel`](https://github.com/ipython/ipyparallel/issues/370)).

**Comment by jcrist** [comment]
I believe `dask-mpi` should solve your problem, see the documentation here: http://mpi.dask.org/en/latest/batch.html

**Comment by basnijholt** [comment]
Thanks a lot! That is exactly what I needed.
