### ISSUE TITLE
Small doc clarifications needed

### ISSUE THREAD

**Issue by chrish42** [dask/distributed#2771]
I'm reading through the docs of Dask Distributed, and a couple points are unclear to me. I'd be happy to submit a pull request with doc improvements if someone can at least point me in the general direction of answers for my doc questions. (Actually, two of my three questions are yes/no, so at least those two should be quick to answer for someone who knows Dask Distributed well.)

1. In the "Resilience" page, the "Restart and Nanny Process" section doesn't really talk about nanny process. When would I want to use one and why? And when is it not needed?
2. Again in the "Resilience" page, for "Closed Network Connections", point 3: "Data scattered out to the workers is not kept in the scheduler (it is often quite large) and so the loss of this data is irreparable." Is that just about data send via the "scatter()" method? Or is scattering used in a broader sense here?
3. When talking about ClientState in the "Scheduling State", etc. sections, that's an internal object that describes the state of each worker, and which is not related to the Client() object that is instantiated by the user, correct?

Thanks!

**Comment by TomAugspurger** [comment]
1. Nanny seems relatively undocumented. I suppose we could add an API autodoc for it in https://distributed.dask.org/en/latest/worker.html
2. I believe that's correct. May want to double check on `persist`ed collections though...
3. Correct. It's referring to https://distributed.dask.org/en/latest/scheduling-state.html#distributed.scheduler.ClientState (you could link to it with :class:`scheduler.ClientState` if you want to disambiguate.

**Comment by martindurant** [comment]
@chrish42 , are you interested in providing the clarifications as a PR?

**Comment by chrish42** [comment]
Yes. On vacation now, though, so I'll create the pull request beginning of July, if that's okay.

**Comment by martindurant** [comment]
That's fine, just wanting to know how things stand - thanks.

**Comment by chrish42** [comment]
Submitted a first cut at a pull request.

1. I added autodoc for Nanny, but there should probably also be at least a sentence or two there also. Basically, what am I missing out on when I'm not using the nanny to supervise my workers?
2. My understanding is that  data that is `persist`ed will be recreated, because the scheduler knows the Dask task graph that created it, and so can rerun that. But my understanding of the code is still pretty shallow. I think the distinction is between loading data directly (via scatter()) vs. creating data from a Dask task graph (where you can rerun the graph to recreate the data if needed), so I tweaked the doc accordingly. Please confirm, though.
