### ISSUE TITLE
Cancled/Lost Tasks Restarting 

### ISSUE THREAD

**Issue by bybyte** [dask/distributed#2772]
I have noticed some tasks being resumed/retried automatically. I don't have a reproducible setting yet but it seems to happen with canceled tasks. I have also noticed this happening with tasks which have the status "lost" -- today it was the first time I noticed this status BTW and it's not common. 

Under what circumstances are tasks expected to be automatically resumed/retried? Can I explicitly disable this -- I would rather have the tasks error out and resume them manually if needed?

Thank you!

**Comment by mrocklin** [comment]
Once a task is cancelled Dask should not retry it.  If you're seeing
something else then that would be a bug.

**Comment by bybyte** [comment]
After some testing, I think it only happened with futures with the status "lost". We restarted the workers, which is why the futures had that status. I think having the scheduler re-try those futures is expected behavior -- confirmed? 

However, we would prefer futures with status "lost" not to run again. This is particular to our use case. Is it possible to configure this?

**Comment by mrocklin** [comment]
Confirmed.

There is not an easy way to tell the scheduler to not recompute lost
things.  The easiest thing to do here is to remove the future once it is
complete.

**Comment by bybyte** [comment]
Understood. Thank you.
