### ISSUE TITLE
Serve Dashboard over HTTPS

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2775]
Do we have a nice way to serve the dashboard over HTTPS?

https://stackoverflow.com/questions/56602973/dask-bokeh-server-accessd-at-http-scheduler-address8787-can-this-be-run-over

**Comment by mrocklin** [comment]
@jcrist @quasiben

**Comment by jcrist** [comment]
Yeah, this is easy to do if we expose the proper config. Getting valid certs would be on the user though, which may not be easy for them.

**Comment by jeffcbecker** [comment]
Getting valid certs is not an issue for me. Can the dask-distributed developers expose the proper config?

**Comment by mrocklin** [comment]
Yes, that's well in scope.  I've marked this as core maintenance.  We'll discuss it in a weekly meeting tomorrow to see if anyone is around that can handle it.

**Comment by jeffcbecker** [comment]
Thanks!

**Comment by mrocklin** [comment]
FYI @jeffcbecker we discussed this a couple days ago.  @jcrist says it's a pretty easy fix for him, though this week he's out at a wedding.  This should be handled sometime next week.

**Comment by jeffcbecker** [comment]
@mrocklin, thanks!

**Comment by mrocklin** [comment]
cc @jcrist if you're back from vacation

**Comment by jcrist** [comment]
See #2812.

**Comment by mrocklin** [comment]
@jeffcbecker this is in.  See the PR linked above for details.  Please let us know if there are things that could be improved here.
