### ISSUE TITLE
Submitting Graphs from Tasks

### ISSUE THREAD

**Issue by MikeAlopis** [dask/distributed#2777]
Making use of the submitting tasks from tasks features,  I have not found a way to rely on other keys from the graph in the task I submit. Take the following example:

```
from dask.utils_test import add
from dask.distributed import Client

def fun(x):
    from dask.distributed import get_client
    client = get_client()
    res = client.get({'z':(add, 5, 'x')}, 'z')
    return res

dsk = {'x':1, 'y':(fun, 3), 'g':(add, 'x', 'y')}

client = Client()

print(client.get(dsk, 'g'))
```

Gives the error:
```
Function:  add
args:      (5, 'x')
kwargs:    {}
Exception: TypeError("unsupported operand type(s) for +: 'int' and 'str'",)

WARNING:distributed.worker: Compute Failed
Function:  fun
args:      (3)
kwargs:    {}
Exception: TypeError("unsupported operand type(s) for +: 'int' and 'str'",)
```

You get the above error, since it does not recognize what `x` is inside of the `fun(x)` method. With that said, is there a way to refer to the key you defined in `dsk` inside of the `fun(x)` method?

Maybe perhaps using `.submit()` though I did not have success with that yet... Thanks!

**Comment by mrocklin** [comment]
You would make a dask.distributed.Future with the key and then include that
future in the graph instead of the key.

In general we tend to recommend the Futures API to users instead of the raw
graph API.  It handles a lot of these things for you.
