### ISSUE TITLE
Missing prometheus dependency

### ISSUE THREAD

**Issue by sublinus** [dask/distributed#2778]
Currently the dependency for prometheus_client is only available in the dev-requirements.
Should it be included by default?

**Comment by mrocklin** [comment]
It's not required for things to work.  It's optional.

**Comment by sublinus** [comment]
I see that it might be optional for some people, but it is required for the /metrics endpoint to work. The requirements are missing bokeh as well, which is required for the dashboard to work. Of course if you do not intent to use the dashboard, or the metrics it would be optional.

**Comment by mrocklin** [comment]
Right. Exactly.

**Comment by sublinus** [comment]
So you will not add them in the future?

**Comment by mrocklin** [comment]
No, they are not required dependencies.  If we add them to requirements
then it becomes very difficult to install Dask without installing these as
well.  We do not want that.

**Comment by sublinus** [comment]
Alright, makes sense.
