### ISSUE TITLE
documentation for resources kwarg in Client.compute/submit

### ISSUE THREAD

**Issue by IPetrik** [dask/distributed#2780]
The methods `Client.compute` and `Client.submit` accept the keyword argument `resources` but this is not documented in the API documentation.

**Comment by TomAugspurger** [comment]
Looks like `Client.compute` includes the keyword argument, it's just undocumented: https://github.com/dask/distributed/blob/a511f0ea480d7305d86c6439213c3cf3a6d95dc4/distributed/client.py#L2581. A PR documenting that would be welcome.

For `Client.submit` we might want to make all of these

https://github.com/dask/distributed/blob/a511f0ea480d7305d86c6439213c3cf3a6d95dc4/distributed/client.py#L1397-L1405

regular keyword arguments. Though I may be missing a reason to handle them as `**kwargs`.

@IPetrik are you interested in working on some or all of this?

**Comment by IPetrik** [comment]
@TomAugspurger Sure thing - I'll work on it and submit a PR.

**Comment by martindurant** [comment]
Let us know if you need any help with that

**Comment by mrocklin** [comment]
Adding in kw-only arguments here : https://github.com/dask/distributed/pull/2814

**Comment by IPetrik** [comment]
Added documentation: [#2851](https://github.com/dask/distributed/pull/2851)

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/2851
