### ISSUE TITLE
Workers dying because of exceeded memory budget. Nothing suggests so on /workers dashboard

### ISSUE THREAD

**Issue by kindjacket** [dask/distributed#2789]
Hi,

I'm running tasks from inside tasks. I have followed the following documentation http://distributed.dask.org/en/latest/task-launch.html.

My process is as such I run simulations in parallel. This process runs over multiple steps as I search the solution space and optimize.
Simulations are done in parallel using
``` python
elements_in_partitions = math.ceil(len(input_list) / dask_workers)
chunks = [
            delayed(part) for part in partition_all(elements_in_partitions, input_list)
        ]
b = db.from_delayed(chunks)
results = b.map(function, *args).compute()
```

I run these optimizations in parallel using
``` python
futures = client.map(method, input_list)
for future in as_completed(futures):
        result = future.result()
```

For smaller input datasets the process runs perfectly fine but for larger input datasets the process stops almost immediately. The cited issue being 
```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker process 2969 was killed by signal 15
```

However, I have watched the dashboard for `/workers` and can't see any of the workers using significant memory. See image below.  When ordering by memory the workers with the highest memory usage are only using around 30% of memory.

![image](https://user-images.githubusercontent.com/7778402/59805413-19684100-92a6-11e9-9a55-4f1d49fcf59e.png)

Any ideas why workers with high memory usage are not represented here?

I'm sorry I don't have an easy toy example right now.

Running python 3.7.3 and dask distributed v1.28.1 on a 72 Core Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1040-aws x86_64) machine.

**Comment by mrocklin** [comment]
We only update that plot every few hundred milliseconds.  Perhaps your
method quickly allocates a lot of data?

**Comment by kindjacket** [comment]
So the theory is that the memory explodes so quickly that the dashboard fails to capture it.  I guess that makes sense.

After digging into the memory allocation, I can see that there's a ~50MB object passed to each simulation from the worker node running the optimization. When it has to create 100 simulation tasks, I would guess it has to serialize and deserialize that object. I would imagine that that then creates a significant load on the memory for that worker.

**Comment by martindurant** [comment]
What you say is plausible, but it's hard for us to be sure. You could try changing the size and number of objects you are passing around, to see what behaviour you see, and there are of course various tools around to investigate memory use within a single process that might help you with the former of these.

**Comment by kindjacket** [comment]
Okay. Going to close. Thanks for the help! The answer to the specific issue title is that there is a delay in the dashboard. Therefore,  it may not represent everything going on a given point in time. My other memory issues are separate, and I will work to figure those out.
