### ISSUE TITLE
computing time for each process on a thread

### ISSUE THREAD

**Issue by AakashGfude** [dask/distributed#2795]
Hello, 
I am using dask distributed and want to compute time for each individual process, but I am having a hard time computing that. 
My setup at present is :- 

#### code for creating a client
```
self.client = Client(processes=False, threads_per_worker = self.threads_per_worker, n_workers = self.n_workers)
c = Counter(SchedulerPlugin)
self.client.scheduler.add_plugin(c)
```

#### counter class as a scheduler plugin to add additional information of each task
```
class Counter(SchedulerPlugin):
       def __init__(self,scheduler):
          self.scheduler = scheduler

      def transition(self, key, start, finish, *args, **kwargs):
          ts = self.scheduler.tasks[key]

      def restart(self, scheduler):
          self.counter = 0
```

#### running a loop here and passing each notebook to client.submit as 'nb'
```
    starting_time = time.time()
    future = self.client.submit(*some task here*, nb, {"metadata": { "start_time" : starting_time}})
    self.futures.append(future)
```

#### checking the completion of each future and recording the time by using the start_time key of the metadata of each notebook which was passed to it in the block above
```
for future, nb in as_completed(self.futures, with_results=True):
    passed_metadata = nb[1]['metadata'] 
    notebook_time = time.time() - passed_metadata['start_time']
```

This notebook time gives time taken from the moment it was added to the scheduler, to the moment it was completed. It also takes into account the time is waited for a worker. 
I wish to only get the time each notebook took in processing on a thread. Like the one we can see in bokeh.

Any directions on how I can achieve that? 
Thanks

**Comment by mrocklin** [comment]
I think that you're looking for
https://docs.dask.org/en/latest/futures.html#distributed.Client.get_task_stream

**Comment by AakashGfude** [comment]
Thank you for this. works smooth now.
