### ISSUE TITLE
Add compatibility for --no-bokeh option

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2799]
OK with this before 2.0 @mrocklin? Making a PR now in case (Pangeo specifies --no-bokeh).

**Comment by mrocklin** [comment]
Yeah, I wasn't sure how best to provide a message around a True/False flag. In Python I would set this to None and then raise if it was not None.

I'm comfortable with adding it back in as long as it raises an annoying warning.

**Comment by TomAugspurger** [comment]
> In Python I would set this to None and then raise if it was not None.

I was just running into that. I think we're fine. The only weird case is if the user does `--no-bokeh --dashboard`, or something like that, to raise. There's not a clean way to check if dashboard is explicitly set. You can do `default=None`, but that messes with other things. So I think we'll just take `--no-bokeh` in that case (after warning).
