### ISSUE TITLE
Is it possible to get into a task resubmission loop?

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#280]
I am finding sometimes it looks like I can get stuck waiting for a task that never finishes, I see logs like this:

~~~
distributed.worker - WARNING - Could not find data for ['aggregate-355f7592-270a-4b7a-acc4-afd53476e263']
~~~

which seems to be closely followed by a "re-execution" of a task. Is this a feature? worth noting that I see this when using a distributed scheduler in dask, not when it is local.

**Comment by mrocklin** [comment]
Getting stuck in any way is definitely a bug.  

If it can't find data then possibly the worker with the data has died?  Are your workers all healthy?  I run into problems like this when some of my workers run out of distributed memory.

**Comment by mrocklin** [comment]
I don't really expect this, but are you able to provide an example that I can replicate?

**Comment by nfaggian** [comment]
I can share the basic pattern I am using, which is this:

~~~

from dask.delayed import delayed

@delayed
def load(json_file):
    # mutate json data 
   return json_dict

@delayed
def run(json_dict):
   # os.subprocess call to execute a simulator
   # mutate json dict 
   return json_dict

@delayed
def normalize(json_dict):
   # perform some data manipulation (data pointed to in dict)
   # mutate json dict 
   return json_dict

@delayed 
def aggregate(data):
     return data

workflow = aggregate([ normalize(run(load(x))) for x in json_file_list])

~~~

I guess this is a good opportunity to ask for advice too -- is the way I am using delayed a bit flawed. It seems really easy to break a large task if any one of the workflow steps breaks.

**Comment by mrocklin** [comment]
Nothing here seems particularly scary.  I wouldn't recommend mutating inputs, especially if multiple functions rely on the same data, but that doesn't appear to be the case here.

Are your machines running out of RAM by any chance?

**Comment by nfaggian** [comment]
The machines are not running out of ram. Was wondering if it was anything to do with how I am executing the simulators: 

~~~
def execute_command(cmd, prefix=None, log_output=True):
    """
    Executes a system call and logs output.
    """

    try:
        LOG.info("Executing: {0}".format(cmd))
        output = subprocess.check_output(
            cmd, shell=True, stderr=subprocess.STDOUT)
        if log_output:
            LOG.info("Output: \n {0}".format(
                "\n> ".join([""] + output.decode().split("\n"))))
    except subprocess.CalledProcessError as ex:

        # An exception occurred, capture log output.
        log_content = None
        if prefix is not None:
            log_content = log_files(prefix)
        # Raise the runtime error, which should propagate out.
        raise RuntimeError(ERROR_MESSAGE.format(cmd,
                                                ex.output.decode(),
                                                log_content))

~~~

**Comment by nfaggian** [comment]
Also should say that I do a deep copy of the input prior to mutation so the output is always something "new".

**Comment by mrocklin** [comment]
Do you see other evidence of workers dying for some reason?

**Comment by nfaggian** [comment]
Don't see the workers dying...

**Comment by nfaggian** [comment]
What do you recommend to make the task chain resilient to failure? for example if "a" causes load to fail, "b" will not be computed because of an exception being raised in load. 

```
workflow = aggregate([ normalize(run(load(x))) for x in (a, b)])

```

**Comment by mrocklin** [comment]
Oh, sorry quick question, when you say it "locks" do you mean that the scheduler no longer responds to new computations, e.g. `e.submit(lambda x: x, 1).result()` hangs?  Or do you mean that your possibly failed computation is not available?  Perhaps my question more generally is "in what way does it lock?"

**Comment by mrocklin** [comment]
Yeah, so when you `compute(workflow)` you're telling the scheduler that you only want the ouptut of your entire computation.  Once one task errs it's clear that it's not going to be able to deliver the entire output and so it bails.  If what you actually want is all of the results to `normalize` say, when you should compute those

```python
e.compute(*[normalize(run(load(x))) for x in (a, b)])
```

And then it'll run what it can to produce those outputs, even if some of them fail.

**Comment by nfaggian** [comment]
Sorry I guess I am mixing two things up here the resubmission loop seems to be a case of the scheduler re-injecting tasks that have been lost? I think that your comment just now might give me a way around a failing task.

I could just filter out failed tasks and report them back to my "user" -- me staring at a notebook :-)

**Comment by nfaggian** [comment]
Am I doing this part wrong?
~~~
TypeErrorTraceback (most recent call last)
<ipython-input-14-aaafb8309fc0> in <module>()
      1 executor = Executor('scheduler:8786')
----> 2 m = executor.compute(*[normalize(run(load(x))) for x in simulations])
      3 progress(m)

TypeError: compute() takes from 2 to 3 positional arguments but 768 were given
~~~

**Comment by mrocklin** [comment]
Yeah, so a common pattern is the following:

```python
futures = e.compute(dask_delayed_values)

from distributed import wait
wait(futures)

futures = [f for f in futures if f.status == 'finished']
```

When you first said that things lock up I interpreted that as "you have successfully deadlocked the scheduler" which wouldn't be entirely shocking but also hasn't happened in several months.  I'm quite curious to know if this has occurred.  

Seeing your most recent comment I apologize I led you astray.  See example in this comment.

**Comment by mrocklin** [comment]
To explain the `Could not find data` error message for some reason the scheduler thinks that that data exists on some worker in the network, but another worker who is trying to collect it isn't able to find it on any of his buddies.  He complains to the scheduler which then goes and recompute the result.  

I've only seen this happen in two cases:

1.  A worker unexpectedly dies
2.  In the recent past the scheduler thought that it should delete this data (no one wanted it).  It sent out a message to delete this data.  For internal scheduler reasons this message was low-priority and so was delayed by about a second.  In the interim someone showed up that did want the data but, unfortunately the worker has just now gotten the delete message and so deletes otherwise valuable data

In either case the system recovers by recomputation.

**Comment by nfaggian** [comment]
Does a single failed task break the progress bar?

**Comment by mrocklin** [comment]
The notebook progress bar, yes.  Web interface progress bar no.

**Comment by nfaggian** [comment]
A bit sad - the notebook progress bar is really useful to me, could it just change colour (to red) if a sub-component fails?

**Comment by mrocklin** [comment]
Yeah, that seems reasonable to change.  This is probably something that I won't prioritize for at least a week and possibly longer though (conference season, non-critical).

Any chance I can interest you in playing around?  The relevant code is here.  You might even find other ways in which you could make it more useful to you:

https://github.com/dask/distributed/blob/master/distributed/diagnostics/progress.py#L226-L231
https://github.com/dask/distributed/blob/master/distributed/diagnostics/progressbar.py#L113

**Comment by nfaggian** [comment]
Sure - it is about time I tried to help out, rather than taking advantage of your good work!

**Comment by frol** [comment]
I have seen the following messages quite often (they happen once every 30 minutes during intensive experimentation) on my little cluster and even on one single laptop hosting the scheduler, the worker, and the executing code:

```
distributed.worker - INFO - Deleted 19 keys
distributed.worker - INFO - Deleted 13 keys
distributed.worker - WARNING - Could not find data for ["('getitem-1c0318d594d052d0143baa68e871400b', 2)"]
distributed.scheduler - INFO - Recover missing ('apply-b83661773bb310a60dda6b52ca7094b3', 2)
distributed.worker - INFO - Deleted 16 keys
distributed.worker - WARNING - Could not find data for ["('getitem-1c0318d594d052d0143baa68e871400b', 1)"]
distributed.scheduler - INFO - Recover missing ('apply-b83661773bb310a60dda6b52ca7094b3', 1)
```

(I have a scheduler and a worker running on one terminal in background, so we can see the order of the messages and notice that the worker missed `getitem`, but the scheduler recovers `apply`. Isn't it weird?)

I'm sure neither the worker nor executor failed, but after a while, I start seeing these messages and eventually my computations just hang (0% CPU load, Bokeh status page reports that a few tasks are still waiting for something). If I interrupt my computations I see that it is just sitting waiting for some results:

```
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/executor.py", line 1054, in get
    results = self.gather(futures)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/executor.py", line 767, in gather
    return sync(self.loop, self._gather, futures, errors=errors)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/utils.py", line 114, in sync
    e.wait(1000000)
  File "/mnt/storage/miniconda3//lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/mnt/storage/miniconda3//lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
```

My only guess at the moment is that it might be related to the workflow I have:

1. I often restart my Jupyter Notebook to start from scratch, and I also actively run code from the terminal in a batch processing mode.
2. My code crashes (just regular Python exceptions, not Segfaults) sometimes, so this may break some machinery on workers.

**Comment by mrocklin** [comment]
I suspect that this is a separate issue to what came up here.

You may find the refactor in https://github.com/dask/distributed/pull/398 valuable.  The internals have been reworked and should make it much easier to track things down.  Issues likely still exist, but cleaning them up should now be easier.

**Comment by caseyjlaw** [comment]
I am seeing a similar behavior as described above. I've built a graph that does a one-to-many in a few stages. So one input turns into 10 and that turns into 20 futures. Many of these functions are written in numba and return a numpy array.
Viewing the web UI, at some point in the middle of that growth in the number of jobs scheduled, it stops scheduling jobs and starts again from the first task.

The scheduler has some messages about "recover missing *jobname*"

```
distributed.scheduler - INFO - Lost all workers
distributed.utils - ERROR - global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/users/claw/miniconda/lib/python2.7/site-packages/distributed/utils.py", line 206, in log_errors
    yield
  File "/users/claw/miniconda/lib/python2.7/site-packages/distributed/scheduler.py", line 1572, in worker_stream
    except (StreamClosedError, IOError, OSError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
```

I am using distributed v1.11.3 in Python 2.7.12. Conda install most dependencies, but pip install distributed.

**Comment by mrocklin** [comment]
@caseyjlaw I suspect that your problem is unrelated.

You have two problems

1.  Something is killing your workers, perhaps not enough RAM?  Perhaps a segfaulting function?
2.  There was a Python 2 compatibility error in the last version.  This has been fixed in master

        pip install git+https://github.com/dask/distributed.git --upgrade

    or wait a week and then pip install again once we release

**Comment by caseyjlaw** [comment]
@mrocklin Ah, yes, thanks. I can see that it completes if I reduce the memory footprint of the computation.

I didn't think of this partly because the web UI did not show any large increase in memory usage. Is that worth investigating as a potential new issue?

**Comment by mrocklin** [comment]
Displaying memory use per worker and per task group would be a nice addition.  Raising a new issue sounds good.

**Comment by caseyjlaw** [comment]
A quick update: I believe my issue is indeed related to workers trying to access missing data. Thanks to the new per-worker memory display, I can see that my workers are not overworked.
I am working to find a minimum failing example, but it is slippery and may take me a bit.

**Comment by mrocklin** [comment]
This issue has gotten off track from the original topic.  I'm going to close for now.  For lingering topics please re-raise new issues if the problem persists.
