### ISSUE TITLE
setup.py should use python_requires

### ISSUE THREAD

**Issue by dwhswenson** [dask/distributed#2805]
The `setup.py` in `dask.distributed` doesn't have a `python_requires` defined (`dask` does have one). This leads to errors when pip-installing `distributed` on projects that still use (or test against) Python 2.7. It tries to install `distributed` 2.0, which isn't compatible with Python 2.

With my installation procedure for a project on Travis, pip gives a warning about the inconsistency, then errors when I `import distributed`. (https://travis-ci.org/dwhswenson/contact_map/jobs/550446504) On my local machine, creating an environment with Python 2.7 and pip, then running `pip install distributed` raises an error that it can't find dask>=2.

**Comment by cpaulik** [comment]
Same as https://github.com/dask/distributed/issues/2804 :smile:

**Comment by TomAugspurger** [comment]
Let's move to #2804.
