### ISSUE TITLE
[feature request] Dashboard: change time window of tasks graph

### ISSUE THREAD

**Issue by stsievert** [dask/distributed#2809]
**Summary**
I think it'd be useful to change the time window on the task graph (e.g., zooming). For me at least, this would provide better debugging information.

**Details**
I find the deletion of tasks from the Bokeh dashboard to be limiting sometimes, especially when individual jobs take long to run. At times, the task graph will be wiped clean and start afresh. I suspect this is by design to show the *current* state of Dask.

This information is retained, and so it the plot. The plot below shows briefly shows when `/tasks` is first loaded:

<img width="380" alt="Screen Shot 2019-06-26 at 7 50 01 PM" src="https://user-images.githubusercontent.com/1320475/60225268-96cb1d00-9875-11e9-9736-70908a4bf513.png">

This plot is updated to show the same graph as `/status` when a new task gets scheduled.

This plot is useful to me because it lets me see the history of the computation, when I started the computation and when individual jobs were scheduled (and the names of those jobs!). For me at least, this is useful debugging information, especially if I could zoom in to different regions.

**Comment by mrocklin** [comment]
> I think it'd be useful to change the time window on the task graph (e.g., zooming). For me at least, this would provide better debugging information.

You should be able to zoom using either of the bokeh tools in the upper right.  


![Uploading Screen Shot 2019-06-27 at 10.41.46 AM.png…]()


> I find the deletion of tasks from the Bokeh dashboard to be limiting sometimes, especially when individual jobs take long to run. At times, the task graph will be wiped clean and start afresh. I suspect this is by design to show the current state of Dask.

It wipes if there is a 20s gap between tasks I think.  You could make this configurable if you were interested.  You can also use the `get_task_stream` context manager to collect a chunk of your computation.


Was this your question?

**Comment by stsievert** [comment]
Yup! I'm closing this issue. I should have realized earlier – of course this would be configurable and enabled by default. Thanks for the tip.

I'm aware of `get_task_stream` but these tools will be easier to use and
