### ISSUE TITLE
Scheduler's TCPServer fails to handle 3k concurrent connection establishment requests

### ISSUE THREAD

**Issue by tddg** [dask/distributed#2820]
We are trying to setup a Dask cluster on a 3-thousand node cluster. We did some preliminary scalability micro-benchmarking by following the examples provided on http://matthewrocklin.com/blog/work/2017/07/03/scaling. We observed extremely long latencies (3 - 7 seconds) when thousands of workers were trying to establish a connection to the scheduler simultaneously. We suspect it is the high concurrency at the worker side that causes significant resource contention at the scheduler side, given that the scheduler is listening on a single port with a single core. 

We were wondering if this issue has occurred at such a scale, and if there are any benchmarking results about the scalability of the scheduler's TCP server (both connection handling and request processing).

**Comment by quasiben** [comment]
@tddg very interesting!  Is it possible to share more about the workload you were running and/or the task graph ?  There are some notes on efficiency on the dask website which may be worth consulting https://distributed.dask.org/en/latest/efficiency.html#efficiency

Some additional questions:
- How did you go about setting up the cluster ? 
- What is the worker configuration ?  nthreads/ncores ?

**Comment by jrbourbeau** [comment]
Just checking in here, @tddg can you provide any of the additional information @quasiben mentioned?

**Comment by jrbourbeau** [comment]
Closing due to lack of reply. Feel free to re-open if you'd like to continue
