### ISSUE TITLE
Explicit, even distribution of partitions/chunks

### ISSUE THREAD

**Issue by NickLeaf** [dask/distributed#2849]
I'm working on an application which needs one chunk/partition of data per worker in a Dask-MPI cluster. Dask tends to distribute my data entirely to one rank, though, and I haven't been able to find a way to make it distribute the data evenly. `Client.reblance()` appears like it would do what I need, but printing from each rank indicates that all chunks/partitions are being run on the same rank. Is there a way to force Dask to distribute data evenly? If not, ought there be?

The code to reproduce this (running the dask-mpi cluster and running a task on each array block) looks like:
```
mpiexec -n 1 dask-mpi --scheduler-file scheduler.json --no-nanny & mpiexec -n $N dask-mpi --scheduler-file scheduler.json --no-nanny --no-scheduler
```
```python
from dask.distributed import Client, Sub, Pub, fire_and_forget
client = Client(scheduler_file='../scheduler.json', set_as_default=True) #Connect to the Dask scheduler

N = len(client.scheduler_info()['workers']) #Get the number of workers in our cluster

import numpy as np
npvol = np.array(np.fromfile('/home/nleaf/data/RegGrid/Vorts_t50_128x128x128_f32.raw', dtype=np.float32))
npvol = npvol.reshape([128,128,128])

import dask.array as da
ar = da.from_array(npvol).rechunk([npvol.shape[0], npvol.shape[1], npvol.shape[2]/N])

def test(ar):
    from mpi4py import MPI
    rank,size = MPI.COMM_WORLD.Get_rank(), MPI.COMM_WORLD.Get_size()
    return np.array([rank], ndmin=3, dtype=np.int)

client.rebalance()
print(client.persist(ar.map_blocks(test, chunks=(1,1,1))).compute())
```
The output I expect after `client.rebalance()` would be some some permutation of all of the ranks. Instead, the output almost always indicates that the function is run on just one rank.

 I _am_ able to use a workaround for Dask dataframes via `Dataframe.get_partition(rank)` and calling the function with `client.map()`. That's fairly clunky, though, and I haven't found a similar solution that works for Dask array.

**Comment by quasiben** [comment]
@NickLeaf the docstring says `rebalance` distributes keys so that the bytes are distributed evenly amongst the workers -- is this in fact the case for you ?  

Could you try using `scatter` ?  In theory, this should distribute evenly

**Comment by NickLeaf** [comment]
> @NickLeaf the docstring says `rebalance` distributes keys so that the bytes are distributed evenly amongst the workers -- is this in fact the case for you ?

That's what I expected `rebalance` to do, but all of the data stays on a single rank (or, occasionally, one other rank). This is a fairly small dataset, only 8 MB total and about 2 MB per chunk; are there any heuristics that limit when Dask decides to move data instead of keep it where it is?

> Could you try using `scatter` ? In theory, this should distribute evenly

I get the same result if I replace the last two lines with:
```python
ar2 = client.scatter(ar).result()
print(client.persist(ar2.map_blocks(test, chunks=(1,1,1))).compute())
```

**Comment by mrocklin** [comment]
You load all of your data on a single process into a numpy array.  Perhaps you wanted to read in parallel instead?

    npvol = np.array(np.fromfile('/home/nleaf/data/RegGrid/Vorts_t50_128x128x128_f32.raw', dtype=np.float32))

Then you call `from_array`, but nothing has happened yet, because Dask is lazy

    ar = da.from_array(npvol).rechunk([npvol.shape[0], npvol.shape[1], npvol.shape[2]/N])

Then you call rebalance, but there isn't any data anywhere, so nothing happens

    client.rebalance()

Then you trigger computation, but the data is all on one machine, so it stays there.

    print(client.persist(ar.map_blocks(test, chunks=(1,1,1))).compute())

perhaps you wanted to persist your data so that it is actually on the cluster and then call rebalance on that object afterwards?

**Comment by NickLeaf** [comment]
> You load all of your data on a single process into a numpy array. Perhaps you wanted to read in parallel instead?

I definitely would like to read in parallel, but I'm not sure how to read chunks of a raw binary file in parallel. 

> Then you call `from_array`, but nothing has happened yet, because Dask is lazy
> 
> Then you call rebalance, but there isn't any data anywhere, so nothing happens
> 
> Then you trigger computation, but the data is all on one machine, so it stays there.
>
> perhaps you wanted to persist your data so that it is actually on the cluster and then call rebalance on that object afterwards?

This shows where I was thinking about things incorrectly. I had some notion that Dask would assign unloaded chunks to processors before they were ever loaded. Per your suggestions, I changed the code to:
```python
ar = da.from_array(npvol).rechunk([npvol.shape[0], npvol.shape[1], npvol.shape[2]/N]).persist()
client.rebalance()

def test(ar):
    from mpi4py import MPI
    rank,size = MPI.COMM_WORLD.Get_rank(), MPI.COMM_WORLD.Get_size()
    return np.array([rank], ndmin=3, dtype=np.int)

client.compute(ar.map_blocks(test, chunks=(1,1,1))).result()
```
And this now creates the expected result. I appreciate the help!
