### ISSUE TITLE
Support workers= in persist and compute

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#285]
Sometimes we want to restrict tasks to land on a subset of our cluster.

**Comment by martindurant** [comment]
Noticing that in some existing functions (scatter), workers is a list of (host, port), i.e,. specific processed, but in others (submit) it is hosts only. Is there a preference for persist and compute? 
Should submit be brought into line with scatter, or vice-versa?

**Comment by mrocklin** [comment]
We want to support just hostname when we think about restrictions based on hardware (e.g. does this machine have a GPU or access to particular blocks of HDFS data.)  We want to support hostname+port when we think about particular worker processes, perhaps to target specific memory spaces.  We also often want to support name aliases like `'alice'` that workers may have.

In principle all functions probably want to support all cases.  I don't currently know how comprehensive this is.  I suspect that most functions on the scheduler handle this logic on their own, which probably isn't best.
