### ISSUE TITLE
Issue switching between synchronous and asynchronous mode with Client

### ISSUE THREAD

**Issue by pierreglaser** [dask/distributed#2853]
Hi, 
I played around with `distributed` to solve joblib/joblib#852, especially the ability of `Client` to switch from sync to async mode.

The documentation seems to state that it is possible:
https://github.com/dask/distributed/blob/e5ec8daab0d2b30702cfce4acb6259c10aef8e05/docs/source/asynchronous.rst#L47-L58

But the following script just hangs forever without outputing anything.
```python
from tornado.ioloop import IOLoop
from distributed import Client


async def f():
    results = client.map(lambda x: x, [(1,), (2,)])
    results = await client.gather(results, asynchronous=True)
    return results


if __name__ == "__main__":
    client = Client()
    res = IOLoop.current().run_sync(f)
    print("final result: {}".format(res))
```
When using `Client(asynchronous=True)` instead, the scripts runs fine.
Is it expected behavior?

Using python3.7, distributed master, tornado 6.0.3

**Comment by mrocklin** [comment]
You need to run `f` in the IOLoop that is created by the `Client`.  Tornado's `IOLoop.current` function returns the IOLoop for the current thread, while the `Client`, when running in synchronous mode has to make an IOLoop on a different thread.

Probably you want the following:

```python
from tornado.ioloop import IOLoop
from distributed import Client


async def f():
    results = client.map(lambda x: x, [(1,), (2,)])
    results = await client.gather(results, asynchronous=True)
    return results


if __name__ == "__main__":
    client = Client()
    res = client.sync(f)  # <<---- changed line
    print("final result: {}".format(res))
```

**Comment by pierreglaser** [comment]
Thanks a lot -- sorry for the noise. Closing.

**Comment by mrocklin** [comment]
It was a good question, and it's nice to have a public record of it.
Thanks.

**Comment by dhirschfeld** [comment]
Perhaps #2293 might have helped avoid some confusion?
