### ISSUE TITLE
PBS Issues

### ISSUE THREAD

**Issue by jlevy44** [dask/distributed#2856]
Hey there!

I've set up a data pipeline as follows, powered by dask.

1. Data in -> save to zarr; this works fine
2. Access random chunks of the saved array after loading the zarr, and find some stats on each chunk, put this into delayed then run compute at the end on a list of delayed

I'm operating in a PBS compute environ, running the task interactively in the test node seems to work, but when I submit a job with an embedded python script that tries to run this compute statement, my job half the time gets killed, which I suspect may be due to leaking memory? https://github.com/dask/dask-jobqueue/issues/178

Can you assist me with this issue please? I've been scratching my head over this for a few days. Pretty much there's low memory usage when I run the command in my test node (~3GB) then my job is killed when I submit it with the same parameters, and in the job I am no longer calling a Client, just running compute.

**Comment by jlevy44** [comment]
I'm submitting PBS jobs with local clusters embedded in the jobs.

**Comment by jlevy44** [comment]
I also submitted without the local cluster and just called dask with multithreading, and obtained this error.

I ran single threaded and it was fine.

**Comment by jlevy44** [comment]
I've left some more information here: https://github.com/dask/distributed/issues/2328

**Comment by jlevy44** [comment]
I'm going to go ahead and close this issue. I spoke with the system admin at my institution and we were able to resolve with some modifications to the scheduler.

**Comment by mrocklin** [comment]
Great.  I'm glad to hear it.  My apologies that no one was able to help you
move things along on this side.
