### ISSUE TITLE
Gracefully restart a worker from a nanny

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2861]
A common request is that people want to restart a single worker into a clean state.  This might be to refresh the imported software environment or to clear out leaked memory.  To do this cleanly a worker needs to stop accepting work, offload its data to peers, and then close itself and let the nanny restart it.  We can do all of these steps today, but it's a bit of a manual process.  It would be nice to make it easier.

As an example use case, long-running Dask workers (days or weeks) may want to refresh themselves every hour

```
dask-worker scheduler-address:8786 --refresh-restart 1h
```

**Comment by filmor** [comment]
This is also connected to #1823 in my opinion (i.e. allowing explicit restart via a `Client`).

AUtomatic restart would be nice as well, though :)
