### ISSUE TITLE
Bokeh downstream tests no longer work

### ISSUE THREAD

**Issue by bryevdv** [dask/distributed#2863]
The Bokeh tests have moved I guess? The test reports:

> +py.test distributed/bokeh
> ============================= test session starts ==============================
> platform linux -- Python 3.6.8, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
> rootdir: /home/travis/miniconda/envs/testenv/lib/python3.6/site-packages
> plugins: metadata-1.8.0, cov-2.7.1, xdist-1.28.0, forked-1.0.2, html-1.20.0
> collected 0 items                                                              
> ========================= no tests ran in 0.01 seconds =========================
> ERROR: file not found: distributed/bokeh

Here are the files to update:

* install: https://github.com/bokeh/bokeh/blob/master/scripts/ci/install.downstream
* test: https://github.com/bokeh/bokeh/blob/master/scripts/ci/test.downstream

cc @mrocklin @jcrist (not sure who else to ping these days)

**Comment by mrocklin** [comment]
We've moved the distributed/bokeh directory to distributed/dashboard
