### ISSUE TITLE
SpecCluster error when removing workers

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2869]
When attempting to scale down a `SpecCluster` I'm getting the following error.

```python-traceback
distributed.utils - ERROR - 'Worker' object has no attribute 'worker_address'
Traceback (most recent call last):
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/utils.py", line 714, in log_errors
    yield
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/adaptive.py", line 176, in _retire_workers
    await f
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/spec.py", line 324, in scale_down
    if v.worker_address in workers:
AttributeError: 'Worker' object has no attribute 'worker_address'
```

**Comment by mrocklin** [comment]
The `worker_address` attribute was originally used to support `Nanny` objects, which have both their own address, and a reference to their worker's address.  The `Worker` object aliases address to worker_address.

https://github.com/dask/distributed/blob/586ead997dc72c1b7170dbf30af253257f53b1fc/distributed/worker.py#L676-L679

I'm not sure about the best way to handle this generally.  The easy thing to do is to requie that `worker_address` is on anything that we put into SpecCluster (we should probably start maintaining a formal interface for what is expected) though I'll admit that this seems a little kludgey.

**Comment by jacobtomlinson** [comment]
I agree a `SpecProcess` interface would be useful for things like this. There are a couple of other things I have come across which should go in there too.

**Comment by jacobtomlinson** [comment]
See #2874
