### ISSUE TITLE
[Errno 51] Network is unreachable

### ISSUE THREAD

**Issue by jbednar** [dask/distributed#2883]
Is it intended that `distributed` can't even be imported, when there is no network?  If I turn off my wifi (e.g. on an airplane), I get:

```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import distributed
/Users/jbednar/miniconda3/envs/holoviz-tutorial/lib/python3.6/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 51] Network is unreachable
  RuntimeWarning,
>>> distributed.__version__
'2.0.1'
```

Sure, some features of distributed won't be available without a network, but is it appropriate not to be able to even import it without getting a warning?  My specific situation is that `distributed` is imported by [Datashader](http://datashader.org), whether or not a particular user happens to be using a distributed scheduler, and it's very confusing for users to get such a warning message in general unless they are actively trying to use something that accesses the network.

**Comment by mrocklin** [comment]
> Is it intended that distributed can't even be imported, when there is no network? 

Obviously the answer to this is "no", right?  Who would intend a limitation like that?

**Comment by mrocklin** [comment]
It looks like the offending call is here:

https://github.com/dask/distributed/blob/f16ee17bc9481f2d9e19479f390d4248fc7c83a3/distributed/comm/inproc.py#L37

I think that it would probably be safe to catch warnings around that lilne.  It may also be safe for that value to always be `127.0.0.1`, though I'm not sure, someone would have to check.

**Comment by jbednar** [comment]
> Who would intend a limitation like that?

Not me, but people can have very different priorities, so I didn't want to assume... :-)

**Comment by mrocklin** [comment]
@jbednar are you or anyone around interested in helping out with this?

**Comment by jbednar** [comment]
Sure; I'll give it a try.
