### ISSUE TITLE
Couroutine scheduler.start was never awaited

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#2895]
I noticed that with the latest master there have been some changes and I can no longer do this to run the scheduler (or similar for worker):

```
scheduler=Scheduler()
scheduler.start()
loop=IOLoop.current()
loop.start()
```

because I get a warning:
`Runtimewarning: couroutine 'Scheduler.start' was never awaited scheduler.start()`

Any suggestions what changes have been made since last month that would cause this? many thanks

**Comment by mrocklin** [comment]
Thanks for the reminder.  Fixed in https://github.com/dask/dask/pull/5163
