### ISSUE TITLE
[UI][FEATURE] Invalid worker or task keys should return 404 instead of 500 HTML status code

### ISSUE THREAD

**Issue by rs2** [dask/distributed#2910]
E.g. http://host:8787/info/task/foobared.html returns `500: Internal Server Error`.

Should instead return a friendlier 404 page.

**Comment by mrocklin** [comment]
Sounds good to me.  You seemed interested in contributing to the dashboard earlier.  Does that still apply here?  If so, here are some possibly useful places to start looking:

Our routes are here:

https://github.com/dask/distributed/blob/051a79e05c501dcea57a19715f59d0cd203f6be6/distributed/dashboard/scheduler_html.py#L231-L251

And they get added to this Tornado web server (which is hiding within a Bokeh server)

https://github.com/dask/distributed/blob/051a79e05c501dcea57a19715f59d0cd203f6be6/distributed/dashboard/core.py#L51

**Comment by martindurant** [comment]
Meaning that `(r"info/task/(.*).html", Task), ` picks up that URL, but the corresponding handler errors. You would get a 404 if you missed the routes altogether, but the handlers should indeed do that too, if you pass a URL that looks valid, but the target isn't found; in this case "No such task" or something.

@rs2 , we would be happy to see this as a PR.
