### ISSUE TITLE
Distributed Scheduler Python API - start scheduler

### ISSUE THREAD

**Issue by amermelao** [dask/distributed#2931]
The API has been changed without issuing a warning. The scheduler method start() in version 2.2.0 doesn't allow for an address or port to be a parameter, but in version 2.1.0 and below does allow for a parameter to be passed for the address and port. This is not updated on the website as shown in the image attached nor is there a deprecation warning.

![image](https://user-images.githubusercontent.com/5368026/62571684-f696e980-b85f-11e9-8d39-3cb4a79692cd.png)

**Comment by mrocklin** [comment]
Indeed.  Thanks for the warning.  We should fix the docs.  I recommend
looking at https://docs.dask.org/en/latest/setup/python-advanced.html ,
which was kept up to date during this process.

**Comment by mrocklin** [comment]
Closing in favor of https://github.com/dask/dask/issues/4813
