### ISSUE TITLE
Prevent reruns when worker dies?

### ISSUE THREAD

**Issue by cicdw** [dask/distributed#2935]
It seems that when a dask worker dies in the middle of a computation, the incomplete computation is re-submitted to a new worker _and its upstream dependencies are also rerun_.

To illustrate; suppose we set up a local dask cluster with two workers and run the following:

```python
from distributed import Client
import time

client = Client(address="tcp://10.0.0.41:8786")

def root_task(*args):
    print("IM RUNNING HERE")
    if args:
        time.sleep(5)

def run():
    a = client.submit(root_task)
    b = client.submit(root_task, a)
    client.gather(b)

run()
```
and we quickly find the worker which is running the tasks (via the presence of two print statements) and kill it.  When I look at the stdout of the second worker I actually see _two_ print statements when I expected to only see one (corresponding to `b`).

I imagine there is some implementation reason for this but I'm wondering what exactly is happening under the hood (I couldn't figure it out myself) and whether there is a way of turning this behavior off or pre-empting it in some way?

**Comment by mrocklin** [comment]
Sorry for the long delay in response.  My guess is that the upstream dependency was released from memory and so had to be recomputed in order to provide the input to the task that was lost while processing.
