### ISSUE TITLE
SpecCluster Multiple IP addresses

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2962]
There are situations when creating a distributed cluster where the workers will need to connect to the scheduler on an internal private IP address but the client should connect on an external public IP.

One example of this would be out-of-cluster kubernetes where the workers need to connect via the internal container networking IP but the client should connect through an external load balancer or node port. Another would be on AWS ECS where the scheduler is assigned both an internal and external address, sadly workers are not able to route to the external address and clients are not able to route to the internal address.

When creating the scheduler via the various APIs both addresses will be known, but currently the `SpecCluster` only takes a single address which is passed on to the worker tasks as well as used to connect the RPC.

I propose that we make it possible for an external address to optionally also be set, which will be used for the RPC and daskboard urls. The `scheduler_comm` is created [here](https://github.com/dask/distributed/blob/master/distributed/deploy/spec.py#L228) and we could change it to `self.scheduler.external_address or self.scheduler.address` with `self.scheduler.external_address` defaulting to `None`.

**Comment by mrocklin** [comment]
Just to make sure I understand, the way that we currently set up a scheduler is fine.  It's possible to connect to it on a variety of network interfaces.  However the `.address` field that we publish is restricted to a single network interface.

What you propose makes sense to me.  I'm curiuos if it makes sense to generalize further.  Rather than have an `external_address` attribute perhaps we have an `addresses` attribute, which contains a mapping of network interface to address.  We might pass this dictionary to workers and allow them to choose an appropriate address, given their preferred network interface.  Mostly my goal here is to avoid having to go through this process again.

**Comment by mrocklin** [comment]
This may be a bad idea for a variety of reasons though.  Feedback would be appreciated.

**Comment by mrocklin** [comment]
Although I suppose that this breaks if we consider non-tcp/tls comms, like inproc:// or ucx:// (I think)

**Comment by jacobtomlinson** [comment]
> Just to make sure I understand, the way that we currently set up a scheduler is fine. It's possible to connect to it on a variety of network interfaces. However the .address field that we publish is restricted to a single network interface.

Yup thats it.

> perhaps we have an `addresses` attribute, which contains a mapping of network interface to address

I wonder how the workers or clients would make sense of this dictionary. Would they pick keys like `worker` or `external` or would it be more intelligent? I feel like knowing which address is useful in which location is down to some logic in the implementation of the `SpecCluster`.

> Although I suppose that this breaks if we consider non-tcp/tls comms, like inproc:// or ucx:// (I think)

This is an interested point that I hadn't considered. It is likely that when using non-tcp/tls comms from `SpecCluster`s that have been created remotely those protocols may not be supported from the client at all. You may want to pass work and data in to dask via tcp/tls and then have internal communications be ucx for example.

**Comment by mrocklin** [comment]
> I wonder how the workers or clients would make sense of this dictionary.

I think that I was assuming (perhaps incorrectly) that the interface names would be the same.  That's probably not true though.  

>  Would they pick keys like worker or external or would it be more intelligent?

I'm mostly trying to avoid a future in which someone asks for something very similar, for example when having workers deployed on two different networks, and now asking for a `Scheduler.address_one` and `Scheduler.address_two` to add on to this.  Maybe we solve that problem when it occurs though (if it occurs).

**Comment by mrocklin** [comment]
This is what I was thinking, but I'm no longer confident that it's a good choice:

```python
In [1]: import psutil, socket

In [2]: {k: v[0].address for k, v in psutil.net_if_addrs().items() if v[0].famil
   ...: y == socket.AF_INET}
Out[2]: {'lo0': '127.0.0.1', 'en0': '192.168.1.195'}
```

**Comment by mrocklin** [comment]
I think that what you propose seems reasonable for now.  We can generalize things in the future if we find a better way.
