### ISSUE TITLE
Track killed workers in SpecCluster

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2968]
I've noticed that workers created by a `SpecCluster` remain in the worker count if they are killed harshly. The client shows them as being gone.

Perhaps we should add some checks in correct state to remove any dead workers and call it intermittently?

**Comment by mrocklin** [comment]
The relevant code to fix this is probably here:

https://github.com/dask/distributed/blob/b083b10d64763b38e559096127d6e3e0c0638c31/distributed/scheduler.py#L5022-L5053

and here

https://github.com/dask/distributed/blob/b083b10d64763b38e559096127d6e3e0c0638c31/distributed/deploy/cluster.py#L90-L108

Probably we want to override `Cluster. _watch_worker_status` with `SpecCluster. _watch_worker_status` that also removes the object from `.workers`?

**Comment by guillaumeeb** [comment]
OK, I'm working on this, will submit a PR soon.
