### ISSUE TITLE
[BUG/FEATURE]Handle deserialization of tracebacks

### ISSUE THREAD

**Issue by rs2** [dask/distributed#2971]
https://github.com/dask/distributed/blob/b083b10d64763b38e559096127d6e3e0c0638c31/distributed/protocol/pickle.py#L61
`TypeError: 'traceback' object is not subscriptable`

**Comment by mrocklin** [comment]
This would be welcome

**Comment by mrocklin** [comment]
How does this occur?  Are we calling `pickle.loads(tb)` somewhere?  If so, it seems like there is a core issue to figure out here.

**Comment by mrocklin** [comment]
Any update here @rs2 ?  If you're able to help us reproduce this error that is probably the right place to start.

**Comment by jrbourbeau** [comment]
Closing due to lack of response. @rs2 we can re-open if you want to pick this up again
