### ISSUE TITLE
dask.distributed.progress no longer callable in 2.3.0?

### ISSUE THREAD

**Issue by joeschmid** [dask/distributed#2973]
We've used the progress() function from dask.distributed a bunch in the past to display a progress bar in JupyterLab, but it seems to have stopped working after upgrading to Dask 2.3.0:

```
from dask.distributed import Client, progress
import dask.dataframe as dd

df = dd.demo.make_timeseries('2010', '2016',
                             {'value': float, 'name': str, 'id': int},
                             freq='10s', partition_freq='7d', seed=1)

df = df.persist()
progress(df)
```

Executing this in a single cell in JupyterLab (with an existing Dask cluster already running) results in:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-16af814d7204> in <module>
      7 
      8 df = df.persist()
----> 9 progress(df)

TypeError: 'module' object is not callable
```

Let me know if I can provide any more info. Thanks!

**Comment by mrocklin** [comment]
Thanks for raising this @joeschmid .  Fixed in https://github.com/dask/distributed/pull/2975

**Comment by joeschmid** [comment]
Thanks @mrocklin for the super fast response! Much appreciated! (And also a quick thanks to you and the Dask community. We're somewhat new users, but have already had big success running thousands of data science experiments in parallel on Dask using Prefect. Also using Dask Kubernetes to easily scale up workers -- can quickly have a 100 node Dask cluster, run lots of experiments, then scale it back down. It's already been a big success for us and we're building out our data science stack with Dask as the core of it.)

**Comment by mrocklin** [comment]
I'm glad to hear it!  

If you're interested in sharing more we love seeing blogposts about how people use Dask in practice.  We also enjoy collecting use cases at https://stories.dask.org
