### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#30]
Communications both between workers and between workers and center/scheduler/client can all, at times, benefit from compression.  Do we want to turn this on by default?  Do we want to make it optional?  If so, at what granularity should it be optional?

*  Whole system
*  Specified per worker/center/... object?
*  Specified per communication?

If we specify it per communication then we'll have to have a proper header that is separate from the current payload.

* What do other systems (spark, impala) do?
* What compression systems are both very fast and widely available (or at least on conda)?

**Comment by minrk** [comment]
I'm not sure what existing systems use, but [blosc](http://www.blosc.org/) is pretty awesome and easy to install, as far as I can tell. I would probably do it per-message and specify the compression in a header. There are too many uses for proper headers that I don't think you are going to be able to stay away from them for long. That way you could blosc-compress binary data, gzip text (I don't know how great blosc is at text), skip compression for small messages, etc.

**Comment by broxtronix** [comment]
I agree than (blosc)[https://github.com/Blosc/python-blosc] looks very promising.  Here are the standard blosc benchmarks running on my laptop.

```
Creating NumPy arrays with 10**8 int64/float64 elements:
  *** ctypes.memmove() *** Time for memcpy():	0.438 s	(1.70 GB/s)

Times for compressing/decompressing with clevel=5 and 8 threads

*** the arange linear distribution ***
  *** blosclz  ***  0.089 s (8.38 GB/s) / 0.095 s (7.86 GB/s)	Compr. ratio:  85.6x
  *** lz4      ***  0.097 s (7.65 GB/s) / 0.114 s (6.55 GB/s)	Compr. ratio:  86.5x
  *** lz4hc    ***  0.124 s (6.03 GB/s) / 0.119 s (6.27 GB/s)	Compr. ratio: 152.1x
  *** snappy   ***  0.093 s (8.03 GB/s) / 0.136 s (5.49 GB/s)	Compr. ratio:  19.0x
  *** zlib     ***  0.840 s (0.89 GB/s) / 0.319 s (2.34 GB/s)	Compr. ratio: 312.1x

*** the linspace linear distribution ***
  *** blosclz  ***  0.277 s (2.69 GB/s) / 0.118 s (6.33 GB/s)	Compr. ratio:   2.9x
  *** lz4      ***  0.160 s (4.66 GB/s) / 0.118 s (6.34 GB/s)	Compr. ratio:   5.0x
  *** lz4hc    ***  0.565 s (1.32 GB/s) / 0.101 s (7.40 GB/s)	Compr. ratio:  40.9x
  *** snappy   ***  0.162 s (4.60 GB/s) / 0.135 s (5.50 GB/s)	Compr. ratio:   6.1x
  *** zlib     ***  1.013 s (0.74 GB/s) / 0.276 s (2.70 GB/s)	Compr. ratio:  38.3x

*** the random distribution ***
  *** blosclz  ***  0.198 s (3.77 GB/s) / 0.098 s (7.59 GB/s)	Compr. ratio:   3.9x
  *** lz4      ***  0.131 s (5.68 GB/s) / 0.111 s (6.71 GB/s)	Compr. ratio:   4.7x
  *** lz4hc    ***  6.212 s (0.12 GB/s) / 0.127 s (5.87 GB/s)	Compr. ratio:   5.5x
  *** snappy   ***  0.164 s (4.55 GB/s) / 0.142 s (5.26 GB/s)	Compr. ratio:   4.4x
  *** zlib     ***  2.385 s (0.31 GB/s) / 0.396 s (1.88 GB/s)	Compr. ratio:   6.1x
```

The (blosc)[https://github.com/Blosc/python-blosc] readme has another set of benchmark numbers for comparison.  

Compared to the speed of the inter-process or inter-node communication, compression is very fast indeed.  It looks to me like the `blosclz` algorithm (the default) or perhaps 'lz4' would probably work well as an all-purpose compressor.  Both of these get reasonable compression ratios and are plenty fast on both the encoding and decoding sides.

One thing worth thinking about: `blosc` uses multiple threads to help it achieve its fast compression speeds.  Since `distributed` is already using multiple cores, it might make sense to throttle back the number of cores `blosc` uses so that each `dworker` has a processor footprint that keeps it within a relatively small number of threads even when compressing / uncompressing messages.  That said, I would think that it would not hurt to give each instance of `blosc` access to at least a few (2-4?) threads to help make sure the CPU is fully utilized at all times.

+1 to @minrk's comments on adding a header for notating what compression is being used for a given message.

**Comment by mrocklin** [comment]
Blosc is neat and great at what it was designed for (streaming large arrays off of disk).  Distributed's needs are somewhat different, but do overlap some.  Some concerns:

*  I agree that we wouldn't want to use threads
*  We really want something that releases the GIL here
*  I don't think that the arange and linspace benchmarks are realistic
*  Sometimes the compression systems that blosc uses, like `lz4` or `snappy` are sufficient on their own.  Some of Blosc's main value adds are blocking and multithreading, which we don't need.
*  Blosc is optimized for arrays, and not for general data.  Some of blosc's strengths arise only when you give it dtype information which, for general communication, we won't have without some more serious special-casing.
*  Blosc is under only pseudo-active maintenance.  The developers are fairly busy with other projects

In my ideal world blosc acts first as a gateway and standard interface to other compression libraries.  See https://github.com/Blosc/python-blosc/issues/101.  In this context it would be super useful for us.  I'm less enthused about the blocking, multi-threading, and shuffling for compressing slightly more general network traffic.

**Comment by broxtronix** [comment]
A few more thoughts:

It looks like [Spark](http://spark.apache.org/docs/latest/configuration.html#compression-and-serialization) uses Snappy by default, although it also supports LZ4.  Compression of broadcast variables is turned on by default, but it looks like compression of RDDs is not on by default.  This may be due partly to the fact that Spark RDDs are stored in memory as serialized data, so compression effects memory usage and access speeds as well as communication speeds.  

In the case of `distributed` I would imagine that compression will really only come into play when sending / receiving byte streams over the network.  Personally I think the sensible default would be to enable compression for memory transfers, but what do you guys think?

Regardless of defaults, as a user I'd like to be able to tune up the compression to suit my particular needs, including settings for:
* Compression of message payloads: on, off
* Compression codec: snappy, blosclz, lz4, lz4hc, zlib
* Compression level: 0 - 9 
(More on the blosc compression options can be found [here](http://python-blosc.blosc.org/reference.html#module-blosc). 

In general I think I'd be pretty happy with "whole system" granularity when it comes to compression.

One other note on Blosc, as far as I can tell the conda package currently only contains the C library.  Unfortunately `pip install blosc` resulted in an installation that segfaulted when I ran `import blosc` in Python, at least on my machine.  Installing blosc from the [github page](https://github.com/Blosc/python-blosc) worked, though.

Also, it looks like there are dedicated Python bindings for [snappy](https://github.com/andrix/python-snappy) if `blosc` does not work out.

**Comment by mrocklin** [comment]
OK, as of #149 we have compression support.  The current policy for this is that we use LZ4 or Snappy if available (preferring LZ4 over Snappy) on any message that is over 1kB.

We can provide user hooks to define policies in the future.  I recommend that we see how this goes for now.
