### ISSUE TITLE
Start workers with conda environments

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#300]
In [Knit](http://knit.readthedocs.io/en/latest/) we start workers on YARN with pre-packaged conda environments.  This is handy.  Perhaps the workers/nannies should handle this on their own so that they can restart themselves in a new environment.  This would help with non-yarn systems.

@quasiben 

I have a few questions about how to do this well:
1.  What parts do we pull out of Knit?  Should this be separately packaged or just shoved into dask/distributed for now?
2.  How do we restart the worker from the nanny in the new environment?  The nanny will be in some base environment and we'll want to call the Worker process robustly in the new environment.  I'm actually a bit curious if we should keep using multiprocessing (which is less conda-friendly presumably) but append the environment to `sys.path`.
### Detailed suggestion on how to implement this
1.  Change nanny to use subprocess rather than multiprocessing.Process to start the worker.  Communication of `port` and `local_dir` will have to be through some mechanism other than the current `multiprocessing.Queue`.  This could use perhaps either a file on disk or stdout.
2.  Build the necessary functions in the Executor/Nanny/Worker to pass environments around.  I suggest the following:
   1.  Executor function takes a path to a zipfile as created by https://github.com/quasiben/condacreate and sends it to some scheduler function using something like 
      
      ```
      response = yield self.scheduler.restart_workers_in_environment(env=open(filename, 'b').read())
      ```
   2.  Scheduler uses the `scatter` coroutine with `broadcast=True` to scatter the zipped env out to the workers as data.  This communicates large amounts of data efficiently with a tree-pattern.
      
      ```
      response = yield self.scatter(workers=workers, data={'zipped-env-hash': bytes}, broadcast=True)
      ```
   3.  The scheduler then calls some function on all the workers to dump the data to disk and unzip, returning the location of the resulting directory.  
      
      ```
      directories = yield [self.rpc(addr=worker).unpack_environment(key='zipped-env-hash') for worker in workers]
      ```
      
      This will require building a new route on the worker registered under `'unpack_environment'` to write the data in `self.data['zipped-env-hash']` to `os.path.join(self.local_dir, 'zipped-env-hash')`, unzip it to `env-hash` and return the resulting directory.
   4.  After this response the scheduler contacts all of the nannies
      
      ```
      nannies = [self.worker_info[worker]['services']['nanny'] for worker in workers]
      ```
      
      and issues a call to restart each worker while also including a new keyword to change the python path:
      
      ```
      responses = yield [self.rpc(nanny).restart(new_environment=directory) for nanny, directory in zip(nannies, directories)]
      ```

**Comment by ogrisel** [comment]
Would be great to also add support for virtualenvironment / requirements.txt files.

About 2, I think we should just use `subprocess.Popen` and pass the start worker qualified function name as a CLI argument.

**Comment by mrocklin** [comment]
Is there a nice way to package a virtualenv environment into a single redeployable file that we can move around between nodes?  I want to avoid assuming that we have access to PyPI on the worker nodes.

**Comment by mrocklin** [comment]
After chatting with a few people real-time on this here are some concerns and responses

### conda packages have relative paths

It's tough to create relocatable environments.  @quasiben says that actually as long as we're using explicit paths to the main executable things seem to be fine

### If we expose a programmatic conda/pip api we'll eventually be asked to support all of conda/pip

We can probably gracefully punt to having users author their environment with the actual CLI and then ship that.  This lets us avoid a large maintenance burden.  Users will have to create environments with `--copy` to avoid hardlinks.

### We still care about containers for isolation, etc..

from @hussainsultan 

We can probably create bare-bones docker containers that just have enough to launch dask.distributed.  Dask can then bootstrap from there if we're happy with conda environments.  Naive users can more rapidly change environments without creating and registering many docker containers for each change.

**Comment by ogrisel** [comment]
> Is there a nice way to package a virtualenv environment into a single redeployable file that we can move around between nodes? I want to avoid assuming that we have access to PyPI on the worker nodes.

Just zipping / unzipping the venv folder works great.

**Comment by ogrisel** [comment]
> Just zipping / unzipping the venv folder works great.

Actually that is only the case if you have matching version of Python (and the same OS) on the machine were you create the venv folder and the machines where you deploy. It's the case if you use docker containers but not necessarily otherwise.

**Comment by mrocklin** [comment]
Update: a while ago @quasiben made https://github.com/quasiben/condacreate to create zip files programatically from conda environments.

@ogrisel I suspect that if I head up this work that I'll start with conda.  Both because of the people that I'm around and also because it's what I use personally.  Hopefully it's easy to extend to virtualenv afterwards.

**Comment by mrocklin** [comment]
Implemented.  Closing
