### ISSUE TITLE
Reset worker that performed errored task

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3006]
When a worker has completed a task with an error, the scheduler appears to mark the bar in dark grey. That is is all fine. But the question is, how can I reset the worker for it to forget the errored task and free the memory, and make the dark grey bar disappear in the scheduler?

Is there a way to do that without having to restart the worker and scheduler? In my case there are still tasks market as 'in memory'.. I assume this means that some of the future's results (which are errors) have not been picked up? This is surprising, as I'm using

```
for future in as_completed(futures):
    _ = future.results()
```

**Comment by mrocklin** [comment]
I think that there is a client.retry method?

**Comment by dickreuter** [comment]
The failures happen because some function is not working correctly and raising an error. So a retry won't help. I'd simply like the worker and scheduler to forget about it.

**Comment by mrocklin** [comment]
Delete all references to the task?  Create a new task with the same
arguments but a different name, perhaps with pure=False?

**Comment by dickreuter** [comment]
Deleting all references to the task doesn't appear to be enough. In my case, I have an administrative task that kicks of subtasks. The administrative tasks ends once all subtasks have ended, and therefore there should be no more reference to them.

What's the purpose of pure=False? Why would create a new task with the same arguments help? In my case the tasks run for several hours so this is not a preferred way to handle this.

**Comment by quasiben** [comment]
If you use `pure=False` you are instructing dask to use a unique identifier for the task name.  Thus, with a unique name, the scheduler will recompute the task instead of relying on the failed result.  I'd recommend reading: https://distributed.dask.org/en/latest/client.html#pure-functions-by-default

**Comment by dickreuter** [comment]
My problem is not that failed tasks should be recalculated. The problem is that they stay in the scheduler dashboard forever. Under normal circumstances, the bar disappears if all tasks were completed successfully. What is needed is some kind of reset or a timeout after which old failed tasks are no longer shown in the dashboard.

**Comment by TomAugspurger** [comment]
@dickreuter at this point you should probably put together an example that fails. For example, this works fine.

```python
from distributed import Client

client = Client()
client

def a():
    raise TypeError
    
def b():
    pass
```

```python
f1 = client.submit(a)
```

![Screen Shot 2019-09-04 at 9 57 20 AM](https://user-images.githubusercontent.com/1312546/64266443-3a7e1c80-cefa-11e9-8342-b3ea5abf1b0a.png)


```python
f2 = client.submit(b)
```

![Screen Shot 2019-09-04 at 9 57 28 AM](https://user-images.githubusercontent.com/1312546/64266497-4833a200-cefa-11e9-89f4-9fc57fee4724.png)


```python
del f2

del f1
```

![Screen Shot 2019-09-04 at 9 57 38 AM](https://user-images.githubusercontent.com/1312546/64266502-4bc72900-cefa-11e9-88d9-43fdc254a3a2.png)

**Comment by jrbourbeau** [comment]
Just checking in here, @dickreuter are you able to produce a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)?

**Comment by TomAugspurger** [comment]
@dickreuter any updates here?

**Comment by dickreuter** [comment]
I'll close this issue. I managed to solve almost all my problems with dask distributed by using a dedicated resources worker rather than secede(), as the latter seems to have quite severe memory leak issues.
