### ISSUE TITLE
dask dashboard removes task history from the status page when a dask delayed process is running

### ISSUE THREAD

**Issue by rbavery** [dask/distributed#3009]
My dashboard looks like this after some of my dask delayed functions have run, allowing me to see that my processes are being completed by workers with roughly the same amount of time

![Screenshot from 2019-08-28 11-46-57](https://user-images.githubusercontent.com/22258697/63884358-dfdd4180-c98a-11e9-962f-0f1270d9585a.png)

But during the second to last step, "move_chips_to_folder" , the process sits around in memory for a couple of minutes after it has completed. Then after these minutes, the next process "connected_components" starts up and removes what was on the status page (I've tried zooming in and out and the task progress is gone):

![Screenshot from 2019-08-28 11-54-02](https://user-images.githubusercontent.com/22258697/63884628-63972e00-c98b-11e9-8240-11c3731d4faa.png)

From the above image, it looks like the yellow process, "connected_components",  is run one worker at a time.

But when everything finishes the dashboard looks like this:

![Screenshot from 2019-08-28 12-07-53](https://user-images.githubusercontent.com/22258697/63885130-81b15e00-c98c-11e9-8837-dc5450f10d6d.png)

**Comment by mrocklin** [comment]
That plot clears out old tasks if nothing has come in in a while.

**Comment by mrocklin** [comment]
You may want to look at the tasks page for a longer term view
