### ISSUE TITLE
dask.compute workers won't release memory after moving different sets of files to different folders

### ISSUE THREAD

**Issue by rbavery** [dask/distributed#3010]
I'm getting an issue with the `dask.compute` scheduler where my delayed `move_chips_to_folder` function is completing quickly but then sticking around in memory, causing there to be a long (over 5 minute) pause before the next delayed function starts.I noticed this part of the docs:

```
Difference with dask.compute
The operations client.persist(df) and client.compute(df) are asynchronous and so differ from the traditional df.compute() method or dask.compute function, which blocks until a result is available. The .compute() method does not persist any data on the cluster. The .compute() method also brings the entire result back to the local machine, so it is unwise to use it on large datasets.
```

But I'm not working with large datasets in the problem function, `move_chips_to_folder`, and each delayed object is operating on a separate set of files, moving them from folder to another. Could blocking still occur in this case?

See this image, where the `move_chips_to_folder` function is hanging around in memory even though nothing is stored in memory to be used by the next function, `connected_components`.

![Screenshot from 2019-08-28 11-46-57](https://user-images.githubusercontent.com/22258697/63888770-795d2100-c994-11e9-9281-1b92195a73f6.png)

For reference here is the problem function:

```
    def move_chips_to_folder(self):
        """Moves a file with identifier pattern 760165086.tif to a 
        folder path ZA0165086/image/ZA0165086.tif
        
        """

        for old_chip_path in self.chip_img_paths:
            chip_id = os.path.basename(os.path.splitext(old_chip_path)[0])
            chip_folder_path = os.path.join(self.TRAIN, chip_id)
            if os.path.exists(chip_folder_path) == False:
                os.mkdir(chip_folder_path)
            else:
                raise Exception('{} should not exist prior to being created in this function, it has not been deleted properly prior to a new run'.format(folder_path)) 
            new_chip_path = os.path.join(chip_folder_path, "image")
            mask_path = os.path.join(chip_folder_path, "mask")
            os.mkdir(new_chip_path)
            os.mkdir(mask_path)
            shutil.copyfile(old_chip_path, os.path.join(new_chip_path, chip_id + ".tif")) # moves the chips   
            os.remove(old_chip_path)
        return self
```

any thought son what is causing dask to hold onto memory? Any suggestions on how to further profile this are welcome.

**Comment by quasiben** [comment]
@rbavery what is producing the memory originally?   You might want to read over how [dask manages memory](https://distributed.dask.org/en/latest/memory.html#managing-memory)

**Comment by rbavery** [comment]
Hi @quasiben after some code modifications, the items hanging around in memory seems to happen at the end of the process which reads in tif images and converts them to byte scaled pngs:

```
def label_to_png(tif_path, png_path):
    """
    Converts processed tif chip labels into pngs
    """
    arr = skimage.io.imread(tif_path)
    
    if len(arr.shape) > 2:
        arr = np.any(arr, axis=2)
                
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        skimage.io.imsave(png_path, img_as_ubyte(1*arr))
```

This function is the last of the dask delayed functions applied to a sequence of image paths in parallel:

```
results = []
for scene_path in scene_list:

    wflow = dask.delayed(PreprocessWorkflow)(param_path, scene_path, labels_path)

#     wflow = PreprocessWorkflow(param_path, scene_path, labels_path)
    
    band_list = wflow.yaml_to_band_index()
        
    product_list = wflow.get_product_paths(band_list)
        
    a = wflow.load_meta_and_bounds(product_list)
        
    b = a.stack_and_save_bands()
        
    c = b.negative_buffer_and_small_filter(-31, 100)
        
    d = c.grid_images()
    
    e = d.imgs_to_pngs()
        
    f = e.connected_components()
    
    result = f.labels_to_pngs()

    results.append(result)
  

# https://docs.dask.org/en/stable/delayed-best-practices.html
from dask.distributed import Client

client = Client()  # use dask.distributed by default

x = client.compute(results)  # start computation in the background
```

I'm not sure which of these conditions is causing the memory to stick around but I don't think it is 1 since there is no "future" task after `label_to_png`. could this be because the `label_to_png` function doesn't return anything and so there is no final result that indicates to the dask client that the dask delayed function should finish (related to condition 2  for memory sticking around in the link you posted)? 

```
1. A client holds a future pointing to this task. The data should stay in RAM so that the client can gather the data on demand.

2. The task is necessary for ongoing computations that are working to produce the final results pointed to by futures. These tasks will be removed once no ongoing tasks require them.
```

Here is my task graph, where now the memory sticking around after all processsing has finished occurs at the end (14 processes are still in memory):

![Selection_005](https://user-images.githubusercontent.com/22258697/64901795-3668a200-d652-11e9-8843-9d317daef4fa.png)

Thanks for the help!

**Comment by rbavery** [comment]
And when I check out a worker's info to look at it's dependencies and future sthat are tied to this I see this:

![Selection_007](https://user-images.githubusercontent.com/22258697/64902062-81d07f80-d655-11e9-9d3c-9764a0d29208.png)

And when I click to examine "Clients with future" I get 404: Not Found

In the transition log in the Finish column, what's the difference between "memory" and "waiting"? On the Status page it says that the connected_components calls all have finished and are not in memory but this Transition Log lists a connected_components with "memory" rather than "released"

**Comment by quasiben** [comment]
Sorry for the delay @rbavery , `memory` indicates that the task is done processing and currently stored in memory.  As you noted, this is often because a dependent task is going to be using it.  `released->waiting` often means waiting for new work. The task doc page,
https://distributed.dask.org/en/latest/scheduling-state.html?highlight=waiting#understanding-a-task-s-flow , lists all the worker states and the transition states workers can move through



released → waiting | occupancy, idle, saturated

**Comment by TomAugspurger** [comment]
I guess as a relatively easy way to determine whether you're keeping a reference to the data, can you put all your code into a function and call that? Then when the function exits, all the local variables will be removed. Something like

```python
client = Client(...)

def func():
    results = []
    for scene_path in scene_list:
        wflow = dask.delayed(PreprocessWorkflow)(param_path, scene_path, labels_path)
        ....
        results.append(...)
    x = client.compute(results)  # start computation in the background
```

@rbavery If you're memory is freed after `func` completes, that that indicates you have a reference to something keeping the data alive.

**Comment by rbavery** [comment]
Thanks a bunch for the help, I understand now that I was misinterpreting "memory" as my dask task graph not having finished processing, thanks for the explanations and suggestions.
