### ISSUE TITLE
Raise exception if the user passes in unused keywords to Client

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3014]
For example

```python
client = Client(address, dashboard_address="foo")
```

The dashboard address keyword is useful if we're creating a `LocalCluster`, but it doesn't get used if we're connecting to an already-started scheduler.  In these cases, we should probably raise, otherwise we risk adding confusion.

cc @shwina

**Comment by detroyejr** [comment]
I can try my hand at submitting a PR for this issue.

In lieu of a good existing exception, it might be useful to add a custom exception to help clarify why this is being raised such as:

```
class UnusedKeywordException(ValueError):
    pass
```

I think this exception should then be raised just after this conditional block [here](https://github.com/dask/distributed/blob/master/distributed/client.py#L641).

Something like this might work:

```
if address:
    if "dashboard_address" in kwargs:
        raise UnusedKeywordException("Keyword argument 'address' cannot be used simultaneously with 'dashboard_address'.")
```

Would this be a satisfactory solution?

**Comment by mrocklin** [comment]
Most of the time we tend to use built-in exceptions, but with informative messages.  We should probably either change this policy everywhere (and make dozens of new exception types) or keep it.  I'm in favor of keeping it.

The code you provide would solve the specific issue around dashboard_address, but we would prefer a solution that covers any excess keyword.  dashboard_address was just used above as an example.

**Comment by detroyejr** [comment]
Thanks for the feedback.

Took another look and implemented something more general that would go after [here](https://github.com/dask/distributed/blob/78d8cad9e8934a3b863999832b7c46dfe8162683/distributed/client.py#L917).

```
        if address is not None:
            from .deploy import LocalCluster
            unused_args = [
                arg for arg in self._startup_kwargs
                if arg in list(LocalCluster.__init__.__code__.co_varnames) and 
                arg not in ["silence_logs"]  and
                self._startup_kwargs.get(arg) is not None
            ]

            if unused_args:
                raise ValueError(
                    "{} arguments cannot be used when scheduler or LocalCluster is already running.".format(
                        ", ".join(["'{}'".format(arg) for arg in unused_args])
                    )
                )

```
Errors will be raised when users invoke.

```
from dask.distributed import Client

# Fails
client = Client(address="127.0.0.1:8786", n_workers=4)

# Fails
client = Client(address="127.0.0.1:8786", dashboard_address="127.0.0.1:8787")

# Fails
client = Client(address="127.0.0.1:8786", scheduler_port=8787)

# Passes
client = Client(n_workers=4)

# Passes
client = Client(scheduler_port=8000)
```

The message itself needs a little more thought, but the solution itself seems to work alright. Any arguments that should be excluded from this check?

I originally excluded "silence_logs" since I remember a test failing without that line included, but I need to check and make sure that's still the case. Other than that, all other tests are passing AFAIK.

**Comment by mrocklin** [comment]
I wonder if we might just be able to do something like the following:

```python 
if address is not None and kwargs:
    raise ValueError("Unexpected keyword arguments: {}".format(str(sorted(kwargs))))
```

**Comment by detroyejr** [comment]
Yeah, simpler is better. I didn't know if that would be too broad and raise for other extra keywords that are not in LocalCluster.

**Comment by mrocklin** [comment]
I don't think that we use them anywhere else, but hopefully if we do then
tests will start failing if this is wrong.
