### ISSUE TITLE
Stop Queue from printing it's name on __init__

### ISSUE THREAD

**Issue by roveo** [dask/distributed#3031]
There's a print statement here:

https://github.com/dask/distributed/blob/8d07bf162b1f6434fc982f36360c5cedbac369a6/distributed/queues.py#L50

Would be nice to replace it with logging.debug()

**Comment by TomAugspurger** [comment]
Whoops, thanks. Interested in submitting a PR for that? Otherwise, I'll submit one later today.

(note: it should probably be `logger.debug`, rather than `logging.debug`)

**Comment by roveo** [comment]
Sure, I will

**Comment by jrbourbeau** [comment]
Great, thanks @roveo!
