### ISSUE TITLE
Inefficient memory use when computing arrays constructed via `da.from_array`

### ISSUE THREAD

**Issue by d-v-b** [dask/distributed#3032]
```python
client = Client(LocalCluster(n_workers=2, threads_per_worker=1))
#~80 GB, but it can be anything that shows up in the resource monitor. 
big_np_array = np.zeros((1000, 1000 * 10000))
big_dask_array = da.from_array(big_array, chunks=(1,-1))
big_dask_array[0].compute()
```
On my workstation, the task gets assigned to a single worker, and this worker proceeds to load ~80 GB of data into RAM. This is not the most efficient way to allocate data for this computation, given the chunking scheme we specified. 

By contrast, this is much more efficient, in terms of memory usage, despite using the same chunking:
```python
big_dask_array_2 = da.stack((da.from_array(element) for element in big_np_array))
big_dask_array_2[0].compute()
```
Looking at the task graphs for both dask arrays reveals that when using `from_array(arr)`, the entirety of `arr` is a task dependency for all computations on that array, regardless of the chunking, while constructing a comparable dask array via `stack` produces tasks that (rightly) only depend on the data specified by the chunking scheme. See https://github.com/dask/dask/issues/5367 for a longer description. It's likely that fixing the issue described in https://github.com/dask/dask/issues/5367 would resolve the issue I describe here.

**Comment by quasiben** [comment]
@d-v-b after looking at this a bit i definitely agree putting an 80GB node in your task graph is not efficient and as you've noted, the stacking is significantly more performant and better resource managed. 

In dask/dask#5367, are you asking that dask should include this type of optimization automagically ?  

I wonder if @jrbourbeau has time and thoughts here?

**Comment by d-v-b** [comment]
@quasiben in dask/dask#5367 I'm mainly asking for the opinion of the devs on the asymmetry between `from_array` and `stack`, and to raise awareness that there is an large performance issue. Personally, I think the task graph created by `stack` is far more intuitive than the task graph created by `from_array`, but there might be good reasons the status quo that I'm not familiar with.

**Comment by mrocklin** [comment]
What do you think from_array should do?

**Comment by mrocklin** [comment]
Should we not include the original object in the task graph?  If so, what should we include?  Please note that from_array is usually used with objects like h5py Files or Zarr datasets, and relatively infrequently used with Numpy arrays in practice.  (Loading large data locally and then giving it to Dask is something of an antipattern, because it needs to be sent everywhere).

**Comment by d-v-b** [comment]
Since `stack(*collection_of_subarrays)` does the "right" thing, is it possible for `from_array` to do the same thing? (n.b. I haven't tried testing this strategy with different chunking schemes.)

I agree that creating a big dask array in memory locally and distributing the computation is an anti-pattern, but it's a very easy anti-pattern for users to use, given then apparent simplicity of 
`from_array(big_numpy_array).map_blocks(func).compute()`

In this particular case, I was helping a dask user understand why her simple compute task were blowing up workers. Because I assumed that the chunking in `from_array` determined the data partitioning of subsequent tasks, it took a while to track down the issue. I suspect a lot of non-experts would make the same assumption I did.

**Comment by mrocklin** [comment]
I don't personally know what the *right thing* to do in this case is.  Should we slice up the array ahead of time or not?  I think that the answer is "it depends on the type of the thing that we put into `from_array`.  If slicing it is super fast and just makes smaller versions of itself then sure, slicing it immediately makes sense (This is true for numpy, sparse, cupy arrays). However if slicing it is slow and makes different kinds of things (like h5py, zarr) then the answer is that we want to delay slicing until later.

**Comment by mrocklin** [comment]
Maybe it's worth adding in a type check for numpy arrays.  I'm not sure.  

Anyway, I think that "right thing" here isn't fully defined.  And that figuring out a policy that works generally is the crux of the matter.

**Comment by d-v-b** [comment]
These are good points, and I now regret using the phrase "right thing", because array creation covers such a wide range of use-cases. 

Concerning checking array type, 'from_array' [already](https://github.com/dask/dask/blob/master/dask/array/core.py#L2649) checks whether the input has a `.chunks` attribute as a special convenience for `zarr` and `h5py` arrays; this already seems like a reasonable proxy for testing whether the input can be casually sliced. To me, it doesn't seem excessive for dask make reasonable assumptions about whether slicing will be expensive or not, especially if the payoff is more intuitive behavior from `from_array`.

Or maybe something could be added in graph optimization? I'm not sure.

**Comment by d-v-b** [comment]
But the cost of the current implementation of `from_array(large_np_array)` is that it produces very sub-optimal performance when deployed to a distributed scheduler (including `LocalCluster`).

**Comment by mrocklin** [comment]
> To me, it doesn't seem excessive for dask make reasonable assumptions about whether slicing will be expensive or not

This is obviously true.  It's never excessive to make reasonable assumptions.  

The question here really is "what is a reasonable assumption?".  This requires taking into account many possible situations.  I've laid out a possibility above.  The next thing to do in this process is to figure out what a good plan would be.

**Comment by d-v-b** [comment]
I don't know the dask internals well enough to feel too confident here, but I have a few ideas:

1. Keep `from_array` the way it is, maybe add some clarifying information about performance with in-memory arrays in the docstring. Also maybe add a section in the documentation on chunking to indicate that chunk size does not always determine the smallest amount of data that a worker receives. 
2. Add a new internal array creation routine optimized for in-memory arrays that uses slicing + stack / concatenate. Either present this routine as a peer function to `from_array`, or dispatch to it using a `kwarg` to `from_array`, e.g. `from_array(npy_array, in-memory=True)`, or make `from_array` dispatch silently to this new function based on the estimated in-memoryness of the input
3. Look into whether the "can I safely slice this?" logic could be added in graph optimization. If the root data can be safely sliced, elevate slicing operations up the task graph to the root to generate a new task graph with a chunk-sized root dependency. If I understand things correctly, the threaded scheduler should be immune to the issue we are discussing, so putting the solution in graph optimization might allow it to be scheduler-specific. 

I don't have the perspective to know how much stuff would break by making changes to `from_array`. Probably a lot of stuff would break. So maybe starting with a totally separate function that could be dispatched to in the future is easier?
