### ISSUE TITLE
Propose changing printed output from client object

### ISSUE THREAD

**Issue by jennirinker** [dask/distributed#3033]
# Summary of proposal

I find the client printout to be a little confusing, so I'd like to propose a modification. For example, here's what I'd like `print(client)` to return (for `processes=True`, `n_workers=3` and `threads_per_worker=2`):
```
<Client: scheduler='tcp://127.0.0.1:51788' n_workers=3 n_threads=6>
```
I think returning just the total number of workers and threads in the workers would be easier to understand and perhaps more useful for inexperienced users.

However, for more experienced users, we could add a new attribute (or more) to `Client` that contain information on the processes/threads configuration of the cluster. (E.g., how many processes for the nanny, scheduler, client, workers, etc. and how many threads in each process; this would also show how the workers and scheduler become threads in the client process when `process=False`) I don't know exactly what form this attribute(s) should be, so that's up for debate.

# Motivation

## Example of non-intuitive print statement

Here's an example of a non-intuitive (to me) output when printing the client instance:
```python
from dask.distributed import Client
with Client(n_workers=3) as client:
        print(client)
```
returns
```
<Client: scheduler='tcp://127.0.0.1:51788' processes=3 cores=6>
```
This makes it look like my laptop has 4 cores, but the `6` is actually a reference to the total number of threads.

## Example of incorrect print statement

Here's an example of a printed output that's actually incorrect:
```python
from dask.distributed import Client
with Client(processes=False, n_workers=3) as client:
        print(client)
```
returns
```
<Client: scheduler='tcp://127.0.0.1:51788' processes=3 cores=6>
```
but I don't see how there can be three processes if the workers are threads.

**Comment by TomAugspurger** [comment]
So the primary change is from `processes=` to `workers=`? That seems sensible to me.

**Comment by jennirinker** [comment]
I guess four things in total:  
1. `processes` to `n_workers`  
2. `cores` to `n_threads`  
3. Add an attribute (or more) with information on the processor/thread configuration.
4. Update the docs to reflect the new attributes/variable names

**Comment by TomAugspurger** [comment]
For item 3, check `Client.scheduler_info()`: https://distributed.dask.org/en/latest/api.html#distributed.Client.scheduler_info.

I have a slight preference for `workers=` rather than `n_workers=`, since this isn't intended to be an executable repr.

No preference on cores vs. threads.

**Comment by mrocklin** [comment]
Threads is more precise.  Cores is more interprettable by users.

**Comment by mrocklin** [comment]
Those are my thoughts anyway

**Comment by jennirinker** [comment]
Ok, `Client.scheduler_info()` looks like it already does most of what I was thinking. Apologies for not checking out the docs better.

For `n_workers` vs. `workers` I agree that `workers` is better, also because it matches the printout from a `LocalCluster` object.

I find `cores` a bit confusing because inexperienced users might think it's the same as the output from `multiprocessing.CPU_count()`. What about having the variable be called `nthreads`? In that case, the printout from `LocalCluster` and `Client` would be consistent, which I think would be good.

**Comment by GenevieveBuckley** [comment]
It seems like at some stage, the client `__repr__` has been updated. Now it says the number of processes and threads (so not the confusion you mention above, where "cores" used to show the number of threads instead)

```python
In [1]: from dask.distributed import Client
   ...: with Client(n_workers=3) as client:
   ...:         print(client)
   ...: 
<Client: 'tcp://127.0.0.1:45201' processes=3 threads=12, memory=15.40 GiB>
```

I'll close this now, since it looks like it's fixed in newer versions of Dask. Thanks @jennirinker
