### ISSUE TITLE
Security and user management

### ISSUE THREAD

**Issue by MaxNoe** [dask/distributed#304]
We just found out that I could delete files on a coworkers machine when he had running a `dworker` using something like

``` python
from distributed import Executor
from subprocess import check_call

e = Executor('schedulermachine')
e.submit(lambda: check_call(['rm', 'test_file']))
```

Is it planned to add some security features and/or user management to the library?

**Comment by mrocklin** [comment]
That's correct.  All users of a single scheduler are in the same memory space.  If you want to isolate users then each one should start up a separate scheduler and workers.

I don't see a way to isolate different users while also allowing the execution of arbitrary Python code.  All isolation and security should probably happen when deploying dask, such as with docker containers or other deployment technology.

**Comment by minrk** [comment]
I think dask cluster per user is the right way to go for this, so user management is probably out of scope. If there is an appropriate security feature, perhaps a way to use PKI and client certificates to authenticate/encrypt communication would be appropriate.

The Jupyter protocol adds basic authentication using HMAC signatures and a secret key that lives in the connection file, but no encryption, so people with access to the socket can spy on results, but not run code. If you used zmq, your could turn on both authentication and encryption with its CURVE support.

**Comment by mrocklin** [comment]
Perhaps tornado offers something similar?

**Comment by minrk** [comment]
Yes, you can set up SSL PKI with client certs, etc. in tornado. I imagine that should work for most people.

**Comment by mrocklin** [comment]
Dask supports TLS.  Closing.
