### ISSUE TITLE
document prometheus support and available metrics

### ISSUE THREAD

**Issue by arpit1997** [dask/distributed#3065]
related to https://github.com/dask/distributed/pull/2499 and https://github.com/dask/distributed/pull/2833

I can not find prometheus metrics support and available metrics documented at [dask-distributed](https://distributed.dask.org/en/latest/search.html?q=prometheus&check_keywords=yes&area=default).

Happy to contribute a PR.

**Comment by mrocklin** [comment]
Sounds good to me.  cc @jacobtomlinson in case he wants to track this

**Comment by arpit1997** [comment]
I would propose it under `additional-features -> Monitoring Dask Clusters`. But it might be a little bit confusing since we have a web interface section. 

Probably we can make a `Monitoring Dask Clusters` section in which we can have web interface and prometheus metrics pages. 

Would love to hear your thoughts on this. @mrocklin

**Comment by mrocklin** [comment]
I recommend making a standalone page.  I wouldn't be surprised if we
deprecate the web interface page in favor of the one on docs.dask.org.

**Comment by jacobtomlinson** [comment]
Yeah, I agree a `additional-features -> Monitoring Dask Clusters` page would be good. Thanks for offering to raise a PR for it.
