### ISSUE TITLE
distributed.core - WARNING - No handler found: register-worker

### ISSUE THREAD

**Issue by xiantianzhou** [dask/distributed#3068]
Hi, I am new to dask. I just installed it on different nodes in a cluster. The dask.distributed works fine in one node. But when I ran "dask-worker scheduler:8687 " on another node of the cluster, the server shows a warning:

"distributed.core - WARNING - No handler found: register-worker
Traceback (most recent call last):
  File "/home/dbms/anaconda3/lib/python3.6/site-packages/distributed/core.py", line 267, in handle_comm
    handler = self.handlers[op]
KeyError: 'register-worker'
"
Do you have some suggestions?

**Comment by TomAugspurger** [comment]
What versions do you have on the scheduler and worker machines?

**Comment by xiantianzhou** [comment]
Hi,
the scheduler machine:
               dask: 0.15.3
               distributed: 1.19.3
the worker machine:
                dask: 2.3.0
                distributed: 2.3.2
I got this error is because of different versions? what should I do to fix this error? Thank you.

**Comment by mrocklin** [comment]
Yes.  You should make sure that the versions are the same across all parts
of your Dask deployment.

**Comment by jrbourbeau** [comment]
@xiantianzhou does using the same software versions resolve this issue for you?

**Comment by xiantianzhou** [comment]
Yes. I just installed the same version on all the nodes. Now it works fine. Thank you so much.

**Comment by jrbourbeau** [comment]
Glad to hear things are working!
