### ISSUE TITLE
Why does dask need to serialise a task even though the function is present on the worker?

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3080]
When submitting a task with client.submit(), dask will submit the function via `self._send_to_scheduler` to the scheduler (in client.py). While doing that it appears to serialise the whole function that needs to be passed to the worker (in worker.py there's a function called `dumps_task` that is used for that). 

Why is it necessary to serialize the whole function? Wouldn't it be enough to just keep the name and then run that on the worker? I'm asking because in my case it takes several seconds to submit a task to the worker from the client and I have thousands of them. Because my function is very complex, I'm wondering why it is necessary to serialise it, even though it is present on all the workers.

**Comment by jrbourbeau** [comment]
One thing that comes to mind is it's not guaranteed submitted functions will exist on all worker. For example:

```python
In [1]: from distributed import Client

In [2]: client = Client()

In [3]: def inc(x):
   ...:     return x + 1
   ...:

In [4]: client.submit(inc, 1)
Out[4]: <Future: status: pending, key: inc-2b9f697075a1d9cc63d6949083fcf5ef>
```

The `inc` function isn't defined on the workers. There may be other reasons why serialization is needed, but this is just one reason that comes to mind.

**Comment by dickreuter** [comment]
Is there any way I can avoid having to transmit all functions to the workers, assuming all workers have the same code as the client?

**Comment by mrocklin** [comment]
Dask uses pickle or cloudpickle to serialize functions.  You can see how large your function is by calling `len(cloudpickle.dumps(func))`.

You might want to ask the cloudpickle developers how to ensure that functions can serialize efficiently.  

In the common case these libraries do serialize functions just as you suggest, by encoding the module and function names:

```python
In [1]: import math, pickle

In [2]: pickle.dumps(math.sin)
Out[2]: b'\x80\x03cmath\nsin\nq\x00.'
```

If you need more help with function serialization, you might consider asking questions or inspecting the code here: https://github.com/cloudpipe/cloudpickle

**Comment by dickreuter** [comment]
Do the dask workers need any of the code that they should execute or is a bare venv enough? How does dask distributed know if it needs to pickle the whole venv or just a function and the functions that are called by that function?

**Comment by dickreuter** [comment]
It appears the pickling is caused by nested python functions..

**Comment by mrocklin** [comment]
> Do the dask workers need any of the code that they should execute or is a bare venv enough? How does dask distributed know if it needs to pickle the whole venv or just a function and the functions that are called by that function?

We just call `cloudpickle.dumps/loads` and assume that that works.
