### ISSUE TITLE
how distributed memory is managed in dask

### ISSUE THREAD

**Issue by xiantianzhou** [dask/distributed#3082]
hi, I am struggling with reading files from workers.

The first question, I have one file test1.csv stored in node 1(worker 1).  And file test2.csv stored on node 2(worker 2). I want to read them and then doing sum separately. The path of these files is the same. The following is my code :
c = Client(dask scheduler ip address)
def readFile(filename):
        df = dd.read_csv('file:///path/to/file')
        mySum = df.v.sum().compute()
        print (mySum)
        return mySum

b1= c.submit(readFile, 'test1.csv', workers = ['worker1 ip address'])
b2 = c.submit(readFile, 'test2.csv', workers = ['worker2 ip address'])

however, even I ask the worker1 read from test1.csv, but sometimes it looks for test1.csv from node2. And worker2 looks for test2.csv on node1.

what should I do to read different file from different workers?

And also when I do client.scatter(), for example,
c = Client('dask-scheduler ip address')

a = [0,1,2,3,4,5,6,7,8,9,10]
b = c.scatter(a)

def mySum(b):
        Sum = sum(b)
        print(b)
        return Sum

s = c.submit(mySum, b)

Then I find each worker receives 10 elements. But I think each worker should have 5 data. What did I wrong?

Thank you.

**Comment by mrocklin** [comment]
It looks like you're running Dask code within a function submitted to Dask.  This sort of nesting is rarely necessary and probably not what you want.

**Comment by xiantianzhou** [comment]
Thank you for your reply. 

But when I read file which located in the worker, it showed to me "No such file". Here is my code:

def readFile(filename):
        df = dd.read_csv('test03.csv')
        mySum = df.v.sum().compute()
        return mySum

b1= c.submit(readFile, 'test03.csv', workers = [worker address])

I checked with client.run(os.listdir, my_directory). The file is there. what did I wrong?

Thank you.

**Comment by mrocklin** [comment]
I do not see why you are using client.submit here.  I recommend just using
dd.read_csv directly.  You are mixing Dask's futures API and it's Dataframe
API.  You should use one or the other but not both.

**Comment by xiantianzhou** [comment]
I understand now. Thank you very much.

**Comment by xiantianzhou** [comment]
I changed the code to dd.read_csv() in the function called. Now it works. Thank you so much.
