### ISSUE TITLE
Proposed additions to `dask-ssh` CLI

### ISSUE THREAD

**Issue by gforsyth** [dask/distributed#3091]
I've been using `dask-ssh` the last few days and it has been super helpful. Thanks!

I've run into two small things that I think might be of benefit to others to add but wanted to check in (especially given what looks like an upcoming switchover to `asyncssh`).

1. `dask-ssh` keeps an SSH connection open while the scheduler and clients are running -- killing the process also shuts down the remote workers (this seems good). However, SSH timeouts also cause this to break and fall over. `paramiko` (which is currently driving the show here) can send some noise over the wire to keep the connection "active". This could be an optional way (given some `--keepalive` flag) to work around timeouts.  Might also be a bit of scope creep, but I thought I'd raise it.

2. Add an option to disable `StrictHostKeyChecking` -- shouldn't be the default, but if you've just spun up resources to add to a cluster, you might not worry so much about having those machines in `known_hosts`.

Let me know if either/both of these are of interest and I'm happy to take them on.

**Comment by mrocklin** [comment]
Hi @gforsyth !  I'm very glad to see that you're engaging with Dask and SSH.  

One of the biggest surprises of our user survey was that SSH is the most common deployment strategy, so improvements here likely have high impact.

Have you tried the solution in distributed.deploy.ssh2 ?  This new implementation isn't as battle-tested as the one that you're currently using, but I think that it's probably easier to manipulate.  It just passes most things through to asyncssh and the workers.

https://github.com/dask/distributed/blob/f7f6bd77ab8d28d8811b94aa84528d3a470f1ff1/distributed/deploy/ssh2.py#L193-L213

**Comment by gforsyth** [comment]
Thanks for the pointer, @mrocklin !  I'll take a look and see if key checking and keepalive are valid additions to the newer implementation.

**Comment by mrocklin** [comment]
My hope is that we're able to defer those questions entirely to "are key checking and keepalives valid options in asyncssh" and that Dask gets to extract itself from that conversation.

**Comment by gforsyth** [comment]
Looking at https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnectionOptions

it would seem that setting `known_hosts` to `None` will handle host checking issues and it's also possible to set `keepalive_interval` to send a ping to keep the connection active.  I'll test both of these out -- the configs can always be added as additional examples to the docstrings.

**Comment by mrocklin** [comment]
Any update here @gforsyth ?  Did this approach end up resolving your problem?

**Comment by gforsyth** [comment]
Hey @mrocklin -- I have a PR incoming with a fix for the existing implementation to keep the connection alive.  It looks like `asyncssh` does support both options so those can just be passed along by `dask` although I ran into some other issues while testing that out.

**Comment by mrocklin** [comment]
Grand.  Thanks Gil

**Comment by gforsyth** [comment]
disabling host key checking is available now and the "legacy" dask-ssh CLI keeps the connection alive, so I'm closing this out.

**Comment by mrocklin** [comment]
Thanks Gil!
