### ISSUE TITLE
Dask worker having memory leaks

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3096]
I have a process that runs around 500 client.submit() with dask distributed.

I have noticed that memory usage is gradually increasing on each worker. This only happens when I'm calling the tasks over dask distributed, but not when I call them directly in sequence.

What's the best way to detect / trace down memory leaks that coud be caused the a dask worker?

**Comment by mrocklin** [comment]
> What's the best way to detect / trace down memory leaks that coud be caused the a dask worker?

Just however you would do this normally in Python.  You might find things easier if you put them all in the same process/thread with the async mechanisms.

**Comment by mrocklin** [comment]
(my apologies for the delayed response)

**Comment by TomAugspurger** [comment]
Just FYI, there are [many issues](https://github.com/dask/distributed/search?q=memory+leak&type=Issues) reporting seeming memory leaks. https://github.com/dask/distributed/issues/2757 went into some depth and things *maybe* point to Python's object allocater, but it's hard (for me) to say for certain.

**Comment by mrocklin** [comment]
Thanks for the summary @TomAugspurger .  Closing this as it's handled elsewhere.
