### ISSUE TITLE
Does Dask Distributed or dask_cudf supports Apache Arrow Flight batch stream for IO?

### ISSUE THREAD

**Issue by vnkesarwani** [dask/distributed#3097]
I am sharing my data in arrow format in arrow flight as a stream; and need to consume it from dask_cudf in GPU.

What i tried 
 - read arrow batch stream as a table.
 - Create cudf
 - pass it to dask_cudf.
 
This works for small data, but reading full stream as a single arrow table into cudf may cause out of memory error.

Is there any better way out of the box in dask distributed or in dask_cudf to read/write to Arrow Flight Buffer?

**Comment by mrocklin** [comment]
You would probably want to use something like Dask Delayed, and then convert those calls to a Dask Dataframe.  

https://docs.dask.org/en/latest/delayed-collections.html

**Comment by vnkesarwani** [comment]
Thanks @mrocklin.
