### ISSUE TITLE
Bottleneck w/ mapping?

### ISSUE THREAD

**Issue by cicdw** [dask/distributed#3108]
This is probably more of an implementation question than a bug, but I've got a decent-sized class with a method that I want to map over.  

```python
import cloudpickle
import sys

class LargeRunner:
    large_obj = list(range(50000)) # makes the class "large"
    def run(self, x):
        print(x)
        return x + 1

runner = LargeRunner()
sys.getsizeof(cloudpickle.dumps(runner.run)) # 150547 ~ 0.15MB
```
If I was being naive, here's what I might do:

```python
from distributed import Client

client = Client("tcp://10.0.0.41:8786")

def submit_in_sequence():
    futs = []
    for i in range(2000):
        futs.append(client.submit(runner.run, i))
    return client.gather(futs)

%time results = submit_in_sequence() # 2min 46s
```
which ultimately submits all the worker to a single worker in sequence, and notably the work begins immediately.

If, however, I use mapping:

```python
def map_over_sequence():
    return client.gather(client.map(runner.run, list(range(2000))))

%time results = map_over_sequence() # 2min 59s
```
then everything hangs for a long time and the work is all executed essentially simultaneously in the last few seconds.

The delay in the start of execution + the difference in execution time becomes more of an issue as:
- the length of what I'm mapping over increases
- the length of time the computation takes increases (I'd rather computations begin sooner rather than later).
- the size of the class increases

This result surprised me as the callable payload is fixed in the mapped case so I would've expected it to take significantly _less_ time, but I imagine there's a good reason for it (maybe scheduling overhead?).

**Comment by mrocklin** [comment]
Each individual task has to have a self-contained copy of the function to be called.  So my guess is that the cost here is in transferring a large number of sizable bytestrings.

The simplest thing to do here would be to make the function itself a task that is tracked by dask, perhaps like the following:

```python
obj = dask.delayed(obj)

futures = client.map(apply, [obj.method] * len(L), L)
```

This way we only include the serialized form of the class in the graph once, and we include many pointers to that class.

**Comment by cicdw** [comment]
Hey @mrocklin - excellent! Using `dask.delayed` didn't work for me, but this did:

```python
def apply(func, *args, **kwargs):
    return func(*args, **kwargs)

def run_with_apply():
    func = client.scatter(runner.run)
    return client.gather(client.map(apply, [func] * 2000, list(range(2000))))

%time run_with_apply()  # Wall time: 5.46 s
```

I'm wondering if this is an optimization `client.map` could possibly make under the hood to prevent users from having to do this?  Not sure of the overhead or whether that adds other complications for more normal use-cases of mapping, but I'd be happy to take a stab at it if you think it's worthwhile.

**Comment by mrocklin** [comment]
To be clear though, for future readers, mostly the solution to this is to avoid sending through functions that are very large and difficult to serialize.  Mostly this means that you should try to avoid closures, methods on large classes, and dynamically generated functions.  Cloudpickle, the library that Dask uses for serialization, can handle all of these, but they are costly, both in serailization time and size.  It's much nicer to send through functions that don't rely on external state.

**Comment by RAMitchell** [comment]
We had a very similar problem to this where client.map was taking far too long before executing the function. The problem was not the size of the function but the serialized size of one of the function arguments being unexpectedly large as it contained a reference to an entire data frame.

I would encourage anyone who encounters this to systematically check the serialized size of both the function and all of its arguments using something like this:
```
import cloudpickle
import sys
sys.getsizeof(cloudpickle.dumps(arg))
```
