### ISSUE TITLE
Can't pass future to Actor

### ISSUE THREAD

**Issue by zachary62** [dask/distributed#3113]
Here's a minimal example:
```
class Counter:
    n = 0

    def __init__(self):
        self.n = 0

    def increment(self):
        self.n += 1
        return self.n

    def add(self, x):
        self.n += x
        return self.n
    
def fix_num():
    return 1

from dask.distributed import Client          # Start a Dask Client
client = Client()

future = client.submit(Counter, actor=True)  # Create a Counter on a worker
counter = future.result()                    # Get back a pointer to that object

num = client.submit(fix_num)
future = counter.add(num)   
```
error message:
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f9564e9bc88>>, <Future finished exception=Exception("unsupported operand type(s) for +=: 'int' and 'Future'")>)

Currently, I want to use dask distributed to apply machine learning model. I use actor because I want worker to load model only once and memorize the state. However, actor doesn't seem to support future arguments. I don't want to pass future.result() because I want to pass testing dataset to worker which is loaded by another worker and is assumed to be very large.

**Comment by mrocklin** [comment]
> However, actor doesn't seem to support future arguments. 

Yes, actors are intentionally very simple.  In particular, they aren't integrated into the task scheduling system.  The caller of the actor never has to check in with the scheduler to see if the future is finished or not.  This is what allows actors to be fast.

> I don't want to pass future.result() because I want to pass testing dataset to worker which is loaded by another worker and is assumed to be very large

You might want to call `future.result()` inside the actor instead

**Comment by zachary62** [comment]
Your suggestion solves my problem! Thank you a lot!
