### ISSUE TITLE
Scheduler Dashboard Workers Link not working - distrbuted 2.5.2

### ISSUE THREAD

**Issue by ameetshah1983** [dask/distributed#3120]
Trying to upgrade distributed 1.25.3 to latest 2.5.2. On doing so the workers link is not working for dashboard - http://localhost:8787/workers. Have the following versions - 

dask - 2.5.2
distributed  - 2.5.2
bokeh - 1.3.4
tornado - 6.0.3

Also if cl = Client() is started, the Bytes Stored on Status page keeps incrementing. We are running this on windows machines.

**Comment by mrocklin** [comment]
Hi @ameetshah1983 .  Unfortunately this works well for me, and on our test systems, so there must be something else going on.  

Do you have any other ideas for what might be going wrong?  maybe there are some errors in logs, either in Python or in your browser?

**Comment by JSybrandt** [comment]
Doesn't work for me either.
I'm also on dask 2.5.2, distributed 2.5.2 and bokeh 1.3.4
I'm on linux and using python 3.7
It was working yesterday before I upgraded.

**Comment by mrocklin** [comment]
Great.  If either of you could help by providing logs or error messages that would be very welcome.  There isn't much that can be done without more information about what is going on.

**Comment by ameetshah1983** [comment]
No errors recorded in chrome developer console. All statuses show 200 except for ws?bokeh-protocol-version which is 101 same as 2.5.1 version. 

However main difference between the two is that for 2.5.1 it has additional 2 data links / enteries for the data:image/gif which are not present for 2.5.2.

**Comment by mrocklin** [comment]
You could also try using `git bisect` to find the bad commit.  That would
be helpful to narrow down what introduced the bug for you.

**Comment by ameetshah1983** [comment]
Diffing the code between 2.5.1 and 2.5.2, the code that directly impacts the page looks like the bandwidth calculation for the workers that seems to be updated. Will try and narrow it down more and get back.

**Comment by mrocklin** [comment]
Thanks for your efforts here @ameetshah1983

**Comment by ameetshah1983** [comment]
Looks like if commit 52d3e057721802ee725d71448b6f7ef17a8e515a is reverted from master or v2.5.2, it then works fine.
Commit Title - Collect worker-worker and type bandwidth information (#3094) 
https://github.com/dask/distributed/commit/52d3e057721802ee725d71448b6f7ef17a8e515a

Hope this helps.

**Comment by mrocklin** [comment]
Can you run the following command and verify that it does not produce an error:

```python
client.get_versions(check=True)
```

**Comment by ameetshah1983** [comment]
The command spit out a json and had no errors when running. Also both scheduler and workers are on the same machine and the cluster was created using command - 

> cl = Client()

**Comment by darindf** [comment]
I am having the same issue using 

dask 2.5.2, 
distributed 2.5.2 
bokeh 1.3.4
python 3.7
on windows 10

I see there is an error being reported in the browser, which I've enclosed here. 

![image](https://user-images.githubusercontent.com/3588158/66660742-9d9a5780-ebfa-11e9-8d65-8254c38ceef4.png)

**Comment by mrocklin** [comment]
I can reproduce.  I'm looking into it.
