### ISSUE TITLE
Scatter question

### ISSUE THREAD

**Issue by darindf** [dask/distributed#3125]
I have some questions about the use of scatter.

I have added a call to use scatter to distribute data to all of the workers, i.e. broadcast is true. That is rather straight forward and returns a future in finished state.

Each worker then may run one or more tasks, via submit, with the scatter future passed as a parameter.  

Once all of the multiple tasks, using the future, are completed, I would like to reclaim (free storage) of the scatter future. 

What is the process to free the data that scatter distributed? Can one use cancel on the future?

The algorithm that is being used is traversing a graph, where the graph requires the parent node to be completed before the children can be started. Once the parent completes, it can schedule (via submit) all of the children tasks in parallel, and when one of the child nodes complete, it can then schedule grand children. Thus, depending on the amount of work a node has, the graph can be expanded, where a one path from the root is expanding level 4 in the tree, while another path from the rot is still executing a level 2 node, as the dependency is only between parent and child. 

The other question, is how does the worker decide on when to gc the future?  All of these tasks will need to access the scatter data. 

How (or when) does the worker decide to delete or gc the future? For example could I could call scatter before task 1 starts, then task 1 executes and completes (via submit) on the worker, then could the scatter future be reclaimed, before task 2 is created and submitted to the worker? 

For submitted tasks, I can use wait, gather, as_completed to get notifications that tasks/futures completes, for the scatter future it doesn't make sense to use these, but I would like to end the life cyle of the scatter future, and not sure what is the best practice.

**Comment by TomAugspurger** [comment]
> What is the process to free the data that scatter distributed?

If I understand your question, deleting the future should suffice. Futures follow the usual memory rules of Python objects.

```python
data = b'0' * dask.utils.parse_bytes("500Mb")
fut = c.scatter(data, broadcast=True)

# do stuff
del fut
```

**Comment by TomAugspurger** [comment]
Hopefully https://distributed.dask.org/en/latest/memory.html#clearing-data explains this clearly.

**Comment by darindf** [comment]
Thanks for the link. I gather there is not difference between clearing remote data that is either persisted or scattered, i.e. using del 

```del df  # Deleting local data often deletes remote data```

will remove both types of data distribution.

I guess I'm caught up with the differences between clearing data vs computations, as with clearing remote computations one uses
```
 client.cancel(df)  # kills df, df2, and every other dependent computation
```

One further question is scatter with broadcast being true, equal to calling persist?

**Comment by TomAugspurger** [comment]
> One further question is scatter with broadcast being true, equal to calling persist?

No. Persist only operates on dask collections.

**Comment by GenevieveBuckley** [comment]
I hope those tips from Tom helped you solve your problem. Thanks @darindf!
