### ISSUE TITLE
as_completed timeout

### ISSUE THREAD

**Issue by CJ-Wright** [dask/distributed#3131]
Would it be possible to have a timeout with `as_completed` similar to the `concurrent.futures.as_completed` timeout capability?

**Comment by mrocklin** [comment]
Seems fine to me.

**Comment by ameetshah1983** [comment]
This would be a very helpful feature to have. Would it be possible to have this added to as_completed.

**Comment by mrocklin** [comment]
Seems fine to me.

**Comment by CJ-Wright** [comment]
xref: https://github.com/dask/distributed/pull/3133

**Comment by hendrikmakait** [comment]
Closed by #7811
