### ISSUE TITLE
Rename executables from dfoo to dask-foo

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#314]
This would involve the following changes:

    dscheduler -> dask-scheduler
    dworker -> dask-worker
    ...

Any objections/thoughts?  We would need to go through a deprecation cycle.

**Comment by minrk** [comment]
👍 from me

**Comment by scopatz** [comment]
Sounds reasonable, though it seems like it would couple distributed to dask pretty strongly.  I am not sure how many people want to use distributed without dask, so it is probably not a big deal

**Comment by mrocklin** [comment]
It only couples the two in name, which is seems reasonable to me.  The name `distributed` is overly generic and the projects are fairly related.
