### ISSUE TITLE
Distributed holding onto references until exit

### ISSUE THREAD

**Issue by kkraus14** [dask/distributed#3144]
We're currently having an issue with [RMM](https://github.com/rapidsai/rmm.git) where we register a `finalize` method via `atexit.register(...)` and Distributed is holding onto objects expecting to call `rmmFree` until the atexit function stack starts executing. The Distributed atexit thread cleanup is lower in the Stack than the `rmmFinalize` call, but I'd expect these threads to have essentially no references at this point. Stacktrace from pdb stepping below:

```
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/local.py(240)close_clusters()
-> @atexit.register
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/local.py(242)close_clusters()
-> for cluster in list(clusters_to_close):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(67)__len__()
-> def __len__(self):
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(68)__len__()->0
-> return len(self.data) - len(self._pending_removals)
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/local.py(242)close_clusters()->None
-> for cluster in list(clusters_to_close):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/process.py(328)_cleanup_dangling()
-> @atexit.register
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/process.py(330)_cleanup_dangling()
-> for proc in list(_dangling):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(67)__len__()
-> def __len__(self):
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(68)__len__()->0
-> return len(self.data) - len(self._pending_removals)
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/process.py(330)_cleanup_dangling()->None
-> for proc in list(_dangling):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(569)close_clusters()
-> @atexit.register
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(571)close_clusters()
-> for cluster in list(SpecCluster._instances):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(67)__len__()
-> def __len__(self):
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/_weakrefset.py(68)__len__()->1
-> return len(self.data) - len(self._pending_removals)
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(572)close_clusters()
-> with ignoring(gen.TimeoutError):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/contextlib.py(157)helper()
-> @wraps(func)
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/contextlib.py(159)helper()-><contextlib._...x7fcc0cb3a1d0>
-> return _GeneratorContextManager(func, args, kwds)
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(573)close_clusters()
-> if cluster.status != "closed":
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/contextlib.py(85)__exit__()
-> def __exit__(self, type, value, traceback):
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/contextlib.py(90)__exit__()->False
-> return False
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(571)close_clusters()
-> for cluster in list(SpecCluster._instances):
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/deploy/spec.py(571)close_clusters()->None
-> for cluster in list(SpecCluster._instances):
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(4492)_close_global_client()
-> def _close_global_client():
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(4497)_close_global_client()
-> c = _get_global_client()
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(101)_get_global_client()
-> def _get_global_client():
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(110)_get_global_client()->None
-> return None
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(4498)_close_global_client()
-> if c is not None:
(Pdb)
--Return--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/client.py(4498)_close_global_client()->None
-> if c is not None:
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/_concurrent_futures_thread.py(40)_python_exit()
-> def _python_exit():
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/_concurrent_futures_thread.py(42)_python_exit()
-> _shutdown = True
(Pdb)
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/distributed/_concurrent_futures_thread.py(43)_python_exit()
-> items = list(_threads_queues.items())
(Pdb)
--Call--
> /home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/weakref.py(438)items()
-> def items(self):
(Pdb)
nvcategory destructor: 94339368547184
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: cudaErrorInitializationError: initialization error
Fatal Python error: Aborted

Current thread 0x00007fcc415f2740 (most recent call first):
  File "/home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/nvstrings_cuda101-0.0.0.dev0-py3.6-linux-x86_64.egg/nvcategory.py", line 173 in _destroy_nvcategory_instance
  File "/home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/weakref.py", line 548 in __call__
  File "/home/nfs/kkraus/miniconda3/envs/cudf_dev/lib/python3.6/weakref.py", line 624 in _exitfunc
Aborted (core dumped)
```

Will work on getting a reproducer.

**Comment by kkraus14** [comment]
Minimal reproducer (Sorry for it not being more minimal...):
```
 from streamz import Stream
 from streamz.dataframe import DataFrame
 import cudf


 if __name__ == "__main__":
     func = lambda x: x.sum()
     stream = Stream()
     df = cudf.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
     sdf = DataFrame(example=df, stream=stream)
     df_out = func(sdf).stream.gather().sink_to_list()
     sdf.emit(df)
```

**Comment by quasiben** [comment]
I just ran the above without issue but I may need a newer RMM:

> rmm                       0.10.0a191001           py37_94    rapidsai-nightly

**Comment by kkraus14** [comment]
@quasiben this may depend on a couple of inflight changes that are blocked by this in hindsight: https://github.com/rapidsai/rmm/pull/157, https://github.com/rapidsai/cudf/pull/3061

**Comment by mrocklin** [comment]
It looks like there is a pending result sitting in a queue of the ThreadPoolExecutor of a worker of a cluster.  So probably some task was running in a thread when we shut things down and that thread still pushed that result to the work queue in ThreadPoolExecutor after it finished?

Question: Is the cluster that ran this closed already?

One fix here would be to change the `ThreadPoolExecutor.shutdown` method to clear out all of the work queues if we're not waiting.  I'm curious if we're actually waiting on shutdown or not though.  From what I can see, we *seem* to wait for all threads to clear out by default.  Is it easy for you to print out `wait` here?

https://github.com/dask/distributed/blob/00d7f7dfff47cf2aa67dd220c15d3ccaebbabcc8/distributed/_concurrent_futures_thread.py#L159-L165

Looking at the code, I'm pretty sure that we wait.  However I also don't see how we can still have a work item in a queue if wait is anything but False.

**Comment by kkraus14** [comment]
> Question: Is the cluster that ran this closed already?

The cluster isn't manually shut down as part of the Python script / pytest and it looks like it closes as part of the atexit stack.

> Is it easy for you to print out `wait` here?

I tried naively adding a print there and it didn't bubble its way up in running normally or via pdb. Are we sure the `shutdown` function gets called? I'm only seeing https://github.com/dask/distributed/blob/master/distributed/_concurrent_futures_thread.py#L40-L47 from the atexit registration.

**Comment by mrocklin** [comment]
> The cluster isn't manually shut down as part of the Python script / pytest and it looks like it closes as part of the atexit stack.

I would expect that the `client.close()` call in your pytest fixture would also close the cluster.  Can you verify this with 

```python
assert client.cluster.status == "closed"
```

just after the `client.close()` line?

**Comment by mrocklin** [comment]
> Are we sure the shutdown function gets called

I would expect it to be called as part of `cluster.close()`

**Comment by kkraus14** [comment]
> > The cluster isn't manually shut down as part of the Python script / pytest and it looks like it closes as part of the atexit stack.
> 
> I would expect that the `client.close()` call in your pytest fixture would also close the cluster. Can you verify this with
> 
> ```python
> assert client.cluster.status == "closed"
> ```
> 
> just after the `client.close()` line?

To be clear, I've commented all of this out and am using the minimal reproducer above. I'm struggling to find where this is even calling distributed code.

**Comment by kkraus14** [comment]
I've confirmed uninstalling distributed resolves the issue and the distributed atexit functions occur when importing either streamz class above.

**Comment by mrocklin** [comment]
> The cluster isn't manually shut down as part of the Python script / pytest and it looks like it closes as part of the atexit stack.

OK, so would it make sense to interpret your concern in the following way?

"I believe that at the end of this computation no references should exist to cudf objects, and yet some part of the dask.distributed machiner seems to be holding onto them.  It would be nice to verify that all references get flushed out."

**Comment by mrocklin** [comment]
Oh, nm, you're saying that you're not actually calling into Dask, never mind the last comment.

**Comment by kkraus14** [comment]
So somewhere the StreamZ library is calling into Distributed (I haven't been able to track down where yet), and it seems that there's a single dangling reference that doesn't get cleaned up until very deep in the atexit stack at which point RMM and Numba have cleaned themselves up so RMM / CUDA are in an uninitialized state.

**Comment by mrocklin** [comment]
I tried your same script, but replaced cudf with pandas (it's easier for me to experiment on my laptop) and I added a breakpoint here and didn't get anything

```diff
diff --git a/distributed/deploy/spec.py b/distributed/deploy/spec.py
index 11ff3b44..dc8ffee8 100644
--- a/distributed/deploy/spec.py
+++ b/distributed/deploy/spec.py
@@ -569,6 +569,7 @@ class SpecCluster(Cluster):
 @atexit.register
 def close_clusters():
     for cluster in list(SpecCluster._instances):
+        breeakpoint()
         with ignoring(gen.TimeoutError):
             if cluster.status != "closed":
                 cluster.close(timeout=10)
```

**Comment by mrocklin** [comment]
Maybe the thing to do here is to add a breakpoint in `LocalCluster` to see where that is being called.  I agree with you that we shouldn't be constructing any clusters in your code.

**Comment by kkraus14** [comment]
I inserted a breakpoint into the LocalCluster `__init__` and didn't get anything either.

**Comment by kkraus14** [comment]
Okay, streamz seems to be calling into `distributed.client.default_client()` even if not creating a DaskStream and that's what creates the cluster.

**Comment by kkraus14** [comment]
Just another note: if you move the `import cudf` above the streamz imports then it makes the rmm finalization happen *after* distributed finalizations and things work as expected.

**Comment by mrocklin** [comment]
It sounds like maybe streamz shouldn't be calling `default_client`.  What was the call stack that triggered that call?

**Comment by kkraus14** [comment]
Sorry, I don't think it's necessarily calling `default_client()` but it's importing default_client and importing things from Dask is enough to register the atexit functions. https://github.com/python-streamz/streamz/blob/master/streamz/dask.py This will get imported on streamz import if possible.

**Comment by mrocklin** [comment]
Sure, but your traceback shows, I think, that there is a Cluster object
around, which seems weird to me.

**Comment by kkraus14** [comment]
@mrocklin and I connected via video chat to dive into things and isolated it to: https://github.com/dask/distributed/blob/master/distributed/utils.py#L1358-L1365

**Comment by mrocklin** [comment]
I would try putting those lines directly into your script, and removing the distributed import. 

```python
import weakref
from concurrent.future import ThreadPoolExecutor

_offload_executor = ThreadPoolExecutor(
        max_workers=1, thread_name_prefix="Dask-Offload"
)

weakref.finalize(_offload_executor, _offload_executor.shutdown)
```

**Comment by mrocklin** [comment]
You could also take this further by creating a thread and then joining on it during shutdown.  Maybe something like this?

```python
from threading import Thread
import time

def f():
    time.sleep(2)

thread = Thread(target=f, daemon=True)

weakref.finalize(thread, thread.join)
```

**Comment by kkraus14** [comment]
Confirmed the above reproduces without distributed, new minimal reproducer:
```python
# from dask import distributed
import weakref
from concurrent.futures import ThreadPoolExecutor

try:
    _offload_executor = ThreadPoolExecutor(
        max_workers=1, thread_name_prefix="Dask-Offload"
    )
except TypeError:
    _offload_executor = ThreadPoolExecutor(max_workers=1)

weakref.finalize(_offload_executor, _offload_executor.shutdown)


import cudf


if __name__ == "__main__":
    df = cudf.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
    summed_df = df.sum()
```

**Comment by kkraus14** [comment]
@mrocklin the above with the Thread triggers it as well.

**Comment by kkraus14** [comment]
FWIW moving from an `atexit.register` to creating a dummy object in the `__init__.py` of the module and creating a `weakref.finalize` against it seems to have resolved this problem for us. I'm still not sure on the root cause or what exactly is happening, but for some reason with a Thread being spawned before importing rmm (daemon or not) it would screw up the atexit call order if a weakref finalize was registered for the Thread. *shrug*
