### ISSUE TITLE
Unexpected kwargs error

### ISSUE THREAD

**Issue by cicdw** [dask/distributed#3151]
It appears that https://github.com/dask/distributed/pull/3117 introduced a check for whether certain kwargs were used when initializing a `Client`.

Previously, this sort of pattern was allowed:
```python
from distributed import Client

c = Client(processes=True, silence_logs=True)
```
with the expectation that these kwargs were passed down to the `LocalCluster` object which is created when a scheduler address is not provided.  Now this raises:
```python
ValueError: Unexpected keyword arguments: ['processes', 'silence_logs']
```

- is this an unsupported use of the API with the release of 2.6.0?
- or should Dask only be raising these kwarg errors whenever a `scheduler_address` is actually passed?

**Comment by cicdw** [comment]
Update: I'm using a utility function to create Clients, in which I always pass those two keyword arguments even when I'm connecting to a known scheduler address, so I suppose this is on me to change how I do this.

**Comment by cicdw** [comment]
That works for me! I had forgotten that these clients were created with this utility which force-fed the kwargs when I originally opened the issue - I've already fixed it on my side 👍

**Comment by SOUMYASHUKLA** [comment]
I am trying to get rid of contineous rolling of worker warnings on the console. 
I tried Unexpected keyword arguments: client(..., silence_logs=30) but it does not work. Also checked in the distributed.yaml file. I did not find any particular setting for this.
How can I do this with the new version of dask?

**Comment by fjetter** [comment]
@SOUMYASHUKLA this exception is only raised if you are providing an address. Either you provide an address to an existing cluster or we'll use the extra kwargs to initialize a new LocalCluster. Both is not possible. If you are still experiencing issues, may I ask you to open a new issue with your specific exception and traceback?

**Comment by bryanwweber** [comment]
@SOUMYASHUKLA I suspect this would be a better topic for the Discourse group, here: https://dask.discourse.group/ since it is about using Dask/distributed, and not so much about a bug report. Please let me know if you have any questions :smile:

**Comment by SOUMYASHUKLA** [comment]
@bryanwweber Thank you. This issue was reported already at [discourse discussion] :)(https://dask.discourse.group/t/unexpected-dask-cluster-behavior-on-docker-setup/370/3)

**Comment by bryanwweber** [comment]
@SOUMYASHUKLA Great, then let's avoid duplicating discussion here.

**Comment by kchawla-pi** [comment]
> @SOUMYASHUKLA this exception is only raised if you are providing an address. Either you provide an address to an existing cluster or we'll use the extra kwargs to initialize a new LocalCluster. Both is not possible. If you are still experiencing issues, may I ask you to open a new issue with your specific exception and traceback?

This should be added in the documentation. If it has been, in a more prominent place; I perused the documentation and never saw this.
