### ISSUE TITLE
Debug Scheduler and Web Pages

### ISSUE THREAD

**Issue by darindf** [dask/distributed#3155]
I was reviewing the documentation about the [worker and scheduler web pages](https://distributed.dask.org/en/latest/web.html) and noticed they have a section for additional debugging web pages

> Debug Scheduler pages at http://scheduler-address:8788. These pages have more detailed diagnostic information about the scheduler. They are more often used by developers than by users, but may still be of interest to the performance-conscious. These pages run from inside the scheduler process, and so compete for resources with the main scheduler.
Debug Worker pages for each worker at http://worker-address:8789. These pages have detailed diagnostic information about the worker. Like the diagnostic scheduler pages they are of more utility to developers or to people looking to understand the performance of their underlying cluster. If port 8789 is unavailable (for example it is in use by another worker) then a random port is chosen. A list of all ports can be obtained from looking at the service ports for each worker in the result of calling client.scheduler_info()

Using tcpview to view the ports bound to scheduler and worker, I do not see these ports listed. Besides the scheduler address and dashboard, 8786 and 8787, respectively, I see two additional ports in the higher port range, in this case 62476, and 62477, which are established and not in listening state. 

Is the documentation incorrect on this issue, or is additional configuration required?

**Comment by mrocklin** [comment]
That documentation is outdated
