### ISSUE TITLE
Waiting to connect to...

### ISSUE THREAD

**Issue by rymoore** [dask/distributed#3169]
I am starting a Dask cluster on VMs in an Azure subnet (I've done the same in AWS). These VMs should have completely open ports within the subnet, but I'm seeing the following:

![Screenshot 2019-10-24 14 23](https://user-images.githubusercontent.com/13695135/67518412-64d29780-f66a-11e9-82e8-3d4e9b45c947.png)

The workers just infinitely respond "Waiting to connect to..." the scheduler node. Any suggestions on how to debug this?

**Comment by jrbourbeau** [comment]
Are both workers not able to connect? It looks like worker `10.0.2.5` can connect but `10.0.2.6` can't. I'm not very familiar with networking on Azure, is the scheduler available to worker `10.0.2.6`?

**Comment by mrocklin** [comment]
My guess here is that there are a few networking interfaces available, not all of which are universally accessible.  You might consider using the `--interface` keyword to specify a network interface that is open between the scheduler and workers.

**Comment by rymoore** [comment]
It turned out to be a firewall issue. Thanks!
