### ISSUE TITLE
[Q] Why cloudpickle never used to deserialize?

### ISSUE THREAD

**Issue by rs2** [dask/distributed#3170]
Why is it that `pickle` protocol never attempts to deserialize the payload using `cloudpickle`?

There are examples where payload serialized using `cloudpickle` cannot be deserialized using `pickle`.

Reference: https://github.com/dask/distributed/blob/cc4fc7d8fe42c41b328ade1db54dd88da904244a/distributed/protocol/pickle.py#L57-L62

**Comment by TomAugspurger** [comment]
Do you an example of a payload serialized with cloudpickle that can't be loaded with pickle?

**Comment by hdoupe** [comment]
I may be wrong, but I think cloud pickle only serializes data and [uses pickle to load the data back](https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L1132-L1133).

**Comment by mrocklin** [comment]
That's correct

**Comment by TomAugspurger** [comment]
Thanks for the clarification @hdoupe.

@rs2 the cloudpickle devs may be interested in hearing of examples that can't be deserialized with `pickle`.
