### ISSUE TITLE
Add ability to kill futures that are kicked off via fire_and_forget

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3189]
In some circumstances, it is necessary to kick off long-running jobs via fire_and_forget, for example when a future is started via a restful interface that needs to return an immediate value (e.g. job id). The job is then started, but it's not clear how it can be traced back and even killed in the future. Is there a way to do this already or is this a functionality that could be added in the future?

**Comment by mrocklin** [comment]
You could keep track of the future, and then call `future.cancel()` if you want to cancel the job.

If it is hard for you to keep track of the future then you could name the future, and then recreate the future later with the same name and then cancel it.

```python
future = client.submit(..., name="foo-123")
fire_and_forget(future)
...

future = Future("foo-123")  # should double check that you don't need something else here
future.cancel()
```

**Comment by dickreuter** [comment]
`client.submit(..., name="foo-123")` would currently simply pass an argument 'name' to the function. It's not something that currently appears to be implemented in dask to give futures a name. Is this correct?

**Comment by jrbourbeau** [comment]
@dickreuter there's a `key=` parameter in `Client.submit` that lets you manually provide a name for a task (https://distributed.dask.org/en/latest/api.html#distributed.Client.submit)

**Comment by mrocklin** [comment]
Ah yes, my mistake.  Thanks James

**Comment by dickreuter** [comment]
ok that's fine, but then it's not clear how I can query the scheduler for running jobs. `future = Future("foo-123")` won't tell it to what scheduler to connect, so there needs to be some kind of client first I assume?

**Comment by mrocklin** [comment]
Yes.  You will need to have a client active.  If you are on a worker then you can call `dask.distributed.get_client()`.  Otherwise you'll need to create a client with the right scheduler address explicitly.

**Comment by jrbourbeau** [comment]
Just checking in. @dickreuter anything else to do here, or is it okay to close this issue?

**Comment by dickreuter** [comment]
I have an additional issue that is related to the above:
If I do
```
future = Future(key="random-123") 
future.status
```
it will always respond pending, even though "random-123" does (or did not) exist. How can I find out if the future existed in the first place?

**Comment by TomAugspurger** [comment]
You should be able to compute that based on the scheduler state: https://distributed.dask.org/en/latest/scheduling-state.html. The scheduler has a `.tasks` property, and you can inspect the TaskState for that key.

Closing, since I believe the original issue has been addressed.
