### ISSUE TITLE
Expose adaptive target result

### ISSUE THREAD

**Issue by sublinus** [dask/distributed#3191]
We would like to get more information about how many workers the scheduler needs or wants over the cluster runtime. 

To solve this we would like to expose the result of `adaptive_target` via HTTP as a Prometheus metric. An issue we see here is the cost of a run of `adaptive_target`.
Would you be willing to accept a contribution adding a new metric exposing the desired number of workers?
Additionally or as an alternative exposing the value in `counts.json` would also be interesting.

https://github.com/dask/distributed/blob/9429ffe735e3767b427fd0b18aaa29d6a7da8513/distributed/scheduler.py#L4794

**Comment by mrocklin** [comment]
It looks like `adaptive_target` has a cost that is linear with the number of workers.  In the common case this isn't that bad.  Prometheus metrics get hit with a frequency of every second or so or longer, right?  If so then yes, that should be fine.  If this was being computed more frequently than that then we might want to start being a bit more careful.

**Comment by mrocklin** [comment]
Thanks for building out Dask's prometheus metrics by the way

**Comment by sublinus** [comment]
I started implementing the metric and noticed, that on every call of `adaptive_target`, which in this case is every scrape from Prometheus the `workers_to_close` function logs closing suggestions to log level `INFO`, when the current number of workers deviates from the heuristic.
I feel like this could confuse users and is rather noisy. 
Would it be an option to set the log level in `workers_to_close` to `DEBUG` in order to reduce the noise?

https://github.com/dask/distributed/blob/d575ea0bd0784da2368d486f07914ae669824a07/distributed/scheduler.py#L3065

**Comment by mrocklin** [comment]
That seems fine to me

**Comment by mrocklin** [comment]
This was done.  Closing.
