### ISSUE TITLE
Question: How to assign chunks of a dask.Array to specific workers?

### ISSUE THREAD

**Issue by sjperkins** [dask/distributed#3197]
I want to perform a distributed outer product over arrays A with schema ('row', 'chan') and S with schema ('source',), combined with a reduction over the 'source' dimension of the product. The example below illustrates what I'm trying to achieve:

```python
from itertools import cycle
import dask.array as da
from distributed import LocalCluster, Client

# ('row')
A = da.ones(10000, chunks=1000, dtype=np.complex64)
# ('source')
S = da.ones(100, chunks=10, dtype=np.float32)
# Outer product ('source', 'row')
O = S[:, None] * A[None, :]
# Reduce over outermost axis to form ('row', ) result
R = O.sum(axis=0)

cluster = LocalCluster(nanny=False,  processes=False,  n_workers=8,  threads_per_worker=1)
client = Client(cluster)
workers = cycle(client.scheduler_info()['workers'].keys())
# keys here should be some sort of collection. Round robin collections over workers
key_map = {k: w for k, w in zip(keys, workers)}

with cluster, client:
   f = client.persist(R, workers=key_map)
```

I would like to pin all 'row' chunks in A and R to specific workers in order to prevent data movement of large arrays.

In previous versions of distributed, I would have formed a key_map from the keys of the individual chunks. In recent versions, it seems that the keys of the worker dictionary can only be collections: 

https://github.com/dask/distributed/blob/8b7c47d7e93ee74d543f29ada1c7863bbad78310/distributed/client.py#L3764-L3775

so the granularity is much coarser. For the purposes of illustration, this seems to be possible: 

```python
 f = client.persist(R, workers={A: '192.168.0.10'})
```

Is there some other way to pin the individual chunks to the A (and R) array to individual workers?

**Comment by mrocklin** [comment]
I believe that you can pin individual key names to different workers.  This would require you to understand a bit about how dask graphs work though.

**Comment by sjperkins** [comment]
> I believe that you can pin individual key names to different workers. This would require you to understand a bit about how dask graphs work though.

Thanks for the advice @mrocklin. I feel I'm familiar with the task paradigm:``(name, chunk0, chunk1, chunk2): (fn, arg0, arg1, arg2)``. I also believed that you could pin key names to workers (it used to work that way)

The following MRE:

```python
from itertools import cycle
import dask
import dask.array as da
from distributed import LocalCluster, Client
import numpy as np
from pprint import pprint

A = da.ones(1000, chunks=100, dtype=np.int32)

cluster = LocalCluster(nanny=False,  processes=False,
                       n_workers=8,  threads_per_worker=1)
client = Client(cluster)
workers = cycle(client.scheduler_info()['workers'].keys())

key_map = {(A.name, c): w for c, w in zip(range(A.npartitions), workers)}

B = dask.persist(A, workers=key_map)
```

fails with:

```python-traceback
$ python  test_schedule.py 
{('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 0): 'inproc://192.168.1.81/10656/10',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 1): 'inproc://192.168.1.81/10656/3',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 2): 'inproc://192.168.1.81/10656/4',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 3): 'inproc://192.168.1.81/10656/5',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 4): 'inproc://192.168.1.81/10656/6',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 5): 'inproc://192.168.1.81/10656/7',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 6): 'inproc://192.168.1.81/10656/8',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 7): 'inproc://192.168.1.81/10656/9',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 8): 'inproc://192.168.1.81/10656/10',
 ('ones-ecc42f44aa5a54d427ffcdf1dc537c31', 9): 'inproc://192.168.1.81/10656/3'}
Traceback (most recent call last):
  File "test_schedule.py", line 19, in <module>
    B = dask.persist(A, workers=key_map)
  File "/home/sperkins/venv/distributed/lib/python3.6/site-packages/dask/base.py", line 617, in persist
    collections, optimize_graph=optimize_graph, **kwargs
  File "/home/sperkins/work/ska/code/distributed/distributed/client.py", line 2870, in persist
    collections, workers, allow_other_workers
  File "/home/sperkins/work/ska/code/distributed/distributed/client.py", line 3820, in get_restrictions
    {k for c in flatten(colls) for k in flatten(c.__dask_keys__())}
  File "/home/sperkins/work/ska/code/distributed/distributed/client.py", line 3820, in <setcomp>
    {k for c in flatten(colls) for k in flatten(c.__dask_keys__())}
AttributeError: 'str' object has no attribute '__dask_keys__'
```

I believe this is due to the following code that only accepts collections as keys:

https://github.com/dask/distributed/blob/8b7c47d7e93ee74d543f29ada1c7863bbad78310/distributed/client.py#L3764-L3775


Is this expected behaviour, or perhaps a bug?

**Comment by mrocklin** [comment]
> I also believed that you could pin key names to workers

I think that this is still the case.  But I don't know for sure.

> Is this expected behaviour, or perhaps a bug?

Unfortunately I also don't know.  It has been a while since I've looked at this code.  If you want to dive in here, that would be welcome.
