### ISSUE TITLE
Slow inter-node communication

### ISSUE THREAD

**Issue by broxtronix** [dask/distributed#32]
[ This issue began as a private email discussion between myself and @mrocklin, but we are moving it here so that we can better keep track of it. cc also @shoyer, @freeman-lab, @mrocklin  ]

@mrocklin recently suggested that I try dask.imperative ([docs](http://dask.pydata.org/en/latest/imperative.html), [example](http://nbviewer.ipython.org/github/blaze/dask-examples/blob/master/do-and-profiler.ipynb)) for parallelizing complex computations that do not fit in the working memory of my cluster.  Distributed should be able to process a dask graph as follows:
```
my_dask_value.compute(get=my_executor.get)
```
I tried this and it works great, but I am noticing some surprisingly slow performance when moderately sized results (100 x 2MB image arrays) are collect back from the workers to the executor.  The computation itself seems to run very quickly, but this "gather" operation takes longer than expected.  I created a notebook [here](https://gist.github.com/broxtronix/62f13db4d0869b7b3ad6) that illustrates this problem.

@mrocklin tried my notebook and got similarly slow performance when using the `dask.multiprocessing` scheduler, but got much better results when using `distributed`.  He set up his cluster as follows:
```
$ dcenter
$ dworker 127.0.0.1:8787 --ncores 1  # run this in four separate terminals
```
His results are [here](https://gist.github.com/mrocklin/fd5d3c160a573d7d72cf).  However, when I tried setting up my cluster in this way, my benchmark for distributed is still clocking in at 1 min 22 seconds, while the threaded result runs in 10 seconds on my laptop.  

There must be something else afoot here since @mrocklin is getting much better performance than I am.  FWIW, I'm running the distributed master branch just after you merged in your recent scheduler changes (git hash: fad4ce342d9e935b87cbc99e5c2740299b40e17b) on an Apple laptop running OSX, and Anaconda Python 3.5.0.

**Comment by mrocklin** [comment]
Just tried this on my other machine (Thinkpad W540, i7, 32GB ram, Anaconda python 3.4) and observed still different results

*  Threading: 13.5s
*  Multiprocessing: 18.3s
*  Distributed: 16s

So something wacky is going on

**Comment by broxtronix** [comment]
Interesting.  To add another data point, I just ran my notebook on a Google Compute Engine node running Ubuntu Linux 15.10 and Anaconda Python 3.5.  My results there are similar to your Thinkpad, and more in line with what I would normally expect:
* Threading: 8.61s
* Multiprocessing: 13.6s
* Distributed: 10.7s

Was your Thinkpad running Linux, and other laptop running OSX?   Perplexing!

**Comment by mrocklin** [comment]
Both running linux.  The other laptop is significantly less performant.

**Comment by mrocklin** [comment]
@broxtronix can I ask you to run the dask `Profiler` on the threaded and multiprocessing schedulers and share the results?

http://dask.pydata.org/en/latest/diagnostics.html#profiler

**Comment by mrocklin** [comment]
Just realized that I can do this on my old laptop.  Results forthcoming

**Comment by mrocklin** [comment]
https://rawgit.com/mrocklin/b77da8fb0b0a3ee3dbe4/raw/29602c26a431a52e68788eece79f7db8ee8bd5db/profile-multiprocessing.html

This matches your description from before.

**Comment by mrocklin** [comment]
Hrm, looking at your computation now.  This last task isn't really a computation and shouldn't have to happen on a worker.  It's just collecting all of the results into a list.

As an alternative, you could also just compute a list of dask values

### Before
    colormapped_images = value([ do(colormap_and_combine)(*args) for args in zip(test_images,amplitude_ranges, phase_ranges) ])
    results = colormapped_images.compute(...)


### After

    colormapped_images = [ do(colormap_and_combine)(*args) for args in zip(test_images,amplitude_ranges, phase_ranges) ]
    from dask import compute
    results = compute(*colormapped_images, ...)

This runs at the threading speed for me.

So, that probably resolves the immediate issue.  We might want to be robust to this sort of thing though, and it's still not clear why it was so slow.

We could avoid unnecessary communication by noticing that there aren't any function calls within the task `[..., ..., ...]`.  It's not hard to add this special case, it just feels a bit special-case-y.

The communication costs to move this data from the main process to a worker and then back should be bound by the sum of all previous communications.  It is not.  Perhaps the serialization library is doing something wacky here?

**Comment by broxtronix** [comment]
Oh, interesting!  Now that you point it out, I see how this last "computation" is not exactly what I was intending.  If I understand correctly, the "before" case must have caused (1) a randomly selected worker to gather the color-mapped images from all the other workers and create its own local copy of the list of images, and (2) pickle and send the complete list to the executor (which would have been a fairly large object to serialize and transfer over the network).  

I see how the "after" case runs much more efficiently by gathering the individual color-mapped images to the executor before forming the list.  No need to form the list first and then transfer it over the network!

I made this change and re-ran the test on my laptop.  I now get these performance numbers:
* Threaded: 9.34s
* Multiprocessing: 9.23s
* Distributed: 20.4s

In the case of the `distributed` scheduler, I still noticed about 10 seconds worth of 400% cpu utilization followed by about 10 seconds of 100% (single core) utilization.  I'm still not sure what is going on during that second segment... something is still a little wacky, but this is still a huge improvement.  I'm very grateful to have had my programming error pointed out... thanks for taking the time to look more closely at my code.  I'll have to be careful about those "Value" statements, and their implications for where computations will run.

A few other interesting tidbits: 

I have not re-run this test on my Linux machine.  I imagine I'll get very nearly the same results for all three execution engines.

I tried running the `dask` profiler as you suggested. This worked fine and returns the expected result for the threaded and multiprocessing examples, but it did not work for me when using the `distributed` scheduler.  (`prof.results` was an empty list)

I was curious how long it would take to pickle the list of 100 images.  It looks like it takes about 1 second to serialize and 1 second to deserialize this large list using `cloudpickle,` which isn't toooo slow.  More notably, the pickled data takes about 994 MB whereas the original list of 100 numpy arrays takes 200 MB.  Cloudpickle does not natively handle dense binary data like numpy arrays very well.  (I've run into this in the past... some special handling of the serialization/deserialization of numpy arrays may eventually be worth the effort.

**Comment by mrocklin** [comment]
Try `cloudpickle.dumps(obj, protocol=pickle.HIGHEST_PROTOCOL)`.  It should run quickly and store efficiently.

**Comment by mrocklin** [comment]
Dask's Profiler (and indeed all of its diagnostics) are tied to the single-node scheduler within dask.  They won't be helpful with `distributed`.  We have yet to figure out how best to do diagnostics there (your thoughts on this would be most welcome.)

The "programming error" as you put it is quite natural to do (I do it myself sometimes) and it would be nice to make it efficient, otherwise its a pretty common gotcha.

**Comment by mrocklin** [comment]
Although, the fact that you're running into that performance issue implies that your default pickling protocol might not be properly using the buffer protocol.  Can you verify that you get results like the following:

```python
In [1]: import numpy as np

In [2]: import cloudpickle

In [3]: import pickle

In [4]: x = np.empty(1000000)

In [5]: %time len(cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL))
CPU times: user 17.2 ms, sys: 751 µs, total: 17.9 ms
Wall time: 17.9 ms
Out[5]: 8000161

In [6]: %time len(cloudpickle.dumps(x))
CPU times: user 15.7 ms, sys: 7.86 ms, total: 23.6 ms
Wall time: 23.5 ms
Out[6]: 8000211
```

**Comment by broxtronix** [comment]
Hmm... this is strange.  I ran this above test and got the exact same results as you did when pickling an empty array.  However when I run this test with random (randint) rather than empty arrays, the `HIGHEST_PROTOCOL` version performs significantly better.
```
In [37]: x = np.random.randint(0, 255, size = (512, 1024, 4)).astype(np.uint8)

In [38]: %time len(cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)) / 1024**2
CPU times: user 1.67 ms, sys: 899 µs, total: 2.57 ms
Wall time: 2.29 ms
Out[38]: 2.0001564025878906

In [39]: %time len(cloudpickle.dumps(x)) / 1024**2
CPU times: user 10.9 ms, sys: 1.52 ms, total: 12.4 ms
Wall time: 12.4 ms
Out[39]: 2.9961347579956055
```
This may be a 'cloudpickle` specific problem, though, because when I run the same test using the standard `pickle` module, they return very nearly the same result:

```
In [7]: %time len(pickle.dumps(x)) / 1024**2
CPU times: user 819 µs, sys: 466 µs, total: 1.29 ms
Wall time: 1.27 ms
Out[7]: 2.0001564025878906

In [8]: %time len(pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)) / 1024**2
CPU times: user 759 µs, sys: 443 µs, total: 1.2 ms
Wall time: 1.21 ms
Out[8]: 2.0001564025878906
```
I ran the same test on my Linux box, and got the same result there as I did here.  This is bizarre, but I'm not sure it explains the performance problem since it looks like your are explicit about using the `HIGHEST_PROTOCOL` in `distributed/core.py`.

**Comment by mrocklin** [comment]
I ran into this.  Tracked it down (I think) to a Tornado issue: https://github.com/tornadoweb/tornado/issues/1685

**Comment by mrocklin** [comment]
There were several issues it turned out, many have been resolved, some still have not.  Regardless, we can hit 100 MB/s/node bandwidth on EC2

```python
In [1]: from distributed import Executor, s3, progress

In [2]: e = Executor('127.0.0.1:8786')  # Connect to scheduler running on the head node 

In [3]: import dask.array as da, dask

In [4]: dask.set_options(get=e.get)
Out[4]: <dask.context.set_options at 0x7f55b32f3128>

In [5]: e 
Out[5]: <Executor: scheduler=127.0.0.1:8786 workers=28 threads=28>

In [6]: x = da.random.normal(10, 0.1, size=(50000, 50000), chunks=(1000, 1000))

In [7]: x.nbytes  # 20 GB
Out[7]: 20000000000

In [8]: x = e.persist(x); progress(x)
[########################################] | 100% Completed |  7.4s
In [9]: y = e.persist(x + x.T); progress(y)  # move data
[########################################] | 100% Completed | 24.2s
```

So assuming that most of the data has to move then we're seeing a bit less than 1GB/s aggregate bandwidth over seven machines, which is something like 100MB/s per node.  This isn't optimal, but it's probably usable.

**Comment by mrocklin** [comment]
OK, I've resolved more issues and get around 500MB/s on my own machine, which is near peak.  The performance of this operation stays the same on EC2, which says to me that we're bound by gigabit ethernet.  It would be interesting to see how far we can get on 10Gb.

For posterity here is a local benchmarking script and profile output

### Script

```python
# myscript.py
from distributed import Worker, rpc, Scheduler

s = Scheduler()
s.start(8989)
w = Worker(s.ip, s.port)
w.listen()

import numpy as np
x = np.random.randint(0, 255, dtype='u1', size=1000000000)
w.data['x'] = x

from tornado.ioloop import IOLoop
from tornado import gen
IOLoop.current().run_sync(lambda: gen.sleep(0.5))
```

### IPython session

```python
In [1]: from myscript import *
distributed.scheduler - INFO - Start Scheduler at:        192.168.1.141:8989

In [2]: %prun IOLoop.current().run_sync(lambda: rpc(w.address).get_data(keys=['x']))
distributed.core - INFO - Connection from 192.168.1.141:41832 to Worker
```

### Profile results

```
         381811 function calls (381774 primitive calls) in 1.718 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.384    0.384    0.384    0.384 {built-in method dumps}
        8    0.309    0.039    0.311    0.039 iostream.py:360(write)
    15358    0.229    0.000    0.229    0.000 {method 'join' of 'bytes' objects}
        1    0.196    0.196    0.196    0.196 {built-in method LZ4_compress}
    15362    0.174    0.000    0.174    0.000 {method 'recv' of '_socket.socket' objects}
    15368    0.163    0.000    0.405    0.000 iostream.py:1510(_merge_prefix)
     7769    0.105    0.000    0.105    0.000 {method 'send' of '_socket.socket' objects}
        1    0.040    0.040    1.718    1.718 ioloop.py:746(start)
        8    0.020    0.002    0.205    0.026 iostream.py:876(_consume)
    15362    0.020    0.000    0.204    0.000 iostream.py:721(_read_to_buffer)
       98    0.018    0.000    0.347    0.004 iostream.py:827(_handle_write)
       96    0.014    0.000    0.222    0.002 iostream.py:585(_read_to_buffer_loop)
   122593    0.009    0.000    0.009    0.000 {built-in method len}
    15362    0.007    0.000    0.181    0.000 iostream.py:1010(read_from_fd)
     7769    0.004    0.000    0.108    0.000 iostream.py:1023(write_to_fd)
    38379    0.004    0.000    0.004    0.000 {method 'append' of 'list' objects}
    15278    0.002    0.000    0.002    0.000 iostream.py:754(_run_streaming_callback)
    46004    0.002    0.000    0.002    0.000 {method 'popleft' of 'collections.deque' objects}
    16213    0.002    0.000    0.002    0.000 iostream.py:478(closed)
        2    0.002    0.001    0.199    0.099 protocol.py:65(dumps)
      182    0.002    0.000    0.775    0.004 iostream.py:497(_handle_events)
    22904    0.002    0.000    0.002    0.000 {method 'append' of 'collections.deque' objects}
    23100    0.001    0.000    0.001    0.000 {method 'appendleft' of 'collections.deque' objects}
      207    0.001    0.000    1.675    0.008 stack_context.py:271(null_wrapper)
      188    0.001    0.000    0.001    0.000 {method 'poll' of 'select.epoll' objects}
      191    0.001    0.000    0.001    0.000 {method 'update' of 'dict' objects}
      372    0.000    0.000    0.001    0.000 ioloop.py:908(time)
      181    0.000    0.000    0.000    0.000 iostream.py:474(writing)
       92    0.000    0.000    0.427    0.005 iostream.py:645(_handle_read)
        1    0.000    0.000    0.385    0.385 core.py:43(dumps)
        1    0.000    0.000    0.197    0.197 protocol.py:134(dumps_big_byte_dict)
      374    0.000    0.000    0.000    0.000 {built-in method time}
      187    0.000    0.000    0.000    0.000 {built-in method min}
      199    0.000    0.000    0.000    0.000 iostream.py:772(_find_read_pos)
    17/14    0.000    0.000    0.897    0.064 gen.py:990(run)
```

**Comment by mrocklin** [comment]
Fix here: https://github.com/dask/distributed/pull/224

**Comment by mrocklin** [comment]
Closing.  Report of the process to fix this in case it interests anyone: http://matthewrocklin.com/blog/work/2016/04/14/dask-distributed-optimizing-protocol
