### ISSUE TITLE
memory leak when read from disk?

### ISSUE THREAD

**Issue by AlbertRay** [dask/distributed#3201]
I want to read a dataframe in `client.submit`, this dataframe may occupy more than 2GB of memory.
There are 4 machine in cluster, i will use just one machine in the next code.

1) Use random data, after `return 123` or `print(future.result())` the memory will decrease to normal state (eg. 400MB) quickly.
```python
def test():
    import numpy as np
    import pandas as pd
    df = pd.DataFrame(np.random.randn(971 * 4801, 55))
    print(df)
    return 123

if __name__ == "__main__":
    from dask.distributed import Client
    client = Client("machine_a:8786")
    # client.restart()
    future = client.submit(test, workers="machine_a")
    print(future.result())
    input("wait to exit")
```

2) Read from disk, the memory (eg. 2GB) will occupy for a while (eg. 4seconds) even after exit program.
```python
def test():
    import pandas as pd
    df = pd.read_hdf("test.h5")
    print(df)
    return 123
```

3) Use `gc.collect` can release memory after task finish and return. But if I want to return part of dataframe rather than `123`, it dose not work.
```python
def test():
    import gc
    import pandas as pd
    df = pd.read_hdf("test.h5")
    print(df)

    # OK
    result = 123
    # dose not work
    # result = df.iloc[:5].copy()

    gc.collect()
    return result
```

4) I generate `test.h5` randomly. I have try `format=“fixed”` or no compression or `to_parquet`, get the same result.
```python
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(971 * 4801, 55))
print(df)
df.to_hdf(
    "test.h5",
    "df",
    format="table",
    mode="w",
    append=False,
    complib="blosc:lz4",
    complevel=9,
)
```

5) When use `concurrent.futures.ProcessPoolExecutor`, the memory will release quickly after `print(future.result())`.
```python
if __name__ == "__main__":
    from concurrent.futures import ProcessPoolExecutor
    executor = ProcessPoolExecutor(4)
    future = executor.submit(test)
    print(future.result())
    input(""wait to exit")
```

6) I read dataframe in `client.sumbit` because i have to do some custom func and then stack multiple 2d data (eg. 100GB) into 3d. If I use dask.dataframe to read and concat, then transfer it to dask.array, it will wasted a lot of time and memory on `concat index` and `transfer`.

7) The task I actually have to do is something like next script. I have try `future` or `delayed`, when I finish task and even exit program, still have some memory (eg. 10GB) not released.
```python
def read(path):
    return pd.read_hdf(path, start=start, stop=stop).values.reshape(new_shape)
paths # eg. 1000 files
read_delayed = dask.delayed(read)
datas = [dask.array.from_delayed(read_delayed(path), shape=data_shape, dtype="float32") for path in paths]
data_stack = dask.array.vstack(datas)
# do some compute (eg. use xarray to compute rolling mean)
```

Is my method of using dask incorrect or some wrong in deploying env? Or I misunderstood the working mechanism of dask memory?
```
conda
python 3.6.8
dask 2.6.0
distributed 2.6.0
numpy 1.17.2
pandas 0.25.2
pytables 3.5.2
```

**Comment by mrocklin** [comment]
For the memory leak issue I recommend trying with concurrent.futures (as you have done) and if that reproduces the issue then raise an issue on the pandas issue tracker.  They are more able to help here than we are.

I do not know your application exactly, but if you want multi-dimensional pandas-like data then you might want to look at Xarray.

**Comment by mrocklin** [comment]
Any update on this @AlbertRay ?  Otherwise I'll go ahead and close this out.

**Comment by AlbertRay** [comment]
@mrocklin 
I find the memory problem exists in simple write/read script.
```python
# write
import pathlib
import numpy as np
import pandas as pd

dst_dir = pathlib.Path("dir_path")
shape = (800 * 4000, 50)

x = pd.DataFrame(np.random.standard_normal(shape))
x.to_hdf(dst_dir / "a.h5", "df", format="table", mode="w", complib="blosc:lz4", complevel=9)
x.to_hdf(dst_dir / "b.h5", "df", format="table", mode="w", complib="blosc:lz4", complevel=0)
x.to_hdf(dst_dir / "c.h5", "df", format="table", mode="w", complib="zlib", complevel=0)
```
```python
# read
import pathlib
import dask.dataframe as dd
from dask.distributed import Client

client = Client("machine:8786")
# client.restart()

src_dir = pathlib.Path("dir_path")
x = dd.read_hdf(src_dir / "a.h5", "df", mode="r")  # a.h5, b.h5, c.h5 have same problem
print("result", x.sum().compute())  # I think memory should be released when compute is finished

input("wait to exit")
```
Memory is not released immediately. (memory is 200~300 MB in nomal state.)
![0](https://user-images.githubusercontent.com/20217594/69708928-6d216500-1137-11ea-837e-8cd2e76338dc.png)
I don't know which casuse this issue, dask or pandas or pytables or my env.

**Comment by mrocklin** [comment]
For the memory leak issue I recommend trying with concurrent.futures and if that reproduces the issue then raise an issue on the pandas issue tracker. They are more able to help here than we are.

**Comment by mrocklin** [comment]
Closing this out.  @AlbertRay if you have more information, or are able to try this without Dask, but with concurrent.futures, then please post here and we'll reopen.
