### ISSUE TITLE
Consider not having an import time side effect (distributed.utils)

### ISSUE THREAD

**Issue by rahulporuri** [dask/distributed#3202]
At the moment, `import distributed` has the import time side-effect of modifying the asyncio event loop policy (if the environment contains asyncio and if the tornado version >= 5).

This is because `distributed.__init__` imports from the `distributed.utils` module, which is where the import time side-effect happens. See below

https://github.com/dask/distributed/blob/bc04d7642c0439bf3757b34bd1eb802b9679ba12/distributed/utils.py#L1191-L1209

This is a problem for desktop applications built around dask/distributed which already use an event loop and aren't expecting `distributed` (or any other package for that matter) to update the event loop policy at any point during the application lifecycle, especially not implicitly.

**Comment by rahulporuri** [comment]
FTR, here's the PR which originally added the relevant code - https://github.com/dask/distributed/pull/1518 - and here are the PRs which touched the relevant code - https://github.com/dask/distributed/pull/2326 and https://github.com/dask/distributed/pull/2343

**Comment by mrocklin** [comment]
Thanks for raising this issue @rahulporuri .  Do you have any suggestions on how to resolve the underlying issue caused when running Dask within a Jupyter notebook?

**Comment by mrocklin** [comment]
@rahulporuri any thoughts on the question above?

**Comment by potpath** [comment]
@mrocklin @rahulporuri , I just encountered this problem when `import distributed` in the ipython startup script. We can reproduce by adding the following to `~/.ipython/profile_default/startup/00-first.py`
```python
import asyncio
import tornado.platform.asyncio

asyncio.set_event_loop_policy(
    tornado.platform.asyncio.AnyThreadEventLoopPolicy()
)
```
I think it is essentially the same issue with https://github.com/dask/distributed/pull/2343.
But this one is when the asyncio event loop is not started yet. I'm not sure if we could just add the `and not is_kernel()` check at https://github.com/mrocklin/distributed/blob/master/distributed/utils.py#L1325.

**Comment by mrocklin** [comment]
Thanks for the comment @potpath ! 

> I'm not sure if we could just add the and not is_kernel() check

is this something that you're able to investigate?  I'll be honest that I personally don't know much about this space.  If you're able to help here that would be very welcome.

**Comment by potpath** [comment]
@mrocklin Sure, opened at https://github.com/dask/distributed/pull/3336.
