### ISSUE TITLE
Re-computions (flapping) due to GIL-holding

### ISSUE THREAD

**Issue by marco-neumann-jdas** [dask/distributed#3204]
## 1. Abstract
On computations involving a large dask dataframes, we often see the computation flapping, i.e. recomputing parts of an already finished graph multiple times.

## 2. Environment

```
bokeh==1.0.4
dask==2.6.0
distributed==2.6.0
numpy==1.17.2
pandas==0.24.2
python==3.6.6
tornado==6.0.3
zict==1.0.0
```

## 3. Worker Logs
Looking at the workers, we observe the following pattern (example)

### 3.1. Normal Operations
Normal operations, we have a prometheus scraping in place indicating the worker interpreter works fine

```
...
2019-11-06 14:51:45,536 INFO     200 GET /metrics (10.3.2.5) 2.09ms (tornado.access)
2019-11-06 14:52:45,535 INFO     200 GET /metrics (10.3.2.5) 1.55ms (tornado.access)
2019-11-06 14:53:45,542 INFO     200 GET /metrics (10.3.2.5) 1.59ms (tornado.access)
...
```

### 3.2. Freeze
Then, out of a sudden, the worker seems to freeze:

```
...
2019-11-06 15:11:47,316 INFO     200 GET /metrics (10.3.2.5) 9.92ms (tornado.access)
2019-11-06 15:14:26,553 INFO     200 GET /metrics (10.3.2.5) 40859.23ms (tornado.access)
2019-11-06 15:14:26,560 INFO     200 GET /metrics (10.3.2.5) 2.77ms (tornado.access)
2019-11-06 15:14:46,087 INFO     200 GET /metrics (10.3.2.5) 1.50ms (tornado.access)
...
```

### 3.3. Communication Issues
The communication seems to fail shortly after, mixing multiple of the following errors

```
2019-11-06 15:17:08,413 ERROR    Worker stream died during communication: tls://10.3.136.47:30187 (distributed.worker)
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/distributed/worker.py", line 1881, in gather_dep
    self.rpc, deps, worker, who=self.address
  File ".../venv/lib/python3.6/site-packages/distributed/worker.py", line 3109, in get_data_from_worker
    max_connections=max_connections,
  File ".../venv/lib/python3.6/site-packages/distributed/core.py", line 531, in send_recv
    response = await comm.read(deserializers=deserializers)
  File ".../venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 204, in read
    convert_stream_closed_error(self, e)
  File ".../venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 132, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TLS>: Stream is closed
```

```
2019-11-06 15:18:16,325 ERROR    Worker stream died during communication: tls://10.3.136.74:30858 (distributed.worker)
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/distributed/comm/core.py", line 221, in connect
    _raise(error)
  File ".../venv/lib/python3.6/site-packages/distributed/comm/core.py", line 204, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tls://10.3.136.74:30858' after 60 s: connect() didn't finish in time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/distributed/worker.py", line 1881, in gather_dep
    self.rpc, deps, worker, who=self.address
  File ".../venv/lib/python3.6/site-packages/distributed/worker.py", line 3099, in get_data_from_worker
    comm = await rpc.connect(worker)
  File ".../venv/lib/python3.6/site-packages/distributed/core.py", line 869, in connect
    connection_args=self.connection_args,
  File ".../venv/lib/python3.6/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File ".../venv/lib/python3.6/site-packages/distributed/comm/core.py", line 204, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tls://10.3.136.74:30858' after 60 s: Timed out trying to connect to 'tls://10.3.136.74:30858' after 60 s: connect() didn't finish in time
```

### 3.4. Dangling Connections
We then also observer these warnings all following connection issue:

```
2019-11-06 15:18:49,607 WARNING  Closing dangling stream in <TLS  local=tls://10.3.136.75:45130 remote=tls://10.3.136.74:30858> (distributed.comm.tcp)
2019-11-06 15:18:49,611 WARNING  Closing dangling stream in <TLS  local=tls://10.3.136.75:45174 remote=tls://10.3.136.74:30858> (distributed.comm.tcp)
```

### 3.5. Re-computations
The worker then assumes dependencies are lost and asks the scheduler:

```
2019-11-06 15:18:16,329 INFO     Can't find dependencies for key ('unique-combine-1457cbeb0132b5ba48d92a0ae8022acd', 1, 5, 0) (distributed.worker)
2019-11-06 15:18:16,334 INFO     Dependent not found: ('unique-chunk-1457cbeb0132b5ba48d92a0ae8022acd', 0, 44, 0) 0 .  Asking scheduler (distributed.worker)
```

## 4. GIL Debugging
Analyzing the logs, our assumption is that the somehow the Python interpreter freezes, then the TCP/TLS connections break and the computations are assumed to be lost. To validate this, we have implement the following debugging plugin:

```python
from distributed.utils import parse_timedelta
import dask.config
import asyncio
import faulthandler


class FindLoopBlockersPlugin:
    async def reschedule_faulthandler_forever(self):
        while True:
            faulthandler.dump_traceback_later(self.limit, repeat=True)
            await asyncio.sleep(self._reset_interval)

    def teardown(self, worker):
        faulthandler.cancel_dump_traceback_later()

    def setup(self, worker):
        self.limit = parse_timedelta(
            dask.config.get("distributed.admin.tick.limit"), default="ms"
        )
        loop = worker.loop.asyncio_loop
        self._reset_interval = self.limit / 5.0
        self._task = asyncio.ensure_future(
            self.reschedule_faulthandler_forever(), loop=loop
        )
```

which is registered with the client BEFORE the computation:

```python
client.register_worker_plugin(FindLoopBlockersPlugin())
```

Since in case of a GIL-freeze, stacks for all threads will be dumped, the output can be quite overwhelming. Also, the functions that are listed in the tracebacks do not necessarily have to be the root cause but only hints. We have founds the following good candidates:

- payload (primary computation requested by the dask/distributed user):
  - pandas: often ending in `pandas.core.algorithms:take_nd`, `pandas.core.internals.blocks:concat_same_type`, etc.
  - pyarrow: often ending in `pyarrow.pandas_compat:dataframe_to_types`, `pyarrow.pandas_compat.py:convert_column`, etc.
- runtime (dask/distributed itself):
  - "spilling": `distributed.worker:transition_executing_done` ... `zict.buffer:__setitem__` ... `zict.lru.:evict` ... `zict.buffer:fast_to_slow` ... `distributed.protocol.serialize:serialize_bytelist` and ends in things like `distributed.protocol.pickle:dumps`,`distributed.utils:ensure_bytes`, ...
  - loading: `distributed.worker:execute` ... `zict.buffer:__getitem__` ... `zict.buffer:slow_to_fast` ... `protocol.pickle:loads`

## 5. Log-faulthandler correlation
If we correlate the log entries from 3. and the faulthandler errors from 4., we see that communication errors do not seem to occur during the payload-driven freezes, but mostly during the runtime spilling/loading. This might have the following reasons:

- maybe the payload-induced freezes are short / not severe
- maybe during payload execution, less TCP/TLS communication occurs
- the actual logs do not occur on the same worker: if you have 2 workers (one with GIL freezes that has cached data, one that is about to start a computation and needs that data), then the freeze may occur on the first and the communication error and dependency-miss on the second

It therefore seems that both GIL freezes could lead to re-computations.

## 6. Solutions
It's quite hard to fix that issue as long as the following things occur within the same python interpreter / process:

- payload execution
- in-memory (fast) data caching
- spilling and loading to/from disk
- answering other workers requests
- requesting other workers cached data

Any ideas?

## References
Issues that are potentially related:

- #2507
- #3142

**Comment by mrocklin** [comment]
Hi @marco-neumann-jdas ,

I apologize for the long delay in responding here, and thank you for the detailed report.

My short answer is "I don't know what's going on" unfortunately.  Your summary seems sensible to me.  I agree with your conclusion that probably the next thing to do here is to isolate the problem further.  I don't have any special suggestions on how to do this beyond normal debugging techniques.  For example, I might try to take one of those activities, like loading/spilling data from disk, and time it.

```python
start = time()
x = self.data[key]
stop = time()
if stop - start > 1:
    print(...)
```

And hope that that shows something interesting.  You could also try turning off spilling-to-disk behaviors with `memory_limit=None` and see if the problem persists.  (assuming, of course, that you have enough memory to avoid OOM errors).

I will be curious to hear what you find, and hopefully I'll be better able to respond in the coming weeks.

**Comment by mrocklin** [comment]
Any update here @marco-neumann-jdas ?  Otherwise I think that we should possibly close this.

**Comment by Timost** [comment]
This is not going to be very helpful, but I'm seeing similar behaviour when processing big files which trigger spill to disk operations. Sometimes it seems workers are lost and tasks have to be recomputed.

Most of the times those tasks are actually the most expensive ones (load from remote storage and parse into a pandas dataframe ~7-8GiB in RAM, worker has a total 14GiB of ram) which makes it really painful. Workers run with one process and three threads per process. The files read are gzipped so they don't support "on the fly" chunking.

I haven't had the time to dig deeper but what is described here fits what I've been seeing on my cluster. As I'm quite new to the dask stack this might as well be me not using dask properly.

I'm running dask in a kubernetes cluster with dask-kubernetes using dask 2.8.0.

**Comment by marco-neumann-jdas** [comment]
@Timost my team contributed a bunch of connection stability improvements for distributed (#3246, #3294, #3301). Can you please try again w/ version 2.9.0 and also set the [retry count](https://github.com/dask/distributed/blob/cf0767536b2b2e17afd6c849c687695c83200979/distributed/distributed.yaml#L76) to something appropriate (3 is a good start).

**Comment by marco-neumann-jdas** [comment]
@mrocklin we're currently trying to disable the disk spilling and test if this helps. The tests take a while though.

**Comment by mrocklin** [comment]
Cool.  Let me know how it goes.

**Comment by Timost** [comment]
@marco-neumann-jdas I've finally been able to test things with dask 2.9.1 and I'm not seeing the same issues as before anymore. So there has definitely been an improvement. Thank you !

**Comment by marco-neumann-jdas** [comment]
I would be OK to close the issue for now then.

**Comment by jrbourbeau** [comment]
Closing for now then. @marco-neumann-jdas feel free to re-open if needed

**Comment by jakirkham** [comment]
> Can you please try again w/ version 2.9.0 and also set the [retry count](https://github.com/dask/distributed/blob/cf0767536b2b2e17afd6c849c687695c83200979/distributed/distributed.yaml#L76) to something appropriate (3 is a good start).

Was just talking with @quasiben and @gjoseph92 and we are thinking to bump the default retry count. Currently thinking 5 may make a good choice
