### ISSUE TITLE
Use CSS for profile and profile server plots

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3206]
These plots currently only function well when they are of a certain aspect ratio.  It may be that Bokeh's layout engine isn't cut out for them.  If someone with some CSS knowledge is around, it would be great to have these operate more like the /status route (see `dashboard/components/scheduler.py::status_doc` for pointers) so that it conformed to the space that it was in.

cc @jacobtomlinson

**Comment by mrocklin** [comment]
cc @dsludwig and @jsignell in case either of them feel like a side project

**Comment by jsignell** [comment]
Not right now, but maybe in the future :)
