### ISSUE TITLE
`concurrent.futures._base.CancelledError` : unclear how to avoid this

### ISSUE THREAD

**Issue by kmadathil** [dask/distributed#3209]
I'm testing a dask deployment on Kubernetes (created using helm as in the [documentation](https://docs.dask.org/en/latest/setup/kubernetes.html))

```
client = Client(SCHEDULER_ADDRESS)

N = 30000
C = 1000

x = da.random.random(size=(N,N))
#x = da.random.random(size=(N,N),chunks=(C,C))
s = x.sum().compute()
```

Everything runs fine if N <=10000, and I do not use a forced chunk size. Else, I see an exception thus:

```
concurrent.futures._base.CancelledError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/home/karthik/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/home/karthik/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 1007, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "/home/karthik/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 1056, in _ensure_connected
    msg = await gen.with_timeout(timedelta(seconds=timeout), comm.read())
```
This looks like some sort of timeout issue (which makes sense, given the behavior), but I do not see any timeout documented in the dask documentation. 

Everything runs as expected with a local client. How can this be debugged further?

**Comment by mrocklin** [comment]
It's hard to tell without the full traceback, but it looks like the client
can't connect to the scheduler?  Perhaps this is a networking issue?  You
might look at worker logs to see if they're having difficulty connecting or
running into some issue.

**Comment by kmadathil** [comment]
It does not look like a networking issue, but a resources issue. I will add comments and close once I come up with a reliable procedure for avoiding this and debugging this once it arises.

**Comment by mrocklin** [comment]
Thank you @kmadathil

**Comment by kmadathil** [comment]
This turned out to be similar to https://github.com/dask/distributed/issues/2605 

Steps to debug
  1. Get the scheduler logs through kubectl logs scheduler_pod_name
  2. Noted that a deserialization error happened on the scheduler
```
 ValueError: Data is compressed as lz4 but we don't have this installed
distributed.scheduler - INFO - Remove client Client-2a08b1dc-04c5-11ea-a82b-f5c8b81c7bbd
distributed.scheduler - INFO - Close client connection: Client-2a08b1dc-04c5-11ea-a82b-f5c8b81c7bbd
distributed.core - ERROR - Data is compressed as lz4 but we don't have this installed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 185, in loads_msgpack
    decompress = compressions[header["compression"]]["decompress"]
KeyError: 'lz4'
```
 3. Considered reporting this as a bug, then saw #2605 
 4. Ran `client.get_versions(check=True)` and saw the mismatch 
```
lz4
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 2.1.10  |
| scheduler               | None    |
| tcp://172.17.0.10:34839 | None    |
| tcp://172.17.0.8:39587  | None    |
| tcp://172.17.0.9:34819  | None    |
+-------------------------+---------+

```
 5. Added lz4 to scheduler and clients through `env:EXTRA_CONDA_PACKAGES` and `helm upgrade release_name -f helm_config.yaml`

Now things work as expected

**Comment by kmadathil** [comment]
Unlike my initial intuition, this was not a resources (memory/cpu) issue, but a package dependency. This will not occur in a production deployment, since I expect more attention to be paid to the python environment everywhere, but this is highly likely to occur when someone begins playing with dask on a kubernetes cluster. 

lz4 is a very common python package, and in the case where
  
1. lz4 is installed on the client
2. the helm dask/dask charts are used as the dask page suggests

This error is bound to occur. It is just the kind of frustrating error which you wouldn't want someone to face as they're trying to get off the ground. 

To avoid this error, I suggest upgrading the daskdev/dask container to include all the compression packages that dask could use.

**Comment by kmadathil** [comment]
Closing as the issue is not dask.distributed related.
