### ISSUE TITLE
if `dask-scheduler` dies and started again

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#322]
`dask-workers` do not connect back to scheduler.

**Comment by mrocklin** [comment]
What is your immediate goal?  Do you want the network to persist or do you want the scheduler state to persist as well?  The first goal is short-term attainable, the second goal requires significant effort.

**Comment by hussainsultan** [comment]
immediately, i'd like the network to persist. it is ok if the state is lost. Operationally, this helps in maintaining a large cluster where a scheduler process may be restarted and it will be nice to get all the workers reconnect. 

on the point of scheduler state, i think the above step may be a good iteration towards that? thoughts?

**Comment by mrocklin** [comment]
Sure, seems reasonable.

Are you running into cases where the scheduler is actually dying or is this hypothetical at the moment?  What situations where the scheduler dies interest you?  Is this about machine failure?  A job scheduler taking away resources?

**Comment by hussainsultan** [comment]
i just ran into it when i set up a dask cluster using ansible roles and i had to change the master post first time setup. I have not encountered scheduler dying yet in my light use thus far.

**Comment by mrocklin** [comment]
Can the workers assume that the scheduler address given to them remains the same?

**Comment by hussainsultan** [comment]
yes!

**Comment by hussainsultan** [comment]
here is the ansible role: https://github.com/hussainsultan/ansible-dask it runs `dscheduler`/`dworker` via systemctl

**Comment by mrocklin** [comment]
OK, so I think that the way to resolve this is to have the workers in charge of the heartbeat connection rather than the scheduler.  That way the heartbeat can just become an idempotent `register-worker` message.

**Comment by mrocklin** [comment]
I'm going to wait until after the next release to do this.  It should be fairly straightforward though.
