### ISSUE TITLE
Scheduler bars only show first 12 characters of keys

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3222]
Scheduler bars only show the first 12 characters of the keys, even though there would be a lot more space to show the full name (or at least the first 50, instead of replacing it with an ellipsis). This is especially relevant if many long running tasks are kicked off, each with a different job name. They are currently not easily visible.

![image](https://user-images.githubusercontent.com/1256318/68593237-de50ef00-048c-11ea-85c5-ac7140d1a1e5.png)

**Comment by TomAugspurger** [comment]
Do we know the total size of the bar when we determine the text to display?

**Comment by dickreuter** [comment]
The size of the bar is probably determined by the screen with or how much it is zoomed, so it can change anytime. I'm not sure who determines where the text is cut off. Is it something that is taken care of by bokeh?

**Comment by TomAugspurger** [comment]
I'm not sure either.

**Comment by mrocklin** [comment]
We know how many bars there will be, but we don't know how large they will be.  I don't know if this is something that Bokeh can handle.  My guess is that it's hard.  It might be worth asking on that issue tracker, or on the [Bokeh Discourse](https://discourse.bokeh.org/)

**Comment by mrocklin** [comment]
This appears to have stalled.  Closing.
