### ISSUE TITLE
Spending time in asyncio.selector_events._ssock.recv

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3223]
When profiling the scheduler's event loop we find that we are spending most of our time in `asyncio/selector_events.py::BaseSelectorEventLoop._read_from_self`

https://github.com/python/cpython/blob/84ac4376587e35d16b4d0977c4f330d9d04b690a/Lib/asyncio/selector_events.py#L112-L122

All this seems to be doing is receiving `b'\x00` over and over again.  I'm curious about its purpose and steps I can take to reduce its use. 

@pitrou do you have any information here?  I suspect that you are quite familiar with this part of asyncio, and are also familiar with how Dask internals operate.  Do you have any suggestions on where to start looking?

**Comment by mrocklin** [comment]
cc also @minrk

**Comment by pitrou** [comment]
Well, this is a "self-pipe" meant to wake up the IO loop thread from other threads or from a signal, for example when adding a callback. Normally this mechanism isn't used when a callback is added from regular async code (i.e. called from the IO loop thread itself), but perhaps Tornado's compatibility layer doesn't make a difference between the two situations?

You'll have to trace the calls to [`_write_to_self`](https://github.com/python/cpython/blob/84ac4376587e35d16b4d0977c4f330d9d04b690a/Lib/asyncio/selector_events.py#L124-L138) to find out a bit more.

**Comment by mrocklin** [comment]
Thanks for the suggestion @pitrou .  I'll give that a try and report back.

**Comment by mrocklin** [comment]
OK, this is called when we use `loop.run_in_executor`, which we do often in two cases:

1.  In workers when we run tasks in a ThreadPoolExecutor
2.  Everywhere, when we offload deserialization/decompression to a separate thread

**Comment by pitrou** [comment]
This suggests that the unit of parallelization is not coarse enough. You should offload bigger tasks. `_read_from_self` is probably only part of the task offload overhead (but perhaps the profiler doesn't represent the rest accurately, especially if multi-threading is involved).

**Comment by mrocklin** [comment]
This seems to be a case where asyncio is a bit less efficient than Tornado.  Do we know of any other mechanisms to have an external thread trigger an event in the asyncio event loop?

**Comment by pitrou** [comment]
Not really. By construction, the event loop can only wait on file descriptors, so using a self-pipe for wakeup is how it's usually done in all event loops (the exception is a Windows-specific event loop, since Windows is a bit more flexible in allowing waits on multiple kinds of events).

**Comment by mrocklin** [comment]
> You should offload bigger tasks

Agreed.  Looking more deeply into it, it looks like we offload every serialization call, regardless of how large we expect it to be.  I can adjust this on the Dask side, but i'm also curious if there are better ways of triggering events in asyncio.

**Comment by mrocklin** [comment]
OK.  That narrows down my next steps a bit.  Thank you for the sharing your experience here @pitrou .  This conversation saved me plenty of time.

**Comment by pitrou** [comment]
You're welcome :-)

**Comment by mrocklin** [comment]
@bdarnell have you run into a negative performance change with other Tornado applications when dealing with `concurrent.futures.ThreadPoolExecutor` futures since the move to asyncio?  

Anecdotally, however the Tornado event loop handled things before did not seem to generate this level of performance concern.

**Comment by pitrou** [comment]
I would suggest that, if something appears surprising in a profiler output (here, a mechanism that exists on Tornado appearing as a bottleneck only with asyncio), then perhaps the profiler numbers are not to be trusted. IO calls are thread scheduling points (Python releases the GIL when reading from a file descriptor, even a non-blocking one), and perhaps what the profiler shows as time spent is really time spent in another thread...

**Comment by pitrou** [comment]
(I get the feeling we already had this conversation about trust in profiler numbers btw :-))

**Comment by mrocklin** [comment]
(Indeed, that does sound like a conversation that we would have had :) )

**Comment by bdarnell** [comment]
> have you run into a negative performance change with other Tornado applications when dealing with concurrent.futures.ThreadPoolExecutor futures since the move to asyncio?

No, I don't think so. I believe the threading handoffs are pretty similar between the two: it costs at least one syscall (writing to a pipe) and as many as 3 (the call to read() and another call to epoll/etc). I recall that this seems to show up more prominently in instrumentation-based profiles than its true cost (compare `cProfile` with stack-sampling profilers like `plop`)

In early iterations of the tornado/asyncio integration, things were slowed down by taking the thread-safe self-pipe path even when everything was on the main thread. That would produce the same profile symptoms. But it's fixed now (I can't remember when that landed).
