### ISSUE TITLE
scheduler hangs when performing a dd.assign

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#324]
```python
e = Executor('127.0.0.1:8786')
e
out: <Executor: scheduler=127.0.0.1:8786 processes=10 cores=160>
df = dd.read_csv('s3://xx/*.csv')
x= df.apply(lambda x: datetime.datetime.strptime(x.str_mt, "%d%b%Y").date(),axis=1)
df.assign(new_date = x).compute()
#scheduler hangs
```
the scheduler hangs and bokeh web app shows `map-partition` task that never finishes
here are the scheduler logs:

```sh
Jun 10 16:49:30 xxx conda[1003]: distributed.scheduler - INFO - Starting worker compute stream, 10.xxx.xx.xx:34198
Jun 10 16:49:30 xxx conda[1003]: distributed.scheduler - INFO - Starting worker compute stream, 10.xxx.xx.xx:59001
Jun 10 16:50:05 xxx conda[1003]: distributed.scheduler - WARNING - Heartbeat failed for 10.xxx.xx.xx
Jun 10 16:50:07 xxx conda[1003]: distributed.scheduler - WARNING - Heartbeat failed for 10.xxx.xx.xx
Jun 10 16:50:58 xxx conda[1003]: distributed.scheduler - WARNING - Heartbeat failed for 10.xxx.xx.xx
Jun 10 16:50:58 xxx conda[1003]: distributed.scheduler - WARNING - Heartbeat failed for 10.xxx.xx.xx
```

**Comment by hussainsultan** [comment]
after waiting for a while, i get the following error:
`StreamClosedError: Stream is closed`
with scheduler logs:
```sh
SystemError: <built-in method pack of pandas.msgpack._packer.Packer object at 0x7fd041482400> returned NULL without setting an error
```

**Comment by mrocklin** [comment]
That does indeed look pretty dire.  Are you on a new version of Pandas and git-master version of `distributed`?

**Comment by hussainsultan** [comment]
I am not on git-master for distributed for sure. I will check on Monday and let your know more info.

**Comment by mrocklin** [comment]
A number of things like this have been cleaned up.  I plan to have a new release within a week (perhaps much sooner) so this might alleviate things a bit.

**Comment by hussainsultan** [comment]
i can confirm that this persists with:
```python
print(dask.__version__)
print(distributed.__version__)
print(pd.__version__)
```
```
0.10.0
1.11.0
0.18.1
```

**Comment by hussainsultan** [comment]
so one of the runs actually succeeded:

<img width="1145" alt="screen shot 2016-06-13 at 9 51 19 pm" src="https://cloud.githubusercontent.com/assets/3936122/16028769/9817e168-31b0-11e6-856e-2995ce4fa64c.png">

this first task `head` took a really long time but the subsequent tasks `apply` finished afterwards: meanwhile the logs show warning for all workers heartbeat failed warning:
`distributed.scheduler - WARNING - Heartbeat failed for xxx`

but after a while somehow it recovered and finished the apply operations

**Comment by hussainsultan** [comment]
after digging into it quite a bit and using a simple lambda (without `datetime`), i find that `dd.assign` operation never returns even when the scheduler finishes all its tasks and ends in `StreamClosedError`. I am guessing this maybe a pandas issue.

**Comment by hussainsultan** [comment]
my understanding is that since this is a fairly large dataset there maybe some  network overhead that is causing client/executor to timeout once assign completes since it is trying to send a pandas dataframe back to the client.

**Comment by hussainsultan** [comment]
Sorry for back and forth but i wanted to close the loop on this. In summary, most of this was due to things like `dd.assign(x=ddf).compute()` that triggers a huge network overhead in computing a new dataframe and sending it to Client that always results in `StreamClosedError`. 

the work around (or correct way of doing this type of operation in my case) is:

```python
new_dd = dd.assign(x=ddf)
e.persist(ddf.compute)
```
this way there assign doesnt return things back to Client. 

i also discovered a pickling overhead with lambda with additional modules like datetime that may take some time to send it around over the network. 

A better error message than `StreamClosedError` in case where large datasets are returned maybe beneficial. Thoughts?

**Comment by mrocklin** [comment]
Oh yeah, sorry I didn't catch that in your earlier message.  Your assessment about compute and persist are entirely correct.  

I agree that we could come up with a better error message.  This will probably require us to pre-identify cases that move a large volume of data *before* the out-of-memory issue comes up.  We could also raise warnings whenever we start to move large volumes of data.

The heartbeat warnings are, at this stage, just warnings.  They usually start occurring whenever you start running a large amount of GIL-bound code.

**Comment by mrocklin** [comment]
Oh, you will probably want the following

```python
# Before
e.persist(ddf.compute)

# After
ddf = e.persist(ddf.compute)
```

**Comment by mrocklin** [comment]
Slight typo in previous comment, edited to correct.

**Comment by hussainsultan** [comment]
makes a ton of sense. Do you think it makes sense to close this issue since i dont think there is anything of urgent priority coming out of this. I could probably add docs with examples like these but other than that i am happy with the current state.

**Comment by mrocklin** [comment]
I'd like to see two things come out of this:

1.  Documentation on compute vs persist, probably in the distributed docs
2.  A page of common gotchas, probably in the dask docs

I'm happy to do these things as well if you don't get to them.  I suggest that we leave this open as a reminder to get these done.

**Comment by hussainsultan** [comment]
sounds good. I'd like to take a crack at the documentation since this will be a good exercise for me. I will get to it this week (hopefully).
