### ISSUE TITLE
How to get a list of active futures from the scheduler

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3263]
How can I get a list of active futures on the scheduler? Assuming i have submitted some futures via fire and forget (and different clients), how could I request a list of all futures key names that have not yet completed on the scheduler?

**Comment by mrocklin** [comment]
The full scheduler state is described in the docs here:
https://distributed.dask.org/en/latest/scheduling-state.html

You can pull anything you like by using the client.run_on_scheduler method.

**Comment by dickreuter** [comment]
Ok great, is there any documentation how I can specifically pull "keys of currently running jobs"?

**Comment by mrocklin** [comment]
If you read the documentation I referred to above you should be able to
answer that question fairly easily.

**Comment by simaster123** [comment]
I believe you're looking for something like the below.

```
def get_all_tasks(dask_scheduler=None):
     return dask_scheduler.tasks

stream = dask_client.run_on_scheduler(get_all_tasks)
```

**Comment by mrocklin** [comment]
This seems to be a Q&A.  It has gone stale.  Closing.

**Comment by jacobtomlinson** [comment]
@ghomem this issue was closed 6 years ago. As this was closed as a stale Q&A I recommend asking on the [Dask Forum](https://dask.discourse.group/) instead.

**Comment by ghomem** [comment]
@jacobtomlinson Actually I found this issue via google and because it was unanswered I  though the answer could be useful for someone else.

Thank you.

**Comment by jacobtomlinson** [comment]
Ah it sounded like you were asking further questions rather than providing an answer.
