### ISSUE TITLE
Discoonect from client

### ISSUE THREAD

**Issue by BabuTango** [dask/distributed#3284]
@mrocklin  For connecting to the client, we can use these commands

**from dask.distributed import Client
client = Client("tcp://192.168.0.999:8786")** 

After finishing my distribued computations I want disconnect from the client.

Can you help me with this

**Comment by jacobtomlinson** [comment]
You should be able to call `client.close()` when you are done with the cluster.

**Comment by BabuTango** [comment]
Thanks @jacobtomlinson

**Comment by mrocklin** [comment]
If you have further questions about how to use Dask then please use Stack
Overflow.  Please only use the Dask issue tracker when you are confident
that you have found a bug, and you are able to provide a reproducible
example for that bug.
