### ISSUE TITLE
Client no longer accepts 'threads_per_worker' parameter

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#3313]
In the most recent master, the Client can no longer be passed threads_per_worker, even though it's still documented here:

https://github.com/dask/distributed/blob/master/distributed/client.py#L571
`client = Client(address=x.x.x.x, threads_per_worker=1)  # doctest: +SKIP`

If it is passed, it will raise a runtime error:
https://github.com/dask/distributed/blob/master/distributed/client.py#L647

It's currently unclear how a job can be submitted to a worker, guaranteeing that this worker will not execute any other job at the same time. How can threads_per_worker be set to 1?

many thanks

**Comment by TomAugspurger** [comment]
I'm not sure what `threads_per_worker=1` really means with `processes=False`. If you want a single worker with one thread and no nanny, you probably want `Client(processes=False, n_workers=1)`.

**Comment by dickreuter** [comment]
I have 10 workers on different machines connected via scheduler. I want to call them, but want to ensure that they all only process one long task at the same time.

**Comment by mrocklin** [comment]
It works ok for me: 

```python
In [1]: from dask.distributed import Client

In [2]: client = Client(processes=False, threads_per_worker=1) # doctest: +SKIP

In [3]:
```

I recommend providing a minimal failing example and a full traceback.

**Comment by dickreuter** [comment]
It fails only when you pass the address keyword. Corrected the original question.

**Comment by jrbourbeau** [comment]
Any keywords other than the ones here

https://github.com/dask/distributed/blob/61238adb12d21985299fccd0f026bd42366d163f/distributed/client.py#L583-L595

are useful if you're using `Client` to create a `LocalCluster`:

https://github.com/dask/distributed/blob/61238adb12d21985299fccd0f026bd42366d163f/distributed/client.py#L540-L542

If you're connecting to an already-started scheduler (via the `address` keyword) then any additional `kwargs` are ignored. Previously they were silently ignored, but now we raise an error to avoid adding any confusion

**Comment by TomAugspurger** [comment]
Thanks @jrbourbeau!
