### ISSUE TITLE
Memory doesn't get freed up after changing reference

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#333]
```python
df = dd.read_csv('s3://xx/*.csv')
e.persist(df) #first result persists in memory

df = dd.read_csv('s3://yy/*.csv')
e.persist(df)
```

the memory on the nodes grows and df now references to the new data.However, it appears that original df doesnt get cleared in the worker memory. Is this expected behavior?

**Comment by mrocklin** [comment]
First, `e.persist` returns a new dataframe, so you should actually say the following:

```python
# e.persist(df)  # don't do this
df = e.persist(df)  # do this instead
```

Second, if you're using IPython here then its possible that it's holding onto the anonymous result in its cache.

Does this problem persist if you provide names to things as suggested above?  If so does it still persist if you explicitly call `del` or `e.cancel` on the dataframe resulting from the `persist` call?

It could also be that you have some other result in RAM.  For example maybe you've done something like the following:

    total = e.compute(df.column.sum())

This would also keep `df` around in distributed ram.  

The scheduler keeps around all data for which any client has any future that depends on that data.  If the scheduler is holding onto RAM that you don't think it should then you should look around for futures (or persisted collections of futures) that depend on that data and delete them.  Alternatively, you should be able to cancel the collection, which should percolate out to all dependent futures.

**Comment by hussainsultan** [comment]
ahh. it was Jupyter holding it in its cache. Thanks! Does this mean that if my Client disconnects, all the persisted data should go away?

**Comment by mrocklin** [comment]
Yes

**Comment by mrocklin** [comment]
Well, unless some other client is holding onto the exact same data

**Comment by hussainsultan** [comment]
I disconnected all my Clients but the memory doesnt get freed up all the way. I looked at the scheduler logs and it registers my client to disconnect.

**Comment by mrocklin** [comment]
That is surprising.  I would want to see more information about what's going on within the scheduler or a reproducible example, but that's probably difficult to produce.  We should probably expose more diagnostic information about the scheduler-client relationship just as we currently expose information about the scheduler-worker relationship.  

You can always call `e.restart()` which forces a clearing of all state and a hard reset of all workers.

**Comment by hussainsultan** [comment]
I also think the desired behavior for long-running dask cluster is that even if all clients have disconnected, we should have a mechanism to keep some keys around that can then be referenced again. My understanding was flawed since i was assuming the above is true.

`e.restart` actually does clear everything.

**Comment by mrocklin** [comment]
I can definitely see use cases for that behavior.  It's not particularly challenging to add pinned data.  

I would want to wait until there is an active use case before investing too heavily though.

**Comment by hussainsultan** [comment]
sounds good. I may come back with a concrete use case for that soon. I will dig more into what is causing all this data to be held in memory. I like your suggestion of better diagnostics for scheduler-client interactions.
