### ISSUE TITLE
No module named 'dask.system'

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/distributed#3331]
Over a Centos 7.6 after updating to the 2.9 I'm getting a ModuleNotFoundError: No module named 'dask.system' error. If I downgrade back to 2.8.1 seems not to fix the problem. 
I've tested to install both anaconda and conda-forge version and to reinstall miniconda and anaconda but nothing change. With Anaconda is distributed the 2.5 and it works. 
Any idea about how come?

import dask
import distributed
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-432545581521> in <module>
----> 1 import distributed

~/miniconda3/lib/python3.7/site-packages/distributed/__init__.py in <module>
      1 from . import config
      2 from dask.config import config
----> 3 from .actor import Actor, ActorFuture
      4 from .core import connect, rpc
      5 from .deploy import LocalCluster, Adaptive, SpecCluster, SSHCluster

~/miniconda3/lib/python3.7/site-packages/distributed/actor.py in <module>
      5 from queue import Queue
      6
----> 7 from .client import Future, default_client
      8 from .protocol import to_serialize
      9 from .utils import sync

~/miniconda3/lib/python3.7/site-packages/distributed/client.py in <module>
     67 from .sizeof import sizeof
     68 from .threadpoolexecutor import rejoin
---> 69 from .worker import dumps_task, get_client, get_worker, secede
     70 from .diagnostics.plugin import WorkerPlugin
     71 from .utils import (

~/miniconda3/lib/python3.7/site-packages/distributed/worker.py in <module>
     20 from dask.compatibility import apply
     21 from dask.utils import format_bytes, funcname
---> 22 from dask.system import CPU_COUNT
     23
     24 try:

ModuleNotFoundError: No module named 'dask.system'

**Comment by jrbourbeau** [comment]
What version of dask are you using? The `dask.system` module should exist for `dask >= 2.7.0`. Upgrading both `dask` and `distributed` to 2.9.0 should resolve the `ModuleNotFoundError`

**Comment by PhenoloBoy** [comment]
Actually is the opposite, to make it work I have to downgrade to the 2.7 
Tested over 2.8.1 and 2.9 and raise the ModuleNotFoundError

**Comment by jrbourbeau** [comment]
Thanks for the quick reply @PhenoloBoy! Hrm, so you're saying `dask==2.9.0` and `distributed==2.9.0` doesn't work? I'd be curious to see what the output of 

```python
import dask
print(f"dask.__version__ = {dask.__version__}")
import distributed
print(f"distributed.__version__ = {distributed.__version__}")
```

looks like when you run it on your system.

When I create a new conda environment with 

```
conda create --name distributed-import-test python=3.7 dask=2.9.0 distributed=2.9.0
```

I'm able to successfully import both `dask` and `distributed` and get:

```
dask.__version__ = 2.9.0
distributed.__version__ = 2.9.0
```

**Comment by PhenoloBoy** [comment]
Bingo! 
I was focused on the conda info result that was reporting 2.9 for both and thanks to your suggestion I spot that, instead, the system picks up a 2.4 version from somewhere. 
As it was a last-minute test I didn't have time to further investigate the reason but at least now it make sense. Pretty sure that there must be something in the system PATH variable that points to an old version that I wasn't aware.

**Comment by PhenoloBoy** [comment]
@jrbourbeau seems that the problem was due to partial isolation of conda. 
[Here](https://github.com/conda/conda/issues/7173) more infos on the issue.
As a workaround, I had to remove all the local package with :

`pip freeze | xargs pip uninstall -y` from [here](https://stackoverflow.com/questions/11248073/what-is-the-easiest-way-to-remove-all-packages-installed-by-pip)

**Comment by jrbourbeau** [comment]
I see, thanks for the additional information. Glad to hear things are working now!
