### ISSUE TITLE
Document Futures mutability of underlying data

### ISSUE THREAD

**Issue by devin-petersohn** [dask/distributed#3350]
I would like to propose adding something to the documentation that discusses the mutability of Futures objects (the underlying data that is).

```python
from distributed import Client
import pandas 

c = Client()  # LocalCluster
df = pandas.DataFrame({"c":[1,2,3,4], "d":[4,5,6,76]})  
a_future = c.scatter(df)
assert a_future.result().index.equals(df.index) 
b_future = c.submit(lambda df: df.set_axis([str(i) for i in df.index], axis="index", inplace=True), a_future)  # A typo, for instance
b_future = c.submit(lambda df: df.set_axis([str(i) for i in df.index], axis="index", inplace=False), a_future)  # Correct the line
assert a_future.result().index.equals(df.index)  # False, `a_future` is modified inplace
```

Is there a location in the documentation that mentions the assumption within Dask that the functions applied to data do not update the underlying data? I spent several hours trying to debug an issue and came up with this small example to show what I was experiencing. I think adding something to the Futures page about the mutability of the underlying data is worthwhile, and I'm willing to contribute the text.

**Comment by mrocklin** [comment]
Thanks for bringing this up @devin-petersohn .  I searched briefly for terms like "pure" and "in-place" and came up with some, but nothing that would have explicitly avoided your frustrating experience.  it would be good to resolve this.  Do you have any recommendations?

The challenge with Dask's documentation is that there are a few places that you would want to mention this.  It's not just that Dask's futures interface expects functions that don't modify values in-place, it's that pretty much all of Dask's task scheduling system assumes this.  Adding a note to the futures page would be good, although we would want to weave it into the current narrative well. This would also apply to dask.delayed, or anywhere that Dask accepts user defined functions.  Adding the same note everywhere seems like it would clutter things, but at the same time I don't think that we can expect users to read through the lower level documentation.  

Do you have any recommendations on what would be good that would both have clearly resolved your problem, and also not bloat things too much?

**Comment by devin-petersohn** [comment]
I see, it may be sufficient to add details in one place then reference it with a single Note(!) everywhere else. My problem is that I am familiar with Apache Arrow's plasma store that treats the data as immutable and so I subconsciously assumed that translated here. 

I took a look through the documentation, but I'm not entirely sure where the best place would be. I would personally look through the Futures documentation first to see mention of the data being mutable, but I also don't know if I represent the average Dask user. As long as it is easily indexed by search engine for the main keywords, I think it would be fine for most cases.

**Comment by mrocklin** [comment]
> My problem is that I am familiar with Apache Arrow's plasma store that treats the data as immutable and so I subconsciously assumed that translated here

Ah, Plasma does something like copy-on-write semantics?  Cool.

> I would personally look through the Futures documentation first to see mention of the data being mutable, but I also don't know if I represent the average Dask user. As long as it is easily indexed by search engine for the main keywords, I think it would be fine for most cases.

I suspect that it is equally likely for users to come to this through delayed and futures, with udfs in dataframes arrays and bags coming behind.  I recommend that we add an "expectations" or "restrictions" section here:  https://docs.dask.org/en/latest/graphs.html that includes things like mutation, holding the GIL, global state, and so on, and then link to that as necessary.  

Would you be interested in starting that section in the task graphs page, including the mutation bit that you ran into, and linking to that section from futures and then I'll add the other constraints afterwards?  No obligation of course, raising this issue is helpful on its own, but the help would be welcome.

**Comment by devin-petersohn** [comment]
Sure, I'm happy to contribute the start of the section.
