### ISSUE TITLE
What is local directory used for in the dask scheduler?

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/distributed#3351]
The `dask-scheduler` has an option called `--local-directory`.

I checked the source code https://github.com/dask/distributed/blob/master/distributed/cli/dask_scheduler.py

And all I can see is that the directory gets added to the `sys.path`.

However nothing is ever put inside there. It seems the code is vestigial. Designed for preloading, but the preloading code was removed from `dask-scheduler`. Does this mean this directory is useless?

**Comment by mrocklin** [comment]
Indeed, it does appear to be vestigal (nice word by the way), and should probably be removed.  Is this something that you're interested in doing?
