### ISSUE TITLE
Switch gen.with_timeout to asyncio.wait_for

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#3367]
There are several instances where [`gen.with_timeout`](https://www.tornadoweb.org/en/stable/gen.html#tornado.gen.with_timeout) is used in the codebase. As part of our switch from existing tornado code to asyncio, we should move to using [`asyncio.wait_for`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for).

However, one important distinction between these functions is that `gen.with_timeout` does not cancel a task when it's timeout expires, while `asyncio.wait_for`does cancel the task. So we need to be careful and determine on a case by case basis when task cancellation on timeout should happen. From @jcrist's comment (https://github.com/dask/distributed/pull/3365#issuecomment-573342606):

> replacing it isn't always straightforward. Each case needs to be examined to determine what the intent was and if the lack of cancellation was accidental or necessary.

To avoid task cancellation when using `asyncio.wait_for`, the task should first be wrapped in [`asyncio.shield`](https://docs.python.org/3/library/asyncio-task.html#asyncio.shield)

**Comment by mrocklin** [comment]
My guess is that in most cases we'll be fine with cancellation.  I would
encourage a PR that tries this, just to see if the test suite passes.

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/3372
