### ISSUE TITLE
Incorrect task counts in scheduler status page

### ISSUE THREAD

**Issue by bnaul** [dask/distributed#3368]
Surprised this hasn't already been posted as I started noticing it at least a month ago:
```
c = distributed.Client()
f = c.submit(sum, [1, 2])
g = c.submit(len, [1, 2])
h = c.submit(sum, [3, 4])
```
Previously the plot would show 2 `sum`s and 1 `len`; now (on 2.9.1 and master, `distributed==2.9.1+10.g44d24098`) it shows 3 of each:
![image](https://user-images.githubusercontent.com/903655/72282921-91a3a480-35f2-11ea-97d9-6b2a79bcd146.png)
This behavior continues indefinitely, so with e.g. 1 `len` and 10000 `sums` we'd see 10001 of each for a total of 20002. Observed the same behavior w/ bokeh 1.0.4 and 1.4.0.

**Comment by quasiben** [comment]
@bnaul yup, looks like this is a bug.  Thank you for reporting.  I think there was some work around aggregate task info last month.  I'll take a look

**Comment by mcguipat** [comment]
I believe this is related but I've also observed incorrect task execution information on the status page of the UI following upgrading `distributed` from `2.9.0 -> 2.9.1`.  This includes showing tasks that were previously executed (but not currently executing) as executing alongside tasks that are actually currently executing.
