### ISSUE TITLE
[Feature] Add support for ClickHouse

### ISSUE THREAD

**Issue by frol** [dask/distributed#337]
*Disclaimer. It is just "a nice idea" since there is only HTTP interface available at this point of time.*

[ClickHouse](https://clickhouse.yandex/) is an open-source column-oriented database management system that allows generating analytical data reports in real time.

ClickHouse manages extremely large volumes of data in a stable and sustainable manner. It currently powers Yandex.Metrica, world’s second largest web analytics platform, with over 13 trillion database records and over 20 billion events a day, generating customized reports on-the-fly, directly from non-aggregated data. This system was successfully implemented at CERN’s LHCb experiment to store and process metadata on 10bn events with over 1000 attributes per event registered in 2011.

**Comment by mrocklin** [comment]
Generally integrating with other systems is good, especially over standard protocols (like ODBC).  I would prefer to see integration with individual databases start in third-party modules rather than be part of the Dask codebase.

**Comment by mrocklin** [comment]
Closing this for now as out-of-scope.  I'd be happy to help anyone who wanted to do this externally.

**Comment by kszucs** [comment]
@frol I'm planning to implement an adapter for clickhouse. Are You still interested?

**Comment by frol** [comment]
@kszucs I would be very happy to see and try it. Currently, we are settled down with HDFS/Parquet, but ClickHouse and Kudu look quite interesting to me. Thank you for tackling this issue!

**Comment by kszucs** [comment]
@wesm @martindurant What do You think, how difficult would it be to create an adapter for clickhouse?

On short term we can connect via http client, on long term with a cython wrapper around [odbc](https://github.com/yandex/clickhouse-odbc).

How should we get started? Some general advice about partitioning, data locality?

**Comment by martindurant** [comment]
Is https://github.com/cloudflare/sqlalchemy-clickhouse enough to use `dask.dataframe.read_sql_table`?

**Comment by kszucs** [comment]
I guess yes, but I'll take a try. How about writing/persisting a ddf? Just `ddf.map_partitions(lambda df: df.to_sql(...))`?

**Comment by martindurant** [comment]
I haven't got around to writing a to_sql method yet but yes, it should be simple like that (using insert for the partitions).

**Comment by kszucs** [comment]
I had a couple of problems with reading from clickhouse:
- incorrent divisions related to https://github.com/dask/dask/issues/2260 
- empty resultset raises a non-existing column when trying to sat as index (it might be a dask issue instead of sqlalchemy-clickhouse)

I'm planning to create a library to provide: `read_clickhouse_table` along with `read_clickhouse` (query). When reading a clickhouse table we can query the partitions (or dask divisions) from system.parts for the table beforehand.

@frol AFAIK you have a lot of experience with building alpine and/or c++ stuff. Could You give me a hand to compile https://github.com/yandex/clickhouse-odbc ?

**Comment by kszucs** [comment]
@frol I've created a minimal pandas reader/writer here https://github.com/kszucs/pandahouse

The next one will be dask support.

**Comment by cloudronin** [comment]
> @martindurant @frol I've created a minimal pandas reader/writer here https://github.com/kszucs/pandahouse
> 
> The next one will be dask support.

@kszucs any update on dask support ?

**Comment by kszucs** [comment]
see my comment https://github.com/yandex/ClickHouse/issues/720#issuecomment-474715158
