### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__

### ISSUE THREAD

**Issue by davideps** [dask/distributed#3393]
When I submit a task to the client that included or generates a [grakn](https://grakn.ai/) transaction object, I get an error like this:
```
result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "stringsource", line 2, in grpc._cython.cygrpc.Channel.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
Other permutations of this code generated errors like "can't pickle a lock object". The code runs fine with dask when I remove the grakn calls and it runs fine with grakn when I remove dask. What do these errors mean?

**Comment by TomAugspurger** [comment]
Dask needs to send bits of data between machines. By default, we use pickle, though you can register custom serializers for custom objects. This is documented at https://distributed.dask.org/en/latest/serialization.html

I'd recommend reaching out to the grakn project to see if their objects can be pickled, or implementing your own serializer.
