### ISSUE TITLE
WorkStealing in DEFAULT_EXTENSIONS when work stealing disabled

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#3409]
It appears that if work stealing is not disabled before importing `dask.distributed` the `config` value is ignored. For example please take the following examples:

Work stealing still enabled:

```python
import dask
import dask.distributed
dask.config.set({'distributed.scheduler.work-stealing': False})
```

Work stealing disabled:

```python
import dask
dask.config.set({'distributed.scheduler.work-stealing': False})
import dask.distributed
```

This seems to come down to the fact that [`dask.distributed.scheduler.DEFAULT_EXTENSIONS` will have `distributed.stealing.WorkStealing` added in the former case]( https://github.com/dask/distributed/blob/3a2f8a84121d27decf432cd4f379724907ea2b3d/distributed/scheduler.py#L92-L93 ) and not the latter. It does not appear that `dask.distributed.scheduler.DEFAULT_EXTENSIONS` is updated later either.

<hr>

As a workaround, users may consider including the following code before starting up any Dask clusters.

```python
from contextlib import suppress
import dask
import dask.distributed

if not dask.config.get("distributed.scheduler.work-stealing"):
    with suppress(ValueError):
        dask.distributed.scheduler.DEFAULT_EXTENSIONS.remove(
            dask.distributed.stealing.WorkStealing
        )
```

**Comment by jrbourbeau** [comment]
We could move the config check and corresponding `WorkStealing` append inside `Scheduler.__init__` here:

https://github.com/dask/distributed/blob/3a2f8a84121d27decf432cd4f379724907ea2b3d/distributed/scheduler.py#L1335-L1336

I think that's the only place where `DEFAULT_EXTENSIONS` for the `Scheduler` class is used

**Comment by jrbourbeau** [comment]
So something like:

```python
if extensions is None:
    extensions = DEFAULT_EXTENSIONS
    if dask.config.get("distributed.scheduler.work-stealing"):
        extensions.append(WorkStealing)
```

What do you think?

**Comment by jakirkham** [comment]
Seems reasonable to me.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/dask/distributed/pull/3410 ) with the suggested fix 🙂
