### ISSUE TITLE
dask-ssh fails if Python is installed in different paths across the workers

### ISSUE THREAD

**Issue by felipeam86** [dask/distributed#341]
I tested distributed on a very simple office "cluster" : My laptop and office server. Both are on Ubuntu 14.04, but I installed Python differently on both. In my laptop I did a user install of miniconda and in the server I installed anaconda as root. The corresponding python paths are :

10.1.0.115 --> '/home/aguirre/miniconda2/bin/python' (My laptop)
10.1.0.118 --> '/opt/anaconda2/bin/python' (Server)

If I manually launch `dask-worker` and `dask-scheduler`, everything works fine. But if I try `dask-ssh`, it does not work :

```
$ dask-ssh 10.1.0.{115,118}
---------------------------------------------------------------
                 Dask.distributed v1.11.0

Worker nodes:
  0: 10.1.0.115
  1: 10.1.0.118

scheduler node: 10.1.0.115:8786
---------------------------------------------------------------


[ scheduler 10.1.0.115:8786 ] : /home/aguirre/miniconda2/bin/python -m distributed.cli.dask_scheduler --port 8786
[ worker 10.1.0.115 ] : /home/aguirre/miniconda2/bin/python -m distributed.cli.dask_worker 10.1.0.115:8786 --host 10.1.0.115 --nthreads 0 --nprocs 1
[ worker 10.1.0.118 ] : /home/aguirre/miniconda2/bin/python -m distributed.cli.dask_worker 10.1.0.115:8786 --host 10.1.0.118 --nthreads 0 --nprocs 1
[ scheduler 10.1.0.115:8786 ] : distributed.scheduler - INFO - Scheduler at:           10.1.0.115:8786
[ scheduler 10.1.0.115:8786 ] : distributed.scheduler - INFO -      http at:           10.1.0.115:9786
[ scheduler 10.1.0.115:8786 ] : distributed.scheduler - WARNING - Could not start Bokeh web UI
[ scheduler 10.1.0.115:8786 ] : Traceback (most recent call last):
[ scheduler 10.1.0.115:8786 ] :   File "/home/aguirre/miniconda2/lib/python2.7/site-packages/distributed/cli/dask_scheduler.py", line 92, in main
[ scheduler 10.1.0.115:8786 ] :     bokeh_proc = subprocess.Popen(args)
[ scheduler 10.1.0.115:8786 ] :   File "/home/aguirre/miniconda2/lib/python2.7/subprocess.py", line 710, in __init__
[ scheduler 10.1.0.115:8786 ] :     errread, errwrite)
[ scheduler 10.1.0.115:8786 ] :   File "/home/aguirre/miniconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
[ scheduler 10.1.0.115:8786 ] :     raise child_exception
[ scheduler 10.1.0.115:8786 ] : OSError: [Errno 2] No such file or directory
[ worker 10.1.0.118 ] : bash: /home/aguirre/miniconda2/bin/python: No such file or directory
[ worker 10.1.0.118 ] : remote process exited with exit status 127

```

As you can see, the worker on `10.1.0.118` tries to call python on the wrong path (`/home/aguirre/miniconda2/bin/python`) which happens to be the path of the scheduler (`10.1.0.115`)

I took a look at the code and I think the problem lies on the [line 189 of cluster.py](https://github.com/dask/distributed/blob/master/distributed/cluster.py#L189). It builds the command to be launched by each worker with the path of the node where `dask-ssh` was launched. Just to check, I hard-coded the python path of `10.1.0.118` on line 189 of cluster.py, and it correctly launches the worker ! However, it now fails to launch a worker on `10.1.0.115`, which is normal...

BTW, I don't think the Exception raised by the scheduler (10.1.0.115) is related... it seems that it does not find bokeh in the PATH... However, when I launch the scheduler by itself, it does manage to launch bokeh web UI. But lets handle one problem at a time and focus on the Python PATH bit of my case.

I don't have many clues on how this could be solved, but with some guidance, I'm willing to give a hand !

**Comment by mrocklin** [comment]
Yeah, that's the behavior I would expect running this tool on systems with Python located in different places.  The Bokeh error is likely the same issue.

In principle this is a hard problem.  There might be several Python installations on your computers and there is no clear way to find the right one.  One approach would be to try the location of the executable on the host machine (what we do now) and then, if that fails, fall back to `python` executable listed in the system path (by just calling `python` rather than `/a/path/to/a/specific/python`) if the first options fails.

**Comment by felipeam86** [comment]
Well, I also tested hard-coding 'python', but that does not work well either. It bumps into the python installed by Ubuntu. But my whole python environement (including distributed) lies on the anaconda installation.

**Comment by mrocklin** [comment]
Right, that's precisely the kind of problem that led to the hard-coding of explicit paths.

**Comment by mrocklin** [comment]
You probably have something set in a bashrc file (or similar) that extends your PATH environment variable to point to your miniconda distribution.  Perhaps we need to find a way to ssh in as a normal user to trigger the various environment tricks that occur.

**Comment by hussainsultan** [comment]
i have had success using `conda run` with an environment name that is already setup (either via anaconda or miniconda) like so:

```
conda run -n dask_env --offline -- dscheduler 
```
this works as long as you have conda command available that is either symlinked to anaconda path or miniconda.

**Comment by felipeam86** [comment]
@hussainsultan I'm aiming more towards solving the problem and not going around it. Either way, I tested your solution, but it didn't work.

```
$ conda run -n dask_env --offline -- dscheduler 
Error: Could not locate 'conda-run'
```

I'm not familiar with `conda run`, didn't find that much info on google and the [docs seem to be broken](http://conda.pydata.org/docs/commands/conda-run.html). @hussainsultan can you give me a hint on the matter ?

**Comment by mrocklin** [comment]
We should probably establish the scope/assumptions of `dask-ssh`.  Currently it assumes an equivalent environment on all nodes.  Perhaps we just continue assuming this and don't bother to extend it.

I think that a somewhat cheap extension would be to try `python` instead of `/path/to/python` if the latter fails but somehow improve the ssh connection by bringing in the user environment variables.  There might be a simple way to do this.

**Comment by hussainsultan** [comment]
@felipeam86 you may have to provide the full path to conda (it appears `home/aguirre/miniconda2/bin/conda`?) I totally agree that its a workaround but i think it is probably a good way to ensure that standard environments are present and created for all nodes. I have been using this pattern with success. By no means, it is a solution for `dask-ssh` but perhaps it could be extended to support `conda run` if that is indeed a value add.

**Comment by felipeam86** [comment]
@mrocklin if you continue assuming an equivalent environment on all nodes, I suggest to explicitly mention this in the docs. My entry point was the quickstart btw.

Otherwise, I think we should aim towards a robust solution. Again, I'm willing to give a hand, but I would need some guidance as to where to start.

**Comment by felipeam86** [comment]
@hussainsultan maybe I was not clear enough. I am familiar with `conda`, but not with `conda run`. My installation does not recognize the `run` command of `conda`. Moreover, I don't see how this might solve the problem of `dask-ssh`.

**Comment by mrocklin** [comment]
@felipeam86 I see two starting options:  

1.  Add notes to the documentation `dask/docs/source/...rst` that `dask-ssh` is assuming similar environments, such as you might see on a system with a shared file system.

2.  Play with `paramiko` and learn how to create a connection that respects user environments.  This probably involves some googling, some doc reading, and some experimentation on your own two-machine cluster setup.  Then play with the implementation in `dask/cluster.py` to implement the changes that you needed in order to make things work well in experiements.

**Comment by hussainsultan** [comment]
@felipeam86 here is the documentation for conda run conda.pydata.org/docs/commands/conda-run.html

**Comment by colin-svds** [comment]
@hussainsultan that link is a 404.

**Comment by felipeam86** [comment]
@mrocklin so far, this seems to work:

    import paramiko

    for ip in ['10.1.0.115', '10.1.0.118', '10.1.0.240']:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(ip)
        stdin, stdout, stderr = ssh.exec_command('which python\n', get_pty=True)
        print ip, '--> Python path:', stdout.readlines()[0]
        ssh.close()

Output:

    10.1.0.115 --> Python path: /home/aguirre/miniconda2/bin/python

    10.1.0.118 --> Python path: /opt/anaconda2/bin/python

    10.1.0.240 --> Python path: /usr/bin/python

**Comment by felipeam86** [comment]
@mrocklin so far, this seems to work:

    import paramiko

    for ip in ['10.1.0.115', '10.1.0.118', '10.1.0.240']:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(ip)
        stdin, stdout, stderr = ssh.exec_command('which python\n', get_pty=True)
        print ip, '--> Python path:', stdout.readlines()[0]
        ssh.close()

Output:

    10.1.0.115 --> Python path: /home/aguirre/miniconda2/bin/python

    10.1.0.118 --> Python path: /opt/anaconda2/bin/python

    10.1.0.240 --> Python path: /usr/bin/python

        
I tried to put this into the source code of distributed and it solved my problems. However, I think [my solution](https://github.com/felipeam86/distributed/commit/a29e7f934c60b4382807c9c82ce470e2c17b1086)  is not robust, it is more like a lazy patch, sorry...

**Comment by caseyjlaw** [comment]
@hussainsultan @felipeam86 'conda run' was removed without much notice in 4.0.10:
https://github.com/conda/conda/issues/2682

There is talk of bringing it back, but I don't see it in conda 4.1.11.
