### ISSUE TITLE
TextProgressBar and logging/print

### ISSUE THREAD

**Issue by kwunlyou** [dask/distributed#3414]
In [TextProgressBar](https://github.com/dask/distributed/blob/4081a0e09febd9099f04a1db9772f6cd95203b2e/distributed/diagnostics/progressbar.py#L138)

```python 
    def _draw_stop(self, **kwargs):
        sys.stdout.write("\r")
        sys.stdout.flush()
```

probably `\n` is better than `\r`? otherwise, other `stdout` messages from `logging` or `print` can't be displayed well.

**Comment by jrbourbeau** [comment]
I believe the use of `\r` is to prevent outputting many lines from the progress bar (one line each time the progress bar is drawn). What's the current behavior when using the text progress bar and printing/logging something? I would be in favor of improving the current printing/logging behavior as long as we don't print a separate progress bar line each time the bar is drawn.

**Comment by kwunlyou** [comment]
@jrbourbeau 
>I believe the use of \r is to prevent outputting many lines from the progress bar (one line each time the progress bar is drawn). 

My concern is about the `\r` in `_draw_stop` but not in `_draw_bar`. I think it is better to use `\n` in `_draw_stop` otherwise this could mess up the following output of `stdout`, such as 

![image](https://user-images.githubusercontent.com/1352316/73248551-12de6800-41ab-11ea-8acc-d63d7fbc36f1.png)

in the figure, `d | 32.9s` is from the progress bar

the right output should be like 
![image](https://user-images.githubusercontent.com/1352316/73248841-926c3700-41ab-11ea-89bc-b31317731bea.png)

**Comment by jrbourbeau** [comment]
Thanks for the screenshots @kwunlyou, those are useful. At this point I think it may be easier to review a PR so things can be tested locally. Is that something you're interested in doing? (no obligation)

**Comment by ma-sadeghi** [comment]
What's the status on this issue? Is it on your radar by any chance?

**Comment by jakirkham** [comment]
I don't think anyone has picked this up. Is this something you are interested in doing, Amin? 🙂

**Comment by ma-sadeghi** [comment]
@jakirkham Sure, I just don't know where to start. Could you please give me some pointers?

**Comment by jakirkham** [comment]
I think this is mostly covered by other comments in the issue. Would suggest reading back over them and trying those changes in a new PR
