### ISSUE TITLE
Possible Incorrect Sizeof Calculations

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3415]
In https://github.com/dask/distributed/pull/3410, @mrocklin noted that work-stealing issues might be related to incorrect size measurements of objects being moved through dask.  I _think_ the following is the location where computing the correct `sizeof` is critical (though there may be other locations).

https://github.com/dask/distributed/blob/241d0d44d8a108bf2412696455dd7486bdfbff17/distributed/worker.py#L3361

Using `sizeof`, does generally calculate the size of cuDF dataframe correctly (it is off by 32bytes below), though `nbytes` is quite short of the full size.

```python
In [1]: import cudf

In [2]: from distributed.utils import nbytes

In [3]: cdf = cudf.datasets.timeseries()

In [4]: cdf.memory_usage(deep=True)
Out[4]:
id       20736008
name      2592673
x        20736008
y        20736008
Index    20736008
dtype: int64

In [5]: nbytes(cdf)
Out[5]: 2592001

In [6]: from distributed.sizeof import safe_sizeof

In [7]: safe_sizeof(cdf)
Out[7]: 85536737

In [8]: cdf.memory_usage(deep=True).sum()
Out[8]: 85536705
```

cc @pentschev

**Comment by mrocklin** [comment]
The use of nbytes shouldn't matter.  It is only used on bytes-like objects like `bytes` or `memoryview`s.  The correct function to check is `sizeof`, which as you note looks fine.  

Another reason for work stealing to be behaving poorly is that our estimate of bandwidth is off.  How is UCX + Dask these days?  If it is occasionally much slower than expected then that would also cause excessive communication.

Dask only moves data when it thinks that it's a good idea.  It determines this based on...
1.  How quickly it thinks it can move data between two machines.  This depends on both the estimated size of the data (with sizeof) and the estimated bandwidth between those two machines
2.  How much work there is to do on the machine that is stolen from. This is based on historical runtimes of functions currently queued on that machine

So if sizeof or bandwidth estimates are off then you can sometimes find that there is too much stealing or not enough.

**Comment by quasiben** [comment]
@mrocklin thank you for the details.  UCX + Dask is performant but I think there is also wide variability in the bandwidth.  Depending on a number of parameters (RMM Pooling, IPC Caching, IB usage, etc) I have observed bandwidths varying between 100s of MB/s to several GB/s .  @beckernick have you observed similar variability ?

**Comment by pentschev** [comment]
I'm not sure I understand how is bandwidth estimated, is that done only at runtime or is also the `distributed.scheduler.bandwidth` parameter relevant in that process?

**Comment by mrocklin** [comment]
We start with the configuration parameter, but we update it over time based
on observed bandwidths.  We maintain an exponentially weighted moving
average of bandwidth that is updated every time the scheduler receives a
heartbeat from the worker.  If you search distributed/scheduler.py for
bandwidth you'll find a few places where things are updated.  There are
equivalent variables in worker.py .

**Comment by pentschev** [comment]
Thanks for the summary @mrocklin , I understand now and it seems like a good way to do it over time. I think we may have additional overhead in UCX that's being accounted as transfer time, we probably need to do some additional investigation regarding this.

**Comment by quasiben** [comment]
for cuDF strings there might be a discrepancy between calculating the size of a object:

> safe_sizeof(cdf)

And getting the size of the buffers of the object when serializing:

> h, f = cdf.serialize()
> sum([nbytes(_) for _ in f])

see https://github.com/rapidsai/cudf/issues/3969 for more details.  I have not traced all of the bandwidth code, but it looks like we call nbytes on deps in `get_data`:

https://github.com/dask/distributed/blob/457281ba826df106737ed96c9327124cc85f6d29/distributed/worker.py#L1232

Does this measurement feed into bandwidth ?

**Comment by quasiben** [comment]
I think we can close this.  I believe, dask is measuring sizes correctly.
