### ISSUE TITLE
Distributed memory error 95% error on smaller zarr file

### ISSUE THREAD

**Issue by Sh4zKh4n** [dask/distributed#3416]
Hi, I've been using dark distributed for some image processing pipelines all day. I've run lots of trials with a zarr file (100gb on disk but array is 270gb). I've been using the local client. 

All of a sudden I keep getting nanny warning and worker shutdowns, even though now I'm working on a small file? I may be missing something simple but, it was working fine and then all of a sudden it didn't like working on anything. I may have run a key interrupt but I've client.restarted() everything a few times. I even tried to call and load the client the file I worked on previously but it's now just crashing. I noticed few others having similar issues?

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @Sh4zKh4n. Are you able to provide any more details about the code your running (example snippet) or any error messages your getting? See https://blog.dask.org/2018/02/28/minimal-bug-reports for crafting minimal bug reports

**Comment by Sh4zKh4n** [comment]
Now heres where i admit im a terrible coder and am learning, still... 

I made a very silly mistake and instead of da.to_zarr , i wrote filename.to_zarr , which seems to be the problem! I have just fixed this issue and I am repeating the original work from yesterday and it's file and function that initially worked and then i couldnt get it to work! It's working fine and going through the motions. So sorry for my newbie issue!

**Comment by Sh4zKh4n** [comment]
Just wanted to say thank you, you made me take a break and re look at what i had done to the code. It's working beautifully and since i cleaned up the code as yesterday. I think its running faster than the first time. This thing is great! Just need to get a handle on this and on image processing and i can have continuous fun with my imaging data!

**Comment by jrbourbeau** [comment]
Not a problem at all. We're all still learning. Glad to hear things are working now
