### ISSUE TITLE
test_local_tls fails on master (MacOS High Sierra, Ubuntu)

### ISSUE THREAD

**Issue by pierreglaser** [dask/distributed#3417]
Reproducer (on a fresh `Python3.7` virtual environment, assuming you at the `distributed` root)

```
pip install -e .
python -m pytest distributed/deploy -k test_local_tls
```

By bisecting the repository it seems that the faulty commit is 3151f09e.
I am not an expert, but it seems that there relying only on `hostname` is not enough -- itself probably being linked tot the fact that we don't pass the IP version (v4 or v6) anymore. As proposed by the already existent [inline comment](https://github.com/dask/distributed/blob/4081a0e09febd9099f04a1db9772f6cd95203b2e/distributed/utils.py#L141), we should probably use `socket.getaddrinfo` or `socket.getfqdn()` on top of the `hostname`.

This currently affects the downstream builds of `cloudpickle`, (see cloudpipe/cloudpickle#324), so pinging @jakirkham :)

**Comment by jakirkham** [comment]
Thanks both for finding and fixing this issue, Pierre! 😄
