### ISSUE TITLE
WorkerPlugin loses name on restart

### ISSUE THREAD

**Issue by nsmith-** [dask/distributed#3426]
If I make a named plugin like:
```python
from distributed import Client, WorkerPlugin, get_worker
client = Client()
client.register_worker_plugin(WorkerPlugin(), 'myplugin')
client.run(lambda: list(get_worker().plugins))
```
then I see the output of the last command has properly-named plugins:
```
{'tcp://127.0.0.1:58761': ['myplugin'],
 'tcp://127.0.0.1:58762': ['myplugin'],
 'tcp://127.0.0.1:58763': ['myplugin'],
 'tcp://127.0.0.1:58764': ['myplugin']}
```
but after issuing a `client.restart()` now the same plugin listing shows:
```
{'tcp://127.0.0.1:58806': ['<distributed.diagnostics.plugin.WorkerPlugin objec-4ecf53b0-b67d-40f5-b2e3-fcb2e76d1979'],
 'tcp://127.0.0.1:58807': ['<distributed.diagnostics.plugin.WorkerPlugin objec-596662ab-f814-481b-a6f4-dc068c65e66c'],
 'tcp://127.0.0.1:58810': ['<distributed.diagnostics.plugin.WorkerPlugin objec-a49d12a3-2f47-4672-b53f-e93299a9290d'],
 'tcp://127.0.0.1:58812': ['<distributed.diagnostics.plugin.WorkerPlugin objec-533dd071-54d4-4452-8763-557d721c7968']}
```

I would prefer if the name stuck.  Also, is there no method to unregister plugins?

P.S. `distributed.__version__` is 2.9.0

**Comment by mrocklin** [comment]
Oh indeed.  It would be good if the name stuck.  I totally agree.  Is this something that you would be interested in investigating?

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue and providing a nice example @nsmith-! Good to see you here : )

Just a heads up, if your plugin has a `name` attribute then things should currently work. For example,

```python
from pprint import pprint
from distributed import Client, WorkerPlugin, get_worker

class MyPlugin(WorkerPlugin):
    name = "my_plugin"

if __name__ == "__main__":

    client = Client()
    client.register_worker_plugin(MyPlugin())
    print("Before restart:")
    pprint(client.run(lambda: list(get_worker().plugins)))
    client.restart()
    print("After restart:")
    pprint(client.run(lambda: list(get_worker().plugins)))
```

outputs

```
Before restart:
{'tcp://127.0.0.1:53243': ['my_plugin'],
 'tcp://127.0.0.1:53244': ['my_plugin'],
 'tcp://127.0.0.1:53247': ['my_plugin'],
 'tcp://127.0.0.1:53249': ['my_plugin']}
After restart:
{'tcp://127.0.0.1:53269': ['my_plugin'],
 'tcp://127.0.0.1:53270': ['my_plugin'],
 'tcp://127.0.0.1:53273': ['my_plugin'],
 'tcp://127.0.0.1:53275': ['my_plugin']}
```

As you pointed out there's definitely room for improvement here, just wanted to mention a temporary workaround

Taking a quick look at the relevant scheduler code, it looks like `Scheduler.worker_plugins` is currently a list of plugins which doesn't keep track of any assigned names beyond what is stored on the class itself (i.e `.name` attribute). So when a worker registers with the scheduler after a restart, this message from the scheduler doesn't contain any previous user assigned names:

https://github.com/dask/distributed/blob/8eadf5e8fa56673aef9063fa91c52f4715638b6d/distributed/scheduler.py#L1710-L1715

**Comment by nsmith-** [comment]
I would also be fine if the `name` attribute is expected to be defined for concrete WorkerPlugin classes, then the optional parameter in `client.register_worker_plugin` could be dropped to avoid confusion.  I'll take a look if I have time, might not be right away.

**Comment by jsignell** [comment]
I think this has been resolved. I just tried to go back to the PR that I'd started and I found that the MRE works as expected now :)
