### ISSUE TITLE
Profile hover extends beyond window

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3427]
Often when looking at the dask dashboard profile page the hover showing the filename and code goes off the edge of the screen, so that it is no longer visible.  This makes it hard to interact with the profile page some times.  

We might fix this in two ways:

1.  Fix things upstream with Bokeh, so that they make sure to move hover elements within the window
2.  Trim our lines of text which can be somewhat long.  This comes up in particular with the filename and sometimes with the line of code.  It might be worth wrapping or truncating those lines of text in some cases.  

That code lives here:

https://github.com/dask/distributed/blob/8eadf5e8fa56673aef9063fa91c52f4715638b6d/distributed/profile.py#L401-L427

**Comment by jakirkham** [comment]
Would it make sense to raise an issue with Bokeh on the first point?

**Comment by mrocklin** [comment]
cc @jsignell

**Comment by jsignell** [comment]
It looks like this has been [brought up before on bokeh](https://github.com/bokeh/bokeh/issues/2673) and I mentioned there that it's still an issue. Maybe we could try to shorten the paths on the dask side in the meantime.

**Comment by jsignell** [comment]
The bokeh PR was merged so this *should* just go away once there is a bokeh release. Not sure if this issue should close in the meantime or wait.

**Comment by mrocklin** [comment]
Woo!  I'm excited to see this fixed.  

Closing.
