### ISSUE TITLE
Remove object from class hierarchy

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3428]
In many cases in the codebase we inherit from `object` like this:

```python
class Foo(object):
    ...
```

This used to be important in Python 2, but we no longer support that.  It might make sense to remove these for now and change code like this to the following:

```python
class Foo:
    ...
```

**Comment by jrbourbeau** [comment]
+1

**Comment by andersy005** [comment]
@mrocklin & @jrbourbeau thank you for the triaging of issues! It makes getting one's feet wet with the code base easy and straightforward :)
