### ISSUE TITLE
test_remote_access fails when running distributed test suite on github-actions

### ISSUE THREAD

**Issue by pierreglaser** [dask/distributed#3439]
(Again) in the process of setting up downstream projects builds for `cloudpickle` (on which `distributed` depends, see cloudpipe/cloudpickle#324), we recently merged #3418 in `distributed` -- because of this fix though, `test_remote_access` fails when trying to connect to the `Scheduler` with `Errno 22: Invalid Argument`.  It is very much linked to #3418 as this test passes before this change.

Debugging is tediuous as I cannot reproduce it locally, but I am happy to help if you have any clue. I currently skip this test when testing `distributed` on `cloudpickle`.

cc @jakirkham

**Comment by pierreglaser** [comment]
It's unclear whether `github` actions supports IPv6, see [this thread](https://github.community/t5/GitHub-Pages/Cannot-reach-any-github-io-page-via-IPv6/td-p/4021). I'd appreciate if somebody with more networking experience could weigh in, but otherwise it's ok to close this.

**Comment by mrocklin** [comment]
Thank you for following up with this issue @pierreglaser .  I apologize for the delay in response.  

I don't personally have much to add here unfortunately.

**Comment by pierreglaser** [comment]
Closing since it's far from critical.
