### ISSUE TITLE
Distributed processes not finding modules

### ISSUE THREAD

**Issue by philastrophist** [dask/distributed#344]
I have a cluster of PCs on the same network and reading from the same mounted python directory. 

I have a layout of code like this:
```
Project\
    package\
        data\
        __init__.py
        fitting.py
        code2.py
        etc...
output\
script.py
```

The workers are started in the same mounted directory as the project above. However, when I run `script.py`, the worker spews out a load of unicode nonsense ,then the traceback below and then the worker apparently crashes. Apparently the module isn't there

```
Traceback (most recent call last):
  File "E:/Dropbox/Project/script.py", line 14, in <module>
    fitter.save_results('output')
  File "E:\Dropbox\Project\Package\fitting.py", line 410, in save_results
    r = future.result()
  File "C:\Anaconda\lib\site-packages\distributed\executor.py", line 96, in result
    six.reraise(*result)
  File "C:\Anaconda\lib\site-packages\distributed\core.py", line 68, in loads
    return pickle.loads(x)
ImportError: No module named package.fitting
```

**`script.py`:**
```
from distributed import Executor
from package import fitting
executor = Executor('127.0.0.1:8786')
T = prepare_data()  # pandas dataframe
fitter = fitting.Fitter()  # my fitting object
fitter.fit_mulitple(T, executor)  # make futures in object
fitter.save_results()  # save to disk on local machine
```

**`fitting.py`:**
```
class Fitter(object):
    ....

    def fit_multiple(data_frame, executor):
        self.futures = [executor.submit(self.fit, series, append=False) for _, series in data_frame.iterrows()]  # submit the `fit` function for each row (`fit` is pure when append=False but requires other modules in the package)
        
    def save_results():
        return [saving_function(f.result()) for f in self.futures]  # generic save to hdf5 
```

**Comment by mrocklin** [comment]
Your workers don't seem to be able to find the `package.fitting` package.  Can you verify that a normal Python session started in the same place is able to find that package?  Perhaps you can install it or put it on the `PYTHONPATH` to help your workers out?

The workers are just Python processes.  They aren't doing anything special with paths or your software environment.  It's mostly up to you to ensure that all of your workers have the same software environment.

How are you setting up your workers?  If it is with `ssh` then you should beware that sometimes actions in `.bashrc` or wherever you set up your user environment sometimes don't persist to ssh sessions.

**Comment by philastrophist** [comment]
Ok I've installed it now and it appears that the workers can find it but error messages like:
```
Exception AttributeError: "'NoneType' object has no attribute 'debug'" in <bound method Future.__del__ of <Future: status: finished, type: GreybodyFit, key: fit-e0ea6b7b34dde76ea3b5ec2433798d2d>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'debug'" in <bound method Future.__del__ of <Future: status: finished, type: GreybodyFit, key: fit-1d7455dc974b5faf585d70613ffbfe48>> ignored
```
why does this happen?
thanks

**Comment by mrocklin** [comment]
Can you give more context about this error?  Is it just a warning showing up or is it stopping you from doing computations?  If it is stopping you from doing computations can you say a bit about the computations that you're doing or perhaps provide a minimally failing example?

**Comment by mrocklin** [comment]
Closing soon if no response

**Comment by rahatzamancse** [comment]
I am having the same issue, and I have run dask-scheduler and dask-workers in local machine to test. From the same directory, if the program is launched, it goes smoothly. But ask workers do not seem to find the module of another python file in the same directory.

**Comment by omarsumadi** [comment]
@rahatzamancse @mrocklin Same for me - if the module is in another python file anywhere, it doesn't find it.

This requires quite a bit of restructuring - is there a way to say 'Don't load imports from outside of the function call'?

Thanks,
Omar

**Comment by atul161** [comment]
Is there any update on this issue?

**Comment by damon-chem-e** [comment]
See MRocklin comment on stackexchange [here](https://stackoverflow.com/a/39994128/7965821). Use [`Client.upload_file`](http://distributed.readthedocs.io/en/latest/api.html#distributed.client.Client.upload_file)
