### ISSUE TITLE
TypeError: add_client() got an unexpected keyword argument 'versions'

### ISSUE THREAD

**Issue by FredLiFromMS** [dask/distributed#3449]
I am getting this error in the log when I try to create a client instance in jupyter notebook. 

Traceback (most recent call last):
  File "/azureml-envs/azureml_920764e50b04f05d9c76f8eea2f0bb7b/lib/python3.6/site-packages/distributed/core.py", line 399, in handle_comm
    result = handler(comm, **msg)
TypeError: add_client() got an unexpected keyword argument 'versions'

and here is the stack trace: 
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    725         for ext in extensions:
    726             ext(self)
--> 727 
    728         self.start(timeout=timeout)
    729         Client._instances.add(self)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/client.py in start(self, **kwargs)
    890         if self.asynchronous:
    891             self._started = asyncio.ensure_future(self._start(**kwargs))
--> 892         else:
    893             sync(self.loop, self._start, **kwargs)
    894 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     Several loop runners can associate safely to the same IO loop.
    344 
--> 345     Parameters
    346     ----------
    347     loop: IOLoop (optional)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/utils.py in f()
    327     if callback_timeout is not None:
    328         if not e.wait(callback_timeout):
--> 329             raise gen.TimeoutError("timed out after %s s." % (callback_timeout,))
    330     else:
    331         while not e.is_set():

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
    983         self.scheduler_comm = None
    984 
--> 985         try:
    986             await self._ensure_connected(timeout=timeout)
    987         except OSError:

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/distributed/client.py in _ensure_connected(self, timeout)
   1065             msg = await comm.read()
   1066         assert len(msg) == 1
-> 1067         assert msg[0]["op"] == "stream-start"
   1068 
   1069         bcomm = BatchedSend(interval="10ms", loop=self.loop)

TimeoutError: Timeout

**Comment by mrocklin** [comment]
You likely have mismatched versions between your various Dask processes.
You might want to make sure that the versions of the dask and distributed
packages are the same everywhere.

**Comment by FredLiFromMS** [comment]
Thanks

**Comment by TomAugspurger** [comment]
@FredLiFromMS did ensuring you have matching versions fix things?

**Comment by FredLiFromMS** [comment]
This happened after upgrading packages in notebook.  I tried to install latest "dask" and "distributed" package, but it didn't work. 

Then I created a new notebook without "pip install " latest packages. Then the issue was gone.

**Comment by TomAugspurger** [comment]
Good to hear, thanks.

**Comment by rokroskar** [comment]
I actually get the same error after installing `dask-gateway` following the basic helm install and installing the corresponding python package in a jupyter notebook. They are all using `dask-gateway==0.6.1`.

**Comment by rokroskar** [comment]
Downgrading `dask` and `distributed` to `2.8.1` fixes the issue.

**Comment by TomAugspurger** [comment]
Looks like that's being discussed at https://github.com/dask/dask-gateway/issues/213. Let's keep the gateway conversation there.
