### ISSUE TITLE
Make Adaptive keyword args configurable?

### ISSUE THREAD

**Issue by willirath** [dask/distributed#3452]
Currently, `kwargs` of `deploy.Adaptive`
https://github.com/dask/distributed/blob/105d040fb9cabfa3581dcdce73165c77cb22de9a/distributed/deploy/adaptive.py#L12 do not seem to be configurable. As tuning these parameters is depending on the use case, the platform, etc. (see https://github.com/pangeo-data/pangeo/issues/757), there should be a way of changing these default values via dask config.

**Comment by mrocklin** [comment]
Adding these to the configuration makes sense to me

**Comment by willirath** [comment]
cc: @kathoef

**Comment by TomAugspurger** [comment]
This was fixed by https://github.com/dask/distributed/pull/3509 I think.
