### ISSUE TITLE
Scheduler sometimes sends duplicated messages in report

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#3454]
When the scheduler sends update messages in its `report` method, it can sometimes duplicate the message, sending it multiple times to the same remote comm.

The relevant code is here: https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L2433

If `client` is not `None` and the client is interested in the given task, the method will send him the message twice. This happens with a scatter for example (the `report` call is in `update_data` through `client_desires_keys`):

```python
client = Client("tcp://localhost:8786")
f = client.scatter([1])
```
Here the client receives `key-in-memory` with the given key twice. If there were 1000 scattered objects, it would receive 2000 key-in-memory notifications.

I created a simple commit which fixes this. It uses sets, if you don't like it, it can be also solved differently, for example checking in the final loop if the given comm isn't the same as the passed client's comm.
https://github.com/Kobzol/distributed/commit/093497f29fa9137557995f0ddcc65e0a6d4dcb84

**Comment by mrocklin** [comment]
My apologies for the delay @Kobzol (I've been somewhat occupied this month) 

This change makes sense to me.  Thank you for highlighting it and proposing a fix.  I agree that your fix looks sensible.  If you want to submit a PR I would be very happy to merge it.
