### ISSUE TITLE
How to dynamically scale a LocalCluster with varying resources per worker?

### ISSUE THREAD

**Issue by acowlikeobject** [dask/distributed#3457]
[Per the docs](https://distributed.dask.org/en/latest/local-cluster.html), we can scale the cluster using `cluster.add_worker`.

However, on `dask` `2.10.1`, I get an `AttributeError`:
```
from dask.distributed import LocalCluster, Client

cluster = LocalCluster()
client = Client(cluster)
worker = cluster.add_worker()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-809c0e84bc97> in <module>
      3 cluster = LocalCluster()
      4 client = Client(cluster)
----> 5 worker = cluster.add_worker()

AttributeError: 'LocalCluster' object has no attribute 'add_worker'
```

Are the docs out of date?   Later on the same page, there's a snippet to scale up using `cluster.scale(3)`.  There's also a `cluster.start_worker` function, but that appears to be deprecated in favor of `cluster.scale`. 

However, I'd like to add workers with a heterogeneous mix of resources (e.g., some workers with default resources, and one with a `GPU` resource).

Is it possible to scale up iteratively, each time providing a different resources dict to achieve this?

**Comment by mrocklin** [comment]
Thanks for the issue @acowlikeobject .  Yes, those docs are old.  I've removed them in https://github.com/dask/distributed/pull/3458 and redirected to the newer deployment docs here: https://docs.dask.org/en/latest/setup.html

The `LocalCluster` class assumes some homogeneity among your workers.  If you're looking for something less homogenous then you might want to try the `dask.distributed.SpecCluster` class, which is much more flexible (although also somewhat more complex).  The docstring for that class should be fairly informative.

**Comment by acowlikeobject** [comment]
Thanks for the quick response, @mrocklin !

`dask.distributed.SpecCluster` looks promising.  But I was just going through the code and wondering: wouldn't modifying `cluster.new_spec['options']['resources']` also achieve this?

E.g.:
```
import time

from dask.distributed import LocalCluster

# Spin up a LocalCluster with 4 workers.
n_workers = 4
cluster = LocalCluster(n_workers=n_workers)

# The 5th worker has a gpu resource.
n_workers += 1
cluster.new_spec['options'] = {'resources': {'gpu': 1}}

# Scale up to 5 workers.
cluster.scale(n_workers)

# Assert that first 4 workers don't have any resources.
for n in range(n_workers - 1):
    assert cluster.workers[n].process.worker_kwargs['resources'] is None

# And the 5th has the gpu resource.
time.sleep(1)
assert cluster.workers[n_workers - 1].process.worker_kwargs['resources'] == {'gpu': 1}
```

**Comment by mrocklin** [comment]
I imagine that something like that might work.  It seems a little more
error-prone to me than using SpecCluster directly, but if it works for you
then go for it :)

**Comment by acowlikeobject** [comment]
Fair enough.  It's not harder to use the arguments for `SpecCluster`, and probably more robust.

Will close this.  Thanks.
