### ISSUE TITLE
Error removing task group

### ISSUE THREAD

**Issue by bnaul** [dask/distributed#3465]
Believe this is related to #3322: running on master since pulling in that PR, I'm suddenly seeing a lot of these errors:
```
distributed.scheduler - ERROR - Error transitioning '_plot_hourly_scatterplots-e923799215afb4e224b3d5672cdf8be3' from 'processing' to 'memory'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/scheduler.py", line 4658, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
distributed.core - ERROR - list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/usr/local/lib/python3.7/site-packages/distributed/scheduler.py", line 2600, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/usr/local/lib/python3.7/site-packages/distributed/scheduler.py", line 2015, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/distributed/scheduler.py", line 4658, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
```
Played around a bit with trying to simply reproduce but no luck so far; some possible culprits are:
- many of these tasks are stolen
- some workers could be starting/stopping during processing
- I believe the tasks that are failing are being `fire_and_forget`ten 

@jrbourbeau anything stand out to you...? if it's possible for `ts.group.states` and `ts.prefix.groups` to be inconsistent then maybe there should be another `if` or `try/pass` here regardless?

**Comment by jrbourbeau** [comment]
Thanks for reporting this @bnaul! Your usage of the dev version of `dask` and `distributed` has been valuable to the project on several occasions

The failure definitely looks related to #3322. After a quick glance at some relevant portions of the codebase, I don't see where `ts.group.states` and `ts.prefix.groups` would get out of sync. I'll take a deeper look tomorrow. If you're able to provide a reproducer, that would be awesome

**Comment by bnaul** [comment]
Glad to hear it 🙂

I haven't been able to reproduce so far but I do suspect stealing is related; it does seem like https://github.com/dask/distributed/pull/3322/files#diff-6a3108098afcddf88b38652ae1e383b5R4611-R4612 would definitely fail in that way if it were run twice, and couldn't that be a possible race condition involved with stealing? For now I'm trying to work around this with
```
                 if not any(tg.states.get(s) for s in ALL_TASK_STATES):
-                    ts.prefix.groups.remove(tg)
-                    del self.task_groups[tg.name]
+                    try:
+                        ts.prefix.groups.remove(tg)
+                        del self.task_groups[tg.name]
+                    except (KeyError, ValueError):
+                        pass
```
any reason the above might be undesirable?

**Comment by bnaul** [comment]
Just checking in, does anyone have any thoughts about this bug? I am pretty confident it's going to be a problem for people once #3322 is released so it seems important to fix it before then; not affecting me personally bc I am already using the workaround I posted above but it would be nice to move back off our fork 🙂 

cc @jrbourbeau @TomAugspurger

**Comment by jrbourbeau** [comment]
Thanks for following up @bnaul! Do you know why work stealing would cause that section of code to run multiple times? A `try`/`except` catch seems reasonable if it's difficult to avoid, e.g. a race condition with work stealing, but I just want to make sure we're fixing the problem if possible and not just working around a side effect

**Comment by bnaul** [comment]
Unfortunately all I really have are guesses; work stealing is the only source of a race condition that comes to mind...if it helps I could rerun my workflow w/o work stealing and see if that avoids the issue, but I don't know that I'll be able to come up with a proper reproducible example since the only times I've seen it have been pretty big jobs.

**Comment by jrbourbeau** [comment]
Rerunning without work stealing would be great if you don't mind

**Comment by bnaul** [comment]
@jrbourbeau managed to isolate the issue! it is related to fire-and-forget + work stealing:
```
import distributed
from distributed.utils_test import slowadd
c = distributed.Client()
x = c.scatter(list(range(100)), workers=list(c.scheduler_info()['workers'].keys())[0])
# same error does not appear w/o fire-and-forget
distributed.fire_and_forget([c.submit(slowadd, i, x[i]) for i in range(len(x))])
```
this is happening for me in the new 2.11.0; the workaround I posted above fixes the issue, not sure if there's a better way of handling this though.

**Comment by bnaul** [comment]
Just checking in, does the example above reproduce the issue for others? Happy to PR our workaround but I figure there's probably a better way to properly avoid this that @jrbourbeau or @mrocklin could come up with 🙂

**Comment by mrocklin** [comment]
As a disclaimer, most of the people who could handle this issue are
currently as the Dask summit (we're missing you @bnaul) so it may be that
nothing happens here for a few days.
