### ISSUE TITLE
Per key resources do not seem to work

### ISSUE THREAD

**Issue by chrisroat** [dask/distributed#3481]
I believe I've found a couple key problems (pun intended!) with collection-based resources.

To illustrate, note that he following code completes successfully, though it should be resource constrained.
```
import dask
from dask import core
import distributed
import dask.array as da

x = da.zeros(4, chunks=2)
y = x.map_blocks(lambda e: 2*e)
z = y.map_blocks(lambda e: 2*e)

client = distributed.Client(resources={'ABC':1})
dask.compute(z, resources={tuple(y.__dask_keys__()): {'ABC': 2}})
```

I believe there is one problem, and one secondary problem.  I may not fully understand the system, so there may be other explanations than mine.

The first issue I see is the use of the `utils.tokey` with `utils._expand_key` in [expanding resources](https://github.com/dask/distributed/blob/04de4b2adc1f0c94ab86e9aa46a4c67382a7eaea/distributed/client.py#L3805).  This turns the tuple keys into strings, which then presumably do not match real task ids, which are tuples, at some later point in the scheduling algorithm.
 
```
distributed.Client._expand_resources(distributed.Client, {(('key1', 0),): {'FOO': 1}}, [('key', 0), ('key', 1)])
```
```
{"('key1', 0)": {'FOO': 1}}
```

This does not happen with global constraints, where each key remains a tuple.
```
distributed.Client._expand_resources(distributed.Client, {'FOO': 1}, [('key', 0), ('key', 1)])
```
```
{('key', 0): {'FOO': 1}, ('key', 1): {'FOO': 1}}
```

The second issue is that lists don't hash, and so complex keys need to be handle carefully.  The [instructions](https://distributed.dask.org/en/latest/resources.html#resources-with-collections) don't work for multi-dimensional collections with nested lists for keys:

```
import dask.array as da
x2 = da.zeros((4,4), chunks=2)
resources = {tuple(x2.__dask_keys__()): {'ABC': 1}}
```
```
TypeError: unhashable type: 'list'
```

I found an existing helper function that helps, albeit suffering from the primary string-key problem above when fed in as a resources parameter.

```
import dask.array as da
from dask import core

x2 = da.zeros((2,2), chunks=2)
resources = {tuple(core.flatten(x2.__dask_keys__())): {'ABC': 1}} # Works!
```

I have proposed #3480 to fix the docs.  The fix for the string-keys is a bit more subtle, since it's in core code that other code relies on.  I'm happy to take some direction to help make a fix, or perhaps rethink things a bit.

**Comment by CMCDragonkai** [comment]
This may be related: https://github.com/dask/distributed/issues/3445

I'm confused how to make just 1 component of a dictionary that is a dataframe to run with a resource constraint.

**Comment by chrisroat** [comment]
Actually, this is just due to the graph optimizing away the keys for y.  In this case, one must add `optimize_graph=False` to `compute`.
