### ISSUE TITLE
distributed incompatible with msgpack

### ISSUE THREAD

**Issue by xiaozhongtian** [dask/distributed#3501]
Hello team of dask,
We have updated recently the new version ``dask/distributed``, with ``msgpack>0.6.0 (updated yesterday on 1.0.0)`` a dependency of this package.
We find that an incompability that the dask``Client`` can't ``upload_file`` to the cluster.

`error: tuple is not allowed for map key ` when `upload_file("*.zip")`

regard.

**Comment by TomAugspurger** [comment]
Fixed in https://github.com/dask/distributed/pull/3494

**Comment by quasiben** [comment]
I believe we fixed the msgpack issue yesterday afternoon.  Can you try
pulling from master and retrying?
