### ISSUE TITLE
Following dask-tutorial and local cluster errors on compute

### ISSUE THREAD

**Issue by Austin-Crabtree** [dask/distributed#3504]
# Problem:
I am following the dask-tutorial provided by dask and I am experience and error on computing the value of z with in the first few cells of the notebook, when using dask.distributed.Client. Though when using single-machine scheduler there is no error. 

**Error:**  ValueError: tuple is not allowed for map key

### Environment:
Linux: 5.3.0-7629-generic 
miniconda3: conda 4.8.2
python: 3.7.6 packaged by conda-forge
conda env: created from tutorial environment.yml file

I ran this on jupyter lab

### Code from 01_dask.delayed.ipynb: 
```
from dask.distributed import Client

client = Client(n_workers=4)

from time import sleep

def inc(x):
    sleep(1)
    return x + 1

def add(x, y):
    sleep(1)
    return x + y

from dask import delayed

%%time
# This runs immediately, all it does is build a graph

x = delayed(inc)(1)
y = delayed(inc)(2)
z = delayed(add)(x, y)

%%time
# This actually runs our computation using a local process pool

z.compute()
```
This is where I receive the error. If I don't setup a local cluster I am able to compute and get the result of z.

**Comment by quasiben** [comment]
@Austin-Crabtree i'm a little confused about what the error is but `Client` will create a `LocalCluster` when no scheduler is defined.  This is the case with the materials in dask tutorial.  If this not what you are asking can you provide a bit more detail on what/where the error is?

**Comment by Austin-Crabtree** [comment]
Yes sorry I was not more clear. I am aware that client will `Client` will create a `LocalCluster`. The error is occuring when using a `LocalCluster` trying to run the above code. The result is 

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/crabbyinatree/miniconda3/envs/dask-tutorial/lib/python3.7/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:34987'], add-1ab7d9ca-327b-43ce-9518-5843a27193db
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'add-1ab7d9ca-327b-43ce-9518-5843a27193db': ('tcp://127.0.0.1:34987',)}
```
Sorry I didn't have the notebook up earlier and so didn't get the rest of the error in the issue.

**Comment by jrbourbeau** [comment]
`ValueError: tuple is not allowed for map key` is related to the recent msgpack 1.0 release. @Austin-Crabtree what version of dask are you using? If not using 2.11.0 of dask and distributed, could you try upgrading?

**Comment by Austin-Crabtree** [comment]
Yes that fixed it. I also checked the environments.yml for the tutorial and its is specifying 2.8.1 for the dask version to install for the conda environment, so that may need to be updated to avoid this issue in the future. But thank you @jrbourbeau  and @quasiben for your help.

**Comment by jrbourbeau** [comment]
Thanks for reporting back @Austin-Crabtree! Agreed the tutorial should be updated

**Comment by jrbourbeau** [comment]
Closing this issue in favor of https://github.com/dask/dask-tutorial/issues/162
