### ISSUE TITLE
Accelerated networking options for the scheduler

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3506]
With UCX-Py and additions to the comms code in dask, we've enable workers to communicate with accelerated hardware.  This has largely been done by passing flags/env-vars with [dask-cuda](https://github.com/rapidsai/dask-cuda/blob/474108a3b597d27339a019a200bd824f6f85ef50/dask_cuda/dask_cuda_worker.py#L178-L182) to the worker setup.

For example, one can start a dask-cuda-worker with following flags:

> dask-cuda-worker ucx://scheduler --enable-nvlink --enable-infiniband

I don't think any such options exist for the scheduler today.  While the scheduler should largely only be touching host memory and serialized strings (task graph), nothing restricts the user from inserting GPU objects in the task graph.  Furthermore, transport over enabled IB should be faster than non-enabled IB

By allowing such options directly in the distributed code base other cluster managers (Dask-K8s, Dask-SSH, Dask-jobqueue) can easily expose the options as well.

**Comment by mrocklin** [comment]
Ideally we can get by with options like `--protocol ucx://` and configuration settings for UCX itself (which is presumably separate).

To me, adding UCX specific keywords into the dask-scheduler CLI is likely out of scope.

**Comment by pentschev** [comment]
> Ideally we can get by with options like --protocol ucx:// and configuration settings for UCX itself (which is presumably separate).

Not really, if you're creating the scheduler from scratch, it's up to you to define what kind of transports you want enabled, otherwise you'll just use UCX's defaults and have no control over it.

**Comment by mrocklin** [comment]
I get that, and I agree that there needs to be some way to configure the use of UCX.  However I am vetoing putting UCX-specific configuration options into Dask's top level CLI API.  We can't put every dependency's options into the CLI.  It would become thousands of options long.  We'll need to find some way to make these things configurable without putting all of them into the core Dask interface.

I think that maybe it makes sense to have a ucx config file?

```yaml
ucx:
  tls: all
  net-devices:...
```

If memory serves we had this conversation when @pentschev first added `--enable-nvlink` to the dask-cuda-worker API.

**Comment by quasiben** [comment]
Relying on the the config seems like a good option.  I think the cluster managers could expose these options (should they want to) with reasonable defaults.  They should be able to do something like the following before the scheduler is created, right ?

something like:

```python
dask.config.set('ucx.tls': '...')
dask.config.set('ucx.net-devices': '...')
...
```

Then we could handle these options appropriately in the source.  Thoughts ?

**Comment by mrocklin** [comment]
We typically encode default values into the config yaml files living in the
various repositories.  Then yes, users or other automated systems could
change those configuration values with Python code as you have above, or
through other means.  I think that this is what you're saying, but I'm not
entirely certain, so please push back if I'm misunderstanding.

> Then we could handle these options appropriately in the source. Thoughts ?

Yes, I think that having `dask.config.get("ucx....") calls in the
distributed/comm/ucx.py file would make sense.  We already do a bit of
this, and pass those values to ucp.init.

**Comment by quasiben** [comment]
I think we have two options now for what I/we want accomplish.  Perhaps this would have been better stated at beginning.  We are writing CLI commands like the following:

> UCX_NET_DEVICES=mlx5_0:1 UCX_TLS=rc,tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm dask-scheduler --protocol ucx

It's very very easy to mess up these env vars and we want to establish better patterns for users and for ourselves.   We could present higher level config options as we do with dask-cuda-worker. This might look like the following:

```yaml
ucx:
  nvlink: true/false
  infiniband: true/false
  tcp_over_ucx: true/false
```

Then map these flags to appropriate env vars as we do in [dask-cuda](https://github.com/rapidsai/dask-cuda/blob/96a43b7483b9bed941add352ed46de42fa255745/dask_cuda/initialize.py#L57-L72)

Alternatively, dask-cuda could build a dask-cuda-scheduler with similar flags to dask-cuda-worker. This might be preferable short term while we better understand how UCX needs to start for the scheduler.  Maybe this is also the long term solution as UCX specific CLI commands would not be appropriate in dask main line.

**Comment by mrocklin** [comment]
> Alternatively, dask-cuda could build a dask-cuda-scheduler with similar flags to dask-cuda-worker

Doing something like this makes sense short term.  However I would like to see us move away from needing these things in the future.  It makes composing the dask-cuda work with other projects harder.  For example if you wanted to use this with dask-jobqueue or some other deployment solution then there is now more integration work for other people to do.  This seems like a short term win, or a local win, rather than a great long-term solution.  My sense is that configuration files are the right way to handle this sort of thing long-term.  They're easy to compose.

**Comment by quasiben** [comment]
Agreed.  My preference is not to build dask-cuda-scheduler but I also want ease of use.  This discussion is helpful in finding the balance between ease and and an overloaded CLI.
