### ISSUE TITLE
RMM Pool for Scheduler

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3507]
Related to #3506 

While the scheduler should largely only be touching host memory and serialized strings (task graph), nothing restricts the user from inserting GPU objects in the task graph (ref: https://github.com/dask/distributed/issues/3334).  If the user does insert GPU objects into the task graph we may want to consider allowing for GPU memory management in the scheduler as well

**Comment by mrocklin** [comment]
The scheduler never deserializes user objects, so the only code that will touch these things is UCX-Py.  Perhaps this could be handled in UCX-Py configuration?

**Comment by pentschev** [comment]
> The scheduler never deserializes user objects, so the only code that will touch these things is UCX-Py. Perhaps this could be handled in UCX-Py configuration?

If we handled this in UCX-Py configuration this would mean that all processes using it would have the same configuration (scheduler, workers and client). That solution would not be flexible enough for various uses, such as when we know there may be "some" memory allocated on the scheduler, but in much smaller size than in workers.

**Comment by mrocklin** [comment]
> If we handled this in UCX-Py configuration this would mean that all processes using it would have the same configuration

What is the configuration here?  My understanding was that it was just calling `rmm.enable()` or something similar when we start up UCX.  I think that turning this off or on by some environment variable or YAML config file seems nice?

I may not understand the situation here though.  Is there a proposal?

I guess what I'm saying is that I'm against any sort of `--use-rmm` flag in dask-scheduler .  That may not be what folks are suggesting though.

I would be totally fine with a config value in YAML though.  Those are easy to keep organized and separate.  I might suggest something like:

```yaml
ucx:
  rmm: true
```

**Comment by quasiben** [comment]
@mrocklin thank. you for the responses.  First, I want to clear something up.  While the scheduler never deserializes, it may be responsible for allocating memory.  For example:

```python
def noop(part, sr):
    return part
res = ddf.map_partitions(noop, sr=cudf.Series(), ...).compute()
```

In the above, the `cudf.Series` will be serialized and passed from the client, to the scheduler, then to a worker.  When transported to the scheduler, the scheduler will allocate accordingly, right ?   It will not be a fully constituted object but will still be occupying some memory in the scheduler process.  (I know we have discussed this before and I'm sorry for my confusion here)

A config value here would probably be the rmm pool size rather than enable/disable.  I would propose keeping rmm and ucx as separate configs:


```yaml
ucx:
  tls:...

rmm:
  pool-size: '2G'
  managed-memory: False
```

**Comment by mrocklin** [comment]
Yes, we'll call `Comm.read`, which will produce frames (probably
rmm.DeviceBuffer objects?).  Having an `rmm` config family makes sense to
me.

**Comment by jakirkham** [comment]
I wonder if short term we can just do something like call [`Client.run_on_scheduler`]( https://distributed.dask.org/en/latest/api.html#distributed.Client.run_on_scheduler ) to setup the RMM pool on the scheduler. Admittedly this is a little hacky, but it is functional and no worse than what we did to setup the RMM pool on workers for some time.

A less hacky solution akin to what Peter did for the RMM pool on workers recently might be to create a [Scheduler Plugin]( https://distributed.dask.org/en/latest/plugins.html#distributed.diagnostics.plugin.SchedulerPlugin ) that initializes the RMM pool whenever the scheduler starts or restarts.

My guess is these things can live in dask-cuda, but I could be wrong about this. What else are we missing? 🙂

**Comment by quasiben** [comment]
We have regularly been doing the following on the scheduler:

```
DASK_RMM__POOL_SIZE=1GB \
dask-scheduler \
    --scheduler-file $LOCAL_DIRECTORY/dask-scheduler.json \
    --protocol ucx --interface ib0 > $MOUNTED_HOME/sched-out.txt 2>&1 &
```

A complete example of RMM and UCX:
```
DASK_UCX__CUDA_COPY=True \
DASK_UCX__TCP=True \
DASK_UCX__NVLINK=True \
DASK_UCX__INFINIBAND=True \
DASK_UCX__RDMACM=True \
UCX_NET_DEVICES=mlx5_0:1 \
DASK_RMM__POOL_SIZE=1GB \
dask-scheduler \
    --scheduler-file $LOCAL_DIRECTORY/dask-scheduler.json \
    --protocol ucx --interface ib0 > $MOUNTED_HOME/sched-out.txt 2>&1 &

```
