### ISSUE TITLE
dask-submit

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#351]
Often times, the Client cannot be run on the same machine as the Scheduler; it may also not be possible to replicate the same environment as scheduler machine especially on EC2 e.g. EC2 machines may have access to S3 buckets while the executor machine may not. In the event, the client machine cannot replicate the environments, being able to ship a script to the client may be super helpful.

Akin to `spark-submit`, the Client lives with Scheduler node and can accept a python script over ssh/http etc.

**Comment by hussainsultan** [comment]
looking at `distributed.deploy`, it appears that much of the ssh machinery is already there. I am happy to take this on if this makes sense.

**Comment by mrocklin** [comment]
How would you design this?  Is this adding a service to the scheduler to create an on-demand client locally?  Is this running a client alongside the scheduler all the time that accepts scripts, runs them, and then returns results?

**Comment by hussainsultan** [comment]
I think minimal step would be to run the client on on-demand basis on the same machine as scheduler when a user submits a job. Much of this code could live outside of scheduler and user will be in-charge of figuring out how outputs are handled e.g. output to s3 for persistence, etc. 

More sophisticated solution could be running an IPython kernel alongside scheduler that can run and return results in an interactive manner - this maybe more complex and i am not sure if we need this yet.

**Comment by mrocklin** [comment]
OK.  Those both sound like good ideas to me.

One solution would be to subclass distributed.core.Server to create a
RemoteClient(Server) object.  This is the same common subclass of Scheduler
and Worker.  We would then send the script over TCP using the same
communication machinery that everything else uses.  Tracking the code in
Worker.upload_file might be useful.

**Comment by hussainsultan** [comment]
ahh. interesting, that sounds pretty good. i will take this on in next couple of days.

**Comment by hussainsultan** [comment]
Closing!

**Comment by hussainsultan** [comment]
Sorry wrong issue. Reopening!

**Comment by mrocklin** [comment]
This seems to be resolved

**Comment by hussainsultan** [comment]
Thanks!
