### ISSUE TITLE
How to terminate worker and schedule gracefully in cmd

### ISSUE THREAD

**Issue by webzerg** [dask/distributed#3511]
I started the dask scheduler and dask worker manually with cmd following the examples below (https://distributed.dask.org/en/latest/worker.html), how can I terminate the scheduler and worker gracefully via cmd after executing the job? Thanks. 

$ dask-scheduler
Start scheduler at 127.0.0.1:8786

$ dask-worker 127.0.0.1:8786
Start worker at:               127.0.0.1:1234
Registered with scheduler at:  127.0.0.1:8786

**Comment by mrocklin** [comment]
Typically when people create these manually via the CLI they use a Keyboard
Interrupt (Ctrl-C) to stop them.

In more production use cases Dask is typically started with some other
system like Kubernetes or Yarn.

**Comment by quasiben** [comment]
I don't think there is anything else here so I am going to close.  @webzerg if you want to continue with the discussion please feel free to re-open
