### ISSUE TITLE
Downpin msgpack to 0.6.2 for dask 2.9

### ISSUE THREAD

**Issue by kondabathula** [dask/distributed#3520]
The new version of msgpack 1.0.0 is creating following errors 

`2020-02-26 13:19:44,102 INFO     Register tls://xx.x.xxx.xx:xxxxx (distributed.scheduler)
2020-02-26 13:19:44,105 INFO     Starting worker compute stream, tls:/xx.x.xxx.xx:xxxxx (distributed.scheduler)
2020-02-26 13:19:44,107 INFO     Starting established connection (distributed.core)
2020-02-26 13:19:44,138 CRITICAL Failed to deserialize (distributed.protocol.core)
Traceback (most recent call last):
  File "/mnt/mesos/sandbox/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 106, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key`

I guess the issue can be reproduced with the following code.

`
import dask, os

from dask.distributed import Client
​

endpoint = os.environ["ENDPOINT_DISTRIBUTED"]
​

def wrap_test(n):
    return n
​

with Client(address=endpoint):
    delayed = dask.delayed(wrap_test)(2)
    result = delayed.compute()
`

dask, distributed versions 2.9.0

**Comment by kondabathula** [comment]
This issue is not in the case of Local cluster.

**Comment by jrbourbeau** [comment]
Could you try with the latest release of `distributed`? It should include compatibility fixes for `msgpack` 1.0

**Comment by kondabathula** [comment]
yes, for dask 2.11.0, it is good... I just raised it so that ppl like me still using 2.9 could still survive.. :)

**Comment by jrbourbeau** [comment]
I see, thank you for the additional context! There was a discussion about patching the existing `distributed` conda-forge packages to require `msgpack<1` for older releases (xref https://github.com/conda-forge/distributed-feedstock/pull/114#issuecomment-588286765). I don't know if it's possible to do something similar for older packages on PyPI. 

Are there any additional changes that should be made in this repo, or is it okay to close this issue?

**Comment by jrbourbeau** [comment]
Older versions of `distributed` on conda-forge should now set a constraint on the msgpack version used (xref https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/32). I don't think there's an equivalent patch that can be made on PyPI -- though I would be happy to hear if there is. Closing this issue. Thanks again for raising this point @kondabathula!

**Comment by kondabathula** [comment]
Thank you @jrbourbeau
