### ISSUE TITLE
Dashboard not rendered properly when using dask-labextension

### ISSUE THREAD

**Issue by andersy005** [dask/distributed#3522]
I've been trying out the new additions to the dashboard (which are awesome :)).

- One of the issues I am running into has to do with `/individual-bandwidth-types` frame. This frame is not being rendered properly when using the dask-labextension. 

<img width="1666" alt="Screen Shot 2020-02-26 at 1 50 18 PM" src="https://user-images.githubusercontent.com/13301940/75386499-ffecaf80-589e-11ea-8b83-3a71028f7991.png">

However, everything works just fine when I access the application from the dashboard url. 

<img width="1679" alt="Screen Shot 2020-02-26 at 1 55 39 PM" src="https://user-images.githubusercontent.com/13301940/75386917-b781c180-589f-11ea-9bc1-8bcfcd7401ad.png">

- Another issue I ran into is that cluster map frame is missing from the dashboard when the client is instantiated inside a notebook

With @jacobtomlinson's help, I also learned that everything works fine when the client/cluster is instantiated from the dask-labextension's widget:

<img width="376" alt="Screen Shot 2020-02-26 at 2 15 09 PM" src="https://user-images.githubusercontent.com/13301940/75388547-6cb57900-58a2-11ea-8319-85556ff5aa54.png">

**Comment by andersy005** [comment]
I forgot to add that I am using Brave browser.

**Comment by mrocklin** [comment]
cc @jsignell in case she has time to look at this

**Comment by quasiben** [comment]
@andersy005 there have been some updates to dask-labextension ?  Would you be willing to try again ?  If you are still experiencing this issue can you also try another browser to help narrow the scope ?

**Comment by andersy005** [comment]
I can confirm that this appears to have been fixed. Thank you for the ping, @quasiben
