### ISSUE TITLE
dask-ec2 security group VPC error

### ISSUE THREAD

**Issue by ngcrawford** [dask/distributed#354]
I'm getting a Amazon VPC security error when I try to run `dask-ec2 up`. I followed the directions in http://distributed.readthedocs.io/en/latest/ec2.html exactly. If I run the `dask-ec2 up` a second time it successfully starts images, but the ssh step fails. I'm guessing this is an EC2 permissions problem... 

Thanks, 
Nick

```
MyMac$ dask-ec2 up --keyname aws_key_pair --keypair ~/.ssh/aws_key_pair.pem 
Launching nodes
DEBUG: Checking that keyname 'aws_key_pair' exists on EC2
DEBUG: Checking that security group 'dask-ec2-default' exists on EC2
DEBUG: Default security group 'dask-ec2-default' not found, creating it
DEBUG: Creating default (very open) security group 'dask-ec2-default'
DEBUG: Setting up default values for the 'dask-ec2-default' security group
Unexpected EC2 error: An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupEgress operation: Only Amazon VPC security groups may be used with this operation.
```

**Comment by mrocklin** [comment]
cc @danielfrg

**Comment by danielfrg** [comment]
Are you using EC2 Classic or VPC?

**Comment by ngcrawford** [comment]
EC2 Classic (I think). I made new login credentials this morning, but otherwise didn't change anything in my account. I played around with MrJob (https://pythonhosted.org/mrjob/) a few years ago, but since then haven't been using my AWS account.

**Comment by danielfrg** [comment]
Yeah, that makes sense you probably have EC2 classic. All my accounts have EC2 Classic disabled so I cannot test it that easy. If you can upgrade that would probably solve that issue. I'll take a look when I have a chance and see if there is a setting I can change to make it compatible with both.

**Comment by ngcrawford** [comment]
I created a default VPC security profile in my `us-east-1` region, but as far as I can tell `dask-ec2` continues to read the original EC2 classic default profile. Since that wasn't working I tried running everything in` us-west-1` which only has VPC available. I was able to make a keypair (etc), but I still get the ssh connection error.

```
MyMac$ dask-ec2 up --region-name us-west-1 --keyname aws_nor_cal --keypair ~/.ssh/aws_nor_cal.pem --ami ami-a7fdfee2
A file named cluster.yaml already exists, proceding will overwrite this file. Continue? [y/N]: y
Launching nodes
DEBUG: Checking that keyname 'aws_nor_cal' exists on EC2
DEBUG: Checking that security group 'dask-ec2-default' exists on EC2
DEBUG: Default security group 'dask-ec2-default' not found, creating it
DEBUG: Creating default (very open) security group 'dask-ec2-default'
DEBUG: Setting up default values for the 'dask-ec2-default' security group
DEBUG: Creating 4 instances on EC2
DEBUG: Tagging instance 'i-9561f5d0'
DEBUG: Tagging instance 'i-9761f5d2'
DEBUG: Tagging instance 'i-9661f5d3'
DEBUG: Tagging instance 'i-9061f5d5'
Checking SSH connection to nodes
DEBUG: Checking ssh connection for 52.53.255.114
DEBUG: Attempt 1/10 of function 'check_ssh' failed
DEBUG: Checking ssh connection for 52.53.255.114
DEBUG: Attempt 2/10 of function 'check_ssh' failed
DEBUG: Checking ssh connection for 52.53.255.114
```

**Comment by danielfrg** [comment]
Yes, unfortunately `dask-ec2` only uses whatever its the default for the AWS account even when you create a default VPC. There is an issue to track that here: https://github.com/dask/dask-ec2/issues/17

Since you changed region i think it should work. On this case the error I see is different. Those ssh errors are "expected" since the EC2 instance state is  `running` but SSH is not available immediately and there is no event from AWS to tell us that. So we have to poll and retry a couple of times. If you let that command run it should connect eventually and start the bootstrap process.

**Comment by ngcrawford** [comment]
Letting the script run longer fixed my issue. Thanks for you help Daniel.
