### ISSUE TITLE
Proposal to add __dask_attributes__

### ISSUE THREAD

**Issue by mmohrhard** [dask/distributed#3542]
G'day,

we'd like to see if there is any interest in dask adding a __dask_attributes__ property to collections. I'm filing this issue here as the use case is much more distributed centered than dask centered. The motivation behind this is that we have a number of features in our version of distributed that depend on having additional information available and our long term plan would be to upstream a few features if there is interest in the community. We use additional per task information for example for advanced scheduling, memory tracking, checkpointing, replications, progress tracking for long running tasks, ...

We have not completely decided yet how our __dask_attribute__ solution would look like. Currently we use a scheduler plugin and wrapping the functions in the low level task API with a decorator. The limitations of this aproach are that it is limited to using the low level task API and not to advanced features like dask array and that it requires an additional unpickling of all task functions on the scheduler.
Adding a new attribute to each task obviously comes with additional memory being used on the scheduler but we have a patch in the pipeline to fix a few "memory leaks" in distributed that should make this less of an issue.
The obvious open questions are how to represent and handle attributes that are only loosely specified and how to make the API user friendly.

Would such a feature be something the dask community would be interested in?

Cheers,
Markus

**Comment by mrocklin** [comment]
I'm glad to see that you've been finding Dask useful enough to extend it for custom needs.

To start this conversation, I think that it would make sense to begin with what those needs are.  It may be that people here can find some solutions that make more sense than `__dask_attributes__` or some similar extension of the collection protocol.  As you might imagine, we're pretty sensitive to changing things this low down and prefer to avoid it when possible, or if we do change things, we try to do so in a way that allows for as much generalization as possible. 

So, can you say a bit more about what you're trying to achieve?

**Comment by mmohrhard** [comment]
Hey Matthew,

in general the idea is that we have additional information for a task that we need to preserve. Currently there does not appear to be a way to transfer per task attributes from the application code to distributed. As an example we have certain tasks that we know should be checkpointed because their results are expensive to compute and loosing them would be too costly to recompute. Currently there is no way to provide this information on the application side in a way that it would end up in TaskState.

Another common case that apparently has come up before are resource restrictions for specific tasks (see also https://github.com/dask/dask/issues/3783 and https://github.com/dask/distributed/issues/2127).

I can't think of all cases where it would be useful right now but here is a small list of attributes that we currently pass from the application to the scheduler for features that need it: resource restrictions for some tasks, initial duration estimations, replication count, whether to checkpoint a key, whether to use a special scheduling behavior (for some tasks we use a different scheduling decision) and more that are quite specific to our setup.

Our experience is that any solution that works purely on the low level task API is difficult to use from higher level APIs like dask array. As a result it seems that the collection interface might be a useful place to start. Maybe you have an idea for a better concept that allows to specify per task/collection attributes and a way to get them from an application to the scheduler.

**Comment by TomAugspurger** [comment]
How would this interact with the proposals in https://github.com/dask/dask/issues/3783? The primary difference is that your proposal is at the collections level, rather than the Task level (which sounds a bit like Jim's comment [here](https://github.com/dask/dask/issues/3783#issuecomment-413193231)?

**Comment by mrocklin** [comment]
This conversation seems to have gone stale.  Closing.
