### ISSUE TITLE
Workstealing On/Off

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3565]
Lately, in a number of experiments I and others I work with are looking at performance and memory pressure issued with workstealing on and off. I know of two ways to run the experiments:

1) restart the cluster with workstealing on/off -- time consume
2) Turn off work stealing with a [call to the scheduler](https://stackoverflow.com/questions/49343494/how-to-turn-off-distributeds-work-stealing-programatically) -- a little awkward

How would folks feel about converting option 2) into something built into distiributed's code base:

```python
client.scheduler.set_workstealing(...)
```

Do this, users would be able to programmatically change the workstealing configuration after a cluster has already been established and work has been done

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @quasiben! I agree the current solution of 

```python
def f(dask_scheduler):
    dask_scheduler.periodic_callbacks['stealing'].stop()

client.run_on_scheduler(f)
```

is a bit clunky and requires additional knowledge of the scheduler's internals. That said, in practice I'm not sure how often workstealing needs to be switched on or off while a cluster in running. 

My primary concern with adding something like `scheduler.set_workstealing(...)` is scope creep with other `scheduler.set_*` methods that allow for programmatically modifying things that can also be set with config values or environment variables.

I'd be curious to hear what others think about this

**Comment by quasiben** [comment]
@jrbourbeau appreciate the response.  Scope creep is definitely something we should consider.  This might be the experiments i've seen as of late and does not have broad enough usage outside our group

**Comment by mrocklin** [comment]
I agree with the scope creep concern.  I think that this is the sort of
thing that should be resolved with configuration.

Also, I'll note that every time someone has wanted to turn off
work-stealing it has always been due to some other issue other than work
stealing.  Often our ability to estimate sizes or bandwidths has been
incorrect for some data type or transport, and fixing that issue made
everything much smoother.

**Comment by jakirkham** [comment]
Yeah one thing I've seen lately is `"pickle"` being used intermittently to serialize data needed by stolen work. Haven't actually figured out why this is happening. Though a pointer to where data gets serialized when stealing work may help isolate this.

**Comment by mrocklin** [comment]
Work stealing doesn't serialize data any differently than any other communication.  Serialization is decently low level.

**Comment by jakirkham** [comment]
Yeah I wouldn't think so. Does it need to go through the scheduler first or does it go directly from worker-to-worker?

**Comment by mrocklin** [comment]
All data transfer between workers is peer-to-peer, without involving the scheduler

**Comment by jakirkham** [comment]
Well not all ( https://github.com/dask/distributed/issues/3507 ), right? 😉

Anyways just trying to see if there is a reason pickling would be chosen. Data moving through the scheduler might be one (though I'm likely still missing something here). Are there others? 🙂

**Comment by mrocklin** [comment]
No, all data transfer between workers is peer-to-peer, without involving the scheduler.  

The issue that you're referring to is about transfers that go through the scheduler.  Certainly data can pass through the scheduler, such as if a client is talking to workers without having direct access, or if the workers want to communicate directly to the scheduler, but that's not transfer between workers.

Even for data moving to the scheduler there is no reason why it would be pickled over transfers between other nodes in the cluster.  Serialization code doesn't really care about the source or destination.

I get the sense that you're hunting for situations that might trigger calling pickle.  I don't think that looking at work stealing is fruitful ground for that.  Or at least it's no more fruitful than any other standard transfer.  Generally Dask handles serialization in a pretty uniform way.  We don't call things specially on a case by case basis.

**Comment by jakirkham** [comment]
Thanks for the details Matt! 😄

Well from the issues I've seen, disabling work stealing eliminates the pickling problem. Hence the interest in looking at work stealing more closely.

**Comment by jakirkham** [comment]
Digging a bit deeper, it appears [`Worker.get_data(...)`]( https://github.com/dask/distributed/blob/f2f82c6c2e8d36731cb3fb82fb1f80ea0323358e/distributed/worker.py#L1192 ) is where deserialization is going awry in our case. Though I'm less clear on where this is getting called from.

**Comment by jakirkham** [comment]
Would you be able to point me to where `Worker.get_data(...)` is getting called @mrocklin? Would like to know what `serializers` it is provided with 🙂

**Comment by jrbourbeau** [comment]
It looks like `Worker.get_data` is called in `Worker.get_data_from_worker` here:

https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/worker.py#L3197-L3204

**Comment by jakirkham** [comment]
Thanks James!

So the serializers are coming from the  [`rpc` object specified]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/worker.py#L3188-L3191 ), which appears to just be [`self.rpc`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/worker.py#L1947-L1949 ) (is that always the case). This in turn seems to be [defined in the `Node` parent class of `Worker`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/node.py#L31-L39 ).

**Comment by jakirkham** [comment]
So I guess the question I have now is how does `ConnectionPool` work. Is this using TCP?

**Comment by jrbourbeau** [comment]
IIUC it will determine the protocol needed from input addresses you'd like to connect to. When a `ConnectionPool` attempts to make a connection here: 

https://github.com/dask/distributed/blob/2acffc3172ec32e173547ee4c39a01b6c94e74a1/distributed/core.py#L894

ultimately results in the selection of the appropreiate connector (e.g. `TCP`, `UCX`, etc.) here:

https://github.com/dask/distributed/blob/2acffc3172ec32e173547ee4c39a01b6c94e74a1/distributed/comm/core.py#L187-L189

**Comment by mrocklin** [comment]
Conversation here seems to have stalled.  @quasiben is this still something that is important to you all?  Should we keep it open?

**Comment by quasiben** [comment]
no, i think we can close for now. Thank you @jrbourbeau and @mrocklin for the discussion
