### ISSUE TITLE
how do I broadcast pd.DataFrame or numpy array to the workers.

### ISSUE THREAD

**Issue by Adam1679** [dask/distributed#3571]
Say that if I have 10 workers and I want to calculate 10 different statistics of the same pd.DataFrame object. I think client.publish_datasets() is not useful because it only supports dask object. I also want to use the communication layer. (Listener in the worker and connector in the main function) but I don't know to use these two components to achieve my goal. Any suggestions?

**Comment by mrocklin** [comment]
I would use either the dask delayed or dask futures APIs.  You shouldn't need anything complex like publish dataset.

**Comment by Adam1679** [comment]
soory i dont get it. From my understanding, delayed is used for computing the DAG and future is used to get the computed results. Why are these two APIs could be used to transfer data?
What I want to do is to train 10 different ML models on the same dataset on 10 different workers and get 10 results.

**Comment by jrbourbeau** [comment]
Both the delayed and futures interfaces will submit tasks to workers in your cluster which you can then retrieve the results. I recommend reading through https://docs.dask.org/en/latest/futures.html and https://distributed.dask.org/en/latest/journey.html

**Comment by Adam1679** [comment]
can delayer or futures transfer data? like a 500MB dataframe?

**Comment by jrbourbeau** [comment]
[Yes](https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-repeatedly-putting-large-inputs-into-delayed-calls). I recommend trying it out to see if either interface is useful to you

**Comment by Adam1679** [comment]
Hey, one more question. I'm trying to use client.submit(func, data, arg1, arg2). This function is very complicated for example, it's the train function of lightGBM. Is it Ok to submit this function to the workers? Now it's working in local machine but I'm afraid this would not work in remote machine even though I could install the dependencies of this `func` in the remote machine. Should I use something like client.upload_file()?

**Comment by mrocklin** [comment]
You should make sure that your software dependencies are the same across
all machines that are using Dask.
