### ISSUE TITLE
Dashboard histogram on "memory usage" doesn't have helpful x-ticks

### ISSUE THREAD

**Issue by stsievert** [dask/distributed#3582]
**Describe the bug**

When the distributed has many workers available, the dashboard page `/status` shows a histogram of the memory usage of each workers:

<img width="265" alt="Screen Shot 2020-03-17 at 10 33 18 AM" src="https://user-images.githubusercontent.com/1320475/76872664-a3106380-6864-11ea-9994-3a1724fd28fb.png">

This graph is not useful to me because it has one tick mark, `0.0`. To see the memory usage of the workers, I have to go to `/workers` and manually parse out the (approximate) maximum memory usage to get an idea of the histogram scale:

<details>
<img width="821" alt="Screen Shot 2020-03-17 at 10 32 27 AM" src="https://user-images.githubusercontent.com/1320475/76872619-9429b100-6864-11ea-9e19-25b2692c792e.png">
</details>

**Expected Results**

I'd like to see at least one other tick mark besides `0.0`. I'd be fine with the maximum usage displaying.

This matters to me because I think I had a `KilledWorker` error because of an out-of-memory error.

**Versions**

* distributed: 2.11.0

**Comment by stsievert** [comment]
This is related to https://github.com/dask/distributed/issues/3060#issuecomment-533335154. The code for the code for the ticks is here: https://github.com/dask/distributed/blob/71c7e4a6305942ae038db05cd55a29e184f998ce/distributed/dashboard/scheduler.py#L385-L388 (thanks to https://github.com/dask/distributed/issues/3060#issuecomment-533344243)

**Comment by mrocklin** [comment]
Thanks for raising Scott.  Do you have any interest in investigating how we
choose ticks in the bokeh/dashboard code?  I have some slight recollection
that this may have been improved on the version of this plot for a smaller
number of workers.

**Comment by stsievert** [comment]
> improved on the version of this plot for a smaller number of workers.

I think you're right: the code to generate the plot moved files. However, the code to generate the memory histogram is the same code on the most recent commit. I've updated https://github.com/dask/distributed/issues/3582#issuecomment-600142237 to point to the code on the latest commit.

**Comment by mrocklin** [comment]
Maybe we want to add more elements to the mantissas parameter?

**Comment by stsievert** [comment]
> Maybe we want to add more elements to the mantissas parameter?

I bet that's right. Here's a case when there are no ticks:

<img width="259" alt="Screen Shot 2020-03-17 at 4 32 35 PM" src="https://user-images.githubusercontent.com/1320475/76903936-d79d1300-6896-11ea-9eed-50cfb716af88.png">

I've got 70 workers, so the average worker is storing 18GB. That is a multiple of 1, but it's not a multiple of 256 or 512.

I'm working on this right now; let me see what happens.
