### ISSUE TITLE
Status page not proxying with bokeh 2.0

### ISSUE THREAD

**Issue by xhochy** [dask/distributed#3593]
This is still an issue for me. I'm hitting the exact same error (No bokeh-protocol specified). 

I've tried with my SM notebook instance being in a VPC / no VPC. Neither works.

Direct Internet is enabled on the SM notebook instance.

_Originally posted by @jennakwon06 in https://github.com/dask/dask/issues/5432#issuecomment-590093520_

**Comment by xhochy** [comment]
As in the referenced issue, I'm also seeing `No bokeh-protocol specified` errors with `bokeh=2.0` and the latest `distributed` version when running the status dashboard behind `jupyter-server-proxy`. Downgrading to `bokeh<2` resolves the problem.

Not sure whether this is a `bokeh` or a `distributed` issue.

**Comment by mrocklin** [comment]
cc @bryevdv from Bokeh, in case he knows of anything that has changed recently that might affect things.

**Comment by bryevdv** [comment]
Bokeh 2.0 was a major release with breaking changes, there is a migration guide here:

https://docs.bokeh.org/en/latest/docs/releases.html#release-2-0-0

**Comment by xhochy** [comment]
The error I get now is 
```
tornado.application - ERROR - Uncaught exception GET /status/ws (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/status/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/uwe/miniconda3/envs/dask-experiments/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/Users/uwe/miniconda3/envs/dask-experiments/lib/python3.8/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
```

**Comment by xhochy** [comment]
Related to this is probably the code in https://github.com/jupyterhub/jupyter-server-proxy/blob/80263c5748f1e0da19fe6b54e6b11883d141788f/jupyter_server_proxy/handlers.py#L317-L322 which proxies the websocket connection.

**Comment by xhochy** [comment]
See also https://github.com/jupyterhub/jupyter-server-proxy/issues/179

**Comment by xhochy** [comment]
Issue is really in `jupyter-server-proxy`, not in `dask`. I'm implementing a fix over there and will close the issue here.

**Comment by mrocklin** [comment]
Thank you for investigating and resolving this Uwe
