### ISSUE TITLE
Adding zoom tools to performance_report

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#3626]
In some cases ["the devil is in the detail"]( https://en.wikipedia.org/wiki/The_devil_is_in_the_detail ), it would be useful to have the zoom tooltips included in other [`performance_report`]( https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports ) panels to allow closer investigation of where time is being spent.

**Comment by mrocklin** [comment]
Sounds great to me
