### ISSUE TITLE
Write doc to explain distributed-on-single-machine

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#364]
I find myself frequently recommending that people use the distributed scheduler on a single machine.  We should write a quick doc page about this.

**Comment by nfaggian** [comment]
Is it a silly idea to have something like "ipcluster" where by default it can just spin up a local dask-scheduler and attached worker?

**Comment by mrocklin** [comment]
This sort of exists now.

>>> Executor()  # does what you want

See distributed.deploy.LocalCluster

**Comment by nfaggian** [comment]
Very cool!
