### ISSUE TITLE
Can't connect to workers inside of VMs across networks

### ISSUE THREAD

**Issue by deepio** [dask/distributed#3648]
Currently this is my worker script:
```python
import asyncio
from distributed import Worker
from config import scheduler_ip

async def f():
  """
  Run tasks comming in
  """
  async with Worker(f"{scheduler_ip}:8786", interface="en0") as w:
    await w.finished()

asyncio.run(f())

```
The interface will return an IP that is only visible to host machine, not the ip of the host controller.
Maybe i'm coming from a naive place where I don't understand all the implications but this seems like an oversight to me, doesn't it? 

```python
Traceback (most recent call last):
  File "/opt/oowashi/env/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/oowashi/env/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/dashboard/components/shared.py", line 325, in cb
    key=self.key, start=self.start, stop=self.stop
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/scheduler.py", line 4933, in get_profile
    for w in workers
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/core.py", line 754, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/core.py", line 898, in connect
    connection_args=self.connection_args,
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/comm/core.py", line 227, in connect
    _raise(error)
  File "/opt/oowashi/env/lib/python3.6/site-packages/distributed/comm/core.py", line 203, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.0.2.15:49164' after 10 s: Timed out trying to connect to 'tcp://10.0.2.15:49164' after 10 s: connect
```
![network issue](https://user-images.githubusercontent.com/28245482/77769203-e499cf00-7019-11ea-91d3-7d6573d0fbee.png)

I don't understand why both addresses need to be specified when a connection is already made? Again this may be a completely naive thought that doesn't consider all scenarios.

**Comment by deepio** [comment]
Maybe there is a NAT thing that can be done?

**Comment by quasiben** [comment]
I am little confused about what is going on here.  It looks like you are defining the IP with `scheduler_ip`, is that not what is being used ?

**Comment by deepio** [comment]
quasiben the workers connect to the scheduler correctly, but it seems the same connection isn't being used to connect back to it? The OSError is from the scheduler side.

**Comment by mrocklin** [comment]
You can select the network interface to be used with the `interface=` keyword.  If your VM has a publicly visible network then you should be able to select it with that keyword. 

I hope that this answers your question.  I'm closing this for now.  If there is some bug in Dask about this then please respond and we'll reopen.

**Comment by deepio** [comment]
it is a bug @mrocklin. When the VM does not have a public IP the worker doesn't work and we need to manually declare a different interface for each VM. When the VM does have a public IP, the interface needs to be manually changed in each worker on the same machine. Why have two connections when TCP goes both ways? This seems to me like a serious design flaw, and I want to emphasize my previous comment :
> I don't understand why both addresses need to be specified when a connection is already made? Again this may be a completely naive thought that doesn't consider all scenarios.

In my naive opinion, only the scheduler's IP should ever be needed period.

**Comment by mrocklin** [comment]
Great.  If you can help to resolve this that would be awesome.

**Comment by mrocklin** [comment]
The workers send along an address at which they can be reached.  The
scheduler makes a connection back to the worker, and also tells other
workers this address so that they can establish peer to peer addresses.

I think that what I'm hearing you say is that it should be able to get the
correct interface/address from the original worker -> scheduler
connection.  I don't know how to do this, but if you do (which it sounds
like you do) it would be great to have your help here.
