### ISSUE TITLE
Call Scheduler.reschedule(key) on tasks with constraints results in memory leak in scheduler

### ISSUE THREAD

**Issue by dtenchurin** [dask/distributed#3663]
Hi,

We are using resources in dask-worker where we specify memory, so as to avoid running too many memory heavy tasks on the same node.

Now, there is explicitly no task stealing for resource constrained tasks/workers. We run everything in AWS and use autoscale, so workers join and unjoin scheduler. A relatively common scenario is when we submit many jobs, and we only have 1 worker in the pool. At some point, more workers will join, and the tasks are not getting rescheduled automatically.

To get around this, we tried getting a list of tasks which are in `constrained` state on a worker, and call `Scheduler.reschedule(key)` on them. Calling `Scheduler.reschedule` many times results in gradual increase of memory used by scheduler which seems to grow linearly with number of calls. Eventually it brings the box down.

I haven't digged deep in the code yet but seems like a memory leak to me so far. 

A minor note:
Often, despite tasks being in `constrained` state, calling Scheduler.reschedule does not end up on moving a task to a free worker. It seems sort of expected by the system, and I was wondering if there was a better way to allow for fully utilizing all workers?

**Comment by gforsyth** [comment]
Hi @dtenchurin -- thanks for reporting!  It would be a huge help to the maintainers if you can provide a [minimal bug report](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).  That would help us figure out if this is an issue on the distributed scheduler only or if it's also present on the threaded and process scheduler.

Additionally, I'm not certain about the efficacy of using resource-constraints in this way. If you know the underlying resources of the node you can specify the number of workers per node to allocate memory-per-worker at the level you want.  Unless you are using heterogeneous worker pools?

**Comment by jrbourbeau** [comment]
> there is explicitly no task stealing for resource constrained tasks/workers

Just as a side note, as of `distributed` version 2.12.0, tasks with resource restrictions can be stolen (xref https://github.com/dask/distributed/pull/3069)

**Comment by mrocklin** [comment]
@dtenchurin do you have time to provide a minimal reproducible example for this?  Otherwise there isn't much that we can do unfortunately.

**Comment by dtenchurin** [comment]
Apologies for longer response times.

I did not notice the new versions originally. After upgrading, I do not see the memory leak anymore. So, we can drop the issue now. 

@gforsyth, thank you for the suggestion. I guess our use case is less about different worker types but more about using different job types. So, the same worker should be allowed to run X jobs of type Y, and X is different for different Y's. Hence, resources were a way to describe this, resulting in heterogeneity of worker pools.
