### ISSUE TITLE
Configurable polling interval for cluster widget 

### ISSUE THREAD

**Issue by jsignell** [dask/distributed#3665]
At the moment, if you render a cluster in the notebook using the widget mechanism, it polls the backend ever 500ms for changes in `scheduler_info`:

https://github.com/dask/distributed/blob/2129b740c1e3f524e5ba40a0b6a77b239d4c1f94/distributed/deploy/cluster.py#L322-L324

It seems like it'd be pretty easy to make this configurable. Perhaps `_widget_callback_interval` (I am open to other names :upside_down_face: ) could be an attr on the Cluster class?

**Comment by jrbourbeau** [comment]
Making this configurable seems fine. These types of values have typically been added as config options in `distributed/distributed.yaml`. Out of curiosity, has the 500ms update time been an issue?

**Comment by jsignell** [comment]
It hasn't been an issue yet, but I am writing a Cluster that does a GET for `scheduler_info` so I am a little worried about doing a done of requests.

**Comment by jrbourbeau** [comment]
Gotcha, thanks for the additional context. How about adding a `distributed.deploy.cluster-repr-update` (other names welcome) config option? It would then be read in when creating the `cluster-repr` `PeriodicCallback` like so:

https://github.com/dask/distributed/blob/7c9da106b2edd543d3b420ad8270261c6a04ec5e/distributed/deploy/spec.py#L354-L356
