### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by robolth** [dask/distributed#3686]
Hi,

[This line](https://github.com/dask/distributed/blame/master/distributed/utils.py#L201) raised an issue for me:

```    except exceptions as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```
Shouldn't this be "Exception as e" (with a capital E)?

(I'm not used to reporting errors, sorry if this is a bit messy.)

Thanks and best regards!

**Comment by martindurant** [comment]
`exceptions` (lower case) here is a list of possible exception classes to match. 

Perhaps for your case you can find out which specific exception is no, apparently, a subclass of `Exception`, and where it's being passed from.
Ideally, you would post a complete and reproducible example here, if you cannot find the cause yourself.

**Comment by jrbourbeau** [comment]
Just checking in here, @robolth are you able to provide a minimal example? (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by TomAugspurger** [comment]
Let us know if you can provide a minimal example or some logs @robolth.
