### ISSUE TITLE
SSHCluster fails in non-bash compatible shells

### ISSUE THREAD

**Issue by abduhbm** [dask/distributed#3687]
SSHCluster fails to propagate `DASK_INTERNAL_INHERIT_CONFIG` variable to scheduler and workers 
 using non-bash compatible shells. 

I suggest to pass this in the `env` keyword in `asyncssh.connection.create_process` instead of embedding it in the process command string to avoid handling different shell syntax for setting variables.

**Comment by mrocklin** [comment]
That sounds sensible to me.  Is this something that you would be
comfortable contributing?

**Comment by mrocklin** [comment]
Ah, I see that you've already started and submitted something.  Thanks!
