### ISSUE TITLE
Mysterious KilledWorker exception

### ISSUE THREAD

**Issue by d-v-b** [dask/distributed#3694]
I'm using `client.map()` with `dask-jobqueue` to run a long compute job on an LSF cluster. This job reliably fails about about an hour, which is wonderful for debugging. 

The failure itself is heralded by a "killed worker" announcement, with no report of an error from inside my code, which makes me think something funky is going on with the scheduler / nanny. 

An additional clue is the reliable appearance of this uncaught exception from bokeh:
 
```python
ERROR - Uncaught exception GET /status/ws (10.60.1.99)
HTTPServerRequest(protocol='http', host='10.36.110.11:8787', method='GET', uri='/status/ws', version='HTTP/1.1', remote_ip='10.60.1.99')
Traceback (most recent call last):
  File "/groups/scicompsoft/home/bennettd/miniconda3/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/groups/scicompsoft/home/bennettd/miniconda3/lib/python3.8/site-packages/bokeh/server/views/ws.py", line 135, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.
```
Sorry I can't be more precise in my diagnosis -- debugging an error that takes an hour to appear is necessarily time-consuming, and since my code is fine (and I need the output) I can just divide the job into partitions and restart at the point where the failure occurred. 

My hope is that a dev sees the bokeh exception and the solution to my problem is obvious. A long shot, I know :)

**Comment by mrocklin** [comment]
cc @jsignell

**Comment by d-v-b** [comment]
Continued testing suggests that the bokeh thing is a red herring -- my workers are chugging along happily despite that unhandled exception popping up. 

Here's the full traceback, in case this gives anyone any clues. This had been running for about an hour before it crashed. 
```python
KilledWorker          Traceback (most recent call last)
<ipython-input-11-3930f5a7b23c> in <module>
      2 results = []
      3 for batch in tqdm(slices_partitioned):
----> 4     results.append(cl.gather(cl.map(saver, batch)))
      5 cl.cluster.scale(0)

~/miniconda3/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1886             else:
   1887                 local_worker = None
-> 1888             return self.sync(
   1889                 self._gather,
   1890                 futures,

~/miniconda3/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    775             return future
    776         else:
--> 777             return sync(
    778                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    779             )

~/miniconda3/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

~/miniconda3/lib/python3.8/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

~/miniconda3/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1751                             exc = CancelledError(key)
   1752                         else:
-> 1753                             raise exception.with_traceback(traceback)
   1754                         raise exc
   1755                     if errors == "skip":

KilledWorker: ('saver-4c6691538914a258eb69939ae9a29ce1', <Worker 'tcp://10.36.60.23:38828', name: 367, memory: 0, processing: 5>)
```

I will next do a test where I re-instantiate the client + cluster for each partition to test for any funny statefulness in those bits.

**Comment by mrocklin** [comment]
I would also check worker logs if you have them

**Comment by d-v-b** [comment]
Dividing my job into batches and cleanly recreating client + cluster per batch was successful. So there's no problem intrinsic to the tasks themselves. 

I'm attempting to replicate the error, this time with worker logs.

**Comment by d-v-b** [comment]
Worker logs revealed that I was hitting a 1 hour runtime limit imposed by our cluster scheduler. Not a dask problem :)

**Comment by mrocklin** [comment]
Glad to hear it.  You might want to look at the lifetime keyword for
dask-workers.  They can shut themselves down gracefully in just under an
hour if you like, which might avoid this situation in the future.

**Comment by joej** [comment]
I don't know if this is worth posting to an old thread, but ...

I have long-running application, submitting sets of records to dask over a range of millions of records. At some point, the scheduler freezes -- 

site-packages/tornado/websocket.py line 3208  

site-packages/bokeh/server/views/ws.py line 149, in open

raise ProtocolError("Token is expired.")

bokeh.protocol.exceptions.ProtocolError: Token is expired.
