### ISSUE TITLE
SSHCluster fails if client and nodes have different Python paths

### ISSUE THREAD

**Issue by abduhbm** [dask/distributed#3700]
I tested this on my laptop and a remote server. Python installations are on different paths.
```python
    with SSHCluster(
            ["remote-node"] * 2,
            scheduler_options={"idle_timeout": "10s"},
            worker_options={"death_timeout": "10s"},
    ) as cluster:
        with Client(cluster) as client:
            ....
```
output:
```
distributed.deploy.ssh - INFO - bash: /client/path/bin/python: No such file or directory
Traceback (most recent call last):
...
```

`dask-ssh` overcomes this by allowing passing `remote_python` keyword to nodes. This can be easily done in the new `SSHCluster` implementation. I will work on a new PR.

**Comment by mrocklin** [comment]
Yes, that would be great.  Ideally everywhere that we currently use
sys.executable we would instead defer to some user provided value (which
would presumably default to sys.executable).  Thank you for volunteering
for this.
