### ISSUE TITLE
remote_path is ignored in SSHCluster

### ISSUE THREAD

**Issue by H4dr1en** [dask/distributed#3707]
Current State:

In the doc: https://docs.dask.org/en/latest/setup/ssh.html#cmdoption-dask-ssh-remote-python
It is not specified that one can use `remote_python` in SSHCluster, although both `worker_options` and `scheduler_options` support it:
- https://github.com/dask/distributed/blob/master/distributed/deploy/ssh.py#L87
- https://github.com/dask/distributed/blob/master/distributed/deploy/ssh.py#L163

Furthermore, these parameters are ignored when passed, dask always using `sys.executable` in both remote scheduler and workers.

Expected behavior:
I would like to pass `remote_python` to both `worker_options` and `scheduler_options`.

Implementation details:

- https://github.com/dask/distributed/blob/master/distributed/deploy/ssh.py#L113
- https://github.com/dask/distributed/blob/master/distributed/deploy/ssh.py#L189

Both calls should replaced with `self.remote_python or sys.executable`, as it is in [old_ssh.py](https://github.com/dask/distributed/blob/master/distributed/deploy/old_ssh.py#L295)

**Comment by abduhbm** [comment]
PR #3701 was created to pass `remote_python` in SSHCluster.  It seems that I missed this part when trying to resolve a merge conflict. My bad !
