### ISSUE TITLE
403 Forbidden when accessing bokeh interface over ssh port forwarding

### ISSUE THREAD

**Issue by Futrell** [dask/distributed#371]
I connected to a remote host with port forwarding:

`ssh me@example.com -L 8888:localhost:8889`

Then I started the dask scheduler with `localhost` in the bokeh whitelist:

``` bash
$ dask-scheduler --bokeh-port 8889 --bokeh-whitelist localhost
distributed.scheduler - INFO - Scheduler at:        169.228.47.26:8786
distributed.scheduler - INFO -      http at:        169.228.47.26:9786
/home/rfutrell/anaconda3/lib/python3.5/site-packages/distributed/bokeh/application.py - INFO -  Bokeh UI at:  http://169.228.47.26:8889/status/
bokeh.command.subcommands.serve - INFO - Check for unused sessions every 50 milliseconds
bokeh.command.subcommands.serve - INFO - Unused sessions last for 1 milliseconds
bokeh.command.subcommands.serve - INFO - Starting Bokeh server on port 8889 with applications at paths ['/status', '/tasks']
distributed.core - INFO - Connection from 169.228.47.26:46043 to Scheduler
distributed.core - INFO - Connection from 169.228.47.26:46044 to Scheduler

```

Connecting to `localhost:8888/status` locally, I get `403: Forbidden`, and on the remote server it says `bokeh.server.tornado - INFO - Rejected connection from host 'localhost:8888' because it is not in the --host whitelist`.

I think the argument `--bokeh-whitelist localhost` is supposed to avoid this problem, but maybe I misinterpreted the docs? 

Thanks!

**Comment by mrocklin** [comment]
This might be related to https://github.com/dask/distributed/pull/376

**Comment by mrocklin** [comment]
You might have to specify the port in the whitelist something like `--bokeh-whitelist localhost:8888`

**Comment by mrocklin** [comment]
Was that helpful at all?  By default we now send `*` in the whitelist.

Closing if no further information arises.

**Comment by Futrell** [comment]
Thanks for looking into it! I just pulled and with 
```{bash}
ssh me@example.com -L 8888:localhost:8889
dask-scheduler --bokeh-port 8889
``` 
I get a 404 error when I try to connect to `localhost:8888`, with no message on the server side.
Same result including `--bokeh-whitelist localhost`.
With `--bokeh-whitelist localhost:8888`, it says `Invalid host value: localhost:8888:8889` and does not accept connections.

**Comment by mrocklin** [comment]
Closing as out of scope.  Network issues are important but probably distinct enough for every individual installation so that we can't reasonable resolve them all.
