### ISSUE TITLE
Test failure in test_oversubscribing_leases

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3717]
This showed up in a recent PR.  I copy-pasted the traceback and then restarted the job. 
 Unfortunately my attempt to copy-paste the trace turned out to be incomplete.  My apologies.  Hopefully this helps though.

cc @fjetter 

```python-traceback
>   assert not sem.acquire(timeout=0.05)
E   assert not True
E    +  where True = <bound method Semaphore.acquire of <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>>(timeout=0.05)
E    +    where <bound method Semaphore.acquire of <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>> = <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>.acquire

distributed\tests\test_semaphore.py:396: AssertionError
---------------------------- Captured stderr call -----------------------------
distributed.worker - WARNING -  Compute Failed
Function:  observe_state
args:      ()
kwargs:    {'sem': <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>}
Exception: AssertionError('assert not True\n +  where True = <bound method Semaphore.acquire of <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>>(timeout=0.05)\n +    where <bound method Semaphore.acquire of <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>> = <distributed.semaphore.Semaphore object at 0x0000027BF23DE438>.acquire',)

```

**Comment by mrocklin** [comment]
It's coming up here as well.  (I didn't restart the job this time)

https://github.com/dask/distributed/pull/3650/checks?check_run_id=593854022

Pinging also @lr4d

**Comment by fjetter** [comment]
Looking into it

**Comment by mrocklin** [comment]
Thanks!

**Comment by mrocklin** [comment]
I *think* that this is still happening.  I reran these tests about an hour ago, which I think is after the recent merge of #3720 

https://github.com/dask/distributed/pull/3650/checks?check_run_id=596031832

**Comment by lr4d** [comment]
@mrocklin in the traceback I see `>   assert not sem.acquire(timeout=0.05)`, whereas this was changed in #3720 at https://github.com/dask/distributed/pull/3720/files#diff-dee863c4f303f33e8e88eb708f00130bL396
