### ISSUE TITLE
Dask dashboard over ssh

### ISSUE THREAD

**Issue by funkMasterRyan** [dask/distributed#3724]
I use Dask with Xarray and I am trying to profile my code through the Dask dashboard. My aim is to tunnel the dashboard over ssh from a remote virtual machine to my local (laptop) browser. This doesn't seem to work for me. Here's what I do. 

First of all I am setting up port forwarding from the remote location to my laptop via

    ssh -N -L 8000:localhost:8787 <username>@<remote hostname>

Then as a test in a separate terminal, I ssh to the remote host in the normal way

    ssh -X <username>@<remote hostname>

and run the following in IPython from that terminal

   ```
 from dask.distributed import LocalCluster
 cluster = LocalCluster(n_workers=1)
```

then open a browser on my laptop with the address http://localhost:8000/ in an attempt to open the Dask dashboard. This fails and returns the following in my port forwarding terminal

    ​channel 2: open failed: connect failed: Connection refused

I have made small progress here by defining the scheduler_port variable. I changed my IPython code to

    from dask.distributed import LocalCluster
    cluster = LocalCluster(n_workers=1, scheduler_port=8787)

​​Now when I try the address http://localhost:8000/ I no longer get connection refused error above. However, the browser just hangs and does nothing as if it is waiting for data.

The way I see it there are three potential sources of my problem:-
1) I have made a trivial error 
2) This is a specific problem with the remote machine that I am trying the tunnel the dashboard from 
3) There is a bug with Dask

I presume it is 1) or 2) but I thought I'd post here in case it is 3).

**Comment by gforsyth** [comment]
@funkMasterRyan -- what's the value of `cluster.dashboard_url` on the remote host?

**Comment by funkMasterRyan** [comment]
`cluster.dashboard_url`
 
returns 

`'LocalCluster' object has no attribute 'dashboard_url'`

Did I misinterpret what you mean here?

I can import `bokeh` just fine on the remote host, if that helps. It seems version 0.12.4. is installed.

**Comment by gforsyth** [comment]
Ugh, sorry, `cluster.daskboard_link`

**Comment by funkMasterRyan** [comment]
Ohh yeah, you are right. `cluster.daskboard_link` returns an empty string.

Though I can import `bokeh`. Is Dask not linking up with `bokeh` properly?

**Comment by gforsyth** [comment]
Could be you have two separate environments -- you might want to install using `conda` to avoid any missing dependencies.

In terms of specifying ports, if you set `scheduler_port` to `8787`, that's the default dashboard port so that might be messing with things.  You could try instead to run

```
LocalCluster(n_workers=1, dashboard_address="localhost:8787")
```

**Comment by funkMasterRyan** [comment]
I have got to the bottom of my problem, lack of conda was the issue.

Whilst I did have conda and did use it to install some packages, the word 'some' here was root of my problem. I had installed some packages using conda and some with pip. After reinstalling everything with conda, the dask dashboard worked just fine.

Thanks for your comments @gforsyth
