### ISSUE TITLE
2.15.1 release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#3749]
We're getting a few bug reports about the dashboard on the latest 2.15.0 release (xref https://github.com/dask/distributed/issues/3741, https://github.com/dask/distributed/issues/3748, https://github.com/dask/dask/issues/6141). At least one of the issues, if not more, were fixed by https://github.com/dask/distributed/pull/3746. Any objections to doing a 2.15.1 release of `distributed`? cc @mrocklin @TomAugspurger @jakirkham

**Comment by TomAugspurger** [comment]
Yeah that seems reasonable.

**Comment by mrocklin** [comment]
+1 from me

**Comment by jakirkham** [comment]
+1

**Comment by jrbourbeau** [comment]
2.15.1 is out on PyPI and the conda-forge feedstock was just updated

**Comment by jakirkham** [comment]
Thanks James! 😄
