### ISSUE TITLE
Missing dask attribute from executor object

### ISSUE THREAD

**Issue by alberthdev** [dask/distributed#375]
According to http://distributed.readthedocs.io/en/latest/executor.html#dask-graph, there should be a `.dask` attribute attached to the `executor` object for examining the computation graph.

However, when trying to access this attribute after a dask computation with `distributed.get`, `AttributeError: 'Executor' object has no attribute 'dask'` occurs. In addition, `dask.base.visualize(executor, filename='executor.pdf')` produces a blank PDF, likely due to the missing attribute as well.

Mini example:
```python
import distributed

def inc(x):
    return x + 1

executor = distributed.Executor('127.0.0.1:8786')
x = executor.submit(inc, 10)
print(x.key)
print(executor.refcount)
print(executor.futures)
print(executor.dask) # AttributeError here
```

I'm using the latest distributed (distributed.__version__ == '1.11.2') and the latest dask (dask.__version__ == '0.10.1').

**Comment by mrocklin** [comment]
Thanks!  I've removed this section from the docs.  You're correct that this is no longer accessible from the Executor

**Comment by alberthdev** [comment]
Do you know if there's an alternative to viewing the executor's "perspective" of the graph? I've noticed that executor schedules different parts of the graph for threads/processes, and it would be interesting to see some of that in action!

(Even more interesting would be to control how distributed handles that, but that might be for another issue...)

**Comment by mrocklin** [comment]
A serialized version of the dask graph lives on the scheduler.  If you're running the scheduler from the local process then it's accessible.  This occurs when you create an executor without arguments:

```python
e = Executor()
e.cluster.scheduler.dask
```

The web interface may interest you: http://distributed.readthedocs.io/en/latest/web.html
