### ISSUE TITLE
Graph Construction Time

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3750]
Lately a number of problems have come up which typically involve long/longish graph construction times.  Graph construction time may be due to the large number of partitions (TB scale) or complex operations or both combined!  It would be great to quantify how long this construction is.  

Naively, we could do something like:
```
t0 = time.time()
x = x.persist()
t1 = time.time()
```

But this would involve more than just the graph construction, it would also measure serialization and communication (though hopefully these are quite small) and possibly other things.  This metric would potentially also be useful in measuring changes to algorithms.  For example, in a recent exploration task annotations, users [visualized with/without changes](https://github.com/dask/dask/pull/6051#issuecomment-606800071).  I don't think in that particular example graph construction was the core issue but the ease with which maintainers can ask for more information and have users provide that was nice.

I think the [visualize function](https://github.com/dask/dask/blob/master/dask/base.py#L496-L510) effectively computes the graph with options to optimize.  If I didn't call `dot_graph` or matplotlib things, would that be a reasonable proxy?

**Comment by mrocklin** [comment]
You may want to read through https://docs.dask.org/en/latest/phases-of-computation.html

My guess is that you want to use `dask.optimize` rather than `dask.visualize` to make sure that you do all of the processing before sending the graph off.

In addition to timing, you might also look into profiling.  This might give you a better sense for what to focus on to reduce costs.

**Comment by jakirkham** [comment]
Thanks for that pointer. Would it make sense to add that doc page to the index somewhere to aid discoverability?

**Comment by quasiben** [comment]
Thanks @mrocklin for anyone else coming along to this issue that would be something like following:

```python
In [1]: from dask import optimize
   ...: from dask.datasets import timeseries
   ...: from dask.dataframe.shuffle import shuffle
   ...: from distributed import Client

In [2]: client = Client()

In [3]: ddf_h = timeseries(start='2000-01-01', end='2005-01-01', partition_freq='1d')

In [4]: result = shuffle(ddf_h, "id", shuffle="tasks")

In [6]: %time optimize(result)
CPU times: user 2.41 s, sys: 62.4 ms, total: 2.47 s
Wall time: 2.46 s
Out[6]:
(Dask DataFrame Structure:
                      id    name        x        y
 npartitions=1827
                   int64  object  float64  float64
                     ...     ...      ...      ...
 ...                 ...     ...      ...      ...
                     ...     ...      ...      ...
                     ...     ...      ...      ...
 Dask Name: drop_by_shallow_copy, 97709 tasks,)
```
