### ISSUE TITLE
[FEA] Include total number of tasks in the performance report summary

### ISSUE THREAD

**Issue by beckernick** [dask/distributed#3753]
Dask performance reports can be invaluable when profiling complex workloads. When evaluating multiple workloads at once, it can be difficult to remember the size of the task graphs in each workload. Including the total number of tasks in the Summary tab of the performance report would be a nice addition, perhaps under the Duration section.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @beckernick, adding the total number of tasks seems like a reasonable addition. Is this something you're interested in working on? (no obligation though)

**Comment by beckernick** [comment]
Thanks @jrbourbeau . I don't have the bandwidth at the moment to explore this segment of the codebase (I'm not already familiar with it), so if someone wants to jump on this to implement this feature in the short term that's fine with me.

**Comment by jrbourbeau** [comment]
Not a problem, we'll just leave this issue open to track progress. As this does require some knowledge of how the performance report is produced, I've marked it as a good second issue
