### ISSUE TITLE
Add logo to performance_report browser tab

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#3754]
Dashboard pages have the Dask logo as a favicon for browser tabs

<img width="353" alt="Screen Shot 2019-09-26 at 9 01 32 AM" src="https://user-images.githubusercontent.com/11656932/65728164-b98ced80-e07f-11e9-9220-138a11c73555.png">

It would be nice if `performance_report` pages also had the logo as a favicon

**Comment by mrocklin** [comment]
+1
