### ISSUE TITLE
stealing from dask bags

### ISSUE THREAD

**Issue by pierreglaser** [dask/distributed#3762]
Hi all!

In the context of improving the `joblib-dask` integration I've been playing a bit with the `dask.bag` feature. Although the `joblib.Parallel` API is not exactly similar to the `bag`-`map` api, `dask.bag` is still of interest because `joblib` peforms task batching to speed up the execution of numerous tasks.

There are some situations though where `joblib` can become too greedy when batching tasks, to the point where a worker is given the vast majority of tasks (in a single batch) while other workers end up idle with nothing to execute. 

We thought about implementing work stealing in `joblib`, but this mean taking a step towards making `joblib` behave like a scheduler, which I'm not sure we want.

What sounds possible though, is leveraging `dask.distributed`'s scheduler capabilities to perform work stealing. By playing around with work stealing, it works great when `submit`ing individual tasks, but (and this is perfectly normal), If we `submit` a batch of tasks, `workers` won't be able to steal some of those tasks within this batch.

My question is thus: is it possible, using the `dask.bag.map` api, to have workers steal tasks from within a `dask` bag? I tried a naive attempt and my provisional answer is that it is not possible right now:

```python
import time
import logging

import numpy as np

from distributed import Client, LocalCluster
from dask import bag as db


def sleep_and_return_len(x):
    if len(x) == 1000:
        time.sleep(0.01)
    elif len(x) == 2000:
        time.sleep(1)
    else:
        raise ValueError
    return len(x)


if __name__ == "__main__":
    cluster = LocalCluster(
        n_workers=2, threads_per_worker=1, silence_logs=logging.WARNING
    )
    client = Client(cluster)

    list_of_arrays = [np.arange(1000)] * 5 + [np.arange(2000)] * 5
    b = db.from_sequence(list_of_arrays, npartitions=2)

    t0 = time.time()
    print(b.map(sleep_and_return_len).compute())
    print(f"total time: {time.time() - t0}")
```

The first 5 tasks take only 0.01 second to be executed, whereas the last 5 take 1 second to be executed. Thus, the first bag will take 0.05 seconds, and the second will take 5.

IF `distributed` was able to perform work stealing, I would expect the total time to be ~2.5 seconds, but I'm seeing 5 seconds.

***

My next question is thus: is stealing from within a bag a feature that you think is useful? How hard would it be to implement it?
cc @mrocklin in particular.

Cheers!

**Comment by mrocklin** [comment]
All of the APIs, futures, bag, dataframes, arrays, ml, all create task graphs for the scheduler.  When the scheduler is running computations it doesn't know the origin of those graphs.  The scheduler doesn't know what a bag is.

> My question is thus: is it possible, using the dask.bag.map api, to have workers steal tasks from within a dask bag?

Certainly the tasks that correspond to operating on a partition of a bag can be moved around, just as the tasks that correspond to a future can be moved around.  However if you are asking if it is possible to have the scheduler decide to split up a partition of a bag on the fly then the answer is "no".  More generally, if you wanted to do this it would also be the same for futures, because the scheduler doesn't see any difference between the two.  

I think that futures + as_completed is the right Dask API for joblib.  I think that most of the confusion around that integration comes from the implementation, which is messy, rather than any specific lack of feature.  

I think that if we incorrectly batch too many tasks together into a single batch then Dask probably won't un-batch things.  I think that this logic should happen before we get to Dask.  Maybe we can changing the batching logic to be a little bit more smooth, and so hopefully avoid making bad guesses around batch size?

**Comment by pierreglaser** [comment]
> I think that futures + as_completed is the right Dask API for joblib. I think that most of the confusion around that integration comes from the implementation, which is messy, rather than any specific lack of feature.


One important remark: I opened this issue because of the following problematic situation that was reported to `joblib`: when using `joblib` to run a bunch of *long-running* tasks, and that the first ones have been `cached` using `joblib.Memory`, the autobatching feature of `joblib` will think that those first tasks are very quick (which they aren't), and increase the batch size a lot.

Thus, this is not particularly about adding a feature, but more about making sure the one `joblib` already has work smoothly :)

>   I think that if we incorrectly batch too many tasks together into a single batch then Dask probably won't un-batch things. I think that this logic should happen before we get to Dask. Maybe we can changing the batching logic to be a little bit more smooth, and so hopefully avoid making bad guesses around batch size?
 
This is what we did in answer to this situation - we also thought about implementing work stealing, but ended up not doing this because of what I mentioned above. While working on `dask`, I remembered about this issue (opened a year ago), hence this post.


>  However if you are asking if it is possible to have the scheduler decide to split up a partition of a bag on the fly then the answer is "no". More generally, if you wanted to do this it would also be the same for futures, because the scheduler doesn't see any difference between the two.

Understood.

**Comment by mrocklin** [comment]
You could choose to cancel a task and resubmit many smaller tasks maybe?

**Comment by pierreglaser** [comment]
> You could choose to cancel a task and resubmit many smaller tasks maybe?

Thank you for providing an alternative, this is definitely an option. I'll think about it, although this would delegate some of the work stealing logic to `joblib`, which I would rather not do in the first place. I opened this issue hoping that it was be possible, using the right API, to have `dask` do this job for `joblib` (or to implement this feature in `dask`, provided that it was reasonably doable), but given what you are telling me, it is not.

**Comment by mrocklin** [comment]
Unfortunately correct I think
