### ISSUE TITLE
test_preload_remote_module failing on windows

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#3774]
See e.g. https://github.com/dask/distributed/pull/3729/checks?check_run_id=645884483. First thought is a race condition setting up the endpoint, but that's just a guess.

**Comment by jrbourbeau** [comment]
Thanks @jcrist. It looks like our windows CI builds didn't run in https://github.com/dask/distributed/pull/3768. I just saw the final "all CI passed" check mark and didn't notice that only Travis builds ran. I'll try a few things over in https://github.com/dask/distributed/pull/3775, and if that doesn't work out then we can `xfail` for the time being

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/3775
