### ISSUE TITLE
Incorrect GPU Memory Totals 

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3808]
On the `/individual-gpu-memory` page, the GPU memory title value far exceeds what is used and available:

<img width="1470" alt="Screen Shot 2020-05-17 at 10 50 09 PM" src="https://user-images.githubusercontent.com/1403768/82170031-4f84bb00-9891-11ea-997d-b065d4d213bb.png">

This was executed on a DGX1 with 256GBs of 
GPU memory, not 2TBs.  Perhaps a counting issue within https://github.com/dask/distributed/blob/1bcbaeee4a92d57fb2d399c9580fce6480a6d7c9/distributed/dashboard/components/nvml.py#L136-L153

**Comment by jacobtomlinson** [comment]
Out of curiosity how much system memory does that DGX1 have? Is that where the 2TB number is coming from or is it more random than that?

**Comment by quasiben** [comment]
> bzaitlen@dgx12:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:        1031977       14079      291489          90      726408     1011670
Swap:             0           0           0

1TB

**Comment by mrocklin** [comment]
It looks like there is some repetition.  My guess is that every worker is
looking at all of the GPUs on the machine, and so you're getting 8x8
records.  They should probably filter by CUDA_VISIBLE_DEVICES or something.

**Comment by jacobtomlinson** [comment]
I've started exploring this in #3810, although I don't think I've found a fix yet.
