### ISSUE TITLE
ValueError: too many file descriptors in select() 

### ISSUE THREAD

**Issue by ankravch** [dask/distributed#381]
I am testing how many workers I can start with dask distributed on Windows. After ~150 workers I see error message:

Traceback (selected):
sys.exit(distributed.cli.dask_scheduler.go())
...
distributed\cli\dask_scheduler.py line 69, in main
loop.start()
...
tornado\ioloop.py, line 858, in start
event_pairs = self._impl.poll(poll_timeout)
tornado\platform\select.py, line 63, in poll
self.read_fds, timeout
ValueError: too many file descriptors in select()

P.S. After googling it looks like FD_SETSIZE has to be increased but I not sure what specifically should be recompiled to reset FD_SETSIZE.

**Comment by mrocklin** [comment]
Yup, that'll have to be handled on the operating system level.  I can point you to very good resources for how to change this limit on Linux.  I don't have any information off-hand on how to do this on Windows.  We should figure this out though and put docs up somewhere.  

Just to be clear, there is nothing within the Dask codebase itself that can help you here.  There is some setting somewhere in your operating system that needs to be tweaked.

I'm quite curious what your use case is.  You're the first person that I know of who has run into this issue while on Windows (most larger installations run on Linux.)

**Comment by ankravch** [comment]
I have a bunch of files (~500). Each file has 100-5000 columns (some columns are columns of arrays), ~20M rows, ~20Gb in hdf5 format (now testing bcolz as alternative). And I am trying to use Dask as 'swiss army knife' tool to do:

step0: Select specific rows based off finder file(s) (join operation). Output file is sorted by 2 columns. Output Nrows can be up to 500M. Output Ncolumns can be up to 1000 columns.
(I want to benchmark Dask against Hadoop+Hive+ORC)

step1: further reduce data by basic sql-like operations
(I want to benchmark Dask against MonetDB)

step2: statistical analysis/machine learning

P.S. My feeling is that Dask could outperform other alternatives for this use case. Potentially I could setup a few hundreds worker cluster with a total shared RAM 1-3 Tb.

**Comment by mrocklin** [comment]
@ankravch did you find a way to change the open file limit on Windows?  I apologize for not having a ready answer for you on this one.

**Comment by ankravch** [comment]
No I didn't, I am working on a company machine, so I cannot recompile Windows on my own to test possible solutions that I found on Google. Though I could try to ask IT department for help.

**Comment by ankravch** [comment]
I follow up http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/ to increase FD size on CentOS Linux
After setting: fs.file-max = 100000 (in etc/sysctl.conf) and session required pam_limits.so (in pam.d/login)
```python
[akravchenko@hnode1 ~]$ cat /proc/sys/fs/file-max
10000000
[akravchenko@hnode1 ~]$ ulimit -Hn
100000
[akravchenko@hnode1 ~]$ ulimit -Sn
100000
[akravchenko@hnode1 ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128355
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 10240
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

[akravchenko@hnode1 ~]$ python
Python 3.5.1 |Anaconda custom (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
>>> from socket import *
>>> from select import select
>>> s = [socket(AF_INET, SOCK_DGRAM) for i in range(1024)]
>>> select(s, [], [], 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: filedescriptor out of range in select()
>>>
KeyboardInterrupt
```
and
```python
>>> s = [socket(AF_INET, SOCK_DGRAM) for i in range(1020)]
>>> select(s, [], [], 1)
([], [], [])
```
Is there a way to increase FD_SETSIZE from 1024 to 100000 (for example) on Linux? 
P.S. It looks like possible solutions http://stackoverflow.com/a/27389613 (for Linux) and http://stackoverflow.com/a/14929259 (for Windows) require to modify and re-compile /usr/include/sys/select.h (on Linux) and Win32 SDK WINSOCK.H (on Windows).
