### ISSUE TITLE
Worker plugin called with superseded transition

### ISSUE THREAD

**Issue by nre** [dask/distributed#3813]
The bug is obvious in the code but the effect is a bit too subtle for a MWE.

Please see #3812 for the fix and a test.

**Comment by jacobtomlinson** [comment]
> The bug is obvious in the code

Could you spell it out at least a little for future visitors to this issue?

**Comment by nre** [comment]
When a worker transitions a task from state A to state B and that transition is superseded by a transition to state C, then the worker incorrectly notifies its plugins that the resultant task state is B, instead of C.
