### ISSUE TITLE
Worker plugin is not notified when worker releases task

### ISSUE THREAD

**Issue by nre** [dask/distributed#3815]
The worker plugin is notified when a task changes state but not when the task is released.

@mrocklin asked [whether `release_key` should be added to the worker plugin API](https://github.com/dask/distributed/issues/3681#issuecomment-610653124).

Alternatively, `release_key` could notify the worker plugin that the task has transitioned to "forgotten", which is consistent with the behaviour of the scheduler plugin.

I am keen to implement either solution.

**Comment by jacobtomlinson** [comment]
I think that given the worker is still working on the task, despite it being released, means that moving to forgotten doesn't make sense.

A PR to add `release_key` to the worker plugin would be a nice addition.
