### ISSUE TITLE
Inconsistent RAM display in the GUI

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#3818]
In the bokeh dashboard:

- Status tab, top-left panel: "Bytes stored" and the mouseover tooltip are expressed in GB (10^9) and rounded to 2 decimals
- Status tab, top-left panel: the X axis of the bar chart is in GiB (2^30) with 1 decimal
- Workers tab: the "memory" and "memory_limit" columns are expressed in GiB with 0 decimals.

The first point frequently forces me to flip out the pocket calculator to figure out how far I am from the pause threshold.
The last point is annoying as I set my memory limit to 1.5 GiB but I read "2 GiB" in this table.

I think that
- All measures should be in powers of 2, as it makes it easier to correlate them with the RAM installed on the host
- All measures should be rounded to 3 digits (2 decimals if >10, 1 decimal if >100, 0 decimals otherwise).

Bonus:
- It would be useful to have vertical marking bars on the graph to show the various thresholds (target, spill, pause, terminate)
- The bars currently turn orange if they go beyond 50% of the memory_limit. I find it's not very meaningful; IMHO they should turn orange if they go beyond ``distributed.worker.memory.target`` and red if they go beyond ``distributed.worker.memory.pause``.

**Comment by jacobtomlinson** [comment]
Making these values consistent sounds reasonable. Would you be interested in submitting a PR to make these changes?

**Comment by jacobtomlinson** [comment]
> The bars currently turn orange if they go beyond 50% of the memory_limit.

This is being discussed over in #3799

**Comment by crusaderky** [comment]
> Would you be interested in submitting a PR to make these changes?
In theory yes, in practice this would go fairly low in my backlog. Sounds like a great ticket for a beginner to me
