### ISSUE TITLE
"Too many open files" in scheduler

### ISSUE THREAD

**Issue by amosonn** [dask/distributed#382]
Sometimes, when using the same scheduler process for too long, while killing and respawning workers, we start getting "Too many open files" errors, and then of course everything breaks. This isn't an issue of too many workers for the amount of available fds, since we manage to launch a scheduler and all the workers afresh, and everything works; and we always kill the workers before spawning the new ones.

Sadly, I don't have a good, reproducible way to get this; it just happens sometimes after too many times of restarting the workers.

I looked a bit at the scheduler code for closing dead sockets and didn't find something obvious. One guess I have is that it might take some time for the scheduler to notice that the stream is dead, even after the workers are - either because the OS is waiting for some timeout on TCP, or because tornado doesn't get to the worker_stream coroutine yet - and in the meantime connections from the new workers are already getting opened.

**Comment by mrocklin** [comment]
OK.  Thanks for the bug report and the warning that everything works fine ahead of time.

We should construct a test that starts and closes workers repeatedly while also doing work to see if we can trigger this.

**Comment by mrocklin** [comment]
I'm unable to trigger this.  See #422 .   @amosonn can you provide a test case?  Closing for now.  Please reopen if problem persists and is reproducible.
