### ISSUE TITLE
Default value for Security(require_encryption=) keyword

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3886]
I'm curious about the `require_encryption=` keyword.  Currently it defaults to False.

I'm curious if it should default to True if the user provides TLS information

cc @jcrist

**Comment by jcrist** [comment]
Yeah, IMO this should always be true, I don't see a use case for enabling TLS but not requiring it. If a user wants to enable an encrypted channel and an unencrypted channel, they should listen on multiple ports.

**Comment by mrocklin** [comment]
Here is one approach to address this: https://github.com/dask/distributed/pull/3887
