### ISSUE TITLE
What is the best way to profile workers in "process" mode local cluster?

### ISSUE THREAD

**Issue by dkhokhlov** [dask/distributed#3891]
What is the best way to profile workers in "process" mode local cluster?
Inject cProfile in each worker?

**Comment by mrocklin** [comment]
You may be interested in this documentation page:
https://docs.dask.org/en/latest/understanding-performance.html

**Comment by dkhokhlov** [comment]
That is just Worker time stats. I need function level profiling, like cProfile, tracing type.

**Comment by mrocklin** [comment]
I recommend that you read dead the docs more closely, and maybe also take a
look at some of the videos that are there.

**Comment by mrocklin** [comment]
https://docs.dask.org/en/latest/diagnostics-distributed.html#capture-diagnostics

**Comment by dkhokhlov** [comment]
Right, but that is sampling, not tracing type, isn't it? 

===================================

Client.profile([key, start, stop, workers, …]) | Collect statistical profiling information about recent work

===================================

Is using Yappi in worker good idea?
