### ISSUE TITLE
Variables leak virtual clients

### ISSUE THREAD

**Issue by marco-neumann-jdas** [dask/distributed#3899]
**What happened**:

```python
def _get_number_of_clients(dask_scheduler: Optional[Scheduler] = None) -> Optional[int]:
    if dask_scheduler is None:
        return None
    else:
        return len(dask_scheduler.clients)

n_clients1 = client.run_on_scheduler(_get_number_of_clients)
assert n_clients1 is not None

for i in range(100):
    future = create_some_dummy_future()
    var = Variable(f"var-{i}", client)
    var.set(future)
    future.cancel(force=True)
    var.delete()

n_clients2 = client.run_on_scheduler(_get_number_of_clients)
assert n_clients2 is not None

assert n_client1 == n_clients2
```

This fails, because here:

https://github.com/dask/distributed/blob/1d7640b0172febf9ceef37c2c31241c66ac165eb/distributed/scheduler.py#L2333-L2347

a new virtual client for each and every variable is created but here:

https://github.com/dask/distributed/blob/1d7640b0172febf9ceef37c2c31241c66ac165eb/distributed/scheduler.py#L2349-L2361

we never clean up / prune these clients again.

**What you expected to happen**:

Scheduler-side state is not leaky.

**Environment**:

- Dask version: 2.17.2
- Distributed version: 2.17.0
- Python version: 3.6
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
Thank you for the issue @marco-neumann-jdas .  I'm able to reproduce.  

It looks like we should call `Scheduler.remove_client` when we delete a variable (assuming that it has already been created).  Is this something that you would be interested in fixing?
