### ISSUE TITLE
Broken dashboard on latest Bokeh Version

### ISSUE THREAD

**Issue by dariusgm** [dask/distributed#3913]
**What happened**:
- I installed dask with distributed in a docker environment. One Container is for the scheduler and one for workers. After running my first job, it returned "404: Not Found" instead of showing the dashboard. I was suprised, as the dashboard worked on a different device, installed earlier without docker without issues.

**What you expected to happen**:
I want to see the dashboard correctly

**Minimal Complete Verifiable Example**:
see install

**Anything else we need to know?**:
I could fix the issue, but wanted to share the fix to the appropriate Project

**Environment**: Docker (Ubuntu)

- Dask version: 2.18.1
- Python version: 3.8.2 (3.7 in Docker)
- Operating System: Windows 10 64bit (Ubuntu in Docker)
- Install method (conda, pip, source): Dockerfile

Dockerfile, Broken:
```
FROM python:3.7
RUN apt-get update -y && apt-get install -y python3-pip libsnappy-dev
RUN pip install numpy
RUN pip install dask
RUN pip install distributed
RUN pip install fsspec
RUN pip install fastavro
RUN pip install python-snappy
RUN pip install dask[bag]
RUN pip install dask[dataframe]
RUN pip install jupyter-server-proxy

# Dashboard
EXPOSE 8787
# Scheduler
EXPOSE 8786
```
this will install bokeh using Version **2.1.0**

Dockerfile with Fix:
```
FROM python:3.7
RUN apt-get update -y && apt-get install -y python3-pip libsnappy-dev
RUN pip install bokeh==2.0.2
RUN pip install numpy
RUN pip install dask
RUN pip install distributed
RUN pip install fsspec
RUN pip install fastavro
RUN pip install python-snappy
RUN pip install dask[bag]
RUN pip install dask[dataframe]
RUN pip install jupyter-server-proxy

# Dashboard
EXPOSE 8787
# Scheduler
EXPOSE 8786
```
Will force install bokeh using Version **2.0.2**

With this Version, the Dashboard works as expected

See also my post on stackoverflow for more Details and for a full copy past example: https://stackoverflow.com/questions/62345391/local-dask-cluster-using-docker-compose

**Comment by mrocklin** [comment]
Thank you for reporting.  This was resolved in the latest Dask update.
2.19.0.

**Comment by quasiben** [comment]
Thanks @mrocklin .  Closing
