### ISSUE TITLE
LocalCluster not responding to n_workers.

### ISSUE THREAD

**Issue by drdraad** [dask/distributed#3923]
Using a debian linux server with 16 cores, I am trying to set the number of workers in the local cluster, but no matter what I set `n_workers` to it always creates 4 workers with 4 processes each.

```
from dask.distributed import Client, LocalCluster
import multiprocessing
cluster = LocalCluster(n_workers=multiprocessing.cpu_count())
```
SELF.CLIENT.NCORES() {'tcp://127.0.0.1:34473': 4, 'tcp://127.0.0.1:36213': 4, 'tcp://127.0.0.1:42079': 4, 'tcp://127.0.0.1:44011': 4}

**Comment by quasiben** [comment]
Hmm, I just tired this without issue:

```python
In [23]: import multiprocessing

In [24]: multiprocessing.cpu_count()
Out[24]: 96

In [25]: from distributed import Client, LocalCluster

In [26]: cluster = LocalCluster(n_workers=multiprocessing.cpu_count())

In [27]: cluster
Out[27]: LocalCluster('tcp://127.0.0.1:36399', workers=96, threads=96, memory=1.62 TB)

In [28]: len(cluster.scheduler.get_ncores())
Out[28]: 96
```

What version of distributed and dask are you using ?

**Comment by drdraad** [comment]
Thanks. I'll test those outputs. 
dask==2.16.0
distributed==2.18.0

**Comment by drdraad** [comment]
Resolved. Was not passing `cluster` into the `Client()`. Doh!
