### ISSUE TITLE
Large bytestrings making their way into msgpack

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#393]
Msgpack does not handle large bytestrings well.  Usually we evict large bytestrings from messages and send them along separately (see http://matthewrocklin.com/blog/work/2016/04/14/dask-distributed-optimizing-protocol).  

From https://github.com/dask/dask/issues/1411#issuecomment-235655955 it appears that this isn't happening during a `scatter` operation.  This may be because the large bytestrings aren't at the top-level of the message, but instead in a `data=` key.  

If this is the case then there are a few options:

1.  Dump scattered keys into the top-level keys of the message (and watch out for key conflicts)
2.  Teach the protocol to look more deeply into sub dictionaries (but be careful that this doesn't affect performance in the many-small message case)
3.  Special case a few keys, like `data` and `payload`

This might be a good learning issue.  Pinging @jcrist

**Comment by jcrist** [comment]
I've tried repeatedly to reproduce the issue, and am failing. I've tried:

- 1 single large numpy array to send to one worker
- Many single large numpy arrays to send to one worker.

Both cases have passed fine. The code is below:

```python
import numpy as np
from distributed import Executor, LocalCluster
import pickle
from pandas import msgpack

c = LocalCluster(n_workers=1, threads_per_worker=1)
exc = Executor(c)

# -- Single large array --
# Shape picked so that pickle.dumps(data, protocol=2) results in a bytestring
# longer than 2**31. You can't pickle numpy arrays where the data bytes are longer
# than 2**31 - 6.
data = np.zeros(2**31 - 6, dtype='i1')
exc.scatter([data])

# -- Many Slices --
# Shape taken from original issue, div by 2 so it fits on my machine twice
shape = (145, 174, 145, 288 / 2)
data = np.zeros(shape=shape)
slices = [data[..., i] for i in range(data.shape[-1])]
remote = exc.scatter(slices)
```

@akcheung, do you have a reproducible example for this?

**Comment by akcheung** [comment]
Try the code pasted in the beginning of [#1411](https://github.com/dask/dask/issues/1411), uncommenting out `data = np.random.randint(0, 1000, size=(145, 174, 145, 288))`

**Comment by mrocklin** [comment]
Regardless of whether or not we can get this to fail it remains a performance bottleneck.  

This should produce unfriendly results:

    from distributed.protocol import dumps

    msg = {'x': {'y': b'large-random-byte-string'}}
    %prun dumps(msg)

@jcrist I suspect that your example did not fail due the data being highly compressible.  Try switching out for random data for a better (worse) result.

**Comment by mrocklin** [comment]
I've been thinking about this a bit more and I think that the following could work:

Currently messages are broken into two parts

1.  Small msgpack friendly bits
2.  key-value pairs of large bytestrings in the top-level dictionary

I propose that instead we swap out part 2 for key-sequences and large byte strings.  Consider the following example

    {'x': 1, 'y': b'big-byte-string-1', 'z': {'a': 2, 'b': b'big-byte-string-2'}}

As currently implemented the protocol would decompose this into the following two pieces

    msg = {'x': 1, 'z': {'a': 2, 'b': b'big-byte-string-2'}} 
    keys = ['y']
    values = [b'big-byte-string-1']

Instead I propose the following:

    msg = {'x': 1, 'z': {'a': 2}} 
    keys = [('y',), ('z', 'b')]
    values = [b'big-byte-string-1', b'big-byte-string-2']

Keys now contains paths from which large bytestrings originated.  These paths are similar to what you find in `toolz.update_in`. 

This doesn't solve the performance problem; we need to verify that traversing through every message doesn't cause undue overhead.  We should benchmark this a bit.  If it is a problem then we can probably get around it with a combination of opt-in (we know which messages are likely to contain large bytestrings) and exception handling (if the protocol fails to serialize something, then try traversing through.)
