### ISSUE TITLE
Compute time per task with too many task types

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3930]
I'm loving the new compute time per task plot.  I think that we could improve it in two ways:

1.  Format times better.  Often I see times like `1.528528e4 s`.  We might do this on the server side with `dask.utils.format_time`, or on the Bokeh side, however they manage formatting. 
2.  We should probably only show the top few entries:

![image](https://user-images.githubusercontent.com/306380/85952538-cdbb8f00-b91e-11ea-8fcd-4eba18d40c1e.png)

Actually, this may be one situation where a pie chart makes more sense.  We don't need to give the same horizontal space to every task type.

**Comment by mrocklin** [comment]
@quasiben @jsignell

**Comment by jsignell** [comment]
I think we could do away with the legend entirely if it's just duplicating the x-ticks. I am personally fine with a pie chart for this, but people hate them so much, I'm not sure it's worth it.

**Comment by mrocklin** [comment]
Heh, yeah.  This seems like maybe one of those situations where a pie chart
might actually make sense though.  The amount of visual emphasis matches
the question we're trying to figure out, and the distribution of values
that we tend to see (there are often only one or two relevant components to
cost, and pie charts do well in that range).

**Comment by mrocklin** [comment]
Not pushing hard for pie charts though, we could also just truncate
anything less than 2% or something.
