### ISSUE TITLE
Deadlock in dask.DataFrame in multithreading environments

### ISSUE THREAD

**Issue by frol** [dask/distributed#395]
Here is a minimal reproduction example:

``` python
import threading

import dask
import dask.dataframe
import dask.distributed
import pandas

e = dask.distributed.Executor('master:8786')

dask_df = dask.dataframe.from_pandas(
    pandas.DataFrame([{'x': x for x in range(10)}], columns=['x']),
    npartitions=1
)

def worker(x):
    print("Started #%d" % x)
    dask_df.count().compute(get=e.get)
    print("Ended #%d" % x)

tt = []
for i in range(50):
    t = threading.Thread(target=worker, kwargs={'x': i})
    t.start()
    tt.append(t)

for i, t in enumerate(tt):
    print("Joining thread #%d..." % i)
    t.join()
```

It doesn't matter what kind of computation on `dask.DataFrame` I run in the `worker` function, it just inevitably hangs.

I have Dask 0.10.2 and Distributed 1.11.3 running on Linux (4 workers with `--nprocs 20 --nthreads 2`).

NOTE: `dask.Bag` seems to work just fine.

NOTE2: `threaded` and `multiprocessing` Dask schedulers also work fine.

**Comment by mrocklin** [comment]
Very interesting.  It would be interesting to see if things still lock up when each thread creates a separate Executor.  This would isolate the issue between the executor and the scheduler.

**Comment by frol** [comment]
@mrocklin Creating a new executor in each thread helps to avoid the deadlock.

**Comment by mrocklin** [comment]
OK, so this is just that the Executor is not threadsafe.  I'm not overly concerned about this at the moment.  Do you agree or do you see this being important for your use case?

**Comment by frol** [comment]
@mrocklin I would love to see this fixed, and since it happens in just one specific case, I believe that the fix won't be hard (though I am almost sure that tracking it down will be nasty). If you don't have time at the moment, please, suggest the places where it is worth to start since I'm not quite familiar with the source code of distributed yet.

**Comment by mrocklin** [comment]
I would try putting a lock around the self._graph_to_futures call in the
get() function.

**Comment by frol** [comment]
The deadlock does not occur only if I wrap both `self._grapth_to_futures` and `self.gather` with the same lock (it can be two individual locks but with the same key/filename). Wrapping them with different locks doesn't solve the deadlock, so they somehow interfere. I'm continuing my digging, but if this raises some thoughts on where should I focus, it would be helpful.

BTW, `e.compute(dask_df.count(), sync=True)` doesn't cause the deadlock!

**Comment by mrocklin** [comment]
I'm fairly surprised that `compute(sync=True)` is safer than `get()`.

I'm also surprised that you needed to lock around gather, which should just be dumping a callback onto the tornado IOLoop (in a thread-safe way.)

**Comment by frol** [comment]
Basically, there are two functions:

1. [`dask.base.compute`](https://github.com/dask/dask/blob/master/dask/base.py#L129-L184) is not thread-safe
2. [`distributed.executor.Executor.compute`](https://github.com/dask/distributed/blob/master/distributed/executor.py#L1063-L1133) seems to be thread-safe

First, why are there two quite similar implementations? Can they be merged?

The differences that I have noticed:

1. `dask.base.compute` uses `distributed.executor.Executor.get` while `distributed...compute` calls `_graph_to_futures` and `gather` directly
2. `dask.base.compute` gathers results and calls `._finalize` on them while `distributed...compute` merges `._finalize` into the `dsk` graph, so it gets executed on workers.
3. `dask.base.compute` uses `set(flatten([[var._keys() for var in variables]]))` as names while `distributed...compute` uses `['finalize-%s' % tokenize(v) for v in variables]` (`set` VS `list`).

**Comment by mrocklin** [comment]
The `Executor.compute` method differs from `dask.compute` because it returns asynchronous futures rather than concrete results.  The dask.compute function blocks.

**Comment by frol** [comment]
Hmm, it turned out that the deadlock only occurs if I repeatedly schedule the same computations, e.g. in the example above I used `dask_df.count()`, which resolves always to the same dask key, the same deadlock will happen if I run `dask_df.query('x > 10').count()` or `dask_df[dask_df.x > 10].count()` or `dask_df.head()`. However, I don't hit the deadlock if every computation is unique, e.g. `dask_df[dask_df.x > x].count()` (notice I use `x` variable which is passed to the `worker` function instead of a constant `10`).

**Comment by frol** [comment]
It feels like the issue somewhere in non-atomic caching, something along these lines:

```python
if key in cache:
     return cache[key]
...
```

Though, I couldn't find anything like that, and it looks like I ran out of ideas at the moment.

**Comment by mrocklin** [comment]
The relevant shared state here is probably the `Executor.futures` dict.  Perhaps you can make a thread-safe get by either using a lock or using `sync`

```python
def get(dsk, keys):
    return sync(e.loop, e._get, dsk, keys)
```

**Comment by frol** [comment]
Yes, I figured that I can just use `e.compute(sync=True)`, but I wanted to catch the bug... I have tried to put locks down into `Executor._graph_to_futures` and `Executor.gather`, but I couldn't find anything specific yet.

**Comment by mrocklin** [comment]
Any progress on this?  Generally I don't think we're likely to "catch the bug" here.  The executor is not designed to be threadsafe.  There are countless occasions where functions assume that they are being called transactionally.  Functions that only use `sync` should be fine because everything gets sequentialized down to the IOLoop.  We probably can't trust functions outside of the IOLoop though, nor do I think we should devote significant energy here.  I think it makes more sense for calling code to use locks.

**Comment by frol** [comment]
@mrocklin I'm sorry, I was busy with my other tasks, so I haven't been able to get back to this since then. Also, while I still need to manipulate with Dask DataFrames concurrently, I may get away with the workarounds I have already discovered here (`e.compute(sync=True)` and explicit locks). Thus, I'm not sure how much effort I will be able to put here.

**Comment by mrocklin** [comment]
Fine by me.  I'm personally find just closing this and claiming that `get` isn't threadsafe.

**Comment by frol** [comment]
Yep, it is definitely worth to make that statement somewhere in the documentation with a link to this thread.

**Comment by mrocklin** [comment]
I believe that get is now threadsafe
