### ISSUE TITLE
Extracting memory allocation from serialization

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#3970]
Currently serialization handles memory allocation/transmission internally in a somewhat custom way. For example in `tcp` we allocate `bytearray`s, which we fill up with data received. Whereas for `ucx`, we use NumPy arrays (or `bytearray`s if NumPy isn't available) for host allocations and RMM (or Numba if RMM is not available) for device allocations. It would be useful to collect these allocations procedures into one common module. . This would also allow us to use them in other places where they may be important like spilling or even more specific utilities (like those used to merge/split frames). Should also help us to cutdown some code duplication between the `ucx` and `tcp` code paths and avoid bugs that may occur due to differences between these paths. Feedback on this thought would be welcome 🙂

cc @mrocklin @quasiben @pentschev @madsbk

**Comment by jakirkham** [comment]
Any thoughts here? 🙂

**Comment by quasiben** [comment]
I would be +1 on common module for allocation.  Would you expect that if an error arises on the TCP side that someone would have to be knowledgable about UCX serialization as well to fix ?

**Comment by pentschev** [comment]
@quasiben makes a great point I didn't consider initially. Maybe it would be risky to do that for now while we don't have tests that cover UCX more broadly, a change that works on TCP may completely break UCX. But if we find a way to test things, I'm +1 in unifying things.

**Comment by jakirkham** [comment]
Honestly I think this will be easier for us to test. As [it is]( https://github.com/dask/distributed/blob/7cdba1d7e17df7be005f4d4b8ca528065a3f83a7/distributed/comm/ucx.py#L66-L103 ), it's not really easy or possible to test.

**Comment by pentschev** [comment]
> Honestly I think this will be easier for us to test. As it is, it's not really easy or possible to test.

It depends, I understand it will make things easier for us to test as a whole, and most of us are testing when we change things in `ucx.py`, even though there aren't many tests in CI. What worries me is someone who's mostly unaware of UCX doing TCP-related changes that end up breaking UCX support.

**Comment by jakirkham** [comment]
We are already in the habit of reaching out to potentially affected parties when making changes. I don't think this will be too different. That said, I don't expect this to change much.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/dask/distributed/pull/5750 ), which starts down this path. It is not as clean as a separate module atm. However it does provide a way to benefit from NumPy's faster allocations in TCP, which should address the issue seen in this comment ( https://github.com/dask/distributed/issues/5258#issuecomment-904296519 ).

**Comment by jakirkham** [comment]
Resolved in PR ( https://github.com/dask/distributed/pull/5750 )
