### ISSUE TITLE
profile plots incorrect?

### ISSUE THREAD

**Issue by mdering** [dask/distributed#3985]
**What happened**:
I'm running a distributed cluster and trying to use the profile plots to see where our bottlenecks are in different tasks. Unfortunately I'm dealing with what I can only describe as a correctness issue. Specifically the plot shows lines of code being children of other lines in an impossible way. Having things this way basically makes these plots kind of useless. Is this a known issue or could it be something specific to our environment?

**What you expected to happen**:
I'd expect to see code nested correctly
**Minimal Complete Verifiable Example**:
Sorry, I don't really have anything to put here

**Comment by mrocklin** [comment]
Thank you for raising an issue.  I'm surprised to hear that things aren't
working correctly for you.  Without an example there isn't much we can do
to help. You might want to look through the implementation here to see if
you can spot any place where there might be an issue:
https://github.com/dask/distributed/blob/master/distributed/profile.py

**Comment by mdering** [comment]
I think it's pretty strange too. I've used py-spy on this code base and not seen a similar issue, but the flame chart format is the same right? some of it can be inferred from context, but plenty of it can't be. For instance, for one of my tasks it says that a pandas dataframe being copied is taking a long time, but below it in the hierarchy is other user code which wouldn't be invoked by a simple copy. I'm sorry I can't help replicate it.

**Comment by quasiben** [comment]
If you can I would recommend generating a [performance report](https://docs.dask.org/en/latest/diagnostics-distributed.html#capture-diagnostics) and posting and linking it here.  Maybe you could annotate some of the plots and indicate where you think the there are correctness issues

**Comment by jakirkham** [comment]
Any updates here @mdering? A performance report or even screenshot would be helpful 🙂

**Comment by mdering** [comment]
I can try to generate a performance report, but I'll have to go through and anonymize things because I'm using this for a system at work and plenty of the stack traces i'm having trouble with are part of our core IP. I'm not sure if that will be terribly helpful, but maybe. I'll try to get a screenshot of what I'm referring to, just to show that i'm not crazy, but I'm going to have a hard time recreating even a MWE and I can't really share it here.

**Comment by mdering** [comment]
<img width="1377" alt="dask screenshot" src="https://user-images.githubusercontent.com/1246446/89069182-ace0c200-d340-11ea-9f39-cc9518a23f24.png">
ok here is a screenshot of a task I'm trying to profile. As you can see, the hierarchy is there, but the profiler says the task spends 75% of its time copying a single series, and even above that in the hierarchy, it lists other processing done elsewhere, outside of making a copy of that series, so it's definitely not correctly reporting what it's spending time on. Let me know if this is helpful at all.

**Comment by quasiben** [comment]
It's a little hard to comment but copies can take a long time.  Are you copying between processes ?  If so then there is going to be a serialization component ?  Is this host memory or GPU memory ?  Can you profile just the copy with something like snakeviz ?

**Comment by mrocklin** [comment]
It could also be that the code in that line (slicing and copying) has some
unexpected effects that trigger other computations.  Python code is
sometimes a bit magical. If those objects are lazy in some way then maybe
that line triggers some computation?
