### ISSUE TITLE
Rotate text of Bandwidth type chart

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#3992]
![image](https://user-images.githubusercontent.com/306380/88599638-19964c80-d021-11ea-808e-9d3a3e9d8e50.png)

We should probably slightly rotate the labels on the x axis so that they pack a bit more nicely.

This requires understanding a bit of Bokeh (or looking at their docs) and modifying the BandwidthTypes class here

https://github.com/dask/distributed/blob/907452b1bc0f7876a01de5ff39cc2dc64eb3c4a4/distributed/dashboard/components/scheduler.py#L274-L322

**Comment by mrocklin** [comment]
We do this for other plots too, so there are probably examples of rotating text in that same file

**Comment by quasiben** [comment]
`fig.xaxis.major_label_orientation = -math.pi / 12` is what we've typically done

**Comment by hugobowne** [comment]
I'll happily take a stab at this, probably next week some time!

**Comment by mathdugre** [comment]
@hugobowne Did you start working on this issue ? Otherwise, I would be glad to work on it.

**Comment by mrocklin** [comment]
Go for it Mathieu

**Comment by mathdugre** [comment]
Following @quasiben suggestion I set the `fig.xaxis.major_label_orientation` to rotate the x-axis labels. After trying different values, I found that a rotation of `-0.5` looked pretty good.
Those are the plots generated with a value of `-0.5`: 

### Dask Bandwidth [Type]
![image](https://user-images.githubusercontent.com/16450132/89724992-c8f7f980-d9f9-11ea-9655-584b094bcb03.png)

### Dask Bandwidth [Type] (smaller window)
![image](https://user-images.githubusercontent.com/16450132/89724994-d0b79e00-d9f9-11ea-9f9c-ce774dd944a2.png)

If this seems good, I'll open a PR.

**Comment by mrocklin** [comment]
It seems like an improvement to me :)

**Comment by hugobowne** [comment]
This looks cool. Apologies for dropping the ball slightly here.
