### ISSUE TITLE
Dashboard issues with very large clusters

### ISSUE THREAD

**Issue by willirath** [dask/distributed#4002]
I'm on the latest conda defaults channel  `dask` and `distributed` and see formatting issues of the dashboard with very large clusters:

- On `...:8787/workers`: For a cluster of 100 workers with 24 maxed out (each at 100% cpu) threads each I get total CPU displayed as roughly the average use of one worker (2400%)

![image](https://user-images.githubusercontent.com/5700886/89029134-08558480-d32e-11ea-8bd8-235efb004a28.png)

- On `...:8787/status`: The histogram view of memory use displays bytes stored of O(1 MB) while the true memory occupation of the cluster is O(10TB):

![image](https://user-images.githubusercontent.com/5700886/89029328-77cb7400-d32e-11ea-9a64-8c759079605e.png)

**Comment by mrocklin** [comment]
My guess is that we're using the `dask.sizeof.sizeof` function to guess the size in bytes of all of the data tracked by each worker, and that we're underestimating the objects that you're using.  

For the non-histogram plot (which is used for fewer workers) we switched from using sizeof to using the memory of the process as reported by psutil.  We should probably make this same change for the histogram plot.

I think that we probably want to replace the `ws.nbytes` here

https://github.com/dask/distributed/blob/7cdba1d7e17df7be005f4d4b8ca528065a3f83a7/distributed/dashboard/components/scheduler.py#L264-L271

Any interest in handling this @willirath ?  It seems like a mostly easy fix.

**Comment by willirath** [comment]
> Any interest in handling this @willirath ? It seems like a mostly easy fix.

Yes, I'll have a look next week.

**Comment by willirath** [comment]
#4006.

I just noticed that the averaging of the CPU percentages is intended. So my PR only tackles the memory histogram issue.
