### ISSUE TITLE
Executor fails when not started

### ISSUE THREAD

**Issue by stefanv** [dask/distributed#401]
When starting the executor asynchronously, it can happen that tasks are submitted before it has been started, resulting in:

```
Exception raised while submitting task:
'Executor' object has no attribute 'scheduler_stream'
```

It would be good to have a way of querying the executor status, to see if it is currently accepting tasks or not.

**Comment by mrocklin** [comment]
That seems reasonable.  We have a `.status` attribute on all other classes.
