### ISSUE TITLE
Worker dashboard crashes when dask-worker --memory-limit 0 set

### ISSUE THREAD

**Issue by timeisapear** [dask/distributed#4020]
**What happened**: I set dask-worker --memory-limit 0 and the worker status page crashes 500

**What you expected to happen**: To see the worker page not crash

**Minimal Complete Verifiable Example**: 

```python
dask-worker tcp://:8786 --memory-limit 0
```
then navigate to 

http://scheduler-ip:8787/workers

**Anything else we need to know?**:
`dask-scheduler` stack trace:

```python
dask_scheduler_1  | ERROR - 2020-08-05 14:10:32 - distributed.utils.log_errors.l661 - division by zero
dask_scheduler_1  | Traceback (most recent call last):
dask_scheduler_1  |   File "/opt/conda/envs/dra/lib/python3.7/site-packages/distributed/utils.py", line 656, in log_errors
dask_scheduler_1  |     yield
dask_scheduler_1  |   File "/opt/conda/envs/dra/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1939, in workers_doc
dask_scheduler_1  |     table.update()
dask_scheduler_1  |   File "/opt/conda/envs/dra/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 93, in func
dask_scheduler_1  |     return input_function(*args, **kwargs)
dask_scheduler_1  |   File "/opt/conda/envs/dra/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1864, in update
dask_scheduler_1  |     ) / sum(ws.memory_limit for ws in self.scheduler.workers.values())
```

**Environment**:

- Dask version: '2.20.0'
- Python version: Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
- Operating System: Ubuntu Linux (Docker)
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
I think this was resolved by https://github.com/dask/distributed/pull/3984.  Can you upgrade to latest dask and try again ?  I'm going close for now but if this is still an issue feel free to reopen
