### ISSUE TITLE
Dashboard not found (404)

### ISSUE THREAD

**Issue by STOpandthink** [dask/distributed#4026]
I'm using [Python Advanced Setup](https://docs.dask.org/en/latest/setup/python-advanced.html) to run Dask on AWS inside a Docker container. For some reason when I try to access the dashboard, I get a 404. This even happens when I ping `http://localhost:8787` inside Docker. Everything else works fine.

Logs:
```
distributed.scheduler - INFO - Scheduler at: tcp://10.0.101.154:8786
distributed.scheduler - INFO - dashboard at: :8787
```

I've read through (all?) related issues here, but none of the fixes seemed to work.

Code:
```
async def scheduler_main():
    s = Scheduler(port=8786)
    s = await s
    await s.finished()

asyncio.get_event_loop().run_until_complete(scheduler_main())
```

**Environment**:

- Bokeh: 2.1.1
- jupyter-server-proxy==1.5.0
- Dask version: 2.22.0
- Python version: 3.7
- Operating System: Amazon ECS-Optimized Amazon Linux AMI 2018.03.20200723
- Install method (conda, pip, source): pip

**Comment by STOpandthink** [comment]
One thing that wasn't quite clear to me: do I need to run jupyter lab along side this (or something like that)?

**Comment by mrocklin** [comment]
Try adding dashboard=True to the Scheduler constructor

**Comment by STOpandthink** [comment]
Oh, wow, that's it. Thank you.

I guess I'd expect it be on by default, or that the documentation should tell you to turn it on, or that the logger shouldn't imply that the dashboard is running.
Overall though, Dask is amazing, so kudos to everyone!

**Comment by mrocklin** [comment]
Yes, most people don't use this API, and instead use LocalCluster or
dask-scheduler, both of which add this value by default.
