### ISSUE TITLE
Executor: more robustly connect to scheduler

### ISSUE THREAD

**Issue by stefanv** [dask/distributed#403]
Currently, the executor does not attempt to re-connect to the scheduler if the scheduler dies.  This could potentially improve robustness.

**Comment by mrocklin** [comment]
To be clear, you're not looking to recover the scheduler state here, yes?  Presumably all Futures currently in play in the Executor would transition to a lost or cancelled state if the scheduler restarts with a blank canvas.

**Comment by stefanv** [comment]
Yes, I am willing to accept that loss, but I would like the system to come back online as soon as possible so that I can start re-submitting tasks.

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/distributed/pull/413

**Comment by mrocklin** [comment]
You can now close a scheduler, restart it in the same place with the same port, and all of the workers and clients will reconnect within a short time.  

All in-flight futures will be cancelled and will need to be resubmitted.  It's possible, that some function calls will err if the socket break happens while they're communicating.  This doesn't currently heartbeat, so we're trusting the socket to close itself.  This happens with SIGTERM but not with SIGKILL so we're still not resilient to something like a power outage or the scheduler segfaulting but we are resilient to the operating system closing the process for any reason, such as shutting down, a keyboard interrupt, etc..

**Comment by stefanv** [comment]
This is very helpful to us, as we run the scheduler as a service (along 
with many other services), and sometimes want to cycle all of these up/down 
without restarting all the workers. Thanks a lot, Matthew.

**Comment by mrocklin** [comment]
Let me know how it goes.  We should expect a couple of lingering issues to arise in production.
