### ISSUE TITLE
HTTPS Dashboard CLI option

### ISSUE THREAD

**Issue by smst329** [dask/distributed#4040]
I have been searching through the documentation and I do not see a way to get a HTTPS dashboard with CLI option when launching the scheduler from the CLI. I am already using TLS. I could reverse proxy or set up other machinery but I also think it should be an standard option.

**Comment by quasiben** [comment]
I suspect this is because the tls protocol options are not passed to the dashboard tls options directly.  Still, I think this can be done with env vars on the CLI like the following:

```
DASK_DISTRIBUTED__SCHEDULER__DASHBOARD__TLS__CA_FILE=distributed/tests/tls-ca-cert.pem \
DASK_DISTRIBUTED__SCHEDULER__DASHBOARD__TLS__CERT=distributed/tests/tls-cert.pem \
DASK_DISTRIBUTED__SCHEDULER__DASHBOARD__TLS__KEY=distributed/tests/tls-key.pem \
dask-scheduler  --tls-ca-file distributed/tests/tls-ca-cert.pem --tls-cert distributed/tests/tls-cert.pem --tls-key distributed/tests/tls-key.pem
```
Or you could also change the dask config file as well to something like the following:

```
distributed:
  scheduler:
    dashboard:
      tls:
        ca-file: foo
        cert: foo
        key: foo
```

**Comment by smst329** [comment]
Awesome! I'll definitely test the env variables. I still want to push a --https true or just --https flag, especially if tls has already been set up for everything else. So far I'm digging dask and wish I heard of it earlier. Really like the notebook server container with comparable setup to the worker and scheduler containers. The team is doing great work! Feel free to close this issue, the options given are definitely enough to pursue this further.

**Comment by quasiben** [comment]
Thanks @smst329 and if you do want to push on things feel free to open a new issue
