### ISSUE TITLE
consistent color scheme across workflows

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/distributed#4050]
This is a minor suggestion, but it would be nice if the colors assigned to task had some deterministic flavour (e.g. based on the hash of the task name). This would make it easier to compare scheduler activity across different workflows/scheduler sessions. Somewhat related to https://github.com/dask/distributed/issues/2711

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @SultanOrazbayev. Is there a particular plot where you've noticed non-deterministic colors being assigned to tasks? Taking a quick look at the task stream plot, it looks like we're using using the [`color_of` utility](https://github.com/dask/distributed/blob/5e7285cb200d461034a439274d2a5db87c3df9e7/distributed/utils.py#L1283-L1287) to [determine what color a task should have](https://github.com/dask/distributed/blob/e08aa22a4a7e955f247033ed8403a908461896df/distributed/diagnostics/task_stream.py#L156-L170). As `color_of` uses a md5 hash of the task key to determine the color, I would have expected it to be deterministic

**Comment by SultanOrazbayev** [comment]
Oops, my bad. :/ I think the problem is that my functions have similar, but not exactly the same names across the workflows. So `load_func` will have a very different color from `load_f`... and I assumed that the color was just random, but I see that I should just have more consistent naming of the functions. Thanks for the pointer!

**Comment by jrbourbeau** [comment]
I see, no worries, thanks for your quick follow up!
