### ISSUE TITLE
Opening Graph dashboard page causes work starvation on workers due to high scheduler CPU load

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#4055]
**What happened**:

Opening the `Graph` page of the bokeh dashboard while executing a large task graph (>100k) puts so much load onto the scheduler that it is not able to distribute tasks to workers anymore. This issue cannot be resolved by closing the dashboard again. In fact, the scheduler instance is put into a state where, following the opening of the page once, it cannot handle large tasks graphs ever again and must be restarted.

The configuration option `distributed.dashboard.graph-max-items` does not protect from this scenario. Opening the dashboard page registers a periodic callback which continuously executes `TaskGraph.update` which calls the `TaskLayout.reset_index` and loops over all tasks and their dependencies causing the slowdown of the scheduler.

Below is the profile-server view of an affected cluster

![image2020-8-18_14-50-55](https://user-images.githubusercontent.com/8629629/90775377-0f523000-e2f9-11ea-9b14-7f84a8a27564.png)

**What you expected to happen**:

Only marginal impact of bokeh dashboard on compute performance.

**Minimal Complete Verifiable Example**:

* Start a cluster

```python
client = Client("...")
client.gather(client.map(lambda x:x, range(100000)))
```

* Open bokeh dashboard and open the graph and monitor CPU load

**Comment by mrocklin** [comment]
Agreed. that this is an issue.  That plot isn't terribly useful above a few thousand tasks.  I think that this has come up before in an issue, but I can't find it right now.

I think that the easiest fix for this is to modify `TaskGraph.update` to only update things if the number of tasks is smallish (a few thousand).  It looks like this was the intent of the `graph-max-items` change by @martindurant but that hasn't been entirely effective.  @fjetter are you or someone on your team interested in resolving this?

**Comment by martindurant** [comment]
(the intent of `graph-max-items` was to stop the browser downloading or attempting tp render graphs that are too big to be sueful)

**Comment by fjetter** [comment]
I'm also wondering if the `GraphLayout` plugin should be disabled if the submitted graph is too large. I haven't measured the runtime for `GraphLayout .update_graph`, yet, but if it isn't used anyhow it seems like a waste of time (submitting large graphs is slow as it is already).
I can of course deal with this in another PR but I'm curious if there are opinions about this / if this plugin is used elsewhere

**Comment by mrocklin** [comment]
The plugin is used only for this dashboard plot.  Removing or pausing it in this situation sounds good to me.

**Comment by jsignell** [comment]
I think it makes sense to disable it and show some explanatory message. I have been alarmed by a blank graph page before.

**Comment by mrocklin** [comment]
That sounds like a great idea to me.  If only we had a Bokeh expert around
....
