### ISSUE TITLE
Semaphores release automatically - refresh won't run

### ISSUE THREAD

**Issue by pvanderlinden** [dask/distributed#4057]
**What happened**:
Semaphores always automatically release after 40 seconds

```
Example output:
1597944899.78569 1
1597944899.7857327 0
1597944939.7501612 3
1597944939.75026 2
distributed.semaphore - WARNING - Tried to release semaphore but it was already released: name=database, lease_id=52a2ef49dbfa4fafb68d1118adfcb807. This can happen if the semaphore timed out before.
distributed.semaphore - WARNING - Tried to release semaphore but it was already released: name=database, lease_id=08821fab060c4d25b05209d5bfba6716. This can happen if the semaphore timed out before.
finished 0
finished 1
...
```

**What you expected to happen**:
Semaphore leases should be automatically refreshed.

**Minimal Complete Verifiable Example**:

```python
import dask.distributed as dd

import time


if __name__ == '__main__':

    client = dd.Client(processes=False, threads_per_worker=10)

    sem = dd.Semaphore(max_leases=2, name="database")

    def access_limited(val, sem):
        with sem:
            print(time.time(), val)
            # Interact with the DB
            time.sleep(60)
        print('finished', val)

    futures = client.map(access_limited, range(10), sem=sem)
    client.gather(futures)
    sem.close()
```

**Anything else we need to know?**:
Workaround would be appreciated!

**Environment**:

- Dask version: 2.22.0 & 2.23.0 tested
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by pvanderlinden** [comment]
The example is exactly a copy from the docs (adjusted to add the sleep and create a client). I also tried to make access_limited a asyncio coroutine, but that won't actually run.

**Comment by mrocklin** [comment]
Thanks for raising an issue @pvanderlinden 

cc'ing @fjetter and @lr4d who I think did most of the work here and may have thoughts.

**Comment by pvanderlinden** [comment]
Also more remarks: during a task, the ioloop is not running, which is the reason. Do I need to managed the ioloop myself if I want to use a semaphore in a task (just trying to figure out how they currently can be used for a workaround)?

**Comment by fjetter** [comment]
The behaviour you're describing is an expected state if you're executing a computation which holds the GIL but this is clearly not the case with the example (I can confirm the example on my end)

> during a task, the ioloop is not running, which is the reason. Do I need to managed the ioloop myself if I want to use a semaphore in a task (just trying to figure out how they currently can be used for a workaround)?

We do require an event loop to be active but there should not be a need to manage it yourself. this should be done by the client. I'll need to dig a bit deeper to determine the root cause. In the meantime, increasing the lease timeout should serve as a workaround to ensure the leases simply never time out (that's a protection for cases where workers die and cannot release the semaphore again). That's the configuration option `distributed.scheduler.locks.lease-timeout` which is, by default, set to 30s.

**Comment by fjetter** [comment]
The issue appears to be that the client-side refresh `PeriodicCallback` is never actually executed (it is scheduled but never executed)

https://github.com/dask/distributed/blob/6a32208717c04aa9ccb4defdf253b8a00cab32b7/distributed/semaphore.py#L367-L382

My suspicion is that in this example we're running workers in a threadpool. According to https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading "Almost all asyncio objects are not thread safe" and I assume this is then also true for the tornado PC and this is why the PC is never properly scheduled? If that's the case, I'd be surprised to see this only pop up now, though. @mrocklin has something like this ever occurred / is this a known issue?
