### ISSUE TITLE
KeyError: 'workers'

### ISSUE THREAD

**Issue by FredFLi** [dask/distributed#4065]
From the logs in cluster:

distributed.core - INFO - Starting established connection
**tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7efde043e378>, <Task finished coro=<BaseTCPListener._handle_stream() done, defined at /azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/distributed/comm/tcp.py:445> exception=KeyError('pickle-protocol',)>)**
Traceback (most recent call last):
  File "/azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/tornado/tcpserver.py", line 327, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/distributed/comm/tcp.py", line 457, in _handle_stream
    await self.on_connection(comm)
  File "/azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/distributed/comm/core.py", line 223, in on_connection
    comm.local_info, comm.remote_info
  File "/azureml-envs/azureml_7627c615978b72dc500c269fe7382a2f/lib/python3.6/site-packages/distributed/comm/core.py", line 138, in handshake_configuration
    "pickle-protocol": min(local["pickle-protocol"], remote["pickle-protocol"])
KeyError: 'pickle-protocol'
distributed.comm.tcp - INFO - Connection closed before handshake completed
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.0.0.5:8786 remote=tcp://10.0.0.5:39948>
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.0.0.4:36725', name: tcp://10.0.0.4:36725, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.0.0.4:36725

**What happened**:
Got the following errors when I try to view the widget after starting a azureml dask cluster.

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    916             method = get_real_method(obj, self.print_method)
    917             if method is not None:
--> 918                 method()
    919                 return True
    920 

~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\distributed\deploy\cluster.py in _ipython_display_(self, **kwargs)
    344                 self.dashboard_link
    345             )
--> 346         else:
    347             dashboard = "Not Available"
    348         return (

~\Desktop\projects\git_repos\dask-cloud-fli\dask_cloudprovider\providers\azure\azureml.py in _widget(self)
    845         jupyter = HTML(jupyter_link)
    846 
--> 847         status = HTML(self._widget_status(), layout=Layout(min_width="150px"))
    848 
    849         if self._supports_scaling:

~\Desktop\projects\git_repos\dask-cloud-fli\dask_cloudprovider\providers\azure\azureml.py in _widget_status(self)
    752     def _widget_status(self):
    753         ### reporting proper number of nodes vs workers in a multi-GPU worker scenario
--> 754         nodes = len(self.scheduler_info["workers"])
    755 
    756         if self.use_gpu:

KeyError: 'workers'

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

~\AppData\Local\Continuum\anaconda3\envs\daskaks\lib\site-packages\distributed\deploy\cluster.py in __repr__(self)
    372         return self.sync(self.__aexit__, typ, value, traceback)
    373 
--> 374     async def __aenter__(self):
    375         await self
    376         return self

KeyError: 'workers'

**What you expected to happen**:
Can see the widget without issue

**Comment by jrbourbeau** [comment]
Just checking in here, @FredFLi could you use the same version of dask and distributed everywhere and then try again

**Comment by FredFLi** [comment]
Thanks @mrocklin , @jrbourbeau.  Sure. Let me try that.

**Comment by FredFLi** [comment]
The issue was caused by version mismatch.

**Comment by jrbourbeau** [comment]
Glad to hear it's been resolved, thanks for following up @FredFLi
