### ISSUE TITLE
"Could not find data for" + "Recover missing" when nothing wrong has happened

### ISSUE THREAD

**Issue by frol** [dask/distributed#407]
I have seen the following messages quite often (they happen once every 30 minutes during intensive experimentation) on my little cluster and even on one single laptop hosting the scheduler, the worker, and the executing code:

```
distributed.worker - INFO - Deleted 19 keys
distributed.worker - INFO - Deleted 13 keys
distributed.worker - WARNING - Could not find data for ["('getitem-1c0318d594d052d0143baa68e871400b', 2)"]
distributed.scheduler - INFO - Recover missing ('apply-b83661773bb310a60dda6b52ca7094b3', 2)
distributed.worker - INFO - Deleted 16 keys
distributed.worker - WARNING - Could not find data for ["('getitem-1c0318d594d052d0143baa68e871400b', 1)"]
distributed.scheduler - INFO - Recover missing ('apply-b83661773bb310a60dda6b52ca7094b3', 1)
```

(I have a scheduler and a worker running on one terminal in background, so we can see the order of the messages and notice that the worker missed `getitem`, but the scheduler recovers `apply`. Isn't it weird?)

I'm sure neither the worker nor executor failed, but after a while, I start seeing these messages and eventually my computations just hang (0% CPU load, Bokeh status page reports that a few tasks are still waiting for something). If I interrupt my computations I see that it is just sitting waiting for some results:

```
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/executor.py", line 1054, in get
    results = self.gather(futures)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/executor.py", line 767, in gather
    return sync(self.loop, self._gather, futures, errors=errors)
  File "/mnt/storage/miniconda3//lib/python3.5/site-packages/distributed/utils.py", line 114, in sync
    e.wait(1000000)
  File "/mnt/storage/miniconda3//lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/mnt/storage/miniconda3//lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
```

My only guess at the moment is that it might be related to the workflow I have:

1. I often restart my Jupyter Notebook to start from scratch, and I also actively run code from the terminal in a batch processing mode.
2. My code crashes (just regular Python exceptions, not Segfaults) sometimes, so this may break some machinery on workers.

P.S. I have originally described this in #280, but it turned out to be a separate issue.

**Comment by frol** [comment]
@mrocklin I will take a look at #398. Thank you!

**Comment by mrocklin** [comment]
No guarantees on it working, but I do guarantee that it'll be easier to track down :)

**Comment by mrocklin** [comment]
Closing for now.  Please reopen if the problem persists.
