### ISSUE TITLE
client was defined in a different context

### ISSUE THREAD

**Issue by smst329** [dask/distributed#4086]
whether I just use a regular client, or I do asynchronous=True initialization, I get the error:
`<Token var=<ContextVar name='_current_client' default=None at 0x7f8589afacc0> at 0x7f85884a2fc0> was created in a different Context`

The call is what is causing the issue:

`ds = client.get_dataset(current_dataset)`

I am doing the calls within an async function. I use a lock so that there is only one call to retrieve a dataset and only one call to save a dataset at a time. As above, I have attempted both the regular client and client with asynchronous=True and changing the subsequent client api calls to await client...

Both methods cause the error. Even if I don't use the asynchronous method, normally, many libraries allow non-async blocking calls inside of an async function, it's just non-optimal. I would like to see the client methods either just work or a documented way of getting the context it needs and passing it as a parameter or mirror the common approach of passing the asyncio loop as one of the parameters. I did blindly initially try loop=my asyncio loop, but based on the documentation and source, the loop parameter looks like it is for a tornado loop. This is being run within a notebook on the notebook server but would eventually be moved to running in a regular interpreter. 

**Environment**:

I am running the official docker dask notebook server along with the docker scheduler and worker containers.

**Comment by smst329** [comment]
```
import pandas as pd
from distributed import Client
import dask.dataframe as dd

current_dataset = None
loop = asyncio.get_event_loop()

client = loop.run_until_complete(Client('<IP>', asynchronous=True))

async def set_up_dataframe(loop,client):
    print('ds setup started.')
    global current_dataset
    df = dd.from_pandas(pd.DataFrame(),1)
    current_dataset = str(uuid.uuid4())
    pair = {current_dataset:df}
    await client.publish_dataset(**pair)
    del(df)
    print('ds '+current_dataset+' created.')
loop.run_until_complete(set_up_dataframe(loop, client))


async def get_dataset(loop, client):
    global current_dataset
    print('attempting dataset retrieval of '+current_dataset)
    df = await client.get_dataset(current_dataset)
    print('ds retrieved.')
loop.run_until_complete(get_dataset(loop, client))
```

That is a small example of the issue. I would expect to have the ability to create a dataset in one function call, and then retrieve modify and re-publish in another.

**Comment by smst329** [comment]
Closing issue. Root caused found to be asyncio api changes in jupyter not dask.

**Comment by mrocklin** [comment]
Thanks for reporting the issue and for reporting the solution
