### ISSUE TITLE
Make dask-worker's --nprocs support negative values like joblib

### ISSUE THREAD

**Issue by drorspei** [dask/distributed#4088]
The joblib API allows giving negative `n_jobs` values, which is then interpreted as `n_cpus + 1 + n_jobs`. Can we have this api working for dask-worker's --nprocs argument?

Why is this useful? My current use case is having a network of machines, with varying numbers of cores, connected in a docker swarm, and my typical workload does well with nprocs=all-cpus and nthreads=1. Since the machines have varying numbers of cores, currently no fixed service configuration and container command can utilise exactly the total number of cores connected to the network at any given time. There are two modes for docker services: replicated - fixed number of containers, and global - one container per node. I don't want to use the replicated mode since then I'll always be limited by the number of replicas I set. So global is the way to go. With the requested feature, I could set nprocs=-1, and always have all of my cpus utilised. (Just to clarify, I'm running a docker service that runs the daskdev/dask image with the dask-worker command, and separately I run a single container that runs the dask-scheduler command)

If you like the idea, I can put up a pull request. I would also be thrilled to get advice on a better setup.

**Comment by mrocklin** [comment]
This makes sense to me.  A pull request would be welcome.
