### ISSUE TITLE
Getting length of dask dataframe is extremely slow

### ISSUE THREAD

**Issue by smst329** [dask/distributed#4102]
I can define a dataset like so,

ds = client.get_dataset('dataset')

It can be very small: length of 500

len(ds) is 5 to 8 seconds.
I can persist it it with client.persist or ds.persist, but len calls are still extremely slow 5~8 seconds. It's not just len calls, pretty much all of the methods for getting the length of a dataframe are extremely slow.

Compared with the 186 µs of pandas, that's not good. Now for a dataset this small I would just use pandas, the issue that I am seeing is though is that if I use dask on a dataset that doesn't scale with pandas, and use dask to filter that dataset down, I need the ability to control and ensure that computation is triggered creating the filtered dataset as I have defined, however once that work is done, I believe that I should be able to get the length of the result of that computation, i.e. the length of the filtered dataset quickly. I want to be able to get just length reported and sent over the wire, and if the number is acceptable, I may decide to download the entire dataset to the client.

On a different dataset, taking a few thousand data points and then filtering them down to a few hundred and getting the length was extremely slow (same problem). I believe I have tried just about all of the tricks whether its summing ds.map_partitions(len), or taking the shape of the index or the shape of the one of the columns or adding nan rows and non-nan rows, etc. Every method I've been able to dig up to get the length of a dataframe are slow and still remain slow after persist calls. The also remain slow when doing multiple calls after a persist. So if I get a length once and then ask for it again, it's no faster the second time. When filtering dataframes and creating new dataframes, that kind of computation is expected to take time. However, getting answer to the question of how much was just computed should be fast. If dask did the work, it should be able to quickly report it, especially for smaller datasets. Again, it becomes understandable once it has to request information from a number of distributed nodes holding pieces of the data. But when there is one worker, with a small dataset, it is still very slow.

The fact that lengths are reported slowly has two negative impacts, one is impeding quick iteration on prototyping new workflows with dask prior to scaling up and the other is when switching to pandas or numpy when appropriate is not a good experience if I cannot quickly quickly determine that the original dataset has been adequately filtered down to a reasonable subset. I think size/shape information and getting it quickly makes sense to optimize at multiple scales because it will impact other decisions made when creating workflows.

**Comment by TomAugspurger** [comment]
Can you provide a performance_report of your len calls https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports?

See https://github.com/dask/dask/issues/5633 for a general discussion about adding partition lengths to dataframe metadata.

**Comment by smst329** [comment]
Working on generating and reviewing performance reports on different datasets to see what lessons I can learn there and after my own review, I'll post them or report back here whether there is an undocumented lessons learned or the misunderstanding was on my part. I am new enough to dask that I can't resolve some of the trade offs under discussion for 5633 here. But I did find that illustrative. 

I'll post the report later, but there are a lot of tasks. If I take 4 500 item pandas dfs then call dask df from pandas df and concat them into one dask df, when I call length it turns into thousands and thousands of tasks. There is a fair amount writes happening as well as transfer, so I think the level of data copying is too much.

**Comment by smst329** [comment]
I think the issue can be definitively can be chalked up to repeated concat operations on a streaming dataset creating one partition per datapoint. I think occasional repartitions will solve. I'll also look into accessing the most recent underlying partition and adding data points directly to that. I really appreciated the tip on performance reports.
