### ISSUE TITLE
Worker clients don't respect timeout config settings

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#4114]
Clients created with `worker_client` or `get_client` don't respect the timeout settings (e.g. `distributed.comm.timeouts.connect`. The timeout is available to set programmatically, but defaults to `3` rather than falling back to the config file. I think this should be as simple as replacing `timeout=3` with `timeout=None` throughout that code path.

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/4146
