### ISSUE TITLE
GPU utilization plot reports repeated GPUs

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4117]
@quasiben and I were playing around with his 2-gpu system, and were surprised to see four GPUs in his dashboard plots.  I suspect that each worker was separately reporting the metrics for both GPUs on the system.

The relevant code for this is here:

https://github.com/dask/distributed/blob/ecaf14097f5e69e5b884e9c87b708c85d181a9ef/distributed/diagnostics/nvml.py#L6-L12

Perhaps pynvml does not respect `CUDA_VISIBLE_DEVICES`?  Should we filter this on our own?

cc @rjzamora @jacobtomlinson

**Comment by trivialfis** [comment]
Hi @mrocklin , I'm using `LocalCUDACluster` from `dask-cuda` and couldn't find the utilization information on daskboard.  Is there any document on how to enable it?

**Comment by quasiben** [comment]
@trivialfis you may need to upgrade the [dask lab extension](https://github.com/dask/dask-labextension) if you are using jupyter lab (recommended). 

<img width="423" alt="Screen Shot 2020-09-27 at 9 23 01 AM" src="https://user-images.githubusercontent.com/1403768/94365969-0ba58c00-00a3-11eb-8be4-65e4ee44b127.png">

You can also find it directly on the dashboard at `:8787/individual-gpu-utilization`

**Comment by trivialfis** [comment]
@quasiben Thanks for the reply.  The direct way works perfectly for me.

@mrocklin 

> Perhaps pynvml does not respect CUDA_VISIBLE_DEVICES?

If memory serves, you are right that nvml doesn't respect `CUDA_VISIBLE_DEVICES`, so pynvml won't be affected by this env.

**Comment by trivialfis** [comment]
Related https://github.com/dask/distributed/issues/3808 .

**Comment by jacobtomlinson** [comment]
I think this has been resolved by #3810
