### ISSUE TITLE
dask-worker not found after pip install of complete

### ISSUE THREAD

**Issue by blazespinnaker** [dask/distributed#4129]
**What happened**:

ran:
 20  python3 -m pip install "dask[complete]"
   21  dask-worker

and got

Command 'dask-worker' not found, but can be installed with:

sudo apt install python3-distributed

**What you expected to happen**:
dask-worker to execute

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

workaround was to exit shell and ssh back into node.

**Environment**:

Ubuntu 18.04.5

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by mrocklin** [comment]
This seems like a problem with however it is that you're installing
things.  I'm not sure how much we can help here.  I would check other
things like your PATH, other python libraries that you've installed, and so
on.

Given how you're installing with python3 -m pip you might consider using
that same approach with dask

python3 -m distributed.cli.dask_worker SCHEDULER_ADDRESS

**Comment by blazespinnaker** [comment]
FWIW, it was a fresh azure node using vanilla ubuntu image they list at the top.  I installed pip via apt update / apt install python3-pip.   Nothing else was done.  This was the 6th node I installed and encountered this issue, so I'm pretty confident I'm not missing anything here.

**Comment by blazespinnaker** [comment]
python3 -m distributed.cli.dask_worker tcp://192.168.1.66:8786 worked.  I guess pip install dask[complete] sets up the command line for dask-scheduler but not dask-worker unless you re-enter the shell.

**Comment by blazespinnaker** [comment]
Hmmm, looks like the pip install sets up the local bin.  I see now that it does warn about this in the pip install though.
