### ISSUE TITLE
Dask serialization doesn't respect subclass of array

### ISSUE THREAD

**Issue by cyrilpic** [dask/distributed#4136]
I have been using Dask to perform parallel computation for optimization algorithms. I use a custom subclass of an `array.array` to represent the solutions and store additional attributes. I then send a list of those to a processing function through dask bag.

**What happened**:

The script fails with a `AttributeError: 'array.array' object has no attribute 'multiplier'` exception. The type of the array in the processing function is `array.array` although the object sent is of type `CustomArray`.

It looks like the custom array is processed by `_serialize_array` and `_deserialize_array`, which discards the custom type.

**What you expected to happen**:

Ideally, dask should figure out how to correctly serialize such objects :) And from the documentation it's not so clear to me how to tell dask to use the pickle serializer for this object.

**Minimal Complete Verifiable Example**:

```python
from array import array

from dask.distributed import Client, LocalCluster

import dask.bag as db


class CustomArray(array):
    def __init__(self, typecode, seq=(), attrs=None, *arg, **kwargs):
        super(CustomArray, self).__init__()
        for k, v in attrs.items():
            setattr(self, k, v)

    def __deepcopy__(self, memo):
        cls = self.__class__
        copy_ = cls.__new__(cls, self.typecode, self)
        memo[id(self)] = copy_
        copy_.__dict__.update(copy.deepcopy(self.__dict__, memo))
        return copy_

    def __reduce__(self):
        return (self.__class__, (list(self),), self.__dict__)


def process(x):
    # do stuff
    print(type(x))
    return x[0]*x.multiplier


if __name__ == '__main__':

    cluster = LocalCluster()

    i1 = CustomArray('d', [10., 10., 20.], attrs={'multiplier': 2})
    i2 = CustomArray('d', [1., 2., 2.], attrs={'multiplier': 5})

    with Client(cluster) as client:
        out = db.from_sequence([i1, i2]).map(process).compute()

    print(out)
```

**Environment**:

- Dask version: 2.27.0
- Python version: 3.7.7
- Operating System: Mac OS 10.15.6
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
I think the issue here is a spelling mistake `multipler` -> `multiplier`

**Comment by cyrilpic** [comment]
Sorry for the spelling mistake in my minimal example. I've update the example.

Notice that the error is `AttributeError: 'array.array' object has no attribute 'multiplier'` and not `AttributeError: 'CustomArray' object has no attribute 'multiplier'` like one would expect if it was only for the spelling mistake.

**Comment by quasiben** [comment]
Ah, sorry about that @cyrilpic .  I think in this case you may need to register a custom serializer.   I thought we might be able to use `register_generic`

```python
from distributed.protocol import register_generic

register_generic(CustomArray)
```

But this will fail, I think do to array instance checking:

```python
In [5]: isinstance(i1, array)
Out[5]: True
```

And the serializer already defined https://github.com/dask/distributed/blob/b2f594e69751e0733ac595026e04181c55119ae9/distributed/protocol/serialize.py#L628-L633

We have documentation on building [custom serialization](https://distributed.dask.org/en/latest/serialization.html) which I think should do the trick.  cc @jakirkham in case he has thoughts here

**Comment by jakirkham** [comment]
The `register_generic` approach would work if `CustomArray` contained an `array` instance. Unfortunately it won't work if it subclasses an `array`. Though it doesn't look too difficult to restructure this class to do that if we wanted that option.

Implementing custom serialization is probably the way to go. This involves implementing a [serialization function]( https://github.com/dask/distributed/blob/b2f594e69751e0733ac595026e04181c55119ae9/distributed/protocol/serialize.py#L628-L632 ) and a [deserialization function]( https://github.com/dask/distributed/blob/b2f594e69751e0733ac595026e04181c55119ae9/distributed/protocol/serialize.py#L635-L644 ), both of which are registered to Dask. Would recommend either including those functions or `import`ing them in the same module where `CustomArray` is implemented. Also would make sure this gets `import`ed on all `Worker`s so that Dask knows how to serialize `CustomArray`.

**Comment by cyrilpic** [comment]
Thank you, I got it working with the following:

```python
@dask_serialize.register(CustomArray)
def _serialize_ca(obj): 
    header = {"typecode": obj.typecode, "writeable": (None,), "attrs": pickle.dumps(obj.__dict__)}
    frames = [memoryview(obj)]
    return header, frames


@dask_deserialize.register(CustomArray)
def _deserialize_ca(header, frames):
    a = CustomArray(header["typecode"])
    for f in map(memoryview, frames):
        try:
            f = f.cast("B")
        except TypeError:
            f = f.tobytes()
        a.frombytes(f)
    a.__dict__ = pickle.loads(header["attrs"])
    return a
```

But I had to put everything in a separate module in order for Dask workers to know about it.

I know it's a bit a special use case (but some libraries use it and cannot be refactored so easily), but I'm still a bit surprised that Dask "secretly" replaces a CustomArray with an array. Maybe it would be worth dropping a line about that in the documentation ?

**Comment by jakirkham** [comment]
Glad you got it working! 😄

Yeah Dask just does an `isinstance` check when serializing an object. So if the object is a subclass (in this case of `array`), it will likely be picked up by its parent class. We do this with all of the builtins and also other objects (like NumPy arrays).

**Comment by jakirkham** [comment]
Going to close as this seems to have been resolved, but happy to reopen if there is more needed here

**Comment by emmaai** [comment]
The issue seems coming back in `>=2014.11.0`
