### ISSUE TITLE
Worker should be able to respond to scheduler when running long GIL functions

### ISSUE THREAD

**Issue by saeedshojaee** [dask/distributed#4150]
We are using dask for distributing optimization functions. They are usually long running GIL functions. Since workers are unresponsive when solving tasks, scheduler fails to change the cluster size.
We would like the worker to be able to respond to scheduler, and allow the queued task to be redistributed.

**Comment by quasiben** [comment]
@saeedshojaee could you provide more context for this issue.  Do you mean heartbeats ? Other Diagnostics ? Was there a particular problem you are currently trying to resolve ?

**Comment by quasiben** [comment]
@saeedshojaee any additional comments ?

**Comment by jrbourbeau** [comment]
Closing due to lack of response, feel free to re-open if you would like to continue
