### ISSUE TITLE
Future stays in pending state after worker crashed

### ISSUE THREAD

**Issue by jeanp413** [dask/distributed#4152]
Hi, I'm submitting cython functions to specific dask workers but if the worker doing the computation crashes the returned future stays in `'pending'` state.
```
future = client.submit(cython_function, workers=[worker], args...)

[<Future: pending, key: runQuery-86aa22f1b010210c2144b3c80b747089>]
```
This is similar to this issue I found https://github.com/dask/distributed/issues/1110#issuecomment-305446145 that says the task is waiting for other workers to claim it but that won't happen as it's submitted to a specific worker. 
I expect the future to fail, is there a way to know that? Currently if I call `client.gather()` with that future o use `future.result()`  it will block indefinitely.

Thanks.

**Comment by mrocklin** [comment]
In this case it's still waiting for a worker to arrive that meets
conditions.  For example, even though your worker crashed, it might be
brought up again.  In that case Dask would want to run the task there again.

**Comment by felipeblazing** [comment]
Is there a way for us to be able to detect that the worker did indeed crash during this task execution given that this task is no longer a "valid" one in our case.  The worker won't be coming back and we want to be able to say this failed user.

**Comment by mrocklin** [comment]
A quick and dirty way to get what I think you want is to set the
distributed.scheduler.allowed-failures config value to 1.  I suspect that
that will give you the behavior that you're after.

**Comment by jeanp413** [comment]
> A quick and dirty way to get what I think you want is to set the distributed.scheduler.allowed-failures config value to 1. I suspect that that will give you the behavior that you're after.

I tried it out using `export DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES=1` but it didn't work, the future stays in `pending` state

**Comment by mrocklin** [comment]
Ah sorry, maybe try zero?

For context, this value says that if a task is on a worker when it goes
down, try retrying that task N times before calling it a failure.  In this
case it will be marked with the KilledWorker exception.

**Comment by jeanp413** [comment]
Awesome, that worked thanks.
