### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#4168]
Opening this issue to track Python 3.9 compatibility issues.

**Comment by jcrist** [comment]
Currently `distributed` fails to start worker processes on Python 3.9 with a local cluster (at least on osx). I see 

```python
In [3]: client = Client()
Task exception was never retrieved
future: <Task finished name='Task-396' coro=<_wrap_awaitable() done, defined at /opt/miniconda3/envs/prefect39/lib/python3.9/asyncio/tasks.py:678> exception=ImportError("cannot import name 'Popen' from partially initialized module 'multiprocessing.popen_spawn_posix' (most likely due to a circular import) (/opt/miniconda3/envs/prefect39/lib/python3.9/multiprocessing/popen_spawn_posix.py)")>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/asyncio/tasks.py", line 685, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/nanny.py", line 575, in start
    await self.process.start()
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/miniconda3/envs/prefect39/lib/python3.9/multiprocessing/context.py", line 283, in _Popen
    from .popen_spawn_posix import Popen
ImportError: cannot import name 'Popen' from partially initialized module 'multiprocessing.popen_spawn_posix' (most likely due to a circular import) (/opt/miniconda3/envs/prefect39/lib/python3.9/multiprocessing/popen_spawn_posix.py)
```

**Comment by madkinsz** [comment]
I get the same error in the python3.9 docker image (Debain 10 - Linux version 4.19.76) so I presume this is not limited to OSX

**Comment by mrocklin** [comment]
cc @itamarst this seems like something that might be up your alley

**Comment by itamarst** [comment]
Always impressed at your nerd sniping skills :grin:

**Comment by mrocklin** [comment]
I think that my main value to society today is indexing people by technical interest

**Comment by mrocklin** [comment]
Also, thank you for taking a look, I appreciate it

(I'm interpretting your :grin: as enthusiasm)

**Comment by itamarst** [comment]
A workaround:

```python
>>> import multiprocessing.popen_spawn_posix
>>> from distributed import Client
>>> Client()
<Client: 'tcp://127.0.0.1:41565' processes=4 threads=4, memory=8.26 GB>
```

No idea what's going on yet, but I suspect it's a bug in Python.

**Comment by mrocklin** [comment]
Thank you for investigating this @itamarst

**Comment by mrocklin** [comment]
Short term, would a solution be to add that import to the appropriate file within distributed?

**Comment by itamarst** [comment]
I would guess so, yes (on POSIX platforms, anyway).

**Comment by lingfeiwang** [comment]
And a similar command line workaround:

`dask-worker --preload-nanny multiprocessing.popen_spawn_posix`

> A workaround:
> 
> ```python
> >>> import multiprocessing.popen_spawn_posix
> >>> from distributed import Client
> >>> Client()
> <Client: 'tcp://127.0.0.1:41565' processes=4 threads=4, memory=8.26 GB>
> ```

**Comment by mrocklin** [comment]
Would you be interested in opening a PR Itamar?

Nice solution Lingfei Wang!

**Comment by stonebig** [comment]
hi all,

The workaround proposed doesn't seem to work on Windows / Python-3.9.1
Any hope on this ? any issue/fix identfied for next Python-3.9.2 ?

![image](https://user-images.githubusercontent.com/4312421/102717793-ee204100-42e4-11eb-8109-07d5cd8c6fab.png)

**Comment by stonebig** [comment]
hum, maybe it's  this cpython issue  https://bugs.python.org/issue35943

**Comment by SunMaungOo** [comment]
For Windows workaround

```python
>>> from dask.distributed import Client
>>> import multiprocessing.popen_spawn_win32
>>> Client()
<Client: 'tcp://127.0.0.1:7182' processes=4 threads=8, memory=8.54 GB>

```

**Comment by stonebig** [comment]
Thanks a lot @SunMaungOo , it works nicely.

**Comment by yannikschaelte** [comment]
> A workaround:
> 
> ```python
> >>> import multiprocessing.popen_spawn_posix
> >>> from distributed import Client
> >>> Client()
> <Client: 'tcp://127.0.0.1:41565' processes=4 threads=4, memory=8.26 GB>
> ```
> 
> No idea what's going on yet, but I suspect it's a bug in Python.

Thanks @itamarst for the patch! Also solved my issue of `Client()` just getting stuck without any output on python 3.9.

**Comment by mr-september** [comment]
> ```python
> >>> import multiprocessing.popen_spawn_posix
> ```

PyCharm gives me an error: `No module named 'popen_spawn_posix'`

Do I need to `pip install` something? Sorry very new to python.

**Comment by crusaderky** [comment]
> > A workaround:
> > ```python
> > >>> import multiprocessing.popen_spawn_posix
> > >>> from distributed import Client
> > >>> Client()
> > <Client: 'tcp://127.0.0.1:41565' processes=4 threads=4, memory=8.26 GB>
> > ```
> > 
> > 
> > No idea what's going on yet, but I suspect it's a bug in Python.
> 
> PyCharm gives me an error: `No module named 'popen_spawn_posix'`
> 
> Do I need to `pip install` something? Sorry very new to python.

What's your version of Python?

**Comment by crusaderky** [comment]
@mr-september also, in windows you have to ``import multiprocessing.popen_spawn_win32`` instead

**Comment by mr-september** [comment]
> What's your version of Python?

3.9, and I'm on Ubuntu.

but sorry I don't think I had an issue afterall, I just ignored  PyCharm's warning, things seems to have worked well.

**Comment by pitrou** [comment]
I think this is definitely a CPython regression. Taking this upstream.

**Comment by pitrou** [comment]
https://bugs.python.org/issue43517

**Comment by mrocklin** [comment]
Thanks @pitrou
