### ISSUE TITLE
Passing "zero" to dask-worker cli fails

### ISSUE THREAD

**Issue by marwan116** [dask/distributed#4171]
**What happened**:

I am looking at the dask-worker cli definition, specifically at the how the memory-limit is specified.

As noted here https://github.com/dask/distributed/blob/master/distributed/cli/dask_worker.py#L149

```
@click.option(
    "--memory-limit",
    default="auto",
    show_default=True,
    help="Bytes of memory per process that the worker can use. "
    "This can be an integer (bytes), "
    "float (fraction of total system memory), "
    "string (like 5GB or 5000M), "
    "'auto', or zero for no memory management",
)
```

so ideally I would want to pass the option "zero for no memory management"

this looks like the function that is used to parse the memory limit specification:
https://github.com/dask/distributed/blob/dcb46d07318282d8a8976aadb0e4003144a42ae7/distributed/worker.py#L3128
and if I pass `"--memory-limit 'zero' "`  it will throw the following error 

```
  File "/usr/local/lib/python3.8/site-packages/distributed/worker.py", line 3199, in parse_memory_limit
    memory_limit = parse_bytes(memory_limit)
  File "/usr/local/lib/python3.8/site-packages/dask/utils.py", line 1233, in parse_bytes
    raise ValueError("Could not interpret '%s' as a byte unit" % suffix) from e
ValueError: Could not interpret 'zero' as a byte unit
```

what am I missing here - what value should I pass to make opt for "no limit" i.e. "no memory management" - is it the integer 0 instead?

**Comment by marwan116** [comment]
as a follow up - it seems to me that passing the integer 0 is what is required for no memory management - but it would be nice to get a confirmation and if the documentation is clarified

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @marwan116. As you've found `dask-worker --memory-limit 0` should be used to disable memory management. Do you have interest in clarifying this in the documentation?

**Comment by marwan116** [comment]
@jrbourbeau - thanks for confirming, please see the linked PR for a proposed update to the memory-limit options' documentation.

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/4172
