### ISSUE TITLE
Does the address attribute support a cluster instance

### ISSUE THREAD

**Issue by jpujari-ctx** [dask/distributed#4179]
https://github.com/dask/distributed/blob/18fff8b0ca0297e100695519931c78e579cb55a6/distributed/client.py#L662

The code referenced above throws an error saying 

```
 "Scheduler address must be a string or a Cluster instance, got {}".format(
                    type(address)
```

But the elif is only checking against the str class and no checks against a cluster class.

**Comment by jcrist** [comment]
We don't enforce a cluster base class, `Cluster`-like objects passed in as `address` should have a `scheduler_address` attribute, which is pulled in the check above this one:

https://github.com/dask/distributed/blob/18fff8b0ca0297e100695519931c78e579cb55a6/distributed/client.py#L655

**Comment by jpujari-ctx** [comment]
> We don't enforce a cluster base class, `Cluster`-like objects passed in as `address` should have a `scheduler_address` attribute, which is pulled in the check above this one:
> 
> https://github.com/dask/distributed/blob/18fff8b0ca0297e100695519931c78e579cb55a6/distributed/client.py#L655

Thanks, it makes sense now
