### ISSUE TITLE
Task Stream Empty in Dask Performance Report

### ISSUE THREAD

**Issue by blchu** [dask/distributed#4189]
**What happened**:

When attempting to profile via `performance_report`, the resulting HTML file has an empty graph for the task stream tab.
The graph is similarly empty when trying to capture the task stream through `get_task_stream`.

**What you expected to happen**:

Task stream graph should have been populated in the recorded HTML file.

**Minimal Complete Verifiable Example**:

```python
import cudf, dask_cudf
from dask.distributed import Client, performance_report
from dask_cuda import LocalCUDACluster

if __name__ == '__main__':

    cluster = LocalCUDACluster()
    client = Client(cluster)

    with performance_report(filename='debug_task_stream.html'):
        s = cudf.Series([i for i in range(1000000)])
        ds = dask_cudf.from_cudf(s, npartitions=2)
        ds.cumsum().compute()
```

**Anything else we need to know?**:

This may be related to the issue in https://github.com/rapidsai/tpcx-bb/issues/116

**Environment**:

- Dask version: 2.24.0, 2.30.0 (tested both versions)
- Python version: 3.8.5
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
This may be due to a Bokeh issue.  I think that it was resolved in master
and may be fixed in the next bokeh release.  In the meantime you might want
to pin to an older version.  cc @jsignell for verification

**Comment by jrbourbeau** [comment]
@blchu there was an issue in bokeh that caused the task stream to stop rendering (xref https://github.com/dask/distributed/issues/4161). Upgrading to the latest release (`bokeh==2.2.3`) should fix the issue

**Comment by jsignell** [comment]
Right or downgrading to bokeh < 2.2
