### ISSUE TITLE
ImportError: cannot import name local

### ISSUE THREAD

**Issue by wsf1990** [dask/distributed#420]
when I use df.head(),
it show me this:
```
ImportError: cannot import name local
```
What cause this error? Dose I need install some other package?

**Comment by mrocklin** [comment]
Boto3 recently released an update with breaking changes.  This can be resolved by updating the `s3fs` package from master.

    pip install git+https://github.com/dask/s3fs --upgrade

This is unfortunately necessary even if you're not using s3 for anything.  This will be resolved in the next release, which will hopefully be out within a week.

**Comment by wsf1990** [comment]
OK,got it ! thanks!
