### ISSUE TITLE
Enabling discussions

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/distributed#4207]
If possible, it would be great to have "Discussions" tab for clarifications/open-ended questions (https://github.community/t/can-one-apply-for-github-discussions-beta/121120/3).

**Comment by mrocklin** [comment]
Sure!  We actually discussed this last month in our meeting, got access to the beta, but never actually set it up.  I've gone ahead and done this.  Let's see how well it works.

Thanks for the reminder @SultanOrazbayev !
