### ISSUE TITLE
OpenCV types can't be serialized

### ISSUE THREAD

**Issue by MaxBareiss** [dask/distributed#4210]
I can't serialize custom objects from OpenCV (I haven't tested other libraries). The example `Human` type works fine, but one from OpenCV doesn't. The custom serialization/deserialization works if I just do the KeyPoint object, but if it's in a list or tuple it causes problems. Best as I can tell, there's some logic to tell whether to use the `dask` or the `pickle` serializer. This logic works when the actual thing I'm trying to serialize is the custom object, but if the custom object is inside some tree of simple python objects the dask encoder gives up with a NotImplementedError and it switches over to the pickle serializer, which doesn't support custom serdes.

This has the effect of making the custom serdes code a whole lot less powerful.

**What happened**:

```
distributed.protocol.pickle - INFO - Failed to serialize ([], <KeyPoint 0x7fafc435dfc0>, <KeyPoint 0x7fafc421c2a0>). Exception: cannot pickle 'cv2.KeyPoint' object
Traceback (most recent call last):
  File "serial_test.py", line 46, in <module>
    deserialize(*serialize(data))
  File "/opt/anaconda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/opt/anaconda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 82, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type tuple.
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 41, in dumps
    result = pickle.dumps(x, **dump_kwargs)
TypeError: cannot pickle 'cv2.KeyPoint' object
```

**What you expected to happen**:

A lack of errors in my example code

**Minimal Complete Verifiable Example**:

```python
from typing import *
from dask.distributed import Client, progress, as_completed
from distributed.protocol import dask_serialize, dask_deserialize, serialize,deserialize
import cv2
import msgpack

class Human:
    def __init__(self, name):
        self.name = name

from distributed.protocol import dask_serialize, dask_deserialize

@dask_serialize.register(Human)
def _serialize(human: Human) -> Tuple[Dict, List[bytes]]:
    header = {}
    frames = [human.name.encode()]
    return header, frames

@dask_deserialize.register(Human)
def _deserialize(header: Dict, frames: List[bytes]) -> Human:
    return Human(frames[0].decode())

@dask_serialize.register(cv2.KeyPoint)
def _serialize_KP(kp: cv2.KeyPoint) -> Tuple[Dict, List[bytes]]:
    print("***** SERIALIZE")
    header = {}
    frames = [
        msgpack.packb(dict(x=kp.pt[0], y=kp.pt[1], size=kp.size, angle=kp.angle, response=kp.response, octave=kp.octave,
                           class_id=kp.class_id))]
    return header, frames


@dask_deserialize.register(cv2.KeyPoint)
def _deserialize_KP(header: Dict, frames: List[bytes]) -> cv2.KeyPoint:
    data = msgpack.unpackb(frames[0])
    return cv2.KeyPoint(data['x'], data['y'], data['size'], data['angle'], data['response'], data['octave'],
                        data['class_id'])


if __name__ == "__main__":
    #client = Client(n_workers=12, threads_per_worker=1,serializers=['dask'],deserializers=['dask'])

    data = (list(),Human("Alice"),Human("Bob"))
    #data = (list(),cv2.KeyPoint(),cv2.KeyPoint())

    deserialize(*serialize(data))
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.20.0 / 2.20.0
- Python version: 3.8.3 / 3.6.10
- Operating System: Arch(conda) / Windows10(conda)
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment]
Before looking at custom dask serialization I recommend looking at cloudpickle.  Are your objects cloudpickleable?

```python
>>> import cloudpickle
>>> b = cloudpickle.dumps(my_obj)
>>> cloudpickle.loads(b)
```

If not, you might consider adding support in Cloudpickle, or maybe raising this at the OpenCV library asking them to make their objects serializable with normal Python routines, like `__setstate__/__getstate__` or `__reduce__`

**Comment by mrocklin** [comment]
Closing due to lack of response.  If there is an update here we'll be happy to reopen.
