### ISSUE TITLE
'SLURMCluster' has no attribute "start_workers"

### ISSUE THREAD

**Issue by briannghiem** [dask/distributed#4223]
I'm running into an issue with deploying dask-jobqueue on an HPC (SLURM). I'm able to create a cluster object, although its start_workers() method seems to be missing. Reading through similar issues that have been raised in the past, the solution was usually to ensure that the dask, dask-distributed, and dask-jobqueue versions were compatible/up-to-date; however, still no luck after updating them.

**Minimal Complete Verifiable Example**:

```python
#test_dask.py
from dask_jobqueue import SLURMCluster
from dask.distributed import Client

cluster = SLURMCluster(cores = 3, memory = "3GB") #example of requested resources
cluster.start_workers(2) #error occurs here
client = Client(cluster)
```

**Error Message**:
Traceback (most recent call last):  
  File "test_dask.py", line 5, in <module>  
    cluster.start_workers(2)  
AttributeError: 'SLURMCluster' object has no attribute 'start_workers'

**Environment**:

- dask: v 2.30.0
- dask-distributed: v 2.30.0
- dask-jobqueue: v 0.7.1
- Python version: 3.7.9
- Operating System: Linux (Slurm HPC)
- Install method: pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @briannghiem. Looking at the [Dask-Jobqueue release notes](https://jobqueue.dask.org/en/latest/changelog.html), it looks like `.start_worker` was removed in favor of `.scale` in 0.7.0.

**Comment by briannghiem** [comment]
Good to know, `.scale` works, thank you! I had been following an example in the Dask-jobqueue 0.7.1 Documentation (section 3.7.6, page 18), although I notice now that this is the only appearance of `.start_worker` and that everywhere else `.scale` is used.

**Comment by jrbourbeau** [comment]
Awesome, glad to hear `.scale` works!

It'd be good to update any example in the docs that uses `.start_worker`, though after searching through the docs the only occurrence of `.start_worker` I found was in the changelog. Perhaps you're looking at a slightly outdated version of the docs?

**Comment by briannghiem** [comment]
Ya that's probably the case. I'll go ahead and close this issue.
