### ISSUE TITLE
Actors on same worker cause deadlock

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#4224]
Consider
```python
client = dask.distributed.Client()

class Minimal:
    
    def thetime(self):
        import time
        return time.time()

class UsesMinimal():
     
     def getthetime(self, ac):
         return ac.thetime().result()
```

The following works
```python
ac = client.submit(Minimal, actor=True, workers=["127.0.0.1:61047"]).result()
ac2 = client.submit(UsesMinimal, actor=True, workers=['tcp://127.0.0.1:61046']).result()
ac2.getthetime(ac).result()
```

but if they are on the same worker
```python
ac2 = client.submit(UsesMinimal, actor=True, workers=['tcp://127.0.0.1:61047']).result()
ac2.getthetime(ac).result()
```
... deadlock

- Dask version: master (dask/distributed)
- Python version: 3.7
- Operating System: osx
- Install method (conda, pip, source): source

**Comment by mrocklin** [comment]
Actors use the standard thread pool used by default.  If that worker has
only one thread then one actor will be waiting for the other to finish.  In
the actor-calling-actor state we probably want to secede/rejoin around the
call.

**Comment by martindurant** [comment]
Would you think it better to phrase this in async style? I wasn't sure how to do that - `return await ac.thetime()` ?

**Comment by martindurant** [comment]
I tried the following
```
class UsesMinimal():
    def __init__(self):
        try:
            dask.distribted.get_worker()
            self.worker = True
        except:
            self.worker = False

    def getthetime(self, ac):
        if self.worker:
            dask.distributed.secede()
        r = ac.thetime().result()
        if self.worker:
            dask.distributed.rejoin()
        return r
```
and still deadlocks.

**Comment by martindurant** [comment]
This works
```python
class Minimal:

    async def thetime(self):
        import time
        return time.time()

class UsesMinimal():

    async def getthetime(self, ac):
        import time
        t0 = time.time()
        return await ac.thetime() - t0

ac = client.submit(Minimal, actor=True).result()
ac2 = client.submit(UsesMinimal, actor=True).result()
%time ac2.getthetime(ac).result()
CPU times: user 2.99 ms, sys: 1.16 ms, total: 4.15 ms
Wall time: 4.7 ms
0.0005402565002441406
```

(0.54ms latency to call the actor from an actor on the same worker and wait for the result)

**Comment by mrocklin** [comment]
Async will definitely avoid the deadlock.  If same-worker actors are going to be common then this is probably something that we could special-case pretty easily and get down to normal Python speeds.

This would probably also avoid the deadlock, because you could just call the object directly in the same thread.
