### ISSUE TITLE
ENH: Add client.unregister_worker_plugin 

### ISSUE THREAD

**Issue by jsignell** [dask/distributed#4237]
The `Scheduler` class has `add_plugin` and `remove_plugin` methods for `SchedulerPlugin`s. But for worker plugins there is only `client.register_worker_plugin`. I think it could be useful to add a `client.unregister_worker_plugin`. 

In practice, I have found myself wanting this when I have accidentally created a broken plugin and then need to restart my cluster to get rid of it. It could also be useful if you want to overwrite a plugin with a new one that has the same name.

The argument to `client.unregister_worker_plugins` could be the plugin name.

**Comment by mrocklin** [comment]
Sounds good to me

**Comment by ncclementi** [comment]
Just a heads up, I'll be working on this one.
