### ISSUE TITLE
dask-worker doc might need an update

### ISSUE THREAD

**Issue by Timost** [dask/distributed#4244]
Hi,
First of all thank you for the dask ecosystem :heart: !

I've been browsing through the distributed doc and I think the worker doc at https://distributed.dask.org/en/latest/worker.html might need an update.

For example the shown `dask-worker` cli options aren't the same as what I get on the latest distributed release (`2.30.1` at the moment). Also things like dask-worker diagnostic dashboard aren't mentioned.
I'm willing to update the doc, I'm just not sure if leaving out many options of the dask-worker cli was intentional (to keep things simple).

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @Timost! The `dask-worker` cli options are indeed out of date and this is not intentional. In the documentation for `dask/dask` we use the [sphinx-click](https://github.com/click-contrib/sphinx-click) to render CLI options directly from the corresponding click command (see https://docs.dask.org/en/latest/setup/cli.html#cli-options), which ensures things are kept up to date. Do you have an interest in doing something similar here?

**Comment by mrocklin** [comment]
I'm inclined to start to retire docs in distributed when there are
equivalent docs in dask/dask.  The traffic to that page is an order of
magnitude higher.  Maybe instead we should start to redirect to those pages
and move over whatever content is missing instead?

**Comment by Timost** [comment]
As a dask user, I know that I sometime get confused between the different docs domain:
- docs.dask.org
- distributed.dask.org
- kubernetes.dask.org
- etc...
This was especially the case when I was beginning with dask. So I think I would prefer it if it would be more centralized, although I'm not aware of what this would imply from a technical standpoint.

**Comment by jrbourbeau** [comment]
In general I agree moving/redirecting content to docs.dask.org is best when duplicate content exists. In this particular instance a good first step would be to remove the content on the `dask-worker` CLI options here (on distributed.dask.org) and instead link to https://docs.dask.org/en/latest/setup/cli.html#dask-worker

> although I'm not aware of what this would imply from a technical standpoint

There is some code in `docs/source/conf.py` for redirecting existing link on distributed.dask.org to new locations. To see an example of this, in https://github.com/dask/distributed/pull/2936 we updated the setup docs on distributed.dask.org to point to the setup docs on docs.dask.org

**Comment by Timost** [comment]
> In this particular instance a good first step would be to remove the content on the dask-worker CLI options here (on distributed.dask.org) and instead link to https://docs.dask.org/en/latest/setup/cli.html#dask-worker

Ok I've taken a look at #2936 and also dask/dask#4813. I'll open a PR with the changes.
