### ISSUE TITLE
Task ordering for rapidly submitted tasks

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4246]
Generally Dask prefers computations which were submitted early. However, tasks which are submitted in rapid succession (i.e. within the `fifo_timeout` limit) are actually run in a last-in-first-out order (xref https://github.com/dask/distributed/pull/1828). I was wondering what the reasoning is for adopting a LIFO policy within small time windows, while having a FIFO policy over larger time windows? Specifically: Is there a downside to changing the policy to FIFO within small time windows?

**Comment by mrocklin** [comment]
I don't fully recall, but generally LIFO is more like depth first search, which generally results in better memory use.  This is a general principle though, and may not apply all the time.
