### ISSUE TITLE
Replacing task stream with large graphs

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4260]
The task stream is a well loved plot that stops making sense at a certain scale.  Here is [an example](https://gistcdn.githack.com/mrocklin/fb2406e1740590c5a481485f08411bf1/raw/8abb118514db0636a72ec4c31c85123b7859e036/gwas-height-performance-report-fast.html) (20MB file, image below)

![image](https://user-images.githubusercontent.com/306380/99828703-27ac3380-2b10-11eb-8278-5a3bd40cfdc8.png)

It would be nice to find a set of charts that could replace this chart at larger scales.  To that end I encourage us to think about what questions we seek to answer when we look at these charts.  We might then be able to make different charts that answer these questions with more aggregated data.  I would love some thoughts below.  I'll start with a few.

**Comment by mrocklin** [comment]
Often I look for the relative proportion of white, red, and different colors over time.  

For example in this chart I can make a few valuable observations

-  There is a non-trivial amount of white, so we're not saturating our hardware
-  There is about equal parts of red and colors, so we're network bound ish
-  There appear to be waves of activity followed by some waves of less activity

**Comment by d-v-b** [comment]
One simple idea would be to define how to aggregate across workers and display a population-level summary as a one-dimensional representation (or a small collection of one-dimensional representations) like a line plot or bar plot. 

It might be helpful to play around .. Is it easy to get the data behind that above visualization in a pydata-friendly format (e.g., dataframe)?

**Comment by davidbrochart** [comment]
Maybe a heatmap could fit well, as it's a 2D plot that can show e.g. a density of data transfers inside regions of the cluster. That would depend on the layout of the nodes on the Y axis though. Maybe it could be overlaid with another heatmap for the density of computations.

**Comment by jakirkham** [comment]
Just loading that PNG took a moment, which I think really drives this point home 😄

FWIW I like the idea of having some high-level overview with the possibility to drill in on parts to get a sense of what takes time in them. Maybe these correspond to HLGs (though maybe this already what you are thinking 😉)? Though not strongly attached if there's another way to accomplish this.

It does seem larger graphs do increase the burden on the visualization front, which IIUC lives on the Scheduler right? Having some way to reduce that load would be helpful.

**Comment by ssanderson** [comment]
> Often I look for the relative proportion of white, red, and different colors over time.

One way to systematize this would be to aggregate the data into a stacked area timeseries chart that shows the number of workers in each state over time.

Example of this from the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.area.html):

![image](https://user-images.githubusercontent.com/1588357/99842681-4e815e80-2b3e-11eb-86dd-db2391815adf.png)

I'm imagining a chart like the above, but replacing the legend with "network", "cpu", etc.

Reasons I think this might be a useful way to visualize aggregated data from this chart:

- The overall height of the graph tells you how many workers are doing some kind of useful work, so dips in the graph tell you places where you're not saturating the workers. A useful feature here is probably the ability to toggle whether or not idle workers are shown, so you can get a sense of whether you're saturating the available resources.
- The relative heights of different layers of the graph will tell you the proportion of time being spent on each activity, so you'll be able to recover the "network bound ish" observation you're currently getting from the task chart.

**Comment by jakirkham** [comment]
That's an interesting idea. How would one disambiguate the behavior of individual Workers (say one is behaving badly)?

**Comment by mrocklin** [comment]
@d-v-b https://docs.dask.org/en/latest/diagnostics-distributed.html#dask.distributed.get_task_stream

**Comment by exactlyallan** [comment]
I'd suggest the key attribute to keep is the time series view, but then aggregate all the workers into 1D heatmaps of each task type (as shown by a color in the above). So there would be ~7x stacked 1D heatmaps. 

Maybe a way to drill down could involve a slider to 'scrub' through individual task streams or order them by total of each task type.

**Comment by ssanderson** [comment]
> That's an interesting idea. How would one disambiguate the behavior of individual Workers (say one is behaving badly)?

I think the chart I suggested would mainly be helpful for getting a high-level view of when things are going well or poorly during a computation, but I don't think it would tell you much by itself about what specifically is going poorly (or well) during a period of interest, so I think you probably still would want some way to drill down

I think a good follow-up question might be "If we've identified an area of temporal interest by looking at aggregated data, is there a way we can use that to 'focus in' on what's happening during that time period?" One option might just be to display the full task stream on a smaller time slice. Depending on the workload, filtering down in time might be enough to make the full task stream more coherent. If it's still too much data though, then I think we probably come back to @mrocklin's original question of what's the next question that we want to answer when we've identified an area of interest (e.g., that a cluster is underutilized during some part of a computation).

**Comment by mrocklin** [comment]
Yeah, to be clear, I expect the right answer to all of this to be "this set
of five orthogonal charts" or "this multi-chart interactive dashboard that
allows for drilling down and exploration"

**Comment by Timost** [comment]
I'm not sure if this actually doable for dask, but since there are no pictures in this thread here is a visual version of what I can think of:
![newplot(61)](https://user-images.githubusercontent.com/7479071/101069157-e9942280-3599-11eb-8caa-0626164ef8a3.png)
The share would be computed for a group (or all workers ?) of worker over a time window (not sure if this is doable efficiently). Maybe we can group the smaller tasks into an "Other" category.

**Comment by mrocklin** [comment]
This is a duplciate of #4744
