### ISSUE TITLE
Use Layer annotations

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4262]
In https://github.com/dask/dask/pull/6767 task annotations were added to `HighLevelGraph` `Layers`. We can now start supporting `priority`, `resources`, `retries`, etc. annotations here in the distributed scheduler.

@sjperkins you've been leading the task annotation effort and expressed an interested in incorporating them into `distributed`. Some colleagues and I have time to dedicate to this if now is a busy time for you, but I first wanted to check in with you to see if you're still interested in working on this

**Comment by sjperkins** [comment]
Thanks for the reminder @jrbourbeau. I've been on leave this past week, but this is first thing on my to-do this week.

**Comment by jrbourbeau** [comment]
Awesome, thank you for continuing to lead this effort (also hope your leave was relaxing : ) )

**Comment by asford** [comment]
Is this resolved by #4406?

**Comment by ian-r-rose** [comment]
@asford Yes, that's right, thanks for the ping @asford
