### ISSUE TITLE
Implementing `__hash__` and `__eq__` for `BatchedSend`

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#4273]
In [`Scheduler.report`]( https://github.com/dask/distributed/blob/bbb23eb4a68ee0301db35dd18a916cb6b1cbafe4/distributed/scheduler.py#L2578 ) we [collect a `set` of `comms` for the `Client`s]( https://github.com/dask/distributed/blob/bbb23eb4a68ee0301db35dd18a916cb6b1cbafe4/distributed/scheduler.py#L2594-L2603 ). Looking more closely at the contents of [`self.client_comms`, it appears to just contain `BatchedSend` objects]( https://github.com/dask/distributed/blob/bbb23eb4a68ee0301db35dd18a916cb6b1cbafe4/distributed/scheduler.py#L2630-L2632 ). Putting these objects in a `set` will wind up using `__eq__` and `__hash__`. Neither of these appear to be defined by `BatchedSend`. As a result a good chunk of time is spent hashing these objects by some fallback mechanism before adding them to the `set` in `Scheduler.report`. Would be good to have implementations of `__eq__` and `__hash__` for `BatchedSend` to avoid this issue.

**Comment by jakirkham** [comment]
Alternatively we might investigate another way to write this code so it doesn't rely on `hash`ing and comparing `BatchedSend` objects.

**Comment by jakirkham** [comment]
Maybe another way to look at this is, when would a `BatchedSend` object be used for more than 1 `Client`?

cc @mrocklin (in case you have thoughts here 😉)

**Comment by mrocklin** [comment]
It seems reasonable that there would be only one BatchedSend per Client.  In this situation I would try implementing this (hopefully it's cheap to do), and then seeing if any tests fail.  If no tests fail then we're good to go.

**Comment by mrocklin** [comment]
We can also ask @jrbourbeau to do this if y'all are less familiar here.  James is fairly adept at these sorts of changes.

**Comment by jakirkham** [comment]
Found a good way to do this with a `dict` ( https://github.com/dask/distributed/pull/4275 ), which should get us past this issue. It may be possible to simplify this further to a `list`, but that might not matter much.
