### ISSUE TITLE
Implementing `__hash__` and `__eq__` for `TaskState`

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#4277]
As `TaskState` objects sometimes wind up in `set`s and as keys of `dict`s, it would be good to implement `__hash__` and `__eq__` to make them [hashable]( https://docs.python.org/3/glossary.html#term-hashable ). Python does implement a fallback, but if we have a better sense of what makes a `TaskState` unique, we may be better off implementing it ourselves.

**Comment by mrocklin** [comment]
The key attribute should be enough to establish uniqueness

**Comment by jakirkham** [comment]
Ok thanks for clarifying. That's what I was thinking, but wasn't sure if I was missing something. Implemented with PR ( https://github.com/dask/distributed/pull/4278 ).

**Comment by jakirkham** [comment]
Also IDK if we want to do this for `TaskGroup` as well. I'm not seeing it show up in contexts where it needs to be `hash`ed (at least after a few quick searches). Though I could be missing something there.
