### ISSUE TITLE
Apple M1 support?

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/distributed#4293]
Possibly silly question - does dask/distributed support the new Apple M1 chip?

**Comment by mrocklin** [comment]
Probably, assuming that Python does.

It's probably more important to ensure that related libraries like Numpy
and Pandas have full support.

**Comment by quasiben** [comment]
I believe Dask/Distributed has noarch packages and can be installed anywhere.  As for osx-arm64 support, conda-forge added building October: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

And you can see support for those [packages on anaconda.org](https://anaconda.org/search?q=platform%3Aosx-arm64) including Pandas and NumPy. @lostmygithubaccount, do you have an M1 enabled machine ?

**Comment by lostmygithubaccount** [comment]
I do not, otherwise would be happy to test

**Comment by wchatx** [comment]
I've only just started using it but dask/distributed is working fine for me with some toy examples on the M1 chip. Created some dataframes, did some common tasks with them and submitted some work to a local Distributed cluster.

Installed using [miniforge](https://github.com/conda-forge/miniforge)
