### ISSUE TITLE
Replace the terms "chain" and "chaining" throughout the codebase

### ISSUE THREAD

**Issue by brendanpl14** [dask/distributed#4303]
Although it is commonly utilized in CS to denote that act of combining multiple objects, functions, or processes into a series, the word “chaining” (or “chain”) is a borderline-racist term that can be associated with slavery and the act of restraining, binding, and imprisoning slaves.  Chains were used to prevent slaves from running away, while allowing enough mobility for them to complete their forced labor.  Symbols such as open handcuffs, shackles, or broken chains are commonly used in art or literature to represent the idea of slaves breaking free from their oppressors.

Please replace these words in the codebase.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @brendanpl14! Following-up on the conversation over in https://github.com/dask/dask/issues/6922, let's move this conversation over to the existing community-wide discussion happening over in https://github.com/dask/community/issues/68
