### ISSUE TITLE
Disabling logging in stealing

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#4359]
Through profiling of the Scheduler, there are 2 parts of stealing that stick out. First is a generator expression that is being fixed in PR ( https://github.com/dask/distributed/pull/4358 ). Second is this logging line (below). Am wondering given this logging is pretty granular (logging each key to steal), whether it would make sense to disable this logging with an option to re-enable. Thoughts? 🙂

https://github.com/dask/distributed/blob/07970728386788eace213487b54562b3af077b84/distributed/stealing.py#L88

**Comment by mrocklin** [comment]
Yes, that makes sense I think.  Most of the other log_event events in
scheduler.py occur at the worker level (like every time a worker comes or
goes), or the client interaction level (like every time the client submits
a graph).  I think that it is sensible to avoid per-task operations like
this.

**Comment by jakirkham** [comment]
Should we just drop it entirely then?

**Comment by jakirkham** [comment]
Proposing just dropping it in PR ( https://github.com/dask/distributed/pull/4375 )

**Comment by jakirkham** [comment]
Fixing another extra `log` line that we missed before in PR ( https://github.com/dask/distributed/pull/4609 )
