### ISSUE TITLE
bokeh plot memory display

### ISSUE THREAD

**Issue by caseyjlaw** [dask/distributed#437]
It would be helpful to have the bokeh web UI display memory use per worker and per task group. Memory intensive applications can get stuck (for a bit) retrying a computation that is too memory intensive. The current display does not make it clear that a memory limit is killing the computation.

**Comment by mrocklin** [comment]
There are a few ways in which we could slice and dice this data and display it.

1.  A worker table showing, among other things, the total amount of memory consumed as a percentage (we used to have this)
2.  A simple plot showing the distribution of bytes among task groups, like 50% read_csv, 25% groupby, 25% sum, although in a more visual form.
3.  Something that tries to cross the two, like the plot of part 2 for every worker
4.  Something else ...

There are undoubtedly many ways to do this.  Sketches for what you think would be useful are most welcome.  I'm fooling around with the web interface now, so this issue is timely

**Comment by caseyjlaw** [comment]
For my issue, I think the per-worker memory needs to be clear. So I think option 1 or 3 is best.
I'll elaborate on #438.

**Comment by mrocklin** [comment]
I think that #438 is strictly option 2.  I think that in the end we'll want many such views.  I'll probably stand up option 1 in the near future.

**Comment by mrocklin** [comment]
@caseyjlaw says 

> I wonder if the per-task-group memory bar could be accompanied by a per-worker memory bar? I'm imagining a bar in the same units and same design as the per-task-group, but showing how many bytes are used in each worker. The total number of bytes represented in both bars would be the same, so they'd be pretty easy to interpret at a glance.

So this would show us the relative distribution of bytes across the workers.  More or less it would let us quickly answer the question "are my bytes spread evenly across my workers."  

However, usually when I'm curious about workers and memory the question I want to answer is "How much memory is being used on my workers?" and, a corollary "Are any of my workers close to being saturated?"  I think that the plot style in #438 is bad at showing absolute quantities like these.  I think that we should consider other styles.  We have a lot of power with Bokeh, I think that we really just need to think about the right kind of plot.  I genuinely encourage sketches here.  I've been sitting down with paper and pen for a bit.

**Comment by caseyjlaw** [comment]
I think you have summarized what I want well. I suppose stacked histograms are pretty bad at showing absolute values. I thought that with the hover label that bokeh does well, it would be easy to extract absolute values. Another consideration is that any per-worker visualization needs to work in the n=1  and n=many cases.
How about using lines instead of bars for per-worker memory? So maybe (sorry for ascii):

Worker Memory
.........|..|.|.|.|||||.........|..

And on hover, it would show the name of the worker. This would show outliers well.

**Comment by mrocklin** [comment]
Yeah, agreed on the n = 1 and n = many case.  Some of our current plots (like the beautiful task stream plot) fail to be meaningful above a few hundred workers

**Comment by mrocklin** [comment]
Showing the distribution of worker memory percentages could make sense.  Perhaps we couple this with a selection tool to then show what's going on on those workers by highlighting cells in a table or producing some other more detailed plot.

**Comment by mrocklin** [comment]
Fixed in #440
