### ISSUE TITLE
Set worker nprocs and nthreads in the same way as LocalCluster

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#4373]
In `LocalCluster` the number of processes and threads are calculated by default based on the number of cores in the system.

https://github.com/dask/distributed/blob/3fb3d8c8c14800ff8f1cd76d0052985f355ecfcc/distributed/deploy/local.py#L246-L271

It would be great if the `dask-worker` and `dask-spec` CLI commands could work the same way.

It is possible to set `dask-worker --nprocs=-1` which will create one process per CPU core, but that feels like overkill. The heuristic used in `LocalCluster` is nice.

Spec is the next level down where you are expected to pass a spec for a single worker, or multiple workers. But ideally I would like to pass a single worker spec by create n workers based on the same heuristic.

**Comment by mrocklin** [comment]
For dask-worker I could imagine a --nprocs="auto" option would be nice

For spec I think that we would want some sort of MultiWorker or MultiNanny
class maybe?

**Comment by jacobtomlinson** [comment]
Closed in #4377

**Comment by jrbourbeau** [comment]
Thanks for following up @jacobtomlinson!
