### ISSUE TITLE
Key Error in distributed worker tasks dictionary

### ISSUE THREAD

**Issue by chrisroat** [dask/distributed#4382]
**What happened**:

In a dask-gateway GKE cluster, I have a graph that consistently stalls with the error below.  The error appears across many workers, and they all get wedged -- all referencing the same key value.  The workers stop communicating (last seen of 15+ minutes) and stop doing any work .  Killing the corresponding GKE pods does not help -- the scheduler still seems to happily wait for them.  I did not see any errors in the scheduler.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 2627, in execute
    self.ensure_communicating()
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 1880, in ensure_communicating
    to_gather, total_nbytes = self.select_keys_for_gather(
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 1985, in select_keys_for_gather
    total_bytes = self.tasks[dep].get_nbytes()
KeyError: 'xarray-image-bc4e1224600f3930ab9b691d1009ed0c'
```

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fac3d04f4f0>>, <Task finished name='Task-143' coro=<Worker.execute() done, defined at /opt/conda/lib/python3.8/site-packages/distributed/worker.py:2524> exception=KeyError('xarray-image-bc4e1224600f3930ab9b691d1009ed0c')>)
```

**What you expected to happen**:

Ideally, the key would not be missing.  At the very least, the worker would go away and be replaced with a new worker.

**Minimal Complete Verifiable Example**:

Running locally on a small data sample does not show the problem.

**Environment**:

- Dask version: 2020.12.0 (dask-gateway 0.9.0)
- Xarray: 0.16.2
- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): conda

What might cause this?  Is there something else I should be looking into?

**Comment by chrisroat** [comment]
@martindurant

I have spent some time dealing with a couple of workloads with these issues.  Just to get the work through, I have to scan the workers page for the red highlighting indicating the worker hasn't been seen for a while.  Then it's time to restart the workload (and the scheduler, since it gets bogged down and seems to have a memory leak).  

Now with more experience and knowing what to look for, I am seeing the KeyError across many workers, often with several different keys reported as problematic.

Not all workers with KeyErrors get "wedged", so it's not clear that the KeyError is directly causing the worker problems.  If I do try to retire a wedged worker via the client, the call never returns and the scheduler prints the following every 10 seconds:
```
distributed.scheduler - WARNING - Communication failed during replication: {'status': 'missing-data', 'keys': {"('getitem-799691bb5a558f83cf899aadbb6778de', 0, 3, 0)": ('tls://10.4.141.23:39415',)}}"
```

**Comment by fjetter** [comment]
I _think_ I am fixing this in #4360

Can this issue be reliably reproduced?

**Comment by chrisroat** [comment]
I haven't reproduced locally.  On my cluster, once I started looking for it, I definitely see the KeyError a lot.  The wedged worker does not happen every time, though.

It sounds like a very hard problem to get to the bottom of. And thank you for tackling it. 

If your PR is near ready, I'd be happy to give it a try.
