### ISSUE TITLE
Segmentation fault on travis

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#4387]
There appears to be a segfault on CI. Haven't debugged further. 

See for example https://travis-ci.org/github/dask/distributed/jobs/750955092

**Comment by fjetter** [comment]
Seems to be pretty consistently on python 3.8 during the `test_worker.py` tests

**Comment by jacobtomlinson** [comment]
Yeah I've also noticed this.

I've been trying to push forwards with #4218. I'd hate to waste effort tracking down a Travis specific issue and then move CI.

**Comment by jrbourbeau** [comment]
>  I'd hate to waste effort tracking down a Travis specific issue and then move CI

+1, as the Travis tests have been consistently failing, I've primarily been relying on our Windows tests

**Comment by jakirkham** [comment]
Agree with others that time is likely better spent migrating to GitHub Actions than debugging Travis CI. If we still see this issue on GitHub Actions, then it would be worth debugging further.

**Comment by crusaderky** [comment]
I never experienced a segfault on github actions (Linux/Windows/MacOS) over ~500 jobs.

**Comment by jacobtomlinson** [comment]
That's reassuring thanks @crusaderky. Will close.
