### ISSUE TITLE
Ability to have a Dask client get a handle on tasks running, disconnect, and then reconnect and re-establish connection with the tasks

### ISSUE THREAD

**Issue by Rakesh4G** [dask/distributed#4391]
Ability to have a Dask Client :
  - Get a handle on tasks running
  - Disconnect
  - Reconnect and re-establish connection with the tasks

This is required when client and scheduler are running on different places and we have long running tasks. We have seen client looses Connection to Scheduler and we get a failure on client side. Though job is still running without any issues.
But we are unable to get the result.

**Comment by martindurant** [comment]
Have you tried using published datasets? https://distributed.dask.org/en/latest/publish.html

**Comment by CMCDragonkai** [comment]
@martindurant Does that maintain knowledge of errors?

As in we submit a task from a client over a network, sometimes there are failures on the network. The client disconnects and there's no way to know the status of the job now.

**Comment by martindurant** [comment]
Yes, if you use "publish", the futures held by the scheduler can have any of the normal states, so that if you retrieve them later from another client, you can get an exception back.

**Comment by CMCDragonkai** [comment]
So it's all based on the name?

```
df = client.get_dataset('negative_accounts')
```

If the job that resolves `negative_accounts` results in an exception, will that exception be acquired from that?

**Comment by martindurant** [comment]
Yes, exactly. For example:
```
fut = client.submit(lambda: 1 / 0)
client.publish_dataset(err=fut)
```
and then
```
fut = client.get_dataset("err")
fut.result()  # Exception
```

**Comment by fjetter** [comment]
FWIW you can also store a future in a variable object which will then be available indefinitely until let go explicitly. It is then also available for other clients


```python
# Client A
fut = client.submit(udf)

var = Variable("my-udf-computation")
var.set(fut)
client.close()
```

```python
# Later... on Client B
var = Variable("my-udf-computation")
fut = var.get()
fut.result()
```

This is not very well advertised but afaik a fully supported feature.

**Comment by jrbourbeau** [comment]
Closing as there are ways to support the request outlined in the original post (e.g. `Variable` and datasets mentioned above)

**Comment by CMCDragonkai** [comment]
I noticed that `client.publish_dataset` doesn't seem to work according to the docs:

```
await client.publish_dataset(result, name, True)

# this results in an empty set
await client.list_datasets()
```

But if I use `client.publish_dataset(**{name: result})`, it does work as expected.

**Comment by martindurant** [comment]
It seems to me that the docstring is clear:
```
Publish named datasets to scheduler

This stores a named reference to a dask collection or list of futures
on the scheduler.  These references are available to other Clients
which can download the collection or futures with ``get_dataset``.

Datasets are not immediately computed.  You may wish to call
``Client.persist`` prior to publishing a dataset.

Parameters
----------
args : list of objects to publish as name
name : optional name of the dataset to publish
override : bool (optional, default False)
    if true, override any already present dataset with the same name
kwargs : dict
    named collections to publish on the scheduler

Examples
--------
Publishing client:

>>> df = dd.read_csv('s3://...')  # doctest: +SKIP
>>> df = c.persist(df) # doctest: +SKIP
>>> c.publish_dataset(my_dataset=df)  # doctest: +SKIP

Alternative invocation
>>> c.publish_dataset(df, name='my_dataset')
```
So all non-keyword arguments are considered datasets, and you must explicitly pass `name=` and `override=` for this case.

I agree that a meaningful exception should be raised when the inputs do not match expectations.
Marking this as good-first-issue.

**Comment by martindurant** [comment]
-EDIT-

please make a new issue with the case of `client.publish_dataset()` or `client.publish_dataset(thing)` not raising an exception. That should be the good-first-issue
