### ISSUE TITLE
Adaptative stops after some time

### ISSUE THREAD

**Issue by Timost** [dask/distributed#4421]
Hi,
First :heart: dask,  so thank you !

**What happened**:
I'm using dask-kubernetes (0.11.0) to run a distributed dask cluster on top of azure kubernetes service. The cluster itself is comprised of two nodepools with auto scaling enabled:
- `stable`: VMS of standard priority (eg: guaranteed availabilty)
- `spot`: VMS of spot priority (eg: premptible can be deleted anytime). To save on compute costs

I'm using the adaptative feature of dask-distributed to make sure the pool of spot instances gets "renewed" as `spot` nodes get deleted. At first everything works as expected, spot nodes get created to replace the deleted ones.

After some time though (20-30 minutes) the adaptative feature stops working with a:
```
distributed.deploy.adaptive_core - INFO - Adaptive stop
```

Looking at the code it seems this is done when there is an `OSError`. I couldn't find more details about it though. I would love to have more details on this.

**What you expected to happen**:
I would expect the adaptative to continue working.

**Minimal Complete Verifiable Example**:
Not runable as is sorry.
```python
from dask_kubernetes import KubeCluster
from distributed import Client

cluster = KubeCluster()
client = Client(cluster)
cluster.scale(80)
cluster.adapt(minimum=75, maximum=80, wait_count=10, interval='10s')
... actual dask job ...
```

**Anything else we need to know?**:
Somehow using adapt to handle pre-emptible nodes getting deleted feels a bit like a workaround. I'm not aware of a dedicated dask-kubernetes or distributed but maybe I just missed it.

**Environment**:

- Dask version: 2.30.0
- Python version: 3.6.12
- Operating System: Debian testing
- Install method (conda, pip, source): pip (via poetry)
- Distributed version: 2.30.0

**Comment by jacobtomlinson** [comment]
> Somehow using adapt to handle pre-emptible nodes getting deleted feels a bit like a workaround.

This definitely feels like a workaround. Having adaptive clusters on spot means you will likely lose work and distributed will have to recompute things (potentially everything you are working on).

I would be nice to explore draining things safely over in `dask-kubernetes`.

---

It would be interesting to get to the bottom of why adaptive is stopping though. I agree that it isn't clear from inspecting the code.

I've raised #4422 to improve the logging here to hopefully help in tracking this down in lieu of a minimum reproducible example.

**Comment by Timost** [comment]
Thank you ! I'll test the pipeline with distributed master as soon as I can. It's long running so next time will be tomorrow.

> This definitely feels like a workaround. Having adaptive clusters on spot means you will likely lose work and distributed will have to recompute things (potentially everything you are working on).

Yes, we are using a mix of  stable and spot instances to keep the data losses/recompute within reasonable levels. So far it has worked pretty well, but it seems spot instances life time is getting shorter.

**Comment by jacobtomlinson** [comment]
> but it seems spot instances life time is getting shorter

I am less familiar with Azure but AWS notifies you via a metadata URL that you can poll when you have two minutes before the spot instance is removed. I wonder if the same thing is also available on Azure?

If so we could potentially write a Dask worker plugin which polls this URL and if it gets a termination warning it could gracefully remove itself from the cluster.

**Comment by Timost** [comment]
Ah right ! After a quick look it seems like something equivalent exists for azure:
The eviction doc:
https://docs.microsoft.com/en-us/azure/virtual-machines/spot-vms#eviction-policy
The metadata service:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events

They mention that the termination will happen `30 seconds` after the notification which might be a bit short depending on the use case.

Just to be sure when you mention worker-plugins, you are refering to https://distributed.dask.org/en/latest/plugins.html?highlight=plugin#worker-plugins ?

**Comment by jacobtomlinson** [comment]
Ah great.

Yeah I expect things may not be perfect. 30 seconds may not be long enough to migrate memory to another worker depending on the computation. But we can still try!

Yeah that's what I was referring to. We could write a plugin which on `startup` registers a periodic callback which polls the metadata API. If the API gives a termination notification we could tell the worker to call `close_gracefully`.

This has been previously discussed in #3300, might be a good time to renew that conversation.

**Comment by Timost** [comment]
Thanks for the pointers, I've gone through the various issues. 
From the documentation, it seems the worker plugins run on the main worker thread, would that pose an issue in the case of polling an endpoint ? I guess everything should be asynchronous but this is not really mentioned in the doc.

Regarding the issue, I've been able to continue the pipelines with the added log. Here is the details we get:
```
distributed.deploy.adaptive_core - ERROR - Adaptive stopping due to error in <closed TCP>: TimeoutError: [Errno 110] Connection timed out: while trying to call remote method 'adaptive_target'
distributed.deploy.adaptive_core - INFO - Adaptive stop

```

**Comment by jacobtomlinson** [comment]
> would that pose an issue in the case of polling an endpoint

No. If you have a poke through the code you'll find other instances of periodic callbacks. Running these asynchronously is handled for us.

Also thanks for the logs, that is helpful. Looks like the comm is closed and we aren't retrying correctly.

**Comment by Timost** [comment]
Alright, So I've been reading the code in more depth, and here's what I think is hapenning:
The worker on the spot instances get deleted without prior notice to the scheduler. Which can manage it, unless too many workers are lost in which case the scheduler ends up lost, it tries to talk to worker that no longer exist which triggers the `OSError` that stops the adaptative behaviour.

I've been playing with the plugin idea you mentioned. Here's what I have so far:
```python
from distributed.diagnostics.plugin import WorkerPlugin
from tornado.ioloop import IOLoop, PeriodicCallback

class PreemptibleListener(WorkerPlugin):
    def __init__(
        self, interval=1, metadata_url=None,
        termination_events=None
    ):
        self.callback = None
        self.loop = None
        self.worker = None
        self.interval_s = interval
        self.metadata_url = (
            metadata_url or
            'http://169.254.169.254/metadata/scheduledevents?api-version=2019-08-01'
        )
        self.termination_events = termination_events or ['Preempt', 'Terminate']

    async def poll_status(self):
        async with aiohttp.ClientSession(headers={'Metadata': 'true'}) as session:
            async with session.get(self.metadata_url) as response:
                data = await response.json()
                for evt in data['Events']:
                    event_type = evt['EventType']
                    if event_type in self.termination_events:
                        logger.info(
                            'Node will be deleted attempting graceful shutdown',
                            data_event=evt, worker_name=self.worker.name
                        )
                        await self.worker.close_gracefully()

    def setup(self, worker):
        self.worker = worker
        self.loop = IOLoop.current()
        # callback time is in ms
        self.callback = PeriodicCallback(
            self.poll_status,
            callback_time=self.interval_s * 1_000
        )
        self.loop.add_callback(self.callback.start)

    def teardown(self, worker):
        logger.info('Tearing down plugin', worker_name=self.worker.name)
        if self.callback:
            self.callback.stop()
            self.callback = None
```
It seems to improve the situation with regards to the scheduler being noticed of worker retirement. However, I get a lot of these warnings on the worker, once the plugin is registered:
```
distributed.comm.tcp - INFO - Connection closed before handshake completed                                                                                                                                                             
distributed.comm.tcp - INFO - Connection closed before handshake completed                                                                                                                                                             
distributed.comm.tcp - INFO - Connection closed before handshake completed                                                                                                                                                             
distributed.comm.tcp - INFO - Connection closed before handshake completed                                                                                                                                                             
distributed.comm.tcp - INFO - Connection closed before handshake completed
```
So I guess my implementation messes up with the connection to the scheduler.

**Comment by jacobtomlinson** [comment]
That plugin looks great! That's exactly what I had in mind. 

I can't see anything obvious in your plugin that would cause the `Connection closed before handshake completed` logs. @mrocklin could you have a quick glance in case you spot something for me to investigate?

@Timost perhaps you could like to contribute this plugin to `dask-cloudprovider`. It's a subproject which handles cloud vendor specific things. Today that is mainly constructing clusters via their native APIs, but I think utilities like this could also live there.

I can imagine some docs along the lines of

```python
from dask.distributed import Client
from dask_kubernetes import KubeCluster
from dask_cloudprovider.azure.utils import AzurePreemptibleListener

cluster = KubeCluster(...)
client = Client(cluster)
client.register_worker_plugin(AzurePreemptibleListener)
```

Although it's not 100% clear to me where.

**Comment by Timost** [comment]
Actually there is an issue in the above code, it can call `close_gracefully` several times for a given worker. Here is the latest version:
```python
class PreemptibleListener(WorkerPlugin):
    def __init__(
        self, interval=1, metadata_url=None,
        termination_events=None
    ):
        self.callback = None
        self.loop = None
        self.worker = None
        self.interval_s = interval
        self.metadata_url = (
            metadata_url or
            'http://169.254.169.254/metadata/scheduledevents?api-version=2019-08-01'
        )
        self.termination_events = termination_events or ['Preempt', 'Terminate']
        self.terminating = False

    async def poll_status(self):
        if self.terminating:
            return
        async with aiohttp.ClientSession(headers={'Metadata': 'true'}) as session:
            async with session.get(self.metadata_url) as response:
                data = await response.json()
                for evt in data['Events']:
                    event_type = evt['EventType']
                    if event_type in self.termination_events:
                        self.terminating = True
                        logger.info(
                            'Node will be deleted, attempting graceful shutdown',
                            data_event=evt, worker_name=self.worker.name
                        )
                        await self.worker.close_gracefully()

    def setup(self, worker):
        self.worker = worker
        self.loop = IOLoop.current()
        # callback time is in ms
        self.callback = PeriodicCallback(
            self.poll_status,
            callback_time=self.interval_s * 1_000
        )
        self.loop.add_callback(self.callback.start)

    def teardown(self, worker):
        logger.info('Tearing down plugin', worker_name=self.worker.name)
        if self.callback:
            self.callback.stop()
            self.callback = None
```

I would love to contribute it and I'm ready to spend some time on it. I just feel like things need to be a bit more polished before doing that, so I'm going to do some testing on production workloads to make sure it improves the situation.

**Comment by Timost** [comment]
Hi, just a heads up, to say I haven't forgotten about these issues, I've spent the last week trying to get a setup that actually works in practice, without real success so far.

Here are a few things I have discovered along the way:
1. azure spot instances (used as aks node pools) can outlive the lifetime given by the metadata service by up to an hour, so listening naively to the metadata service is actually wasteful in this precise case.
2. adaptative could be more resilient to unclean worker loss, but I don't blame it. I've ended up disabling it and writing a custom scheduler plugin that calls `scale` every 15 seconds if the number of observed workers is lower than the requested one (dumb adaptative). While doing this I discovered that:
3. the `remote` scheduler of dask-kubernetes does not support scheduler plugins so I had to run it along the client.
4. After some time calling `scale` repeatedly does not create any new pod even if the number of workers needs to be increased. I'm not sure what's happening, looking at the code (`distributed.deploy.spec.SpecCluster._correct_state` and `distributed.deploy.spec.SpecCluster._correct_state_internal`) I see some stateful guards against repeated calls and lock mecanism so maybe a race condition.

**Comment by jacobtomlinson** [comment]
> azure spot instances (used as aks node pools) can outlive the lifetime given by the metadata service by up to an hour, so listening naively to the metadata service is actually wasteful in this precise case.

I understand what you mean by wasteful but we should still honour the metadata service. Perhaps even go a step further and destroy the node ourselves (wherever the appropriate place is to do that).

> I've ended up disabling it and writing a custom scheduler plugin 

I'm not sure I understand why you've done this? 

> the remote scheduler of dask-kubernetes does not support scheduler plugins so I had to run it along the client.

Could you raise an issue for this on `dask-kubernetes`? We should definitely support this.

> After some time calling scale repeatedly does not create any new pod even if the number of workers needs to be increased.

cc @mrocklin in case he can educate us on the reasoning here

**Comment by Timost** [comment]
> I'm not sure I understand why you've done this?

My workers configuration is 3 processes, 1 thread per process. I have 1 dask-worker pod per k8s node, each node has 3 vCPU. So from the scheduler perspective I have 3 workers per k8s node. It seems `Adaptative` works on a `worker` basis, not on a `node` basis and it ends up requesting 3 times more nodes than needed. I'm not sure if the problem is with `Kubecluster` or with `Adaptative` as there are interactions between the two when scaling up or down the cluster.

I was getting some weird behaviour, so I wanted to work with something simpler so that I can groke the whole thing and isolate the issues.

**Comment by jacobtomlinson** [comment]
Ah interesting.

I think `KubeCluster` may assume one worker per pod.

Do you notice a big difference with 3 procs 1 thread vs 1 proc 3 threads?

**Comment by Timost** [comment]
> I think KubeCluster may assume one worker per pod. 

I agree, after looking at the code, I think the responsibility lies with `KubeCluster`.

> Do you notice a big difference with 3 procs 1 thread vs 1 proc 3 threads?

Yes, the pipeline in question does mostly GIL holding operations so the speed up is close to 3x.

**Comment by jacobtomlinson** [comment]
Fair enough. Might be worth raising this over on `dask-kubernetes` then so we can fix over there.

**Comment by Timost** [comment]
This issue turned out to be the symptoms of several other issues:
- https://github.com/dask/dask-kubernetes/issues/294
- https://github.com/dask/dask-cloudprovider/pull/251
- probably others that I haven't opened yet
So I think I will be closing this one and work on the other issues directly.

**Comment by jacobtomlinson** [comment]
Sounds good!
