### ISSUE TITLE
Publish collections/futures

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#444]
From one client/executor I may want to create a dataset and then share it with my colleagues working from other clients/executors.  Currently I can pickle my dask collection, send it to them, they unpickle it, and through the creation of Futures they get registered as clients to the data.  However this pickling-and-sending process is inconvenient.  We could publish collections to the scheduler itself

### Client 1

```python
e.publish_dataset(df, 'analysis')
```

### Client 2

```python
df = e.collect_dataset('analysis')
```

### Scheduler

```python
>>> s.published_datasets
{'analysis': {'thing-to-send-to-client': ...,
              'relevant-keys': {set of keys}}
```

This is completely orthogonal functionality for the scheduler, but fairly trivial to build.  It should be a couple of handlers and a dictionary on the scheduler, a couple of methods on the Executor, and a sane way to collect futures and things that wrap futures into something that we can store in the dictionary.

This would be an interesting and moderately challenging task for someone like @jcrist or @martindurant if they have interest.  It would touch major pieces of code peripherally but it isn't conceptually or algorithmically tricky.

**Comment by martindurant** [comment]
Given that the user can already specify the key name associated with any future in their executor when submitting, isn't the only task here to be able to create a future pointing to a given key on the scheduler?

**Comment by mrocklin** [comment]
A collection might contain several futures.  

Under normal use of collections like dask.dataframe users usually don't specify keynames.  We would want to associate a name to both a set of futures and sufficient metadata to re-create the dask.dataframe that surrounds those futures on the new client.
