### ISSUE TITLE
Publish Cython build

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4442]
The Cython work seems mature enough that we might want to make it more publicly accessible with an optional separate package.  Is this easy to do?  I _don't_ think that we should make it default yet, but having it be easy to install by people who are not familiar with Cython or compilation would probably be a plus.

One option would be to have a separate conda package `conda install -c conda-forge distributed-cython` (I'm curious how this would play with the `dask` metapackage).  I wonder also if there is some more blessed way to specify variants. 

cc @jakirkham

**Comment by jakirkham** [comment]
I don't think it is ready to live in a package yet. There are some other packaging related things we would want to sort out before doing that ( like PR https://github.com/dask/distributed/pull/4326 ).

If you or your team need help building this, I'm happy to walk them through it. Assuming an environment with `dask` installed. Here are the steps:

1. Install the `compilers` and `cython` packages from `conda-forge`
2. Clone and `cd` into `distributed/`
3. Run `python -m pip install -vv --no-deps --install-option="--with-cython=profile" .`

**Comment by jakirkham** [comment]
@jrbourbeau and I made some improvement to testing in PR ( https://github.com/dask/distributed/pull/4764 ). We did observe a few test failures (and are now skipped when the Scheduler is Cythonized). These are being tracked in PR ( https://github.com/dask/distributed/pull/4767 ). Some of these issues may involve working with Cython to address

**Comment by jakirkham** [comment]
Now that nightlies are supported ( https://github.com/dask/community/issues/76 ). Maybe a good first step would be to build nightlies with Cython enabled.

Admittedly this isn't quite as easy as installing from conda-forge, which we could also discuss, but it is an improvement from a user standpoint since they could install the package and would not need to compile from source.
