### ISSUE TITLE
Unable to control the CPU load using LocalCluster

### ISSUE THREAD

**Issue by fcharras** [dask/distributed#4444]
I want to use dask on a single machine because I think my load could benefit from pre-scattering data and from the Futures interface (especially as_completed).

I run the tasks in a `Client` context manager with the following configuration:

```
        n_workers=10,
        processes=True,
        threads_per_worker=1,
        dashboard_address=None,
        worker_dashboard_address=None,
        memory_limit=0
```
then I submit 10 tasks, and using `as_completed` I add a new task whenever a result is available and fetched to the main process.

I would expect the CPU load to be 1000% plus some acceptable overhead, but the CPU load seems to be (`(2*n_workers-1)*100%`), said differently: for each process with 100% usage (but one) there is a second process with 100% usage.

The same load using `joblib.Parallel` have 1000% CPU usage as expected

Not sure if this is a misconfiguration or a misconsception from me, or a bug ? What could those extra processes be used for at this rate ? the documentation advises the use of `LocalCluster` but I don't think such drawback is mentionned.

- Dask version: 2021.1.0
- Python version: 3.7.5
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
That's surprising.  Dask should create ten processes as you expect.  Maybe
you ran your script a couple of times by mistake?  Nothing comes to mind on
what might cause this.  If you have a reproducible example that would help.

**Comment by fcharras** [comment]
I reproduce with this example:

```
import time
from dask.distributed import Client, as_completed

def parallel_map(
        function,
        seq,
        *args,
        n_jobs=1,
        **kwargs):

    if n_jobs == 1:
        return [function(*x, *args, **kwargs) for x in seq]

    results = []

    x = next(seq, None)
    if x is None:
        return results

    nb_dispatched = 0

    with Client(n_workers=n_jobs, processes=True, threads_per_worker=1, dashboard_address=None,
                worker_dashboard_address=None, memory_limit=0) as client:

        pending_completion = as_completed(None, with_results=True)

        while x is not None or nb_dispatched > 0:

            if nb_dispatched > 0:
                result = next(pending_completion)[1]
                results.append(result)
                nb_dispatched -= 1

            while x is not None and nb_dispatched < n_jobs:
                pending_completion.add(client.submit(
                    function, *x, *args, **kwargs))
                nb_dispatched += 1
                x = next(seq, None)

    # NB: the results are returned by order of completion not order of input
    return results


class Function:
    def __init__(self):
        self.stuff = [["someword_%d %d" % (i, j) for i in range(500)] for j in range(5000)]

    def __call__(self, x):
        now = time.time()
        while (time.time() - now) < 240:
            continue
        return x


if __name__ == "__main__":
    seq = (
        (
            [
                ["someword_%d %d %d" % (i, j, k) for i in range(500)]
                for j in range(5000)
            ],
            )
        for k in range(40)
        )

    function = Function()

    res = parallel_map(
        function,
        seq,
        n_jobs=10)
```

I expect ~1000% cpu usage with this script, but after a few minuts (maybe 10 minuts) it will be >> 1000%.

**Comment by jakirkham** [comment]
Why is the `Client` being created within `parallel_map` as opposed to outside of it? Would have expected the latter.

**Comment by fcharras** [comment]
Moving the client creation in the `__main__` bloc and passing it as an argument of `parallel_map` does not change the behavior. Creating the client outside of `__main__` is forbidden.

Can you confirm that this script should consume ~1000% CPU, could you run my example and report your observations ? the environment I'm using is fairly standard, it would be surprising if it's not reproducible. It's running on `Ubuntu 16.4`, within a `screen` session, `python 3.7.5` is deployed with `pyenv` and I'm using a python virtual environment, that's about it.

I thought it could have to do with the function and/or the inputs being somewhat large that could disturb inter-process communication (~50MB per input submitted to a worker, I do get the warning suggesting to scatter the data beforehand), although it shouldn't, since joblib.Parallel works fine with the same load ?

**Comment by fcharras** [comment]
Here's a more minimal (and faster) example, htop screenshots, and comparison with joblib.

```
import time
from joblib import Parallel, delayed
from dask.distributed import Client, as_completed


def parallel_map(
        function,
        seq,
        *args,
        n_jobs=1,
        **kwargs):

    x = next(seq, None)
    nb_dispatched = 0
    futures = []

    with Client(n_workers=n_jobs,
                processes=True,
                threads_per_worker=1,
                dashboard_address=None,
                worker_dashboard_address=None,
                memory_limit=0) as client:

        while x is not None or nb_dispatched > 0:

            # submit n_jobs and wait 
            while x is not None and nb_dispatched < n_jobs:
                x = client.scatter(x)
                futures.append(
                    client.submit(function, *x, *args, fifo_timeout="10000 ms", **kwargs))
                nb_dispatched += 1
                x = next(seq, None)

            time.sleep(2400)


def function(x):
    now = time.time()
    while (time.time() - now) < 240:
        continue
    return x


if __name__ == "__main__":
    seq = (
        (
            [
                ["somemore_%d %d %d" % (i, j, k) for i in range(5)]
                for j in range(5)
            ],
            )
        for k in range(40)
        )

    # uncomment one of the following two

    # Parallel(n_jobs=10)(delayed(function)(x) for x in seq)

    # res = parallel_map(
    #     function,
    #     seq,
    #     n_jobs=10)
```
Here's htop sorted by CPU load with the joblib line uncommented:
![image](https://user-images.githubusercontent.com/29153872/105826615-3b1cc480-5fc1-11eb-9296-7408a553f485.png)

Here's htop sorted by CPU load with the joblib line commented and dask lines uncommented:
![image](https://user-images.githubusercontent.com/29153872/105826696-4ec82b00-5fc1-11eb-9391-c21fcd78ce02.png)

When using dask, there are twice as much processes, half of them sleeping, but despite sleeping with a 100% CPU load each. In fact there are two processes for each pipe handle, one running and one sleeping:

![image](https://user-images.githubusercontent.com/29153872/105826804-71f2da80-5fc1-11eb-81b4-6a2b99194196.png)

**Comment by fcharras** [comment]
It seems to be purely a problem of display in htop. Other CPU monitoring tools properly display the expected CPU usage (top, mpstat,...) when running this example.

When process states change at a high frequency (e.g between R (running) state and S (sleeping)) state, it seems that monitoring tools can get confused, that might be an explanations here, oops.

The conclusion is that there are no issues with dask. 

One can hope this issue in the archives will prevent similar confusions. :blush:
