### ISSUE TITLE
Does the name flag on dask-worker work?

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#446]
I would like to spin up two different workers (embedded in containers) on the same host and then preferentially push work. 

I set the --name flag but don't see anything other than the ip-address keeping track of things??

**Comment by nfaggian** [comment]
I guess a better question is: If I have a list of delayed jobs and two workers, how do I manually assign parts of that list of jobs to the workers.

**Comment by mrocklin** [comment]
http://distributed.readthedocs.io/en/latest/locality.html#user-control

The `workers=` keyword argument currently only works on submit and map.  

It's not entirely clear what people want when they specify `workers=` for complex graphs, so I have some questions for you on what you would expect:

* Should the entire graph run only on that set or workers or only the final nodes?  
* What if you submit a graph that already has some overlap with what is in the scheduler, should we union or intersect the worker sets?  
* How should we allow people to specify restrictions for only particular parts of the graph?

**Comment by mrocklin** [comment]
And yes, if you use `--name some-name` it does become a valid identifier for the `workers=` inputs

**Comment by nfaggian** [comment]
Thanks @mrocklin - reliable and quick as usual :-)  Apologies for missing the documentation.

To answer your questions:
1) I would expect the entire graph to run on the set of specified workers.
2) I think intersection makes sense.
3) I think a restriction graph for advanced use cases?

Do you need to still know the port for the --name option to work? is this code in a new release?  

Is there a way to check the association between the alias and the actual IP addresse:port for debugging?

**Comment by mrocklin** [comment]
It's not super accessible, but this would give you that information:

```python
In [1]: from distributed import Executor
from 
In [2]: from distributed.utils import sync

In [3]: e = Executor('localhost:8786')

In [4]: sync(e.loop, e.scheduler.identity)
Out[4]: 
{'id': 'cd4893ac-68b8-11e6-9c0e-e82aea155996',
 'services': {'http': 9786},
 'type': 'Scheduler',
 'workers': {'127.0.0.1:56503': {'active': 0,
   'info': {'active': 0, 'stored': 0},
   'last-seen': 1471905431.6465929,
   'name': 'alice',
   'services': {'http': 59560, 'nanny': 35347},
   'stored': 0,
   'time-delay': 0.003352642059326172}}}
```

Note the name field of a worker.

You can use either `workers='host:port'` or `workers='alice'` equally

**Comment by nfaggian** [comment]
Thanks - what do you think about a property on the Executor instance that returns the workers sub-dictionary? might be useful for interactive debug.

**Comment by mrocklin** [comment]
Yeah, we've added those as they've become useful.  You might find it useful to look at the definitions of functions like Executor.who_has, Executor.rebalance, or Executor.ncores.  They're all more-or-less the same

**Comment by mrocklin** [comment]
I'll keep this open for now.  Having this information be more accessible sounds good to me.

**Comment by nfaggian** [comment]
Great. I ended up forming a chained set of submit calls btw. Which allowed one submit to go to a different worker. Using a delayed decorator would have been nicer though :)

**Comment by nfaggian** [comment]
I think propagating workers to compute would be a nice addition in the future.

**Comment by mrocklin** [comment]
Have added a `.scheduler_info` method to the Executor.  Closing.
