### ISSUE TITLE
Avoid is_coroutine_function calls in Server

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4469]
We currently support handlers that are either synchronous or asynchronous 

https://github.com/dask/distributed/blob/1297b18ff09276f6ad1553d40ab3ce77acf0fc0e/distributed/core.py#L567-L572

In #4443 we learned that these checks take up some time.  In a recent run it takes 100ms out of about a 2.5s run, so around 4%

There are a couple of ways to address this:

1. We can try to find some other cheaper check
2. We can make all of our handlers `async def` functions and asyncify the entire codebase (we should also check that this doesn't incur other costs if so)

cc @dask/scheduler-performance

**Comment by fjetter** [comment]
A third alternative to avoid the binding of the instance is to define handlers based on the class methods but not the instance methods, e.g. `handlers = {"op": Worker.handler}` instead of `handlers = {"op": self.handler}`. We'd need to modify handle_stream, etc. accordingly, of course

**Comment by mrocklin** [comment]
Yup, that could make sense.  I recommend that we just go ahead with this for now though and see if any future work is actually necessary.  (I suspect that this is also your plan)

**Comment by ian-r-rose** [comment]
There are some year-old tests on the average duration `is_coroutine_function` this in this comment: https://github.com/dask/distributed/pull/4474#issuecomment-772871716. I don't know whether this would be reproducible on today's code base, but back then we see a few percent for a scheduler-bound computation.

At the time, I preferred moving to fully async stream handlers (that's what was done in #4474), but we went for caching to have a smaller API change.
