### ISSUE TITLE
Missing fixture when using distributed.utils_test.client fixture in pytest

### ISSUE THREAD

**Issue by wtbarnes** [dask/distributed#4479]
**What happened**:

When attempting to use the `distributed.utils_test.client` in a test suite for one of my packages, my tests error out due to a missing fixture `loop` that is required by the `client` fixture. The traceback is pasted below in the MCVE.

**What you expected to happen**:

To be able to use the `client` fixture without raising an error when running tests that require a `distributed.Client` instance.

**Minimal Complete Verifiable Example**:

```python
from distributed.utils_test import client


def test_foo(client):
    def inc(x):
        return x + 1
    foo = client.submit(inc, x)
```

when running this as,

`pytest test-dask-client-fixture.py` (where I've put the above snippet in a file called `dask-client-fixture.py`), I get the following error message from pytest,

```
======================================================= test session starts ========================================================
platform darwin -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/wbarnes/Desktop
collected 1 item

test-dask-client.py E                                                                                                        [100%]

============================================================== ERRORS ==============================================================
____________________________________________________ ERROR at setup of test_foo ____________________________________________________
file /Users/wbarnes/Desktop/test-dask-client.py, line 4
  def test_foo(client):
file /Users/wbarnes/miniconda3/envs/dask-fresh/lib/python3.8/site-packages/distributed/utils_test.py, line 543
  @pytest.fixture
  def client(loop, cluster_fixture):
E       fixture 'loop' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/wbarnes/miniconda3/envs/dask-fresh/lib/python3.8/site-packages/distributed/utils_test.py:543
===================================================== short test summary info ======================================================
ERROR test-dask-client.py::test_foo
========================================================= 1 error in 5.25s =========================================================
```

**Environment**:

- Dask version: 2021.1.1
- Python version: 3.8.5
- pytest version: 6.2.2
- Operating System: macOS 10.15.3 (I've also encountered this on Ubuntu 18.04.5)
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @wtbarnes! 

The fixtures defined in `distributed.utils_test` aren't part of the public API and, in general, aren't guaranteed to work outside of the `distributed` codebase. In this particular case, you can import the `loop` and `cluster_fixture` fixtures from the same module and things should work:

```python
from distributed.utils_test import client, loop, cluster_fixture

def test_foo(client):
    def inc(x):
        return x + 1
    foo = client.submit(inc, 1)
```

FWIW if you would like to use some `distributed`s test suite machinery in another project, I would recommend taking a look at `gen_cluster`

https://github.com/dask/distributed/blob/98570fbcd662bc0fe468ccba9d57d582d2a3c678/distributed/utils_test.py#L828-L843

It's used extensively throughout the codebase here (see [here](https://github.com/dask/distributed/blob/98570fbcd662bc0fe468ccba9d57d582d2a3c678/distributed/tests/test_client.py#L321-L333) for an example) and is used in a variety of other project's test suites.

**Comment by wtbarnes** [comment]
Thanks for the really quick reply @jrbourbeau! 

Ah ok. I figured it was primarily for internal use so I will keep that in mind. Adding those extra imports works in my case.

Thanks for the pointer about the `gen_cluster` decorator. In my case, I would like the client (and cluster) to persist across multiple tests in my test suite. What is the preferred option in that case?

**Comment by jrbourbeau** [comment]
Hmm in that case, you might be best off creating your own fixture where you set the `scope=` keyword in `pytest.fixture`. For example, something along the lines of (haven't tested the snippet below at all):

```python
from distributed import LocalCluster

@pytest.fixture(scope="session")
def test_cluster():
    with LocalCluster() as cluster:
        yield cluster
```

**Comment by wtbarnes** [comment]
Ok I will give that a try. I had previously just naively defined a fixture that returned a cluster without a context manager or a `yield` statement. 

I'll go ahead and close this as my original issue is clearly fixed by just adding the additional imports. Thanks!

**Comment by jrbourbeau** [comment]
Sounds good. Good luck @wtbarnes!
