### ISSUE TITLE
Failure in test_worker_task_data

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#4493]
Am seeing a failure when running `test_worker_task_data` using latest Dask ( https://github.com/dask/dask/commit/a14e47f84556800411ad180abb5ff4a779275e8f ). This goes away when switching to the latest Dask release.

**What happened**:

(snipped exception from test included below)

```python
../../miniconda/envs/dask/lib/python3.8/site-packages/tornado/ioloop.py:530: in run_sync
    return future_cell[0].result()
distributed/utils_test.py:912: in coro
    result = await future
../../miniconda/envs/dask/lib/python3.8/asyncio/tasks.py:491: in wait_for
    return fut.result()
distributed/tests/test_worker.py:352: in test_worker_task_data
    xx = c.persist(x)
distributed/client.py:2957: in persist
    result = [
distributed/client.py:2958: in <listcomp>
    func({k: futures[k] for k in flatten(c.__dask_keys__())}, *args)
../dask/dask/delayed.py:511: in _rebuild
    return Delayed(key, dsk, self._length)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Delayed('int-41927912-56cf-43f0-a538-9921d96b1d31'), attr = '_length'

    def __getattr__(self, attr):
        if attr.startswith("_"):
>           raise AttributeError("Attribute {0} not found".format(attr))
E           AttributeError: Attribute _length not found

../dask/dask/delayed.py:535: AttributeError
```

**What you expected to happen**:

No exception

**Minimal Complete Verifiable Example**:

```bash
$ python -m pytest -vv -k test_worker_task_data distributed/tests/test_worker.py
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.2.0+3.ga14e47f8
- Distributed version: 2021.2.0
- Python version: 3.8.6
- Operating System: macOS
- Install method (conda, pip, source): conda + source

**Comment by jakirkham** [comment]
Restarted test suite on Distributed `master` to reproduce

https://github.com/dask/distributed/runs/1860516778

**Comment by crusaderky** [comment]
Cannot reproduce against dask-2021.2.0+1.g2640241fb

**Comment by jakirkham** [comment]
Restarted CI on `master` now that the fix is in Dask

https://github.com/dask/distributed/runs/1867272924
