### ISSUE TITLE
Move default branch from "master" -> "main"

### ISSUE THREAD

**Issue by jsignell** [dask/distributed#4496]
@jrbourbeau and I are in the process of moving the default branch for this repo from master to main. 

 - [x] Changed in GitHub
 - [x] Merged PR to change branch name in code (xref #4495) 
 
### What you'll see
Once the name on github is changed (the first box above is Xed, or this issue closed), when you try to `git pull` you'll get 

```bash
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

### What you need to do

First: **head to your fork and rename the default branch there**
Then:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by jrbourbeau** [comment]
I'm going to pin this issue to increase it's visibility

**Comment by jakirkham** [comment]
Should we close this issue now that this is done? Or are we keeping this to guide devs through the change? If the latter, when do you think we should close this?

**Comment by jsignell** [comment]
I haven't heard any complaints so fine to close for me.
