### ISSUE TITLE
Client.cancel: leaking memory and KeyError

### ISSUE THREAD

**Issue by sk1p** [dask/distributed#4510]
**What happened**: when repeatedly creating and canceling futures, memory usage continues to grow, until the `Nanny` restarts the worker. Also, sometimes a `KeyError` is thrown:

```
distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/home/alex/source/distributed/distributed/core.py", line 496, in handle_comm
    result = handler(comm, **msg)
  File "/home/alex/source/distributed/distributed/scheduler.py", line 3438, in heartbeat_worker
    ws._executing = {
  File "/home/alex/source/distributed/distributed/scheduler.py", line 3439, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'workload-74833e33-b74a-4383-aa0a-ca2928f49bb1'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f5e042802e0>>, <Task finished name='Task-12' coro=<Worker.heartbeat() done, defined at /home/alex/source/distributed/distributed/worker.py:936> exception=KeyError('workload-74833e33-b74a-4383-aa0a-ca2928f49bb1')>)
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/dd/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/alex/.virtualenvs/dd/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/alex/source/distributed/distributed/worker.py", line 942, in heartbeat
    response = await retry_operation(
  File "/home/alex/source/distributed/distributed/utils_comm.py", line 384, in retry_operation
    return await retry(
  File "/home/alex/source/distributed/distributed/utils_comm.py", line 369, in retry
    return await coro()
  File "/home/alex/source/distributed/distributed/core.py", line 861, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/alex/source/distributed/distributed/core.py", line 660, in send_recv
    raise exc.with_traceback(tb)
  File "/home/alex/source/distributed/distributed/core.py", line 496, in handle_comm
    result = handler(comm, **msg)
  File "/home/alex/source/distributed/distributed/scheduler.py", line 3438, in heartbeat_worker
    ws._executing = {
  File "/home/alex/source/distributed/distributed/scheduler.py", line 3439, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'workload-74833e33-b74a-4383-aa0a-ca2928f49bb1'
```

**What you expected to happen**: memory usage should stay constant, and no errors should be throws. It should be possible to run the example indefinitely, without running into worker restarts or other memory problems.

**Minimal Complete Verifiable Example**:

```python
import gc

import distributed as dd
import numpy as np


def workload():
    size = 1  # in GiB. to speed up memory growth, increase `size` here.
    result = np.ones((size * 1024 // 8, 1024, 1024))
    return result


if __name__ == "__main__":
    n_workers = 16
    client = dd.Client(processes=True, threads_per_worker=1, n_workers=n_workers)

    while True:
        futures = [
            client.submit(workload, pure=False)
            for i in range(n_workers*2)
        ]

        for fut in futures:
            client.cancel(fut)

        # client.run(gc.collect) - workaround: run gc after canceling a future
```

**Anything else we need to know?**: memory usage seems to grow proportional to the result size of the future. Manually forcing a GC run on the workers after cancellation frees up the memory. The following patch silences the `KeyError`, although I don't understand the scheduler code enough to be confident that it is correct:

```diff
diff --git a/distributed/scheduler.py b/distributed/scheduler.py
index c13f5292..3a51ab99 100644
--- a/distributed/scheduler.py
+++ b/distributed/scheduler.py
@@ -3437,6 +3437,7 @@ class Scheduler(SchedulerState, ServerNode):
         if executing is not None:
             ws._executing = {
                 parent._tasks[key]: duration for key, duration in executing.items()
+                if key in self._tasks
             }
 
         if metrics:
```

**Environment**:

- Dask version: 2021.02.0+6.g02a85f78
- Python version: 3.8.6
- Operating System: Linux
- Install method (conda, pip, source): source

**Comment by uellue** [comment]
Running the reproducer with the `gc.collect` part activated on Windows 10 , Python 3.8.5, distributed 2021.2.0 runs out of memory just as quickly as without `gc.collect`. Within seconds, my 32 GB RAM are completely taken up and the system starts swapping heavily.

**Comment by sk1p** [comment]
> Running the reproducer with the `gc.collect` part activated on Windows 10 , Python 3.8.5, distributed 2021.2.0 runs out of memory just as quickly as without `gc.collect`. Within seconds, my 32 GB RAM are completely taken up and the system starts swapping heavily.

You may need to reduce `n_workers` to fit you system - I increased it for mine to make the reproducer "converge" faster.

**Comment by uellue** [comment]
> You may need to reduce `n_workers` to fit you system - I increased it for mine to make the reproducer "converge" faster.

Ah I see! With two workers the "gc version" did improve dramatically and fixed the issue.

**Comment by jakirkham** [comment]
The `KeyError` may be something getting dropped on the `Worker` side. Please see issue ( https://github.com/dask/distributed/issues/4587 ) as one example of this

**Comment by jakirkham** [comment]
Is there a version of Distributed that did work? Would start by trying 2.30.1

**Comment by sk1p** [comment]
The MCVE above doesn't trigger the memory leak or the key error anymore with the current distributed release, I'm going to close this issue.
