### ISSUE TITLE
Executor.gather hangs when IP to Executor specified

### ISSUE THREAD

**Issue by stsievert** [dask/distributed#452]
On local and remote machines, when I use `exe = Executor()`, everything works. When I use `exe = Executor('10.129.38.93:8786')` (the output of dask-scheduler) it can connect and calls to `exe.map` pass without hanging.

However, calls to `exe.gather` hang. I'm calling `exe.gather` with a list of Futures, the expected use case from [QuickStart#Gather].

My complete script is below (relevant imports trimmed)

``` python
# `dask-scheduler` is being run and has printed "INFO - Scheduler at 10.129.38.93:8786"
e = Executor('10.129.38.93:8786')  # hangs on e.gather(x)
# e = Executor()  # this works; doesn't hang on e.gather(x)

def foo(a):
    time.sleep(1)
    return {'a': a, 'b': 10}

if __name__ == "__main__":
    a = [1, 2, 3, 4, 5, 6]
    x = e.map(foo, a)
    x = e.gather(x)
    print(x)
```

When it hangs, I can still ping `10.129.38.93`.

I've spent a couple hours seeing if this is local to my machine. Any suggestions/tips?

[QuickStart#Gather]:http://distributed.readthedocs.io/en/latest/quickstart.html#gather

**Comment by mrocklin** [comment]
Can you verify that you have workers connected to the scheduler?  This is consistent with these futures never completing.

What is the output of `e.ncores()`

**Comment by stsievert** [comment]
I added a print statement for `e.ncores()`, and it printed `{}`.

**Comment by mrocklin** [comment]
That means that the scheduler isn't seeing any workers.  

If you start up a scheduler with 

    dask-scheduler

Then you also need to give it some workers.  These are other processes that you start with 

    dask-worker 127.0.0.1:8786

`Executor()` does both steps for you

**Comment by mrocklin** [comment]
@stsievert does this work for you?  Closing soon if no resposne

**Comment by stsievert** [comment]
It worked. I'll probably submit a PR to make this issue more clear in the docs.

**Comment by mrocklin** [comment]
Great.  Thank you!

**Comment by stsievert** [comment]
Doc clarification added in #459
