### ISSUE TITLE
UCP get_config

### ISSUE THREAD

**Issue by alvarozamora** [dask/distributed#4520]
I tried running the kNN search example on the cuml GitHub, but I got an error while initializing ucp for dask, namely an import error:

`ImportError: cannot import name 'get_config' from 'ucp'`

Here is the code I ran:

```
# Initialize UCX for high-speed transport of CUDA arrays
from dask_cuda import LocalCUDACluster

# Create a Dask single-node CUDA cluster w/ one worker per device
cluster = LocalCUDACluster(protocol="ucx",
                           enable_tcp_over_ucx=True,
                           enable_nvlink=True,
                           enable_infiniband=False)

from dask.distributed import Client
client = Client(cluster)

# Read CSV file in parallel across workers
import dask_cudf
df = dask_cudf.read_csv("omitted/my/csv/path")

# Fit a NearestNeighbors model and query it
from cuml.dask.neighbors import NearestNeighbors
nn = NearestNeighbors(n_neighbors = 10, client=client)
nn.fit(df)
neighbors = nn.kneighbors(df)

```

**Comment by quasiben** [comment]
Is UCX-py installed ?

> conda install -c conda-forge -c rapidsai cudatoolkit=<CUDA version> ucx-proc=*=gpu ucx ucx-py

**Comment by alvarozamora** [comment]
Nope.. will try that now with `cudatoolkit=10.0`

**Comment by quasiben** [comment]
I don't think 10.0 is support any more.  Last release for 10.0 in RAPIDS was 0.14.  I think you may need to upgrade to 10.1 or preferably 11.0

**Comment by alvarozamora** [comment]
I'll try 11.0 then

**Comment by jakirkham** [comment]
Did you have any more questions here @alvarozamora?

**Comment by alvarozamora** [comment]
all is good
