### ISSUE TITLE
pandas hashtable KeyError with distributed scheduler on column selection

### ISSUE THREAD

**Issue by gforsyth** [dask/distributed#4525]
**What happened**: `KeyError` stack trace from `pandas` when selecting a column of a dask dataframe and inspecting `head`

Full stacktrace is here: https://gist.github.com/gforsyth/f3425d6bd37e6f0b68ba46dbf8121efd

**Minimal Complete Verifiable Example**:

```python

from dask import datasets
from distributed.client import Client
c = Client()
ddf = datasets.timeseries()
ddf = ddf[["x"]]
ddf.head()
```

**Anything else we need to know?**:
I've tried this with pandas `1.0.x`, `1.1.x` and `1.2.x`

This doesn't happen when:
a) I use the processes scheduler, e.g.

```
In [8]: import dask

In [9]: ddfhead = ddf.head(compute=False)

In [10]: dask.compute(ddfhead, scheduler="processes")
Out[10]: 
(                            x
 timestamp                    
 2000-01-01 00:00:00  0.581005
 2000-01-01 00:00:01  0.578595
 2000-01-01 00:00:02  0.423835
 2000-01-01 00:00:03  0.334679
 2000-01-01 00:00:04  0.351653,)
```

b) also doesn't happen if I select out the Series instead of the Dataframe, that is

```
In [11]: ddf = datasets.timeseries()

In [12]: ddf = ddf["x"]  # note only one set of brackets

In [13]: ddf.head()
Out[13]: 
timestamp
2000-01-01 00:00:00    0.517800
2000-01-01 00:00:01    0.722214
2000-01-01 00:00:02    0.732969
2000-01-01 00:00:03    0.276553
2000-01-01 00:00:04   -0.931951
Freq: S, Name: x, dtype: float64
```

**Environment**:

- Dask version:
```
In [21]: dask.__version__
Out[21]: '2021.02.0'

In [22]: distributed.__version__
Out[22]: '2021.02.0'
```
- Python version: 3.8.6
- Operating System: OSX 10.15.7
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Hmm I can't seem to reproduce this locally

```python
In [1]: import dask

In [2]: import distributed

In [3]: import pandas as pd

In [4]: dask.__version__
Out[4]: '2021.02.0'

In [5]: distributed.__version__
Out[5]: '2021.02.0'

In [6]: pd.__version__
Out[6]: '1.2.1'

In [7]: from dask import datasets
   ...: from distributed.client import Client
   ...: c = Client()
   ...: ddf = datasets.timeseries()
   ...: ddf = ddf[["x"]]
   ...: ddf.head()
Out[7]:
                            x
timestamp
2000-01-01 00:00:00 -0.929299
2000-01-01 00:00:01  0.767281
2000-01-01 00:00:02  0.758069
2000-01-01 00:00:03  0.889771
2000-01-01 00:00:04  0.331287
```

You mentioned you tried on pandas `1.2.x`. What was the specific version you have locally?

**Comment by gforsyth** [comment]
Hey @jrbourbeau -- I was on pandas `1.2.2` -- I've dropped to `1.2.1` and still hitting the same error.

Ahh, I just discovered an important bit of info I had missed.

This only happens if `optimization.fuse.active = False`

**Comment by jrbourbeau** [comment]
> This only happens if optimization.fuse.active = False

Ah, I see. I'm am able to reproduce the `KeyError: "('x',)"` when I turn off low-level task fusion. Though when I try the same thing with the latest dev version of Dask, things work as expected:

```python
In [1]: import dask

In [2]: dask.config.get("optimization.fuse.active")
Out[2]: True

In [3]: with dask.config.set({"optimization.fuse.active": False}):
   ...:     print(f'{dask.config.get("optimization.fuse.active") = }')
   ...:     from dask import datasets
   ...:     from distributed.client import Client
   ...:     c = Client()
   ...:     ddf = datasets.timeseries()
   ...:     ddf = ddf[["x"]]
   ...:     print(ddf.head())
   ...:
dask.config.get("optimization.fuse.active") = False
                            x
timestamp
2000-01-01 00:00:00  0.952899
2000-01-01 00:00:01  0.832474
2000-01-01 00:00:02  0.266802
2000-01-01 00:00:03 -0.002417
2000-01-01 00:00:04  0.457181
```

Could you try with the latest dev version?

**Comment by jrbourbeau** [comment]
Specifically, it looks like https://github.com/dask/dask/pull/7213 is what fixed this

**Comment by gforsyth** [comment]
Yep, that did it.  I had tried with an updated version of `distributed` locally but not `dask`.  Thanks!

**Comment by jrbourbeau** [comment]
Awesome! Glad things are working (thanks again @rjzamora)
