### ISSUE TITLE
Some tests require numpy and fail if not present

### ISSUE THREAD

**Issue by bnavigator** [dask/distributed#4529]
For reason's briefly discussed in https://github.com/dask/dask/issues/7170#issuecomment-780872128, openSUSE does not have numpy for Python 3.6 in the Tumbleweed distribution anymore. At the same time, we need to have a working test suite to make sure that the built package works (without numpy functionality of course.)

Most tests of distributed involving (runtime optional) numpy are already skipped automatically if numpy is not present. But there are some ERRORs and FAILs:

```
[  150s] FAILED distributed/tests/test_client.py::test_turn_off_pickle[True] - ModuleN...
[  150s] FAILED distributed/tests/test_client.py::test_turn_off_pickle[False] - Module...
[  150s] FAILED distributed/tests/test_client.py::test_de_serialization - ModuleNotFou...
[  150s] FAILED distributed/tests/test_client.py::test_de_serialization_none - ModuleN...
[  150s] FAILED distributed/tests/test_pubsub.py::test_speed - ModuleNotFoundError: No...
[  150s] ERROR distributed/tests/test_nanny.py
[  150s] ERROR distributed/tests/test_utils.py
```

I am using this ad-hoc patch right now. It might need some polishing to meet your code standards:

[importorskip-numpy-tests.patch.txt](https://github.com/dask/distributed/files/6018277/importorskip-numpy-tests.patch.txt)

**Comment by jrbourbeau** [comment]
Thanks for reporting @bnavigator! Looking at a few of the tests listed above,  using `np = pytest.importorskip("numpy")` instead of `import numpy as np` will ensure we automatically skip tests when NumPy isn't installed. Feel free to submit your current patch as a PR if you'd like (though no obligation)
