### ISSUE TITLE
Bokeh RC Updates Breaks Dashboard

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#4534]
In `bokeh 2.3.0rc2`, there are some issues with Dask dashboard documented here:
https://github.com/bokeh/bokeh/issues/10935

While Bokeh updates to handle nullables for a variety of objects dask could update the null calls within Bokeh

Setting `None` in x_range:
https://github.com/dask/distributed/blob/383ea0326ae103b5d5e0b62ed9c3cb18510c5b9e/distributed/dashboard/components/scheduler.py#L867-L874

This could be set to `100` which we do in the update:
https://github.com/dask/distributed/blob/383ea0326ae103b5d5e0b62ed9c3cb18510c5b9e/distributed/dashboard/components/scheduler.py#L994

We also have a `None` in the Profile plot selector:
https://github.com/dask/distributed/blob/383ea0326ae103b5d5e0b62ed9c3cb18510c5b9e/distributed/dashboard/components/shared.py#L277

I believe the defaults here is `['All', None]

**Comment by bryevdv** [comment]
AFAIK the code above would fail to render *initially*, but the raised error was not critical, and things "worked" in the sense that a later updating to meaningful values later allowed subsequent renders to succeed. We will make some temporary easements to strict nullability now to prevent immediate breakage for Dask users, but it would certainly be good to update these on your end as soon as is practical.

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/issues/10935 is merged and part of 2.3.0rc3 which is available via
```
conda install -c bokeh/c/dev bokeh=2.3.0rc3
```
Would be really great if someone on the the dask side could check it out and give a 👍 (we would like to release tomorrow)

**Comment by bryevdv** [comment]
I followed the procedure outlined here: https://github.com/bokeh/bokeh/issues/10935#issuecomment-783835213 and there seems to be one issue, with the task graph, so we will plan to postpone a day until it can be resolved.

**Comment by jakirkham** [comment]
This was fixed right?

**Comment by quasiben** [comment]
Fixed on the bokeh side but I still plan change a the xrange and select defaults
