### ISSUE TITLE
System tab (scheduler resources) widget

### ISSUE THREAD

**Issue by rikturr** [dask/distributed#4539]
Love this project! It's so much fun to watch all the widgets moving along while doing Dask work :) 

It would be helpful to have a widget for the /system page from the standalone dashboard

![image](https://user-images.githubusercontent.com/8964039/107394567-06813080-6aca-11eb-80d5-153e0e1c41ed.png)

**Comment by jacobtomlinson** [comment]
This has been merged and will be in the next release
