### ISSUE TITLE
worker : params processing done twice (nanny and worker)

### ISSUE THREAD

**Issue by alikefia** [dask/distributed#4547]
When starting a worker with set `temprary-directory`, the `dask-worker-space` suffix is joined twice.

```
(pydata) ali@localhost:~/hacks/pydata$ cat "${DASK_CONFIG}/dask.yaml" | grep temporary
temporary-directory: '/tmp'
(pydata) ali@localhost:~/hacks/pydata$ dask-worker tcp://localhost:8786
nanny -> /tmp
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:37347'
worker -> /tmp/dask-worker-space
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:45815
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:45815
distributed.worker - INFO -          dashboard at:            127.0.0.1:33133
distributed.worker - INFO - Waiting to connect to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.08 GB
distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/dask-worker-space/worker-mauez8mj
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```
The issue here is that the path is processed twice : Nanny and Worker

More generally, I think that parameters verification logic is duplicated on both classes and probably needs to be consolidated on one side for maintenance reasons (probably the worker since the nanny is just a wrapper)

**Environment**:

- Dask version: 2021.02.0+20.g1c9a9622
- Python version: 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): source

**Comment by martindurant** [comment]
I an confirm this, will look into a fix.

**Comment by alikefia** [comment]
I was thinking to make a larger review of the overlap between nanny and worker code (preloads, temporary_dir, etc.).
I don't understand why the Nanny does not send empty params (without any processing to set defaults) and let worker manage.
Is there any usage of Nanny other than wrapping a worker?

**Comment by martindurant** [comment]
The only use of local_directory is for preloads. I don't know if nanny preloads are used. You are generally right that the duplication of kwargs and processing of them, where those kwargs are used by the worker only, not nanny, could do with being passed on unaltered (like Client does for LocalCluster).

**Comment by alikefia** [comment]
Agree with the fix.
The nanny process has its own preloads and needs the temp dir for that.
Thx a lot for help !
