### ISSUE TITLE
Different behavior when running dask in a distributed environment 

### ISSUE THREAD

**Issue by Gabrielsvc** [dask/distributed#4578]
**What happened**: I've been trying to run Dask on a distributed environment using SLURM. I can run this example when connecting to a node, and executing the code(with salloc), but when i send the job to slurm (by running sbatch), i get the error in the gist bellow. I've checked both environment variables in both cases and they seem to be the same

https://gist.github.com/Gabrielsvc/038d1e2b786c64a83983aa298d9f3f65

**What you expected to happen**: I would expect the same behavior from both executions, it seems to be related to memory, but i've failed to identify the problem. It looks like in some way slurm limits dask access to memory.

**Minimal Complete Verifiable Example**:

```python
from distributed import Client, wait
from distributed import LocalCluster
n = 100

def vectest(x):
        data  = [0 for k in range(n**3)]
        for i in data:
                i = i + x
        return data

if __name__ == "__main__":
        data = [1,2,3]
        cluster = LocalCluster(n_workers = 2, memory_limit = 0)
        client = Client(cluster)
        results = []
        for x in data:
                results.append(client.submit(vectest,x))
        wait(results)
        for i in results:
                print(i.result())
```

**Anything else we need to know?**: 

**Environment**:

- Dask version: 2.30
- Python version: 3.8.5
- Operating System: Red Hat 7.6
- Install method (conda, pip, source): conda 4.9.2

**Comment by quasiben** [comment]
It would be more helpful if you posted the error as a gist or inlining some section of traceback in the github issue.  

However, looking at the versions you have, `2.30` is quite old at this point.  Can you upgrade and re-run ?  Latest release is `2021.03.0`

**Comment by Gabrielsvc** [comment]
I will see if it's possible, thanks for the quick feedback!

**Comment by Gabrielsvc** [comment]
I've been in contact with the technical support of the Cluster, where they tried to run my same example using Dask latest version, encountering the same problem. They said that the problem might be on port communication between the nodes

**Comment by jacobtomlinson** [comment]
Workers and the scheduler communicate via random high ports. Do you think you might have firewall rules on your cluster preventing this?

**Comment by Gabrielsvc** [comment]
It could be, but doesn't make much sense, since the workers are receiving the jobs. So far we having the following executions tested:

1. Running in a node by connecting to it with salloc (runs fine)
2. Running in a node by sending a job with sbatch (fails)
3. Setting up Workers and schedulers in different nodes with sbatch and then running it from a new node with salloc (fails)
4. Setting up Workers and schedulers in different nodes with sbatch and then running it with a new node with sbatch (fails)

Next test that will be done is setting manually workers and scheduler in the same node and then trying to run the code from this same node. It is weird since it look like a memory problem, with a lower dimension array (n**2, as an example) the example runs, but i'm absolutely sure the cluster has enough memory to compute the code given.

**Comment by Gabrielsvc** [comment]
The failure seems to happens due to some configuration on the Supercomputer, will improve further as more information is given by technical support. For now, I'm closing this issue.
