### ISSUE TITLE
Scheduler fails to add worker when Scheduler.add_worker is called in a synchronous environment.

### ISSUE THREAD

**Issue by buotex** [dask/distributed#4580]
**What happened**:
Since the dask/distributed *2021.02.0* release, whenever I try to create an extra worker in a synchronous setting, dask hangs.

**What you expected to happen**:
I expect the worker to be created and the call finishing.

**Minimal Complete Verifiable Example**:

```python
import asyncio
from dask.distributed import Client


async def create_worker(client):
    worker = client.scheduler.add_worker()
    await worker
    return worker


def test_dask():
    client = Client()
    worker = asyncio.get_event_loop().run_until_complete(create_worker(client))
```

**Anything else we need to know?**:
This behavior seems to have started with the split of SchedulerState and I get the following error:
```
test_dask.py::test_dask distributed.core - WARNING - No handler add_worker found in Scheduler
Traceback (most recent call last):
  File "/home/xub2rng/.pyenv/versions/miniconda3-latest/envs/testing/lib/python3.8/site-packages/distributed/core.py", line 482, in handle_comm
    handler = self.handlers[op]
KeyError: 'add_worker'
```
And whether the `await worker` call progresses is very flaky - sometimes it does, sometimes dask hangs.
**Environment**:

- Dask version: 2021.02.0
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
The scheduler is not responsible for creating workers.  You _could_ create workers programmatically by doing something like the following:

https://github.com/dask/distributed/blob/e734fc3de5d6c3a938413fb0a3dfa08d298e2fbe/distributed/tests/test_worker.py#L1031

However, this is not too common. Typically, workers are either created with `LocalCluster/Client`, `dask-worker`, or other [cluster managers](https://docs.dask.org/en/latest/setup.html)

**Comment by buotex** [comment]
Ok, I'll use that workflow then.
