### ISSUE TITLE
Incorrect number of futures with client.map if both keys and batch_size are specified

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/distributed#4588]
If both `keys` and `batch_size` are specified, then the number of `futures` created with `client.map` is incorrect. Here's a reproducible example:

```python
from dask.distributed import Client
client = Client()
futs = client.map(lambda x: x**2, list(range(20)), batch_size=5, key=[f"{x}" for x in list(range(20))])
print(len(futs)) # prints 80
```

If you try to collect these futures with `client.gather` then client will hang indefinitely.

This has to do with simultaneously specifying `batch_size` and custom `key` list, removing either of them will generate the correct number of futures.

I suspect the problem is in line 1701 here: https://github.com/dask/distributed/blob/4ce8c65039e9b531878f9d77cf884920690a3745/distributed/client.py#L1692-L1716

Specifically, it seems that the same keys are passed to every batch, this is problematic if key is a list. My suggested fix for this is to modify it as follows (code removed, it was faulty, see PR for working code).

Would be happy to submit PR if this code makes sense.

**Environment**:

- Dask version: 2021.02.0
- Python version: 3.6
- Operating System: MacOS
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for reporting @SultanOrazbayev. Batching the user-specified keys in this case seems like the right thing to do. A PR would be welcome

**Comment by SultanOrazbayev** [comment]
Great, I'll work on it now.
