### ISSUE TITLE
Allow specifying worker resources on a per thread basis

### ISSUE THREAD

**Issue by kkraus14** [dask/distributed#4598]
Currently specifying worker resources happens on a per-process basis: https://distributed.dask.org/en/latest/resources.html#resources-are-applied-separately-to-each-worker-process

We have use cases where we'd ideally like to specify resources on a per thread basis. I.E. I'd want a worker with say 5 threads, 1 of which has a GPU resource, the other 4 of which have a CPU resource. We could then use those CPU resources to stage data for the GPU resourced thread to process. Ideally these would be in the same process so that the memory doesn't need to be transported across processes.

**Comment by mrocklin** [comment]
I think that it might be fun to consider Dask workers that have multiple concurrent.future.Executor types.  This would solve a few problems that we see today:

1. People who want to run tasks in separate processes for better isolation
2. Situations where we have async tasks like IO (cc @martindurant )
3. This situation, where we want to associate and constrain certain resources 

Anyway, I think that thinking about multiple executors might be a possibly more general modification that would give you all what you want, and also engage a few other groups at the same time.

**Comment by martindurant** [comment]
I would add "actors" to this list, which is the only case that already has its own executor, but probably shouldn't.

For IO, fsspec will no longer (on current main) create a separate thread for the event loop, but will run a loop with `run_until_complete` in the thread where it's called. I'm not sure if that affects the discussion - now the workload will be mixed between IO waiting and any other computing.

**Comment by crusaderky** [comment]
> I'd want a worker with say 5 threads, 1 of which has a GPU resource, the other 4 of which have a CPU resource.

Is there a particular need to pin these resources to a specific thread? As of now, if you specify ``--nthreads 5 --resources GPU 1 CPU 4`` you should get exactly what you described but the jobs will be run by arbitrary threads.

**Comment by kkraus14** [comment]
> Is there a particular need to pin these resources to a specific thread? As of now, if you specify `--nthreads 5 --resources GPU 1 CPU 4` you should get exactly what you described but the jobs will be run by arbitrary threads.

Sorry yes, I should have clarified that. The use cases I have in mind are related to using the CPU threads to stage data for a GPU thread to asynchronously execute work. If the GPU thread changes, then we'd need to enforce some type of synchronization behavior between the threads for the GPU to do things safely and that gets pretty gross pretty quick.

**Comment by crusaderky** [comment]
@kkraus14 could you make an example? Isn't your issue solved by using either the legacy default stream or a process-wide explicit stream? On the other hand, if you're already using multiple cudaStreamNonBlocking streams to allow for pipelining between kernel and RAM transfers, aren't they supposedly thread-safe?

Ref. https://docs.nvidia.com/cuda/cuda-driver-api/stream-sync-behavior.html

**Comment by kkraus14** [comment]
@crusaderky Would be hard to write up a code example but let me write up a pseudo-example that I had in mind.

Say I'm using `per-thread default stream` (https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html) and my library / tasks don't explicitly synchronize the stream. The task would return effectively as soon as the kernel launch is done as opposed to when the work is actually done. Say I then have some type of task graph, we can assume it's a linear chain of tasks for now for simplicity sake, `data (CPU) --> A --> B --> C --> D --> E`, if each task can get scheduled on an arbitrary thread, then task `B` could have a kernel launch on a different thread which could attempt to read the result of task `A` before it's safe to do so. If I'm only doing a single task on the GPU at a time then there's no real benefit from using the `per-thread default stream` vs the `legacy default stream`, but we could imagine a world where I have say a `GPU0:0` resource and a `GPU0:1` resource and want those resources assigned to specific threads in order to handle multiple of the linear task graphs concurrently on a single GPU.

**Comment by crusaderky** [comment]
@kkraus14 I understand the use case now, but it feels to me like yours may be the wrong solution to the problem.
Namely, a design where you manually name 2+ swimlanes to allow pipelining in the GPU falls apart when you have to deal with it inside a wrapper - namely, if you want to pipeline different chunks of the same dask.array.

Maybe a better design would be a NEP-18 compliant wrapper around cupy, that also rewraps the outputs (see pint.Quantity) and that keeps track of the streams?

**Comment by kkraus14** [comment]
The challenge we face is that our users are often times using multiple libraries which can't share explicitly defined streams (larger problem we're working on solving), where the only way to get them to all target the same stream so we can enqueue kernels properly is to use either the legacy default stream or per-thread default stream.

We aren't explicitly talking about Arrays or DataFrames here, where it could be dealing with more general Dask collections, i.e. I use my CPU threads to do IO and stage data in pinned host memory in some type of wrapper objects that exposes a protocol like `__array_interface__` or python buffer protocol, then have my GPU threads running tasks that could use CuPy, Numba, RAPIDS, PyTorch, Tensorflow, etc. where they can all share data zero-copy between one another via `__cuda_array_interface__`. There's no requirement of them to synchronize before returning their object, so even though Dask thinks a task has finished, the kernel / memcpy / etc. could still be running under the hood, meanwhile Dask could get going on the next Python task which could enqueue more work on the stream.

**Comment by crusaderky** [comment]
> multiple libraries which can't share explicitly defined streams

It shouldn't be a problem as long as each library can build its own flavour of Stream python wrapper around an external int*?

**Comment by kkraus14** [comment]
> It shouldn't be a problem as long as each library can build its own flavour of Stream python wrapper around an external int*?

Someone recently explored this and it got pretty gross pretty quickly between some of the more "cooperative" libraries: https://gist.github.com/leofang/4a043e5d94b4702d04fde2b9e7dcebbd

When you add in a DL framework things get much messier. But even just with the above I don't think end users should be expected to do this type of ninja coding, and solving the underlying interoperability challenges are going to take a long time. Even if a user is only using a single library doing explicit stream management is non-trivial versus using per-thread default stream in many situations.
