### ISSUE TITLE
Add key/value state manager to the scheduler

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#4607]
Cluster manager objects contain state. As experienced in `dask-gateway` and also now in `dask-ctl` if you want to destroy a cluster manager without destroying the cluster and then later create a new cluster manager to represent that existing resource the state needs to persist somewhere.

`dask-gateway` has opted to run a database alongside the service and serialize state into that database, allowing newly created cluster managers to deserialize that state.

In `dask-ctl` I have started down the road of implementing cluster manager specific serializations. For example in dask/dask-kubernetes#318 I have attempted to serialize the object into a Kubernetes Secret.

While working on that PR I found it to be very inconvenient managing the state this way, and it also came with some drawbacks. Specifically that I only serialized state at create time, so any internal state that changes over time such as the new worker name (an internal counter) is not stored.

I also have concerns that not all platforms (batch systems in particular) will have a convenient way to store cluster state.

One thing that is consistent between all clusters is the scheduler. The discovery mechanism in `dask-ctl` is intended to find schedulers (and everything else) and then reconstruct the object around them. One solution to managing state would be to sync that state over to the scheduler, so when reconstructing an object if we can find the scheduler using platform specific means and connect to it we would be able to retrieve the state from there.

Therefore I propose adding a key/value store within the scheduler that can be used via the RPC. My intended implementation would be to have a dictionary in both the `Scheduler` and `Cluster` objects which would be kept in sync via the RPC. I think it would be fine to insist that only JSON serializable objects can be stored here.

**Comment by mrocklin** [comment]
Having get/set routes for msgpack serailizable data in the `Scheduler`, or even down in the`Server` class sounds fine to me.  This should also be pretty trivial to implement.

**Comment by jrbourbeau** [comment]
The scheduler already has `get_metadata` & `set_metadata` methods / handlers. I've not looked at them in a while, but they might be of use here
