### ISSUE TITLE
pickle_loads attempts item assignment with tuple

### ISSUE THREAD

**Issue by JSKenyon** [dask/distributed#4611]
**What happened**:
I am using the `main` branch in order to play with annotation functionality as well as to circumvent other serialization problems. However, the changes made in https://github.com/dask/distributed/pull/4541 seem to have broken my application. In particular,  
https://github.com/dask/distributed/blob/98148cbfee818889f683c4be0e591d33a59ffdf8/distributed/protocol/serialize.py#L70-L84 triggers messages like:
```
File "/site-packages/distributed/protocol/serialize.py", line 78, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
```
@madsbk could you please help me understand the specific condition that would trigger this failure?

**What you expected to happen**:
I expected no change - the `2021.02.0` versions don't seem to have the problem. 

**Minimal Complete Verifiable Example**:

I don't have a specific example, rather I am fairly certain that `buffers` is of type tuple and item assignment will never be successful.

**Environment**:

- Dask version: `main` as of 19 March 2021
- Python version: 3.8.8
- Operating System: Pop!_OS 18.04
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
I think this has been resolved in https://github.com/dask/distributed/pull/4595 .  Can you try latest in main ?

**Comment by JSKenyon** [comment]
I was using main from today and I believe that the PR you linked went in
yesterday. I think that the issue is present before and after that merge
with the original source of the problem being the PR I linked above.

**Comment by quasiben** [comment]
@JSKenyon the error reported looks like an older version of serialize compared to latest in main. Can you double check that latest is installed correctly ?
> python -c 'import distributed;print(distributed.__version__)'
I have `2021.03.0+18.g98148cbf`

**Comment by JSKenyon** [comment]
I just reinstalled to be extra sure and the problem has indeed gone away. Maybe I made a mistake when setting up my environment earlier (that or I somehow ended up one version behind `main`). Reagardless, thanks for the help @quasiben!

**Comment by quasiben** [comment]
Thanks for reporting and confirm the issue was resolved!
