### ISSUE TITLE
Import of distributed created an IOLoop

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#4616]
In `distributed.comm.tcp`:
```python
class BaseTCPConnector(Connector, RequireEncryptionMixin):
    _executor = ThreadPoolExecutor(2, thread_name_prefix="TCP-Executor")
    _resolver = netutil.ExecutorResolver(close_executor=False, executor=_executor)
    client = TCPClient(resolver=_resolver)
```
the `ExecutorResolver`, which is evaluated and instantiated at import time, creates a tornado IOLoop and whichever asyncio loop underneath, and sets these as the "default" for the current thread, usually the main thread. I don't immediately know the consequences of this, but it seems like a bad idea.

**Comment by martindurant** [comment]
Interestingly, xarray imports distributed when accessing some backends, to use one of the locks, so this can happen on any `xr.open_dataset` call.

**Comment by mrocklin** [comment]
I agree that it is generally good to avoid creating things at import time.  Suggestions here would be welcome.

**Comment by martindurant** [comment]
- A data descriptor on a metaclass
- Have a module global container hold the instance
- Have __init__ set the class attribute if it isn't already
 
These could fall foul of races maybe.

I don't gather from the code whether these is an implicit requirement to have these classes live in the main thread.

**Comment by mrocklin** [comment]
Yeah, I don't think anyone knows here.  This is overwriting some Tornado
system that I don't think any of us knows deeply.  I think that the next
thing to do is to try some of the approaches that you mention and see what
happens.

**Comment by shughes-uk** [comment]
Would love to see this get resolved, caused me some grief tracking things down this morning while trying to solve some thread leak issues with our app.

**Comment by QuLogic** [comment]
This is a duplicate of #4521?

**Comment by martindurant** [comment]
> This is a duplicate of #4521?

Yes, I believe so. Unresolved nevertheless.
