### ISSUE TITLE
Dependent not found ('split-simple-shuffle-....)

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#4639]
Doing a dd.merge of two dask dataframes and one of the workers crashes with 
Dependent not found ('split-simple-shuffle-....)

Sorry can't give more details at this point, but will try to add more  if this isn't a known problem already.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @dickreuter. I don't think this is a known issue -- more details are welcome

**Comment by dickreuter** [comment]
looks like the issue is caused by timeouts...
