### ISSUE TITLE
Bokeh nbytes widget flickers after adding workers

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#4675]
1. ``dask-scheduler``
2. open localhost:8787 in your browser
3. ``dask-worker localhost:8786 --nprocs 49 --memory-limit 500MB``
4. the "Bytes stored" widget in the GUI (top left) starts flickering so heavily that it becomes completely unusable. This issue persists well after the workers have finished starting and is only fixed by reloading the page in the web browser.

**Comment by crusaderky** [comment]
I suspect this has to do with updating x_range.end. #4651 dynamically increases x_range.end when there's a lot of spilled data, and I'm seeing a very similar behaviour.

**Comment by jrbourbeau** [comment]
cc'ing @jsignell for visibility

**Comment by ncclementi** [comment]
This issue should have been closed when  PR #4997 was merged, it seems it wasn't triggered when the merging happened. Closing the issue manually.
