### ISSUE TITLE
`dask-worker` option `--death-timeout` does nothing

### ISSUE THREAD

**Issue by charlesbluca** [dask/distributed#4685]
It looks like the `--death-timeout` option for the Dask worker CLI is not passed into the main function and has no effect on the workers or nannies - is this intentional? If so, the option can be removed from the CLI. If not, then `death_timeout` should probably be listed in the CLI's main function and passed on to the workers/nannies.

**Comment by jrbourbeau** [comment]
I think any `click` options not explicitly specified in the `main` function signature will be passed through `kwargs`

https://github.com/dask/distributed/blob/d70314fb8c542ad3c46de724b93271dd98844a4b/distributed/cli/dask_worker.py#L268

You can also try passing a non-default value for `--death-timeout` to confirm it has an affect. For example, locally if I run 

```
dask-worker localhost:8786 --death-timeout 1.23
```

without any scheduler at `localhost:8786 ` then I get the following error message 

```python
asyncio.exceptions.TimeoutError: Nanny failed to start in 1.23 seconds
```

**Comment by charlesbluca** [comment]
Thanks for the clarification - I didn't realize that click args could get passed through `**kwargs`.
