### ISSUE TITLE
DeprecationWarning on python 3.9

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#4711]
[This line](https://github.com/dask/distributed/blob/main/distributed/deploy/spec.py#L342) triggers the following warning on 3.9:
```
/home/gsk/miniconda/envs/lib/python3.9/site-packages/distributed/deploy/spec.py:343: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
    await asyncio.wait(tasks)
```

**Environment**:

- Dask version: 2021.4.0
- Python version: 3.9.2
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for reporting @gsakkis! To avoid this `DeprecationWarning` I think we want to first wrap the coroutine in `asyncio.create_task` before passing it to `asyncio.wait` as outlined [here](https://docs.python.org/3/library/asyncio-task.html#asyncio-example-wait-coroutine). Do you have any interest in submitting a PR?

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/4717
