### ISSUE TITLE
[Feature] Implicit secede/rejoin for client.gather() executed on a worker

### ISSUE THREAD

**Issue by ArtinSarraf** [dask/distributed#4738]
Before I continue with this suggestion, as I'm unfamiliar with the history/details behind the feature, I'd like to first ask if there's a known good reason not to implicitly secede/rejoin when gathering on a worker. A couple possible reasons I can think of:

1) It's a relatively expensive operation, which you would prefer to avoid when you know you have enough workers to avoid a deadlock
2) You don't want to rejoin after the gather, either because (a) you only plan on returning immediately after the gather step, or (b) you want to stay on the "administrative" thread and do some additional non-CPU intensive work

(I would be interested to learn about any other reasons as well)

If either of the 2 points above are valid, I would propose that they be considered the "special case" rather than the "default case". Where the default case would wrap gather in a secede/rejoin. I'd be happy to expand on my reasoning on this in further discussion.

In terms of the gather interface, to account for the cases where you don't want to secede and/or rejoin, I would provide the ability to opt-out on client.gather. Something like this:

```
# forbid explicit secede=False, rejoin=True
results = client.gather(futures, secede=False)  # automatically sets rejoin=False
results = client.gather(futures, rejoin=False)  # secede True by default
```

Potential implementation provided in a PR here: 
https://github.com/dask/distributed/pull/4737

**Comment by fjetter** [comment]
We do have a seceding logic in place in case you are performing a `Client.get` instead of a `Client.gather`, see https://github.com/dask/distributed/blob/2e446ae70f3bfc23853c2a61915f5bd0625ce7d0/distributed/client.py#L2659-L2672
I'm not very familiar with the context of this. cc @jrbourbeau

**Comment by ArtinSarraf** [comment]
@jrbourbeau - thoughts on this? The above snippet that @fjetter provided, suggests to me the usefulness of providing the ability to implicitly gather. If you wanted to write a function that could be run both locally or nested through another worker, it would be tedious to have to write the boilerplate to check if you can/should secede/rejoin.
