### ISSUE TITLE
DOC: changing the number of cores for a worker

### ISSUE THREAD

**Issue by stsievert** [dask/distributed#479]
I use a cluster at UW-Madison, and I'm supposed to be a "responsible citizen" on the cluster downstairs by not using too many cores, too much memory, too much disk space, etc.

In light of this, I looked at changing the number of cores for a `dask-worker` -- I didn't want to use all the 40 cores available to me, maybe only 20.

To change this, I ran `dask-worker --help` first because I'm launching a `dask-worker` on each worker machine. This didn't help much -- it looks like I'm supposed to change `nthreads` (not `nprocs` but changing the number of cores used in a variable called `nthreads` confused me.

``` shell
$ dask-worker --help
...
  --nthreads INTEGER     Number of threads per process. Defaults to number of
                         cores
  --nprocs INTEGER       Number of worker processes.  Defaults to one.
```

I then looked at `distributed.worker.Worker`'s docs and see that it has a `ncores` variable. Is this what `--nthreads` changes? I'd like to change `ncores`, but I'm not certain how to obtain a list of `Worker`s for a `Executor`.

**Comment by mrocklin** [comment]
The dask-worker command line tool starts `nprocs` many `Worker` objects in different processes.  Each `Worker` object has `nthreads` many threads running at once, which corresponds to the `ncores` attribute in the Worker.

You probably to set numbers such that `nthreads * nprocs == 20`

**Comment by stsievert** [comment]
nvm, I'm closing this issue: in practice it's not an issue for me.
