### ISSUE TITLE
Timeout in `test_thread_time`

### ISSUE THREAD

**Issue by pentschev** [dask/distributed#4790]
There was a [timeout in CI when running `test_thread_time`](https://github.com/dask/distributed/pull/4787/checks?check_run_id=2518984863):

```python
_______________________________ test_thread_time _______________________________

    def test_thread_time():
        start = metrics.thread_time()
        run_for(0.05)
        dt = metrics.thread_time() - start
>       assert 0.03 <= dt <= 0.2
E       assert 0.03 <= 0.020078000000012253

distributed/tests/test_metrics.py:48: AssertionError
```

Perhaps the timeout is a bit too tight, should we maybe consider increasing it to `0.3`?

**Comment by quasiben** [comment]
Test test_num_fds also (failed](https://github.com/dask/distributed/pull/4787/checks?check_run_id=2518984824#step:10:2136) because of a timeout

```
E           assert 1620314850.620627 < (1620314840.5793889 + 10)
E            +  where 1620314850.620627 = time()
```

**Comment by quasiben** [comment]
Also seeing a timeout issue on [test_AllProgress_lost_key](https://github.com/dask/distributed/pull/4786/checks?check_run_id=2508907268#step:10:2153) seen on https://github.com/dask/distributed/pull/4786

**Comment by jacobtomlinson** [comment]
`test_AllProgress_lost_key` also spotted in #4785

**Comment by fjetter** [comment]
FWIW I can reproduce this and #4839 reliably locally using `pytest-xdist` with oversubscribed CPUs, i.e. by more processes than actual CPUs. That simulates the heavy load problem of CI.
I would suggest to remove these tests since we're effectively only testing the stdlib here anyhow.

**Comment by mrocklin** [comment]
This doesn't quite test the stdlib.  We needed to make our own timers in
order to support subsecond readings for Windows.  This code is in metrics.py

**Comment by fjetter** [comment]
> We needed to make our own timers in
order to support subsecond readings for Windows.  This code is in metrics.py

That's true for `metrics.time` but not for `metrics.thread_time` and `metrics.process_time`. Here the relevant code

https://github.com/dask/distributed/blob/9d4f0bf2fc804f955a869febd3b51423c4382908/distributed/metrics.py#L86-L95

`timemod` is simply `import time as timemod` https://github.com/dask/distributed/blob/9d4f0bf2fc804f955a869febd3b51423c4382908/distributed/metrics.py#L3
