### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#482]
### History of optional dependencies

Historically with `dask` we made the core library depend only on the standard library.   This was to make downstream dependencies more comfortable with depending on the project, and also isolated dask.array users from Pandas, dask.bag users from NumPy, etc..

However this caused some confusion, because people invariably perform the following:

```
$ pip install dask
>>> import dask.dataframe as dd
```

And they would have wrong versions of Pandas and such.  We tried to push people to `pip install dask[complete]` but education is hard.  From this lesson for `distributed` we just pushed all of the optional dependencies into requirements.txt and waited until someone complained.  Someone has just brought this up, so we should probably switch back to the more dependency-friendly approach of separating core and optional dependencies.
### Current list

Strictly required
-  tornado 
-  toolz
-  msgpack-python or pandas.msgpack
-  cloudpickle
-  dask  (but just core dask, which is pure python and stdlib only)
-  six

Very convenient but could be made optional with some pain
-  click
-  tblib
-  psutil

Strictly optional
-  boto3  (Should be moved to dask regardless)
-  s3fs  (Should be moved to dask regardless)
-  locket  (Used for HDFS work in Python 2)
-  Bokeh (should be added)

cc @GaelVaroquaux

**Comment by mrocklin** [comment]
@GaelVaroquaux is there anything in the strict or convenient list that you think people would find objectionable or non-standard?

**Comment by GaelVaroquaux** [comment]
> Historically with dask we made the core library depend only on the standard library. This was to make downstream dependencies more comfortable with depending on the project, and also isolated dask.array users from Pandas, dask.bag users from NumPy, etc..

Right. I, as someone who runs a scientific research lab, shiver at the
idea of upgrading numpy or pandas, because I need to revalidate my code
to check for subttle changes of behavior that sometimes happen.

> Someone has just brought this up,

Dude, you just outed me! :)

> so we should probably switch back to the more dependency-friendly approach of separating core and optional dependencies.

It might be even more true for distributed than for dask, as it is more
universal.

>   • dask (but just core dask, which is pure python and stdlib only

Any reasons that this part of dask is not moved to distributed, in the
long run? (that a genuine question, I haven't looked at the problem). My
ideal dependencies graph is a DAG, though it's seldom feasible in complex
real-world projects.

>   • boto3 (Should be moved to dask regardless)
>   • s3fs (Should be moved to dask regardless)
>   • locket (Used for HDFS work in Python 2)
>   • Bokeh (should be added)

Should bokeh really be a mandatory dependency?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux is there anything in the strict or convenient list that you think people would find objectionable or non-standard?

I'd push for msgpack-python rather than pandas.msgpack.

I'd push for not depending on dask, but having dask depend on distributed
(seems that distributed is more general than dask, hence the direction of
the arrow).

The rest seems quite fine.

Out of curiosity, what made you prefer cloudpickle to dill?

**Comment by mrocklin** [comment]
> Dude, you just outed me! :)

I hope this is a fun comment and not actual concern :)  If not then you have my very sincere apologies.

>  Any reasons that this part of dask is not moved to distributed, in the long run?

Then we would either have dask.array/dataframe users depending on distributed or we would have code duplication.  In practice core `dask` is very lightweight (again, no dependencies outside of the stdlib) so it seems reasonable to me to keep it where it is for now.  The alternative would be to eventually split apart the dask repository into `dask.core`, `dask.dataframe`, `dask.array`, etc..

The core part that distributed depends on is just things like the graph spec, convenience functions to manipulate graphs, hash down functions and inputs, etc..  This is code that needs to be shared between the algorithmic modules (like dask.array) and the distributed system.

> Should bokeh really be a mandatory dependency?

Bokeh is listed there in the set of purely optional dependencies.  I think that this is accurate.  It's entirely feasible (and common) to run distributed without Bokeh.

**Comment by mrocklin** [comment]
>  I'd push for msgpack-python rather than pandas.msgpack.

Currently the presence of either suffices.  We explicitly depend on `msgpack-python`

> I'd push for not depending on dask, but having dask depend on distributed
(seems that distributed is more general than dask, hence the direction of
the arrow).

The distributed scheduler is much heavier weight than Dask.core due to things like Tornado.  Dask.core is pure python and only depends on the stdlib.  It is about as lightweight as is Toolz.  I don't think that it is a good idea to reverse this dependency.  We would have single-machine dask.array users (which are probably still the dominant user base) suddenly depending on Tornado.

>  Out of curiosity, what made you prefer cloudpickle to dill?

I was more able to change `cloudpickle` than `dill`.  Dill development was moving slowly around issues like pickling functions that depend on globals.  Cloudpickle development on the other hand was fairly active and by a few active people rather than a single individual.

**Comment by GaelVaroquaux** [comment]
>     Dude, you just outed me! :)

> I hope this is a fun comment and not actual concern :)

It is.

>     Any reasons that this part of dask is not moved to distributed, in the long
>     run?

> Then we would either have dask.array/dataframe users depending on distributed or we would have code duplication. In practice core dask is very lightweight (again, no dependencies outside of the stdlib) so it seems reasonable to me to keep it where it is for now.

Fair enough. No problem from my side.

> The alternative would be to eventually split apart the dask repository into dask.core, dask.dataframe, dask.array, etc..

I don't suggest that you do that for now. It makes things more complex
for users. I would suggest that you do it only if there is a lot of
pressure for it to happen.

> Bokeh is listed there in the set of purely optional dependencies. I think that this is accurate. It's entirely feasible (and common) to run distributed without Bokeh.

Good! We have the same situation in nilearn, where matplotlib is an
optional dependency. To make sure that it stays optional, we run one CI
configuration without matplotlib installed.

**Comment by GaelVaroquaux** [comment]
Thanks for your answers! It is useful for us to hear about your strategical choices.

**Comment by mrocklin** [comment]
> Good! We have the same situation in nilearn, where matplotlib is an
optional dependency. To make sure that it stays optional, we run one CI
configuration without matplotlib installed

This would be a good idea for both dask and distributed, so as to catch issues like https://github.com/dask/distributed/issues/480

**Comment by mrocklin** [comment]
Short term I've removed s3fs and boto3 from requirements.  That functionality is now in `dask[complete]` anyway
