### ISSUE TITLE
map_partitions unexpected behavior

### ISSUE THREAD

**Issue by fredms** [dask/distributed#4823]
The dask dataframe has 4 partitions, and I mapped the "write_and_run" func to each partition,

Expected:
	1. There are total 4 subprocesses started. 
	2. I am using 2 gpus and I also suppose the partitions are distributed evenly to each gpu

Actual:
	There are more than 4 subprocesses started because I can see more than 4 prints of "starting subprocess"

```python
def write_and_run(df):
    #do write stuff
    print("starting subprocess")
    process = subprocess.run(shlex.split(command), stdout=open(stdout_filename,mode='a'),stderr=open(err_filename, mode='a'))
    # do extra stuff

out = ddf.map_partitions(write_and_run)
#out.compute()
persisted_values = dask.persist(*out)
for pv in persisted_values:
    try:
        wait(pv)
    except Exception:
        print("Error encountered")
        pass
```

**Environment**:

- Dask version: latest
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by fredms** [comment]
@jrbourbeau can you take a look?

**Comment by jrbourbeau** [comment]
Dask will run your function to try and figure out relevant metadata for what your function does to DataFrame partitions (e.g. does it create a new column? Does it return a DataFrame or a Series? etc.). So seeing it run more than four times is expected. If this is an issue, you can explicitly pass a `meta=` keyword argument to `map_paritions` to bypass the automatic inference step.

**Comment by fredms** [comment]
Thanks @jrbourbeau . The func doesn't create a new column and it returns a series. 
what's the value of "meta" argument? if I want to keep it only run 4 times.

**Comment by jrbourbeau** [comment]
The [`DataFrame.map_partitions` docstring](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) has additional information and examples on `meta=` -- hopefully that helps

**Comment by fredms** [comment]
Without "meta=", there is one more call of func to inference the return type, which is probably ok. I am running prediction job and it only picks 4 rows to inference return type.

In my example, if each node is assigned 2 partitions, will 2 subprocesses be started at the same time on this node?

**Comment by jrbourbeau** [comment]
It depends on the size of the threadpool your workers have, but in the general case (when there are multiple threads) multiple calls `write_and_run` can happen on the same node

**Comment by fredms** [comment]
Thanks @jrbourbeau . that's helpful. 
In the func `write_and_run`, it starts a subprocess.  Does this mean multiple subprocesses will be started at the same time if there are multiple threads on one worker?

If it desires to have 1 subprocess on 1 worker, should I limit the process/thread when starting the worker? like this
`dask-worker --nprocs 1 --nthreads 1`

**Comment by jrbourbeau** [comment]
> Does this mean multiple subprocesses will be started at the same time if there are multiple threads on one worker?

Yes

> If it desires to have 1 subprocess on 1 worker, should I limit the process/thread when starting the worker?

Yep, that would limit each worker to only be able to make a single call to `write_and_run` at a time (i.e. no concurrent calls leading to multiple subprocesses being launched)

**Comment by fredms** [comment]
That's great. thanks @jrbourbeau .

In such case, how to fully utilize the resource capacity without starting multiple subprocesses at the same time? 

for example, I have a compute node with capacity `(6 cores, 56 GB RAM, 380 GB disk)`.
if I limit the -`-nprocs 1 --nthreads 1`, only 1/6 capacity of compute node is used.

**Comment by jrbourbeau** [comment]
It sounds like you want to explicitly _not_ utilize all the resources available since you don't want to run `write_and_run` in parallel on the same node. If setting the worker threadpool to only have a single thread is too restrictive (for example, if you have other tasks in your workflow that you do want to run in parallel) then you can use a [`SerializableLock`](https://github.com/dask/dask/blob/c5633c21e754df6b2c13195f1e2688e347c48963/dask/utils.py#L952) inside `write_and_run` to ensure that only one of the worker's threads can run `write_and_run` at a time
