### ISSUE TITLE
test_metrics.py:test_process_time() failing assertions

### ISSUE THREAD

**Issue by stefanor** [dask/distributed#4839]
@andrewshadura reports in [Debian Bug #987816](https://bugs.debian.org/987816) that he's getting some assertion failures in `test_process_time()` in his build environment:

```
    ______________________________ test_process_time _______________________________
    
        def test_process_time():
            start = metrics.process_time()
            run_for(0.05)
            dt = metrics.process_time() - start
    >       assert 0.03 <= dt <= 0.2
    E       assert 0.03 <= 0.02570413899999835
    
    distributed/tests/test_metrics.py:27: AssertionError
    _______________________________ test_thread_time _______________________________
    
        def test_thread_time():
            start = metrics.thread_time()
            run_for(0.05)
            dt = metrics.thread_time() - start
    >       assert 0.03 <= dt <= 0.2
    E       assert 0.03 <= 0.027913339999997788
    
    distributed/tests/test_metrics.py:48: AssertionError
    …
```

I haven't been able to reproduce it, but those numbers feel like they were pulled out of thin air in #1625. @pitrou?
Should we just reduce the 0.03 to 0.02?

**Environment**:

- Dask version: 2021.01.0
- Python version: 3.9.2
- Operating System: Debian
- Install method (conda, pip, source): Debian

**Comment by fjetter** [comment]
Thanks for the report! We've seen a similar issue popping up in https://github.com/dask/distributed/issues/4790
