### ISSUE TITLE
Dask Client Computing Prior to Calling .compute()

### ISSUE THREAD

**Issue by timhdesilva** [dask/distributed#4844]
Hi,

I'm having a problem that is almost surely a mistake on my part, but I haven't been able to sort it out so I'm posting it as a bug here. I'm running the following code:

```python
from dask import dataframe as dd
from dask.distributed import Client
client = Client()
import webbrowser
webbrowser.open("http://localhost:8787/status")
```

Next, I run ``data = dd.read_csv('data.csv') # 12GB file``. When doing so, the code executes immediately, but a computation on the client that takes a few minutes begins. Then, I run ``data = data[data['X'] <= 180]``. When I run this second command, two computations occur on the client and the first one looks identical to the computation that occurred when I ran the ``read_csv`` line of code. So that computation appears to be happening twice. Am I doing something obviously wrong here -- I have many more commands that will follow, but I don't want them to be executed until the very end at which I use ``.compute`` on a command that returns a Pandas DF that will fit in my RAM.

Thanks and sorry if this is a dumb question!

**Comment by jrbourbeau** [comment]
Thanks for raising an issue. Can you post a minimal reproducer (see https://blog.dask.org/2018/02/28/minimal-bug-reports)? When I run the following snippet locally I don't see any computations being triggered on the cluster:

```python
import pandas as pd
import dask.dataframe as dd
from dask.distributed import Client

# Write csv file to disk (using pandas)
df = pd.DataFrame({"a": range(20_000)})
df.to_csv("foo.csv")

# Read csv file in with Dask
client = Client()
ddf = dd.read_csv("foo.csv")
```

**Comment by timhdesilva** [comment]
Thanks for the prompt response. I just ran your code snippet and a computation was triggered. See below. I wonder if this has something to do with the fact that I'm using Spyder as an IDE? 
![Capture](https://user-images.githubusercontent.com/51328901/119418313-b79c8700-bcc5-11eb-82fc-52784c63692d.PNG)

**Comment by timhdesilva** [comment]
Even after replacing ``client = Client()`` with 
```
if __name__ == "__main__":
    client = Client()
```
based on #4846 resolution, I still have this problem.

**Comment by fjetter** [comment]
@timhdesilva can you please state the dask and distributed versions you are using? I would like to encourage you to try out more recent versions to see if this problem might already be fixed (at least judging from the dashboard screenshot you posted, there should be newer versions available)
I tried reproducing with latest versions but I couldn't see any computations either and the entire thing finishes in milliseconds

**Comment by timhdesilva** [comment]
@fjetter I'm using version 2021.02.0 of each. I cannot update to a newer version because I'm also using ``dask-sql``, which isn't compatible with any earlier versions.

**Comment by fjetter** [comment]
> I get the following error printed to the console repeatedly, which might be helpful.

This is an unfortunate and misleading error which usually appears if the worker process either never started properly or died very suddenly. I would hope there are other messages to indicate what the underlying problem is

> I cannot update to a newer version because I'm also using dask-sql, which isn't compatible with any earlier versions.

Can you please try to verify the problem in an isolated environment with more recent versions of dask? Especially with the above message about failed processes, this might also indicate a problem with a third party package, e.g. import failure or module initialization prohibits the worker to start because `import dask_something` is broken

**Comment by timhdesilva** [comment]
Thanks for the response. On the first error, there is no other information provided aside from that message repeated multiple times. However, I was able get rid of it in an environment where I do not import any other modules. I'm not sure why this is the case, but I guess I can work around it by copying the functions from the modules I'm importing into the actual file. 

On the problem about the code executing, I think the issue was with the following code I ran after setting ``client = Client()``:
```
import webbrowser
webbrowser.open("http://localhost:8787/status")
```
I'm not sure why this would cause Dask to compute, but now it only computes when expected (i.e. when I add ``.compute()``. Is there another way to open the console automatically in a browser window instead of using the code above, which clearly causes problems?

**Comment by timhdesilva** [comment]
As a follow-up on the above, the execution of operations immediately (instead of upon calling ``.compute()``) appears to be a problem specific to Spyder. Everything works as expected when code is executed in Jupyter Notebook, but not in Spyder.

**Comment by jrbourbeau** [comment]
Thanks for following up @timhdesilva. Could you open up a GitHub issue over with the Spyder folks since this appears to be Spyder-related and not an issue with Dask itself?

**Comment by timhdesilva** [comment]
Will do, thanks @jrbourbeau!
