### ISSUE TITLE
Build cluster between multi computers

### ISSUE THREAD

**Issue by zhangte113** [dask/distributed#4849]
In order to speed the calculation speed, I have built clusters between two computers. And there are several models write by myself.
I build connection between two computers by the command of  `dask-scheduler` and `dask-worker 10.100.207.208:8786` in two computers respectively, and it success. However, when I run my code on one computer, there are a error in another computer `ModuleNotFoundError: No module named 'cosipy'` . The 'cosipy'  is a model that write by myself. So how can I solve this problem??

**Comment by quasiben** [comment]
You many things to solve this issue:
- manually copy the file to the other machines
- use [upload_file](https://docs.dask.org/en/latest/futures.html?highlight=upload_file#distributed.Client.upload_file) to copy the file to the workers
- create a pip / conda package and make a reproducible environment

**Comment by gjoseph92** [comment]
https://docs.dask.org/en/latest/setup/environment.html also has some suggestions for this.

**Comment by zhangte113** [comment]
@quasiben  I tried your way, but I haven't grasped it. Fisrt，I zipped my model to egg file. Second, I copy the egg file to the directory of my main program. Last, I ran my code, but it appeared a error : `zipimport.ZipImportError:` bad local file header: 'E:\\cmder\\dask-worker-space\\worker-lhqaxx42\\cosipy-0.0.1-py3.7.egg'.`

**Comment by zhangte113** [comment]
In fact, I want to run this model [https://github.com/cryotools/cosipy](url), and I did this change in the COSIPY : `#!/usr/bin/env python

"""
    This is the main code file of the 'COupled Snowpack and Ice surface energy
    and MAss balance glacier model in Python' (COSIPY). The model was initially written by
    Tobias Sauter. The version is constantly under development by a core developer team.
    
    Core developer team:

    Tobias Sauter
    Anselm Arndt

    You are allowed to use and modify this code in a noncommercial manner and by
    appropriately citing the above mentioned developers.

    The code is available on github. https://github.com/cryotools/cosipy

    For more information read the README and see https://cryo-tools.org/

    The model is written in Python 3.6.3 and is tested on Anaconda3-4.4.7 64-bit.

    Correspondence: tobias.sauter@fau.de

"""
import os
from datetime import datetime
from itertools import product
import itertools

import logging
import yaml

from config import *
from cosipy.cpkernel.cosipy_core import *
from cosipy.cpkernel.io import *

from distributed import Client, LocalCluster
from dask import compute, delayed
import dask as da
from dask.diagnostics import ProgressBar
from dask.distributed import progress, wait, as_completed
import dask
from tornado import gen
import scipy

import cProfile

def main():
    print(time_start)
    time_restart = time_start.replace(':', '-')
    files = os.listdir(os.path.join(data_path, 'meteo'))
    for file in files[:1]:
        glacier_name = file.split('_')[0]
        meteo_file = os.path.join(os.path.join(data_path, 'meteo', file))
        restart_file = os.path.join(os.path.join(data_path, 'restart', 'restart_{}.nc'.format(time_restart)))
        print(meteo_file, restart_file)
        start_logging()

        #------------------------------------------
        # Create input and output dataset
        #------------------------------------------
        IO = IOClass()
        DATA = IO.create_data_file(meteo_file, restart_file)

        # Create global result and restart datasets
        RESULT = IO.create_result_file()
        RESTART = IO.create_restart_file()

        #----------------------------------------------
        # Calculation - Multithreading using all cores
        #----------------------------------------------

        # Auxiliary variables for futures
        futures = []

        # Measure time
        start_time = datetime.now()

        #-----------------------------------------------
        # Create a client for distributed calculations
        #-----------------------------------------------
        multi_computer = True
        if multi_computer is True:
            cluster1 = "10.100.207.208:8786"
            run_cosipy(cluster1, IO, DATA, RESULT, RESTART, futures)
        else:
            with LocalCluster(scheduler_port=8786, n_workers=None, local_dir='logs/dask-worker-space', threads_per_worker=1, silence_logs=True) as cluster:
                print(cluster)
                run_cosipy(cluster, IO, DATA, RESULT, RESTART, futures)

        start_writing = datetime.now()
        calculate_time = start_time - start_writing
        print("\t Total calculate time: %4g minutes %2g seconds \n" % (calculate_time.total_seconds()//60.0,calculate_time.total_seconds()%60.0))
        print('\n')
        print('--------------------------------------------------------------')
        print('Write results ...')
        print('-------------------------------------------------------------- \n')
        #-----------------------------------------------
        # Write results and restart files
        #-----------------------------------------------
        timestamp = pd.to_datetime(str(IO.get_restart().time.values)).strftime('%Y-%m-%dT%H-%M')

        encoding = dict()
        for var in IO.get_result().data_vars:
            dataMin = IO.get_result()[var].min(skipna=True).values
            dataMax = IO.get_result()[var].max(skipna=True).values
            dtype = 'int16'
            FillValue = -9999
            scale_factor, add_offset = compute_scale_and_offset(dataMin, dataMax, 16)
            #encoding[var] = dict(zlib=True, complevel=compression_level, dtype=dtype, scale_factor=scale_factor, add_offset=add_offset, _FillValue=FillValue)
            encoding[var] = dict(zlib=True, complevel=compression_level)

        IO.get_result().to_netcdf(os.path.join(data_path,'result','result_{}'.format(file)), encoding=encoding, mode = 'w')

        encoding = dict()
        for var in IO.get_restart().data_vars:
            dataMin = IO.get_restart()[var].min(skipna=True).values
            dataMax = IO.get_restart()[var].max(skipna=True).values
            dtype = 'int16'
            FillValue = -9999
            scale_factor, add_offset = compute_scale_and_offset(dataMin, dataMax, 16)
            #encoding[var] = dict(zlib=True, complevel=compression_level, dtype=dtype, scale_factor=scale_factor, add_offset=add_offset, _FillValue=FillValue)
            encoding[var] = dict(zlib=True, complevel=compression_level)

        IO.get_restart().to_netcdf(os.path.join(os.path.join(data_path, 'restart'),'restart_'+timestamp+'.nc'), encoding=encoding)

        #-----------------------------------------------
        # Stop time measurement
        #-----------------------------------------------
        duration_run = datetime.now() - start_time
        duration_run_writing = datetime.now() - start_writing

        #-----------------------------------------------
        # Print out some information
        #-----------------------------------------------
        print("\t Time required for write restart and output files: %4g minutes %2g seconds \n" % (duration_run_writing.total_seconds()//60.0,duration_run_writing.total_seconds()%60.0))
        print("\t Total run duration: %4g minutes %2g seconds \n" % (duration_run.total_seconds()//60.0,duration_run.total_seconds()%60.0))
        print('--------------------------------------------------------------')
        print('\t SIMULATION WAS SUCCESSFUL')
        print('--------------------------------------------------------------')


def run_cosipy(cluster, IO, DATA, RESULT, RESTART, futures):

    # with Client("tcp://10.100.207.208:8786") as client:
    print(cluster)
    with Client(cluster) as client:
        print('--------------------------------------------------------------')
        print('\t Starting clients and submit jobs ... \n')
        print('-------------------------------------------------------------- \n')
        client.upload_file("cosipy-0.0.1-py3.7.egg")
        print(client)
        ss1 = datetime.now()
        # Get dimensions of the whole domain
        ny = DATA.dims[northing]
        nx = DATA.dims[easting]

        cp = cProfile.Profile()

        # Get some information about the cluster/nodes
        total_grid_points = DATA.dims[northing]*DATA.dims[easting]

        # Distribute data and model to workers

        for y,x in product(range(DATA.dims[northing]),range(DATA.dims[easting])):

            mask = DATA.MASK.isel(lat=y, lon=x)
            if ((mask==1) & (restart==False)):
                if np.isnan(DATA.isel(lat=y,lon=x).to_array()).any():
                    print('ERROR!!!!!!!!!!! There are NaNs in the dataset')
                    sys.exit()
                futures.append(client.submit(cosipy_core, DATA.isel(lat=y, lon=x), y, x))
            elif ((mask==1) & (restart==True)):
                if np.isnan(DATA.isel(lat=y,lon=x).to_array()).any():
                    print('ERROR!!!!!!!!!!! There are NaNs in the dataset')
                    sys.exit()
                futures.append(client.submit(cosipy_core, DATA.isel(lat=y, lon=x), y, x,
                                                 GRID_RESTART=IO.create_grid_restart().isel(lat=y, lon=x)))
        # Finally, do the calculations and print the progress
        start_calculation = datetime.now()
        print("\t 计算数据准备时间: %4g minutes %2g seconds \n" % ((start_calculation-ss1).total_seconds()//60.0,(start_calculation-ss1).total_seconds()%60.0))

        progress(futures)
        end_calculation = datetime.now() - start_calculation
        print("\t 计算数据时间: %4g minutes %2g seconds \n" % (end_calculation.total_seconds()//60.0,end_calculation.total_seconds()%60.0))


        #---------------------------------------
        # Guarantee that restart file is closed
        #---------------------------------------
        create_time = datetime.now()
        if (restart==True):
            IO.get_grid_restart().close()
      
        # Create numpy arrays which aggregates all local results
        IO.create_global_result_arrays()

        # Create numpy arrays which aggregates all local results
        IO.create_global_restart_arrays()
        edd = datetime.now() - create_time
        print("\t 写入数据准备时间: %4g minutes %2g seconds \n" % (edd.total_seconds()//60.0,edd.total_seconds()%60.0))

        #---------------------------------------
        # Assign local results to global 
        #---------------------------------------
        write_time1 = datetime.now()
        for future in as_completed(futures):

                # Get the results from the workers
                indY,indX,local_restart,RAIN,SNOWFALL,LWin,LWout,H,LE,B,QRR,MB,surfMB,Q,SNOWHEIGHT,TOTALHEIGHT,TS,ALBEDO,NLAYERS, \
                                ME,intMB,EVAPORATION,SUBLIMATION,CONDENSATION,DEPOSITION,REFREEZE,subM,Z0,surfM,MOL = future.result()
               
                IO.copy_local_to_global(indY,indX,RAIN,SNOWFALL,LWin,LWout,H,LE,B,QRR,MB,surfMB,Q,SNOWHEIGHT,TOTALHEIGHT,TS,ALBEDO,NLAYERS, \
                                ME,intMB,EVAPORATION,SUBLIMATION,CONDENSATION,DEPOSITION,REFREEZE,subM,Z0,surfM,MOL)

                IO.copy_local_restart_to_global(indY,indX,local_restart)

                # Write results to file
                IO.write_results_to_file()
                
                # Write restart data to file
                IO.write_restart_to_file()

        # Measure time
        end_res = datetime.now()- write_time1
        print("\t 写入数据时间: %4g minutes %2g seconds \n" % (end_res.total_seconds()//60.0,end_res.total_seconds()%60.0))


def start_logging():
    ''' Start the python logging'''

    if os.path.exists('./cosipy.yaml'):
        with open('./cosipy.yaml', 'rt') as f:
            config = yaml.load(f.read(),Loader=yaml.SafeLoader)
        logging.config.dictConfig(config)
    else:
       logging.basicConfig(level=logging.INFO)

    logger = logging.getLogger(__name__)
    logger.info('COSIPY simulation started')    


def transform_coordinates(coords):
    """ Transform coordinates from geodetic to cartesian
    an array of tuples)
    """
    # WGS 84 reference coordinate system parameters
    A = 6378.137 # major axis [km]   
    E2 = 6.69437999014e-3 # eccentricity squared    
    
    coords = np.asarray(coords).astype(np.float)
                                                      
    # is coords a tuple? Convert it to an one-element array of tuples
    if coords.ndim == 1:
        coords = np.array([coords])
    
    # convert to radiants
    lat_rad = np.radians(coords[:,0])
    lon_rad = np.radians(coords[:,1]) 
    
    # convert to cartesian coordinates
    r_n = A / (np.sqrt(1 - E2 * (np.sin(lat_rad) ** 2)))
    x = r_n * np.cos(lat_rad) * np.cos(lon_rad)
    y = r_n * np.cos(lat_rad) * np.sin(lon_rad)
    z = r_n * (1 - E2) * np.sin(lat_rad)
    
    return np.column_stack((x, y, z))


def compute_scale_and_offset(min, max, n):
    # stretch/compress data to the available packed range
    scale_factor = (max - min) / (2 ** n - 1)
    # translate the range to be symmetric about zero
    add_offset = min + 2 ** (n - 1) * scale_factor
    return (scale_factor, add_offset)


@gen.coroutine
def close_everything(scheduler):
    yield scheduler.retire_workers(workers=scheduler.workers, close_workers=True)
    yield scheduler.close()



''' MODEL EXECUTION '''
if __name__ == "__main__":
    main()
`

**Comment by quasiben** [comment]
Seems like you may want to consider building a python package if you have multiple files associated with one another.  If not, you could upload multiple files?

**Comment by zhangte113** [comment]
@quasiben Thank you very much, I made it.

**Comment by quasiben** [comment]
Were you able to create your cluster correctly this time ?

**Comment by zhangte113** [comment]
@quasiben Yes, I can. In fact, I have a model(named constant) out of the main model(named cosipy), so it doesn't work. Then I moved the constant model to the cosipy model and changed the way of import(from cosipy.comstant import *), it can work.
Thank you very much again!

**Comment by gjoseph92** [comment]
Out of curiosity, @zhangte113 do you think https://github.com/dask/distributed/pull/4628 would be helpful to you here? (Documentation for this is at https://github.com/dask/dask/pull/7459/files.)
