### ISSUE TITLE
Style hover tooltip in worker memory plot

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4855]
The new managed worker memory is great.  I wonder if we could improve it by styling the hover tooltip a bit.  Currently the hover changes depending on if you're on the managed or unmanaged part.  It's also quite long, looking like this:

    tls://worker-address:1234: 10.0 GiB (8.33 GiB managed (in memory))

And then if you wander over to the right a bit you get something like 

    tls://worker-address:1234: 10.0 GiB (512 MiB unmanaged )

and then again for spilled to disk, etc..

These are long, and it's hard to see everything at a glance.  

Instead, we might consider using a styled table (without borders), maybe similar to how we do with the progress bar.  This includes all measurements at once, and uses bold/emphasized text to separate categories from values.  You don't need to trace your mouse over the horizontal bar to see the different values, which can be especially tricky during computation when the values move.  

We probably also want to avoid the full explanations in the tooltip, and instead find some name for these and put the description in documentation.

**Comment by mrocklin** [comment]
For convenience, here is the code for the hover for the progress bar.  I think that it might be a good model here.

https://github.com/dask/distributed/blob/26a1da050636b4e37490b675ba16aa29a484e106/distributed/dashboard/components/scheduler.py#L1825-L1849

**Comment by jrbourbeau** [comment]
> We probably also want to avoid the full explanations in the tooltip, and instead find some name for these and put the description in documentation.

xrefing https://github.com/dask/distributed/issues/4746

**Comment by ncclementi** [comment]
For reference the hover we want to modify is this one:
https://github.com/dask/distributed/blob/26a1da050636b4e37490b675ba16aa29a484e106/distributed/dashboard/components/scheduler.py#L379-L382

**Comment by ncclementi** [comment]
@mrocklin and @jrbourbeau In terms of style, how do we like this for the Hover? 
Showing screenshots of same computation, showing managed and unmanaged part.

![Screen Shot 2021-06-22 at 11 13 05 AM](https://user-images.githubusercontent.com/7526622/122951773-8908df00-d34b-11eb-877f-6bce41baeaac.png)
![Screen Shot 2021-06-22 at 11 13 26 AM](https://user-images.githubusercontent.com/7526622/122951786-8b6b3900-d34b-11eb-95c9-c90f452028f2.png)

**Comment by mrocklin** [comment]
There are several numbers to track (I think four or five?) I'll suggest a bit more structure.  Maybe something like the following:

## .

tcp://...

  **Total**: 100 GiB
  **Managed**: 70 GiB
  **Unmanaged**: 10 GiB
  **Pending**: 10 GiB
  **Disk**: 10 GIB

If there was some way to align the GB totals I think that that would be ideal.  Maybe a table without boundaries?

**Comment by mrocklin** [comment]
cc also @crusaderky

**Comment by ncclementi** [comment]
One thing I notices is that what is displayed in the Hover the part that says for example `unmanaged: 305.66 MiB` is related to the `width` variable, which is what changes depending on where you hover. I believe the way it's designed we don't have in variables the breakdown to display something like. Maybe I'm wrong, @crusaderky ? 

Managed: 70 GiB
Unmanaged: 10 GiB
Pending: 10 GiB
Disk: 10 GIB

**Comment by mrocklin** [comment]
I'm hopeful that we can do whatever we did for the progress bar, which seems to accomplish this in a similar situation.

**Comment by ncclementi** [comment]
How about this? (I'm not sure what's the Pending status, but if we have that info in `meminfo` then I can display it too)

![Screen Shot 2021-06-22 at 12 36 42 PM](https://user-images.githubusercontent.com/7526622/122965949-c32bae00-d356-11eb-9f68-b8a1604c5d82.png)

**Comment by crusaderky** [comment]
Never heard of pending. I don't like the label "total", as it's ambiguous. The tooltip should show the process memory (which does not include the spilled memory).

We should strive for coherent naming between
- this tooltip
- the column headers in the workers tab
- the sphinx documentation
- ``WorkerState.__repr__``

Also, take a look at the latter for verbiage. Not saying that it should be copied verbatim, but I think that the tooltip and the repr should be kept aligned:
https://github.com/dask/distributed/blob/7d0f0102ddfec1195257c82889ff695d32d61fbc/distributed/scheduler.py#L370-L379


More importantly: if memory serves me, if you have many workers (e.g. 32) and hover on top of the first worker, the tooltip will be hidden by the top bar. The tooltip for the last workers will also be partially covered by whatever's below.

**Comment by ncclementi** [comment]
I open a PR, so we can discuss based on that. Currently an example with 32 workers displays like this. What do we think? 

![Screen Shot 2021-06-22 at 3 34 04 PM](https://user-images.githubusercontent.com/7526622/122989829-44903a00-d371-11eb-804b-f21d19635e2c.png)
![Screen Shot 2021-06-22 at 3 33 39 PM](https://user-images.githubusercontent.com/7526622/122989835-4659fd80-d371-11eb-8406-5fa8f5ad5d2b.png)

**Comment by mrocklin** [comment]
This looks like an improvement to me

**Comment by ncclementi** [comment]
I was wondering if we need/want the worker info the `tcp://`

**Comment by crusaderky** [comment]
Spilled shouldn't be indented under RSS, as it's separate from it.
I think this would be clearer:
```
Process memory (RSS):
  Managed:
  Unmanaged (old):
  Unmanaged (recent):
Spilled to disk:
```
