### ISSUE TITLE
It becomes slower, when I build clusters between multi computers

### ISSUE THREAD

**Issue by zhangte113** [dask/distributed#4861]
I did a test to compare the time that code runs on one computer and four computers.

1.  one computer with 32G memory： total time about 8 mins
![image](https://user-images.githubusercontent.com/49877472/119879087-68708380-bf5d-11eb-81ac-435c5e16fca7.png)

2. four computers with a total  memory of more than 100G： total time of about 12 mins
![image](https://user-images.githubusercontent.com/49877472/119879223-948c0480-bf5d-11eb-89b6-47b6499b21ff.png)

Why it became slower??? Is there are any way to turn this situation around??

**Comment by zhangte113** [comment]
Sometimes, the two speeds are similar, but the former will not surpass the latter.

**Comment by quasiben** [comment]
It's hard to say why something is slower/faster without a detailed look at the code.  Moving data between machines can be a source of slower performance.  I'd recommend reading: these two pages:
- https://docs.dask.org/en/latest/understanding-performance.html
- https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports

**Comment by zhangte113** [comment]
@quasiben Thank you very much, but this is hard for me to understand. Maybe I have to give up it.
