### ISSUE TITLE
Workers' system monitors errors when running without GPU and pynvml initialized/installed

### ISSUE THREAD

**Issue by martinsotir** [dask/distributed#4868]
**What happened**: 

I am getting a lot of errors on Dask workers started on hosts without GPU (at least with no visible GPUs, within SLURM jobs) :

```
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 2 memory: 215 MB fds: 116>>
Traceback (most recent call last):
  File "/python3.7/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/python3.7/site-packages/distributed/system_monitor.py", line 96, in update
    gpu_extra = nvml.one_time()
  File "/python3.7/site-packages/distributed/diagnostics/nvml.py", line 45, in one_time
    h = _pynvml_handles()
  File "/python3.7/site-packages/distributed/diagnostics/nvml.py", line 30, in _pynvml_handles
    gpu_idx = cuda_visible_devices[0]
IndexError: list index out of range
```

**What you expected to happen**:

Be able to deploy Dask workers without errors even when pynvml initialize correctly and no GPU are available.

**Anything else we need to know?**:

* I am not 100% confident, but I don't think this issue affect Dask jobs (this mostly makes the logs more difficult to read).
* On my setup `nvidia-smi` displays `No devices were found`
* `pynvml.nvmlDeviceGetCount()` returns `0`
* I tried setting `CUDA_VISIBLE_DEVICES` to `""` or `-1` without any success.
* It seems `system_monitor.py` only check if `pynvml` is available but do no handle the case "pynvml.nvmlDeviceGetCount() == 0"
* I do not want to use a GPU and I don't want my SLURM job to hold an unused GPU.
* Uninstalling pynvml could be a workaround ? (not sure how it got installed in my environment)

**Minimal Complete Verifiable Example**:

I don't know how my SLURM worker nodes are setup but they all seem to have cuda and nvidia drivers installed and GPU devices are hidden unless explicitly requested.

I am running a cluster using dask_jobqueue:

```
import dask_jobqueue

cluster = dask_jobqueue.SLURMCluster(
    cores=12,
    processes=12,
    memory='72G',
    env_extra=['source "/miniconda/bin/activate" "my_env"'],
    name='my-project-dask',
    local_directory='/var/tmp',
    walltime='3:00:00',
    job_extra=["-o /logs/log_%j-%n.out"]
)

cluster.scale(jobs=4)
```

**Environment**:

- Dask version: `2021.4.1`
- Python version: 3.7
- Operating System: CentOS 7
- Install method : conda

**Comment by jrbourbeau** [comment]
Thanks for reporting @martinsotir! cc @pentschev @quasiben @charlesbluca

**Comment by pentschev** [comment]
Thanks for the report @martinsotir , this should be an easy fix. I send a PR shortly.

**Comment by pentschev** [comment]
I opened https://github.com/dask/distributed/pull/4873 to handle this. @martinsotir would you be able to test that and see if it resolves your use case?
