### ISSUE TITLE
Worker memory chart is very jittery

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4872]
Currently the worker memory chart moves around a lot as data is allocated and deallocated rapidly.  This makes it distracting and hard to read.  I suggest that we consider slowing down the rate at which we scale down the x-axis after deallocation.  Maybe at every cycle we only allow it to decrease by 5% or something.  Inside the code for updating this plot we would look at the maximum of the x-range before updating things, then we would update, and then we would increase the maximum of the x-range if it was below 95% of the previous value.

This is just one suggested approach.  There may be others.

**Comment by mrocklin** [comment]
Actually, looking at it now while it's still at rest it appears to be jumping around on its own faster than the cycle time.  I suspect that there is some fanciness going on (maybe even fanciness like what I propose above)

**Comment by jrbourbeau** [comment]
xref-ing https://github.com/dask/distributed/issues/4675 as these issues might be related

**Comment by mrocklin** [comment]
cc also @crusaderky

**Comment by crusaderky** [comment]
> I suggest that we consider slowing down the rate at which we scale down the x-axis after deallocation.

If you're talking about x_range.end, it only changes when 
1. you add or remove a worker
2. the amount of spilled memory causes process + spilled memory to go beyond the worker's memory limit

In both cases rate limiting won't solve the problem. On chrome the graph keeps bouncing around well after x_range.end has stopped moving, and only stabilizes after a browser page refresh.
