### ISSUE TITLE
Dask-worker cli doesn't work with symlinked files passed as a parameters for TLS options (-tls-ca-file, --tls-cert, --tls-key))

### ISSUE THREAD

**Issue by oshadura** [dask/distributed#4889]
**What happened**:
```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ dask-worker --tls-ca-file /etc/cmsaf-secrets/ca.pem 
Usage: dask-worker [OPTIONS] [SCHEDULER] [PRELOAD_ARGV]...
Try 'dask-worker --help' for help.

Error: Invalid value for '--tls-ca-file': Path '/etc/cmsaf-secrets/ca.pem' does not exist.
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ 
```

```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ ls -la /etc/cmsaf-secrets/
total 0
drwxrwsrwt 3 root users 220 Jun  8 12:06 .
drwxr-xr-x 1 root root   27 Jun  8 12:06 ..
drwxr-sr-x 2 root users 180 Jun  8 12:06 ..2021_06_08_12_06_23.361115774
lrwxrwxrwx 1 root root   13 Jun  8 12:06 ca.key -> ..data/ca.key
lrwxrwxrwx 1 root root   13 Jun  8 12:06 ca.pem -> ..data/ca.pem
lrwxrwxrwx 1 root root   19 Jun  8 12:06 condor_token -> ..data/condor_token
lrwxrwxrwx 1 root root   31 Jun  8 12:06 ..data -> ..2021_06_08_12_06_23.361115774
lrwxrwxrwx 1 root root   19 Jun  8 12:06 hostcert.pem -> ..data/hostcert.pem
lrwxrwxrwx 1 root root   16 Jun  8 12:06 .servicex -> ..data/.servicex
lrwxrwxrwx 1 root root   19 Jun  8 12:06 usercert.pem -> ..data/usercert.pem
lrwxrwxrwx 1 root root   19 Jun  8 12:06 xcache_token -> ..data/xcache_token
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ 
```

But it works if to use directly `dask-worker --tls-ca-file /etc/cmsaf-secrets/..data/ca.pem ..`, it works...

**Environment**:

- Dask version: 2021.06.0
- Python version: Python 3.8.8 from conda
- Operating System: Debian based image
- Install method (conda, pip, source): conda

cc: @bbockelm

**Comment by oshadura** [comment]
We are not sure when happen regression but we noticed problem while updating between Dask 2021.06.0 and 2021.05.0

**Comment by jrbourbeau** [comment]
Thanks for reporting @oshadura. The only recent CLI-change that is coming to mind is https://github.com/dask/distributed/pull/4810, but that was included in the `distributed=2021.05.0` release so probably isn't related to what you're seeing. What version of `click` are you using? You might try with `click < 8` to test if you're running into https://github.com/pallets/click/issues/1921

**Comment by oshadura** [comment]
@jrbourbeau wonderful investigation! You were right, I deployed both images separately in prod and dev instance and I see that not working image with dask 2021.06.0 has click "8.0.1" while working 2021.05.0 still has '7.1.2'

Using reproducer from https://github.com/pallets/click/issues/1921:

 Dask 2021.05.0 (from conda) with click '7.1.2'

```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ python test.py /etc/cmsaf-secrets/ca.pem
/etc/cmsaf-secrets/..2021_06_09_10_44_17.133410100/ca.pem
```
Dask 2021.06.0 (from conda) with click "8.0.1"

```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ python test.py /etc/cmsaf-secrets/ca.pem
Usage: test.py [OPTIONS] FILENAME
Try 'test.py --help' for help.

Error: Invalid value for 'FILENAME': Path '/etc/cmsaf-secrets/ca.pem' does not exist.
```

**Comment by jrbourbeau** [comment]
Thanks for following up @oshadura! I'm going to close this issue for now and we can continue the conversation over on the `click` side
