### ISSUE TITLE
Compartmentalize threads

### ISSUE THREAD

**Issue by simonkamronn** [dask/distributed#489]
I have a PyMC3 model defined as e.g.
```
with pymc3.Model() as model:
    model_param1 = pymc3.some_disitribution('parameter_name1')
    model_param2 = pymc3.some_disitribution('parameter_name2')

    step = pymc3.NUTS([model_param1, model_param2])

    trace = pymc3.sample(1000, step=step, njobs=1)
```
When I run this using `distributed.submit()` it works fine for one process, but if I try in parallel with some other data, an error occurs saying that 'parameter_name1' is already defined, indicating `model` is available in both environments. 

Any way to compartmentalize calls to `distributed.submit()`?

**Comment by mrocklin** [comment]
What do you mean by compartmentalize?  Do you mean use only one thread per process?  If so then you might want to start your workers with `dask-worker --nprocs N --nthreads 1` for N the number of cores you have on each machine.

**Comment by simonkamronn** [comment]
**Update:** was going to post the message below but found that I switched `--nprocs` and `--nthreads` so with 1 thread/process the last error seems to be gone. There's a new error now, however, regarding Theano compilation but I'm not sure `distributed` is to blame for that. `dask-ssh --nprocs 1 --nthreads 1` does the trick though it's a serious limitation on 12 core servers. 

---
I already do that, but I'm not sure what the problem is to be honest. It might be an issue with how PyMC3 defines models globally? To expand a little I have a function which includes the above such that
```
def run_model(*args):
    with pymc3.Model() as model:
        ... define model and run sampler
    return model_output
```
and if I run `executor.submit(run_model, args)` on that function more than once, it errors.

**Comment by mrocklin** [comment]
If my memory serves (and it's been a long time since I worked with Theano) they keep compiled artifacts in a shared directory on disk.  I wouldn't be surprised if different processes were overwriting each other there.  

A few options come to mind:

1.  You could deploy dask workers using something like docker for isolation.  
2.  You could ask on theano-dev about using theano in multiple processes concurrently
3.  You could find some way to specify the compilation directory, and set it explicitly within each task

**Comment by simonkamronn** [comment]
Theano should already be able to handle parallel compilation processes. It just locks the compilation directory until finished. I'll try to figure out why it fails at that. Thanks for the time.
