### ISSUE TITLE
Worker started from the command line fails to start

### ISSUE THREAD

**Issue by scganterh** [dask/distributed#4903]
**What happened**: Worker fails with message `AttributeError: module 'click._unicodefun' has no attribute '_verify_python3_env'` after being started from the command line.

**What you expected to happen**: The worker should start running normally.

**Minimal Complete Verifiable Example**:

```bash
$ python3 -m distributed.cli.dask_worker
Traceback (most recent call last):
  File "python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "python3.6/site-packages/distributed/cli/dask_worker.py", line 469, in <module>
    go()
  File "python3.6/site-packages/distributed/cli/dask_worker.py", line 464, in go
    check_python_3()
  File "python3.6/site-packages/distributed/cli/utils.py", line 33, in check_python_3
    _unicodefun._verify_python3_env()
AttributeError: module 'click._unicodefun' has no attribute '_verify_python3_env'
```

**Anything else we need to know?**: I am using the following list of dependencies:

    click==8.0.1
    cloudpickle==1.6.0
    contextvars==2.4
    dask-jobqueue==0.7.2
    dask==2021.3.0
    distributed==2021.3.0
    heapdict==1.0.1
    immutables==0.15
    importlib-metadata==4.5.0
    msgpack==1.0.2
    psutil==5.8.0
    pyyaml==5.4.1
    sortedcontainers==2.4.0
    tblib==1.7.0
    toolz==0.11.1
    tornado==6.1
    typing-extensions==3.10.0.0
    zict==2.0.0
    zipp==3.4.1

**Environment**:

- Dask version: 2021.3.0
- Python version: 3.6.2
- Operating System: Linux 3.10.0
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for reporting @scganterh! Unfortunately older versions of `distributed` aren't compatible with `click > 8`. You need to either pin `click < 8` or `distributed >= 2021.5.0`. See https://github.com/dask/distributed/issues/4817 for more information.

**Comment by scganterh** [comment]
Thanks @jrbourbeau

**Comment by brenting** [comment]
I see @scganterh uses Python 3.6, which I am also using for a project. Distributed version 2021.3.0 is the last supported version on Python 3.6. However, the [requirements.txt](https://github.com/dask/dask/tree/2021.03.0) file of distributed version 2021.3.0 does not pin click to a version <8. Doing `pip install dask[distributed]` on Python 3.6 now results in a non-working version.

**Comment by jrbourbeau** [comment]
Unfortunately there's not much we can do for older releases on PyPI. We patched older releases on conda-forge with the updated `click` version pin so, if conda is an option for you, then that should work. Otherwise, I recommend manually pinning `click < 8`
