### ISSUE TITLE
Prefixing UCX/RMM config variables with `distributed.`

### ISSUE THREAD

**Issue by charlesbluca** [dask/distributed#4904]
As discussed in dask/dask#7579, the configuring variables for UCX/RMM are not contained in the namespace of Distributed, despite only being used there. With that in mind, it would make sense moving forward to prefix these variables with `distributed.`, and maybe have some deprecation period to handle scripts using UCX/RMM with the old variables. In general, we should be able to prefix old variables with a new alias:

```diff
diff --git a/distributed/config.py b/distributed/config.py
index 4b1cfb35..bebc0560 100644
--- a/distributed/config.py
+++ b/distributed/config.py
@@ -48,6 +48,7 @@ aliases = {
     "log-length": "distributed.admin.log-length",
     "log-format": "distributed.admin.log-format",
     "pdb-on-err": "distributed.admin.pdb-on-err",
+    "ucx": "distributed.ucx",
 }

 dask.config.rename(aliases)
```

But I'm not sure if that would cover all the cases where UCX/RMM is configured for Dask-CUDA.

cc @pentschev

**Comment by pentschev** [comment]
I think that covers all the cases, we will only update how they are used in Dask-CUDA and should be good to go. I would only suggest that we consider whether this should be `distributed.ucx` or `distributed.comm.ucx`, or even a more specific namespace such as `distributed.comm.interface.ucx` (`interface` is obviously a suggestion to a namespace that doesn't exist today, but could be `framework` or some better name if someone can think of one).

@quasiben any thoughts on the above?

**Comment by jrbourbeau** [comment]
I am curious why the current format was chosen. There could be some reasoning behind it which I'm unaware of. Maybe @quasiben knows?

**Comment by quasiben** [comment]
I think the current format was chosen to reduce the amount of text `DASK_UCX__NVLINK` vs `DASK_DISTRIBUTED_UCX__NVLINK`.  The lines were a little long when we were initially bringing UCX into distributed env vars. However, it's probably more important to be consistent than reduce text.

Nesting ucx in `distributed.comm.ucx` make sense to me. If we adopt other tunable networking libraries `distributed.comm.foo` would also work without having to drop another nested level like `interface`

**Comment by charlesbluca** [comment]
Opened #4916 to handle this change on Distributed's end, will probably need to open something similar in Dask-CUDA.
