### ISSUE TITLE
 Remove `tmpfile` utility context manager

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4910]
Similar to https://github.com/dask/dask/issues/7800, we can replace our `tmpfile` context manager

https://github.com/dask/distributed/blob/5e5b9835a5e6929bb97acf94f0a2eecccc0b6a2f/distributed/utils.py#L862-L863

with [`tempfile.TemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile) from the standard library.

**Comment by adeyezbamz** [comment]
> Similar to [dask/dask#7800](https://github.com/dask/dask/issues/7800), we can replace our `tmpfile` context manager
> 
> https://github.com/dask/distributed/blob/5e5b9835a5e6929bb97acf94f0a2eecccc0b6a2f/distributed/utils.py#L862-L863
> 
> with [`tempfile.TemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile) from the standard library.

Nice

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/4912
