### ISSUE TITLE
Logging update breakages

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4940]
https://github.com/dask/distributed/pull/4909 introduced some internal refactoring to our cluster logging system. Some of the changes (e.g. the `Logs` -> `MultiLogs` rename) can lead to errors for users using the previous `Log` and `Logs` objects from `distributed.utils` (xref https://github.com/dask/dask-kubernetes/issues/344). Additionally, `Cluster.get_logs()` now returns a dictionary with a different structure (a `dict` of `tuple`s instead of a `dict` with `str`s) which can lead to breakages for user code which parses the output of `Cluster.get_logs()`.

Are there changes we can make to keep the functionality introduced by https://github.com/dask/distributed/pull/4909, but do so in a backward-compatible way? 

cc @charlesbluca @jacobtomlinson

**Comment by charlesbluca** [comment]
I think the easiest fix here would be to return to the original behavior of `Log`, `Logs`, and `Cluster.get_logs`, and just refactor how we're wrapping the logs' inline styling. My only reasoning behind the refactor was to directly map the output of `Node.get_logs` to the HTML reprs, but I was under the assumption that these utils weren't being used downstream.

I can start working on a fix now

**Comment by charlesbluca** [comment]
Opened in #4941
