### ISSUE TITLE
Is pausing the worker pausing the work?

### ISSUE THREAD

**Issue by max-sixty** [dask/distributed#4975]
**What happened**:

In a follow up to https://github.com/dask/distributed/issues/4939, could I ask another clarifying question — does "pause" from ["fraction at which we pause worker threads"](https://distributed.dask.org/en/latest/worker.html#memory-management) mean:
1. Paused starting new tasks, but continuing on existing tasks
2. Paused currently running tasks

All these tasks are "processing" given they're on the worker, so my question is re the tasks that the worker is running.

To the extent it's not just me who thinks this might be ambiguous — I'll PR this in too.

Thanks!

**Comment by fjetter** [comment]
Pausing a worker means:

* Prohibit submitting further tasks to the internal threadpool executor, i.e. no new tasks will be executed
* Currently executing tasks continue to run (we lack the technical possibility to "suspend" or pause a thread)

The scheduler is not aware of whether or not a worker is paused.

**Comment by max-sixty** [comment]
Great, thanks, that's clear. I'll do a PR shortly
