### ISSUE TITLE
Drop down tile to reveal "secret" dashboards

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#4977]
We're accumulating a lot of _secret_ dashboard pages https://github.com/dask/distributed/blob/c2557938e6c4175534031cba5ca5ac9d2cdc95f7/distributed/dashboard/scheduler.py#L82-L119
although most are not easily accessible from the UI. Most of the pages are not useful for the ordinary user and are only relevant for specific edge cases or debugging. hence, it makes sense that they are not promoted as a top-level dashboard page.

However, at least for debugging purposes, I would really appreciate if these pages were a bit easier to navigate. In particular I'm looking for a way which doesn't require me to know the exact endpoint for an individual plot and requires me to type it into my browser.

I would propose to add a drop down menu / button which can be used to browse all _hidden_ dashboard pages.

Disclaimer: I can't implement this. I barely know what bokeh is.

**Comment by mrocklin** [comment]
I agree that a dropdown menu would be a good way to solve this.  

> Disclaimer: I can't implement this. I barely know what bokeh is.

cc @jacobtomlinson, although I think that he's on vacation
