### ISSUE TITLE
Use bokeh tabs on the dashboard status page?

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4981]
Thanks to @ncclementi, today I learned [bokeh has a tab pane](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#tabs) which allows you to switch between multiple plots in selectable tabs (see the "circle" and "line" tabs in the screenshot below).

![Screen Shot 2021-06-25 at 1 52 14 PM](https://user-images.githubusercontent.com/11656932/123472275-95e03980-d5bc-11eb-92f7-13524e97933a.png)

In our current dashboard status page, we display the number of processing tasks per worker in the lower lefthand corner. However, we have are other similar bar charts which also describe the current "load" on each worker (e.g. cpu per worker, occupancy per worker, etc). Would folks be interested in using bokeh tabs for the lower lefthand plot to allow users to switch between different "X per worker" bar chats? 

<img width="1552" alt="Screen Shot 2021-06-25 at 1 51 47 PM" src="https://user-images.githubusercontent.com/11656932/123472233-85c85a00-d5bc-11eb-9ffb-3c1d5b64b3c1.png">

**Comment by fjetter** [comment]
I actually thought about proposing to ditch the tasks processing in favour of occupancy but the tabs would probably be a perfect compromise

**Comment by mrocklin** [comment]
Tabs are neat.  I don't currently feel a strong urge to use them.  If they don't clutter things and serve a purpose then great.  I wouldn't want us to spend time just because we wanted to try out a new thing though. 

Also, if people want to see what tabs feel like, the performance_report is built with tabs.

**Comment by jrbourbeau** [comment]
Easily switching between the nprocessing, CPU, and occupancy load plot on the dashboard landing page would, I think, be a net gain. Though I agree it's not worth spending a lot of time on right now. My hope is that someone with bokeh skills like @ncclementi could probably handle this in an hour or so (@ncclementi feel free to push back on that estimate if you think I'm being too optimistic). If that's the case, then I think it would be worth it
