### ISSUE TITLE
Dashboard Plots tab not working in Firefox

### ISSUE THREAD

**Issue by ncclementi** [dask/distributed#4994]
**What happened**:
Currently the Plots Tab added to the Dashboard doesn't work in latest FIrefox (89.0.2 (64-bit)) see image below:
![Screen Shot 2021-06-29 at 12 01 48 PM](https://user-images.githubusercontent.com/7526622/123831912-cd0f5d00-d8d2-11eb-9dbb-9ea1b69154eb.png)

**What you expected to happen**:
I checked on Safari, and it looks ok. This is what I'd expect
![Screen Shot 2021-06-29 at 12 10 20 PM](https://user-images.githubusercontent.com/7526622/123832108-ffb95580-d8d2-11eb-9257-61dde0c59bb4.png)

**Environment**:

- Dask version: '2021.06.2+4.g453f740e'
- DIstributed version: '2021.06.2+19.g5dc591bb'
- Python version: 3.8.10
- Operating System: macOS BigSur 11.4

**Comment by mrocklin** [comment]
cc @jacobtomlinson

**Comment by jrbourbeau** [comment]
Thanks for reporting @ncclementi! I agree it'll be good to see if @jacobtomlinson has any thoughts on this. Interestingly I wasn't able to reproduce on my mac, which is also on macOS BigSur 11.4 and using Firefox 89.0.2 (64-bit), with latest `distributed` `main` branch (5dc591bbdd4427fe49fe90338a34fc85ee35f2c9 at the time of writing this comment)

**Comment by jacobtomlinson** [comment]
Hrm interesting I am also unable to reproduce with the same Firefox version on mac.

**Comment by jacobtomlinson** [comment]
It actually looks like none of the CSS changes that I made have been applied in that first screenshot. Perhaps your browser is caching an older version of the CSS.

Could you try clearing your cache (hold shift and click refresh) and see if that resolves it?

**Comment by ncclementi** [comment]
Yes that solved it. No problems at all now. I'm going to go ahead an close the issue. 
Thank you for your help : )
