### ISSUE TITLE
Ability to view performance reports without internet access

### ISSUE THREAD

**Issue by max-sixty** [dask/distributed#4999]
I'm working in an airgapped environment. The general dask dashboard running on the scheduler works really well.

But when I attempt to view performance reports, I get a blank page and it seems that Bokeh is attempting & failing to connect to an external resource. The http server that I started to view it reports the request and replies with a 304:

```sh
$ python -m http.server
Serving on ...
{IP} {date} "GET /dask-report.tml HTTP/1.1" 304
```

The page is blank an the the developer console shows:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/5635139/123879641-1f15aa00-d8f6-11eb-8003-ad1a1ca554ea.png">

Has anyone else had this and has a workaround?

**Comment by mrocklin** [comment]
cc'ing @jsignell who has both Dask and Bokeh experience

**Comment by jsignell** [comment]
Hmm - sorry for the slow response. My first thought is that you might need to have the js locally so it doesn't have to get fetched from cdn. Here are some related docs](https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.output_file), it looks like you would want to pass `mode=inline` but I'm not sure if it's possible to pass that through the distributed performance_report class. So it might need a change to distributed.

**Comment by jrbourbeau** [comment]
Here's the location where we would need to add `mode="inline"`

https://github.com/dask/distributed/blob/cbcec9cdc020a36c024d55c216d5391c7b09ccae/distributed/scheduler.py#L7092

I don't have a good sense for how large the js content can get. This will influence if we want to just hardcode `mode="inline"` or expose a `mode=` keyword on the client-side `performance_report` class which passes the value along to the scheduler.

**Comment by jrbourbeau** [comment]
FWIW when I run this example

```python
from distributed import Client, performance_report

client = Client()
with performance_report():
    import dask.array as da

    x = da.random.random((500, 1_000))
    x.sum().compute()
```

the generated performance report is 57 KB with `mode="cdn"` (the default value) and 1.1 MB with `mode="inline"`.

**Comment by jakirkham** [comment]
@jrbourbeau did PR ( https://github.com/dask/distributed/pull/5025 ) fix this? Or were there other outstanding tasks?

**Comment by jrbourbeau** [comment]
Thanks for following up here @jakirkham. https://github.com/dask/distributed/pull/5025 did indeed close this issue. I guess GitHub didn't like my use of "Closes XXX" in that PR 🤷

**Comment by jakirkham** [comment]
Ofc. Yeah not sure why it didn't either

Filed an issue with GitHub to see if they could figure out why it didn't work

**Comment by jakirkham** [comment]
> Filed an issue with GitHub to see if they could figure out why it didn't work

@jrbourbeau, I got a response from GitHub. The gist is we have to check the checkbox for the PR to close the issue. If it is not checked, the issue will not be closed

**Comment by jsignell** [comment]
This explains so much. Thanks for figuring that out @jakirkham!
