### ISSUE TITLE
dashboard url for worker logs has 500 error response

### ISSUE THREAD

**Issue by niole** [dask/distributed#5004]
**What happened**:

The workers' logs links in the dashboard 500s. The url in the request sent by the dashboard looks like this: `/info/logs/tcp%3A%2F%2F100.96.2.7%3A3000.html`. It seems that the generated url cannot be parsed successfully. See the logs below.

I wonder if there is a workaround that could be implemented such that the worker html page has a parseable name.

<img width="1344" alt="Screen Shot 2021-06-30 at 2 46 19 PM" src="https://user-images.githubusercontent.com/6508755/124014934-fc889d00-d998-11eb-9515-34c981e11210.png">
<img width="1007" alt="Screen Shot 2021-06-30 at 2 50 19 PM" src="https://user-images.githubusercontent.com/6508755/124015326-64d77e80-d999-11eb-8b4a-fd194dbe1af0.png">

```
HTTPServerRequest(protocol='http', host='niolef1369.workbench-analyze-team-sandbox.domino.tech', method='GET', uri='/info/logs/tcp:/100.96.2.7:3000.html', version='HTTP/1.1', remote_ip='100.96.0.182')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/distributed/http/scheduler/info.py", line 106, in get
    logs = await self.server.get_worker_logs(workers=[worker])
  File "/opt/conda/lib/python3.8/site-packages/distributed/scheduler.py", line 6999, in get_worker_logs
    results = await self.broadcast(
  File "/opt/conda/lib/python3.8/site-packages/distributed/scheduler.py", line 5502, in broadcast
    results = await All(
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 238, in All
    result = await tasks.next()
  File "/opt/conda/lib/python3.8/site-packages/distributed/scheduler.py", line 5494, in send_message
    comm = await self.rpc.connect(addr)
  File "/opt/conda/lib/python3.8/site-packages/distributed/core.py", line 1012, in connect
    comm = await connect(
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/core.py", line 285, in connect
    comm = await asyncio.wait_for(
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py", line 375, in connect
    ip, port = parse_host_port(address)
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/addressing.py", line 94, in parse_host_port
    return host, int(port)
ValueError: invalid literal for int() with base 10: '/100.96.2.7:3000'
```

**What you expected to happen**:

We should be able to see the logs for the worker.

**Minimal Complete Verifiable Example**:

I am sorry, I cannot provide a repro.

**Anything else we need to know?**:

The link for the worker `/info/worker/(worker).html` also fails, it 404s. Might be related. The 404 is not logged in the scheduler's logs. The 500 is logged.

The Dask cluster is deployed in a distributed fashion. 1 scheduler node, 1 worker node, a separate node is used to submit jobs to the cluster and view the dashboard.

We have deployed dask cluster on a k8s cluster. The dask cluster is located at a subpath in the k8s cluster. We use a reverse proxy with url rewriting in order to proxy requests to the dashboard.

**Environment**:

- Dask version:  `dask.distributed` python library is `2` and the `dask-scheduler` binary is 2021.6.0
- Python version: 3.8
- Operating System: debian buster/sid
- Install method (conda, pip, source): conda, installed via the daskdev/dask:2021.6.0 image

**Comment by jrbourbeau** [comment]
Thanks for reporting @niole. It's been a while since version 1.3 has been released and there have been many improvements since then. Could you try a more recent version of Dask and Distributed (for example the latest releases) to see if the problem is still present?

**Comment by niole** [comment]
@jrbourbeau so sorry, 1.3 is wrong. Updating the description. I'm using `daskdev/dask:2021.6.0` on the scheduler.  `dask.distributed` python library is `2` and the `dask-scheduler` binary is 2021.6.0.

**Comment by jrbourbeau** [comment]
> dask.distributed python library is 2 and the dask-scheduler binary is 2021.6.0

Sorry, I don't quite follow this. Do you you mean you're using Python 2 (e.g Python 2.7), or the distributed version is 2? I would recommend making sure you're using the same version of libraries for you client, scheduler, and workers. You can check this by running:

```python
client.get_versions(check=True)
```

That should raise an error if there's a version mismatch

**Comment by niole** [comment]
@jrbourbeau I don't think that the problem has anything to do with the dask client. This is about how the dashboard works. The tornado web server seems to dedupe the `//` in `tcp://<host>:<port>`, mangling the worker address when it pulls it out of the url when showing the WorkerLogs page.

tornado.application - ERROR - Uncaught exception GET **/info/logs/tcp:/100.96.2.17:3000.html** (100.96.2.165)
HTTPServerRequest(protocol='http', host='niolef1369.workbench-analyze-team-sandbox.domino.tech', method='GET', uri='/info/logs/tcp:/100.96.2.17:3000.html', version='HTTP/1.1', remote_ip='100.96.2.165')

The url in the request sent is `/info/logs/tcp%3A%2F%2F100.96.2.7%3A3000.html`. I verified that `tornado.escape.url_unescape`  correctly unescapes the string that it receives. the code in [distributed/comm/addressing.py](https://github.com/dask/distributed/blob/611923e2d718350b8e8443d0d94c853c18b91574/distributed/comm/addressing.py#L86-L94) ends up trying to parse `/100.96.2.17:3000` as an int, because it thinks it's a port.

**Comment by niole** [comment]
@jrbourbeau thanks for your patience. This is a problem with our stack. Seems like our nginx parses and modifies the encoded uri component and dedupes the `//`.

**Comment by jrbourbeau** [comment]
Thanks for following up @niole!
