### ISSUE TITLE
cannot import local modules

### ISSUE THREAD

**Issue by blakemas** [dask/distributed#501]
@stsievert and I are running into an issue which only happens when we pass an IP address to Client/Executor. Specifically, it cannot locate modules in the same local folder.

For example, say I have the script:
`from distributed import Executor
import moduleTest as mt 

e = Executor('IP_ADDRESS:PORT')

y = [e.submit(mt.printHello, x) for x in ['Bill', 'Janice', 'Franklin']]

y = e.gather(y)

print(y)`

which calls a module named `moduleTest.py`
which contains the function:
`def printHello(name):
	print("hello %s" %name)
	return name`

If I run without providing an IP, it runs without issue, but if I use the scheduler and create a worker, local or otherwise, it throws an import error:
`ImportError: No module named 'moduleTest'`

One way of working around this for the interim I have found is to move `moduleTest.py` into the folder "anaconda/lib/python3.5/", but I am wondering if there is an easier way that I am missing.

**Comment by mrocklin** [comment]
See http://stackoverflow.com/questions/39295200/can-i-use-functions-imported-from-py-files-in-dask-distributed

**Comment by blakemas** [comment]
Thanks!
