### ISSUE TITLE
Add pytest marker for GPU tests

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#5015]
It came up in the monthly community meeting that we should add a `gpu` pytest marker to certain test modules / individual tests which run on GPUs. This will allow us to select only GPU-related tests when running the test suite on machines with GPUs in CI (xref https://github.com/dask/distributed/pull/5011) 

cc @charlesbluca @quasiben @aktech

**Comment by aktech** [comment]
Nice! This will be very useful. We do something similar in the [sgkit project](https://github.com/pystatgen/sgkit/) as well.

**Comment by charlesbluca** [comment]
I agree! I think a good starting place would be to target the tests being ran as part of [dask-cuda's CI](https://github.com/rapidsai/dask-cuda/blob/79bc44ee75aefd4bacbd0877ea724fcd3ee2ea64/ci/gpu/build.sh#L120-L125), and we can add more as we see needed.

**Comment by jrbourbeau** [comment]
Great! If I were doing this I would probably do something like:

1. Add a description for a new `gpu` marker here

https://github.com/dask/distributed/blob/8b79bd95d0c5a681f6d0543eb20d645dc1182ec1/setup.cfg#L49-L52

   this will inform `pytest` about the new marker

2. Mark all of the test modules [here](https://github.com/rapidsai/dask-cuda/blob/79bc44ee75aefd4bacbd0877ea724fcd3ee2ea64/ci/gpu/build.sh#L120-L125) (except for `test_nanny.py`) with a [module-level](https://docs.pytest.org/en/6.2.x/example/markers.html#marking-whole-classes-or-modules) `pytest.mark.gpu` marker
3. Go into `test_nanny.py` and decorate individual tests that run on GPUs with `@pytest.mark.gpu`

**Comment by charlesbluca** [comment]
Thanks! Opened up a draft PR #5023; I'm not exactly sure what tests in `test_nanny.py` we want running here - 
@quasiben @pentschev any ideas here?

**Comment by pentschev** [comment]
I'm not really sure what are the tests of interest in `test_nanny.py`, I think @quasiben added that, maybe he could confirm. We could also just take the same approach that we do currently and test all of `test_nanny.py`.

**Comment by pentschev** [comment]
There's some overlap with those from `dask-cuda`, but ideally we would want to have UCX in gpuCI and run those in https://github.com/pentschev/ucx-py/blob/5376b43c2f17e3062666abc89d81c48a75beb039/ci/gpu/build.sh#L108-L115 too.

**Comment by jrbourbeau** [comment]
> We could also just take the same approach that we do currently and test all of test_nanny.py

That seems reasonable too 👍

**Comment by quasiben** [comment]
We added test_nanny because of a UCX issue.  Here is the PR for the work https://github.com/dask/distributed/pull/3747 -- I think if it's not too much overhead testing the entire file would be good
