### ISSUE TITLE
Stacked area chart for TaskGroups

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5019]
As part of the effort to replace the Task Stream plot I'd like to propose a stacked area chart, with each line the amount of time spent in a specific task group.  Here are some images of stacked area charts to give a sense for what I mean

![image](https://user-images.githubusercontent.com/306380/124198308-004e1980-da96-11eb-9278-e6d6ecc58ae4.png)
![image](https://user-images.githubusercontent.com/306380/124198326-07752780-da96-11eb-9a2c-d7259c93c1e0.png)

This would give us a sense for which task groups have been active, and how concentrated or diffuse they are.  We might also try to find a way to include transfers or disk access.

I think that we can probably get the information that we need for this chart by capturing the timestamp of when we reach 5% done, 10% done, 15% done, ... 95% done, and 100% done where "done" is measured by the number of tasks.  

Here is some very silly pseudocode to try to give a sense for what I mean.

```python
class TaskGroup:
    ...
    time_done: list

class Scheduler:
    def transition_processing_done(...):
        ts._group.some_counter += 1

        if ts._group.some_counter % len(ts._group) / 20:
            ts._group.time_done.append(time())
```

I think that if we then take the total duration of the task group, assume that it is uniform throughout all tasks, then we should be able to get a sense for the average number of CPUs actively working on this group during every given interval.  If the time between two successive timestamps is short, then our cluster was really concentrating on this task group during that period.  If the time between two successive timestamps is long, then our cluster wasn't concentrating on this task group.

This should give us some points in time and height values for each of our different task groups.

To merge these all into a stacked area chart my sense is that we want to select a time range, get a number of samples along that range (maybe 100) and then use some of the numpy interpolation routines on each of the task groups to sample appropriately.

I *think* that this is all somewhat normal for interpolation processes.  I'm guessing that this is moderately tricky, but shouldn't require any deep novelty on our part.

**Comment by mrocklin** [comment]
cc @bryevdv I think that this might an interesting non-trivial project if you're interested.

**Comment by jakirkham** [comment]
cc @randerzander (in case you have thoughts on this :)
