### ISSUE TITLE
dask sees pytorch model as daemonic 

### ISSUE THREAD

**Issue by garretvo19** [dask/distributed#5058]
Hi, 
I have the following code using dask :
`PATH = 'C:\Users\dvan\NERDA_model.pkl'
model = torch.load(PATH)
dmodel = dask.delayed(model)
text_batches = [df.iloc[i,7] for i in range(10)]

def text_pred(text, model):
  ner_task = model.predict_text(text)
  return ner_task  
ner_pred = [text_pred(text, dmodel) for text in text_batches]
predictions = dask.compute(*ner_pred)
`
However, I got the following error: AssertionError: daemonic processes are not allowed to have children
Can anyone help? Thanks

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @garretvo19. Are you able to provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)? The full traceback from the `AssertionError` would be useful too. 

Also, how are you creating your Dask cluster? FWIW this type of issue has come up before when using PyTorch (xref https://github.com/dask/distributed/issues/2718) and, at least in that case, setting the [`distributed.worker.daemon`](https://docs.dask.org/en/latest/configuration-reference.html#distributed.worker.daemon) configuration setting to `False` helped resolve their issue.

**Comment by garretvo19** [comment]
@jrbourbeau . That is the example I tried to use. The full traceback is below:

`
 ---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<command-239758> in <module>
----> 1 predictions = dask.compute(*ner_pred)

/dats/python/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

/dats/python/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2723                     should_rejoin = False
   2724             try:
-> 2725                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2726             finally:
   2727                 for f in futures.values():

/dats/python/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1990                 direct=direct,
   1991                 local_worker=local_worker,
-> 1992                 asynchronous=asynchronous,
   1993             )
   1994 

/dats/python/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    831         else:
    832             return sync(
--> 833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )
    835 

/dats/python/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

/dats/python/lib/python3.7/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

/dats/python/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

/dats/python/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1849                             exc = CancelledError(key)
   1850                         else:
-> 1851                             raise exception.with_traceback(traceback)
   1852                         raise exc
   1853                     if errors == "skip":

/dats/python/lib/python3.7/site-packages/dask/utils.py in __call__()
    891 
    892     def __call__(self, obj, *args, **kwargs):
--> 893         return getattr(obj, self.method)(*args, **kwargs)
    894 
    895     def __reduce__(self):

/dats/python/lib/python3.7/site-packages/NERDA/models.py in predict_text()
    310                             tag_encoder = self.tag_encoder,
    311                             tag_outside = self.tag_outside,
--> 312                             **kwargs)
    313 
    314     def evaluate_performance(self, dataset: dict, **kwargs) -> pd.DataFrame:

/dats/python/lib/python3.7/site-packages/NERDA/predictions.py in predict_text()
    175                           pad_sequences = pad_sequences,
    176                           tag_encoder = tag_encoder,
--> 177                           tag_outside = tag_outside)
    178 
    179     return sentences, predictions

/dats/python/lib/python3.7/site-packages/NERDA/predictions.py in predict()
     83 
     84     with torch.no_grad():
---> 85         for _, dl in enumerate(dl):
     86 
     87             outputs = network(**dl)

/dats/python/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __iter__()
    277             return _SingleProcessDataLoaderIter(self)
    278         else:
--> 279             return _MultiProcessingDataLoaderIter(self)
    280 
    281     @property

/dats/python/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __init__()
    717             #     before it starts, and __del__ tries to join but will get:
    718             #     AssertionError: can only join a started process.
--> 719             w.start()
    720             self._index_queues.append(index_queue)
    721             self._workers.append(w)

/dats/python/lib/python3.7/multiprocessing/process.py in start()
    108                'can only start a process object created by current process'
    109         assert not _current_process._config.get('daemon'), \
--> 110                'daemonic processes are not allowed to have children'
    111         _cleanup()
    112         self._popen = self._Popen(self)
`
I will take a look at your suggestion. Thank you

**Comment by garretvo19** [comment]
it resolves the issue. Thank you
