### ISSUE TITLE
Bokeh is validating properties

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5064]
I'm noticing that my laptop is hot even with an idle cluster.  I brought up the profile-server chart to look at what was going on and it looks like Bokeh is pretty active validating properties, which it shouldn't be doing.  I looked at the line profile and found that for example, this line was triggering validation

https://github.com/dask/distributed/blob/5f01fe6010a0a3621956920d0260ac5f0111f17d/distributed/dashboard/components/scheduler.py#L2408-L2413

despite the containing method being wrapped with `@without_property_validation`

cc @jsignell @bryevdv

**Comment by fjetter** [comment]
Peaking at the code of the validation decorator in https://github.com/bokeh/bokeh/blob/branch-2.4/bokeh/core/property/validation.py

it appears we could disable the validation globally by setting 

```python
from bokeh.bases import Property
if not hasattr("_should_validate", Property):
    # We're kind of hooking into private API here so we should check if smth changed
    raise RuntimeError("Bokeh API changed")
Property._should_validate = False
```

That's of course a bit fragile. I'm fine with decorating everything. maybe we can also find a nice place where we apply this decorator *once* high up the stack. 

Assuming we actually never want this kind of validation to happen, of course.

**Comment by mrocklin** [comment]
We could do this in the CLI commands (dask-worker and so on) but it feels unclean to do it globally within Dask in case other folks want validation and are using Bokeh.

**Comment by bryevdv** [comment]
@fjetter there is public API for that (on a phone not handy to link)
