### ISSUE TITLE
Make actor futures play with as_completed

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#5077]
Based on [this slack thread](https://app.slack.com/client/T019Q6SMM5Z/C019Q0QSD4J) , it would be nice if `as_completed` respected actor futures as well as normal ones. Now actor futures are not actually awaitable:
```
    def __await__(self):
        return self.result()
```
(which is a blocking call, that waits on a queue.Queue, `self.q.get()`) but it could be, since we can check for the appearance of an item in the queue (`q.empty()`) or that the result is already cached.

**Comment by martindurant** [comment]
Also doesn't play with `client.gather`: `gather(actor_future) -> actor_future`. I can tweak ActorFuture to make it more Future-like and for this work, probably, but I don't know why they had to be separate things in the first place.

**Comment by martindurant** [comment]
```diff
--- a/distributed/actor.py
+++ b/distributed/actor.py
@@ -241,14 +241,33 @@ class ActorFuture:
         self.io_loop = io_loop
         if result:
             self._cached_result = result
+        self.status = "pending"

     def __await__(self):
         return self.result()

+    async def _result(self, raiseit=True):
+        while not hasattr(self, "_cached_result"):
+            if self.q.empty():
+                await asyncio.sleep(0.01)
+            else:
+                out = self.q.get()
+                if out["status"] == "OK":
+                    self._cached_result = out["result"]
+                else:
+                    self._cached_result = out["exception"]
+        if isinstance(self._cached_result, Exception):
+            self.status = "error"
+            raise self._cached_result
+        self.status = "finished"
+        return self._cached_result
+
     def result(self, timeout=None):
         try:
             if isinstance(self._cached_result, Exception):
+                self.status = "error"
                 raise self._cached_result
+            self.status = "finished"
             return self._cached_result
         except AttributeError:
             out = self.q.get(timeout=timeout)
```
solves `as_completes`.

**Comment by mrocklin** [comment]
There is no intention around keeping them separate.  Actors were originally built quickly as an experiment.  Their implementation was different enough that little attempt was made to make them like normal futures.

What you propose seems fine.  However, I would prefer to avoid polling.  Perhaps we should switch from a `queue.Queue` to an `asyncio.Queue` instead.

**Comment by mrocklin** [comment]
it sounds like to do this we would want to make the async `_result` method the main way to get a result.  We would then define `result` using the client.sync method.

**Comment by martindurant** [comment]
Do you have an immediate feeling or memory of how much effort it would take to get full Future comliance?

> we should switch from a queue.Queue to an asyncio.Queue instead.

Agreed, if this is easy. I haven't tried yet. The work may be in another thread in this process (asyncio.Queue is not tread-safe), and is accessed via __getattr__ (blocking), so maybe not straight forward.

> We would then define result using the client.sync method.

This certainly occurred to me - this is, of course, scratch code.

**Comment by mrocklin** [comment]
> The work may be in another thread in this process

Nope.  All logic in distributed happens on the main event loop thread.  You shouldn't need another thread for this.  

> so maybe not straight forward

I'm confident that if you stick to everything running on the event loop thread that things will work out.
