### ISSUE TITLE
JupyterLab polling and Dashboard redirection cause painful slowdown

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5087]
I noticed that when having JLab up my session was really expensive, even when it wasn't doing much. 

I looked at the /profile-server chart, and saw that we were spending most of our time updating bokeh plots.  This lead to https://github.com/bokeh/bokeh/issues/11424

I put in a print statement and saw that we were sending all of the rectangles in the TaskStream up, even if there was no change, or even if we weren't looking at the TaskStream plot.  This kept happening, about once every second or two.

I suspect what is happening here is that the Dask JupyterLab extension is looking at `/`, which is redirecting to `/status`, which triggers a whole bunch of charts to be made for just a moment.  Probably we want to query some other endpoint?

cc @ian-r-rose

**Comment by ian-r-rose** [comment]
What version of `dask-labextension` are you using? There was an issue very much like this (#4827, dask/dask-labextension#185), but it should have been fixed as of the most recent release (5.0.2), in which we started trying to just look at `individual-plots.json` for just this reason.

**Comment by mrocklin** [comment]
Ah, indeed.  I may have had a dev version installed which was clobbering attempts to get a recent release.  Trying now ...
