### ISSUE TITLE
Status page misaligned

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5089]
![image](https://user-images.githubusercontent.com/306380/126073863-11050cf3-9122-4130-9512-9ceba791a9d9.png)

The Processing/CPU/Occupancy chart is huge while the task stream chart is small.  I suspect the recent use of tabs.  I'm not sure though.

cc @ncclementi

**Comment by mrocklin** [comment]
Another failure

![image](https://user-images.githubusercontent.com/306380/126073960-7effa00d-0536-4d89-b87f-7ffecba5162b.png)

This should be fitting to the screen I think.

**Comment by mrocklin** [comment]
Hrm, that screenshot didn't come out well.  Trying again

![image](https://user-images.githubusercontent.com/306380/126073989-7c23a283-0022-4388-b2a8-277fe84f07ef.png)

In particular note that the xaxis of the Occupancy chart isn't visible.  I believe that this was previously handled.

**Comment by mrocklin** [comment]
If we don't find a solution before the release this Friday then I recommend
that we revert the tabs commit.

**Comment by jsignell** [comment]
What version of bokeh were you on? I am on 2.2.3 and having trouble reproducing.

**Comment by ncclementi** [comment]
I'm on bokeh  2.3.2
The problem happens when you shrink the status page.

**Comment by jsignell** [comment]
Ok upgrading my bokeh

**Comment by ncclementi** [comment]
I can confirm that if I downgrade to bokeh 2.2.3 and up to 2.3 things seem to work well. When trying 2.3.1 then things break. I'm not sure why but this look like a bug on the bokeh end.

**Comment by jsignell** [comment]
Yeah 2.3.3 looks good. I'll just check that I see oddness with 2.3.1

**Comment by ncclementi** [comment]
So in conclusion we should avoid bokeh 2.3.1 and 2.3.2.

**Comment by jsignell** [comment]
Haha yeah! I was just arriving at that conclusion as well :)

**Comment by jsignell** [comment]
I did find https://github.com/dask/distributed/pull/5094 as well while I was squishing up the dashboard.

**Comment by jrbourbeau** [comment]
Thanks for investigating @ncclementi @jsignell! It sounds like "please update your bokeh version" is the recommendation here. Is it safe to close this issue?

**Comment by fjetter** [comment]
> It sounds like "please update your bokeh version" is the recommendation here. Is it safe to close this issue?

Do we want to set a minimal bokeh version? This way a `conda update distributed` would pick this up as well

**Comment by ncclementi** [comment]
> Do we want to set a minimal bokeh version? This way a `conda update distributed` would pick this up as well

It could be an option, although the problem seems to be only in bokeh 2.3.1  and 2.3.2. Is it too pushy to set the minimal as the latest 2.3.3 (July 2021)?

**Comment by mrocklin** [comment]
I recommend that we move on.  I think that this problem will fix itself.
There are probably bigger things to resolve.

**Comment by jrbourbeau** [comment]
Yeah, +1 for not pinning to hard here. For reference, we have [explicitly disallowed certain `bokeh` versions](https://github.com/conda-forge/dask-feedstock/blob/2aeda30fafc40d8142ff3a20a95bd9e9bb0be821/recipe/meta.yaml#L22) before but usually we only do this when things totally fall down (which happens very rarely)
