### ISSUE TITLE
Observed worker network bandwidth chart

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5090]
We have a couple of charts for inter-worker bandwidth that use our own metrics.  I don't trust these metrics that much.  We also keep per-worker metrics.  These are currently reported in the /workers tab with read/write at the end of the table.  I think that these are recorded with psutil and are sent in the worker heartbeats.  We might want to create another real-time bar-chart like occupancy/cpu/memory but for read/write traffic.  

This is slightly more complex because there are a couple of different values to show for each worker.  As options I could imagine ...

1.  Summing these up
2. Overplotting both with colors that make it clear which one is ahead
3. Plotting two skinnier rectangles per worker

**Comment by fjetter** [comment]
I would actually love to see the measured bandwidths as a timeseries plot since they vary quite a bit over time, but I'm not sure how feasible this is

**Comment by mrocklin** [comment]
It's pretty feasible.  We would copy the /system charts.

Personally, I'd love both :)

**Comment by mrocklin** [comment]
For context we already have this data rendered in the workers chart here:

![image](https://user-images.githubusercontent.com/306380/126406711-7fd4641e-60c4-44e8-9d8b-80a351c4f8d2.png)

(see the last two columns, the top row is the sum)

it would be good to have this same information rendered much in the same way we do for cpu/occupancy/nbytes charts for realtime status

![image](https://user-images.githubusercontent.com/306380/126406762-c1eab711-462d-4599-98a4-c8bd5f2394ee.png)

As well as a timeseries plot, much like how we do the /system charts

![image](https://user-images.githubusercontent.com/306380/126406823-fdecaf24-3534-4fe4-b9d9-c069bea3c9cb.png)


Personally, for the realtime chart I would just copy the occupancy/cpu/... charts, swap out CPU stats for network io stats (consulting the /workers chart to see where those are coming from) and then maybe that's it.

For the timeseries chart I would probably just plot the total bandwidth, rather than one value for every worker.  If we wanted to be clever we could have both a left and right axis for total and average bandwidth respectively.

**Comment by ncclementi** [comment]
After looking into this a bit more I have some questions/ comments. 
For the first plot (Nbytes looking one)
- Is the idea to have read and write per worker overlapped with different colors and some alpha? 
- If we are plotting memory, what is the connection with the cpu/occupancy/etc plots, don't we want a plot more like the Bytes stored per worker but that has read bytes and write bytes with network io stats? 

For example, if I have 2 workers I would have to horizontal bars that each one shows read_bytes and write_bytes(where this data comes from `ws.metrics.read_bytes` and `ws.metrics.write_bytes`)

For the times series chart, I'm not sure if I'm understanding this correctly: 
We want a time series per worker that has the total bandwidth and this is would be the sum of `ws.metrics.read_bytes` and `ws.metrics.write_bytes`, is this correct?

**Comment by mrocklin** [comment]
> Is the idea to have read and write per worker overlapped with different colors and some alpha?

Naty and I discussed this briefly we decided to go with multi-bar plots like the following

![image](https://user-images.githubusercontent.com/306380/126552352-0d75f207-bd74-4a67-9490-82fdc7b42384.png)

**Comment by mrocklin** [comment]
Although I think in our situation we should skip the whitespace.  It would be good if these bars corresponded with the other horizontal bar charts so that people can compare CPU use against bandwidth.

**Comment by mrocklin** [comment]
I'm going to reopen this so that we continue to track the timeseries option (which I think would be valuable)

**Comment by jrbourbeau** [comment]
Whoops, thanks for re-opening
