### ISSUE TITLE
Joblib integration does not use dask workers from local cluster and bokeh monitor does not show any tasks (using PyCharm – Jupyter Notebook)

### ISSUE THREAD

**Issue by DrHolgerLange** [dask/distributed#512]
Here is my setup with a small example:

**Ubuntu 16.04** with **PyCharm 2016.2.3** as IDE and Anaconda/Conda (with added conda-forge-channel) as package and environment manager, using **Python 2.7.12** and the following packages (installed 9/12/2016): **jupyter 1.0.0**, **scikit-learn 0.17.1**, matplotlib 1.5.3, pandas 0.18.1, numexpr 2.6.1, bottleneck 1.0.0, graphviz 0.5.1 (pip), pydotplus 2.0.2 (pip), dask 0.11.0, **distributed 1.13.0** (github), **joblib 0.10.2** (pip), dask-ec2 0.3.0, cachey 0.1.1 (pip).

```
from distributed import LocalCluster
cluster = LocalCluster()
cluster
```
_LocalCluster("127.0.0.1:8786", workers=12, ncores=12)_

```
cluster.start_diagnostics_server()
```
_AssertionErrorTraceback (most recent call last)<ipython-input-2-883d1caa05e4> in <module>()
----> 1 cluster.start_diagnostics_server()
      2 # Firefox: http://127.0.0.1:8787/status
/home/drh/sw/anaconda2/envs/ds2/lib/python2.7/site-packages/distributed-1.13.0-py2.7.egg/distributed/deploy/local.pyc in start_diagnostics_server(self, port, show, silence)
    178             return
    179 
--> 180         assert self.diagnostics is None
    181         if 'http' not in self.scheduler.services:
    182             self.scheduler.services['http'] = HTTPScheduler(self.scheduler,
AssertionError:_ 

Firefox: http://127.0.0.1:8787/status

```
import distributed.joblib
from joblib import Parallel, parallel_backend
```

```
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
pipe = Pipeline(steps=[('RandomForest', RandomForestClassifier(n_estimators=1000, n_jobs=-1))])
grid = {'RandomForest__max_depth': range(1,21)}
```

```
from sklearn.grid_search import GridSearchCV
grid_search = GridSearchCV(pipe, grid, n_jobs=-1)
```

```
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data, iris.target_names[iris.target]
```

```
with parallel_backend('distributed', scheduler_host='127.0.0.1:8786'):
    %time grid_search.fit(X, y)  
```
_CPU times: user 3.48 s, sys: 740 ms, total: 4.22 s
Wall time: 19.6 s_

The bokeh monitor shows only an increase in CPU activity, but does not report anything on the task processing! Using glances (system monitoring) I can see that there are 12 dask workers created after creating the local cluster, but then there are another 12 dask workers created to handle the joblib.

**Comment by mrocklin** [comment]
SKLearn seems to vendor its own version of `joblib` in `sklearn.externals.joblib`.  It doesn't work nicely with the proper `joblib` library.

You may want to check out the example in the [distributed.joblib docs](http://distributed.readthedocs.io/en/latest/joblib.html) although this seems to require sklearn 0.18.0

cc @ogrisel

**Comment by DrHolgerLange** [comment]
Thank you for your quick response.

Yes, now with **scikit-learn 0.18.dev0 (git clone git://github.com/scikit-learn/scikit-learn.git)** scikit-learn's joblib integration as described on your webpage works!
