### ISSUE TITLE
Dask Dashboard "More" tab not accessible from "Workers" tab

### ISSUE THREAD

**Issue by rrpelgrim** [dask/distributed#5136]
**What happened**:
When on the "Workers" page of the Dask Dashboard, the "More" tab is not fully accessible. 
It drops down but I can't navigate to any items past "Groups". Seems like there's a conflict with the underlaying information in the read/write columns of the workers. See screencast below.

https://user-images.githubusercontent.com/68642378/127451332-87049b74-85a5-48bc-94f9-9c7601b07679.mov

**What you expected to happen**:
To be able to click on items in the "More" tab like "CPU", "Cluster Memory", etc. etc.

**Minimal Complete Verifiable Example**:

```python
import coiled
import dask.dataframe as  dd
from dask.distributed import LocalCluster

client = LocalCluster()
client
```

**Anything else we need to know?**:

**Environment**:

- Dask/Distributed version: 2021.07.1
- Bokeh version: 2.3.3
- Python version: 3.8
- Operating System: OS 11.3.1
- Install method (conda, pip, source): conda

[EDIT]
- Browser: Brave 1.27.108, Chrome 92.0.45 , Firefox 90.0.2
- clearing the cache does not resolve the issue for me

**Comment by fjetter** [comment]
I'm neither a bokeh nor a JS specialist so I won't be able to resolve this. However, this kind of thing sometimes relates to browser versions. You could try a different browser and/or see if there is an update for yours available. Either way it will likely be useful if you can post which browser+version you are using.
Lastly, with the newly introduced tabs, we've seen issues related to browser caching. Does clearing your browser cache help?

**Comment by rrpelgrim** [comment]
Thanks @fjetter, forgot to list my browsers indeed!
I've updated my issue above, listing browsers and respective versions.
Clearing the cache didn't help for me, unfortunately.

**Comment by jrbourbeau** [comment]
cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Interesting! It looks like the `z-index` of the content in the workers table is being set higher than the dropdown and is therefore sitting in front. This breaks the hover functionality.

However I am unable to reproduce in Firefox, Chrome or Safari on macOS.

**Comment by ncclementi** [comment]
I can reproduce on Firefox 90.0.2 and Safari 14.1.1 on macOS, and clearing the cache does not resolve the issue for me either.
Currently on Dask and Distributed 2021.07.2 (and I've tried with distributed main too) and I see the same as @rrpelgrim 

![more_tab_workers](https://user-images.githubusercontent.com/7526622/128248425-bd444978-1a19-40c8-8fe1-15ebc33de17d.gif)

cc @jsignell

**Comment by jsignell** [comment]
Yeah I can reproduce on any browser. As @jacobtomlinson suggested, I set the z-index for the workers table to 0 in my dev console and that seems to fix it. Now it's just a matter of finding where to put that in the codebase :)

**Comment by jacobtomlinson** [comment]
No idea why I wasn't able to reproduce this but things should be good now! Thanks @jsignell.
