### ISSUE TITLE
can't upload files 

### ISSUE THREAD

**Issue by xxxxsk** [dask/distributed#5138]
When I was deploying my project， I can't  import func from my *.py, and there is a FileNotFoundError after client.upload_file('')

The directory structure
dask_test
 - run.sh
 - test.py
 - upload_file.py
 
run.sh:
```
/opt/anaconda3/envs/pymodel/bin/dask-yarn submit \
  --environment python:///opt/anaconda3/envs/pymodel/bin/python \
  --worker-count 5 \
  --worker-vcores 2 \
  --worker-memory 4GiB \
  test.py
```

test.py:
```python
from dask_yarn import YarnCluster
from dask.distributed import Client
import time
import pandas as pd
import os

cluster = YarnCluster.from_current()
client = Client(cluster)

def square(x):
    return x ** 2
ts = time.time()
client.upload_file('upload_file.py')
A = client.map(square, range(5))
total = client.submit(sum, A)
print(total.result())
print('1cost time :%s'%(time.time()-ts))
client.close()
cluster.close()
```

**Anything else we need to know?**:
I want to konw how to correctly upload file and import ?

**Environment**:

- Dask version:2.11.0
- Python version:3.6.10
- Install method (conda, pip, source):pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @xxxxsk. Your use of `client.upload_file` looks correct. Can you confirm that the `upload_file.py` file exists in the location where you're running `test.py`? You can do this by adding 

```python
import os
assert os.path.exists("upload_file.py")
```

at the top of `test.py`

**Comment by xxxxsk** [comment]
@jedbrown thanks.
As expected, there is an AssertionError
```python
Container: container_1614664426291_1553_01_000007 on optimus10a144_8041
=========================================================================
LogType:dask.worker.log
Log Upload Time:Thu Jul 29 23:06:26 +0800 2021
LogLength:1326
Log Contents:
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.50.30.144:32816'
distributed.worker - INFO -       Start worker at:   tcp://10.50.30.144:47467
distributed.worker - INFO -          Listening to:   tcp://10.50.30.144:47467
distributed.worker - INFO -          dashboard at:         10.50.30.144:60669
distributed.worker - INFO - Waiting to connect to:   tcp://10.50.30.143:38165
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /home/yarn/nm/usercache/guozhiheng/appcache/application_1614664426291_1553/container_1614664426291_1553_01_000007/dask-worker-space/dask-worker-space/worker-y8vkckut
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://10.50.30.143:38165
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.process - INFO - reaping stray process <SpawnProcess(Dask Worker process (from Nanny), started daemon)>


Container: container_1614664426291_1553_01_000008 on optimus10a144_8041
=========================================================================
LogType:dask.client.log
Log Upload Time:Thu Jul 29 23:06:26 +0800 2021
LogLength:208
Log Contents:
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    assert os.path.exists("upload_file.py")
AssertionError
User submitted application test.py failed with returncode 1, shutting down.
```
upload_file.py file exists in the location where i am running test.py, while I submit the project whit --deploy-mode remote, it seems that  the upload_file.py doesn.t exists in the client or workers.The location has changed to  yarn after the submited.

**Comment by jrbourbeau** [comment]
Ah, good to know, thanks for trying that out. `Client.upload_file` is for uploading local files, so if `upload_file.py` doesn't exist then `client.upload_file('upload_file.py')` throwing an error is expected. 

If your yarn cluster has a shared filesystem, you can update the path you pass to `Client.upload_file` to be relative to that shared filesystem. Otherwise, you might consider packaging your Python module (`upload_file.py`) and following some of the suggestions in https://yarn.dask.org/en/latest/environments.html for managing Python environments when using `dask-yarn`

**Comment by xxxxsk** [comment]
@jedbrown thanks. I will try the solution. By the way,  I konw that skein can  upload files in the submit configuration, will dask support upload files not only environment.tar.gz but files such as local scripts when dask-yarn submit in  the future?

**Comment by jrbourbeau** [comment]
I'm not sure. That's probably a question for the `dask-yarn` issue tracker https://github.com/dask/dask-yarn/issues

**Comment by xxxxsk** [comment]
@jedbrown  yeah,it should be.

**Comment by ncclementi** [comment]
@xxxxsk checking in here and letting you know I will close this issue since it seems your conflicts/questions are related to `dask-yarn`.  If you think differently, please feel free to re-open the issue.
