### ISSUE TITLE
Auto GIF!

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#5161]
Lately, I'm seeing more and more GIFs of the Dask dashboard being posted onto twitter.  I'm curious if there is any appetite for more tightly integrating some tooling into Dask to make it easier to generate GIFs of the dashboard.  My current workflow is:

1. Setup Dask Dashboard
2. Quicktime recording
2. Convert to GIF with https://ezgif.com
3. Download GIF and re-share

I heard recently from @jrbourbeau that @ncclementi likes https://github.com/wulkano/Kap though I have never tried it --  I'll correct that this week

In any case, I think making it easier to make GIFs and thus promote Dask and/or the Dask Dashboard would be a good marketing effort for us/community engagement.

**Comment by mrocklin** [comment]
I'm curious what @bryevdv uses?

**Comment by bryevdv** [comment]
I learned a long time ago that a Screenflow license is just worth the investment. I set the default export type to Animated GIF of a given size, and I have the gif on my desktop ready to drag and drop into an upload box about 5 seconds after the recording is stopped.

**Comment by ncclementi** [comment]
@quasiben Kap it's been super easy to use and you export directly on GIF, the only disadvantage is that it is also only for OSX. I know there is something a similar for Ubuntu, called [peek](https://github.com/phw/peek) but I have never tried it.

**Comment by quasiben** [comment]
How insane would it be to take headless snapshots and compose the GIF from pngs ?  cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
My workflow is the same as @quasiben. For the headless snapshots are you thinking of having something in Dask that could do this?

```python
from dask.distributed import snazzy_gif

with snazzy_gif(plot="taskstream", filename="awesome-clip.gif"):
    ## some dask computation
```

I think this would be hard 😆

**Comment by mrocklin** [comment]
+1 on the name though

**Comment by quasiben** [comment]
Yeah :( -- was hopping for some context manager like `performance_report` to generate the gif.  If it's ok with folks can we let this issue linger a bit.  If it gets no traction after a week or so I'll close

**Comment by ncclementi** [comment]
@quasiben checking in here, and seeing if you want to keep this one open. I was reading a bit and see if it would be possible to do this and a possibility might be to [export multiple snapshots](https://docs.bokeh.org/en/latest/docs/user_guide/export.html) as png from the taskstream (we could probably call this on the update method) and then use those snapshots to create a gif afterwards with `ffmpeg` or similar. Although, I'm afraid that this will slow things down since they are io operations.

**Comment by quasiben** [comment]
Yeah, unfortunately I don't think this will be easy to do and as you say, it will mostly likely slow things down.  Thanks for entertaining the idea.  I'll close

**Comment by jacobtomlinson** [comment]
Before we completely say no to this idea I wonder if we could get close by doing something on the client-side.

It is possible to [record canvas elements as a video from JavaScript](https://medium.com/@amatewasu/how-to-record-a-canvas-element-d4d0826d3591) (and as far as I know Bokeh uses canvas, right @bryevdv?). We could potentially add some record buttons in the dashboard itself?

**Comment by bryevdv** [comment]
Yes, uses canvas by default (i.e. unless SVG output is configured). Saving canvas data as image URLs is how the current on-plot `SaveTool` functions FYI.

**Comment by jacobtomlinson** [comment]
Yeah I thought so. Do you think it would be tricky to implement a `recordTool` that uses the `MediaRecorder` to output an MP4?  Perhaps with a start/stop toggle button?

**Comment by bryevdv** [comment]
I'm not sure offhand, I've never used `MediaRecorder`. It seems plausible.
