### ISSUE TITLE
Clarify semantics of `Future.type`

### ISSUE THREAD

**Issue by stefanseefeld** [dask/distributed#518]
A Future's `type` attribute may be None. Assuming that the type represents the return type of the function / task being executed, it is clear that the type may only be available after the future is completed.

However, in certain cases a future may not have a type even when its status is 'finished'. It would be useful to change that so Futures are guaranteed to have a type once their status is 'finished'. (In that case 'None' may still be a valid type: representing functions returning 'None'...

**Comment by mrocklin** [comment]
The type of `None` is `NoneType`

```python
In [1]: type(None)
Out[1]: NoneType
```

I believe that there are some rare cases where we learn of the existence of data without knowings its type.  In these cases it seems sensible to keep the type as None, representing that it is not known.

**Comment by stefanseefeld** [comment]
```
    a, = client.scatter([5])
    print('type of a is', a)
```
reports
```
type of a is <Future: status: finished, key: 7b4b5c735acdd7ee3b2fafd41bc5be78>
```
It isn't clear why the future can't report the type of `a` in that case.

**Comment by mrocklin** [comment]
OK, would you raise an issue that scatter should propagate type information then?

Generally speaking issues should be raised of the following form:

* I'm doing this specific and reproducible set of steps
* I expected the following result
* But instead I got this

It looks like your example almost fits this mold perfectly.

**Comment by stefanseefeld** [comment]
I created https://github.com/dask/distributed/issues/521, which you may consider a follow-up issue, so feel free to close this one.
