### ISSUE TITLE
scheduler immediately takes up > 40 GB of memory

### ISSUE THREAD

**Issue by mdering** [dask/distributed#5180]
**What happened**:
whenever I start the scheduler on linux, it immediately takes up >40 GB of memory, and often gets restarted because the system is OOM. There are 170 workers connected to it, mostly linux, but a few are windows workers. 

**What you expected to happen**:
Not to happen
**Minimal Complete Verifiable Example**:
Sorry I don't have anything that helps with this. I'm happy to run whatever you might ask since this is pretty critical and I'm not sure how long the system can limp along like this.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.07.2
- Python version: 3.7.11
- Operating System: RHEL 8
- Install method (conda, pip, source): conda

**Comment by fjetter** [comment]
Does the same occur if there are no workers connecting to it? Just starting the scheduler without anything else?

**Comment by mdering** [comment]
no it doesn't. I closed all the workers, then restarted the scheduler, then brought all the workers back up, and now the memory usage is only 15 GB. Is there a specific reason for this? should this be our best practice from now on? I should mention the above occurred even with no clients connected and no tasks running.

**Comment by fjetter** [comment]
This should not happen at all, regardless of what you're doing. I was just wondering what happens if you reduce it to the minimal configuration. 15GB is still a lot for a scheduler. The 15GB are only used by the scheduler or are the workers running on the same machine and this is all accumulated?

**Comment by mdering** [comment]
Its what `top` says the memory use is by the python process. Previously we had workers running on this machine, but i disabled them since we have just enough memory to keep the scheduler up.

**Comment by fjetter** [comment]
I cannot provide any more help without more information. This sounds highly unusual since the scheduler itself does not allocate that much memory. I've seen it growing to a few GBs after running a while but not to that extend; I've never seen it beyond ~10GB even on large clusters with long runtime. This kind of memory growth is typically due to logging information we keep but this is limited by design (see config options like `transition-log-length`)

My first line of investigation would be to figure out if the deployment is doing anything "weird". Are you disabling GC, loading any huge libraries or data? You mentioned having windows workers on a linux scheduler. I didn't even know this would work but that sounds like you have a complicated setup. I would suggest to reduce this to a minimal setup and try debugging it from there.

**Comment by mdering** [comment]
Is there some reason we cant have some cross platform work? we need windows workers to connect to a 3rd party data source, and linux workers do most of the compute. anecdotally we found the linux scheduler had fewer issues like this, but with the newer version we see it getting reaped by the oom manager, and ballooning to a massive size without any input. I just checked on it and its at 36 GB. I can list some peculiarities of our setup below, see if any of these are helpful, I'm also happy to answer any other questions you might have
* 170 workers, across 10 linux machines and 1 windows machine
* the windows machine runs the client process as well as a few workers
* `transition-log-length` is 10000, `task-stream-length` is 1000 for status and 100000 for tasks
* the scheduler runs on a RHEL 8 box with no workers on it at the moment so it doesn't run out of memory
* for debugging and consistency we use custom keys with descriptive names so we know what tasks are failing
* we do load libraries and data, but its not too big, and none of that takes place on the scheduler itself. the scheduler does not load a preload file of any kind.
* GC is not disabled. 

I'm happy to reduce to a minimal setup and try to debug but I'm not sure what that would look like. Disable workers on most of the machines and see if that behaves better? Obviously, this is not a very good long term solution since we use that compute to drive faster turnaround times for the customers. I *really* appreciate you helping me out here, hopefully we can look in to what could be causing this

**Comment by fjetter** [comment]
> Is there some reason we cant have some cross platform work?

Serialisation is often very sensitive to low level versions, e.g. having the same python version. Pandas is also using some cythonized code to (de-)serialize code and there are a few other libraries as well which use native code behind the scenes. For cross platform operations you need to ensure that all layers in between behave correctly.
We do not test this so I cannot tell you if it works. I was just saying that I'm positively surprised that it works.

> I'm happy to reduce to a minimal setup and try to debug but I'm not sure what that would look like.

you told me that the scheduler alone without any workers already allocates 15GB of memory. My first steps would be to reproduce this and see what takes so much memory. That requires some memory profiling and code instrumentation. There is nothing out of the box available to do this.
If this doesn't reveal a smoking gun, add on more workers and find out how you get from 15 to 40 GB.

**Comment by fjetter** [comment]
> but with the newer version we see it getting reaped by the oom manager,

On a previous version you didn't observe this behaviour? Can you tell me what the last version was which worker well for you?
Starting with `2021.07.1` we started setting some environment variables which can impact how the libc memory allocator frees memory, see https://github.com/dask/distributed/pull/5098#issue-693934628 / https://distributed.dask.org/en/latest/worker.html#automatically-trim-memory

but that shouldn't cause a significant increase in memory, rather the opposite

**Comment by mdering** [comment]
scheduler memory has always been a bit opaque to us. I'm curious how you would set about instrumenting a scheduler that just starts up and immediately consumes plenty of memory, that's all dask space code, right? Is there anything that persists for the scheduler that I'm not aware of? I forgot to mention we also do connect directly to the workers. In earlier versions this seemed to help keep the scheduler memory down, especially if we started seeing issues, since workers dying or tasks failing seemed to make the memory usage go up a lot. 

`client = distributed.Client(f'{scheduler_host}:{scheduler_port}', name="dask_eval", direct_to_workers=True)`

I had plans to integrate jemalloc and to set the environment variable in our next release, but i haven't done that yet. I can definitely experiment with an environment variable and see if that helps

**Comment by mdering** [comment]
I added that variable to the scheduler service we deployed, I'll update you later on about how its performing.
