### ISSUE TITLE
Switch to using subprocesses slows down Client() use

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#519]
Creating a local cluster is a common case

```python
from distributed import Client
c = Client()
```

Recently we switched from using fork/multiprocessing to using subprocess so that we could deploy workers in other Python executables.  This is a fairly uncommon case.  It is unfortunate that the common case suffers from the uncommon case.

It might be worth letting Nanny's create workers with both mechanisms, only using `subprocess` if the executable is different from the nanny's executable.

**Comment by minrk** [comment]
It's just the instantiation that's taking time? It seems like you could return from the constructor without waiting for the workers to be fully connected, only waiting for the Scheduler.

What sort of performance are you seeing and on what system? When I test it on an 8-core i7, I get a Client with 8 engines in 100ms, which seems pretty reasonable. I get a Client with 80 engines in 800ms, which is pretty slow, but that's a lot of workers for one machine.

**Comment by mrocklin** [comment]
Using fork workers come up in 10s of milliseconds as you've seen.  Using subprocess it's taking a few seconds.  I've actually already implemented this in https://github.com/dask/distributed/pull/520 and just issued a micro-release in 1.13.2.

**Comment by mrocklin** [comment]
Fork is also just cleaner in lots of ways.  I ran into a few problems with the subprocessing solution not cleaning up properly.  These issues were fixed, but still I'll feel more comfortable relying on fork for the immediate future.  Switching to subprocess for the sake of https://github.com/dask/distributed/issues/300 was probably premature
