### ISSUE TITLE
Dashboard link redirects on same tab 

### ISSUE THREAD

**Issue by ncclementi** [dask/distributed#5192]
When  I click the link for the dashboard it redirects me to the dashboard but on the same tab instead of a new one, leaving me with no access to the notebook. I think it would be good that by default it redirects to a new tab. 

```
from dask.distributed import Client
client=Client()
client
```

![redirect_link](https://user-images.githubusercontent.com/7526622/128772563-8fa2217b-5de3-4671-ab27-f0eb0c8ab12c.gif)

Distributed version 2021.07.2 (tried on main too)
Browser Firefox 90.0.2 and Safari 14.1.1

**Comment by jrbourbeau** [comment]
Thanks for reporting @ncclementi! Unfortunately, I'm not able to reproduce on Firefox on my Mac. When I click the dashboard link in the client HTML repr, the dashboard is opened up in a separate tab. My HTML knowledge is quite limited, but we might [adding `target="_blank"` to this (and other) links](https://www.w3schools.com/tags/att_a_target.asp) to make sure they're opened in a new tab or window. cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
I am also unable to reproduce this. But I agree that adding a `target="_blank"` would be a robust way to avoid this.

**Comment by ncclementi** [comment]
@jacobtomlinson just to make sure, would you confirm this is the right place to add `target="_blank"` 
https://github.com/dask/distributed/blob/a0124ac56079320eac81f2210ec29a027fccbf56/distributed/widgets/templates/client.html.j2#L24

**Comment by jacobtomlinson** [comment]
Yeah, there are probably a few more if you look through the other templates.

https://github.com/dask/distributed/blob/a0124ac56079320eac81f2210ec29a027fccbf56/distributed/widgets/templates/cluster.html.j2#L10

https://github.com/dask/distributed/blob/a0124ac56079320eac81f2210ec29a027fccbf56/distributed/widgets/templates/scheduler_info.html.j2#L18
