### ISSUE TITLE
Include Peer address in CommClosedError

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5202]
When a worker in a network dies harshly we often experience a `CommClosedError` raised every other part of the cluster that had a connection to this worker.  To aid debugging I recommend that we include the address of the remote peer that was shut down in the CommClosedError that we raise.  This is often available in `comm._peer_addr`.  

cc @fjetter

**Comment by fjetter** [comment]
I think we have a few places in our code base where we're raising a `CommClosedError` although it should be something else. My point is, there is not always a comm around for us to attach to the `CommClosederror`

Do you have a traceback or smth detailing where this happens?

**Comment by mrocklin** [comment]
> Do you have a traceback or smth detailing where this happens?

I do not, but I suspect that searching github issues for CommClosedError will come up with a few :)
