### ISSUE TITLE
futures returned from `scatter` should report object's type

### ISSUE THREAD

**Issue by stefanseefeld** [dask/distributed#521]
I expect the following code
```
a, = client.scatter([5])
print('type of a is', a)
```
to include the 'type' attribute in the future output. What I get is
```
<Future: status: finished, key: 385d6ca61668cb602fe73705b413b0bc>
```

**Comment by stefanseefeld** [comment]
To motivate the need for Future.type a little more (as the question came up elsewhere):

Consider blaze' compute framework using `distributed` as backend. The `compute` functions need to know the type of the data to dispatch to the appropriäte function to implement the expression evaluation appropriately. That's impossible to do unless the `Future` objects can report the type of the referenced objects.
And while I may be able to infer the result type of an expression evaluation from the types of the expression leaf nodes, I need a way to query those if the leaf nodes are remote DataFrames or Series wrapped by `Future` objects...

**Comment by mrocklin** [comment]
OK thanks.  That definitely helps to motivate the work.   What's in #522 should be sufficient to start with.  There are corner cases where it won't work but I don't expect you'll run into them for a while.  My hope is that this is enough to handle short-term needs
