### ISSUE TITLE
Behaviour change: 2021.07.0 Works -> 2021.08.0 error "Tried sending message after closing" 

### ISSUE THREAD

**Issue by woodcockr** [dask/distributed#5211]
**What happened**:

I have a workflow (15-20 workers, 8 threads ,24 Gigs of RAM each, dask array, dask delayed in use) and it works fine on 2021.07.0. I attempted to update to a later version specifically to take advantage of the the root blocks patch  #4967 . 2021.07.1 and 2021.07.2 fail to run to completion with no information in logs (literally nothing - no errors, warning, nothing) - looks to me like it's stuck in a deadlock.

Tried 2021.08.0 and now I get a log with "Tried sending message after closing". This is consistent.

The actual workflow is looping through the same calculation each time with different inputs, and I have had it run to completion (and #4967 significantly improves memory usage, thank you!). Trouble is its unreliable. I can run the exact same run a second time and have it fail.

As an experiment I run the same workflow on 5 dask clusters simultaneously (I'm using dask-gateway on k8s so this would simple to do). 4 of the 5 failed with "Tried sending message after closing".

At the moment I'm not seeing any mention of comms errors or working dying. The "Tried sending message after closing" says something about a 10 s connection timeout - not sure what that is.

This is happening at scale but I figured the consistency of failure in 2021.08.0 might provide a hint to someone with more experience than I with the details of dask. That and the fact it doesn't occur in 2021.07.0 (though 2021.07.0 does appear to undertake retries).

I'm not quite sure how to navigate towards a minimal reproducer given the nature of the beast - at least 2021.08.0 is more consistent. If anyone has a suggestion on what might help get there I'm open to suggestions. I will try a few options when I next have opportunity to at least isolate it from my workflow which I can't share.

At the moment I'm thinking it might be a comms issue...

**What you expected to happen**:

It should complete the workflow 99.9% of the time.

**Minimal Complete Verifiable Example**:
TBD - looking for suggestions.
```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.08.0 Fails consistently, 2021.07.0 works. 2021.07.1/2 appear to deadlock
- Python version: 3.8.10
- Operating System: Ubuntu
- Install method (conda, pip, source): pip
- Dask Gateway: 0.9.0
- Dask Kubernetes: 2021.3.1

**Comment by fjetter** [comment]
The `Tried sending message after closing` is an exception raised on Client side if the connection to the scheduler broke down. That can have many reasons. Starting with an unreliable network up to the scheduler being actually dead. Are you able to reconnect the client (or a new client) to the scheudler after this happened? If so, does a subsequent computation succeed (something simple as `client.submit(lambda : True).result()`)?

Do you have any logs available surrounding this exception (primarily scheduler but also interesting for workers)?


Does the client issue logs like

```
Client report stream closed to scheduler
Reconnecting...
```

or is it completely silent?

**Comment by woodcockr** [comment]
timely response, thank you. 
2021.08.0 being consistent is proving helpful.
I changed my dask chunks size down to 1/4 the size, whether or not this is related is not the issue but I can now see in the logs one worker with:

`distributed.worker - INFO - Connection to scheduler broken. Reconnecting...

distributed.worker - ERROR - Traceback (most recent call last): File "//env/lib/python3.8/site-packages/distributed/worker.py", line 1892, in transition_flight_memory self.batched_stream.send({"op": "add-keys", "keys": [ts.key]}) File "//env/lib/python3.8/site-packages/distributed/batched.py", line 136, in send raise CommClosedError() distributed.comm.core.CommClosedError
...
distributed.worker - INFO - Comm closed
...'

where ... means there are multiple of this error repeated.
There are also other workers reporting compute failed due to missing dependents - presumably the ones that were on the Comm Closed worker.
Attempting the `client.submit(lambda : True).result()` on this cluster hangs.

The same workflow was repeat on 6 clusters using the same environment.
2 finished 4 errored

The 4 that errored all have a message in the futures (error) result:
`Exception: ('Long error message', "Tried sending message after closing.  Status: closed`
With the message saying `{'op': 'update-graph-hlg', 'hlg': {'layers': [{'__module__': 'dask.highlevelgraph', '__name__': 'MaterializedLayer', 'state': {'dsk': {...`

Followed by my function call and parameters.

The other clusters do not report `Connection to scheduler broken` but
errors in these clusters include:

`distributed.worker - ERROR - Worker stream died during communication: tls://100.64.166.148:33595 Traceback (most recent call last): File "//env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 198, in read frames_nbytes = await stream.read_bytes(fmt_size) tornado.iostream.StreamClosedError: Stream is closed The above exception was the direct cause of the following exception: Traceback (most recent call last): File "//env/lib/python3.8/site-packages/distributed/worker.py", line 2367, in gather_dep response = await get_data_from_worker( File "//env/lib/python3.8/site-packages/distributed/worker.py", line 3738, in get_data_from_worker return await retry_operation(_get_data, operation="get_data_from_worker") File "//env/lib/python3.8/site-packages/distributed/utils_comm.py", line 385, in retry_operation return await retry( File "//env/lib/python3.8/site-packages/distributed/utils_comm.py", line 370, in retry return await coro() File "//env/lib/python3.8/site-packages/distributed/worker.py", line 3718, in _get_data response = await send_recv( File "//env/lib/python3.8/site-packages/distributed/core.py", line 651, in send_recv response = await comm.read(deserializers=deserializers) File "//env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 214, in read convert_stream_closed_error(self, e) File "//env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error raise CommClosedError(f"in {obj}: {exc}") from exc distributed.comm.core.CommClosedError: in <TLS (closed) Ephemeral Worker->Worker for gather local=tls://100.64.133.67:34582 remote=tls://100.64.166.148:33595>: Stream is closed`

Having a smaller set of logs is certainly helping to see what is going on.

So seeing comms related issues but unclear is scheduler/workers are MIA, unreliable network (in k8s cluster?), or something. 

Tried a second run with 6 clusters - one failed immediately, No `Comms` errors nor `scheduler connection broken`. Just a lot of failed to find dependencies errors (not warning nor info, errors - looks like it tried a few things).

Really keen to figure this out since 2021.08.0 is definitely improving the actual performance and memory usage in this workflow. 

K8s will be running these Pods in who knows what configuration in the cluster and I'm wondering if I perhaps I'm getting comms congestion - given the `Connection to scheduler Broken` error.

Is there a way to get Dask Distributed to throttle back or increase timeouts/retries on the connections?

The worker and scheduler Pods appear to be up and healthy but I need to monitor them more closely during a future run. Getting late in my time zone so job for a different day.

Please keep suggestions coming. Now I have it repeating on a smaller workload I might be able to figure out a minimal example.

**Comment by woodcockr** [comment]
Hmm, got this error on the jupyter  labs side of things.
Simpler version of the workflow above (trying to simplify my workflow down until it's simple and repeatable).

`Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "//env/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 696, in _handle_events
    self._handle_read()
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 1478, in _handle_read
    self._do_ssl_handshake()
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 1409, in _do_ssl_handshake
    return self.close(exc_info=err)
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 611, in close
    self._signal_closed()
  File "//env/lib/python3.8/site-packages/tornado/iostream.py", line 641, in _signal_closed
    self._ssl_connect_future.exception()
asyncio.exceptions.CancelledError
distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError`

**Comment by fjetter** [comment]
> Is there a way to get Dask Distributed to throttle back or increase timeouts/retries on the connections?

There are TCP connect and keep-alive timeouts https://github.com/dask/distributed/blob/db0b2352bed85306459d17643ba5bb79f7109754/distributed/distributed.yaml#L190-L193

Especially for large deployments, I've frequently heard people increasing the connect timeout to ~60s. If this is too low you may also see messages like `Connection closed before handshake completed`

The tcp timeout itself might also cause broken connects but this is typically enough unless your network is really in an unhealthy state. I would not recommend to increase this to too large values since this is one mechanism of the scheduler to notice dead workers


> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

That actually suggests that something with your deployment is off. I'm not very familiar with dask-gateway but if the TLS configuration is not set up properly, the workers will not be able to connect properly, assuming TLS is enabled.


----

FYI I adjusted the formatting in your comments for better readabiltiy. For tracebacks or longer code sections I recommend enclosing the blocks in triple backticks to start and end a code block

**Comment by woodcockr** [comment]
Thanks for the additional information. 
I've made some changes to the timeouts as suggested.
Dask 2021.07.0 - this now has a lot less noise about timeouts occurring and a large run completed successfully. I will try this several more times to verify.
Dask 2021.08.0 - now deadlocks with teh cluster becoming unresponsive. Eventually something must timeout cause it looks like it resets itself. I've parked this one at the moment in favour of resolving any outstanding issues with 2021.07.0 and the cluster stability.

With Dask 2021.07.0 I did a multi cluster run and monitored the scheduler logs. Periodically I will see:
`Event loop was unresponsive in Scheduler for 3.81s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.`

I'm uncertain how the scheduler operates so am not quite sure where to begin looking for this issue. I've initially checked to make sure variables being passed in to functions running on the cluster are being `scatter`ed to the cluster. Chunk sizes also seem reasonable (at most 100 Megs which seemed to work well previously in 2021.03.0 which was my last version prior to this recent foray). The periodicity appears to relate to the start/end cycle of the work being fed into the clusters (which makes sense I guess).

I do see a burst of network activity for several seconds in the Dashboards System tab. Number of file descriptors shows around 500 or so as well. Not really sure how to interpret this.

Is there a way to get further diagnostics on what the scheduler is dealing with?

Chances are I may well be asking it do something it doesn't like.

**Comment by fjetter** [comment]
If you see the "unresponsive Scheduler" warning during graph/compute submission that likely means that you are submitting a very big graph. I haven't followed our recent development in serialization and can't say much about it other than it _shouldn't_ happen but if it's just during graph submission and the remaining cluster is at rest, this isn't a big deal.

If this warning becomes too noisy, you can adjust the threshold when it is triggered, see (limit)
https://github.com/dask/distributed/blob/281438033f1e00d11ac043fea80758d607f480a8/distributed/distributed.yaml#L243-L245
the cause for this message is a locked [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) which blocks our asyncio event loop, i.e. during these 4seconds the scheduler will not process any other network calls (e.g. they won't get lost, just delayed).

> I've initially checked to make sure variables being passed in to functions running on the cluster are being scattered to the cluster

The serialized graph might still be large due to how the functions are serialized. I believe getting a read on the actual graph size is currently not easy without patching internals. You can, however, see how your functions serialize using `distributed.protocol.pickle`, e.g.  `len(pickle.dumps(my_func, protocol=4))`

Particularly if you have nested functions as part of your graph instead of global functions, this can make a huge difference since for local functions we'll need to serialize by value (i.e. serialize the entire code) whereas global function can be serialized by reference (name of module + name of function). See also https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs

> I do see a burst of network activity for several seconds in the Dashboards System tab. Number of file descriptors shows around 500 or so as well. Not really sure how to interpret this.

Likely your computation graph being submitted. Don't worry about the file descriptors

**Comment by woodcockr** [comment]
Thanks again. This is helping diagnostics greatly and my learning curve.

So at this stage I'm convinced the GIL blocks on the scheduler logs are exactly as you say, just a big graph. That doesn't appear to impact anything and is occurring when the remaining cluster is at rest as you suggested.

The remaining issue appears to be the workers. When the whole system is running full tilt some, not all, workers shows GIL event loop warning then CommClosed. They never recover. The Workers are still visible in the dashboard and still active in that I can login to the Pods and poke around. They are simply idle.
A few of these workers show the GIL timeout sitting around 5 seconds, which also happens to be the worker heartbeat value. So I am wondering if the Scheduler is assuming the worker has died because a heartbeat wasn't sent in a timely manner. There appears to be a scheduler.worker-ttl configuration value so I'm going to try lifting that up and see what happens, after some sleep though its getting late here again.

**Comment by fjetter** [comment]
> So I am wondering if the Scheduler is assuming the worker has died because a heartbeat wasn't sent in a timely manner. There appears to be a scheduler.worker-ttl configuration value so I'm going to try lifting that up and see what happens, after some sleep though its getting late here again.

That config is off by default, iirc. If you are using this I would recommend something in the _minutes_ range. That depends a bit on what you're doing really. The scheduler dashboard shows the last seen values for all workers in the workers tab which might give you a good idea what healthy values should be. Either way, be generous with worker-ttl would be my recommendation

**Comment by woodcockr** [comment]
> That config is off by default, iirc.

That explains why it didn't make much difference ;-)

A lot of things are much happier with extended time outs but I am still getting some random deadlocks and retries on Futures for no apparent reason (logs so far seem silent). The retries will eventually complete the execution but of course repeating execution is extending computational time and it shouldn't really happen this often. There are about 1000 threads running with 8 threads per worker. Not sure if my expectation that I should be able to have this be stable is correct or not.

At the moment I'm trying to determine if the retry/deadlock always occurs at the same point in execution in the workflow. Isn't clear that it is. I also noted that 2021.08.0 has more deadlock fixes in the history so now the other parts are silent I might retry that and see that helps.

**Comment by woodcockr** [comment]
Hmm, so 2021.07.0 latest run provided:
```
distributed.scheduler - WARNING - Worker failed to heartbeat within 60 seconds. Closing: <WorkerState 'tls://100.64.146.210:35683', name: dask-worker-72bea22a1f834f03bfe2dd458f22d4c6-6w4rd, memory: 0, processing: 2192>
---> Worker Pod logs show Comm Error
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Comm closed
```
The worker was still up and looking at the source code Comm closed is printed when there is an OsError exception.
I'm assuming the scheduler heartbeat error is related to the Comm closed
Any pointers on what to investigate for this one?

**Comment by woodcockr** [comment]
I'm going to close this now. Further tweaks to the dask timeouts seem to have resolved most of the issues involved and which manifested differently in each dask version - hence the inference of the problem being related to the version change.
I still have one outstanding issue but once investigated further and characterised better I'll post a new issue.

@fjetter Thank you very much for your assistance. It was most helpful in working this through.
