### ISSUE TITLE
Scheduler plugin warnings

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#5261]
Following https://github.com/dask/distributed/pull/5120 being merged we started seeing several warnings in the test suite regarding our handling of scheduler plugins. For example:

```
 distributed/dashboard/tests/test_scheduler_bokeh.py: 13 warnings
distributed/deploy/tests/test_local.py: 3 warnings
distributed/diagnostics/tests/test_task_stream.py: 2 warnings
  /home/runner/work/distributed/distributed/distributed/scheduler.py:5479: UserWarning: Scheduler already contains a plugin with name task-stream; overwriting.
    warnings.warn(
```
and

```
distributed/dashboard/tests/test_scheduler_bokeh.py: 5 warnings
distributed/diagnostics/tests/test_eventstream.py: 1 warning
distributed/diagnostics/tests/test_progress_stream.py: 1 warning
distributed/diagnostics/tests/test_scheduler_plugin.py: 2 warnings
distributed/http/scheduler/tests/test_scheduler_http.py: 1 warning
  /home/runner/work/distributed/distributed/distributed/scheduler.py:5503: FutureWarning: Removing scheduler plugins by value is deprecated and will be disabled in a future release. Please remove scheduler plugins by name instead.
    warnings.warn(
```

It looks like there are still internal code paths that are removing scheduler plugins by value (instead of by name) and we're repeatedly adding some of our built-in scheduler plugins

cc @douglasdavis @mrocklin

**Comment by jrbourbeau** [comment]
Whoops, @douglasdavis beat me to it in https://github.com/dask/distributed/pull/5260 : ) Would you mind opening up another PR for the the `add_plugin` cases?

**Comment by douglasdavis** [comment]
Ah yes, missed the adding case. Will take a look

**Comment by mrocklin** [comment]
Thank you both for handling this.  I apologize for missing it before.  I
appreciate you both being thorough here.

**Comment by jrbourbeau** [comment]
No worries! https://github.com/dask/distributed/pull/5179 will help us automatically catch these things in the future
