### ISSUE TITLE
consider truncating huge strings in logging error when deserialization fails

### ISSUE THREAD

**Issue by timodonnell** [dask/distributed#528]
I was getting enormous errors due to this line, which made it difficult to debug. May want to truncate the string logged here if it is huge:

https://github.com/dask/distributed/blob/master/distributed/core.py#L76

**Comment by mrocklin** [comment]
Thanks for the bug report.  Please see https://github.com/dask/distributed/pull/529

**Comment by timodonnell** [comment]
Woah that was fast. Thanks!
