### ISSUE TITLE
Remove stale versions on readthedocs?

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#5282]
As reported by @jbusecke over in https://github.com/dask/distributed/issues/5279, our docs have a few specific, but old, versions of our documentation. We should consider either including specific versions of our docs as part of our release procedure, or removing these older versions from RTD as they can be confusing to users. 

cc @jacobtomlinson @jsignell who have been thinking about docs recently 

> I actually looked at the version of the docs before and was pretty confused that it seems RTD uses a different versioning scheme?

![image](https://user-images.githubusercontent.com/14314623/131160359-edfddac9-ac7a-48bd-bd04-7dfcbdf78dfb.png)

**Comment by jsignell** [comment]
Do we know how these used to be produced? I think we can safely delete the stale versions, but maybe we want to think about including the docs builds of specific blessed versions.

**Comment by jrbourbeau** [comment]
This appears to be a setting in readthedocs. I've gone ahead and deleted the older versions. I'm going to close this issue, but we can keep thinking about if we want to host docs for previous releases
