### ISSUE TITLE
Give dask scheduler publicly accessible IP

### ISSUE THREAD

**Issue by genderev** [dask/distributed#5296]
Hi! I tried to use Docker, Docker Compose and Helm to deploy Dask on Okteto and on Azure.

In these deployments, I could never find out what the scheduler's IP address was, even after using kubectl to list all services. I want to host the scheduler in the cloud and connect to it from anywhere.

**Comment by fjetter** [comment]
You can provide a specific scheduler IP address via the CLI https://github.com/dask/distributed/blob/5bf60e3b59d2e8d622c56587fb86e20a4ea0f25c/distributed/cli/dask_scheduler.py#L27-L28

e.g.

`dask-scheduler --host 1.2.3.4 --port 5678`

providing a valid IP / port which is publicly accessible is something you'll likely need to figure out with okteto/azure

If you do not provide one yourself, dask will pick a valid IP and a free port and will log the result, e.g.

```
 ~ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://192.168.0.74:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
```

**Comment by jacobtomlinson** [comment]
You can also set the host to `0.0.0.0` which means Dask will listen to traffic coming in from anywhere. Then you need to ensure the scheduler container has some routable IP on Okteto and Azure. 

You mention Docker, Docker Compose and Helm as three different methods you've tried to deploy Dask. If you want to pursue one of those in particular then feel free to open an issue on the specific project with more information about how you are deploying Dask and we can help you there.
