### ISSUE TITLE
experiences running large numbers of workers

### ISSUE THREAD

**Issue by timodonnell** [dask/distributed#531]
Thought I'd put this out here in case any of it is helpful. It's just some quick notes on my recent experiences not a real bug report, so feel free to close. I'm curious how this compares to others' experiences and if other people have been able to get >200 distributed workers to work well.

I've been experimenting with using the dask distributed joblib backend to parallelize hyperparameter selection for neural networks. I'm running on google container engine with kubernetes.

My setup for running dask distributed on kubernetes is here: https://github.com/hammerlab/dask-distributed-on-kubernetes

The neural network project is here: https://github.com/hammerlab/mhcflurry/tree/refactor1 . The training script is [here](https://github.com/hammerlab/mhcflurry/blob/refactor1/mhcflurry/class1_allele_specific/cv_and_train_command.py) and it gets invoked as described [here](https://github.com/hammerlab/mhcflurry/blob/refactor1/downloads-generation/models_class1_allele_specific_single)

I'm using the latest distributed from PyPI (1.13.2).

I am able to scale up to about 100-200 workers, and have successfully trained models with this setup. 

However, with larger worker counts, things seem to break down. I wrote a simple [benchmark](https://github.com/hammerlab/dask-distributed-on-kubernetes/blob/master/benchmarking/benchmark.py) that runs a bunch of tasks that sleep for a given amount of time and optionally send/receive/allocate data.

It appears scheduler overhead (or something else) kicks in past 200 workers and we actually see longer overall runtimes with more workers:

![image](https://cloud.githubusercontent.com/assets/467896/18565683/ba5ac14e-7b5e-11e6-9e1e-28c53eb7cb03.png)

![image](https://cloud.githubusercontent.com/assets/467896/18565690/c22f83fa-7b5e-11e6-8f06-0d722eab43e2.png)

![image](https://cloud.githubusercontent.com/assets/467896/18565696/c863a0bc-7b5e-11e6-9cb2-11e21ff352c5.png)

![image](https://cloud.githubusercontent.com/assets/467896/18565711/d88cca18-7b5e-11e6-9330-ff45819ba101.png)

On the model training task, I unfortunately I don't have a single consistent error to report but I can work on putting something together as I get more experience with this setup. Here are some errors I've seen in case any of this is helpful to you in the mean time.

I get a large number of messages like this on the scheduler:

```
[tim@Tims-MacBook ~/sinai/git/mhcflurry-cloud/kubernetes]$ kubectl logs daskd-scheduler-156108278-sjf5o
distributed.scheduler - INFO - Expected data missing from worker: 10.0.9.14:47117, {'<joblib.parallel.BatchedCalls object at 0x117b8ceb8>-67a7d467-385d-48c9-9040-8fa18fcf3181'}
distributed.scheduler - INFO - Excess keys found on workers: {'10.0.9.14:47117': {'missing': ['<joblib.parallel.BatchedCalls object at 0x117b8ceb8>-67a7d467-385d-48c9-9040-8fa18fcf3181'], 'extra': []}}
distributed.scheduler - INFO - Expected data missing from worker: 10.0.5.12:42788, {'<joblib.parallel.BatchedCalls object at 0x118175b00>-eea9ca08-2c6b-42b9-8bfa-ec2b276acc6c'}
distributed.scheduler - INFO - Excess keys found on workers: {'10.0.5.12:42788': {'missing': ['<joblib.parallel.BatchedCalls object at 0x118175b00>-eea9ca08-2c6b-42b9-8bfa-ec2b276acc6c'], 'extra': []}}
distributed.scheduler - INFO - Remove client 259f19f0-7559-11e6-8111-a45e60c9182b
distributed.scheduler - INFO - Close client connection: 259f19f0-7559-11e6-8111-a45e60c9182b
distributed.core - INFO - Lost connection: ('10.142.0.59', 52273)
distributed.core - INFO - Close connection from 10.142.0.59:52273 to Scheduler
distributed.scheduler - INFO - Excess keys found on workers: {'10.0.3.19:33749': {'missing': [], 'extra': ['<joblib.parallel.BatchedCalls object at 0x1180e8550>-e8e8d0a1-9023-4b13-a85d-612ae0525d32']}}
distributed.scheduler - INFO - Excess keys found on workers: {'10.0.8.10:40404': {'missing': [], 'extra': ['<joblib.parallel.BatchedCalls object at 0x117d9a0f0>-e8c01973-77d5-42bc-be87-5a388e99db19']}}
```

with 700 workers, I see lots of these on workers:

```
distributed.core - INFO - Lost connection: ('10.12.1.5', 37454)
distributed.core - INFO - Close connection from 10.12.1.5:37454 to Worker
```

and on scheduler:

```
distributed.core - INFO - Collecting unused streams.  open: 512, active: 375
```

I also see this on the client (i.e. the process submitting tasks to the scheduler), however it is possibly just due to running out of memory:

```
SystemError: <built-in method pack of pandas.msgpack._packer.Packer object at 0x7f6c980a12f0> returned NULL without setting an error
ERROR:distributed.batched:<built-in method pack of pandas.msgpack._packer.Packer object at 0x7f6c980a12f0> returned NULL without setting an error
Traceback (most recent call last):
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/distributed/batched.py", line 58, in send_next
    yield self.last_send
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/distributed/core.py", line 269, in write
    frames = protocol.dumps(msg)
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/distributed/protocol.py", line 116, in dumps
    small_header, small_payload = dumps_msgpack(msg)
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/distributed/protocol.py", line 223, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/hpc/users/odonnt02/anaconda/envs/py35/lib/python3.5/site-packages/pandas/msgpack/__init__.py", line 44, in packb
    return Packer(**kwargs).pack(o)
SystemError: <built-in method pack of pandas.msgpack._packer.Packer object at 0x7f6c980a12f0> returned NULL without setting an error
```

**Comment by mrocklin** [comment]
Hi @timodonnell ,

First, thank you for the excellent writeup.  Reports from the wild like these are very valuable. 

Second, this report is timely.  You might find that https://github.com/dask/distributed/pull/526 strongly impacts your results.

**Comment by mrocklin** [comment]
Some comments/questions:

1.  Can you explain more about what the "32 threads per worker scaling" plot shows?  What is the x-axis precisely?
2.  You can probably ignore the Excess keys bit.  I don't think this will strongly affect you.
3.  The msgpack error is concerning.  
4.  Note that when using Joblib *all* of the results stream back to the client.  This is somewhat inefficient. I would be interested in seeing performance if you took joblib out of the picture.

I recently ran a benchmark just on my laptop with 800 workers and noticed that the scheduler was burning something like 80% CPU when the cluster was just at idle.  Do you experience this as well?  Or more precisely "can you characterize the scheduler CPU and memory load".  There are probably a few simple things we can do here, like reduce heartbeat times and whatnot.

**Comment by timodonnell** [comment]
Thanks for the info!

For # 1: The 32 threads per worker benchmark is running each worker with `--nthreads 32`. The xaxis shows the *total* number of threads, i.e. 32 times the number of workers

For # 4: my program is written so the data sent back from the workers should be small (< 100 mb total). Does that obviate the issue you have in mind or is there still something joblib is doing that is inefficient in this case? Interested in this since i'm currently running out of memory on my client (i.e. the process submitting jobs to the scheduler via joblib), and I'm not sure why.

I actually haven't looked much at the scheduler resource usage. All I can say is it hasn't crashed for me on a 32 core and 120 GB of memory machine handling up to ~700 workers.

**Comment by mrocklin** [comment]
Joblib is still sending lots of small messages and, I think, waiting on them before sending out more tasks.  I suspect it would be more efficient to send all of the information to the scheduler up front.  

The scheduler is single-threaded, so while it may not crash it also might be holding things up, even if run on a beefy machine.  

I've also merged the connection limit PR

**Comment by timodonnell** [comment]
@mrocklin and I talked on Friday and found an issue involving the interaction of dask and joblib when the number of workers changes (as it does in my benchmarks). Joblib does not get updated on the current number of workers, so it tries to schedule the wrong number of tasks at once. For example, if we initially have 10 workers and then raise it to 100, joblib still tries to schedule 10 tasks at a time.

Once that issue was fixed by switching to plain dask distributed instead of the joblib backend in my [benchmark script](https://github.com/hammerlab/dask-distributed-on-kubernetes/blob/master/benchmarking/benchmark.py), we saw good scaling for small numbers of workers:

![image](https://cloud.githubusercontent.com/assets/467896/18647073/57a716ac-7e82-11e6-9be7-625d260d902b.png)

I've tried increasing the number of workers beyond this, but I seem to hit some a mix of deadlock and connection issues after not too many iterations. For example, here is the beginning of a run that was attempting to go up to 800 workers:

![image](https://cloud.githubusercontent.com/assets/467896/18647129/87cb09c4-7e82-11e6-9d62-1b4370ad8be7.png)

At workers=400, it hung for 20 minutes before I killed it. I put up the scheduler logs [here](https://www.dropbox.com/s/1n8syo4nxlgyq27/scheduler.log?dl=0) in case they are useful.

So, while we're still hitting issues with hundreds of nodes, it's good to see that scaling to smaller-sized clusters works well. Thanks for the help @mrocklin . For anyone trying to do similar things, I cleaned up my kubernetes config into more of an example, see [here](https://github.com/hammerlab/dask-distributed-on-kubernetes
).

**Comment by mrocklin** [comment]
Did you happen to get a look at the `scheduler:8787/tasks` view to see if tasks were being well scheduled over time?

**Comment by timodonnell** [comment]
Ah no I didn't check that, unfortunately

**Comment by mrocklin** [comment]
Thanks for the feedback.  Closing.
