### ISSUE TITLE
Should `Worker.data_needed` be priority-ordered?

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#5323]
`Worker.data_needed` is a list of tasks that need data to be fetched. Currently it's just FIFO by task submission time. So in theory, if a higher-priority task gets submitted after a lower-priority one, the low-priority one will get its data fetched first, and therefore probably run first.

I'm not sure in reality if this is much of an issue. We tend to see the biggest priority-vs-FIFO-ordering issues with root tasks; since they don't have dependencies, they're not relevant here. But it does just feel odd. The question is how often tasks with dependencies get submitted to workers out of priority order.

Switching this to a priority heap would be pretty easy and probably pretty cheap. There's even a TODO for it:
https://github.com/dask/distributed/blob/3f86e58f729c315905d51acedd9229a1db240cf4/distributed/worker.py#L437

**Comment by fjetter** [comment]
This is implemented in https://github.com/dask/distributed/pull/5046
