### ISSUE TITLE
Python 3.9 CI broken: fsspec and s3fs git tips are incompatible

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5345]
``mamba env create`` on all Python 3.9 CI builds has started failing with this message:
``` 
 The conflict is caused by:
      The user requested fsspec 2021.9.0 (from git+https://github.com/intake/filesystem_spec)
      dask 2021.9.1+5.g9460bc4e depends on fsspec>=0.6.0
      s3fs 2021.8.1+9.g1b39cf3 depends on fsspec==2021.08.1
```
This is because in environment-3.9.yaml we have:
```yaml
  - pip:
      - git+https://github.com/dask/s3fs
      - git+https://github.com/intake/filesystem_spec
```

**Comment by jrbourbeau** [comment]
cc @martindurant for visibility. I know there have been recent discussions around `s3fs` dependencies, but IIRC this was mostly around `aiobotocore`. @martindurant does the `fsspec==2021.08.1` need to be bumped to `fsspec==2021.09.0` or `fsspec>=2021.08.1`? Any suggestions on how we should go about consistently testing the `main` branch of `s3fs` + `fsspec`?

**Comment by martindurant** [comment]
If we only have s3fs in there, it should pull the version of fsspec that works, right? 
This happens in the time between pushing an fsspec release and then s3fs. I usually wait for conda-forge to finish with the first before starting the second, but I guess I could push the tag and pypi packages eagerly.

**Comment by martindurant** [comment]
https://github.com/dask/s3fs/pull/535

**Comment by jrbourbeau** [comment]
> If we only have s3fs in there, it should pull the version of fsspec that works, right?

Yep, that's correct, and this is what we do in the Python 3.7 + 3.8 CI builds. In the past we've had issues pop up when new releases of `s3fs` and `fsspec` were published, so in the Python 3.9 CI build we've been installing the development versions of `s3fs` and `fsspec` to catch things before they make it into a release.

**Comment by martindurant** [comment]
OK, so I'll tag early in the future (but still wait on conda-forge)

**Comment by martindurant** [comment]
Everything got released
