### ISSUE TITLE
add pre-commit to dask-distributed env

### ISSUE THREAD

**Issue by raybellwaves** [dask/distributed#5351]
Following https://distributed.readthedocs.io/en/latest/develop.html#linting `pre-commit run --all-files` requires pre-commit to be in the environment. It could be added to here https://github.com/dask/distributed/blob/main/continuous_integration/environment-3.9.yaml

**Comment by jrbourbeau** [comment]
Thanks for the suggestion @raybellwaves -- adding `pre-commit` to the environment files in `distributed/continuous_integration` seems reasonable. Interested in submitting a PR?
