### ISSUE TITLE
`dworker` does not work on Windows 7

### ISSUE THREAD

**Issue by eriknw** [dask/distributed#54]
`dworker` does not work on Windows 7 using Python 2.7 (no other versions tested).

The process created by the nanny using `multiprocessing.Process` fails to execute due to an issue with how multiprocess handles forking in Windows.  The error message is `"ImportError: No module named dworker"`.  I don't know the best way to address this.  A workaround is to copy "dworker" to a filename that ends in ".py"--let's say "run_dworker.py"--and then run "python run_dworker.py".

Also, the `dworker` process just hung.

**Comment by eriknw** [comment]
I think I may have found a solution.  Simply change the name of "dcenter" to "dcenter.py" and update the name in the scripts field of setup.py.  In Windows, this installs both "dcenter" and "dcenter.py" into the scripts bin directory and the `dcenter` command works as expected.

**Comment by mrocklin** [comment]
Hrm, we could presumably handle this logic within `setup.py`.  Do other projects have this issue?

**Comment by mrocklin** [comment]
I believe that this is now resolved in master.  Closing.  Please re-raise if the issue persists.
