### ISSUE TITLE
Dependendy asyncssh not installed, when installing distributed

### ISSUE THREAD

**Issue by JulianWgs** [dask/distributed#5424]
**What happened**:
asyncssh was not installed, but is used by distributed.

**What you expected to happen**:
asyncssh is installed, when installing distributed. May be through an ssh flag?

**Minimal Complete Verifiable Example**:

Freshly install:
```bash
pip install distributed
```

Import ssh cluster:
```python
from distributed import SSHCluster
```

```python-traceback
distributed\deploy\ssh.py in start(self)
    165 
    166     async def start(self):
--> 167         import asyncssh  # import now to avoid adding to module startup time
    168 
    169         logger.debug("Created Scheduler Connection")

ModuleNotFoundError: No module named 'asyncssh'
```

**Anything else we need to know?**:
No :)

**Environment**:

- Distributed version: 2021.09.1
- Python version: 3.7.7
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for reporting @JulianWgs. `distributed` has several possible optional dependencies, depending on what functionality one wants to use. In these cases when an optional dependency isn't installed, we tend to raise an informative error message. For example:

https://github.com/dask/distributed/blob/7a3ea4c34ae0af6af1137fe3e3bda927aa9eac26/distributed/security.py#L106-L109

We should do something similar for `SSHCluster`s use of `asyncssh`. Additionally, while the `SSHCluster` docstring mentions `asyncssh`, it doesn't state that `asyncssh` is required to be able to use `SSHCluster` -- we should update the docstring to indicate this. 

Is this something you're interested in contributing? (no obligation though)
