### ISSUE TITLE
Automatic cluster state export upon test timeout

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5437]
We are frequently bothered by unit tests timing out. Most of the timeout are not easily reproducible and are hard to debug. In the past, these timeouts could often be linked to a known issue, deadlocking the cluster. Often this deadlock can be investigated by inspecting the cluster state.

For a manual extraction of the cluster state, I once wrote https://github.com/dask/distributed/issues/5068 which is trying to create a clean, serializable representation of the cluster.

Upon test timeout, this cluster dump could be persisted and archived as an artifact of the GH actions runner.

For instance, if `gen_cluster` fixture is used with a client, a timeout exception could be handled and the state is persisted, see https://github.com/dask/distributed/blob/6a0217e4d7ac442f9c9be018baab37ae3ec90cb9/distributed/utils_test.py#L954-L964

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/5470
