### ISSUE TITLE
Bokeh dashboard doesn't update when new workers are added to the pool

### ISSUE THREAD

**Issue by jni** [dask/distributed#545]
I recently wanted to demo distributed's ability to dynamically add or remove workers from the pool. 

I launched a scheduler with:

```
dask-scheduler --host 127.0.0.1
```

and a worker with

```
dask-worker 127.0.0.1:8786 --nprocs 1 --nthreads 1
```

Then I opened the bokeh dashboard, performed some dask computations, and finally started a new worker with the same command. Although it appeared to connect to the scheduler without any issues, refreshing the dashboard didn't show the new worker.

Is this expected behavior?

**Comment by mrocklin** [comment]
Seems unexpected to me.  I've also experienced a lack of responsiveness in
the /workers page.

**Comment by mrocklin** [comment]
This is now, I believe, resolved.
