### ISSUE TITLE
Persisting custom dask task graphs

### ISSUE THREAD

**Issue by lintusj1** [dask/distributed#546]
Correct me if I'm wrong, but currently it seems that there is no easy way to persist a custom task graph with distributed. The persist method requires a collection object and the distributed.get doesn't seem to support async calling. I would like to get futures for certain tasks from a custom dask graph. What would be the best way?

**Comment by mrocklin** [comment]
You're correct that `get` doesn't support persistence.  Generally for custom graphs people use [dask.delayed](http://dask.pydata.org/en/latest/delayed.html), which are like one-key collections.  You could create delayed objects from a set of keys as follows:

```python
values = [Delayed(key, [dsk]) for key in keys]
values = client.persist(*values)
```

**Comment by lintusj1** [comment]
Thanks for the response, that works!
