### ISSUE TITLE
numpydoc eats whitespaces on parameters spec

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5478]
In client.py:

```python
    def scatter(...):
    """
    ...

        Parameters
        ----------
        data : list, dict, or object
            Data to scatter out to workers.  Output type matches input type.
        workers : list of tuples (optional)
    """
```

in the rendered HTML, the separation between parameter name and type is gone:
https://distributed.dask.org/en/latest/api.html?highlight=scatter#distributed.Client.scatter

![Screenshot from 2021-10-29 11-16-47](https://user-images.githubusercontent.com/6213168/139418346-3772c1e6-2ee1-4b2f-9b48-792c1f685aae.png)

**Comment by jrbourbeau** [comment]
Closing as this was resolved by the `dask-sphinx-theme==2.0.1` release (see, for example, http://distributed.dask.org/en/latest/api.html#distributed.Client.scatter)
