### ISSUE TITLE
Unable to connect to Center in Linux from Client on Windows

### ISSUE THREAD

**Issue by eriknw** [dask/distributed#55]
Using the current master branch (December 16, 2015), I cannot run a Center on Linux and connect to it from Windows.  Creating an Executor on Windows raises `ImportError: cannot import name _psutil_linux` during `loads` called from `read` in core.py.

**Comment by mrocklin** [comment]
OK, good to know that this problem persists after 6af0272e3bcedf687693ff4e937e3b25fabb0784 .  I'll be more able to diagnose this next week when I have easier access to my Windows VM.

**Comment by hussainsultan** [comment]
i also get the same error when center process runs in a linux docker container and connecting it from OSX.

```python
In [1]: import distributed

In [2]: distributed.__version__
Out[5]: '1.6.1'
In [3]: from distributed import Executor

In [4]: a = Executor('192.168.99.100:33001')

In [5]: distributed.core - ERROR - cannot import name _psutil_linux
Traceback (most recent call last):
  File "/Users/rkj837/anaconda/lib/python2.7/site-packages/distributed/core.py", line 34, in loads
    return cloudpickle.loads(x)
  File "/Users/rkj837/anaconda/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/Users/rkj837/anaconda/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/Users/rkj837/anaconda/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/Users/rkj837/anaconda/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
  File "/Users/rkj837/anaconda/lib/python2.7/site-packages/psutil/_pslinux.py", line 23, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name _psutil_linux
```

**Comment by mrocklin** [comment]
OK.  Bumping this up a bit in my priority queue.

**Comment by mrocklin** [comment]
OK, I was trying this out locally.  I am able to do the following on master

1.  Set up a `Scheduler` on linux (schedulers are now replacing centers)
2.  Set up a worker both on linux, and on windows, both pointing to the same scheduler
3.  Set up an Executor, both on linux, and on windows, also pointing to the same scheduler
4.  Run tasks from either client on either worker successfully 

However, I'm not at all confident that this issue is resolved.  I'll keep playing around a bit.

**Comment by hussainsultan** [comment]
i did a quick test with ubuntu docker container and was able to connect to the scheduler from OSX.

**Comment by mrocklin** [comment]
There have been a number of significant changes in the last few days; I'm not sure exactly what the difference is though.

@eriknw if you find yourself with a free moment can you verify your original setup?

**Comment by mrocklin** [comment]
Ping @eriknw

**Comment by mrocklin** [comment]
Closing this for now.  Please reopen if problem persists.
