### ISSUE TITLE
`as_completed.batches()` doesn't yield all ready results for large amount of tasks. 

### ISSUE THREAD

**Issue by gerrymanoim** [dask/distributed#5508]
Not sure if this is a bug report or me not understanding how this works. 

I have code that looks like:

```python
futures = client.compute(...)
for batch in as_completed(futures).batches():
    for future in batch:
         if future.status == "error":
            # do something
         else:
            # do something else
        future.release()
```

The goal is to record the completion of a future and then tell the cluster to forget about it as soon as possible. `fire_and_forget` might be more suited to this, but I do explicitly want to track which futures ended up failing. 

My naïve expectation is that `batch` should be any future that's ready (i.e. in-memory) at each iteration of the loop. 

However, with larger amounts of futures (>100k), I find that I'm still holding on to a significant amount of results (thousands) in memory (based on the progress bar in the dashboard). 

- Dask version: 2021.10.0
- Python version: 3.9 
- Operating System: Linux
- Install method (conda, pip, source): Source

**Comment by fjetter** [comment]
Thank you for the report. Is this something you can reproduce and reduce to a minimal example? See https://blog.dask.org/2018/02/28/minimal-bug-reports

Without a more minimal reducer it is quite difficult to find out what's going on.

For debugging purposes you can try to inspect the scheduler state yourself, e.g.

```python
def task_by_state(dask_scheduler):
    import defaultdict
    res = defaultdict(int)
    for ts in dask_scheduler.tasks.values():
        res[ts.state] += 1
    return dict(res)
client.run_on_scheduler(task_by_state)
```

with this snippet we can at least confirm if there is something with the dashboard or the scheduler. I doubt that this is connected to the `as_completed` call but I cannot say for sure without a reproducer.

**Comment by gerrymanoim** [comment]
Got it - let me put something together if this is actually unexpected behavior.

From the perspective of dask these tasks are equivalent to 

```python
import time
import random 
import itertools 

@dask.delayed
def do_something(base: int) -> str:
    # this mocks an operation that does some processing and writes some data
    n = base + random.randint(-30, 30)
    time.sleep(n)
    return f"Slept for {n} seconds"

tasks = [do_stuff(n) for n in itertools.repeat(60, 130_000)]

futures = client.compute(tasks)
for batch in as_completed(futures).batches():
   ... 
```

Will come back with a real reproduction here, thanks!

**Comment by gerrymanoim** [comment]
I figured out what my issue was. My code actually looked like:

```python
futures = client.compute(...)
for batch in as_completed(futures).batches():
    for future in batch:
         if future.status == "error":
            # do something
         else:
            some_dict['some_key'] = future.result()
        future.release()
```

As we pickup up more and more futures, calling `future.result()` in a loop got slower and slower, causing the next batch picked up to be larger, compounding the problem the next round.
