### ISSUE TITLE
Distributed pandas apply

### ISSUE THREAD

**Issue by nathanscully** [dask/distributed#552]
I am trying to run a fuzzy search of text on a large dataset against ~0.5 million strings, getting the top result then appending the result to the original frame.

```
def compareStrings(input, choices):
    ... #get closet match from 0.5million strings
   return pd.Series((top_result, input), index=['match', 'original'])

client = Client('127.0.0.1:8786')
num_partitions = len(client.ncores().keys())
data = dd.from_pandas(data, npartitions=num_partitions)
data = client.persist(data)

fuzzies = data.apply(lambda r: compareStrings(r, choices), axis=1).compute()
ret = pd.merge(data, fuzzies ...)
```

I have tried to get the custom function as fast as I can, but it's applying it in batch efficiently that is a problem.

I have set a few worker servers up and these connect to the scheduler and the client.ncores() is correct for the partitions. 

However, when the task runs, it maxes out one core on one worker, e.g. 4 core server I ended up with 25% CPU and the other servers don't have any activity.

Am I doing this wrong or is it not possible to use a custom function with apply in this way?

**Comment by mrocklin** [comment]
Your fuzzy string matching function is likely Pure Python, and so likely holds the GIL.  You'll want to use multiple processes rather than multiple threads.  This can be done by using the single-machine multiprocessing scheduler

    dask.set_options(get=dask.multiprocessing.get)

or my using the distributed scheduler as you are now, but starting your workers with multiple processes rather than threads

    dask-worker address:port --nprocs 4 --nthreads 1

**Comment by mrocklin** [comment]
See http://dask.readthedocs.io/en/latest/scheduler-choice.html

**Comment by nathanscully** [comment]
Thank you, I missed the `--nprocs 4` setting. All working now.

In terms of partitions, should this reflect the number of processes. So if I was using 4x c4.xlarge, which I believe have 4 cores, then I should have 16 partitions?

**Comment by mrocklin** [comment]
You probably want at least as many partitions as processes.  I recommend playing around a little and seeing if you experience performance differences.
