### ISSUE TITLE
can not reproduce Web Interface example

### ISSUE THREAD

**Issue by hainm** [dask/distributed#556]
hi

I am trying to follow https://distributed.readthedocs.io/en/latest/web.html but I can not see anything (animation) happens if going to: http://172.17.55.43:8787/status/

![bokeh_application_-_2016-09-28_13 53 05](https://cloud.githubusercontent.com/assets/4451957/18925749/29d4eb7a-8583-11e6-98e3-bc5d4fc349b9.png)

First, I started `dask-scheduler` in one terminal
Then run code in "Example Computation" section in another terminal.

I am using the most updated distributed version (master branch) (https://github.com/dask/distributed/issues/555), firefox 45.0.2 (Linux).

**Comment by mrocklin** [comment]
This is consistent with not having any workers.  You probably need to run `dask-worker 172.17.55.43:8786` somewhere.  See http://distributed.readthedocs.io/en/latest/setup.html for more information.

Closing this for now.  Please reopen if the problem persists.
