### ISSUE TITLE
Work Stealing fails for heterogeneous victim/thief resources

### ISSUE THREAD

**Issue by xuevin** [dask/distributed#5565]
Work stealing has a small bug where `_can_steal` checks on the victim's resources, and not the task's resource restrictions.

This can lead to a case where a thief cannot steal task from a victim where the resource_restrictions are a superset of the thief's. 

ie. if the task has restrictions
Task
`CPU=1, MEMORY=4`

Victim
`CPU=1, MEMORY=4, GPU=1`

Thief
`CPU=1, MEMORY=4`

The thief cannot steal from the victim. Any easy patch is found below to change 

https://github.com/dask/distributed/blob/8d93d8aac339ac858c2cd8461765692ab5f322c8/distributed/stealing.py#L509

```
for resource, value in ts.resource_restrictions.items():
```

**Comment by fjetter** [comment]
Thanks for the report and already isolating the problem. I opened #5573 with a test for this behaviour

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/5573
