### ISSUE TITLE
Flaky test_acquire_replicas_already_in_flight

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5605]
The new ``test test_acquire_replicas_already_in_flight``, which I introduced in #5566, is flaky.
It occasionally complains that there are 3 events instead of the expected 5, but the failure message is lacking enough info to fix the issue.

#5598 should shed more light on this. Please report here an error log downstream of this PR.

**Comment by fjetter** [comment]
Test reports don't see this failing anymore. Closing
