### ISSUE TITLE
Failing TLS test on python 3.7

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#5607]
A previously working TLS + tornado comms test started failing on Python 3.7 only. Copying error here:

```
____________________ test_tls_comm_closed_explicit[tornado] ____________________

tcp = <module 'distributed.comm.tcp' from '/home/runner/work/distributed/distributed/distributed/comm/tcp.py'>

    @pytest.mark.asyncio
    async def test_tls_comm_closed_explicit(tcp):
>       await check_comm_closed_explicit("tls://127.0.0.1", **tls_kwargs)

distributed/comm/tests/test_comms.py:774: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
distributed/comm/tests/test_comms.py:753: in check_comm_closed_explicit
    await b_read
distributed/comm/tcp.py:205: in read
    frames_nbytes = await stream.read_bytes(fmt_size)
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/iostream.py:441: in read_bytes
    self._try_inline_read()
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/iostream.py:913: in _try_inline_read
    pos = self._read_to_buffer_loop()
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/iostream.py:815: in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/iostream.py:945: in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/iostream.py:1690: in read_from_fd
    return self.socket.recv_into(buf)
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/ssl.py:1071: in recv_into
    return self.read(nbytes, buffer)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
len = 65536
buffer = bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x...0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')

    def read(self, len=1024, buffer=None):
        """Read up to LEN bytes and return them.
        Return zero-length string on EOF."""
    
        self._checkClosed()
        if self._sslobj is None:
            raise ValueError("Read on closed or unwrapped SSL socket.")
        try:
            if buffer is not None:
>               return self._sslobj.read(len, buffer)
E               ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2570)

/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/ssl.py:929: SSLError
```

Raising this to track the issue.

**Comment by jcrist** [comment]
I don't believe code related to this has changed recently.

One difference is that in the failing builds openssl 3.0.0 is installed, when a few days ago openssl 1.1.1l was installed.

Failing: https://github.com/dask/distributed/runs/4535979634?check_suite_focus=true

```
  - openssl=3.0.0=h7f98852_2
  - python=3.7.12=hf930737_100_cpython
```

Succeeded: https://github.com/dask/distributed/runs/4513723121?check_suite_focus=true

```
  - openssl=1.1.1l=h7f98852_0
  - python=3.7.12=hb7a2778_100_cpython
```

Not sure if this is a change in mamba or in the build requirements for some other package (the cpython versions are the same between these two test runs, but note that the build artifacts are different - not sure what else depends on openssl).

cc @jakirkham for thoughts.

**Comment by jrbourbeau** [comment]
Thanks @jcrist, I recall us run into this issue, or a similar looking issue, before (xref https://github.com/dask/distributed/issues/3588). From what I can tell it looks like there was an openssl change that broke Python (https://bugs.python.org/issue40018). The change was then reverted in `openssl`, but only for `openssl=1.1.1` (https://github.com/openssl/openssl/pull/11400). For `openssl=3*` there have been several fixes on the Python side (https://bugs.python.org/issue38820), but it doesn't look like they're being backported to Python 3.7 (or Python 3.8 for that matter). 

I'm with you that it's not clear why we started pulling in `openssl=3` in CI

**Comment by crusaderky** [comment]
Is the issue with Python 3.7 or with Tornado 5?

**Comment by jakirkham** [comment]
Yeah I suspect this is issue ( https://github.com/openssl/openssl/issues/11378 ), which is referenced in the thread James linked. In OpenSSL 1.1.1e, this behavior was introduced, but in 1.1.1f it was reverted. IIUC the behavior was kept in 3.0.0

**Comment by jcrist** [comment]
> Yeah I suspect this is issue ( openssl/openssl#11378 ), which is referenced in the thread James linked. In OpenSSL 1.1.1e, this behavior was introduced, but in 1.1.1f it was reverted. IIUC the behavior was kept in 3.0.0

Sure, that's likely the issue. But since no code has changed in python or openssl to lead to this (these versions are all old), I'm more interested in what changed in the conda package metadata that led us to pull in a different version of openssl all of a sudden.

> Is the issue with Python 3.7 or with Tornado 5?

The asyncio comms properly handles this issue, so it's likely tornado not properly handling the potential variation in failure modes here.

---

Since we should drop python 3.7 soon-ish (per NEP-29), I'm just going to push up a patch that xfails this test for python 3.7.

**Comment by jakirkham** [comment]
I'm not sure

xfailing sounds reasonable
