### ISSUE TITLE
Bokeh 3.0 interface changes break performance_report

### ISSUE THREAD

**Issue by garryod** [dask/distributed#5614]
**What happened**:

When `distributed` installed via pip `bokeh` `3.0.0dev2` is installed as a dependency. As of version `3`, the `render_mode` argument of `bokeh.models.annotations.LabelSet` has been removed, resulting in an error whilst producing the report. Bokeh [recommends](https://github.com/bokeh/bokeh/blob/b30d44b6759cf41236b6a5b90ab1531608a8dcb4/sphinx/source/docs/releases/3.0.0.rst#render_mode) replacing `LabelSet` with `HTMLLabelSet` where `render_mode="css"` was previously used.

For now I have pinned boken to `2.4.2` as a workaround.

**What you expected to happen**:

The code within the `performance_report` is executed, after which a report is produced.

**Minimal Complete Verifiable Example**:

```python
from distributed import Client, performance_report
client = Client() 

with performance_report():
    pass
```

**Anything else we need to know?**:

Happy to submit a PR to replace the instances of `LabelSet` [here](https://github.com/dask/distributed/blob/fa326d5b2c41b0bfe190559c676c0d57d42362ce/distributed/dashboard/components/shared.py#L445) & [here](https://github.com/dask/distributed/blob/fa326d5b2c41b0bfe190559c676c0d57d42362ce/distributed/dashboard/components/shared.py#L468) if that's the route to be taken.

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.9.6
- Operating System: Red Hat Enterprise Linux release 8.5 (Ootpa)
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
A PR would definitely be welcome, but I'm also interested in how exactly you ended up with `bokeh 3.0.0dev2` installed. That feels like something that you should have to specifically try to get rather than coming by default. I tried to reproduce your install process:

```bash
conda create -n dask-pip python=3.9
conda activate dask-pip
pip install distributed  # does not install bokeh
pip install dask[complete]  # does install bokeh, but used bokeh 2.4.2 for me
```

I'm not sure if the reason I got bokeh 2.4.2 is just because I already had that cached though.

**Comment by jrbourbeau** [comment]
Thanks @garryod, a PR would be welcome. It looks like `bokeh`s downstream CI build caught this (and other issues) https://github.com/bokeh/bokeh/runs/4551763507?check_suite_focus=true. cc @bryevdv for visibility

**Comment by garryod** [comment]
Looks like our internal pypi server is to blame for serving me the wrong version. I've been unable to reproduce the issue using the official pypi server. Will pop the PR in regardless.

**Comment by bryevdv** [comment]
Do you actually need `render_mode="css"` ? If not a change compatible with 2.x and 3.x would be to just to remove that parameter and use default canvas rendering.

**Comment by jrbourbeau** [comment]
Good point. It looks like we only use `render_mode=` in the system plot. I'm not sure if it's needed, when I comment it out locally the system plot looks the same. cc @charlesbluca who added `render_mode=` in https://github.com/dask/distributed/pull/4561

**Comment by charlesbluca** [comment]
Thanks for the ping @jrbourbeau; I can't remember any obvious reason why I set `render_mode` explicitly in that PR, so I would say if things look the same when we leave it as default it should be safe to remove the kwargs.

**Comment by bryevdv** [comment]
CSS render mode is mostly useful if you need to have more sophisticated styling. Canvas basically has font size and font style (only normal, bold, italic). If more than that is needed, you can use CSS render mode and provide some custom CSS to add whatever fancier styles the label needs.

**Comment by jrbourbeau** [comment]
Thanks for clarifying @charlesbluca @bryevdv. Sounds like we don't need `render_mode` -- @garryod if you could push up a PR that removes that keyword, that would be great
