### ISSUE TITLE
Flaky test test_worker_reconnects_mid_compute*

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5621]
The two tests seem to fail occasionally on windows

`test_worker_reconnects_mid_compute_multiple_states_on_scheduler`
`test_worker_reconnects_mid_compute`

https://github.com/dask/distributed/runs/4556308866?check_suite_focus=true

[windows-latest-3.8-ci1-timeouts.zip](https://github.com/dask/distributed/files/7752878/windows-latest-3.8-ci1-timeouts.zip)

**Comment by crusaderky** [comment]
These two tests fail consistently, but only on Windows 3.8 specifically
![Screenshot from 2022-02-11 12-41-50](https://user-images.githubusercontent.com/6213168/153593262-390562e6-a396-40ab-b851-e8a53a26ccce.png)
.

**Comment by fjetter** [comment]
These tests were removed as part of https://github.com/dask/distributed/pull/6361
