### ISSUE TITLE
Changelog links don't reference specific release version

### ISSUE THREAD

**Issue by aneeshnema** [dask/distributed#5637]
Duplicate of https://github.com/dask/dask/issues/8473

Summary:
Anchor links in the changelog don't actually reference a specific released version.
If I go to the changelog and click on the `2021.12.0` link, I'm redirected to https://docs.dask.org/en/stable/changelog.html#id1 when, naively, I would have expected this link to look like https://docs.dask.org/en/stable/changelog.html#2021.12.0

**Comment by jrbourbeau** [comment]
Thanks @aneeshnema -- whatever fix we go with over in `dask/dask` can be applied here too
