### ISSUE TITLE
Use of unix only resource module

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#564]
Prevents using distributed on Windows!
```python-traceback
 File "C:/dev/code/sandbox/test_dask.py", line 8, in <module>
    from distributed import Client

  File "c:\dev\packages\distributed\distributed\__init__.py", line 5, in <module>
    from .deploy import LocalCluster

  File "c:\dev\packages\distributed\distributed\deploy\__init__.py", line 3, in <module>
    from .local import LocalCluster

  File "c:\dev\packages\distributed\distributed\deploy\local.py", line 15, in <module>
    from ..scheduler import Scheduler

  File "c:\dev\packages\distributed\distributed\scheduler.py", line 11, in <module>
    import resource

ImportError: No module named 'resource'
```

Issue was introduced in https://github.com/dask/distributed/commit/b2cc90a88be5246231325c773c1d19e7997df3da but is also present on [`master`](https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L11)

It looks like the windows equivalent is `_getmaxstdio`/`_setmaxstdio`?

![image](https://cloud.githubusercontent.com/assets/881019/19098950/04c1a96e-8af5-11e6-88a2-6f1ac814e175.png)
https://msdn.microsoft.com/en-us/library/kdfaxaay(v=vs.140).aspx

http://docs.activestate.com/activepython/2.7/pywin32/win32file___getmaxstdio_meth.html
http://docs.activestate.com/activepython/2.7/pywin32/win32file___setmaxstdio_meth.html
![image](https://cloud.githubusercontent.com/assets/881019/19098969/24a61e90-8af5-11e6-8d7d-b42662c99080.png)

![image](https://cloud.githubusercontent.com/assets/881019/19098976/378b2ce4-8af5-11e6-96cf-ad8932bc4dba.png)

**Comment by dhirschfeld** [comment]
It seems to be protected in [`dask_scheduler.py`](https://github.com/dask/distributed/blob/master/distributed/cli/dask_scheduler.py#L55-L58) but not in [`scheduler.py`](https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L321)

**Comment by mrocklin** [comment]
A short term solution would be to just disable this entirely for Windows
and trust to the 512 default.  This is a bad idea if people are deploying
large clusters on Windows, but a good idea if we want to get things moving
again quickly.

**Comment by dhirschfeld** [comment]
I'd be happy with that (for now) - and in fact that's how I've patched my local version!

**Comment by mrocklin** [comment]
Any interest in submitting a PR with a fix?

**Comment by dhirschfeld** [comment]
I can give it a go. Might not be until next week though...

**Comment by jreback** [comment]
@dhirschfeld see this issue: https://github.com/dask/distributed/pull/565. large clusters on windows actually work nicely, provided a linux based scheduler :>
