### ISSUE TITLE
Drop PyPy compatibility?

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#5681]
During a call today the issue of dropping PyPy compatibility was brought up.

We currently loosely maintain PyPy compatibility (we don't test with PyPy at all), but some design/process decisions take PyPy into account. For example, currently the cython build of the scheduler requires that all annotations also work in pure python mode so it can run without cythonization. These annotations muddy the code, and don't work as well with type checkers like MyPy. Additionally, avoiding separating out the cython bits of our code makes it harder to understand what bits have been optimized for cython, and also make it harder to perform further c-extension level optimizations.

Since many users are using libraries that don't support PyPy, PyPy is likely mainly useful for speeding up the scheduler (leaving the workers running cpython). I don't know of any users running in this configuration though (most users use the same python environment for both scheduler and workers), and suspect that the maintenance burden outweighs the benefit.

As such, I suggest that we drop our (loose) PyPy compatibility requirement. This would result in no immediate changes to the codebase, but going forward we might make changes that break compatibility.

**Comment by jcrist** [comment]
Ope, pinging some relevant people from different orgs: @quasiben, @jakirkham, @jrbourbeau, @fjetter, @jsignell (apologies if this issue is relevant to you and I didn't ping you).

**Comment by jakirkham** [comment]
I think @mariusvniekerk has used PyPy support in the past.

Not sure who else. Random issues like this one ( https://github.com/dask/distributed/issues/2734 ) pop-up from time to time suggesting people use this, but have the occasional minor problem.

**Comment by jakirkham** [comment]
cc @mattip (for awareness)

**Comment by jakirkham** [comment]
With Cython annotations, are these only there because of PyPy? At least my understanding originally when working on those was we cared about having pure Python with no Cython as a run option. This can matter outside of PyPy (for example some linters don't work on Cython). Additionally this adds a compilation step for users or packagers. IOW are we now comfortable requiring Cython? Should add this is somewhat separate from PyPy as Cython can also be used with PyPy.

I'm curious if you have some examples of libraries not supported on PyPy that are important. Asking this as conda-forge builds PyPy packages for all sorts of libraries.

**Comment by mattip** [comment]
I am missing a bit of background. 
- It seems there is a python-only wheel on PyPI, https://pypi.org/project/distributed/2022.1.0/#files. Where does cython come into play?
- Are there benchmarks or indications that this library is a bottleneck in some workflow that means people might be searching for a speed-up? If so it might be nice to try PyPy. If not, then why would someone bother?

**Comment by fjetter** [comment]
> It seems there is a python-only wheel on PyPI, https://pypi.org/project/distributed/2022.1.0/#files. Where does cython come into play?

We are indeed not publishing any cythonized builds (https://github.com/dask/distributed/issues/4442). We attempted to implement an optional cythonization for the scheduler (https://github.com/dask/distributed/blob/337f152a0eccf7c1511c0462f007dda6d507e4d3/setup.py#L26-L30) but we never published a build so this would require users to build it themselves. In fact, we are actually also considering to drop support for this, see https://github.com/dask/distributed/issues/5685

> Are there benchmarks or indications that this library is a bottleneck in some workflow that means people might be searching for a speed-up? If so it might be nice to try PyPy. If not, then why would someone bother?

There are a bunch of issues open about speeding up the scheduler. It's known to be bottlenecked for high task workflows (e.g. once you reach 1M tasks). There's been some extensive profiling ongoing as well. There are actually many tickets in our tracker about this topic. Here are just a few important ones

* https://github.com/dask/distributed/issues/854
* https://github.com/dask/distributed/issues/4443

**Comment by jakirkham** [comment]
Sorry for taking us down a tangent here, I'm doubtful that Cython and PyPy are incompatible. We aren't doing anything that is likely to cause PyPy significant issues (there may be performance differences though).

**Comment by jrbourbeau** [comment]
> DId we drop pypy support? Were we even maintaining this?

We decided to drop support at the monthly community meeting on 2022-02-03

> If we wanted to push forward on dropping this, what would be a next step (if there are any)?

I think the actual code changes for dropping support are fairly minimal. See https://github.com/dask/distributed/pull/6029

**Comment by jakirkham** [comment]
There may be packaging changes as well. Filed issue ( https://github.com/conda-forge/distributed-feedstock/issues/201 ) to figure that out

**Comment by jcrist** [comment]
Resolved by #6029. Closing.

**Comment by mrocklin** [comment]
It was nice to see people moving quickly here
