### ISSUE TITLE
Flaky test_adapt_quickly

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5682]
test_adapt_quickly occasionally hangs on Windows, and -to my knowledge- on Windows only.

e.g. https://github.com/dask/distributed/runs/4734418309?check_suite_focus=true

It hangs on pytest_timeout after 300s, which brings down the whole process without any useful stack trace, dump, or log, even if the test uses gen_test to get a much nicer failure after 30s. The only way, to my knowledge, that the gen_test timeout is being ignored is that something is going into an infinite loop without ever returning control to the asyncio event loop.

**Comment by fjetter** [comment]
No failures on the test report. Will close this for now

**Comment by crusaderky** [comment]
That's because when test_adapt_quickly hangs a junit report is not produced. See https://github.com/dask/distributed/pull/5832

**Comment by crusaderky** [comment]
This is the no.1 offender in the branch that doesn't import pandas at worker load: https://github.com/crusaderky/distributed/runs/5273042416?check_suite_focus=true

**Comment by fjetter** [comment]
FYI I suspect all tests that are using SpecCluster / LocalCluster are actually blocked by a race condition during cluster closing. I've been spending a bit of time today on this but couldn't fix it, yet. See also https://github.com/dask/distributed/issues/4859#issuecomment-854705100

**Comment by fjetter** [comment]
Appears to be resolved
