### ISSUE TITLE
flaky test_client_timeout

### ISSUE THREAD

**Issue by graingert** [dask/distributed#5703]
> Test failed once with "address already in use". As there's no way to bind to port 0 here, and nothing else uses that port in the test suite, there's little that can be done to prevent it short of some ad-hoc pytest extension.

_Originally posted by @crusaderky in https://github.com/dask/distributed/issues/5397#issuecomment-939938675_

I saw this again here; https://github.com/graingert/distributed/runs/4938723876?check_suite_focus=true#step:12:1369

**Comment by quasiben** [comment]
Is this still an issue ?  I don't see it anywhere in the latest test report

**Comment by crusaderky** [comment]
I haven't seen it in a while either

**Comment by crusaderky** [comment]
Correction: it's because is labelled as flaky.

**Comment by crusaderky** [comment]
Reading the test, it tries binding the scheduler to a random port - so there's a (small) chance of collision. I'm going to leave the flaky label there - nothing that can be done about it - but I'm closing this issue.
