### ISSUE TITLE
test_dataframe_groupby_tasks is failing

### ISSUE THREAD

**Issue by ian-r-rose** [dask/distributed#5711]
As of dask/dask#8563 the acceptable `meta` for a Dask DataFrame got stricter. This is causing failures in `test_dataframe_groupby_tasks`.

Regardless of whether the upstream change sticks, this should be an easy fix to make here.

**Comment by jrbourbeau** [comment]
Thanks for surfacing @ian-r-rose. This should have been fixed by @jsignell  in https://github.com/dask/distributed/pull/5694 yesterday

**Comment by ian-r-rose** [comment]
Ah, missed that. Thanks @jsignell
