### ISSUE TITLE
numpy is imported unconditionally

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5729]
We have many unit tests that generate Nannies with spawn method. In theory, those tests should become a lot faster if numpy was imported only if needed.
This is not the case today, because of 

1. two places that import pandas; see blockers:
    - https://github.com/dask/distributed/pull/5695
    - https://github.com/dask/distributed/pull/5723
    - https://github.com/dask/distributed/pull/5724
2. two ``import blosc`` statements in ``distributed.protocol.compression``

xfailed unit test is already in #5695.

Note that this means that fixing this issue means that, across all unit tests that do use numpy data on nannies, ``import numpy`` will be moved from ``@gen_cluster`` start to the first time where a numpy array or function is deserialised - which in turn may cause flakiness if the test time margins are too tight.

CC @gjoseph92

**Comment by gjoseph92** [comment]
Yes, I also just looked into the same thing. Maybe we should provide a helper in https://github.com/dask/distributed/pull/5724 for checking if a package exists (via `importlib.metadata`/`pkg_resources`) without actually importing it, so we can use that on blosc?
Also xref https://github.com/dask/distributed/issues/5269.

**Comment by crusaderky** [comment]
> Maybe we should provide a helper in #5724 for checking if a package exists (via `importlib.metadata`/`pkg_resources`) without actually importing it, so we can use that on blosc?

Not that simple - ``distributed.protocol.compression`` fills up a dict of compress/decompress callables at module import time, so we'd need to be a bit more creative.

**Comment by gjoseph92** [comment]
https://github.com/Blosc/python-blosc/pull/159 seems stalled, but we could probably suggest just not importing the tests in top-level `__init__.py`. I'm not sure this is worth worrying about too much right now beyond trying to get an upstream change?

**Comment by crusaderky** [comment]
#### WON'T FIX
#5750 introduces a new unconditional import of numpy, whose benefits definitely exceed those of this ticket.

**Comment by jakirkham** [comment]
If you can think of better ways to handle that `import`, am open to other options 🙂
