### ISSUE TITLE
Publish 1.13.3 to PyPI

### ISSUE THREAD

**Issue by benauthor** [dask/distributed#573]
Fantastic project! According to [changelog](https://github.com/dask/distributed/blob/master/release-notes.md), you've got a 1.13.3 release as of a few days ago, but 1.13.2 is the latest on [PyPI](https://pypi.python.org/pypi/distributed). Do you plan to publish this latest release there?

**Comment by benauthor** [comment]
Oh, reading git history I think i understand, you're collecting new features in the release notes and will cut an actual new release at some point in the future.

**Comment by jcrist** [comment]
That is correct - you can see the list of releases here: https://github.com/dask/distributed/releases.

**Comment by mrocklin** [comment]
I hope to issue a release within a week or so.

**Comment by benauthor** [comment]
💯
