### ISSUE TITLE
Context manager for utils_test to check for leaking file descriptors

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5760]
Many of our tests are failing with OSError, timeouterror, etc.

We should ensure that we are not systematically leaking any resources.

One way is to add a `check_filedescriptorlimit` contextmanager similar to our `check_processleak`, etc. calls

This contextmanager should be enabled for all `gen_test` and `gen_cluster` tests

**Comment by graingert** [comment]
looks like it needs updating too, eg, this should be `from multiprocessing.resource_tracker import main` now: https://github.com/dask/distributed/blob/9fdada1fef36545ef5b560a512d21709d7d46b56/distributed/pytest_resourceleaks.py#L186

**Comment by fjetter** [comment]
I noticed it not being covered (code coverage) but it _should_ be enabled, see https://github.com/dask/distributed/blob/9fdada1fef36545ef5b560a512d21709d7d46b56/conftest.py#L37
