### ISSUE TITLE
Collect and dump resource usage of tests upon failure

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5763]
A lot of our tests deadlock and it is often unclear why. Is there a deadlock, an infinite loop? Collecting before/after and dumping hardware related information like CPU and RSS upon build failure can help triaging the failure.

cc @crusaderky any more metrics that would be useful?

**Comment by crusaderky** [comment]
- mean CPU % over the course of the test (psutil does it out of the box). Make sure to include child processes (or just measure host global CPU time).
- RSS before the test starts and when it fails, BEFORE gen_cluster teardown. Also need to include child processes (or just measure host global RSS)
- number of open file descriptors, also at setup vs before gen_cluster teardown

**Comment by fjetter** [comment]
I think we moved on from this idea. If there is still interest, please reopen
