### ISSUE TITLE
Failures on Windows in distributed/tests/test_client.py

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#581]
```
________________________ test_task_load_adapts_quickly ________________________
distributed\utils_test.py:378: in test_func
    loop.run_sync(lambda: cor(*args), timeout=timeout)
c:\miniconda3\envs\dask35\lib\site-packages\tornado\ioloop.py:457: in run_sync
    return future_cell[0].result()
c:\miniconda3\envs\dask35\lib\site-packages\tornado\concurrent.py:237: in result

    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
c:\miniconda3\envs\dask35\lib\site-packages\tornado\gen.py:1024: in run
    yielded = self.gen.send(value)
distributed\tests\test_client.py:2635: in test_task_load_adapts_quickly
    assert 0 < s.task_duration['slowinc'] < 0.1
E   assert 0 < 0.0
_________________ test_cleanup_after_broken_client_connection _________________
distributed\utils_test.py:378: in test_func
    loop.run_sync(lambda: cor(*args), timeout=timeout)
c:\miniconda3\envs\dask35\lib\site-packages\tornado\ioloop.py:457: in run_sync
    return future_cell[0].result()
c:\miniconda3\envs\dask35\lib\site-packages\tornado\concurrent.py:237: in result

    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
c:\miniconda3\envs\dask35\lib\site-packages\tornado\gen.py:285: in wrapper
    yielded = next(result)
distributed\tests\test_client.py:1605: in test_cleanup_after_broken_client_conne
ction
    proc.start()
c:\miniconda3\envs\dask35\lib\multiprocessing\process.py:105: in start
    self._popen = self._Popen(self)
c:\miniconda3\envs\dask35\lib\multiprocessing\context.py:212: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
c:\miniconda3\envs\dask35\lib\multiprocessing\context.py:313: in _Popen
    return Popen(process_obj)
c:\miniconda3\envs\dask35\lib\multiprocessing\popen_spawn_win32.py:66: in __init
__
    reduction.dump(process_obj, to_child)
c:\miniconda3\envs\dask35\lib\multiprocessing\reduction.py:59: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'test_cleanup_after_broken_client_
connection.<locals>.f'
======== 2 failed, 188 passed, 18 skipped, 1 xfailed in 174.81 seconds ========
```

**Comment by mrocklin** [comment]
The `test_task_load_adapts_quickly` failure is because we're using `time.time()`, which on Windows seems to be rounded to the nearest second.

**Comment by pitrou** [comment]
Yes, Windows has a poor granularity timer. We could just skip that assertion on Windows.

**Comment by mrocklin** [comment]
That test tests an optimization.  Everything should work fine without that functionality.  At some point it would be nice to find a timer that...

1.  Had good precision everywhere
2.  Gave values that were based on the same meaning, for example "time after the epoch" rather than "time after the process began"
3.  Was fast

**Comment by mrocklin** [comment]
The pickling error I suspect is just cloudpickle behaving somewhat differently on Windows.  I'm also comfortable skipping it.

**Comment by pitrou** [comment]
The pickling error could be fixed by making the callback function a global function, what do you think?

**Comment by mrocklin** [comment]
Ah, I see.  This is just an issue with normal multiprocessing.  

Yes, moving it to the top level seems like a good solution to me.

**Comment by pitrou** [comment]
The only timer with good precision on Windows is `time.perf_counter`, but it doesn't have a well-defined epoch (i.e. you could measure durations inside a given thread or process, but not compare absolute times from different processes).

**Comment by mrocklin** [comment]
I recommend that we just skip the test for now.  We can make the scheduler handle relative times in the future.  We already do something like this to account for small clock offsets.

**Comment by jreback** [comment]
FYI a couple of test failures can be bypassed by passing ``timeout=...`` on ``@gen_cluster``, as windows procs take a bit longer to startup/shutdown (e.g. ``test_scheduler/test_restart``)
