### ISSUE TITLE
Upload of `distributed-impl` fails due to duplicate

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#5864]
Seeing the following [on CI]( https://github.com/dask/distributed/runs/5326233537?check_suite_focus=true#step:6:355 ):

```
Uploading file "dask/distributed-impl/2022.02.1a220224/noarch/distributed-impl-2022.02.1a220224-cython.tar.bz2"
Distribution already exists. Please use the -i/--interactive or --force or --skip options or `anaconda remove dask/distributed-impl/2022.02.1a220224/noarch/distributed-impl-2022.02.1a220224-cython.tar.bz2
Error:  ('file noarch/distributed-impl-2022.02.1a220224-cython.tar.bz2 already exists for package distributed-impl version 2022.02.1a220224', 409)
Error: Process completed with exit code 1.
```

cc @charlesbluca

**Comment by jakirkham** [comment]
Wondering if we should start including a time stamp or git hash to help distinguish these further

**Comment by charlesbluca** [comment]
Good catch, completely forgot that these are only distinguished by the pre-release version

> Wondering if we should start including a time stamp or git hash to help distinguish these further

I think the hash makes sense here to distinguish which distributed commit triggered the build, though it'd probably be important to note that would change the install command for specifying Cython slightly from

```
conda install -c dask/label/dev distributed-impl=*=cython
```

to

```
conda install -c dask/label/dev distributed-impl=*=*cython
```

**Comment by charlesbluca** [comment]
Alternatively we could add the `--force` flag to the `noarch` uploads, as I don't think there's a chance for simultaneous uploads here

**Comment by jakirkham** [comment]
Challenge with `--force` is we lose reproducibility (say if the previous package showed some issue we wanted to reproduce)

**Comment by jakirkham** [comment]
We might be able include the hash in the version. For example using the `+` syntax that versioneer often uses for this kind of thing

**Comment by jakirkham** [comment]
In conda-forge we have a package that uses [a full timestamp]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/8ff08c417a2d37fb3cc963b74cd63ecd3b92bb81/recipe/meta.yaml#L1 ). So maybe an option if we go that way

**Comment by charlesbluca** [comment]
In that case, let's go with the hash for now as a minimal solution - if for whatever reason that doesn't work out, happy to switch to a full timestamp

**Comment by charlesbluca** [comment]
Opened https://github.com/dask/distributed/pull/5865 to resolve this / continue the conversation

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/dask/distributed/pull/5865 )

**Comment by jakirkham** [comment]
Seems to have [worked]( https://github.com/dask/distributed/runs/5327716460?check_suite_focus=true ) 😀
