### ISSUE TITLE
This warning has too much output !! Can i change this warning to debug level?

### ISSUE THREAD

**Issue by RockYuan** [dask/distributed#5866]
Unmanaged memory use is high. This may indicate a memory leak ... bla bla bla...  has  too much output !! I can't see other importent warning log. Can i change this line warning to debug level?

https://github.com/dask/distributed/blob/8a99ac7c878ca7c6e0adc166c0cd6fa4a41b4289/distributed/worker.py#L3759

Thank your great works !

**Comment by fjetter** [comment]
If you want to get rid of a specific warning, I suggest to configure this in your application. See https://docs.python.org/3/library/warnings.html#the-warnings-filter

Demoting this to debug level is something I don't feel great about. This is quite a serious warning and in most use cases should trigger some kind of response from users.

**Comment by fjetter** [comment]
If you still have trouble with this, please reopen the ticket.
