### ISSUE TITLE
[Style] Absolute vs Relative imports

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5889]
We're using a lot of relative imports in this package and we're not very consistent about when and how to use which. Counting occurrences in the entire code base slightly favours absolute imports (about 56%).

[PEP8](https://www.python.org/dev/peps/pep-0008/) recommends the usage of absolute imports over relative imports unless a complex package layout would require unnecessarily verbose import statements

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path):
> [...]
> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:

I personally prefer absolute imports since they are much less ambiguous and portable. 

For instance, there are 24 `from .core import` and four `from ..core import` statements and we have six `core.py` files. It's not hard to figure out where the imports are pointing to but an absolute version removes ambiguity, especially for multi-level relative references

If we go for absolute imports, a follow up question would be whether we want to automate this, e.g. https://github.com/MarcoGorelli/absolufy-imports

Thoughts?

**Comment by fjetter** [comment]
> This strikes me as something isort should do. Maybe there's a switch for it?

https://github.com/PyCQA/isort/issues/1677

**Comment by ian-r-rose** [comment]
I was unaware of the recommendation for absolute imports in PEP8, but I don't really agree with it, and second @crusaderky's sentiment that things were a mess before relative imports were an option.

I'd like to specifically call out that people's software environments can be a mess, and can be broken in ways that are too numerous to count (especially for inexperienced users). I've seen cases where absolute imports find the wrong version of the package that is installed somewhere weird and things start to fail in impossible-to-debug ways. We're obviously not responsible for broken user environments, but to me there is some value in things possibly failing faster. This is directly opposed to the PEP8 assertion that such failures are "better behaved", and  "give better error messages", so :man_shrugging:

**Comment by jsignell** [comment]
If we decide to enforce absolute imports we can definitely automate that. I have used absolutify on other projects.

I have no opinion on whether absolute/relative is preferable.

**Comment by fjetter** [comment]
> I'd like to specifically call out that people's software environments can be a mess, and can be broken in ways that are too numerous to count (especially for inexperienced users). I've seen cases where absolute imports find the wrong version of the package that is installed somewhere weird and things start to fail in impossible-to-debug ways. We're obviously not responsible for broken user environments, but to me there is some value in things possibly failing faster. This is directly opposed to the PEP8 assertion that such absolute import failures are "better behaved", and "give better error messages", so

I'm not too concerned about this. If that was a problem, I am pretty sure we'd have heard of this before since we're not 100% consistent with how we import.

IMHO, there is not a technical reason for a properly packaged library to prefer the one over the other. 

I am mostly advocating for a consistent code style. I consider absolute imports much easier to read and don't think our tree is complex enough that we require shortening.
I hate debating about style on a PR and **love** that black, isort, etc. takes care of most of the ambiguity. If we can somehow enforce the rule "relative in modules, absolute in test" using a pre-commit hook, I'm in. I care about automation and linting way more than about the actual style :)

**Comment by gjoseph92** [comment]
> I hate debating about style on a PR and **love** that black, isort, etc. takes care of most of the ambiguity. If we can somehow enforce the rule "relative in modules, absolute in test" using a pre-commit hook, I'm in. I care about automation and linting way more than about the actual style :)

+1, would love to see this.

I also would prefer absolute imports in code. It makes any refactoring much easier, for one thing, and is unambiguous to read.

**Comment by MarcoGorelli** [comment]
Hey, thanks for looking into absolufy-imports

> If we can somehow enforce the rule "relative in modules, absolute in test" using a pre-commit hook

something like 
```
  -   repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
      - id: absolufy-imports
        name: absolufy-imports (modules)
        files: ^distributed/
        exclude: ^distributed/tests/
        args: [--never]
      - id: absolufy-imports
        name: absolufy-imports (tests)
        files: ^distributed/tests/
```
might work for you?

> This strikes me as something isort should do. Maybe there's a switch for it?

Yeah, I haven't had much free time recently, but I'd like to try to get this into isort eventually (not soon, unfortunately)

**Comment by gjoseph92** [comment]
As someone who prefers "absolute in modules, relative in tests" (or frankly just absolute everywhere), seeing a PR showing the opposite would make me happy :)

**Comment by jsignell** [comment]
@dask/maintenance if anyone has issues with enforcing absolute imports to comply with pep8 please speak up!

**Comment by jakirkham** [comment]
Also prefer absolute imports and like that there is tooling to make that simple. Would be good to make sure we have a CI check for it.

**Comment by crusaderky** [comment]
Matching PRs in our other projects:
- https://github.com/dask/dask/pull/8803
- https://github.com/dask/zict/pull/66
