### ISSUE TITLE
Assertion for `SpillBuffer` breaks usage of custom `Worker(data=...)` types

### ISSUE THREAD

**Issue by pentschev** [dask/distributed#5909]
https://github.com/dask/distributed/pull/5814 introduced https://github.com/dask/distributed/blob/main/distributed/worker.py#L3884 which I believe unintentionally breaks the flexibility of passing a custom type via `Worker(data=...)`. In Dask-CUDA we use the `data=` kwarg to pass a specialized handler for spilling GPU memory, and it currently breaks one of our tests, see [here](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/dask-cuda/job/branches/job/dask-cuda-gpu-matrix-branch-22.04/CUDA=11.0,GPU_LABEL=driver-450,LINUX_VER=centos7,PYTHON_VER=3.9/27/testReport/dask_cuda.tests/test_proxify_host_file/test_worker_force_spill_to_disk/).

Would it be possible to remove that assertion or make it somehow flexible so that a custom type wouldn't fail?

cc @crusaderky who's the author.

cc @quasiben @madsbk

**Comment by crusaderky** [comment]
Fixed in #5904. I would be grateful if you could review it and see if it is fit for purpose for you.
