### ISSUE TITLE
Incorrect adress when running LocalCluster on Windows

### ISSUE THREAD

**Issue by efredriksson-modelon** [dask/distributed#5918]
**What happened**:
Running the following code

```python
import dask.distributed
cluster = dask.distributed.LocalCluster()
```
Would result in this pop-up:
![bild](https://user-images.githubusercontent.com/18346319/157456969-02d752b5-a30c-42c1-960e-eabaca93e075.png)

**What you expected to happen**:
I would not expect any firewall issues running a Local cluster.

**Minimal Complete Verifiable Example**:
See above.

**Anything else we need to know?**:
I did some debugging and think I found the issue. My solution is in this [patch](https://github.com/dask/distributed/files/8215350/check-for-empty-string.zip). The issue seems to be that the `address` field returned from `clean_dashboard_address` is never `None`, but rather an empty string to signify that it is not set.

It should also be noted that you only see this pop-up once for every executable. You can trick Windows to think a Python installation is 'new' by moving it to another path and get the pop-up again.

**Environment**:
- Dask version: 2022.02.0
- Python version: 3.7
- Operating System: Windows 10
- Install method: pip

**Comment by maldag** [comment]
I can confirm your issue, but modified the line 147 in node.py to:

`if http_address["address"] is None or http_address["address"] is '':`

Due to the fact tornado will listen to all interfaces is address is '' or None, this should not happen in this case if host is set to localhost
