### ISSUE TITLE
SIGTERM when using LocalCluster

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#593]
When I try to create a `LocalCluster` (awesome feature btw, it was tedious to manually manage and spawn the cluster :-) ) and I run some jobs on it, it sometimes prints `Received SIGTERM, shutting down` to stdout just before the program ends. I think that it may have something to do with a memory limit, for example with this snippet:
```python
from distributed import Executor
from distributed import LocalCluster

cluster = LocalCluster(scheduler_port=8500,
                 n_workers=2,
                 threads_per_worker=1)
client = Executor(cluster)
futures = client.map(lambda x: range(x), [1,2,300000])
client.gather(futures)
```
It prints `Received SIGTERM, shutting down` every time, but if I change `range` to `xrange`, it doesn't (yet I have enough memory to construct `range(300000)`). Is this something to worry about? It seems that it doesn't affect the program, but it also seems like something goes wrong when the cluster shuts down. When I insert `cluster.close()` after the gather, it prints the error twice, once during the `close` and then again during program shutdown.

**Comment by mrocklin** [comment]
It probably shouldn't be logging that to the screen, no, but it's nothing to worry about.  When you exit ipython it's shutting down the workers by sending them SIGTERM signals.  This is routine.
