### ISSUE TITLE
Flaky test_missing_data_errant_worker

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5932]
cc @fjetter 
Since #5883, ``test_missing_data_errant_worker`` has become highly flaky and very frequently hangs.
The issue is easily reproducible on a fast desktop host (it hangs 30~50% of the times).

**Comment by crusaderky** [comment]
big shoutout to @ian-r-rose and his tool https://dask.org/distributed/test_report.html which made this kind of bisect work a breeze!

**Comment by crusaderky** [comment]
``test_worker_stream_died_during_comm`` is also showing a suspiciously correlated pattern on https://dask.org/distributed/test_report.html but I could not reproduce the issue locally.

**Comment by fjetter** [comment]
We just merged https://github.com/dask/distributed/pull/6091 which will make this test flaky again until https://github.com/dask/distributed/pull/5910 is merged
