### ISSUE TITLE
Typo in docs relating to example code for worker plugins

### ISSUE THREAD

**Issue by crendoncoiled** [dask/distributed#5938]
**Issue**:
From plugins.rst, there's an example illustrating the use of workerplugins
```python
class ErrorLogger(WorkerPlugin):
    def __init__(self, logger):
        self.logger = logger
...
```
```python
plugin = ErrorLogger()
client.register_worker_plugin(plugin)
```
However the code incorrectly instantiates ErrorLogger since it's missing the actual logger

**Solution**
```python
import logger
plugin = ErrorLogger(logger)
```
This requires a minimal change and thus I intend on submitting an MR shortly.

**Comment by ncclementi** [comment]
@crendoncoiled Thank you for reporting this, I can reproduce the error.  A PR will be welcomed, one small thing I think we should do:

```
import logging
plugin = ErrorLogger(logger)
```
