### ISSUE TITLE
x-distributed version checks / diagnostic.

### ISSUE THREAD

**Issue by jreback** [dask/distributed#595]
Having mismatched version across the cluster can be hard to detect and cause very odd error reports.

a function to give a snapshot of the versions of various required packages that are used in pieces of the system would be useful. IOW, we have scheduler, workers, and the user environment. 

This would be a first step towards a validation of the environments. IOW, it is *very* important that we have the *same* versions of ``distributed`` running on the workers & the user env. For some operations it is imperative that ``dask`` match (or at least be compatible). I imagine other ``cloudpickle`` & ``msgpack-python`` should be compatible as well. 

So I would envision a ``client.get_versions()`` which could return data on each worker, the user environment and the scheduler environment. (maybe a ``DataFrame`` of results).

At the very least this would be a nice diagnostic. Furthermore *maybe* then the scheduler could provide a warning if mismatches in versions exist.

This would be somewhat linked with #300 as full-fledged environments would also need tools to introspect the remote environments.

**Comment by mrocklin** [comment]
Agreed.  This could be implemented in the following steps:

1.  Collect a list of relevant packages.
2.  Make a bare function that gets the versions of all of those packages.
3.  Use something like `client.run` to call that function on all of the workers
4.  Call that function locally in the client process
5.  Verify that everyone agrees
