### ISSUE TITLE
the "distributed.worker" logger gains ~thousand DequeHandler instances during a pytest run

### ISSUE THREAD

**Issue by graingert** [dask/distributed#5973]
running `len(logging.getLogger("distributed.worker").handlers)` shows a few thousand `DequeHandler` instances in there.
This means that logging messages from the worker or adding handlers to the worker gradually gets slower and slower as the test suite progresses.

the handlers are supposed to be cleared when the worker is GC'd by
https://github.com/dask/distributed/blob/1da51994cc84c0897589a4476cd24073147054b6/distributed/node.py#L88 however https://github.com/dask/distributed/blob/1da51994cc84c0897589a4476cd24073147054b6/distributed/utils.py#L1131-L1142 keeps a permanent strong reference to the worker:

![image](https://user-images.githubusercontent.com/413772/159285688-6305720a-ee4c-4bef-a375-09a6c07fc36b.png)

see https://github.com/dask/distributed/pull/4481 and https://github.com/dask/distributed/issues/4469

**Comment by fjetter** [comment]
If the performance problem is an actual concern, ensuring all handlers are async is probably the most straight forward and would resolve a few other issues around exception handling

some earlier and related work
- https://github.com/dask/distributed/pull/5443
- https://github.com/dask/distributed/pull/4734
- https://github.com/dask/distributed/issues/5483
