### ISSUE TITLE
Workers with long running tasks are only ones that accept new work

### ISSUE THREAD

**Issue by wwoods** [dask/distributed#5975]
This is almost certainly fallout from the fix for https://github.com/dask/distributed/issues/5332 .

With the latest versions (since 2022.1.0, through 2022.3.0), we're seeing occupancy numbers like `-1531476972.28 us` on workers with long running tasks that have seceded. To the scheduler, this looks very appealing and they are the only workers that get assigned work. As one might imagine, this really inhibits processing speed on a large cluster.

**Comment by wwoods** [comment]
Seems to happen only if other tasks are being spun up and completing alongside the long running task.

**Comment by wwoods** [comment]
Here's a MWE:

```python
import dask.distributed
import time
def tlong():
    dask.distributed.secede()
    while True:
        time.sleep(1.)
def t1():
    # Bug only happens with tasks that also secede
    dask.distributed.secede()
    time.sleep(0.1)
def main():
    cli = dask.distributed.Client()
    a = cli.submit(tlong, pure=False)
    c = dask.distributed.as_completed()
    while True:
        while c.count() < 5:
            c.add(cli.submit(t1, pure=False))
        for future in c:
            break

if __name__ == '__main__':
    main()
```

**Comment by edyounis** [comment]
I believe I may be experiencing a similar or the same issue. I was going to post a new issue but figured I just add to this one first.

I am running a workload that submits several top-level tasks, which in turn submit tasks. These use the `get_client`, `secede`, `rejoin` method for submitting tasks from within tasks. For a large portion of the runtime, all tasks are executing on a single worker. I have a MWE below, and I have attached a picture of the task stream from running this.

```
import time
from dask.distributed import Client
from dask.distributed import get_client
from dask.distributed import secede
from dask.distributed import rejoin

def long_running_job(circuit):
    time.sleep(.1)
    return 1

def run(num_work):
    client = get_client()
    results = []
    for _ in range(num_work):
        futures = client.map(
            long_running_job,
            [x for x in range(16)],
            pure=False,
        )

        secede()
        results.append(client.gather(futures))
        rejoin()

    return results

lens = [46, 12, 30, 46, 64, 78, 46]

if __name__ == "__main__":    
    client = Client(threads_per_worker=1)
    futures = []
    for num_work in lens:
        futures.append(client.submit(run, num_work, pure=False))
    results = client.gather(futures)
```

![task_stream](https://user-images.githubusercontent.com/7897816/160046352-0e61be80-2b4d-4678-8b7b-2e9525a7e17b.png)
