### ISSUE TITLE
Preload fetching should be robust to transient error codes

### ISSUE THREAD

**Issue by shughes-uk** [dask/distributed#5981]
If you pass a url to load a preload from currently it seems it will give up fairly fast on encountering most likely transient http error codes.

Preferably on encountering these codes, exponential backoff should be employed with a configurable maximum wait time (or possibly infinite).
```
429 - rate limit
504 - gateway timeout
503 - service unavailable
502 - bad gateway
```
If you don't want to make explicit decisions on which codes to retry, being able to provide it via configuration would be ideal.

**Comment by mrocklin** [comment]
Yup, that seems sensible to me.  The current code looks like this:

```python
def _download_module(url: str) -> ModuleType:
    logger.info("Downloading preload at %s", url)
    assert is_webaddress(url)

    request = urllib.request.Request(url, method="GET")
    response = urllib.request.urlopen(request)
    source = response.read().decode()

    compiled = compile(source, url, "exec")
    module = ModuleType(url)
    exec(compiled, module.__dict__)
    return module
```

(sorry for urllib, we're trying to not include requests as a dependency just for this, and this part of the code should avoid async for various reasons).  

I'm happy to make this change.  However, I don't have a good way to simulate these behaviors.  Do you happen to know of a service that will give me the right response codes?  

I have an attempt at a PR in https://github.com/dask/distributed/pull/5982 .  If you have a chance to give that a try and provide feedback that would be welcome

**Comment by shughes-uk** [comment]
I haven't used it but https://mock.codes/ ? I usually use mocking to test retry/backoff behavior.

https://github.com/litl/backoff is a nice example of implementations of expo backoff (MIT License if you can't add it as a dependency)
