### ISSUE TITLE
Intermittent testing hangs

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#599]
These show up infrequently
- [ ] distributed/tests/test_client.py::test_iterator_gather
- [ ] distributed/tests/test_joblib.py::test_simple
- [ ] distributed/tests/test_ipython.py::test_start_ipython_scheduler 
- [ ] distributed/tests/test_stress.py::test_stress_scatter_death 
- [ ] distributed/deploy/tests/test_adaptive.py::test_adaptive_local_cluster_multi_workers

**Comment by pitrou** [comment]
I managed to reproduce the test_joblib under the pytest-timeout plugin. Here is the output (log + stack traces). Weirdly, it looks like there's a deadlock in Tornado's IO loop over the callback lock...
https://gist.github.com/pitrou/c406b81a4c0cc0e04335604ec9443029

**Comment by pitrou** [comment]
(method to reproduce:
`py.test -v -x --timeout-method=thread --timeout=6 --count=1000 distributed/tests/test_joblib.py`
you'll need the pytest-timeout and pytest-repeat plugins)

**Comment by mrocklin** [comment]
Didn't know you could get that kind of output.  That's handy.  

@ogrisel do custom joblib backends use multiple threads?  Which methods are possibly called concurrently?

**Comment by pitrou** [comment]
it may be a bug or limitation in Tornado too. According to [this](https://github.com/leporo/tornado-redis/issues/59), `add_callback` is not reentrant and deadlocks when the lock is taken again...

**Comment by pitrou** [comment]
Ok, I determined that it is indeed a deadlock in Tornado's `add_callback` due to reentrant invocation through a `__del__`. See the following traceback excerpt:

```
  File "/home/antoine/distributed/distributed/joblib.py", line 54, in apply_async
    future = self.client.submit(func, *args, **kwargs)
  File "/home/antoine/distributed/distributed/client.py", line 643, in submit
    loose_restrictions, priority={skey: 0})
  File "/home/antoine/distributed/distributed/client.py", line 1241, in _graph_to_futures
    'priority': priority})
  File "/home/antoine/distributed/distributed/client.py", line 345, in _send_to_scheduler
    self.loop.add_callback(self.scheduler_stream.send, msg)
  File "/home/antoine/tornado/tornado/ioloop.py", line 964, in add_callback
    stack_context.wrap(callback), *args, **kwargs))
  File "/home/antoine/tornado/tornado/stack_context.py", line 278, in wrap
    null_wrapper._wrapped = True
  File "/home/antoine/distributed/distributed/client.py", line 222, in __del__
    self.release()
  File "/home/antoine/distributed/distributed/client.py", line 210, in release
    self.client._dec_ref(tokey(self.key))
  File "/home/antoine/distributed/distributed/client.py", line 441, in _dec_ref
    self._release_key(key)
  File "/home/antoine/distributed/distributed/client.py", line 452, in _release_key
    'client': self.id})
  File "/home/antoine/distributed/distributed/client.py", line 345, in _send_to_scheduler
    self.loop.add_callback(self.scheduler_stream.send, msg)
  File "/home/antoine/tornado/tornado/ioloop.py", line 959, in add_callback
    with self._callback_lock:
```

**Comment by pitrou** [comment]
https://github.com/tornadoweb/tornado/pull/1875 fixes the test_joblib hang here.

**Comment by mrocklin** [comment]
Oh man, I *really* appreciate having you work on Dask :)

**Comment by ogrisel** [comment]
> @ogrisel do custom joblib backends use multiple threads? Which methods are possibly called concurrently?

Yes: it's using the async callback to schedule more tasks upon completions of the first tasks (that can also get scheduled by consuming the task iterator from the main thread).

**Comment by ajdavis** [comment]
Hi. @pitrou's pull request seems sane. However, it seems like it should be the responsibility of all Tornado users, and all Python programmers, not to take a lock in a `__del__` method for this exact reason.

I noticed last year that destructors must not take locks:

https://emptysqua.re/blog/pypy-garbage-collection-and-a-deadlock/#what-to-expect-when-youre-expiring

So, if we accept the pull request, that will save Tornado from other libraries that take locks in destructors. But I think that this is working around a problem that is fundamental to Python: if there is any code in the entire program that takes a lock from `__del__`, then any code that takes that lock must disable the GC. This doesn't seem like a maintainable strategy.

**Comment by pitrou** [comment]
In a broader view, it is true that `__del__` being called asynchronously at any possible point (and in any possible Python thread) means doing non-trivial stuff in `__del__` is fraught with danger. Yet there are reasons to do so, such as managing distributed objects and having to clean up when a local proxy dies. It is difficult to redo the entire architecture of a library to avoid such side effect code in `__del__`, especially that would result in user-visible regressions in functionality.

**Comment by ajdavis** [comment]
Yes it *is* hard to redo the architecture! We had this problem in PyMongo, and chose to defer any destruction that would require a lock to a periodic background thread ([PYTHON-799](https://jira.mongodb.org/browse/PYTHON-799)). It was complicated.

Let's wait for @bdarnell to review the Tornado pull request, I'm a co-maintainer but I think this is too deep in Tornado for me to decide without Ben.

**Comment by pitrou** [comment]
Yes, a background thread may be a good solution, but it is far from trivial (since a `__del__` can be called from anywhere, how do you ensure you synchronize properly with the background thread? you may end up disabling the GC at points after all...).

**Comment by mrocklin** [comment]
@pitrou are you able to isolate what code in dask/distributed is triggering this?

We're actually fairly clean about only touching the tornado event loop within it's thread or through using `IOLoop.add_callback`.  I'm looking at this now and it appears that we *do* call `Event.clear` in something called by `__del__`.  This is an oversight and can be corrected.

**Comment by pitrou** [comment]
Well, the traceback above shows that it's the decref'ing in `Client.__del__`.

**Comment by mrocklin** [comment]
OK, my *guess* is that we can resolve this locally with the following change in client.py:

```diff
-            self.client._dec_ref(tokey(self.key))
+            self.client.loop.add_callback(self.client._dec_ref, tokey(self.key))
```

I apologize for not taking a closer look at this earlier.

However, the proposed change in Tornado may still be a good one even without our immediate need.

**Comment by pitrou** [comment]
Unless I'm misunderstanding your suggestion, that wouldn't fix it, since our problem is precisely a deadlock when calling `add_callback` from `__del__`.

**Comment by mrocklin** [comment]
Ah, well then I'l retract my suggestion

**Comment by ajdavis** [comment]
The background-thread technique is this:

* Make a global list of cleanup tasks.
* Start a background thread when the library is initialized.
* The thread wakes once per second and checks the list of cleanup tasks.
* In an object's `__del__`, do `cleanup_tasks.append(... info about the task ...)`.
* When the thread next wakes, it does:

```
# Other threads or the GC may append to the queue concurrently.
tasks_copy = []
while True:
    try:
        info = cleanup_tasks.pop()
    except IndexError:
        break

    tasks_copy.append(info)

for info in tasks_copy:
    do_some_cleanup(info)

# Now sleep for a second
```

In your scenario, I think `do_some_cleanup` would be a call to `IOLoop.add_callback`, which would be safe because it's not being called from any  `__del__` method.

**Comment by pitrou** [comment]
Thanks for the info. I think one could be a bit smarter to avoid periodic wakeups (perhaps write a byte on a dedicated fd to wake the background thread?).

**Comment by pitrou** [comment]
As another comment, one problem with the background thread approach is that it makes it difficult to not resurrect the object after `__del__` (you can't wait for the async cleanup to happen, otherwise you fall back on the deadlock issue).

**Comment by pitrou** [comment]
https://github.com/tornadoweb/tornado/pull/1876 was merged in Tornado. It removes the test_joblib hang here.

**Comment by pitrou** [comment]
Note we still may want to try out the background thread approach, at least where it's possible to do so (especially for people who have an older Tornado). I have some work-in-progress code which does that.

**Comment by mrocklin** [comment]
Starting a new issue.
