### ISSUE TITLE
Ways in which inter-worker communication could improve

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#602]
Some computations are bound by worker-to-worker data movement.  This is broken down into a few components:
1.  Serialize objects
2.  Compress messages
3.  Put bytes onto socket (using Tornado)
4.  Pass bytes along a wire (pure hardware)
5.  Decompress and deserialize

We do a decent job at all of these stages, but there is room for improvement.
### Serialization

Currently we serialize data with `pickle`.  

In the case of Python objects this can be slow.  When it would fit, msgpack would generally be faster.

In the case of numeric data (numpy, pandas) this is generally fairly fast, although does incur two memory copies when, ideally, we should be able to serialize metadata and then pass along the bytes buffer directly with zero copies.

In the case of Pandas with text data Pickle is quite slow.  It might make sense to check if all of the "objects" are in fact text and then do something better ourselves.
### Compress messages

Currently we use LZ4 if we think it will be helpful.  This works fairly well for most cases.  We could improve this by specializing compression solution based on the type of the data.  

We might consider using multi-threaded compression like Blosc.  Historically I've avoided multi-threaded compression because we generally already use multiple cores.  However in communication heavy workloads where this is likely to be a bottleneck our machines are rarely firing on all CPUs.
### Put bytes onto socket

Tornado incurs an extra memory copy here that could be avoided if we were to make some changes upstream.
### Reasons not to do any of this

Currently things are pretty simple and work pretty well.  Any solution here would be judged both on performance improvements and on increased code complexity and maintainability.

**Comment by jakirkham** [comment]
I think most of these things have been done today. Would you agree Matt? If so, I think we can close this out.
