### ISSUE TITLE
Observing the state of the cluster

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#603]
Hello :-)

Is there a simple way to observe the state of the whole cluster (mainly worker task load, cpu/memory usage etc.) programatically without using the web (Bokeh) interface?

We're launching our tasks on a big cluster and it's not convenient/possible to use the web interface on it. I know that `Client` has the `scheduler_info` method, but that doesn't have much useful information in this regard. The only other thing that I found is the `distributed.diagnostics.progress` method, but that only shows the progress and it's not useful for me because it blocks until all of the futures are completed (I'm using `as_completed` to iterate on the completed futures one by one).

**Comment by mrocklin** [comment]
There are a variety of functions to get low-level information about the scheduler such as `Client.processing`, `Client.ready`, etc...  There are also the JSON status routes exposed over HTTP: https://github.com/dask/distributed/blob/master/distributed/http/scheduler.py

You could also look at the bokeh diagnostics code itself, which has to get all of its information from the scheduler just as you would have to.  Everything is available either by http or tcp.  The Bokeh server doesn't share a process with the scheduler, and so is in your same position.

Unfortunately, little of this is properly documented.  You'll have to rely on code samples and docstrings to navigate.

**Comment by Kobzol** [comment]
I totally missed the `processing` function, that seems like it will be very useful, and the samples are very clear, I'm sure that will be more than enough for my needs. Thank you very much :-)

**Comment by mrocklin** [comment]
It is intentionally not very well advertised.

**Comment by Kobzol** [comment]
The `distributed.diagnostics.workers` method is **exactly** what I need, however I now noticed that I need a `Scheduler` object to pass to it. Is there any way to access this kind of information (in particular the data from the `Scheduler.host_info` function) when I have a `Client` that is connected to a remote cluster and only has a RPC handle to the scheduler?

I looked at the Bokeh interface source code and (if I'm not mistaken), it uses the REST JSON routes to access that information.
Is there a way to get that data (for example something similar to `/workers.json` or the `host_info` function) directly through the `Client's` RPC, without the need for a separate TCP connection to the scheduler's REST interface?
Sorry if it's a stupid question, I haven't worked with RPC in Python much.

**Comment by mrocklin** [comment]
The `feed` function will run an arbitrary function on the scheduler and send you back the results.  You'll have to become familiar with tornado coroutines though.  The `eventstream` function in `distributed/diagnostics/eventstream.py` is a good example.

This isn't intended to be user facing, so you'll have to do a bit of work.
