### ISSUE TITLE
Drop Mac Python 3.9 builds?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#6040]
Our OSX CI queue is often backed up, especially during US working hours.  Our tests are not very sensitive to Python versions.  I propose that we drop the 3.9 builds and keep 3.8 and 3.10. 

Thoughts?  cc @crusaderky @fjetter @graingert

**Comment by crusaderky** [comment]
Leaving everything else untouched, I don't think it's a wise idea. It's not just about python version.
- 3.8 is the only cythonized one
- 3.9 is the only one with CUDA
- 3.10 is the only one with several libraries at their git tip

We could move CUDA to 3.8 or 3.10 though.

**Comment by fjetter** [comment]
OSX is not a production OS but rather a developer OS and I would be perfectly fine to not test against all dependencies, cython, etc. Having the minimal set running would be OK for me. I can't remember hitting an OSX specific problem, so far.

**Comment by crusaderky** [comment]
> OSX is not a production OS but rather a developer OS

It's production for the Client

**Comment by mrocklin** [comment]
I propose that we move CUDA to 3.8 and drop 3.9

Also, I don't know anyone who has an NVIDIA card on an OSX machine :)
