### ISSUE TITLE
Revert cythonization

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#6086]
Following the Dask community meeting, we decided to close https://github.com/dask/distributed/pull/5839 and remove cython from the current scheduler, reverting the State refactor, CI, etc. along the way. This issue is to track the fact that we want to do this, and hopefully a PR will follow by someone.

**Comment by jrbourbeau** [comment]
Closing in favor of https://github.com/dask/distributed/issues/5685 to keep this conversation in a single thread
