### ISSUE TITLE
API extensions to better support ETL-like workflows

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#612]
Continued discussion from dask/dask#1608

Just a placeholder for now, content still to come...

**Comment by dhirschfeld** [comment]
I have a number of ETL workflows which look similar to the below:
```python
from typing import Dict, List

def extract(filename: str) -> pd.DataFrame:
    # load file
    # process file
    return df


def transform(frame: pd.DataFrame) -> List[Dict[str, object]]:
    # normalise data
    # convert to records
    return records


def load(records: List[Dict[str, object]]) -> int:
    # load records into database
    return rowcount
```
Each operation is chained after the next so an ETL job becomes something like:
```python
etl = lambda filenames = list(map(load, map(transform, map(extract, filenames))))
etl(glob.glob('*.csv'))
```
The distributed equivalent of this is straightforward:
```python
def etl(filenames, *, client):
    futs = client.map(extract, filenames)
    futs = client.map(transform, futs)
    return client.map(load, futs)
```
...where the magic of `client.map` automatically *unboxes* the futures so the ETL functions don't need to be rewritten to handle futures.

This distributed version returns immediately and the scheduler will take care of efficiently chaining all the tasks together. This is great as the calling application which kicked off the job can continue on immediately and respond to other events while the possibly long-running and CPU intensive etl job carries on in the background on a cluster.

The problem with both approaches above is that a failure of any single task will kill the whole job whereas it would be preferable to retry a task in the event of a failure in case it was an intermittent failure and if it was an actual failure, to be notified of the fact whilst all other tasks continued on to completion.

Because distributed unboxes the futures and unboxing will raise exceptions from failed tasks it makes it difficult to deal with any failures.

One way I'm dealing with this is by using `add_done_callback` but this method doesn't return a future so makes it difficult to use in a data processing chain and also IIUC it runs the callback in the local process rather than on the distributed cluster so computationally expensive callbacks could overload the calling process.

I think what's needed is the ability to tell `map/submit` to not unbox the futures - i.e. that the passed function expects to get the futures themselves rather than their results - that way the function can deal with any failed tasks itself - e.g. the signatures would become:
```
client.submit(func, *args, unbox=True, **kwargs)
client.map(func, *args, unbox=True, **kwargs)
```

**Comment by mrocklin** [comment]
> The problem with both approaches above is that a failure of any single task will kill the whole job whereas it would be preferable to retry a task in the event of a failure in case it was an intermittent failure and if it was an actual failure, to be notified of the fact whilst all other tasks continued on to completion

It should only cause those tasks that depend on the failure to stop.  Dask doesn't have any notion of any sort of collection-of-tasks (like a spark stage or a spark job).  Dependencies won't run, but your computations aren't that dependent.  

Retries could be done (https://github.com/dask/distributed/issues/391) but aren't available yet.  Contributions would be welcome here (I don't think this would be too hard but does require going into the scheduling code).  You could also handle this on the user side with something like the following:

def retry(n, exceptions=Exception):
    def _(func):
        @functools.wraps(func)
        def new_func(*args, **kwargs):
            for i in range(n):
                try:
                    return func(*args, **kwargs
                except exceptions:
                    if i >= n: 
                        raise
                    else:
                        continue
        return new_func

    client.map(retry(5)(func), ...)
```

Rather than add_done_callback you might also consider `as_completed` or, if you're comfortable, the torando API.

**Comment by dhirschfeld** [comment]
Thanks for the link to #391. In the interim I had envisaged exactly the decorator you posted above! The only issue with that is that it doesn't allow for niceties such as re-scheduling the task on another worker but it's definitely a sufficient workaround for now.

I don't think I can use `as_completed` to do what I want because AFAICS it will block the calling process and it can't be scheduled on a distributed worker because it accepts futures and the futures would have already been unboxed if it was passed to `client.map/submit`?

On the premise that a decent example is better than 1000 hand-wavy explanations I've created a toy example where I try to handle failed tasks:

https://anaconda.org/dhirschfeld/distributedetl/notebook

The only way I could see to do this was with a complicated wrapping/unwrapping of the functions - is there currently any better way to handle failed tasks?

I also show a *much* cleaner workflow which would be enabled if `map/submit` had an `unbox=False` option. Is that something that's technically feasible to add? Would it be difficult to do so? My tornado isn't up to much but I could certainly give it a go...

**Comment by mrocklin** [comment]
You could also resolve this problem with a few `worker_client`s and channels.  http://distributed.readthedocs.io/en/latest/channels.html#example-with-worker-client

You could use the Tornado version of `_as_completed`, or generally handle this with tornado coroutines by waiting on all of the futures until they complete (one way or the other) and then submitting the final call from the main client once all of the intermediate tasks have finished.  This does require an understanding of async programming though.

**Comment by dhirschfeld** [comment]
The below re-implementation of submit seems to do what I'm after:
```python
def submit(func, *args, client, unbox=True, **kwargs):
    from distributed import worker_client
    from distributed.client import Future
    if unbox:
        return client.submit(func, *args, **kwargs)
    assert all(isinstance(arg, Future) for arg in args)
    keys = [fut.key for fut in args]
    def call_boxed(func, keys):
        with worker_client() as client:
            args = (
                Future(key, client)
                for key in keys
            )
            return func(*args)
    return client.submit(call_boxed, func, keys, **kwargs)
```

**Comment by dhirschfeld** [comment]
`distributed` has moved on so I'll close this as I'm not sure it's relevant anymore.

I'm going to rewrite my ETL code using some of the newer features so will open issues or SO questions if any problems arise with that...
