### ISSUE TITLE
Worker state machine silently ignores bad transitions

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#6133]
```python
@gen_cluster(client=True)
def test_bad_transition(c, s, a, b):
    future = c.submit(inc, 1)
    await future
    ts = a.tasks[future.key]
    a.transition(ts, "foo", stimulus_id="bar")
```

This passes.  It also passes if I send in a real finish state but one that doesn't make sense (like "flight" from "memory").  The current behavior is that it transitions to find a path through "released", but once it gets there it's fine losing the stated final state.

I ran into this trying to make a test for bad behavior (I want to log everything in scheduler events) and found it odd.  Hopefully this never happens, but probably we should be aware of it.

**Comment by mrocklin** [comment]
cc @fjetter @crusaderky

**Comment by fjetter** [comment]
> This passes

It should raise a `InvalidTransition`

> I want to log everything in scheduler events

For production or for a testing setup? These will be way too many messages for the scheduler events in any production environment

**Comment by fjetter** [comment]
This has been added and should now raise an Exception
