### ISSUE TITLE
Test fixtures gen_cluster gen_test are using asyncio.run

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6164]
- [x] https://github.com/dask/distributed/pull/6170
- [ ] https://github.com/dask/distributed/pull/6196
- [ ] avoid pristine_loop/loop.start in loop_in_thread
- [ ] clear asyncio loop in clean - rather than using pristine_loop - asyncio.set_event_loop(None)

**Comment by graingert** [comment]
* avoid pristine_loop/loop.start in loop_in_thread
* clear asyncio loop in clean - rather than using pristine_loop - `asyncio.set_event_loop(None)`
