### ISSUE TITLE
distributed hijacks the logger

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#618]
Simply importing the Client will muck with my logging setup - is it using the root logger?

Will try to add a repro in the morning...

**Comment by mrocklin** [comment]
Hrm, we do do this:

```python
logging.basicConfig(format='%(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)
```

Presumably we should be doing this on `logging.getLogger('distributed')` instead?

**Comment by dhirschfeld** [comment]
Yes, I think so. If you point out the line I can monkey-patch my local version and report back (tomorrow)

**Comment by mrocklin** [comment]
distributed/utils.py around 362

**Comment by dhirschfeld** [comment]
Cheers, will let you know if that fixes it for me...

**Comment by dhirschfeld** [comment]
![image](https://cloud.githubusercontent.com/assets/881019/19950041/e55ae50a-a1a0-11e6-8954-ed10bfc54f0c.png)
...so it looks like it mucks with the root logger. I Am Not A Logging Expert but I'm not sure that a good thing to do. Quite likely I should be doing something to protect my logging from another application calling `basicConfig`. 

In any case PR #623 seems to fix the issue for me...
