### ISSUE TITLE
Waiting on tasks on workers that no longer exist

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#6198]
I was chatting with @bnaul today.  He's run into a stuck cluster and has an interesting situation.

The cluster is mostly done with everything, but there are about 100 tasks yet to complete.  However currently nothing is running them.

![Screen Shot 2022-04-25 at 1 52 36 PM](https://user-images.githubusercontent.com/306380/165154881-ed25cab6-0b26-43a3-994d-420b901a616d.png)

Looking at info pages it looks like there are a few tasks in the processing state

![Screen Shot 2022-04-25 at 1 53 04 PM](https://user-images.githubusercontent.com/306380/165154938-92127f89-91d8-49c8-983f-58ea12049d41.png)

Interestingly these tasks already know their type, so presumably they've run to completion before.

Also interestingly, if I click on the worker page processing that task I get a 404, meaning that the worker is no longer in the scheduler state.

Somehow, the scheduler thinks that a task is running on a worker that no longer exists.

I tried getting a story out of the scheduler, but got no results.  I suspect that this is because we've run past the deque length.  I've asked @bnaul to increase the length to infinity and we'll try again the next time there is a failure.

cc @fjetter

**Comment by gjoseph92** [comment]
My guess is that this is the same as https://github.com/dask/distributed/issues/6263#issuecomment-1128390113.

**Comment by fjetter** [comment]
@gjoseph92 IIUC we currently assume this should be closed by https://github.com/dask/distributed/issues/6356?

**Comment by gjoseph92** [comment]
By whatever fixes #6356, yes
