### ISSUE TITLE
Don't block event loop in `Worker.close` waiting for executor to shut down

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6239]
https://github.com/dask/distributed/blob/1cbee7f18717f060c65b2ac44445745135c8dd46/distributed/worker.py#L1517-L1521

`shutdown` is a blocking call that generally calls `join` on the thread/process. If the executor takes a long time to shut down (say there's a function running that's itself blocked on something), this can block the worker event loop for 30s, or whatever the timeout is.

This is particularly important for our test suite, because the worker event loop is actually the _only_ event loop.

I discovered this trying to run a test something like

```python
event = distributed.Event()
f = client.submit(event.wait, workers=[a.address])
t = asyncio.create_task(a.close())
await asyncio.sleep(1)
await event.set()  # this hangs!
# because the whole event loop is blocked waiting for the ThreadPoolExecutor to shut down,
# which is waiting for the event to be set... which is waiting for the event loop to be free
```

This _probably_ won't affect real-life clusters that much, but would be good to clean up.

cc @graingert

**Comment by mrocklin** [comment]
See also https://github.com/dask/distributed/pull/6091 maybe
