### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by jreback** [dask/distributed#624]
Minor issues / suggestions for the UI, on the workers tab

![image](https://cloud.githubusercontent.com/assets/953992/19965008/59566278-a19b-11e6-9b25-fd003c7295ba.png)

- ``host`` field appears to be too small to contain the 'host' (which is an ip address), it can be resized, but should be wider
- would rename ``host`` to the ``hostname``, and make an ``ip address`` field (maybe have a way to select these via some configuration options)
- would add a top summary line that rolls up the numbers (e.g. number of hosts, total cores, process, memory, avg cpu use, avg memory use)

**Comment by jreback** [comment]
To be honest I find the workers tab top 2 panes (Processing and Pending / Memory Usage) pretty useless.

In an ideal world. I would remove those. Instead make it so you can click on the bottom table and show the history of a specific machine for memory / cpu.

Further might shade the hosts table with high memory usage / cpu (so that you know what to click on!)

**Comment by quasiben** [comment]
In latest viz, host is now address and, on the worker pane, it provides summary stats on number of workers, threads, etc.  We are trying to improve avg/max/min resource usage and we are tracking that in this issue: https://github.com/dask/distributed/issues/4494
