### ISSUE TITLE
Ensure TaskState instances are released on Scheduler and Worker

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6250]
There are strong references on our TaskState instances, Scheduler and Worker instances

See for instance https://github.com/dask/distributed/pull/6246

We should ensure that TaskState is are properly cleaned up

- There is a test in Scheduler.validate that ensure TaskState instances are properly released https://github.com/dask/distributed/pull/6226#issuecomment-1113086051
- `utils_test.check_instances` verifies that there are no leftover Scheduler, Worker, Nanny or TaskState instances

Caveat: This depends on the profiler thread so we may need to relax the above tests and replace them with a more robust, less strict version as appropriate

https://github.com/dask/distributed/pull/6246

- [ ] https://github.com/dask/distributed/pull/6336
- [ ] https://github.com/dask/distributed/pull/6344
- [ ] https://github.com/dask/distributed/pull/6345

**Comment by gjoseph92** [comment]
I don't believe this was fully closed; https://github.com/dask/distributed/pull/6525 was just the first step to being able to track it.
