### ISSUE TITLE
P2P shuffle returns incorrect results if errors occur receiving data (also asyncio tasks are leaked)

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6277]
If an error occurs deserializing, regrouping, serializing, or writing data to disk, and the shuffle isn't in "backpressure mode", that data will simply be lost and the shuffle will still succeed
https://github.com/dask/distributed/blob/7bd64425225af4847e2fbf045df31fb60a253e7d/distributed/shuffle/shuffle_extension.py#L252-L258

When `task` isn't awaited, the asyncio task is leaked. Any error that occurred in it is also lost (besides being logged).

@graingert and I tried to fix this, but we couldn't get something working:
* The dumb way (keep leaking tasks, wrap all of `receive` in a try/except, set `self._exception`, raise `self._exception` in `add_partition`, `get_output_partition`, `inputs_done`) fails tests because of leaking tasks
* The "proper" asyncio way causes a CancelledError to pop out in some unexpected place and seems to shut down the whole worker?

xref #6201

**Comment by fjetter** [comment]
should be fixed after https://github.com/dask/distributed/pull/7268
