### ISSUE TITLE
Cannot serialize datetime64/timedelta64 numpy arrays

### ISSUE THREAD

**Issue by shoyer** [dask/distributed#635]
```
distributed.core - INFO - Unserializable Message: {'finalize-c29ed21fd1e79d8eb6b3ff89cf2ae354': <Serialize: ['2010-01-01T00:00:00.000000000' '2010-01-02T00:00:00.000000000'
 '2010-01-03T00:00:00.000000000']>}
distributed.core - ERROR - cannot include dtype 'M' in a buffer
Traceback (most recent call last):
  File "/Users/shoyer/dev/distributed/distributed/core.py", line 228, in write
    frames = protocol.dumps(msg)
  File "/Users/shoyer/dev/distributed/distributed/protocol/core.py", line 43, in dumps
    for key, value in data.items()
  File "/Users/shoyer/dev/distributed/distributed/protocol/core.py", line 44, in <dictcomp>
    if type(value) is Serialize}
  File "/Users/shoyer/dev/distributed/distributed/protocol/serialize.py", line 103, in serialize
    header, frames = serializers[name](x)
  File "/Users/shoyer/dev/distributed/distributed/protocol/numpy.py", line 58, in serialize_numpy_ndarray
    frames = [x.data]
ValueError: cannot include dtype 'M' in a buffer
```

The buffer protocol fails on these (sigh). You can view as int64, but then you'll need to keep track of the original type (including time units) separately.

This came up in some of my integration tests with xarray.

**Comment by mrocklin** [comment]
Thanks for the bug report.  We've been playing catch up with numpy dtypes ever since the serialization change.  See https://github.com/dask/distributed/pull/630

Should be doable to fix.  Can you think of any other cases that might arise that are not yet tested?

https://github.com/dask/distributed/blob/master/distributed/protocol/tests/test_numpy.py

**Comment by shoyer** [comment]
Looks like you're also missing complex and boolean.

**Comment by mrocklin** [comment]
Thanks.  Fixing datetimes now.  Common case seems trivial (view doesn't copy, right?).  Struct case is slightly more of a pain.
