### ISSUE TITLE
`distributed/tests/test_asyncprocess.py::test_signal` flaky

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6393]
https://github.com/dask/distributed/runs/6513746712?check_suite_focus=true

as part of https://github.com/dask/distributed/pull/6381

running into an async test timeout

**Comment by crusaderky** [comment]
I'm getting a new error:
https://github.com/dask/distributed/pull/6633/checks?check_run_id=7150089143

```
>       assert proc.exitcode in (-signal.SIGTERM, 255)
E       assert -9 in (-15, 255)
E        +  where -9 = <AsyncProcess SpawnProcess-220>.exitcode
```
I cannot understand how the process received SIGKILL after we sent SIGTERM :man_shrugging:

**Comment by fjetter** [comment]
There are a couple of places we are issuing a SIGKILL

- Worker [memory_monitor](https://github.com/dask/distributed/blob/c992f808eefc93b8044b0bddf570495bfecdb162/distributed/worker_memory.py#L381)
- A couple of error handlers in nanny https://github.com/dask/distributed/blob/c992f808eefc93b8044b0bddf570495bfecdb162/distributed/nanny.py#L672-L681
- Lastly, while shutting down the nanny, if the worker process didn't close in time https://github.com/dask/distributed/blob/c992f808eefc93b8044b0bddf570495bfecdb162/distributed/nanny.py#L774

The last item on this list reminds me of https://github.com/dask/distributed/issues/6493#issuecomment-1168934483 where I was also finding a worker not closing as expected

**Comment by fjetter** [comment]
Turns out, the AsyncProcess also has a finalizer that is terminating the process. I do not see any logs in the failing CI, though

https://github.com/dask/distributed/blob/c992f808eefc93b8044b0bddf570495bfecdb162/distributed/process.py#L363-L369
