### ISSUE TITLE
dask.callbacks.Callback

### ISSUE THREAD

**Issue by lintusj1** [dask/distributed#642]
Hi,

I would like to use the `dask.callback.Callback` interface with distributed (as explained here http://dask.pydata.org/en/latest/diagnostics.html). Is this in plans or what is your take on it?

**Comment by mrocklin** [comment]
See http://distributed.readthedocs.io/en/latest/plugins.html

**Comment by lintusj1** [comment]
Thanks for the reply. This is nice. It would be a bit nicer though, if I could use the same interface regardless of the scheduler.

**Comment by mrocklin** [comment]
I don't disagree with you but unfortunately the schedulers themselves are quite different.
