### ISSUE TITLE
future.result() freezes in add_done_callback()

### ISSUE THREAD

**Issue by lintusj1** [dask/distributed#647]
Hi,

below is a simplified example of how calling `future.result()` in `add_done_callback` freezes.

```
c = Client()

def sleep():
    time.sleep(2)
    return 1

def cb(f):
    print(f)
    print('Result should be {}'.format(sleep()))
    print('Result was', f.result())

d = delayed(sleep)()
d.compute() # 1

c.compute(d).result() # 1

f2 = c.compute(d)
f2.add_done_callback(cb)
# <Future: status: finished, type: int, key: finalize-e24717a1ea49f34025d9f69a8d4b9e3e>
# Result should be 1
```

You never get the `f.result()` in `cb`. Execution freezes.

**Comment by pitrou** [comment]
`add_done_callback` schedules the callback to run in the event loop, so you cannot use `f.result()`, which will block synchronously. Instead you must the coroutine API `f._result()`:

```
@gen.coroutine
def cb(f):
    print(f)
    res = yield f._result()
    print('Result was', res)

# [...]
f2.add_done_callback(cb)
```

**Comment by lintusj1** [comment]
Ok, thank you!

**Comment by lintusj1** [comment]
By the way, would `del f` be safe in the callback `cb`

**Comment by pitrou** [comment]
`del f` would probably be safe, but would also not achieve anything particular.

**Comment by mrocklin** [comment]
http://stackoverflow.com/questions/40477518/how-to-get-the-result-of-a-future-in-a-callback/40477862#40477862

**Comment by lintusj1** [comment]
So how would one be able to mark that the scheduler can free the data pointed by the future in the callback?

@mrocklin I see it was already asked :)

**Comment by mrocklin** [comment]
http://distributed.readthedocs.io/en/latest/memory.html

**Comment by lintusj1** [comment]
Yes, `del f` is what I wish to do in the callback, I was just confused by:

> pitrou commented 3 hours ago
> del f would probably be safe, but would also not achieve anything particular.

So I wasn't sure if `del f` would work in the callback since e.g. `result()` would not.
