### ISSUE TITLE
Test Report no longer available

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#6511]
Dask published a test report here: https://www.dask.org/distributed/test_report.html .  With the new webpage update this returns a 404 .  Probably just needs a tweak in cloudflare.

cc @fjetter @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Sorry about the break. Our DNS for `dask.org` now points to WebFlow instead of GitHub pages so there may be some unexpected consequences. @fjetter @ian-r-rose @crusaderky let me know what needs changing and I'll get it updated.

**Comment by quasiben** [comment]
For now, we can also use raw.githack to get a viewable URL:
https://rawcdn.githack.com/dask/distributed/e9dba8f6c0c5627cc01acb612375c9292920979d/test_report.html

The test report lands in gh-pages as part of a [github workflow](https://github.com/dask/distributed/blob/main/.github/workflows/test-report.yaml)

**Comment by jrbourbeau** [comment]
@jacobtomlinson [here's the GHA workflow](https://github.com/dask/distributed/blob/8faa1cb9f91b5acab5569f73a107378957c45675/.github/workflows/test-report.yaml) where the reports are generated and (currently) being uploaded to GitHub pages

**Comment by ian-r-rose** [comment]
Thanks for flagging @quasiben!

> I wonder if we need any dask.org redirecting here. 

I agree, as long as we are not using gh-pages to host the docs or main page, I see no reason to have the redirect at all anymore.

**Comment by fjetter** [comment]
I noticed that the default gh-pages URL dask.github.io redirects to dask.org Is this intentional?

**Comment by quasiben** [comment]
This was intentional for the previous URL routing.  In the maintainers meeting we suggested simply updating the badge to the githack URL .  if we do that, then we should use https://raw.githack.com/dask/distributed/gh-pages/test_report.html as this will reflect latest changes

**Comment by mrocklin** [comment]
Mostly I want to make sure that there is some easy link that points to the
test report.

**Comment by jacobtomlinson** [comment]
I think most folks access the test report by clicking the badge on the README or via a bookmark. So I'm not concerned about how the link looks.

@ian-r-rose that's a good point, I think if we visit dask.github.io/distributed it redirects us and we don't want that any more. So maybe removing the CNAME will do it.

**Comment by jacobtomlinson** [comment]
xref dask/dask.github.io#56
