### ISSUE TITLE
Version warning is blending client/worker versions

### ISSUE THREAD

**Issue by shughes-uk** [dask/distributed#6536]
The versions warning can currently blend client and worker versions, this can be very confusing. The client should have it's own section

```shell
2022-06-08 19:37:28,036 - distributed.worker - WARNING - Mismatched versions found
+-------------+----------------------+----------------------+---------------------------------------------------+
| Package | This Worker | scheduler | workers |
+-------------+----------------------+----------------------+---------------------------------------------------+
| dask | 2022.05.1 | 2022.05.1 | {'2022.05.1', '2022.05.2'} |
| distributed | 2022.5.1+9.gf4765795 | 2022.5.1+9.gf4765795 | {'2022.5.2+29.gf05c94e4', '2022.5.1+9.gf4765795'}
| +-------------+----------------------+----------------------+---------------------------------------------------+
```
Relevant code

https://github.com/dask/distributed/blob/c3e095fbf6c5821f9a88429f48838b7706e08fb0/distributed/scheduler.py#L3684-L3694

cc @gjoseph92 (he did the work finding it!)

**Comment by shughes-uk** [comment]
FYI this is sometimes causing coiled users to assume coiled has created a 'bad' cluster with different worker versons

**Comment by hendrikmakait** [comment]
After taking a first look, I'd remove https://github.com/dask/distributed/blob/c3e095fbf6c5821f9a88429f48838b7706e08fb0/distributed/scheduler.py#L3689 in general. IMO, all we want to do when checking versions is to check whether the versions of the source, i.e., a client or a worker, match against the versions of the cluster, i.e., the scheduler and all other workers. 

If a worker is added and its versions match against those of the cluster, the cluster is in a consistent state and the worker does not care if it does not match _some_ client. Similarly, a client only cares whether its versions match those of the cluster, not those of another (potentially independent) client.

**Comment by fjetter** [comment]
> After taking a first look, I'd remove

Indeed, that doesn't look very helpful. Took me a while to wrap my head around this. I actually didn't know that we had multiple, subtly different version warnings.

I would also suggest to slightly change this. While the logger _should_ carry this information, I often only see the final table as an error message. Maybe it's worth encoding the worker address in the table (see also OP), i.e. Change `This Worker` to `This Worker {ws['id']}`

**Comment by fjetter** [comment]
I think the only case where "all clients" should be relevant is if somebody explicitly runs `Client.get_versions`. In some cases it is useful knowledge if there is a connected client with wrong versions

**Comment by hendrikmakait** [comment]
> Maybe it's worth encoding the worker address in the table (see also OP), i.e. Change This Worker to This Worker {ws['id']}

Agreed! I'll create a PR that drops the line in question and add some beautification.

**Comment by hendrikmakait** [comment]
> I think the only case where "all clients" should be relevant is if somebody explicitly runs Client.get_versions.

Fair point, interestingly enough that appears to be the one place where we do not do this at the moment. When adding this functionality, I'd add it behind a flag though, to maintain API consistency and because I think that the use case of checking against _all_ other clients feels like it would not be the default here.

**Comment by hendrikmakait** [comment]
Or rather, we may want to change the `check` param from a `bool` to something like `Literal["cluster" | "all"] and always return that additional info
