### ISSUE TITLE
Dashboard reporting of errored tasks

### ISSUE THREAD

**Issue by hayesgb** [dask/distributed#6538]
When debugging failed jobs, it would useful for users to have the ability to investigate the errors of individual tasks that have failed.

Can we add a static dashboard page for erred tasks, that makes exceptions, traceback, and state of the worker during failure available for investigation?

**Comment by mrocklin** [comment]
It looks like we overlapped each other.  I'm going to close in favor of https://github.com/dask/distributed/issues/6539
