### ISSUE TITLE
Flaky tests: `coroutine 'InProc.write' was never awaited`

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6551]
Catch-all issue for flaky tests with tracebacks like
```python
    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object InProc.write at 0x7fd864183ec0>
E               
E               Traceback (most recent call last):
E                 File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/warnings.py", line 506, in _warn_unawaited_coroutine
E                   warn(msg, category=RuntimeWarning, stacklevel=2, source=coro)
E               RuntimeWarning: coroutine 'InProc.write' was never awaited
```

I would imagine there's some core problem that could be fixed to make all these tests work.

Some known failures (feel free to add more in comments):
* https://github.com/dask/distributed/issues/6507
* https://github.com/dask/distributed/issues/6506
* https://github.com/dask/distributed/issues/6451
* https://github.com/dask/distributed/issues/6549 (this one is interesting because it's with a TCP comm, which indicates the problem isn't with InProc but rather with comm handling)
* https://github.com/dask/distributed/issues/6769

@graingert do you have any ideas? Weren't you looking at this at some point?

**Comment by graingert** [comment]
maybe this? https://github.com/python/cpython/pull/31003

**Comment by graingert** [comment]
ah no it's this https://github.com/dask/distributed/blob/96c13a5bc26e67d18cee256c2a110102cef7eac6/distributed/batched.py#L94-L96

**Comment by fjetter** [comment]
xref https://github.com/dask/distributed/issues/6389

**Comment by gjoseph92** [comment]
@graingert and I will write up a ticket or comment on what approach we're going to take here. Refactoring BatchedSend to use asyncio right now may not help/be hard, because we don't have something to hang the long-lived task off of yet. We'll probably just ignore the warning for now.
