### ISSUE TITLE
Indentation in pytest output is strange

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6552]
Recently, the indentation in pytest's output of failing tests has gotten weird. It makes it hard to read the Python code of the test in question. For example, things that look like:
```
_________________________ test_adaptive_killed_worker __________________________
@pytest.mark.slow
@gen_test()
asyncdeftest_adaptive_killed_worker():
with dask.config.set({"distributed.deploy.lost-worker-timeout": 0.1}):
asyncwith SpecCluster(
                asynchronous=True,
                worker={"cls": Nanny, "options": {"nthreads": 1}},
                scheduler=scheduler,
            ) as cluster:
asyncwith Client(cluster, asynchronous=True) as client:
# Scale up a cluster with 1 worker.
                    cluster.adapt(minimum=1, maximum=1)
whilenot cluster.workers:
await asyncio.sleep(0.01)
                    future = client.submit(sleep, 0.1)
# Kill the only worker.
                    [worker_id] = cluster.workers
await cluster.workers[worker_id].kill()
# Wait for the worker to re-spawn and finish sleeping.
>                   await future
distributed/deploy/tests/test_spec_cluster.py:154: 
```
https://github.com/dask/distributed/runs/6692197880?check_suite_focus=true#step:11:1724

Notice the strange indentation and missing spaces.

Has anyone else noticed this? Any idea why it's happening?

@jrbourbeau @crusaderky @fjetter

**Comment by crusaderky** [comment]
Yes I noticed. Did anyone try downgrading pytest?

**Comment by gjoseph92** [comment]
This seems to have resolved itself in the last couple days? I have no idea why.

**Comment by jrbourbeau** [comment]
Yeah, it seems to have resolved itself over in `dask/dask` too. Going to close this out for now. We can re-open as needed
