### ISSUE TITLE
 Make writing performance reports to remote filesystems easier

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#6555]
Earlier today I wanted to upload a performance report to an S3 bucket but then noticed that `performance_report(...)` doesn't have a `storage_options` parameter. This isn't a huge deal as one can just create a performance report locally and then use `s3fs` to upload that local file to S3. That said it would be nice is `performance_report` could handle `s3://`, etc. protocols. 

Similar to https://github.com/dask/distributed/issues/5659

**Comment by ivojuroro** [comment]
Hi @jrbourbeau ! I'd like to work on this if it's ok for you. Do you have any suggestions on how to start? The idea would be to add `storage_options` to the `performance_report` class, right?

**Comment by jacobtomlinson** [comment]
@ivojuroro that's great. Yeah that's right. This PR (#5863) did something similar for cluster dumps so may be good inspiration.

**Comment by ivojuroro** [comment]
@jacobtomlinson Great, I'll check and I'll let you know if how it goes. Thanks !

**Comment by ypogorelova** [comment]
Hi, @ivojuroro are still working on this issue? Would you mind if I take it?
