### ISSUE TITLE
API change in #6363 broke dask gateway

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#6559]
In #6363, a parameter was removed that makes distributed in compatible with Dask Gateway: https://github.com/dask/dask-gateway/pull/573

I'd recommend we restore that parameter and deprecate it. If it's impossible to restore the previous functionality, we could restore the parameter and perhaps ignore it, just for the signature compatibility (I don't know if dask-gateway was relying on the previous behavior).

**Comment by jrbourbeau** [comment]
Looking at the linked `dask-gateway` PR, it looks like removing the `fast=` keyword from `Scheduler.close` is the parameter you're referring to @TomAugspurger. cc @fjetter @gjoseph92 who were actively involved on https://github.com/dask/distributed/pull/6363

**Comment by mrocklin** [comment]
Question, are we doing upstream testing in dask-gateway?  If not, does anyone want to take this on?  (@TomAugspurger ?)

**Comment by jrbourbeau** [comment]
From a functional perspective, looking at the `Scheduler.close` source from an earlier `distributed` release, it looks like `fast=` wasn't actually being used

**Comment by TomAugspurger** [comment]
https://github.com/dask/distributed/pull/6561 has a quick fix up for this.

I'm not sure if dask-gateway is testing against upstream (I didn't see anything at a glance). I might be able to add that this weekend or next.
