### ISSUE TITLE
flaky `test_quiet_close_process[False]`

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6582]
It's possible this has already been fixed in https://github.com/dask/distributed/pull/6567. If we don't see it again for a couple weeks, let's close this. However, I have a feeling the TimeoutError not being retrieved is some other problem.

```
_______________________ test_quiet_close_process[False] ________________________
processes = False
tmp_path = PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_quiet_close_process_False0')
@pytest.mark.parametrize("processes", [True, False])
deftest_quiet_close_process(processes, tmp_path):
withopen(tmp_path / "script.py", mode="w") as f:
            f.write(client_script % processes)
        proc = subprocess.Popen(
            [sys.executable, tmp_path / "script.py"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        out, err = proc.communicate(timeout=10)
assertnot out
>       assertnot err
E       assert not b"Future exception was never retrieved\nfuture: <Future finished exception=TimeoutError('Timeout')>\ntornado.util.TimeoutError: Timeout\n"
distributed/tests/test_client.py:7529: AssertionError
```

https://github.com/dask/distributed/runs/6893247153?check_suite_focus=true#step:11:1378

**Comment by crusaderky** [comment]
I'm now getting a different one:


>       assert not out
E       AssertionError: assert not b'/Users/runner/miniconda3/envs/dask-distributed/lib/python3.10/contextlib.py:142: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.\n  next(self.gen)\n'

**Comment by gjoseph92** [comment]
This happened again in https://github.com/dask/distributed/runs/7412363245?check_suite_focus=true#step:11:1326

**Comment by fjetter** [comment]
This is possibly closed by https://github.com/dask/distributed/pull/6847

**Comment by gjoseph92** [comment]
Still happening: https://github.com/dask/distributed/runs/7999878381?check_suite_focus=true#step:11:1709

**Comment by crusaderky** [comment]
The stdout message is now different from before though:
```

>       assert not out
E       assert not b"Future exception was never retrieved\nfuture: <Future finished exception=TimeoutError('Timeout')>\ntornado.util.TimeoutError: Timeout\n"
```

This test is a canary for all unrelated cleanup and performance problems.
I'm going to build a blacklist of common warnings into it.
