### ISSUE TITLE
distributed.batched - ERROR - name 'timedelta' is not defined

### ISSUE THREAD

**Issue by apiszcz** [dask/distributed#659]
I observed this error a few times:

In the base example range was set to 10000

distributed.batched - ERROR - name 'timedelta' is not defined
Traceback (most recent call last):
  File "/a/a3/lib/python3.5/site-packages/distributed/batched.py", line 65, in send_next
    self.interval)
NameError: name 'timedelta' is not defined

==
from distributed import Client
client = Client('10.0.1.41:8786')

def square(x):
    return x ** 2

def neg(x):
    return -x

A = client.map(square, range(10000))
B = client.map(neg, A)
total = client.submit(sum, B)
total.result()

**Comment by mrocklin** [comment]
This was an brief error in version 1.14.2 released last week.  Suggest that you update to version 1.14.3.

    conda install -c conda forge distributed

or

    pip install distributed --upgrade

**Comment by apiszcz** [comment]
I'm seeing much better results with no errors and no restarts required.
Thank you.
