### ISSUE TITLE
Support Yarn and Mesos

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#66]
Previously I've assumed that interacting with Yarn and Mesos would look like asking Yarn/Mesos to spin up a center/scheduler and then spin up N workers.

Now I'm thinking that perhaps the center/scheduler lives outside of Yarn/Mesos and it instead asks Yarn/Mesos for workers.  

If we go with the second case then we need to think of an appropriate API like

*  Scheduler asks Yarn/Mesos for new Workers (grow cluster)
*  Scheduler tells Yarn/Mesos to retire old Workers (shrink cluster)
*  Yarn/Mesos tell Scheduler that workers have unexpectedly died

What does such an API look like more concretely?  Is there a common abstraction that can be supported by Yarn, Mesos, and possibly other systems like SGE?

cc @hussainsultan @danielfrg @quasiben

**Comment by hussainsultan** [comment]
**Regarding Mesos:** This makes a lot of sense.  My initial effort for making Mesos work together with distributed is based on spinning up scheduler and worker processes that are scheduled on Mesos at coarse grain. This work does not call for a need for a separate framework as you can accomplish all of this with a few commands on Marathon or Kubernetes.  I have a local branch of mesos-distributed that spins up dcenter and dworkers in a docker container as well and coordinates the networking required to make them work.
The next steps for mesos-distributed are to integrate Distributed scheduler with mesos that holds state (perhaps in zookeeper or something like Cassandra) and  coordinate with mesos to spin up the workers (akin to Nanny process) with constraints on where they are run. This has a few benefits:

* Scheduler registers with mesos master as a framework and inherits availability of mesos setup ( multiple masters and slaves)
* Scheduler can easily deploy workers in docker containers which provide a nice API to get usage and statistics which can be exposed in a web ui if needed 
* Easy to work with a consensus system like Zookeeper
* Workers can hold state and recover in case of partitions taking advantage of local file system etc.

The challenge around Scheduler will be how to design it so it can be pluggable and work with Mesos and some consensus system while still maintaining the lightweight goals of Distributed. I believe large parts of this scheduler will be customized for Mesos to deal with framework related things or registering/re-registering and coordinating state. Mesos scheduler can then be run with something like Marathon to ensure that it is restarted when needed; a lot of frameworks for mesos like elasticsearch and Chronos take this approach.

Around the worker, i am not sure how Distributed will evolve to manage its state and that may mean more effort in figuring out how to schedule workers with constraints. To begin with, it will help if dworker could have an option to run without Nanny process; it is trivial to run it at the cost of add a custom script to the docker containers anyway.

Is multi-tenancy a goal for distributed? If so, that may mean a lot more complexity in figuring out worker related scheduling as well.

**Comment by mrocklin** [comment]
I think that integrating `distributed` with resource managers in an agnostic/lightweight manner is exactly the challenge to solve here.  My hope is that we can find the right hooks to expose on either end to design some sort of plugin system where distributed can send a few kinds of signals to the plugin and actively listens for a few kinds signals back.

I think it's possible to build some amount of multi-tenancy strictly within distributed's scheduler, and not rely on logic in Mesos/Yarn.  This wouldn't work in an adversarial setting (in which I send a lot of segfaulting functions on to all of your nodes) but is doable otherwise I think.

**Comment by jseabold** [comment]
Linking to #128.

**Comment by jseabold** [comment]
https://github.com/hussainsultan/mesos-distributed

**Comment by mrocklin** [comment]
Closing in favor of #128
