### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by apiszcz** [dask/distributed#660]
At startup: 

/a/a3/lib/python3.5/site-packages/distributed/bokeh/application.py - INFO -  Bokeh UI at:  http://10.0.1.41:8787/status/

The main page http://10.0.1.41:8787/ displays the applications, however selecting any application returns 500 Internal Server Error.

Is it possible to start bokeh the server with --log-level debug ? 

I do not see it as an option in dask_scheduler.py

            bokeh_proc = BokehWebInterface(host=host, http_port=http_port,
                    tcp_port=port, bokeh_port=bokeh_port,
                    bokeh_whitelist=bokeh_whitelist, show=show, prefix=prefix,
                    use_xheaders=use_xheaders, quiet=False)

**Comment by mrocklin** [comment]
As with #659 recommend that you try updating to 1.14.3

**Comment by kaloramik** [comment]
Seeing this exact behavior as well with 1.14.3

**Comment by kaloramik** [comment]
Actually, I just uninstalled the pip version, and installed the conda version, and it seems to be ok.

```python
conda install distributed
```

**Comment by kaloramik** [comment]
Update: actually it looks like I had a conflicting version of bokeh and Jinja installed in my requirements.txt, after updating both this seems to work
