### ISSUE TITLE
Redundant remove_worker in retire_worker

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6643]
`Scheduler. _track_retire_worker` has keyword arguments that allow us to close and/or remove workers.

During an unrelated debugging session we noticed that this may be redundant and we might want to clean this up. Particularly if `close_workers=True ` we will always trigger a remove_worker as well, regardless of the kwarg. This code section is _also_ marked with a TODO about redundant close calls. Is this intentional?

See https://github.com/dask/distributed/blob/a8eb3b23b8fe91f52758db155e7151e3d516cbdc/distributed/scheduler.py#L3452-L3453

https://github.com/dask/distributed/blob/a8eb3b23b8fe91f52758db155e7151e3d516cbdc/distributed/scheduler.py#L6080-L6087

cc @crusaderky

**Comment by crusaderky** [comment]
CC @gjoseph92 who added the comment about redundancy and has been involved in end-of-life batched comms.

**Comment by crusaderky** [comment]
@gjoseph92 added that comment.

The call definitely looks redundant in production code. A handful of tests call close_worker() without remove_worker() - they should be amended.
