### ISSUE TITLE
Add `flake8-bugbear` as additional `flake8` plugin

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6662]
`flake8-bugbear` ([https://github.com/PyCQA/flake8-bugbear](https://github.com/PyCQA/flake8-bugbear)) is a plugin for `flake8` that contains additional rules aimed at finding likely bugs and design problems in the code. Notable rules include:
* B006: Do not use mutable data structures for argument defaults.
* B018: Found useless expression.

At the time of this writing, adding `flake8-bugbear` spits out 166 problems, most of which are in tests. If we decide to go with `flake8-bugbear`, we could ignore it for tests and clean those up over time before flipping the switch.

**Comment by fjetter** [comment]
+1 I love automated code reviews
