### ISSUE TITLE
Dockerfile startup improvements

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#669]
It seems that the [current `Dockerfile`]( https://github.com/dask/distributed/blob/d05c479f424ec001fd7253006b19d194152e853e/continuous_integration/Dockerfile ) simply starts the services and [sleeps]( https://github.com/dask/distributed/blob/d05c479f424ec001fd7253006b19d194152e853e/continuous_integration/docker-files/start.sh#L10 ). The result is we have to `run` the container and `exec` into it. However, we could combine these two steps by [`exec`-ing]( https://github.com/jakirkham/docker_centos_drmaa_conda/blob/6537b2fdbbad44c553745c8382084955975f423d/docker/entrypoint.sh#L56 ) whatever the user provides as a command. This way one could have the shell start right afterward. If there is interest in this startup method, I'd be happy to write up a simple PR for this behavior.

**Comment by mrocklin** [comment]
I agree that the current solution is suboptimal.  Alternatives would be welcome.

**Comment by pitrou** [comment]
One other issue with the current Dockerfile is that it refuses requests from the host (connecting works but the connection is closed immediately (*)), so you must run the tests inside the container as well (which is what our Travis configuration does, incidentally).

(*)
```
2016-11-16 19:22:09.772020, p8602, th140058011375360, ERROR Failed to setup RPC connection to "localhost:8020" caused by:
TcpSocket.cpp: 127: HdfsNetworkException: Write 91 bytes failed to "localhost:8020": (errno: 32) Broken pipe
2016-11-16 19:22:09.772152, p8602, th140058011375360, INFO Retrying connect to server: "localhost:8020". Already tried 1 time(s)
2016-11-16 19:22:10.823544, p8602, th140058011375360, ERROR Failed to setup RPC connection to "localhost:8020" caused by:
TcpSocket.cpp: 127: HdfsNetworkException: Write 91 bytes failed to "localhost:8020": (errno: 32) Broken pipe
[etc.]
```

**Comment by quasiben** [comment]
All dockerfiles are now in https://github.com/dask/dask-docker -- either jupyterlab blocks or we rely on other services to manage the command, for example, dask-kubernetes

**Comment by jakirkham** [comment]
Yeah it also seems like the setup has totally changed. Not seeing the same limitations we had before
