### ISSUE TITLE
doc page title is confusing

### ISSUE THREAD

**Issue by ntabris** [dask/distributed#6729]
The page that explains all sorts of plugins (Scheduler Plugins, Worker Plugin, even Nanny Plugins!) is titled "Scheduler Plugins". This is confusing.

It affects what's listed in the docs sidebar:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/46289310/179262723-44648e26-cbf0-4234-82e1-e1a49c7a449a.png">

It also affects search results:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/46289310/179262780-ab4aab33-81ef-45bb-9682-f517e83c5faf.png">

For a while I thought "why aren't there any docs about worker plugins?!" but eventually I looked at the "scheduler plugin" page and saw the information I wanted.

**Comment by ntabris** [comment]
cc @scharlottej13

**Comment by jrbourbeau** [comment]
Thanks for pointing that out @ntabris -- agreed that current page title is confusing. I think updating to just "Plugins" would be more clear (possibly adding a sentence or two saying there are different kinds of plugins). @scharlottej13 do you have bandwidth to work on this at the moment? (no obligation)

**Comment by scharlottej13** [comment]
Thanks @jrbourbeau! Happy to make this change.
