### ISSUE TITLE
Flaky tests: `OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 5 s`

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6731]
Catch-all issue for tests failing like `OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 5 s` while the client is trying to connect to the scheduler.

TODO: link other flaky-test issues related to this.

**Comment by windowshopr** [comment]
I'm having this issue currently. I can provide a reproducible code, and some details about my setup. This is an extension of my question [asked on SO here](https://stackoverflow.com/questions/73045121/tpot-and-dask-distributed-only-utilizing-one-worker-machine-when-2-are-connecte), however I figured out that question, now stuck on this `Timed out` issue.

**PROBLEM DESCRIPTION**
I'm trying to utilize a distributed cluster across 2 machines for a TPOT machine learning run. I do not think this is an issue with TPOT but rather with distributed. I'm able to setup my scheduler, and have both machines connect to it and the TPOT run starts, but after 2 minutes I get a timed out error on one of the workers, even though both machines are still processing something.

**ENVIRONMENT**
```
2 x Windows 10 machines/workers
Python 3.7.9
TPOT==0.11.7
scikit-learn==1.0.2
dask==2022.2.0
distributed==2022.2.0
numpy==1.21.4
pandas==1.2.5
```

**NETWORK MAP**
**Machine 1** (Main) - Local IP Address: 172.16.1.113
**Machine 2** (Secondary) - Local IP Address: 172.16.1.82

On both machines, I have opened inbound/outbound rules for ports 8786, and 8789-8795 for communication purposes/to try and mitigate any dumb Windows firewall issues.

**STEPS TO REPRODUCE**
1. Machine 1 - Open PowerShell window (as admin) and run the command `dask-scheduler` to start the scheduler.
2. Machine 1 - Open second PowerShell window (as admin) and run the command `dask-worker tcp://172.16.1.113:8786 --nprocs 1 --nthreads 4 --worker-port=8789`
3. Machine 2 - Open PowerShell window (as admin) and run the command `dask-worker tcp://172.16.1.113:8786 --nprocs 1 --nthreads 4 --worker-port=8789`

So effectively, Machine 1 connects to itself (the scheduler), and Machine 2 connects to machine 1's scheduler. When inspecting `http://localhost:8787/status`, I see both workers connected and ready to go.

4. Run this minimal reproducible code on Machine 1 in another PowerShell window or your IDE of choice. This code closely replicates my real use case, hence the shape and weight imbalances (don't worry about it for now, unless the size of the dataset is too big for your machine, you can downsize if needed, like change to `n_samples=5000`):

```
from dask.distributed import Client, Worker
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from tpot import TPOTClassifier

# ------------------------------------------------------------------------------------------------ #
#                                  START WORKER/CLIENT IN SCRIPT                                   #
# ------------------------------------------------------------------------------------------------ #
client = Client("tcp://172.16.1.113:8786")

# ------------------------------------------------------------------------------------------------ #
#                                    MAKE CLASSIFICATION DATASET                                   #
# ------------------------------------------------------------------------------------------------ #
X, y = make_classification(n_samples=10000,
                           n_features=538,
                           n_informative=200,
                           n_classes=3,
                           weights={0:0.996983388, 
                                    1:0.001515257,
                                    2:0.001501355,
                                    },
                           random_state=42,
                           )

# ------------------------------------------------------------------------------------------------ #
#                                         TRAIN TEST SPLIT                                         #
# ------------------------------------------------------------------------------------------------ #
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.15,
                                                    )
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

# ------------------------------------------------------------------------------------------------ #
#                                    CREATE THE TPOT CLASSIFIER                                    #
# ------------------------------------------------------------------------------------------------ #
tpot = TPOTClassifier(generations=100, 
                     population_size=40,
                     offspring_size=None, 
                     mutation_rate=0.9,
                     crossover_rate=0.1,
                     scoring='balanced_accuracy',
                     cv=TimeSeriesSplit(n_splits=3), # Using time series split here
                     subsample=1.0, 
                    #  n_jobs=-1,
                     max_time_mins=None, 
                     max_eval_time_mins=10, # 5
                     random_state=None, 
                    #  config_dict=classifier_config_dict,
                     template=None,
                     warm_start=False,
                     memory=None,
                     use_dask=True,
                     periodic_checkpoint_folder=None,
                     early_stop=2,
                     verbosity=2,
                     disable_update_check=False)

results = tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_pipeline.py')

# Now check http://localhost:8787/status and resources on both worker machines
```

After a few minutes, both machines get spun up and resources are being used. Here is from Machine 1 (main):

![image](https://user-images.githubusercontent.com/40477419/179914232-d17c3cef-4939-49d1-905e-9ae09e99c430.png)

Now, after 2 minutes (as that is what I set in the `distributed.yaml` config file), on Machine 1's worker PowerShell window (NOT the scheduler window), I get the following traceback:

![image](https://user-images.githubusercontent.com/40477419/179914496-78c80887-3a13-4e79-a8cb-29da178c31df.png)

The timed out message comes back every 2 minutes from then on. Both workers continue working for a while (several minutes, doing the TPOT machine learning stuff), then they spin down, and when I check the TPOT output, it looks like nothing has happened that whole time...

![image](https://user-images.githubusercontent.com/40477419/179915467-3703d5c8-d521-4a93-abb2-effff85207a9.png)

So it just hangs, the scheduler is still going, both workers are still showing up in the dashboard, but the worker PowerShell window on Machine 1 just keeps repeating the timed out message and the TPOT run doesn't progress.

**ACTIONS ALREADY TAKEN**
1. Increasing the default `60s` timeout in the config file, which I increased to `120s` and I COULD increase more, however I'm not 100% sure this is the issue.
2. Specify specific worker ports on both machines `8789`. Have also tried setting 1 worker's port to `8789` and the other to `8790` to mitigate same port issues.
3. Decreased the dataset's size to:
```
X, y = make_classification(n_samples=5000,
                           n_features=150,
                           n_informative=50,
                           n_classes=3,
                           weights={0:0.996983388, 
                                    1:0.001515257,
                                    2:0.001501355,
                                    },
                           random_state=42,
                           )
```
4. Let the script run for an hour, only to come back to TPOT's progress still showing 0% and 0 pipelines tested, and both workers stalled with a bunch of those timed out errors on Machine 1's worker PowerShell window.

I hope this has been detailed enough for reproducibility. I know I'm running TPOT here, but I think it's a distributed issue re: connections timing out in the cluster.

As you can see, I'm sort of new to using distributed with TPOT and running it from the command line/PowerShell, however [the only guide](https://examples.dask.org/machine-learning/tpot.html) on it shows only how to run a local cluster (on one machine) not multiple machines, nor how to help with connections timing out like this.

Would love some input on this!!! I want to crank up both machines to run my TPOT! Thanks!!!!

**Comment by gjoseph92** [comment]
@windowshopr thanks for the detailed report. The issue you're having is different from the one I've opened here. This is about a TimeoutError when clients connect to a scheduler, specifically in CI. The TimeoutError you're seeing (evidenced by the traceback being in `worker.py`, in `gather_dep`) is coming from one worker connecting to the other. It seems your workers are unable to talk to each other, though they're both able to talk to the scheduler.

Could you please re-open a separate issue for your problem, and be sure to include the version of distributed and TPOT that you're using?

**Comment by windowshopr** [comment]
Oh that’s my mistake! Yes I will open a separate issue. I have included my dependency versions in the “environment” section. Thanks!

**Comment by gjoseph92** [comment]
All of these tests are commonly failing with `OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 5 s`:
- https://github.com/dask/distributed/issues/6751
- https://github.com/dask/distributed/issues/6752
- https://github.com/dask/distributed/issues/6395
- https://github.com/dask/distributed/issues/6753
- https://github.com/dask/distributed/issues/6754 (this one failed on Windows, an outlier)
- https://github.com/dask/distributed/issues/6755
- https://github.com/dask/distributed/issues/6759
- https://github.com/dask/distributed/issues/6760
- https://github.com/dask/distributed/issues/6761
- https://github.com/dask/distributed/issues/6762
- https://github.com/dask/distributed/issues/6763
- https://github.com/dask/distributed/issues/6764
- https://github.com/dask/distributed/issues/6765
- https://github.com/dask/distributed/issues/6773

**Comment by gjoseph92** [comment]
This should have been obvious, but I just realized it now: every one of these tests involves running the scheduler in a subprocess with some form of `poen(["dask-scheduler"])` and connecting to it. The majority of them are in `test_dask_scheduler.py`. Those also tend to run at the very beginning of the test suite, so if they were leaking subprocesses or ports or something, they could be affecting most of the subsequent tests.

Also, looking at the stderr output of most tests, they all show `distributed._signals - INFO - Received signal SIGINT (2)`. According to the timestamps, it's often within less than 5s of the scheduler starting. I don't think that's the cause of the problem. Rather, it's probably that inside the `popen` contextmanager in the test code, an exception is being raised (possibly the client connection error?), which causes `popen` to send SIGINT to the subprocess.

**Comment by gjoseph92** [comment]
Current theory is that this is actually really simple:
1. importing pandas (or something else) is especially slow on the macOS runners for some reason
2. it takes more than 5s for the `dask-scheduler` subprocess to be available for a connection
3. the client times out and fails the test

We can reproduce a similar-looking error by trying to launch a Client when there's no scheduler available at all:
```python
def test_wat(loop, requires_default_ports):
    with Client(f"127.0.0.1:{Scheduler.default_port}", loop=loop) as c:
        pass
```
```
...
>           raise OSError(
                f"Timed out trying to connect to {addr} after {timeout} s"
            ) from active_exception
E           OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 5 s

distributed/comm/core.py:317: OSError
================================================================================== slowest 20 durations ==================================================================================
5.00s call     distributed/cli/tests/test_dask_scheduler.py::test_wat
0.01s teardown distributed/cli/tests/test_dask_scheduler.py::test_wat

(1 durations < 0.005s hidden.  Use -vv to show these durations.)
================================================================================ short test summary info =================================================================================
FAILED distributed/cli/tests/test_dask_scheduler.py::test_wat - OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 5 s
```
We can see from the test duration that it actually does wait the full 5s; this isn't one of those cases where the error message claims a timeout happened, but it was actually a CancelledError or something that got converted into a TimeoutError.

FYI, the reason for the 5s timeout, rather than default 30s connect timeout, is that the `loop` fixture depends on the `clean` fixture which uses the `clean` contextmanager which calls `_reconfigure` which [sets](https://github.com/gjoseph92/distributed/blob/007c3f0ec913e639599a54c9eb40bb8cd43cc5ea/distributed/utils_test.py#L1894) `"distributed.comm.timeouts.connect": "5s"`.

**So in theory, just using a longer timeout would probably make these tests pass most of the time.**

But I'm going to try to figure out why scheduler startup is so slow first. Ideally they would not all take 10s each, even on CI runners.

**Comment by gjoseph92** [comment]
In https://github.com/gjoseph92/distributed/pull/4, I ran just the `test_dask_scheduler.py` tests on macOS, [launched a py-spy profiler](https://github.com/gjoseph92/distributed/blob/2c4179cd3785349763fe9b8b9449f0a4db508e56/distributed/cli/tests/test_dask_scheduler.py#L61-L88) to record a number of known offenders, and uploaded the profiles as a test artifact. (I could see this being useful to do again in the future.)

Comparing profiles between flaky tests that failed and ones that didn't on a particular run, there wasn't an obvious difference. I expected something major to stand out, but they looked pretty similar.

- `dask-scheduler` subprocess for a test that failed https://github.com/dask/distributed/issues/6752:

<img width="952" alt="Screen Shot 2022-08-02 at 1 09 03 PM" src="https://user-images.githubusercontent.com/3309802/182454248-48810ec4-04a8-41d4-9b4d-fda82ae627b6.png">

- `dask-scheduler` subprocess for a test that passed https://github.com/dask/distributed/issues/6395:
<img width="952" alt="Screen Shot 2022-08-02 at 1 10 05 PM" src="https://user-images.githubusercontent.com/3309802/182454531-7b72907e-afbc-4134-af94-3a6887c9ef2b.png">

In the second one, you can see the `add_client` (I added a `sleep` in there to ensure it would show up better with the sampling profiler). In the first, it doesn't happen because the client times out. In the successful case, the scheduler was done with imports after ~3.6s. In the failed case, it was done after ~4.1s.

So it seems like slow imports are actually the issue, and they're taking so long that normal variability is putting us right up against our 5s timeout.

## Slow imports
Overall:
- 1.90 seconds of imports at startup (before `dask-scheduler.main` starts running)
- 2.09 seconds to `import distributed.dashboard.scheduler` (1s for pandas, 1s for pure bokeh)

**So with 4s of imports before useful work can happen, a 5s connection timeout indeed seems likely to fail sometimes 😁** 

Some imports that stood out:
1. bokeh ~2s
    1. pandas ~1s
6. numpy (via distributed) ~260ms
8. worker_state_machine.py ~200ms making dataclasses
7. urllib3 ~170ms
1. jinja2 (via dask) ~170ms
3. cytoolz (via dask) ~140ms
5. loading yaml (via dask) ~140ms
4. yaml (via dask) ~130ms
8. fsspec (via cluster_dump.py) ~110ms

None of these seem particularly avoidable (numpy will always be there https://github.com/dask/distributed/issues/5729, urllib3/jinja/toolz/yaml/etc probably have to happen). A couple small things:
- Defer fsspec import in cluster_dump.py until the dump actually needs to be written
- Switch from dataclasses to [msgspec structs](https://jcristharif.com/msgspec/benchmarks.html#benchmark-structs) in worker state machine?

A larger change that @graingert proposed was to wait to set up the dashboard (aka import bokeh and pandas) until after we'd started listening for client connections. That way, we can be doing both at once (ish). The issue is that a number of the tests are assuming that once a client is connected, the dashboard must be up. We could refactor this, but I don't really want to deal with it. I don't imagine that it would make much difference for users in real life anyway.

-------

## What should we do

**After all that, I think we should just make `distributed.comm.timeouts.connect` longer when we're connecting to a scheduler run in a subprocess 😄**

The 5s connect timeout arguably makes sense for async or `gen_cluster` tests. No subprocesses, everything should be really quick. But when launching a scheduler from scratch in a new process, it's not a good idea to have expectations for the speed of that on a CI machine.

I did some archaeology and `"distributed.comm.timeouts.connect": "5s"` actually used to only be set in `gen_cluster`. Then in https://github.com/dask/distributed/pull/2687, it was moved from [there](https://github.com/dask/distributed/pull/2687/files#diff-454ff0342d1c0724fc6e164fcb884d6727676fd560869fab3331a11adc812d56L935) to the [`clean`](https://github.com/dask/distributed/pull/2687/files#diff-454ff0342d1c0724fc6e164fcb884d6727676fd560869fab3331a11adc812d56R1517) fixture, where it's been since.

The main question to me is, should we:
1. Manually `dask.config.set({"distributed.comm.timeouts.connect": "10s"})` in all the tests where we make a `dask-scheduler` subprocess and connect a client to it.
    - pros: well-contained
    - cons: tests added in the future (or that we miss) might forget to do this
1. Just change the value to 10s in the [`_reconfigure` contextmanager](https://github.com/dask/distributed/blob/4f6960a33e068d7c66b8993d1dbe92a3d058bc96/distributed/utils_test.py#L1889)—updating it everywhere
    - pros: we know it'll cover every case, including future tests. A reasonable compromise, since it's still a relatively short timeout.
    - cons: we don't know what _else_ it might affect. Or if it'll allow tests to pass/flake that should be failing consistently. Or if tests will still rarely, occasionally, need >10s to connect on a bad CI day.
1. Move the `distributed.comm.timeouts.connect": "5s"` from `_reconfigure` (where it gets set everywhere the `loop` fixture is used) to just `gen_cluster`, _maybe_ `cluster`, _maaaaybe_ `gen_test`?
    - pros: now only applying the short timeout to places we're certain it's appropriate
    - cons: wouldn't apply to manually-created clusters or some other esoteric cases where it _could_ be appropriate—though not having it doesn't make the tests wrong.
1. Remove the `distributed.comm.timeouts.connect` setting from `_reconfigure` entirely, and fall back on the default value of 30s.
    - pros: the justification for a short timeout in CI is actually a little dubious. We've been learning the hard way not to do anything that relies on timing in CI jobs. I don't think a short connect timeout is actually testing anything about correctness—I imagine its main purpose is making bad tests fail faster, for better DX. This probably applies mostly to running tests locally. It's not that helpful in CI though. If the tests don't actually need it to be correct, and it's causing problems, why have it at all?
    - cons: actually bad tests are slower to fail during local development. And if something systematically starts making cluster connection take 2-3x longer, we might not notice.

**Comment by gjoseph92** [comment]
Waaait I think this flakiness was introduced in https://github.com/dask/distributed/pull/6231 @graingert.

Prior to that commit, the [`loop` fixture](https://github.com/gjoseph92/distributed/blob/34a94094834cb50d360b80894927ffbc15a301c9/distributed/utils_test.py#L138-L168) (which all of these flaky tests use) didn't call or depend on `clean`.

That change [added the `cleanup` fixture to `loop`](https://github.com/dask/distributed/pull/6231/files#diff-454ff0342d1c0724fc6e164fcb884d6727676fd560869fab3331a11adc812d56R139).

Prior to that, fixtures that set the 5s timeout (by calling `clean` directly) were:
* `cluster`
* `gen_test`
* `gen_cluster`
* `cleanup`

`loop` and `loop_in_thread` did not used to call `clean` and therefore didn't have a 5s timeout. It's good that they call `clean` now, but maybe not appropriate that they have the timeout.

-----

Another way to say that is: should this `_reconfigure` function actually be a part of `clean`? It doesn't seem related to the job of `check_thread_leak`, `check_process_leak`, and `check_instances`.

https://github.com/dask/distributed/blob/4f6960a33e068d7c66b8993d1dbe92a3d058bc96/distributed/utils_test.py#L1882-L1909

cc @hendrikmakait
