### ISSUE TITLE
Serialization turns tuples into lists

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#675]
```
>>> tup = 1,2
>>> from distributed.protocol import core
>>> core.loads(core.dumps(tup))
[1, 2]
```

It produces ignored exceptions in tests such as `distributed/tests/test_scheduler.py::test_remove_worker_from_scheduler`:

```
ERROR:tornado.application:Future <tornado.concurrent.Future object at 0x7f707583ef98> exception was never retrieved: Traceback (most recent call last):
  File "/home/antoine/tornado/tornado/gen.py", line 304, in wrapper
    yielded = next(result)
  File "/home/antoine/distributed/distributed/worker.py", line 540, in compute_one
    self.active.add(key)
TypeError: unhashable type: 'list'
```

**Comment by pitrou** [comment]
@mrocklin

**Comment by mrocklin** [comment]
Yes, this is a restriction of msgpack, for which there is only one array type.  

When using the client we map all keys to strings.  

That test should do so as well (or ideally just use the client API).  I can fix this easily sometime tomorrow.  Alternatively you could call `distributed.utils.tokey` on all of the keys of `dsk` in that test.
