### ISSUE TITLE
`SpillBuffer.spilled_total` appears to return incorrect results 

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6783]
When spilling data to disk, the `SpillBuffer` appears to return the incorrect size of the data on disk. For example, when spilling an ~8 MB random matrix onto disk, the `data` file created by the `SpillBuffer` is also ~8 MB in size, yet the SpillBuffer only returns ~1 MB.

Reproducer:
```python3
from __future__ import annotations

import os
import tempfile

import numpy as np

from distributed.spill import SpillBuffer


def test_spill_size():
    tmpdir = tempfile.mkdtemp()
    buf = SpillBuffer(spill_directory=tmpdir, target=0, max_spill=False)
    data = np.random.random((1024, 1024))
    buf["data"] = data
    spill_size = os.stat(os.path.join(tmpdir,  "data")).st_size
    assert buf.spilled_total.disk == spill_size
```

fails with
```
>       assert buf.spilled_total.disk == spill_size
E       assert 1048808 == 8388840
E        +  where 1048808 = SpilledSize(memory=8388608, disk=1048808).disk
E        +    where SpilledSize(memory=8388608, disk=1048808) = Buffer<<LRU: 0/0 on dict>, <zict.cache.Cache object at 0x11f2413d0>>.spilled_total
```

**Comment by ncclementi** [comment]
A couple of comments here, it looks a bit weird to me that the disk size calculated as `spill_size` is very close to the value we are calculating as the `buf.spilled_total.memory`. I would expect the `spill_size` to be bigger.  However, I wonder if this is related to how we calculate spilled_total. See:
https://github.com/dask/distributed/blob/55cc1a50f6fc7c10815bed93681eba970c9b63f0/distributed/spill.py#L30-L31

**Comment by hendrikmakait** [comment]
The size of spill_size feels fine to me. Just looking at the way we serialize things, the overhead for this array appears to be 232 bytes (`sys.getsizeof(serialize(data)[0])`), which matches perfectly. There might be a clue in the fact that `spill_size` is always _almost_ 8x the size of `buf.spilled_total.disk`, regardless of the size of `data`.

**Comment by hendrikmakait** [comment]
It looks like the calculation of the memory size is wrong:
https://github.com/dask/distributed/blob/55cc1a50f6fc7c10815bed93681eba970c9b63f0/distributed/spill.py#L290
uses `len` but we should probably use `nbytes` (https://docs.python.org/3/library/stdtypes.html#memoryview.nbytes). I'll file a PR for this.

**Comment by ncclementi** [comment]
That line was suggested by Guido when we were working on this. I'm sure he'll have an idea of what could be happening here. I know he is on PTO, but he might be a good person to review this. He will be back next week.

**Comment by crusaderky** [comment]
I was not aware that `len(memoryview)! = memoryview.nbytes`. Good catch! No need to wait for my return.
