### ISSUE TITLE
Replace `tmpdir` and `tmpdir_factory` fixtures with `tmp_path` and `tmp_path_factory`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6799]
According to the `pytest` docs, `tmpdir` and `tmpdir_factory` are considered legacy (see: https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures). Replacing them with `tmp_path` and `tmp_path_factory` would enable us to use standard `pathlib.Path` objects.

**Comment by mdrodelo** [comment]
Hello. I'm interested in working on this issue. I wanted to be sure I'm looking at this correctly first.

I searched through the repo for tmpdir and a bunch of remaining locations popped up: https://github.com/dask/distributed/search?q=tmpdir

The work for this issue would be to replace tmpdir with tmp_path and make sure any operations on them is consistent with pathlib.Path?

**Comment by hendrikmakait** [comment]
@mdrodelo, thanks for your interest in this issue. Your understanding is correct, but let me stress some points:

> The work for this issue would be to replace tmpdir with tmp_path

The scope of this ticket is replacing the `tmpdir` _fixture_ and its usages, e.g. in https://github.com/dask/distributed/blob/4b89e26c044da2bd5ceb9367568a27911589cdf7/distributed/tests/test_diskutils.py#L41
Cleaning up other variables called `tmpdir` in tests, e.g. https://github.com/dask/distributed/blob/3551d1574c9cd72d60197cc84dd75702ebcfec54/distributed/tests/test_preload.py#L37 is not the scope of this issue, but if you get around to it, it would be appreciated. 

Code outside of `tests` that contains a `tmpdir` variable, e.g. https://github.com/dask/distributed/blob/79ca60bfacfad912fc7f37e213f2c9cd6acdc21c/distributed/worker.py#L3245 should remain untouched.

 > make sure any operations on them is consistent with pathlib.Path

Yes, rewriting the code using the fixtures to be more idiomatic would be greatly appreciated.

Regarding the `tmpdir_factory`, it looks like there are indeed no instances of it left anymore.

**Comment by ypogorelova** [comment]
Hi @mdrodelo, are you still working on this issue? I would like to take it if you don't mind

**Comment by mdrodelo** [comment]
@ypogorelova I am not working this issue.
