### ISSUE TITLE
EC2Cluster adaptive ends up with way more workers than the limit

### ISSUE THREAD

**Issue by martinedgefocus** [dask/distributed#6801]
I set up EC2Cluster with adapt(minimum=0, maximum=64), but have ended up with over 170 workers before I noticed, and it racks up huge bills. Seems like they also don't get released when the cluster is idle.

I tried instrumenting the code to diagnose what's going on and noticed the following:

```
>>> cluster
EC2Cluster(19bd82be, 'tcp://x.x.x.x:8786', workers=1, threads=4, memory=30.85 GiB)
>>> cluster._adaptive.plan     
set()
>>> cluster._adaptive.requested
set()
>>> cluster._adaptive.observed
{'dask-35c0d534-worker-bf6c742a'}
```

From what I can see of the code, nothing should be in observed that doesn't appear in plan/requested? I'm unclear how this occurred

I note that recommendations() seems to scale up/down based on len(plan) so if machines were missing from plan, but present in observed, I can see how we would end up with excess capacity.

I also saw an error, which now sadly seems to have been lost (it appeared on the screen of the python process that created the cluster, but I don't see it recorded anywhere) when ec2.py::create_vm made a new machine, I believe the client.create_tags() call failed with an error the machine did not exist ... however, I believe it actually WAS created.

I'm assuming the adaptive code (eg recommendations()) runs on the scheduler, but it doesn't seem to log to the scheduler when it calls logger.info() ... do those get recorded anywhere? cluster.logs()['Cluster'] seemed to have some of it, but not the exception I saw

**Comment by martinedgefocus** [comment]
This line of code from `recommendations()` also seems to be problematic to me:
`not_yet_arrived = requested - observed`
Which seems like set subtraction, but not of equivalent objects, what's in `requested` seems to be small integers, what's in `observed` is worker names

**Comment by jacobtomlinson** [comment]
Closed by https://github.com/dask/dask-cloudprovider/issues/365

**Comment by martinedgefocus** [comment]
I'm not sure that the ec2 bug is the only way this can happen; it might be worth a general fix for this as the consequences can be expensive. I was experimenting with something like the below as a more general catch-all for the situation where we have machines in observed, but not plan / requested - not convinced this is exactly what should be done, but maybe useful for discussion?

```
diff --git a/distributed/deploy/adaptive_core.py b/distributed/deploy/adaptive_core.py
index 353b11b7..b52a4a7e 100644
--- a/distributed/deploy/adaptive_core.py
+++ b/distributed/deploy/adaptive_core.py
@@ -175,26 +175,28 @@ class AdaptiveCore:
         """
         Make scale up/down recommendations based on current state and target
         """
-        plan = self.plan
+        current_count = max(len(self.plan | self.requested), len(self.observed))
         requested = self.requested
         observed = self.observed
 
-        if target == len(plan):
+        if target == current_count:
             self.close_counts.clear()
             return {"status": "same"}
 
-        if target > len(plan):
+        if target > current_count:
             self.close_counts.clear()
             return {"status": "up", "n": target}
 
-        # target < len(plan)
-        not_yet_arrived = requested - observed
+        # target < current_count
+        not_yet_arrived = requested - observed    # ERROR. requested is numbers, observed is names
         to_close = set()
+        # First subtract from not_yet_arrived
         if not_yet_arrived:
-            to_close.update(toolz.take(len(plan) - target, not_yet_arrived))
+            to_close.update(toolz.take(current_count - target, not_yet_arrived))
 
-        if target < len(plan) - len(to_close):
-            L = await self.workers_to_close(target=target)
+        # Second subtract from observed
+        if target < current_count - len(to_close):
+            L = await self.workers_to_close(target=target) # tail of observed
             to_close.update(L)

```

**Comment by jacobtomlinson** [comment]
@martinedgefocus perhaps you could open a PR so we can discuss the change there?
