### ISSUE TITLE
Setting up conda env takes 2-8min per CI job — cache it?

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6853]
Looking at a [recent CI run](https://github.com/dask/distributed/runs/7724401999?check_suite_focus=true) on main, I see the `Setup Conda Environment` step taking 2-3min on linux, and typically 6-7min on Windows and macOS. That's 10-15% of total job runtime.

Could we cache the conda environment between CI runs, and only reinstall when the `environment.yaml` changes? (And maybe once per day too, so things don't get too stale?)

A downside is that most of our CI dependencies are un-pinned, which we're relying on as a crude form of upstream testing: when dependencies release new versions, our CI might non-deterministically go red if they broke something. Personally, I think this is a bad experience for contributors and bad practice for CI in general, but it doesn't seem like we're going to change this right now https://github.com/dask/community/issues/203. So if we did cache conda envs, it might add more latency when upstream dependencies break us.

cc @fjetter @quasiben

**Comment by quasiben** [comment]
I think caching seems like a good idea to speed up things.  We could also build a nightly docker image of dependencies and run test in the image.  This give us an option of re-running in a "solved" environment.

cc @charlesbluca @jacobtomlinson for additional thoughts

**Comment by gjoseph92** [comment]
A docker image seems like overkill to me. The miniconda docs already discuss how to do this with GHA: https://github.com/conda-incubator/setup-miniconda#caching-environments

And an example: https://github.com/epassaro/cache-conda-envs/blob/c804ffe9508d3d1aaa8a8e4c34c001c84afd34a6/.github/workflows/ci.yml#L49-L60

**Comment by charlesbluca** [comment]
Yeah was going to suggest first trying out caching as described in the miniconda action docs.

> if we did cache conda envs, it might add more latency when upstream dependencies break us.

Would this concern be alleviated if we added an opt-out option for environment caching (thinking of using something like xarray's [ci-trigger](https://github.com/xarray-contrib/ci-trigger)) for PRs or commits where we want to pull in the latest CI deps?

**Comment by quasiben** [comment]
@charlesbluca do you have time to try a test PR which implements the caching ?

**Comment by charlesbluca** [comment]
Yeah I can look into this

**Comment by fjetter** [comment]
Caching the environment and letting the cache expire every day sounds good to me

**Comment by jacobtomlinson** [comment]
> A downside is that most of our CI dependencies are un-pinned, which we're relying on as a crude form of upstream testing: when dependencies release new versions, our CI might non-deterministically go red if they broke something. 

Could we have a nightly job that installs the env, runs the tests and only caches it when everything passes? Then all the PR jobs just use the most recent good nightly env?

**Comment by fjetter** [comment]
> Could we have a nightly job that installs the env, runs the tests and only caches it when everything passes? Then all the PR jobs just use the most recent good nightly env?

+1 I like the idea, if it's not too much trouble

**Comment by jacobtomlinson** [comment]
```bash
until pytest; do echo "trying again 😅"; done
```

**Comment by charlesbluca** [comment]
> Could we have a nightly job that installs the env, runs the tests and only caches it when everything passes?

Think would already be happening if we merge in #6855, as testing CI is also running on a schedule, and thus a cached environment would be created (if it doesn't already exist) at UTC 6:00 and 18:00:

https://github.com/dask/distributed/blob/f43bc4729f52b3fbfc0758506adfcf51276ffb60/.github/workflows/tests.yaml#L7

I'm not sure if these times were set with Dask maintainers' local timezones in mind, but it would be nice to switch the scheduled CI to run at UTC 00:00 and 12:00, so that new cached environments start getting built right when the old cached envs become stale.
