### ISSUE TITLE
Add metrics for worker communications

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6892]
To better understand worker communications, their performance and required resources, we should track more metrics. Specifically, it would be interesting to track the number of open incoming/outgoing connections and `comm_nbytes` in `Worker.get_metrics`. This could help debug issues such as dask/distributed#6208 or https://github.com/coiled/coiled-runtime/pull/229#discussion_r946807049 and help take decisions on possible solutions for those (https://github.com/dask/distributed/issues/6208#issuecomment-1216710657)

**Comment by fjetter** [comment]
If we go down this road I believe it would be interesting to add `comm_nbytes` (or a derivative of some sort) to the dashboard. I suspect that unmanaged memory is often actual communication overhead and it would be nice if we could separate this visually.
