### ISSUE TITLE
Support cgroups memory limit detection for cgroups V2

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6894]
In cgroups v2, the memory limit changed from `/sys/fs/cgroup/memory/memory.limit_in_bytes` to `/sys/fs/cgroup/memory.max`. For example:
* https://github.com/oracle/docker-images/issues/1939
* https://github.com/docker/for-mac/issues/6118

To fix this, let's just replace this with a loop through both files:
https://github.com/dask/distributed/blob/969aa4636bff9a4c9e1f3805fdaf9cc4d44ab1db/distributed/system.py#L25

**Comment by shughes-uk** [comment]
https://github.com/dask/distributed/pull/7051
