### ISSUE TITLE
Adding other [de]serialization methods (e.g. TIFF)

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#690]
I'd be really interested to know how we could add some other serialization methods ( probably in the spirit of PR https://github.com/dask/distributed/pull/606 ) ideally to `distributed` directly for things like TIFFs or other image data formats. Would be really interesting to be able to easily load and work with various kinds of image data.

**Comment by mrocklin** [comment]
For strictly loading image data I would probably just default to calling `skimage.imread` or something similar.  I don't think that strictly loading data needs to engage the custom serialization machinery.

Moving data around is more complex.  I would only want to go down this path after there was a sizable community doing image processing with dask.distributed that was bound by inter-worker communication.

I might not have in mind what you have in mind though.  If you have more details about what you're thinking then please share.

**Comment by jakirkham** [comment]
So I think I may have answered my own question. To briefly summarize so as to hopefully avoid [future confusion]( http://xkcd.com/979/ ), my intention was to lazily read in a bunch of multipage TIFF files larger than a computer/node's memory and stack them together for later computation and/or conversion to HDF5. However, it sounds like the answer is to use [`dask.array.image.imread`]( https://github.com/dask/dask/pull/578 ) and the do some [stacking/reshaping]( https://github.com/dask/dask/issues/672#issuecomment-138101382 ) after with optional [HDF5 conversion]( https://github.com/dask/dask/issues/672#issuecomment-138094929 ).

**Comment by jakirkham** [comment]
Also, for others that may try this, it turns out that `stack`-ing requires the arrays have the same `chunksize`. However, for a multipage TIFF, the chunksize will be the same as the shape, which could have a variable number of pages. That all being said, this can be satisfied by indexing each multipage TIFF to get a single page and thus uniform chunksize. The final result of this operation will be a bunch of single TIFF pages that can be easily stacked. In code, this looks something like this.

```python
import dask.array as da
import dask.array.image

l = ["f1.tif", "f2.tif", "f3.tif"]

d = []
for fn in l:
    a = da.image.imread(fn)
    for i in xrange(a.shape[1]):
        d.append(a[:, i])
d = da.stack(d, axis=1)
```

**Comment by mrocklin** [comment]
This notebook may interest you:
https://gist.github.com/mrocklin/611c64e4fb62486269b507a872984cc5

**Comment by jakirkham** [comment]
That is very interesting. Thanks for sharing.

@stuarteberg , might want to take a look at this. 😉

**Comment by jakirkham** [comment]
So, I'm interested in why you chose to use `delayed(skimage.io.imread, ...)` instead of `dask.array.image.imread`. Were there some performance differences?

**Comment by stuarteberg** [comment]
>This notebook may interest you: https://gist.github.com/mrocklin/611c64e4fb62486269b507a872984cc5

Thanks, @mrocklin, that notebook is indeed interesting.  Currently, we use PySpark for cluster-based computation.  But for quite some time now, I've been meaning to experiment with your `dask` package, to see how it compares for the problems we work on.  It's useful to have an example like this -- with our own data, no less!

cc: @stephenplaza @DocSavage

PS --Thanks for the ping, @jakirkham. 😄

**Comment by mrocklin** [comment]
> So, I'm interested in why you chose to use delayed(skimage.io.imread, ...) instead of dask.array.image.imread. Were there some performance differences?

They both produce similar graphs.  There shouldn't be any performance difference.  Dask doesn't introduce much overhead here.  We're just bound by network I/O and skimage functions.  I used delayed because I forgot about da.image.imread.  In general I just default to using `delayed`.  It's a straightforward way to solve most problems that don't fit cleanly into dask.array/dataframe.

**Comment by mrocklin** [comment]
@stuarteberg glad it's useful.  I was just playing around some evening before a conference, so there are undoubtedly better things one could do.  If you run into issues please get in touch.
