### ISSUE TITLE
Worker resource restrictions

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#691]
Problem
-----

Currently we only execute as many tasks on a worker as there are threads in that worker's ThreadPool.  We also only schedule roughly that many tasks to the worker (plus a few more) as well.  This helps to avoid contention over a valuable resource, the CPU.

However, there are other resources than CPUs whose total consumption by many tasks may bound which tasks can run.  For example:

*  A worker machine may have eight cores but only two GPUs and so we need to make sure that we run at most two GPU tasks concurrently
*  A worker may have 100GB of RAM.  While most tasks may not consume significant amounts of RAM we may know a few whose runtime state requires 60GB, 30GB, etc..  
*  Some worker tasks may be known to hog network resources and so we may prefer to schedule at most one per machine.

Proposal
------

We allow the user to annotate tasks with resource quantities, similar to how they currently [list restrictions](http://distributed.readthedocs.io/en/latest/locality.html#user-control).  For example:

```python
future = client.submit(func, *args, resources={'memory': 100e9})
or
future = client.compute(delayed_value, resources={key2: {'GPU': 1}, key2: {'GPU': 2})
```

Similarly we create workers with known resource quantities

```python
worker = Worker(..., resources={'memory': 250e9, 'GPU': 1})
or
dask-worker ... --resources "memory=250e9, GPU=1"
```

These resource types (memory, GPU) have no semantic meaning (the worker isn't actually becoming GPU aware), rather they are just known quantities that we need to ensure we do not exceed.

This limit will be imposed in a soft way on the scheduler side and in a hard way on the worker side.  The worker will refuse to run tasks that would make it exceed its limits.  The scheduler will never schedule a task to a worker that is incapable of meeting the resource limits, such as by scheduling a GPU job to a worker without a GPU.  The scheduler will also endeavor to spread resource-heavy tasks around, however it *may* schedule tasks whose total required resources exceed the worker's limits, depending on the worker to impose the hard limit.  

## Efficiency

Constant time task scheduling is hard.  Making it work seamlessly is much harder.  Generally we depend on complex logic to spread work around, steal work between workers, etc..  The data structures within the scheduler manage to do all of this in constant time.  

Adding resource limits makes the situation much more complex.  Maintaining the constant-time promise while keeping the scheduler maintainable is likely to be very challenging.  Among these three objectives (adding resource limits, constant time efficiency, and maintainable code) I'm most likely to drop the constant time promise in this case.  Tasks that specify resources may be strictly less efficient to schedule.  Users would be encouraged to use this feature sparingly.

Some examples of inefficiencies:

1.  Finding suitable workers may involve a linear scan through all workers
2.  Work stealing may or may not be implemented for early versions
3.  ...

## Hosts with Several Workers

The current solution to multi-processing with dask/distributed is to start many independent dask-workers on the same machine.  Resources like memory, GPUs, and network are likely to be shared among these many dask-workers.  Ideally we find a way to track resource per host rather than per worker.

**Comment by seibert** [comment]
Would it be possible to make the resource limits for a worker be computed using a function shipped from the client?  This would make it easier for a new kind of resource to be created on the fly for a computation that needed it.

For example, supposing my task is limited not just by the existence of a GPU, but GPU memory.  Rather than have to restart all the workers to add a `gpu_memory` resource with some hard-coded value, it would be extremely convenient to do something like this:

```
def compute_gpu_resource_limits():
    import numba
    try:
        free = numba.cuda.get_current_device().get_primary_context().get_memory_info().free
    except numba.cuda.CudaSupportError:
        free = 0
    
    return dict(gpu_memory=free)

from distributed import Client
client = Client('127.0.0.1:8786')
client.register_resource_function(compute_gpu_resource_limits)

client.submit(func, *args, resources={'gpu_memory': 2e9})
```

Then the scheduler would ensure that function was run on each worker (and new workers when added) and the returned dictionary was added to the dictionary of resource limits for each worker.

**Comment by mrocklin** [comment]
@seibert this fits in with #505

**Comment by seibert** [comment]
Oh, nice!  yes, that does seem to be a very similar idea.

**Comment by mrocklin** [comment]
So I'm working on this over here: #694 

I now think that the scheduler will have to manage the hard resource limits.  It will be hard for multiple workers on the same host to coordinate otherwise.  Question: are *all* resources per-host? or are there relevant per-process resources as well?

**Comment by mrocklin** [comment]
We also have the question of how to schedule resource-restricted tasks.  Should they generally have priority over resource-free tasks?  

What should we do when a resource-restricted task is supposed to run on a worker but can't due to resource constraints?  Do we wait?  Do we move to another worker?  Should we apply the same logic we do in non-resource-constrained cases about minimizing estimated time-to-completion?

Doing the above might involve tracking multiple task stacks per worker.  We might want to generalize this beyond the use of just resources and get a bit into channels of tasks.

**Comment by seibert** [comment]
I had assumed resources would be per process, though I can see why host level also makes sense.  In a multi-GPU server, it would be typical to assign one GPU to each worker, in which case a GPU memory limit would be per process, not per host.

**Comment by mrocklin** [comment]
The per-host idea came from chatting with someone that is GIL bound, and so using multiple workers per host.  I now agree with you though that it's probably simpler to keep restrictions per process and improve multiprocessing in other ways in the future.

**Comment by mrocklin** [comment]
Copying a comment over from #694 

OK, there is a minimal implementation here.  Further work is necessary here, but what's here could feasibly go in.

```
mrocklin@carbon:~/workspace/distributed$ dask-scheduler 
mrocklin@carbon:~/workspace/distributed$ dask-worker localhost:8786 --resources "GPU=1"
mrocklin@carbon:~/workspace/distributed$ dask-worker localhost:8786 --resources "MEM=1e9"
```

```python
In [1]: from distributed import Client

In [2]: c = Client('localhost:8786')

In [3]: c.scheduler_info()
Out[3]: 
{'id': 'a4338232-b0df-11e6-946d-7d159e23c0bc',
 'services': {'http': 9786},
 'type': 'Scheduler',
 'workers': {'127.0.0.1:32974': {'active': 0,
   'last-seen': 1479838557.706151,
   'memory_limit': 10012606464,
   'name': '127.0.0.1:32974',
   'resources': {'GPU': 1.0},    # <<---- Note resources
   'services': {'http': 44992, 'nanny': 33407},
   'stored': 0,
   'time-delay': 0.0043642520904541016},
  '127.0.0.1:43023': {'active': 0,
   'last-seen': 1479838559.570338,
   'memory_limit': 10012606464,
   'name': '127.0.0.1:43023',
   'resources': {'MEM': 1000000000.0},    # <<---- Note resources
   'services': {'http': 45243, 'nanny': 32942},
   'stored': 0,
   'time-delay': 0.004169940948486328}}}

In [4]: def load(fn):
   ...:     pass
   ...: def process(data):  # gpu intensive
   ...:     pass
   ...: def reduce(*data):  # memory intensive
   ...:     pass
   ...: 

In [5]: from dask import delayed
In [6]: raw = [delayed(load)(i) for i in range(10)]
In [7]: processed = [delayed(process)(r) for r in raw]
In [8]: reduced = delayed(reduce)(*processed)

In [9]: future = c.compute(reduced, resources={tuple(processed): {'GPU': 1}, 
                                               reduced: {'MEM': 1e8}})
In [10]: future.result()
```

**Comment by mrocklin** [comment]
This was implemented
