### ISSUE TITLE
Support for tornado==6.2

### ISSUE THREAD

**Issue by gabicca** [dask/distributed#6979]
With the latest release of jupyter-clinet==7.3.5 there is now a version conflict between the requested tornado version of distributed and the other package:

```
 tornado>=6.2 (from jupyter-client==7.3.5->notebook==6.4.12->jupyter==1.0.0)
 tornado<6.2,>=6.0.3 (from distributed==2022.8.1)
```

Could you please add support of tornad==6.2?

Thanks!

**Comment by jrbourbeau** [comment]
Thanks for surfacing this @gabicca! Closing as a duplicate of https://github.com/dask/distributed/issues/6669
