### ISSUE TITLE
Tornado<6.2 dependency clashes with new jupyter-client release

### ISSUE THREAD

**Issue by aberres** [dask/distributed#6984]
https://github.com/dask/distributed/pull/6668 forces `tornado<6.2` due to some issues.

Recent Jupyter Client depends on `tornado>=6.2` since  https://github.com/jupyter/jupyter_client/commit/81d7cf392d4ffc4f6ee4d51ba03e96f78dfbf18b

This means dask is blocking upgrades to newer Jupyter.

It would be great if distributed could support newer tornado releases.

**Comment by jrbourbeau** [comment]
Thanks @aberres! Closing as a duplicate of https://github.com/dask/distributed/issues/6669

**Comment by aberres** [comment]
Ah, sorry. Somehow missed this one.

**Comment by jrbourbeau** [comment]
No worries -- thanks for reporting!
