### ISSUE TITLE
PipInstall plugin restart fails behind private pypi and when --upgrade pip option is specified

### ISSUE THREAD

**Issue by mdwgrogan** [dask/distributed#7037]
If you are installing from a private pypi server and you want the pip install plugin to restart the worker, the following lines of code cause the worker to restart constantly since the first line of text is "Looking in indexes..." not "Requirement already ..."

https://github.com/dask/distributed/blob/1fd07f03cacee6fde81d13282568a727bce789b9/distributed/diagnostics/plugin.py#L306-L312

Similarly, if you happen to pass --upgrade in the pip options list, you get similar behavior where the worker continually restarts, because the message from pip is "Requirement already up-to-date" instead of "Requirement already satisfied"

**Comment by hendrikmakait** [comment]
Hi @mdwgrogan, thanks for filing this issue. I have started a PR that enables installing from a private PyPI server in #7086. 

Regarding the problem with `--upgrade`, what version of `pip` are you using in your environment? I could not reproduce this issue without enabling the legacy resolver using `--use-deprecated=legacy-resolver` on `pip 22.2.2`.

**Comment by mdwgrogan** [comment]
At a guess, 20.2. In the time between diagnosing/submitting this issue and now, the version of pip on my cluster was upgraded and I no longer see the "up-to-date" message, so only the index URL is causing me issues. Thanks!
