### ISSUE TITLE
Need Window Timer

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#712]
We need a timer for Windows that has the following properties:

1.  Fast to run (microsecond or less) - like `time.time` or `timeit.default_timer`
2.  Roughly globally consistent (to within minutes) - like `time.time` but not `timeit.default_timer`
3.  Microsecond precision - like `timeit.default_timer`, but not `time.time`

I wonder if there is a way to combine `time.time` and `timeit.default_timer` to achieve the desired result.  Or is there an established alternative?

cc @pitrou @jreback

**Comment by pitrou** [comment]
"Roughly globally consistent" - you mean accross different machines?

**Comment by pitrou** [comment]
On Windows:
* `time.time()` is the absolute time but has poor resolution
* `time.process_time()` is wall clock time with a fine resolution but an unspecified reference point

By combining the two we should be able to get "absolute" times with decent resolution.

**Comment by pitrou** [comment]
About performance:
```
>>> %timeit time.time()
The slowest run took 132.95 times longer than the fastest. This could mean that
an intermediate result is being cached.
10000000 loops, best of 3: 81.9 ns per loop
>>> %timeit time.perf_counter()
The slowest run took 4.79 times longer than the fastest. This could mean that an
 intermediate result is being cached.
100000 loops, best of 3: 3.44 µs per loop
```

This makes `perf_counter()` a bit slow, but not that much in the context of Python bytecode execution.

**Comment by mrocklin** [comment]
In the Dask scheduler we maintain a known lag-time to each worker that we use to correct all incoming times.  Usually this lag-time is on the order of seconds and we trust that the value never rolls over.  

We probably could use `default_timer` and be fine, especially if the workers are ephemeral, but I'd trust things more if everyone used a baseline that was roughly consistent.

**Comment by pitrou** [comment]
Here is a proposal: https://gist.github.com/pitrou/faf437bf417c77c3cd96b1071737a90b

```
>>> [(time.time(), synctime.synctime()) for i in range(20)]

[(1480609651.5324142, 1480609651.5332496),
 (1480609651.5324142, 1480609651.5332682),
 (1480609651.5324142, 1480609651.5332782),
 (1480609651.5324142, 1480609651.5332887),
 (1480609651.5324142, 1480609651.533298),
 (1480609651.5324142, 1480609651.5333087),
 (1480609651.5324142, 1480609651.5333183),
 (1480609651.5324142, 1480609651.5333276),
 (1480609651.5324142, 1480609651.5333366),
 (1480609651.5324142, 1480609651.5333467),
 (1480609651.5324142, 1480609651.5333564),
 (1480609651.5324142, 1480609651.5333657),
 (1480609651.5324142, 1480609651.533375),
 (1480609651.5324142, 1480609651.5333846),
 (1480609651.5324142, 1480609651.5333939),
 (1480609651.5324142, 1480609651.5334034),
 (1480609651.5324142, 1480609651.533413),
 (1480609651.5324142, 1480609651.5334232),
 (1480609651.5324142, 1480609651.533433),
 (1480609651.5324142, 1480609651.5334423)]
>>> %timeit synctime.synctime()
The slowest run took 5.39 times longer than the fastest. This could mean that an
 intermediate result is being cached.
100000 loops, best of 3: 4.46 µs per loop
```

**Comment by pitrou** [comment]
I agree using a reliable baseline is better. Also, modern systems are supposed to sync their internal clocks with NTP.

**Comment by pitrou** [comment]
Do you want me to make a PR out of that?

**Comment by pitrou** [comment]
(note this scheme doesn't guarantee monotonicity, although it should be statistically monotonic :-))

**Comment by pitrou** [comment]
(even time.time() isn't guaranteed to be monotonic, though...)

**Comment by mrocklin** [comment]
Is drift something to worry about?  Is one `perf_counter` not fairly precisely a second?

**Comment by pitrou** [comment]
I don't know how precisely. If a daemon runs for multiple days or weeks, then perhaps it'll start drifting. As far as I know, `perf_counter` can be based on the CPU's performance counters, which are entirely independent from the system's absolute time.
(also, the performance counters won't be adjusted in case of e.g. DST switch)

**Comment by pitrou** [comment]
A fairly comprehensive PEP was written about the general problem, by the way: https://www.python.org/dev/peps/pep-0418/#windows-queryperformancecounter

**Comment by mrocklin** [comment]
Should the 360 number be much larger then?

**Comment by mrocklin** [comment]
Anyway, yes, I think a PR would be good

**Comment by pitrou** [comment]
Well, resync() should be fairly cheap (around 65µs here), so I think it's better to be conservative...

**Comment by mrocklin** [comment]
OK
