### ISSUE TITLE
Catch exceptions on both send and recv in UCX comm

### ISSUE THREAD

**Issue by wence-** [dask/distributed#7130]
Following on from a review of #6996, there are a few other places in the UCX communicator backend where we should be catching exceptions on message transfer.

In addition, some of the try catch blocks can have their scope tightened (to avoid hiding other errors).

cc @pentschev, I will self-assign, but don't have privileges to do so.

**Comment by pentschev** [comment]
Sorry @wence- , I dropped the ball on that discussion. I've opened https://github.com/dask/distributed/pull/7132 to address what we discussed in #6996.

**Comment by pentschev** [comment]
> Ah, when I said self-assign I meant that I would do it (but you got to it too fast!).

I understood, but I said I would do it when we first discussed, unfortunately it slipped my mind after all the trouble we had to actually get https://github.com/dask/distributed/pull/6996 in. Thanks for the reminder!
