### ISSUE TITLE
CLI tests failing on Windows

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#7142]
After merging #6735, CLI tests are failing consistently on Windows (e.g. https://github.com/dask/distributed/actions/runs/3253316343/jobs/5342043281#step:18:8556).

cc @douglasdavis

**Comment by jrbourbeau** [comment]
Thanks for surfacing @hendrikmakait. That's strange because we didn't see those failures on that PR ([this was the latest CI run on the PR before merging](https://github.com/dask/distributed/actions/runs/3247298707)). Last Friday I saw some issues due to environment caching in CI. I'm rerunning CI against `main` in https://github.com/dask/distributed/pull/7143 to see if things have somehow auto-resolved themselves.

**Comment by hendrikmakait** [comment]
When reproducing this on a local Windows machine, using `conda` to install `dask` only creates a small `dask` file in the `Scripts` folder, whereas using `pip` creates the necessary `dask.exe` (roughly 50x the size of the `dask` file) that is used to run the CLI. Removing `dask` from the dependencies in the environment also seems to make sure that `dask.exe` is generated.

**Comment by hendrikmakait** [comment]
FWIW, e.g. `$ python -m dask` works fine either way, `$ dask` is the problem.

**Comment by jrbourbeau** [comment]
Okay, thanks for digging in @hendrikmakait. I might have fix -- PR incoming...

**Comment by douglasdavis** [comment]
Good find! Interesting that the issue only surfaces on Windows..

**Comment by jrbourbeau** [comment]
Just merged those `conda-forge` PRs. Will rerun CI in https://github.com/dask/distributed/pull/7143 in a bit to confirm whether or not things are fixed

**Comment by jrbourbeau** [comment]
Alright, it looks like that did the trick. Windows builds in https://github.com/dask/distributed/pull/7143 are passing now. Thanks again for surfacing @hendrikmakait

**Comment by crusaderky** [comment]
Is release 2022.10.0 healthy on Windows? Or do we need to drop a new one in a hurry?

**Comment by douglasdavis** [comment]
If anything, only the _new_ CLI should be affected on Windows and only if installed via conda-forge in the last couple of days. @jrbourbeau pushed new builds on conda-forge via https://github.com/conda-forge/distributed-feedstock/pull/225. If someone installs 2022.10.0 right his moment things should be OK

**Comment by jrbourbeau** [comment]
Yeah, I don't think a new release is needed (for the reasons @douglasdavis mentioned)
