### ISSUE TITLE
LocalCluster does not respect memory_limit keyword when it is large

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#7155]
```python
from dask.distributed import Client
client = Client(memory_limit="300 GB")
client.run(lambda dask_worker: dask_worker.memory_limit)
```

```
{'tcp://127.0.0.1:62196': 17179869184,
 'tcp://127.0.0.1:62199': 17179869184,
 'tcp://127.0.0.1:62200': 17179869184,
 'tcp://127.0.0.1:62204': 17179869184}
```

It seems to respect the keyword when it's lower than available memory, but not when it's greater than.  Granted I don't have 1.2 TB of memory on my laptop, but maybe it makes sense to allow the user to over-subscribe.

**Comment by mrocklin** [comment]
```python
from dask.distributed import Client
client = Client(memory_limit="3 GB")
client.run(lambda dask_worker: dask_worker.memory_limit)
```

```
{'tcp://127.0.0.1:62281': 3000000000,
 'tcp://127.0.0.1:62282': 3000000000,
 'tcp://127.0.0.1:62283': 3000000000,
 'tcp://127.0.0.1:62284': 3000000000}
```

**Comment by jrbourbeau** [comment]
Thanks @mrocklin  -- I'm able to reproduce. This behavior is coming from this line

https://github.com/dask/distributed/blob/3a23650936c7e5349c62f30cbfdcc026aaeb5f3a/distributed/worker_memory.py#L404

where we cap things at `system.MEMORY_LIMIT`. cc @crusaderky

**Comment by mrocklin** [comment]
It may also be that this is correct behavior.  It was surprising (reasonably so I think).  It's subjective on if we want to let users do dumb things.  I _think_ that we do want to let them opt-in to being dumb, but I don't have a strong opinion here.

**Comment by jrbourbeau** [comment]
I'm not sure whether or not we should let users over-subscribe or not. This may lead to bad behavior with, for example, the active memory manager. I suspect @crusaderky will have insight here. Regardless, if we keep the current behavior, it'd be good to emit a warning (or something similar) to the user letting them know they've requested more memory than is available and we're capping at the system memory. That way, there will at least be visibility into what's happening

**Comment by fjetter** [comment]
I consider this expected behavior. Is there any sane use case for allowing larger values?

From a UX POV we should raise a warning if this happens such that the user knows what's going on.

---

This also relates roughly to https://github.com/dask/distributed/issues/6895 which discusses making the `system.MEMORY_LIMIT` even stricter

**Comment by mrocklin** [comment]
> From a UX POV we should raise a warning if this happens such that the user knows what's going on.

Sounds like a fine outcome to me.
