### ISSUE TITLE
`dask scheduler` not recognized as a valid command, despite suggestion from `FutureWarning`

### ISSUE THREAD

**Issue by DamianBarabonkovQC** [dask/distributed#7176]
**Describe the issue**:

When starting a dask scheduler the old way via `dask-scheduler`, it produces a future warning as such: `FutureWarning: dask-scheduler is deprecated and will be removed in a future release; use 'dask scheduler' instead`. 

However, then when running `dask scheduler` from the command line produces:

```
Usage: dask [OPTIONS] COMMAND [ARGS]...
Try 'dask -h' for help.

Error: No such command 'scheduler'.
```

Something does not work correct in this case.

**Environment**:

- Dask version: 2022.10.0
- Python version: Python 3.10.6
- Operating System: OSX 12.6
- Install method (conda, pip, source): `conda create -n env_name 'dask=2022.10.0'`

**Comment by jrbourbeau** [comment]
Thanks for reporting @DamianBarabonkovQC. FWIW this appears to be a `conda`-specific issue, so `pip` installing is a temporary workaround. We're working on a fix for the `conda` packages. Will keep this issue posted.

**Comment by jakirkham** [comment]
As James noted, this is a known issue. There have been 2 attempts to fix it, but no success so far. Related threads:

xref: https://github.com/conda-forge/distributed-feedstock/pull/225#discussion_r1000211836
xref: https://github.com/conda-forge/distributed-feedstock/pull/226
xref: https://github.com/conda-forge/dask-core-feedstock/pull/144

Would suggest just using the old entry points (with `-`s like `dask-scheduler`) as they still work. If we don't find a resolution soon, would suggest dropping/softening the deprecation warning (we don't appear to be ready for that).

**Comment by jakirkham** [comment]
Actually maybe PR ( https://github.com/conda-forge/dask-core-feedstock/pull/146 ) will solve it? Would be good to have others take a look 🙂
