### ISSUE TITLE
Add sortedcollections/collections to dependencies

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#719]
It would be convenient to add `sortedcontainers` and `sortedcollections` as dependencies.  

In particular we often need to ask the question "What is the currently least occupied worker?" and these data structures would let us answer this question in near constant time.  This would also allow us to select random elements from sets in constant time.

Under some basic testing they appear to be within a factor of two of the builtins.  There are also significant benchmarks available on their documentation.

* http://www.grantjenks.com/docs/sortedcontainers/
* http://www.grantjenks.com/docs/sortedcollections/

Any concerns?

**Comment by pitrou** [comment]
Alternatives:
* `heapq` for answering minimum or maximum questions
* `bisect` to maintain and query a sorted list with maximum performance
* `blist` for an alternative to the built-in list type with O(1) insertion at any place.

**Comment by pitrou** [comment]
(just an FYI. I am not familiar with `sortedcontainers` yet)

**Comment by mrocklin** [comment]
I was about to say "those are inherently comparison based libraries and so bound to logarithmic time" however then I had to check my "near constant time" claim and I'm not sure it's accurate.

His benchmarks against blist might be compelling.  I recall that there was a good PyCon talk by him one or two years ago.

**Comment by pitrou** [comment]
I've just skimmed the `sortedcontainers` documentation and it looks convincing enough. You may want to measure the import overhead, though :-)

> I was about to say "those are inherently comparison based libraries and so bound to logarithmic time" however then I had to check my "near constant time" claim and I'm not sure it's accurate.

Depends which operation you have in mind. The sorted list obviously answers the minimum question in constant time, but maintaining the sorted list has logarithmic complexity (the `sortedcontainers` documentation mentions using a one-level tree of fragments, as well as `bisect.insort`).

However, the `sortedcontainers` implementation appears to make smart decisions (e.g. relying on the bisect module, which is written in C and very fast compared to pure Python).

Overall I think we're less bothered by complexity (as long as it's logarithmic or less) than by actual implementation quality (constant multiplier and memory footprint). Judging by claims in the documentation, `sortedcontainers` has the latter well-covered. I'm also surprised it manages to beat `blist`, which is supposed to be a heavily-optimized `list` replacement.

**Comment by mrocklin** [comment]
Proposed initial use: https://github.com/dask/distributed/pull/723

**Comment by pitrou** [comment]
To sum up my opinion: `sortedcontainers` looks really good, we should probably use it if it helps us.
I'm less sold on `sortedcollections`: the overhead of those higher-level APIs is not documented, and I would rather be conservative by not adding too many dependencies.

**Comment by mrocklin** [comment]
The code in `sortedcollections` is very small.  It's mostly just recipes.  It is also maintained by the same developer of `sortedcontainers`.  I think it's just an overflow library for recipes that are slightly out of scope.  This is the code that we would use from `sortedcollections`.

```python
class ValueSortedDict(SortedDict):
    """Sorted dictionary that maintains (key, value) item pairs sorted by value.

    - ``ValueSortedDict()`` -> new empty dictionary.

    - ``ValueSortedDict(mapping)`` -> new dictionary initialized from a mapping
      object's (key, value) pairs.

    - ``ValueSortedDict(iterable)`` -> new dictionary initialized as if via::

        d = ValueSortedDict()
        for k, v in iterable:
            d[k] = v

    - ``ValueSortedDict(**kwargs)`` -> new dictionary initialized with the
      name=value pairs in the keyword argument list.  For example::

        ValueSortedDict(one=1, two=2)

    An optional key function callable may be specified as the first
    argument. When so, the callable will be applied to the value of each item
    pair to determine the comparable for sort order as with Python's builtin
    ``sorted`` function.

    """
    def __init__(self, *args, **kwargs):
        args = list(args)
        if args and callable(args[0]):
            func = self._func = args[0]
            def key_func(key):
                "Apply key function to ``mapping[value]``."
                return func(self[key])
            args[0] = key_func
        else:
            self._func = None
            def key_func(key):
                "Return mapping value for key."
                return self[key]
            if args and args[0] is None:
                args[0] = key_func
            else:
                args.insert(0, key_func)
        super(ValueSortedDict, self).__init__(*args, **kwargs)

    def __delitem__(self, key):
        "``del mapping[key]``"
        if key not in self:
            raise KeyError(key)
        self._list_remove(key)
        self._delitem(key)

    def __setitem__(self, key, value):
        "``mapping[key] = value``"
        if key in self:
            self._list_remove(key)
            self._delitem(key)
        self._setitem(key, value)
        self._list_add(key)

    def copy(self):
        "Return shallow copy of the mapping."
        return self.__class__(self._func, self._load, self.iteritems())

    __copy__ = copy
```

**Comment by pitrou** [comment]
Great, no problem from me, then.

**Comment by mrocklin** [comment]
We now depend on sortedcollections
