### ISSUE TITLE
as_completed gives unhelpful error message when passed empty list

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#727]
```
from distributed import as_completed
for a in as_completed([]):
    print(str(a))
```
gives error `NotImplementedError: as_completed on many event loops not yet supported`

which doesn't obviously make sense.

**Comment by mrocklin** [comment]
Agreed.  Do you have any interest in submitting a PR to fix this?

**Comment by rbubley** [comment]
Unfortunately, I don't currently feel competent to.
