### ISSUE TITLE
many "Lost connection ... Stream is closed" messages in logs

### ISSUE THREAD

**Issue by vincentschut** [dask/distributed#730]
while trying to get the local_client fibonacci example working, I always get logs like this:

scheduler log:
<pre>
vincent@localhost:~$ dask-scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:        192.168.0.102:8786
distributed.scheduler - INFO -        http at:        192.168.0.102:9786
distributed.bokeh.application - INFO - Web UI: http://192.168.0.102:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
distributed.core - INFO - Connection from 192.168.0.102:51142 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51144 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51146 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51292 to Scheduler
distributed.scheduler - INFO - Register 192.168.0.102:43739
distributed.scheduler - INFO - Starting worker compute stream, 192.168.0.102:43739
distributed.core - INFO - Connection from 127.0.0.1:40528 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:40530 to Scheduler
distributed.scheduler - INFO - Receive client connection: a8f8a406-bc64-11e6-b712-441ca8e20fe7
distributed.core - INFO - Connection from 192.168.0.102:51574 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51576 to Scheduler
distributed.scheduler - INFO - Receive client connection: a8f99f00-bc64-11e6-a7dc-441ca8e20fe7
distributed.core - INFO - Connection from 192.168.0.102:51578 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51580 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51582 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51584 to Scheduler
distributed.scheduler - INFO - Receive client connection: a8feae6e-bc64-11e6-901a-441ca8e20fe7
distributed.scheduler - INFO - Receive client connection: a8feca5c-bc64-11e6-b6e0-441ca8e20fe7
distributed.core - INFO - Connection from 192.168.0.102:51588 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51590 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51592 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51594 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51596 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51598 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51600 to Scheduler
distributed.scheduler - INFO - Receive client connection: a9070992-bc64-11e6-9820-441ca8e20fe7
distributed.scheduler - INFO - Receive client connection: a90732b4-bc64-11e6-a507-441ca8e20fe7
distributed.scheduler - INFO - Receive client connection: a906f844-bc64-11e6-b80a-441ca8e20fe7
distributed.core - INFO - Connection from 192.168.0.102:51604 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51608 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51610 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51612 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51614 to Scheduler
distributed.scheduler - INFO - Receive client connection: a9121bd4-bc64-11e6-acbf-441ca8e20fe7
distributed.scheduler - INFO - Receive client connection: a9121a9e-bc64-11e6-90b4-441ca8e20fe7
distributed.core - INFO - Connection from 192.168.0.102:51616 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51618 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51620 to Scheduler
distributed.core - INFO - Connection from 192.168.0.102:51622 to Scheduler
distributed.scheduler - INFO - Receive client connection: a918cfec-bc64-11e6-a956-441ca8e20fe7
distributed.scheduler - INFO - Receive client connection: a9190b88-bc64-11e6-a4d5-441ca8e20fe7
distributed.scheduler - INFO - Remove client a9190b88-bc64-11e6-a4d5-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51622) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a9190b88-bc64-11e6-a4d5-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51620) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a918cfec-bc64-11e6-a956-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51618) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a918cfec-bc64-11e6-a956-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51616) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a9121a9e-bc64-11e6-90b4-441ca8e20fe7
distributed.scheduler - INFO - Close client connection: a9121a9e-bc64-11e6-90b4-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51608) while sending result: Stream is closed
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51612) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Remove client a9121bd4-bc64-11e6-acbf-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51614) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a9121bd4-bc64-11e6-acbf-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51610) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a9070992-bc64-11e6-9820-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51600) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a9070992-bc64-11e6-9820-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51590) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a906f844-bc64-11e6-b80a-441ca8e20fe7
distributed.scheduler - INFO - Close client connection: a906f844-bc64-11e6-b80a-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51592) while sending result: Stream is closed
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51596) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Remove client a8feae6e-bc64-11e6-901a-441ca8e20fe7
distributed.scheduler - INFO - Close client connection: a8feae6e-bc64-11e6-901a-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51582) while reading message: Stream is closed. Last operation: identity
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51578) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a90732b4-bc64-11e6-a507-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51598) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a90732b4-bc64-11e6-a507-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51594) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a8feca5c-bc64-11e6-b6e0-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51584) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a8feca5c-bc64-11e6-b6e0-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51580) while sending result: Stream is closed
distributed.scheduler - INFO - Remove client a8f99f00-bc64-11e6-a7dc-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51576) while reading message: Stream is closed. Last operation: identity
distributed.scheduler - INFO - Close client connection: a8f99f00-bc64-11e6-a7dc-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('192.168.0.102', 51574) while sending result: Stream is closed
distributed.core - WARNING - Lost connection to ('127.0.0.1', 40530) while reading message: Stream is closed. Last operation: gather
distributed.scheduler - INFO - Remove client a8f8a406-bc64-11e6-b712-441ca8e20fe7
distributed.scheduler - INFO - Close client connection: a8f8a406-bc64-11e6-b712-441ca8e20fe7
distributed.core - WARNING - Lost connection to ('127.0.0.1', 40528) while sending result: Stream is closed
</pre>

worker log:
<pre>
vincent@localhost:~$ dask-worker 192.168.0.102:8786 --nprocs 1 --nthreads 1
distributed.nanny - INFO -         Start Nanny at:        192.168.0.102:36655
distributed.worker - INFO -       Start worker at:        192.168.0.102:43739
distributed.worker - INFO -              bokeh at:        192.168.0.102:8789
distributed.worker - INFO -              nanny at:        192.168.0.102:36655
distributed.worker - INFO -               http at:        192.168.0.102:40725
distributed.worker - INFO - Waiting to connect to:        192.168.0.102:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.52 GB
distributed.worker - INFO -       Local Directory:        /tmp/nanny-m1eyqzjx
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:        192.168.0.102:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Connection from 192.168.0.102:38094 to Worker
distributed.nanny - INFO - Nanny 192.168.0.102:36655 starts worker process 192.168.0.102:43739
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.client - WARNING - Client report stream closed to scheduler
distributed.core - INFO - Connection from 192.168.0.102:38426 to Worker
distributed.core - INFO - Connection from 192.168.0.102:38430 to Worker
</pre>

(I'm running the worker with --nthreads 1 --nprocs 1 because of #726)

The fibonacci example (slightly edited from the docs at http://distributed.readthedocs.io/en/latest/task-launch.html#submit-tasks-from-worker) is this:
```
from distributed import Client, local_client

client = Client('127.0.0.1:8786')

def fib(n):
    if n < 2:
        return n
    else:
        with local_client() as lc:
            a = lc.submit(fib, n - 1)
            b = lc.submit(fib, n - 2)
            a, b = lc.gather([a, b])
            return a + b

future = client.submit(fib, 10)

print(future)

print(future.result())
```

Though the result seems to be correct, the 'stream closed' messages look problematic to me. Should I be worried?

**Comment by mrocklin** [comment]
Currently we create and throw away a new connection every time a worker connects to another.  The fact that you're seeing WARNING logs is a sign that we're not doing this as cleanly as we should, but generally all of this is fine (if a little inefficient)

**Comment by vincentschut** [comment]
OK, thanks for the clarification. It's just that I'm trying to squash some bugs/problems in my code, and wondered if those closed connection could have anything to do with it. For the time being, I'll just assume these warnings are non-critical and not influencing the functioning of the code.

**Comment by mrocklin** [comment]
I appreciate the detailed error reports.  We've been changing a lot of
things recently and it's reassuring to know that there are developer/user
out there who will speak up.

**Comment by vincentschut** [comment]
And I appreciate the quick and valuable feedback, even if an issue does not appear to be a bug. It is really motivating to keep using dask and develop our processing chains with it, and helps me a lot getting to know and understand it.
