### ISSUE TITLE
CommClosedError

### ISSUE THREAD

**Issue by jmttran** [dask/distributed#7305]
**Describe the issue**: 
When running many dask programs in parallel, I consistently keep receiving 2 errors for some of my jobs:

- asyncio.exceptions.CancelledError
- distributed.comm.core.CommClosedError: ConnectionPool closing.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

This is being called by a shell script being run on a Linux server that draws from multiple python files to conduct each job, so I am not sure that I could provide MCVE code. I considered that this error could be because the job was running too many jobs on the same port, but even after setting scheduler_port=0 for dask.distributed.LocalCluster the same errors keep occurring. When I resubmit the job, I still get errors but some of the jobs that weren't able to be completed during the previous runthrough will be completed correctly.

**Environment**:

- Dask version:
- Python version: 3.9.13
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by jmttran** [comment]
![Error Part 1](https://user-images.githubusercontent.com/109187158/201761982-debcab8a-9891-4d25-9e23-439732d1cc6d.jpg)
![Error Part 2](https://user-images.githubusercontent.com/109187158/201761988-c985d769-90bd-4504-9c71-177887b52e88.jpg)

**Comment by ncclementi** [comment]
@jmttran Is a bit hard to tell what's going on from the screenshots. Do you have a minimal reproducible example we can run https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

What dask and distributed version are you running? 

This might also help https://stackoverflow.com/questions/54769782/distributed-worker-warning-heartbeat-to-scheduler-failed

**Comment by jmttran** [comment]
Hi! The main code is from [here](https://github.com/XiaYangLabOrg/SCING/blob/main/src/MergeNetworksHelpers.py) and we were thinking it could be an issue with the loc_cluster call (line 211). 

This is running on version 2022.7.0.

**Comment by fjetter** [comment]
Can you reproduce your issue on a more recent version as well?

**Comment by jmttran** [comment]
Updating the version helped eliminate the original error, but I'm getting different errors: 

- tornado.iostream.StreamClosedError: Stream is closed
- distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:37468 remote=tcp://127.0.0.1:38354>: Stream is closed

I believe the first error may be from the server, but the latter error could be something with dask (in the case it's not also a server error)?
