### ISSUE TITLE
Asynchronous long-running tasks on workers

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#731]
Dask is able to reason about and run long-running tasks on workers that themselves launch other tasks.  This enables some powerful and novel workflows.  http://distributed.readthedocs.io/en/latest/task-launch.html#extended-example

This system launches a separate thread for the long-running task to divorce it from the normal thread pool.  It then creates a local Client object and uses the synchronous API with that client.  

There may be some benefit to launching a long-running task inside of the main worker thread, running on the same IOLoop as the administrative worker code.  This has a few potential benefits:

1.  It might be less hacky than the current separate thread solution
2.  It would give the long-running task thread-safe access to the worker
3.  It would enable experimentation with asynchronous APIs in Python 3.5, which might bear long term fruit.

This would be useful for example in cases where we know the worker is sitting on some other data source, like a Kafka queue, and we want it to just pump that data into the system forever.  

cc @pitrou this sounds like the sort of thing that might interest you.

**Comment by pitrou** [comment]
> There may be some benefit to launching a long-running task inside of the main worker thread, running on the same IOLoop as the administrative worker code

I suppose this assumes the long-running task is written as a coroutine, and yields execution at selected points to ensure reactivity to external requests. I agree it sounds useful to allow advanced users to run other "async" code on the same IO loop as the Worker.

**Comment by mrocklin** [comment]
Yes, the long running task would probably just be doing communication and administrative work.  We would have to encourage this strongly in documentation.

**Comment by pitrou** [comment]
I'll try to tackle this soon.
