### ISSUE TITLE
Prometheus metric for memory/time used per task prefix

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#7341]
We have some metrics around number of tasks completed over time.  I think that we could use a couple of others:

1.  Amount of time spent in each prefix.  I think that we already store this data in all_durations (I brought this up when @ntabris did his work before as probably what we actually wanted, rather than number of tasks completed).
2. Amount of memory currently used by each prefix.  This is probably not a counter, but instead an instantaneous measurement of current state

This would be useful for after-the-fact debugging of clusters.  @dchudz was curious about this.  @fjetter is this easy for someone on your team to do?

**Comment by mrocklin** [comment]
Currently queued/processing per prefix might also be interesting.

**Comment by ntabris** [comment]
For (1) if we can get that as a cumulative total, that would be great.

For the memory gauge, what's the time resolution at which that's useful data?

**Comment by dchudz** [comment]
@fjetter any sense of where this fits into your next few days/weeks/months?

**Comment by crusaderky** [comment]
Do we already have number of completed tasks per prefix? We need it in order to calculate mean task runtime grouped by prefix

**Comment by mrocklin** [comment]
Internal metrics on the scheduler.

**Comment by crusaderky** [comment]
We need to export the count of tasks per prefix to Prometheus, so that grafana/whatever can calculate mean runtimes.
