### ISSUE TITLE
Expose worker deaths in programmatically consumable cluster event log

### ISSUE THREAD

**Issue by randerzander** [dask/distributed#7375]
When running a lengthy series of benchmarks where we push the envelope of memory usage, workers often restart.

Since the benchmark boils down to waiting for `ddf.compute()` to complete, the user may never know that workers were restarting behind the scenes.

The problem manifests in benchmark runtimes where there's "randomly" a large increase in observed runtime:
```
'somebench_runtimes':     [46.55358576774597, 17.916640996932983, 26.908658981323242, **77.93276262283325**, 17.211974382400513]
```

This makes experimenting with optimization attempts difficult, as a worker death can "silently" throw off results.

It's worth noting explicitly, for a single benchmark, one can watch the dashboard and notice when a worker dies. However, for long jobs, and more so for testing a large number of jobs, it becomes extraordinarily difficult to discern from the dashboard or from scheduler & worker text logs which specific benchmark might actually have experienced a worker restart.

Is there a way to query the scheduler for cluster events like a worker restarting, joining, leaving, being evicted?

**Comment by fjetter** [comment]
We're logging this on the scheduler, see https://distributed.dask.org/en/stable/logging.html#structured-logs

the event you are looking for is logged on the topics `all` and there is a specific topic for every worker named by it's address. The message logged is something like

```python
event_msg = {
    "action": "remove-worker",
    "processing-tasks": {ts.key for ts in ws.processing},
}
```

you can either run `client.get_events` and parse the messages for a failure (note, the event is also emitted on ordinary shutdown) or even register a hook that is called automatically if an event is emitted on a given topic, see https://distributed.dask.org/en/stable/api.html#distributed.Client.subscribe_topic e.g.

```python
def print_if_worker_died_while_computing(event):
    timestamp, msg = event
    if msg.get("action") == "remove-worker" and msg["processing-tasks"]:
        print("oh no!")
client.subscribe_topic("all", print_if_worker_died_while_computing)
```

**Comment by randerzander** [comment]
Thanks, @fjetter ! That's exactly what I needed!
