### ISSUE TITLE
incorrect batch_size docstring?

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#7382]
The docstring for `client.map` says:

```
        batch_size : int, optional
            Submit tasks to the scheduler in batches of (at most)
            ``batch_size``.
            Larger batch sizes can be useful for very large ``iterables``,
            as the cluster can start processing tasks while later ones are
            submitted asynchronously.
```

If I'm understanding things correctly (it's possible I'm not), the idea that larger batch sizes allow the cluster to start processing sooner is incorrect. (Just the opposite in fact: A huge batch delays processing, e.g. in the extreme case of one huge batch if batch_sizes isn't passed.)

It seems (again, if I'm following the code) that:

* the benefit of *smaller* batches the cluster can start processing sooner
* the benefit of *larger* batches is avoiding the overhead of many small batches

If my understanding is correct, I'd be happy to open a PR to rework this docstring.

I'd also like to say in the docstring what the default behavior is (just one batch with everything, if I'm reading the code right).

**Comment by jrbourbeau** [comment]
Good catch @dchudz! You're understanding is correct

> I'd be happy to open a PR to rework this docstring

That'd be great -- thanks! 

> I'd also like to say in the docstring what the default behavior is (just one batch with everything, if I'm reading the code right).

+1. I was thinking the same thing when reading the docstring.

**Comment by phobson** [comment]
The docstring is confusing and needs to be clarified, but let me take a stab at what it's trying to say:

if you're mapping over, say `range(1e7)` but your batch_size is 100, you'll spend more time waiting for the next batch to be submitted. In other words, batches that are too small could be computed before the next one is fully submitted. 

To your point If your batch_size was 1e6, you'd bog down the scheduler with each submission.

As I understand it, you can think of this like a weird optimization problem where you want your batch_size to be large enough that your client be can consistently submitting things, your workers are always have ~batch_size of tasks to dor45 and the scheduler is never overloaded with too many tasks.
