### ISSUE TITLE
Documentation about worker resources with dask.annotate is wrong

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7397]
Our documentation about worker resources is providing false examples

https://distributed.dask.org/en/stable/resources.html#example

It suggests to use the `dask.annotate(resources=...)` ctx manager in combination with `client.submit` but this is not implemented and never tested.
Annotations via the ctx manager are only picked up if the computation is defined using a `dask` collection or `dask.delayed`.

**Comment by jrbourbeau** [comment]
Hmm, I think this should still work as we pick up annotations specified by `dask.annotate(...)` in `Client._graph_to_futures`, which is called when computing Dask collections or `client.submit` / `client.map`

https://github.com/dask/distributed/blob/7fb9c484d9ecc1398754c027ecdabc754f5b9fe8/distributed/client.py#L3005-L3006

Suggesting we add a corresponding test over in https://github.com/dask/distributed/pull/7399
