### ISSUE TITLE
Zstandard compression is not thread safe

### ISSUE THREAD

**Issue by dwragge** [dask/distributed#7403]
**Describe the issue**:

In `compression.py` we create a singleton `ZstdCompressor` and `ZstdDecompressor` object. The docs for the Zstandard library [state](https://github.com/indygreg/python-zstandard/blob/main/zstandard/backend_cffi.py#L1764):

> Unless specified otherwise, assume that no two methods of ``ZstdCompressor`` instances can be called from multiple Python threads simultaneously. In other words, assume instances are not thread safe unless stated otherwise.

**Minimal Complete Verifiable Example**:
This can trivially be reproduced by introducing threading to the `test_maybe_compress` test in `test_protocol.py`

Some errors that I've reproduced range from compression/decompression failure, to seg faults. Examples for searchability:

```
Fatal Python error: Segmentation fault

Thread 0x000000030df25000 (most recent call first):
  File "/Users/dwragge/code/distributed/distributed/protocol/compression.py", line 92 in zstd_compress
  File "/Users/dwragge/code/distributed/distributed/protocol/compression.py", line 186 in maybe_compress
  File "/Users/dwragge/code/distributed/distributed/protocol/tests/test_protocol.py", line 148 in test_compress_decompress
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 870 in run
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/Users/dwragge/miniconda/envs/dask-distributed/lib/python3.8/threading.py", line 890 in _bootstrap
```

-  `zstd.ZstdError: cannot compress: Src size is incorrect`
- `zstd.ZstdError: cannot compress: Operation not authorized at current processing stage`
- `zstd.ZstdError: decompression error: Corrupted block detected`
- `zstd.ZstdError: error determining content size from frame header`
- `zstd.ZstdError: decompression error: Unknown frame descriptor`
- `zstd.ZstdError: decompression error: Destination buffer is too small`

This manifests in production as errors such as:

- `distributed.core - ERROR - Exception while handling op get_data`
- `distributed.worker - ERROR - failed during get data with tcp://a.b.c.d:39195 -> tcp://d.e.f.g:43787`
- `distributed.protocol.core - CRITICAL - Failed to deserialize`

Amongst others, including clear lost workers, and `CommClosedError`s.

**Anything else we need to know?**:

The fix is trivial (instantiate a new Zstd(De)Compressor instance for each compression. I will raise a PR to fix plus tests.

**Comment by mrocklin** [comment]
Thank you for the issue and for the fix @dwragge .  Hopefully we'll get this in today.
