### ISSUE TITLE
Update dask.distributed to work with bokeh last version (bokeh 3.0.3)

### ISSUE THREAD

**Issue by frbelotto** [dask/distributed#7414]
Hello!
Dask has been updated to work with python 3.11.
I am trying to start dask distributed but I got this results :

```
Dask needs bokeh >= 2.4.2, < 3 for the dashboard.
You have bokeh==3.0.3.
Continuing without the dashboard.
  warnings.warn(
```

Any expectations to support the last version?

Thanks in advance!

**Comment by mrocklin** [comment]
This is ongoing.  I think that @jrbourbeau is tracking this the closest.

**Comment by consideRatio** [comment]
Not sure what pr/issue to track to keep updated about development efforts, I'm linking together a few here.

### Related PRs and issues
- #7413 
- #7173
- #7362
- #7512

**Comment by FedericoMuciaccia** [comment]
I can confirm that the issue is still present (March 2023). Any update on the topic?

```
>>> local_cluster = dask.distributed.LocalCluster()
UserWarning: 
Dask needs bokeh >= 2.4.2, < 3 for the dashboard.
You have bokeh==3.1.0.
Continuing without the dashboard.
  warnings.warn(
>>> dask.distributed.__version__
'2023.2.0'
>>> dask.__version__
'2023.2.0'
>>> bokeh.__version__
'3.1.0'
```
