### ISSUE TITLE
`string[pyarrow]` dtype does not roundtrip in P2P shuffling

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#7420]
As discovered in #7410, `string[pyarrow]` columns do not roundtrip in a P2P shuffle but get converted to `string[python]` instead.

**Comment by jrbourbeau** [comment]
Might be https://github.com/pandas-dev/pandas/issues/50074?

**Comment by mrocklin** [comment]
Any thoughts or plans on how we should resolve this?  This seems fairly important to me

**Comment by hendrikmakait** [comment]
Not yet. So far, we have not seen much urgency in fixing this. https://github.com/dask/dask/issues/10326 finally highlighted its impact.
 
I am currently prioritizing getting P2P rechunking in a shape where it can become a possible default (dask/dask#10226) and failure recovery (#7353) over this.
