### ISSUE TITLE
Dask Dashboard doesn't wokk behind a proxy

### ISSUE THREAD

**Issue by chaokunyang** [dask/distributed#7438]
**Describe the issue**:
Dask Dashboard will be empty when accessed behind a proxy:

![image](https://user-images.githubusercontent.com/12445254/210032925-de2543eb-4fe6-4ea7-9bab-9b65cebe6540.png)

Is this related the proxy address we use? We used an absolute proxy path. In `https://antc.alipay.com/proxy/ray/33.176.48.250:34269/tasks`, the `https://antc.alipay.com/proxy/ray` are proxy address, `33.176.48.250:34269/tasks` are real dask dashboard address.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.2.0
- Python version: 3.7.9
- Operating System: linux
- Install method (conda, pip, source):pip

**Comment by chaokunyang** [comment]
Seems the websockets doesn't work behind the proxy

**Comment by mrocklin** [comment]
There are certainly groups that use the Dask dashboard behind a proxy (pangeo, coiled, anyone using JupyterHub's proxy).  As you suggest, it might be that your proxy doesn't proxy through websockets.  That would be useful to check (this isn't a Dask issue, it has to do with the proxy that you're using).

**Comment by chaokunyang** [comment]
It's an issue in out proxy, after some changes with our tomcat proxy, scheduler proxy works fine. Worker proxy doesn't work still since it still use old link.

**Comment by jrbourbeau** [comment]
@chaokunyang is it safe to close this issue?
