### ISSUE TITLE
__str__() of Nanny can fail

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#751]
In `nanny.py`:
`__str__()` of `Nanny` relies on `worker_address`, which in turn relies on `worker_port`. This is initially set to `None`, so it can result in:

`TypeError: %d format: a number is required, not NoneType`

**Comment by mrocklin** [comment]
Indeed.  It would be good to relax that assumption.  

Can I interest you to submitting a small PR to resolve the issue?

**Comment by mrocklin** [comment]
Resolved
