### ISSUE TITLE
Double logging with old style config

### ISSUE THREAD

**Issue by tkorvola** [dask/distributed#7518]
If `distributed` sets a handler for a logger, it should also set `propagate = False`. It used to do so in 2021.3.0 but not any more. Duplicate logging is likely. This only applies to old style config, which does not explicitly define handlers (new style config is processed by the `logging` module).

```python
import logging, distributed
logging.basicConfig()
logging.getLogger('distributed').info("Hello")
```

**Environment**:

- Dask version: 2023.1.1
- Python version: 3.8.15
- Operating System: Linux
- Install method (conda, pip, source): Docker (daskdev/dask:latest)

**Comment by tkorvola** [comment]
Apparently PR #5669 caused this. If propagation is the desired behaviour, then I guess `distributed` should not set any handlers except perhaps on root if it has none.

**Comment by fjetter** [comment]
cc @crusaderky

**Comment by fjetter** [comment]
Closed by https://github.com/dask/distributed/pull/7750
