### ISSUE TITLE
'cannot import name 's3''

### ISSUE THREAD

**Issue by arokem** [dask/distributed#755]
Trying to follow the instructions here: 

http://distributed.readthedocs.io/en/latest/ec2.html

This works neither on ec2, nor on my laptop (Mac OS 10.12, dask and distributed installed using conda)

**Comment by jdoepfert** [comment]
same here

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/distributed/commit/215c567f3f91232bdc33b017148841746b5bac21
