### ISSUE TITLE
Safe asyncio timeout for python 3.11 and above

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7570]
Python 3.11 introduced the [`asyncio.timeout`](https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout) which resolves a couple of consistency issues with `asyncio.wait_for`, see

https://github.com/dask/distributed/pull/6235
Closes https://github.com/dask/distributed/issues/6211 (for python 3.11)

We should offer a `utils.wait_for` function that uses `asyncio.timeout` if available to avoid these problematic cases. All occurrences of `asyncio.wait_for` in our code base should then be replaced by this.

cc @graingert

**Comment by mrocklin** [comment]
I'll be curious to see if CI cleans up significantly in 3.11
