### ISSUE TITLE
Flaky `test_deadlock_cancelled_after_inflight_before_gather_from_worker`

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7576]
There are a couple of failures of `test_deadlock_cancelled_after_inflight_before_gather_from_worker` where the test appears to be stuck. I'm not entirely sure if this is a genuine deadlock or if the test assumption is false.

https://dask.github.io/distributed/test_short_report.html

![image](https://user-images.githubusercontent.com/8629629/220659512-d6da23f4-d635-4873-80d6-c36765cc9e49.png)

@crusaderky would you mind having a look?

E.g. https://github.com/dask/distributed/actions/runs/4217468785/jobs/7321274520

```
E                   asyncio.exceptions.TimeoutError: Test timeout after 30s.
E                   ========== Test stack trace starts here ==========
E                   Stack for <Task pending name='Task-136823' coro=<test_deadlock_cancelled_after_inflight_before_gather_from_worker() running at D:\a\distributed\distributed\distributed\tests\test_cancelled_state.py:736>> (most recent call last):
E                     File "D:\a\distributed\distributed\distributed\tests\test_cancelled_state.py", line 736, in test_deadlock_cancelled_after_inflight_before_gather_from_worker
E                       await wait_for_state(fut2.key, intermediate_state, b, interval=0)
```

There are a lot of logs like

```
2023-02-19 18:22:48,395 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:63020'.
...
2023-02-19 18:22:48,410 - distributed.worker - ERROR - Scheduler was unaware of this worker 'tcp://127.0.0.1:63020'. Shutting down.

```

so this looks a bit suspicious.

**Comment by crusaderky** [comment]
Never failed since March 30th
