### ISSUE TITLE
get_data() never offloads serialization

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7589]
In theory, when a message is >10 MiB, both gather_dep and get_data should offload (de)serialization to a separate thread.
This works for gather_dep, but doesn't for get_data:

```python
import random
import threading
from distributed.utils_test import gen_cluster

@gen_cluster(client=True)
async def test1(c, s, a, b):
    print("main thread", threading.get_ident())
    n = 200_000_000
    class C:
        def __sizeof__(self):
            return n

        def __getstate__(self):
            print("__getstate__", threading.get_ident())
            return random.randbytes(n)

        def __setstate__(self, state):
            print("__setstate__", threading.get_ident())

    x = c.submit(C, key="x", workers=[a.address])
    y = c.submit(lambda x: None, x, key="y", workers=[b.address])
    await y
```
Output:
```
main thread 139750127130432
__getstate__ 139750127130432
__getstate__ 139750127130432
__getstate__ 139750127130432
__setstate__ 139749812926016
```
If you put a breakpoint in `__getstate__`, the stack trace confirms that offload is not involved.

This can cause the worker to become poorly responsive, for the following types of data:
- Dataframes with pure-python string types
- Bespoke pure-python data
- In general, any data where the output of `pickle.dumps` is non-negligible compared to the size of the pickle5 buffers (if any)
- Compressible numpy and pandas data, even when it uses pickle5 buffers. This last use case is particularly bad because compression releases the GIL, so running it on a different thread would leave the main thread completely free.

Notably, as of today the [coiled-runtime benchmarks](https://github.com/coiled/coiled-runtime) do not capture the last use case, as most of them start from `da.random.random` which produces uncompressible output.

**Comment by fjetter** [comment]
This is incredible.... good find @crusaderky !

Turns out that our sizeof implementation actually does what it is intended to. It walks the message recursively and dispatches everything.

Eventually, it reaches the data class `C`. However, this class C is wrapped in `protocol.serialize.Serialize` which doesn't have a dispatch registered, i.e. we're dispatched to the object sizeof which is just `sys.getsizeof`... i.e. instead of registering 200MB, it registers 48 bytes 😱
