### ISSUE TITLE
Link to dashboard docs on the dashboard

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#7592]
It's not immediately obvious from the dashboard how you'd learn more about what all the things on it mean. Now that we have more [documentation](https://docs.dask.org/en/stable/dashboard.html) about it (thanks to @ncclementi especially), we should have links to the docs from the dashboard itself.

Ideally, it could be nice to have a `?` link on each component that would take you to the appropriate section of the docs for that component. For example, the progress section could link you to https://docs.dask.org/en/stable/dashboard.html#progress.

**Comment by fjetter** [comment]
I added am Info Icon / Help tool for the task stream in https://github.com/dask/distributed/pull/7478 Clicking this icon will direct you to the docs.

If somebody wants to make some progress on this, adding similar help tools for other panels should be straight forward.


![image](https://user-images.githubusercontent.com/8629629/212711868-323f8095-66b2-445b-9100-b1bcde2f0139.png)

I wonder if it's also possible to add a global help tool or smth like that

**Comment by gjoseph92** [comment]
That's a great start, thanks.

> I wonder if it's also possible to add a global help tool or smth like that

I'm not sure what a global help tool would look like, but just a global "dashboard docs" link in some corner would also be a good idea, since it might be more visible than the subtle `?` symbols in the bokeh plots.

**Comment by ncclementi** [comment]
Just as a reference I wanted to have a hover tool on the title of the plots, but it was not possible, I opened this issue in bokeh a while ago but no luck https://github.com/bokeh/bokeh/issues/11389
