### ISSUE TITLE
How-to for job schedulers (SLURM, Torque, etc..)

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#76]
Some users will want to launch distributed via job schedulers like SLURM, or Torque, which are commonly found in academic or research institutions.  We should build documentation to aid these users on how to best deploy `distributed` in these settings.

cc @stefanv @pwolfram @rabernat

Notably, there is a bit of a challenge here because we need to communicate to the worker processes where the scheduler process is.  We also need the scheduler process to know that it should be the scheduler process and run `dscheduler` rather than `dworker` accordingly.

**Comment by mrocklin** [comment]
For SLURM it looks like there is an environment variable `$SLURM_NODELIST`, that might be helpful here.  Is this reliably present on all SLURM systems?

**Comment by mrocklin** [comment]
Looks like the equivalent environment variables in PBS include

```
PBS_NODEFILE, which point to a file that lists the hosts (compute nodes) on which the job is run,
PBS_JOBID, which is a unique number PBS assigns to a job and
```

**Comment by pwolfram** [comment]
I just confirmed the existence of `$SLURM_NODELIST` on our systems.

**Comment by mrocklin** [comment]
What does it look like?  We're at an odd situation where you know the information that slurm provides and I know what information distributed needs but neither of us knows both.  How quickly are you able to iterate with your slurm cluster?  I'd be down to hop back on a screenshare (with you driving) if we can knock this out.

**Comment by pwolfram** [comment]
Sounds like a good idea, sorry for the slow response.  Are you still up for this?  I could try this from now until 6pm MST when I head home.  Feel free to ping me at the lanl account.  I could try later tonight or tomorrow although I think tomorrow may be easier.  I haven't installed distributed on the cluster, however.  I'm using conda but would probably do a custom install with pip or whatever you recommend unless there is a package that is already ready to go.

**Comment by mrocklin** [comment]
@koverholt suggested the following approach for SLURM

```
$ cat slurm_distributed.sh
#!/bin/bash
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out
#SBATCH -N 3

SCHEDULER=`srun -N 1 hostname; dscheduler --port 19007 1>&2 &`
echo SCHEDULER: $SCHEDULER

srun dworker $SCHEDULER:19007
```

**Comment by pwolfram** [comment]
Our awesome consultants got back to me and I'm reposting their information after a little filtering of my own:

```
#!/bin/bash
#MSUB -j oe                                                                     
                                                                                                                
module load gcc openmpi                                                                                         
                                                                                                                
# get files with environments for each node                                                                     
rm -rf sadc_outfile                                                                                             
mpirun -npernode 1 -mca btl tcp,self --output-filename sadc_outfile /bin/bash -c "/bin/env "                    
                                                                                                                
# filter nodes to get hostname file for scheduler and workers                                                                              
grep SLURMD_NODENAME sadc_outfile.1.* | sed 's/.*=//g' | sort > hostnames.txt        
                           
```

Presumably dcluster can be booted with this `hostnames.txt` file via 

```
$ dcluster --hostfile hostfile.txt
```

Is this correct @mrocklin?

**Comment by mrocklin** [comment]
Possibly.  Let me update a bit (it was lingering behind master) and then ping you.

**Comment by mrocklin** [comment]
@pwolfram `dcluster` is up and ready to go

**Comment by mrocklin** [comment]
@koverholt thanks for the SLURM example.  That was simpler than expected.

**Comment by venabled** [comment]
Echo the existence of $PBS_NODELIST on Torque systems, just a line for every host name which you can then use to ssh into.

**Comment by venabled** [comment]
From #214 

There's probably a more idiomatic way to do this, depending on your setup, but this is working for me:

```
#PBS -l select=xx:ncpus=yy:mpiprocs=1
#PBS -l walltime=00:30:00
#PBS -q queue
#PBS -m be
#PBS -j oe
#PBS -S /bin/bash

echo "number of nodes"
export PBS_NUM_NODES=`wc -l ${PBS_NODEFILE} | cut -f1 -d" "`
echo $PBS_NUM_NODES
echo "===================="
echo "ssh into each node"

#====================================================================
scheduler_node=$(head -1 $PBS_NODEFILE)
hostIndex=0
for host in `cat $PBS_NODEFILE`; do
    echo "Working on $host ...."
    if [ "$hostIndex" = "0" ]; then
        echo "run dscheduler"
        ssh $host dscheduler --port=8786 &
        sleep 5
    else
        echo "run dworker"
        ssh $host dworker --nprocs 1 --nthreads 1  $scheduler_node:8786 &
        sleep 1
    fi
    hostIndex="1"
done

echo "====-get to work-===="

ssh $scheduler_node
python distributed_executor.py
exit
```

**Comment by mwojcikowski** [comment]
I've created prototype for automatic scheduling, see #428

**Comment by mrocklin** [comment]
Closing in favor of #128
