### ISSUE TITLE
Ensure one CI job runs without pyarrow but with numpy

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7603]
P2P rechunking is an important new feature that requires numpy to be installed. We only have test jobs in our matrix that are installing pyarrow + numpy or neither but we should have a job running that only installs numpy.

This likely requires us to introduce a mindeps+numpy job since numpy is only a transitive dependency

**Comment by jrbourbeau** [comment]
Seems reasonable to me. @milesgranger is this something you're interested in working on?

**Comment by milesgranger** [comment]
You bet, I'd be happy to give it a go. :+1:
