### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#7641]
What do folks think about setting up some `CODEOWNERS` config? Right now I watch the whole notification tracker for distributed but regularly get overwhelmed by notifications and end up declaring bankruptcy and marking all as read. I'd love to get more targeted pings for review in the areas of dask/distributed that I can be helpful.

Opening this issue on distributed as its the place where I'm effective as a reviewer on ~20% of the code and therefore the signal to noise ratio is at its worst. But it could be helpful to set this up in other projects too.

**Comment by fjetter** [comment]
sure. if that helps, let's do it
