### ISSUE TITLE
Fine performance metrics: Bokeh dashboard

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7679]
- Part of #7665 
- Blocked by #7666 

Display the fine performance metrics collected on the scheduler by #7666 on the Bokeh dashboard.

Note that we have separate data for execute, gather-dep, get-data, and async spilling.
This ticket needs to be further refined with a design of what we want to display exactly and how.

**Comment by fjetter** [comment]
apart from the bokeh dashboard, I also think this should be part of the performance_report
