### ISSUE TITLE
Fine performance metrics: Prometheus and Grafana

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7680]
- Part of #7665 
- Blocked by #7666 

Export the metrics collected on the scheduler by #7666 to Prometheus.
For the sake of keeping everything additive, execute, gather-dep, get-data, and async spilling metrics should be kept separate.

**Coiled-specific deliverable**: implement new Grafana plots that use the above metrics.

**Comment by fjetter** [comment]
The current schema of the data we are storing would be helpful for this issue ahead of time. Essentially what we are storing in https://github.com/dask/distributed/issues/7666

**Comment by fjetter** [comment]
Right now, it's not entirely certain if we want to expose this as a timeseries so there is also room to simply attach this information to a `Computation` object

**Comment by fjetter** [comment]
@hendrikmakait @crusaderky I believe there was a meeting discussing this topic. Can either of you summarize the outcome of it here?

**Comment by hendrikmakait** [comment]
I'd be fine with closing this ticket as _not planned_ for now and reopening it at a later point in time. Providing E2E aggregates should be the priority for now.

**Comment by crusaderky** [comment]
Agreed
