### ISSUE TITLE
CI broken: The `ipykernel.comm.Comm` class has been deprecated

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7688]
CI is broken on Python 3.10 and 3.11.
Many tests fail with the message:

> DeprecationWarning: The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

e.g. https://github.com/dask/distributed/actions/runs/4473742414/jobs/7861483350?pr=7686

**Comment by crusaderky** [comment]
This morning the failure changed; and the whole CI is now red:

________ ERROR collecting distributed/diagnostics/tests/test_widgets.py ________
distributed/diagnostics/tests/test_widgets.py:18: in <module>
    from ipykernel.comm import Comm
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/ipykernel/__init__.py:5: in <module>
    from .connect import *  # noqa
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/ipykernel/connect.py:11: in <module>
    import jupyter_client
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_client/__init__.py:8: in <module>
    from .asynchronous import AsyncKernelClient  # noqa
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py:1: in <module>
    from .client import AsyncKernelClient  # noqa
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py:9: in <module>
    from ..client import KernelClient, reqrep
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_client/client.py:20: in <module>
    from .connect import ConnectionFileMixin
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_client/connect.py:20: in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_core/paths.py:208: in <module>
    deprecation(
/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/jupyter_core/utils/__init__.py:89: in deprecation
    warnings.warn(message, DeprecationWarning, stacklevel=stacklevel + 1)
E   DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
E   given by the platformdirs library.  To remove this warning and
E   see the appropriate new directories, set the environment variable
E   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
E   The use of platformdirs will be the default in `jupyter_core` v6

**Comment by crusaderky** [comment]
We've temporarily plugged the issue with #7689 + #7693.
However, gpuCI is failing with the same message.
@charlesbluca I couldn't find where the conda requirements file is for it; it looks like a pre-built docker image?

**Comment by jrbourbeau** [comment]
Just following up here. It looks like the two needed PRs are in. @charlesbluca could you launch an image rebuild whenever you get a moment?

**Comment by charlesbluca** [comment]
Yup, just triggered a rebuild
