### ISSUE TITLE
Update changelog to look like dask/dask

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#769]
The release notes of dask/distributed look different than those in dask/dask (which is a bit fancier).  It would be nice to align these two.  

@dukebody do you have any interest in repeating your effort in https://github.com/dask/dask/pull/1526

https://github.com/dask/distributed/blob/master/release-notes.md

**Comment by dukebody** [comment]
Hey @mrocklin! Yes I can do it, but I won't be available until a week from now. If this ticket can wait that long (I guess so) please assign it to me. :)

**Comment by mrocklin** [comment]
Very happy to wait.  Thanks for taking this on @dukebody !
