### ISSUE TITLE
Client set_as_default is ignored in case a config value is set

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7754]
https://github.com/dask/distributed/pull/7482 introduced a change in how we are setting and getting default clients.

Specifically, with this change we stopped (ab-)using the dask config to communicate whether there is a default client available or not. This was a necessary change since clients can be used in a threaded environment (e.g. worker tasks) and multiple clients may be active at the same time. When multiple clients are active, using the config as a discovery mechanism made it very difficult to set and reset the state properly when activating or closing the client.

From a users perspective this would also change the precedence of client discovery.

Before #7482

```python
import dask, distributed
dask.config.set(scheduler='synchronous')

client = distributed.Client(set_as_default=True)

assert dask.base.get_scheduler() is client.get
```

After 

```python
import dask, distributed
dask.config.set(scheduler='synchronous')

client = distributed.Client(set_as_default=True)

assert dask.base.get_scheduler() is 'synchronous'
```

The earlier behavior was possible because we silently overwrote the user config internally. Now, the config always takes precedence over a default client!

That configs should take precedence is mostly motivated by typically workflows where users are opting for a local compute even though a client exists.

```python
client = Client()
with dask.config.set(scheduler='sync'):
    dask.compute(compute_local)
dask.compute(compute_remote)
```

**Comment by hendrikmakait** [comment]
Would it make sense to utilize a `ContextVar` for changes made via `with dask.config.set(scheduler=...)` and adjust the precedence order to `with dask.config.set(scheduler=) > set_as_default > dask.config`?

**Comment by hendrikmakait** [comment]
cc @jrbourbeau

**Comment by fjetter** [comment]
I don't think a ContextVar approach would be sufficient for this since the defaultclient mechanism is what makes things troublesome and they don't work in contextmanagers, e.g. the following would still be difficult with contextvars

```python

# This is the old behavior and what we'd like to preserve. Switching to ContextVar + chaning precedence would enable this again
import dask, distributed
dask.config.set(scheduler='synchronous')

client = distributed.Client(set_as_default=True)

assert dask.base.get_scheduler() is client.get
```

However, the default client mechanism would still not work as expected. The examples below show how expected behavior _should_ work. However, the below cannot be achieved by simply rearranging precedence but rather it requires default clients and the context manager to operate on the same context (or global) variable.

```python
import dask, distributed
dask.config.set(scheduler='synchronous')

with dask.config.set(scheduler="threads"):
    client = distributed.Client(set_as_default=True)

    assert dask.base.get_scheduler() is client.get


import dask, distributed
dask.config.set(scheduler='synchronous')

client = distributed.Client(set_as_default=True)
with dask.config.set(scheduler="threads"):

    assert dask.base.get_scheduler() is "threads"

```
