### ISSUE TITLE
Add Prometheus counter for `SystemMonitor.last_time` to improve GIL contention metric

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#7767]
Currently, the loose coupling between the system monitor's update interval and the Prometheus scraping interval can cause artifacts like a relative GIL contention > 1 (https://github.com/dask/distributed/pull/7651#issuecomment-1490571845). By exposing the system monitor's update timestamp as a Counter, we would have a synchronized timestamp available in Prometheus to serve as the basis for rate calculations. This should make such artifacts impossible.

cc @ntabris, @gjoseph92, @milesgranger: Thoughts?

**Comment by hendrikmakait** [comment]
I think that we should then also convert the GIL contention metric to the (estimated) total GIL contention time. This would make it easier to understand the metric value than a cumulative sum of percentages and any difference between to measurements would be the same as for the time metric (i.e., an absolute timedelta).

**Comment by ntabris** [comment]
Makes sense to me.
