### ISSUE TITLE
File upload functionality can break with new pickle serialization changes

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#7797]
I have a local `my_code.py` file with a `foobar` function 

```python
# my_code.py

def foobar(x):
    return x
```

That I want to run on my remote workers in this snippet (here I'm using a Coiled cluster, but any cluster where the client and scheduler/workers don't share a filesystem will also have the issue):

```python
import coiled

if __name__ == "__main__":

    cluster = coiled.Cluster()
    client = cluster.get_client()

    # This file has my custom `foobar` function
    client.upload_file("my_code.py")

    from my_code import foobar

    f = client.submit(foobar, 123)
    print(f"{f.result() = }")
```

Previously this would work, but when I run the above snippet with `distributed=2023.4.0` I get the following error:

```
Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/scheduler.py", line 4276, in update_graph
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 432, in deserialize
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 98, in pickle_loads
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 96, in loads
    # the STOP opcode, passing the object that is the result of unpickling.
ModuleNotFoundError: No module named 'my_code'

The above exception was the direct cause of the following error:

Traceback (most recent call last):
  File "/Users/james/projects/dask/distributed/test_upload_file.py", line 14, in <module>
    print(f"{f.result() = }")
  File "/Users/james/projects/dask/distributed/distributed/client.py", line 317, in result
    raise exc.with_traceback(tb)
RuntimeError: Error during deserialization of the task graph. This frequently occurs if the Scheduler and Client have different environments. For more information, see https://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments
```

because `client.upload_file` only uploads the `my_code.py` file to workers, not the scheduler. But with our recent pickle serialization changes we now need `my_code.py` to be on the scheduler for things to work. 

Having `client.upload_file` also upload to the scheduler's filesystem seems fine to me

**Comment by milesgranger** [comment]
I can take this.

After some experimenting, looks like I'll move the `Worker.upload_file` into `ServerNode.upload_file` since both `Server` and `Worker` share that parent. From there, impl an `UploadFile(SchedulerPlugin)` and call both uploads in `Client.upload_file` to scheduler and workers.

**Comment by jrbourbeau** [comment]
Cool that sounds good @milesgranger. I think we'll need to add a `local_directory` to the scheduler too. Currently (I think) only workers / nannys have them, but adding to the scheduler seems fine
