### ISSUE TITLE
P2P shuffling is incompatible with low-level fusion

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#7816]
P2P shuffling heavily relies on the key of the barrier task to be known. This is used to look up the `TaskState` object, track its transition to clean up forgotten shuffles and pin output tasks to workers. With low-level fusion, the barrier task may be fused with other tasks and its name may get mangled in the process, which will prevent the shuffle to work as expected. 

To solve this, P2P shuffling should not rely on known the barrier task's key. 

One suggested approach looks as follows:
- The input task creating the shuffle run on the scheduler will also send its kkey. The extension can then track the transitions of this task. If it transitions to `forgotten`: The entire shuffle run has been forgotten and can be cleaned up. 
- Once the barrier starts, it sends its key to the scheduler. Now, the scheduler can proceed as before. 
- To deal with worker restrictions as implemented in #7801, we send them as part of the payload for the input tasks instead of pulling them off the `TaskState` object.

I may be missing something with this approach. 

cc @fjetter, @wence-

XREF: #7801

**Comment by fjetter** [comment]
Another angle to investigate: In the past we discussed the possibility of not having a dedicated barrier key. Back then we discarded the idea again due to complexity. Maybe we're in a better position to reconsider this and instead of working around this limitation we can just get rid of the **task** by embedding it's functionality in the unpack calls somehow. This would again introduce an all-to-all dependency between transfer and unpack tasks but since we're only submitting metadata this might not be that bad.

**Comment by hendrikmakait** [comment]
I see the appeal of this approach, it might also help to create with the locality-awareness of P2P rechunks. However, I'd like to leave a barrier task in and tackle removing the task in a follow-up step. I think these two items should be more or less orthogonal.

**Comment by mrocklin** [comment]
I'm confused here.  Under what conditions would the barrier task be fused?  This seems pretty unlikely to me, yes?

I mean, I guess maybe if someone increased the width of fusion to as large as the number of partitions that could happen, but we're talkinga about a pathological case here, correct?

**Comment by mrocklin** [comment]
If so, my recommendation would be to just ignore this and hope that in the future low-level task fusion doesn't exist.  I wouldn't be surprised if it goes away before a user actually runs into this.

**Comment by hendrikmakait** [comment]
@mrocklin: One instance of this has popped up in our test suite: https://github.com/dask/distributed/blob/e887fde05a636864f94e7880fd301923406a3db7/distributed/shuffle/tests/test_rechunk.py#L197

I'm not sure how often it happens in the wild, but we also recommend that people turn fusion off when using P2P rechunking.

**Comment by hendrikmakait** [comment]
@mrocklin: After running a few more tests, the above test does not fail if it returns > 1 output partitions. No other tests in `dask/dask` or `coiled/benchmarks` fail. So yes, it seems to be a pathological case. I'm not too familiar with the low-level optimizations within `dask/dask`, but given these results, I agree with your recommendation and suggest to de-prioritize this until users complain.

**Comment by mrocklin** [comment]
🎉
