### ISSUE TITLE
Cannot use `client.submit` when using `pytest` with a pre-existing cluster

### ISSUE THREAD

**Issue by rjzamora** [dask/distributed#7841]
**Describe the issue**:

There seem to be `pickle`-related problems when `client.submit` is used to submit a task to a scheduler that was generated outside the current pytest context. Providing a repro here in case others have thoughts here. Is this behavior known/expected?

**Minimal Complete Verifiable Example**:

I have the following code in `test_repro.py`:

```python
import os
from distributed import Client, LocalCluster, wait

def square_func(x):
    return x*x

def test_submit():
    # Get or create client
    dask_scheduler_file = os.environ.get("SCHEDULER_FILE", False)
    client = (
        Client(scheduler_file=dask_scheduler_file)
        if dask_scheduler_file
        else Client(LocalCluster())
    )

    # Submit simple function on workers
    results = [
        client.submit(square_func, 10, workers=[w])
        for w in client.scheduler_info()['workers']
    ]

    # Wait and shutdown
    wait(results)
    print(f"results: {results}")
    client.shutdown()

if __name__ == "__main__":
    test_submit()
```

The following works fine:

```
$ pytest -vs test_repro.py
```

I get pickle errors for the following:

```
$ dask scheduler --scheduler-file=scheduler.json
$ dask worker --scheduler-file=scheduler.json
$ SCHEDULER_FILE=scheduler.json pytest -vs test_repro.py
```

Although the test reports as "PASSED", the test prints out:

```
test_repro.py::test_submit results: [<Future: error, key: square_func-1022ec805a2fbffb852cfcf87f5b32cf>]
```

and the scheduler log shows the following traceback:

```
2023-05-17 08:08:15,584 - distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x05\x95Y\x01\x00\x00\x00\x00\x00\x00\x8c\x1edistributed.protocol.serialize\x94\x8c\x08ToPickle\x94\x93\x94)\x81\x94}\x94\x8c\x04data\x94\x8c\x13dask.highlevelgraph\x94\x8c\x0eHighLevelGraph\x94\x93\x94)\x81\x94}\x94(\x8c\x0cdependencies\x94}\x94\x8a\x06\x00\x11\xae\x1c\x13\x7f\x8f\x94s\x8c\x10key_dependencies\x94}\x94\x8c\x06layers\x94}\x94\x8a\x06\x00\x11\xae\x1c\x13\x7fh\x06\x8c\x11MaterializedLayer\x94\x93\x94)\x81\x94}\x94(\x8c\x0bannotations\x94N\x8c\x16collection_annotations\x94N\x8c\x07mapping\x94}\x94\x8c,square_func-1022ec805a2fbffb852cfcf87f5b32cf\x94\x8c\ntest_repro\x94\x8c\x0bsquare_func\x94\x93\x94K\n\x86\x94subsubsb.'
Traceback (most recent call last):
  File "/home/nfs/rzamora/workspace/cudf-23.06-v2/distributed/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'test_repro'
```

**Anything else we need to know?**:

The problem does **not** show up when the above code is run as a script (e.g. ` SCHEDULER_FILE=scheduler.json python test_repro.py`). In other words, the problem is specific to the combination of (1) using pytest, and (2) the cluster being generated outside of the pytest context.

**Environment**:

Latest `dask` and `distributed` development branches.

**Comment by rjzamora** [comment]
cc @pentschev

**Comment by rjzamora** [comment]
>pytest imports test modules by appending the directory they are in to the sys.path, however when you run your worker it doesn't have this sys.path mutation and so it won't be able to import your test module

Thanks @graingert ! That makes sense. Is there a recommended workaround for running tests on a cluster that was deployed outside of the pytest context. Or, is the recommendation just "you cannot do this". (Fine with me if it is. I just want to be able to clarify this constraint to others)

**Comment by graingert** [comment]
I'd recommend using [`cloudpickle.register_pickle_by_value`](https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs) on your test module:

```
import os
import sys

import cloudpickle
from distributed import Client, LocalCluster, wait


cloudpickle.register_pickle_by_value(sys.modules[__name__])


def square_func(x):
    return x*x


def test_submit():

    # Get or create client
    dask_scheduler_file = os.environ.get("SCHEDULER_FILE", False)
    client = (
        Client(scheduler_file=dask_scheduler_file)
        if dask_scheduler_file
        else Client(LocalCluster())
    )

    # Submit simple function on workers
    results = [
        client.submit(square_func, 10, workers=[w])
        for w in client.scheduler_info()['workers']
    ]

    # Wait and shutdown
    wait(results)
    print(f"results: {results}")
    client.shutdown()

if __name__ == "__main__":
    test_submit()
```

**Comment by rjzamora** [comment]
Thanks so much @graingert ! This is extremely helpful.

I'll close this after confirming that this works for the original user.
