### ISSUE TITLE
Dask-worker behavior if unable to connect to scheduler

### ISSUE THREAD

**Issue by drickert** [dask/distributed#786]
We aim to use dask distributed to parallelize our computations across our in-house grid. In this setting, dask-workers will be started from a shellscript submitted to a grid-engine (e.g. SGE).

Unfortunately, the current worker behaviour causes issues if the dask-scheduler crashes while worker jobs are still queued in the grid. In this case, workers that are started by the grid engine after the scheduler dies seem to stay around for an unlimited time (or until they are killed via the grid engine), waiting to connect to a scheduler that no longer exists.

Is there some way to have workers time out if they do not manage to connect to a scheduler in a specific time? Neither dask-worker --help nor the documentation seem to mention anything in that direction...

**Comment by mrocklin** [comment]
Adding a timeout would not be hard.  Is this something you're interested in looking into?  This would probably involve adding a timeout to this line in Worker._start

                resp = yield self.scheduler.register(...)

                resp = yield gen.with_timeout(timedelta(seconds=N), self.scheduler.register(...)

Also, you may find the [dask-drmaa](https://github.com/dask/dask-drmaa) project of interest.
