### ISSUE TITLE
Bokeh 2.4 is broken in 2023.6.0

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7908]
#7878 broke compatibility with Bokeh 2.4 for the whole dashboard (not just the Fine Performance Metrics widget), because Bokeh 2.4 does not define interp_pallette.

**Comment by crusaderky** [comment]
CC @milesgranger @jrbourbeau

**Comment by jrbourbeau** [comment]
Good catch @crusaderky. Not sure how easy this would be to fix. Just wanted to point out dropping support for `bokeh=2` is another option.
