### ISSUE TITLE
GPU CI failures in `test_ucx_config_w_env_var`

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7944]
I am observing the occasional GPU CI failure due to some timeout

e.g. https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/6888/

or https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/6872/

`OSError: Timed out trying to connect to ucx://127.0.0.1:13339 after 60 s`

cc @dask/gpu

**Comment by pentschev** [comment]
Sorry it took me a while to look at these, I appreciate reporting and tagging us here @fjetter . I hope https://github.com/dask/distributed/pull/7950 will address those issues, at least they seemed to do so in my local testing, but please let us know if we see those or other UCX tests after the PR gets merged.
