### ISSUE TITLE
Metrics introduce non-trivial overhead

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7949]
I recently noticed that our per-task overhead increased to an extend that is not critical but still concerning.

To test this, I ran a very simple workload

```python
    from distributed import Client
    with Client() as c:
        def inc(x):
            return x + 1
        futs = c.map(inc, range(10_000))
```

First run, this shows quite some whitespace

![image](https://github.com/dask/distributed/assets/8629629/91cabe1b-8573-421b-bb86-2d24b11a4290)

but I anticipate that most of this whitespace is due to `worker-saturation` being set and the mapped tasks are actually detected as root tasks. Workers are just starving.

Disabling worker saturation again reveals a bit of a different problem with metrics. Running a py-spy profile indicates that this line is taking up about 5% of CPU time on the main thread (and another ~2-5% on the worker thread)

https://github.com/dask/distributed/blob/e0dbb35e8d4ae12081bb36e51d62008051a9d2c5/distributed/metrics.py#L325

This is not great but the actual problem is that this is also blocking the event loop, increasing all kinds of latencies and overheads as well.

Digging a bit into why this is so expensive, I noticed that the number of callbacks registered here
https://github.com/dask/distributed/blob/e0dbb35e8d4ae12081bb36e51d62008051a9d2c5/distributed/metrics.py#L212-L217

is increasing monotonically for the duration of this compute until it drops at the very end. In this rather trivial example, I get about 1200 callbacks that are evaluated on every `ContextMeter.digest_metric`.

A side-effect of this is that the dashboard much more often shows `deserialize-**` (grey) blocks because [this](https://github.com/dask/distributed/blob/e0dbb35e8d4ae12081bb36e51d62008051a9d2c5/distributed/worker.py#L2205-L2212) typically trivial task deserialization now takes nontrivial time since `_deserialize` is instrumented. (In my example deserializing `inc` supposedly takes 30-120ms)

cc @crusaderky

**Comment by crusaderky** [comment]
This is weird. You should never have more than 6 callbacks registered in that stack: two for every nested `with context_meter.meter` context manager; and there's 3:
```python
with context_meter.meter("executor"):
    with context_meter.meter("thread-noncpu"):
        with context_meter.meter("thread-cpu", func=thread_time):
            ...
```

I'll look into it.

**Comment by crusaderky** [comment]
Reproduced.

```python
from time import time

import dask
from distributed import Client, wait

dask.config.set({"distributed.scheduler.worker-saturation": float("inf")})
c = Client(n_workers=2, threads_per_worker=2)

def inc(x):
    return x + 1

t0 = time()
N = 10_000
futs = c.map(inc, range(N))
wait(futs)
t1 = time()
print((t1 - t0) / N * c.cluster.scheduler.total_nthreads)
```

| release | time per task |
| --- | --- |
| 2023.3.1 | 1.2ms |
| 2023.3.2 | 6.5ms |
| 2023.6.1 | 8.1ms |
| 2023.6.1, short-circuited `context_meter.digest_metric` | 1.7ms |

**Comment by crusaderky** [comment]
This is the culprit:
https://github.com/dask/distributed/blob/9b9f948b8143fee43887a941a3304273beed4a50/distributed/worker_state_machine.py#L3653-L3655

The line above calls `_ensure_computing`, which in turn spawns new `Worker.execute` tasks while inside the context.
The problem is limited to when there is an extremely long queue of tasks in `ready` state on the worker. If, at any moment, the worker can't saturate all threads with tasks, the stack clear.

In the above example, if I reset `worker-saturation` to the default 1.1, I get:

| worker-saturation | short-circuit digest_metric? | time per task |
| --- | --- | --- |
| inf | no | 8.1ms |
| inf | yes | 1.7ms |
| 1.1 | no | 4.1ms |
| 1.1 | yes | 4.1ms |
