### ISSUE TITLE
`CancelledError` on a simple example 

### ISSUE THREAD

**Issue by srib** [dask/distributed#7951]
**Describe the issue**:

The following code results in a `CancelledError`. What am I doing wrong? 

**Minimal Complete Verifiable Example**:

```python
def add(a, b):
    return a + b

client = Client(SCHEDULER_ADDRESS, timeout=240)
future = client.submit(add, 1, 2)
future 
```

When I submit the future to the scheduler through the client, here is a warning I get:

```console
+-------------+----------------+-----------------+----------------+
| Package     | Client         | Scheduler       | Workers        |
+-------------+----------------+-----------------+----------------+
| dask        | 2023.6.0       | 2023.3.1        | 2023.3.1       |
| distributed | 2023.6.0       | 2023.3.1        | 2023.3.1       |
| msgpack     | 1.0.3          | 1.0.5           | 1.0.5          |
| numpy       | 1.24.3         | 1.23.5          | 1.23.5         |
| pandas      | 1.5.3          | None            | None           |
| python      | 3.9.16.final.0 | 3.10.11.final.0 | 3.10.9.final.0 |
| tornado     | 6.2            | 6.3.2           | 6.2            |
+-------------+----------------+-----------------+----------------+
Notes: 
-  msgpack: Variation is ok, as long as everything is above 0.6
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

**Anything else we need to know?**:

Yes, the dask cluster is deployed on Google Cloud using [`dask kubernetes`](https://kubernetes.dask.org/en/latest/).

**Environment**:

- Dask version: Please see above
- Python version: Please see above
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for the issue @srib. My initial guess is the software environment mismatches you're seeing the warning for are causing the error. In general, Dask assumes that the same version of packages are installed throughout the cluster. Since you're using `dask-kubernetes`, maybe it's straightforward for you to use the same docker image for your client? 

cc @jacobtomlinson

**Comment by srib** [comment]
Thanks, @jrbourbeau. 

It was the different versions of `dask` and `distributed` that caused the problem. Is this something that can be solved with a better error message for the client?
