### ISSUE TITLE
Add `unregister_scheduler_plugin` method to Scheduler and Client

### ISSUE THREAD

**Issue by bphillips-exos** [dask/distributed#7958]
The distributed client has methods for registering and unregistering worker plugins, but for scheduler plugins only a register method exists. The Scheduler class has a `remove_plugin` method that could be used to expose this in the higher level Client class.

**Comment by jrbourbeau** [comment]
Thanks @bphillips-exos. Having an API for unregistering scheduler plugins seems sensible to me. Is this something you're interested in working on? (no obligation though)

**Comment by bphillips-exos** [comment]
Yes, I'll take a look if I have some time this week
