### ISSUE TITLE
Client context manager teardown error: Token was created in a different Context

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#7984]
In the `dask-kubernetes` CI we are seeing some test teardown failures on main when using the client context manager.

```python
    @pytest_asyncio.fixture
    async def client(cluster):
        async with Client(cluster, asynchronous=True) as client:
>           yield client
dask_kubernetes/classic/tests/test_async.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <Client: No scheduler connected>, exc_type = None, exc_value = None
traceback = None
    async def __aexit__(self, exc_type, exc_value, traceback):
        if self._previous_as_current:
>           _current_client.reset(self._previous_as_current)
E           ValueError: <Token var=<ContextVar name='_current_client' default=None at 0x7f994b090220> at 0x7f9939a2ad00> was created in a different Context
```
https://github.com/dask/dask-kubernetes/actions/runs/5520013883/jobs/10066056146

Is this related to a change in distributed?

**Comment by fjetter** [comment]
@jacobtomlinson is it easily possible for you to move away from pytest-asyncio or will this be a big problem?

**Comment by graingert** [comment]
@jacobtomlinson one option is using the test runner built into anyio, it would resolve this specific issue because it runs fixtures in a way that's compatible with ContextVar. dask-kubernetes already has anyio as a dep so switching to the anyio runner would save you a dependency.

You'll need to add an anyio_backend that only selects 'asyncio' otherwise anyio will try to run your tests with trio also

```python
@pytest.fixture
def anyio_backend():
    return 'asyncio'
```

**Comment by jacobtomlinson** [comment]
Ok cool. It seems like a non-trivial change and I'm also not keen to modify the test suite for the classic KubeCluster (which is the one that is failing) given that we are removing it soon. I'd be happy to invest in this change for the operator test suite though.

Does #7987 work around this for now?

**Comment by fjetter** [comment]
> Does https://github.com/dask/distributed/pull/7987 work around this for now?

Yes, but it would raise a DeprecationWarning if that happens
