### ISSUE TITLE
shuffle_transfer failed during shuffle in `test_fused_blockwise_dataframe_merge`

### ISSUE THREAD

**Issue by j-bennet** [dask/distributed#8004]
**Describe the issue**:

Distributed test started failing in dask/dask CI with distributed `main`.

The error looks like this:

```
FAILED dask/tests/test_distributed.py::test_fused_blockwise_dataframe_merge[True] - RuntimeError: shuffle_barrier failed during shuffle 1d8d714896c0fa093a11a0ddfed35635
FAILED dask/tests/test_distributed.py::test_fused_blockwise_dataframe_merge[False] - RuntimeError: shuffle_transfer failed during shuffle 1d8d714896c0fa093a11a0ddfed35635
```

Example workflow:

https://github.com/dask/dask/actions/runs/5555724247/jobs/10147277695

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.7.0
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by j-bennet** [comment]
cc @hendrikmakait @fjetter @crusaderky

**Comment by hendrikmakait** [comment]
Thanks for flagging this, @j-bennet. I can reproduce this locally when installing `pyarrow 13.0.0.dev517`. If using `pyarrow=12`, the test succeeds.

**Comment by hendrikmakait** [comment]
I've created a dedicated issue for this: https://github.com/dask/distributed/issues/8007
