### ISSUE TITLE
P2P shuffling incompatible with `pyarrow-13.0.0.dev*`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8007]
Upstream testing on `dask/dask` revealed a problem with P2P shuffling in combination with the nightly build of the next release `pyarrow=13`.

We should jump on this before `pyarrow=13` gets finalized to figure out if there is a change in API or possibly a regression.

XREF: https://github.com/dask/distributed/issues/8004

**Comment by jrbourbeau** [comment]
Thanks @hendrikmakait

cc @jorisvandenbossche for visibility

**Comment by jorisvandenbossche** [comment]
Thanks for the ping. Opened https://github.com/dask/distributed/pull/8009
