### ISSUE TITLE
P2P blows up memory

### ISSUE THREAD

**Issue by phofl** [dask/distributed#8015]
**Describe the issue**:

There are 2 different issues that @hendrikmakait and I identified:

- Doing a repartition before the shuffle loads all data into memory
- After shuffling is finished, the memory is double the amount we would expected, there seem to be unreleased references. The MCVE has around 80GB of unmanaged memory

Potentially, the tasks during unpack are scheduled a bit too fast as well which results in excessive memory usage, but this should be mitigated by the other 2 points.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd
from distributed import wait

dask.config.set({"dataframe.convert-string": True})  # use PyArrow strings by default

df = dd.read_parquet(
    "s3://coiled-datasets/uber-lyft-tlc/",
    storage_options={"anon": True},
)
df = df.shuffle("PULocationID").persist()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: main
- Python version: 3.11
- Operating System: mac
- Install method (conda, pip, source): condo

**Comment by jrbourbeau** [comment]
xref https://github.com/dask/distributed/pull/7983, which is on `main`, but not yet released, which _may_ help (at least in terms of spikes in unmanaged memory)

**Comment by fjetter** [comment]
before shuffle (persisting the parquet dataset)

![image](https://github.com/dask/distributed/assets/8629629/39d988cf-825f-40cd-a7aa-8ac7ae92910f)


during unpack... worker died of course.

![Screen Recording 2023-07-20 at 10 30 15](https://github.com/dask/distributed/assets/8629629/2cc506a2-7832-47b5-9b9f-40e61aa66a61)


FWIW this is not related to https://github.com/dask/distributed/issues/7990 I can barely see any disk overhead in this example

**Comment by fjetter** [comment]
Note that my example GIF above may not necessarily be representative of the report since I don't know how large the output partitions are. If they are huge and four threads are materializing a big partition at the same time it is clear why it runs OOM

**Comment by fjetter** [comment]
Ok, was successful on a bigger cluster
before
![image](https://github.com/dask/distributed/assets/8629629/eaab018a-a152-4353-932f-acc6f93c67c6)

during unpack

![Screen Recording 2023-07-20 at 10 40 30](https://github.com/dask/distributed/assets/8629629/83600640-b49e-4a5b-bd5a-6e6c296f6f0c)


Apart from inhomogeneous data distributed, we end up with less managed memory and much more unmanaged memory.

![image](https://github.com/dask/distributed/assets/8629629/154e9e4e-7d5f-4122-ac87-9142c2bcc589)

**Comment by phofl** [comment]
@jrbourbeau Rerun this with the commit but no real difference.

@fjetter sorry I should have specified this. I ran this on 40 workers with 16GB memory each. My results are more or less the same as yours.

**Comment by fjetter** [comment]
I played a bit with [memray](https://github.com/bloomberg/memray) and the profile data suggests that we're somehow still holding on to some early `read_parquet` data. This is surprising since after the transfer stage of a shuffle, all of this should be released. Even if the buffers held on to some reference via shards this should not happen since the buffers are supposed to be empty once the transfer stage is over. If the read-parquet data is indeed what's causing this, this is concerning.

We investigated briefly what was referencing these dataframes and some investigation with objgraph suggested that an LRU implementation (apparently SpillBuffer) would be holding on to this. What we saw is not entirely consistent and this has to be double or triple checked.

I will prepare a PR shortly with the code I was using to run memray since I believe this is valuable in other situations as well.

This is an example of one of these profiles

[memray-flamegraph-profile-tls:10.0.34.html.zip](https://github.com/dask/distributed/files/12111269/memray-flamegraph-profile-tls.10.0.34.html.zip)

**Comment by fjetter** [comment]
Actually, I believe this is not a P2P but a read_parquet issue.

```python
from distributed import Client
client = Client()

# Generate something
from dask.datasets import timeseries

dtypes = {
    str(ix): int
    for ix in range(50)
}
dtypes.update({
    str(ix): float
    for ix in range(50, 100)
})
ddf = timeseries(dtypes=dtypes)
ddf.to_parquet("timeseries")
del ddf

import dask.dataframe as dd

from distributed import wait
from distributed.diagnostics.memray import memray_workers, memray_scheduler

# Read it back (with memray profiling
directory = "memray-demo"
with memray_scheduler(directory), memray_workers(directory):
    futs = ddf = dd.read_parquet('timeseries').persist()
    # futs = ddf.shuffle("0").persist()
    
    wait(futs)
    
    import time
    time.sleep(0.5)
    
    del futs, ddf

    import time
    time.sleep(0.5)

```

This video was taken w/out the profiler running to exclude it as a possible source of (reference) contamination

![Screen Recording 2023-08-17 at 14 01 58](https://github.com/dask/distributed/assets/8629629/0979b629-8a1c-4a2f-b2e4-5215c0963dc1)

[worker_memory_profile_read_parquet.html.zip](https://github.com/dask/distributed/files/12369098/worker_memory_profile_read_parquet.html.zip)


cc @rjzamora

**Comment by fjetter** [comment]
> This is odd, didn't our initial results show that we don't have the memory blow-up if we skip the shuffle?

There were two sources, weren't they? IDK

Can you reproduce my result?

FWIW it currently looks like the memory I'm seeing above is the pyarrow memory pool. The memory is properly reused when I run this in a loop but I can't get it down

**Comment by hendrikmakait** [comment]
> FWIW it currently looks like the memory I'm seeing above is the pyarrow memory pool. The memory is properly reused when I run this in a loop but I can't get it down

This is in line with what I read (https://github.com/apache/arrow/issues/36378 and related issues).

**Comment by fjetter** [comment]
FWIW My theory is that same host/process shard transfers are holding a ref to the original data alive. If that's the case, one copy should do the trick. @phofl will test this 🤞 

```diff
diff --git a/distributed/shuffle/_comms.py b/distributed/shuffle/_comms.py
index 255d433d8..8b4c2e2cb 100644
--- a/distributed/shuffle/_comms.py
+++ b/distributed/shuffle/_comms.py
@@ -54,6 +54,7 @@ class CommShardsBuffer(ShardsBuffer):
     def __init__(
         self,
         send: Callable[[str, list[tuple[Any, bytes]]], Awaitable[None]],
+        local_address: str,
         memory_limiter: ResourceLimiter | None = None,
         concurrency_limit: int = 10,
     ):
@@ -63,10 +64,14 @@ class CommShardsBuffer(ShardsBuffer):
             max_message_size=CommShardsBuffer.max_message_size,
         )
         self.send = send
+        self.local_address = local_address

     async def _process(self, address: str, shards: list[tuple[Any, bytes]]) -> None:
         """Send one message off to a neighboring worker"""
         with log_errors():
             # Consider boosting total_size a bit here to account for duplication
             with self.time("send"):
+                if self.local_address == address:
+                    import copy
+                    shards = copy.deepcopy(shards)
                 await self.send(address, shards)
diff --git a/distributed/shuffle/_core.py b/distributed/shuffle/_core.py
index e7dd72c73..35d499189 100644
--- a/distributed/shuffle/_core.py
+++ b/distributed/shuffle/_core.py
@@ -66,7 +66,9 @@ class ShuffleRun(Generic[_T_partition_id, _T_partition_type]):
         )

         self._comm_buffer = CommShardsBuffer(
-            send=self.send, memory_limiter=memory_limiter_comms
+            send=self.send,
+            memory_limiter=memory_limiter_comms,
+            local_address=local_address,
         )
         # TODO: reduce number of connections to number of workers
         # MultiComm.max_connections = min(10, n_workers)
```
