### ISSUE TITLE
Deduplicate code in `Server.close`, `Server.close` and `Server.stop`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8077]
Some of the teardown code is duplicated between the three methods. We should canonicalize that.

See https://github.com/hendrikmakait/distributed/blob/b1a4ac46fd0c2e3d3fd57e2273f1ecf9eeb4ade2/distributed/worker.py#L1598-L1614

https://github.com/dask/distributed/blob/4c4748a323b1ae1b5e8282d577ddfb2d0d26ab41/distributed/core.py#L671-L686

https://github.com/dask/distributed/blob/4c4748a323b1ae1b5e8282d577ddfb2d0d26ab41/distributed/core.py#L1033-L1050

**Comment by thedeg123** [comment]
Hello. I am a new to contributing to dask, but have been using dask.distributed extensively for the past year and want to get involved with development. Can I pick this up?

**Comment by hendrikmakait** [comment]
Hi! Thanks for your interest in contributing to `distributed`. Contributions are always welcome, so please go ahead! Let me know if you hit any roadblocks.
