### ISSUE TITLE
Flaky test_task_groups_update_start_stop

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8084]
`time()` on Windows can slightly but frequently move backwards due to micro-adjustments in `distributed.metrics._WindowsTime`.

This causes flakiness in `test_task_groups_update_start_stop`:
```
>       assert t0 < tg.start < t1 < t2 < tg.stop < t3
E       assert 1691512272.6894543 < 1691512272.6883268
E        +  where 1691512272.6894543 = <x: memory: 2>.start
```

**Comment by crusaderky** [comment]
#8087 was ineffective at fixing the problem: https://github.com/dask/distributed/actions/runs/5854070495/job/15869288671?pr=8101

**Comment by hendrikmakait** [comment]
Just throwing this out there: If the non-monotonicity of `distributed.metrics.time` is generally problematic for testing, what if we patched it for tests to be `monotonic` or some combination of the timestamp at the first call + the monotonic diff?

**Comment by crusaderky** [comment]
@hendrikmakait in order to monkey-patch it for tests you'd need to write a wrapper that persists in production, or special code that switches path between pytest and non-pytest. As a general test philosophy it doesn't strike me as a good idea...

**Comment by hendrikmakait** [comment]
> or special code that switches path between pytest and non-pytest

I was thinking of an auto-use fixture that monkey-patches this, but agreed, I'm also not sure if that's better than having to deal with these issues. Come to think about it, a non-auto fixture that monkey-patches this only for specific tests might be a reasonable idea, though.
