### ISSUE TITLE
scheduler deserialization breaks PipInstall

### ISSUE THREAD

**Issue by bolliger32** [dask/distributed#8099]
**Describe the issue**: The `PipInstall` worker plugin installs packages on the worker, but recent changes to how the scheduler is deserializing might make code that tries to use this package break, if the scheduler and workers do not share a filesystem. I believe this is the same issue as described in #7834 but for `PipInstall` instead of `Client.upload_file`.

**Minimal Complete Verifiable Example**:
First a remote dask cluster. In our case, we are using a kuberentes-backed DaskGateway cluster. In the below example `client` is the `Client` object. And let's say, for example, that the docker image being used does not contain `s3fs`. We have pip installed s3fs locally and would like to use it in dask workflows as well

```python
from distributed import PipInstall
import s3fs

client.register_worker_plugin(PipInstall(["s3fs"]))

def testfunc():
    return s3fs.__version__

client.submit(testfunc).result()
```
Gives:
```python
ModuleNotFoundError                       Traceback (most recent call last)
File /srv/conda/envs/notebook/lib/python3.11/site-packages/distributed/scheduler.py:4545, in update_graph()
   4544 try:
-> 4545     graph = deserialize(graph_header, graph_frames).data
   4546     del graph_header, graph_frames

File /srv/conda/envs/notebook/lib/python3.11/site-packages/distributed/protocol/serialize.py:432, in deserialize()
    431 dumps, loads, wants_context = families[name]
--> 432 return loads(header, frames)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/distributed/protocol/serialize.py:98, in pickle_loads()
     93 buffers = [
     94     memoryview(bytearray(mv) if w else bytes(mv)) if w == mv.readonly else mv
     95     for w, mv in zip(writeable, map(ensure_memoryview, buffers))
     96 ]
---> 98 return pickle.loads(x, buffers=buffers)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/distributed/protocol/pickle.py:96, in loads()
     95     else:
---> 96         return pickle.loads(x)
     97 except Exception:

File /srv/conda/envs/notebook/lib/python3.11/site-packages/cloudpickle/cloudpickle.py:649, in subimport()
    644 def subimport(name):
    645     # We cannot do simply: `return __import__(name)`: Indeed, if ``name`` is
    646     # the name of a submodule, __import__ will return the top-level root module
    647     # of this submodule. For instance, __import__('os.path') returns the `os`
    648     # module.
--> 649     __import__(name)
    650     return sys.modules[name]

ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[21], line 1
----> 1 client.submit(tryimport).result()

File /srv/conda/envs/notebook/lib/python3.11/site-packages/distributed/client.py:327, in Future.result(self, timeout)
    325 if self.status == "error":
    326     typ, exc, tb = result
--> 327     raise exc.with_traceback(tb)
    328 elif self.status == "cancelled":
    329     raise result

RuntimeError: Error during deserialization of the task graph. This frequently occurs if the Scheduler and Client have different environments. For more information, see https://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments
```

Note that the following would work (if the package is imported within the function). This is presumably b/c the scheduler no longer needs to deserialize s3fs into the python package:
```python
def testfunc():
    import s3fs
    return s3fs.__version__

client.submit(testfunc).result()
```

**Environment**:

- Dask version: 2023.8.0
- Python version: 3.11.4
- Operating System: Linux

**Comment by jrbourbeau** [comment]
Thanks for the issue @bolliger32 

For the `Client.upload_file` case we added a corresponding scheduler plugin to make sure files were also uploaded on the scheduler. We should probably do something similar for `PipInstall` / `CondaInstall`. That said, needing to manually register both types of plugins along the lintes of

```python
client.register_worker_plugin(PipInstall(["s3fs"]))
client.register_scheduler_plugin(PipInstallScheduler(["s3fs"]))    # a better name is welcome
```

is pretty verbose. It's a separate issue, but a couple of other follow-ups could be to:

1. Make a new type of plugin (`ClusterPlugin`?) that applies to both workers and the scheduler. This may be more complexity than it's worth
2. Add a new `Client.pip_install(...)` method that serves as the user-facing API for installing packages. This has been brought up before and would move the whole install on scheduler + workers complexity to an implementation detail users don't need to think about. 

> Note that the following would work (if the package is imported within the function). This is presumably b/c the scheduler no longer needs to deserialize s3fs into the python package

Yeah, that's correct. This would be my suggested temporary workaround

**Comment by bolliger32** [comment]
Thanks @jrbourbeau this makes a lot of sense to me. FWIW I like the idea of a Client.pip_install method that works like upload_file

**Comment by bolliger32** [comment]
Also, in case it's helpful, the workaround we're using right now goes something like this:

```python
        pip_installer = PipInstall(
            packages=extra_pip_packages, pip_options=extra_pip_install_options
        )
        client.register_worker_plugin(pip_installer)
        client.run_on_scheduler(pip_installer.install)
```
Probably not the most robust thing to do in the long run though.

**Comment by hendrikmakait** [comment]
FWIW, instead of introducing a `ClusterPlugin`, we could also turn the `PackageInstall` plugin into a `SchedulerPlugin` which then installs a corresponding worker plugin. This might be a good compromise for the short-/mid-term. The P2P scheduler plugin does something similar.

**Comment by bolliger32** [comment]
FWIW the same issue pops up with `UploadDirectory`, where the use case here is uploading a local development version of a package to the workers (and now to the scheduler). Here the workaround is not quite so straightforward, or at least I haven't figured it out. Curious if there are recommendations on a workaround for the time being
