### ISSUE TITLE
NannyPlugin not installed if it is registered while a Nanny is starting

### ISSUE THREAD

**Issue by shughes-uk** [dask/distributed#8100]
Upload directory seems only work sometimes. It also uploads things to a different location to `UploadFile`, it just seems to dump them in the current working directory vs worker temp directory.

This code deadlocks for me the majority of the time. 

```python
client.register_worker_plugin(UploadDirectory(path), nanny=True)

def foo():
        while not Path(path-on-remote).exists():
            print("waiting")
            time.sleep(5)
client.submit(foo).result()
```

**Comment by shughes-uk** [comment]
For my use case I need the have the files somewhere I can predict/control just fyi. Putting them in the worker temp directory i'm not sure would be helpful. Something like `UploadDirectory(path, target_directory="/some-dir")` would be nice.

**Comment by shughes-uk** [comment]
@florian-jetter-by me and @mrocklin spent a bit looking at clustes, one thing we were noticing is that sometimes the nanny seems to not register the upload plugin, or at least the log message is missing

Here's two clusters run by identical code

https://cloud.coiled.io/clusters/257080/information?account=shughes-uk&tab=Logs&filterPattern=

https://cloud.coiled.io/clusters/257083/information?account=shughes-uk&tab=Logs&filterPattern=

**Comment by shughes-uk** [comment]
Code looks like this

```python
        with coiled.Cloud(account=account) as cloud:
            with coiled.Cluster(
                cloud=cloud,
                n_workers=0,
                allow_ssh=True,
                extra_worker_on_scheduler=True,
                shutdown_on_close=shutdown_on_close,
            ) as cluster:
                with Client(cluster) as client:
                    client.register_worker_plugin(UploadDirectory("/Users/samanthahughes/airflow"), nanny=True)

                    def run_command(command):
                        return Path("/scratch/dask-scratch-space/airflow").exists()

                    time.sleep(10)
                    task = client.run(run_command, command=command)
                    print("PATH EXISTS", task)
                    info["command-parsed"] = command

                    task = client.submit(run_command, command=command)
                    print("SUBMIT", task.result())
```

**Comment by mrocklin** [comment]
The cases where Samantha's situation fails are cases where `client.run` returns `{}` (so no workers are active at that moment.  Then she submits a task, but somehow the task runs before the nanny plugin runs, then things shut down before the nanny plugin has a chance.  This would be easier to debug if we had log messages inside `Scheduler.register_*_plugin` acknowledging that the plugins had been registered.

**Comment by shughes-uk** [comment]
@mrocklin not quite right,  if I block in the task with something like `while not Path("blah").exists()`, it never unblocks.

**Comment by fjetter** [comment]
@shughes-uk can you please open a dedicated ticket for the `target_directory` feature?

---

I haven't tried reproducing this but I'm not surprised this isn't working too well after reviewing some code. It seems there is a race condition where a nanny would miss registered plugins if the nanny is mid starting while the plugin is registered...

for mitigation until a fix is available (and for backwards compat...), the easiest is to wait for all expected workers to be up before registering the plugin.

**Comment by shughes-uk** [comment]
@fjetter would this only affect nanny plugins, or could it affect scheduler/worker plugins?

**Comment by shughes-uk** [comment]
oh and that workaround does unblock me nicely.

**Comment by fjetter** [comment]
> @fjetter would this only affect nanny plugins, or could it affect scheduler/worker plugins?

Does only affect Nanny plugins
