### ISSUE TITLE
Allow workers table in info pages to be sorted

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#8140]
In the info pages we have a table of workers like the following:

<img width="1485" alt="Screenshot 2023-08-29 at 7 32 30 AM" src="https://github.com/dask/distributed/assets/306380/9c2b67a1-2802-47c7-bc9b-75510ee07ecb">

It would be convenient to be able to sort by column.  For example, in a case where you have 1000 workers, one of which is still processing a task, it would be nice to be able to click on the Processing column to have that one worker come up to the top. 

These pages are raw HTML written by me, with very little web experience.  I suspect that we could include some very basic JavaScript on these pages and get something that accomplished this easily.

**Comment by jrbourbeau** [comment]
I see how this would be useful

> JavaScript

@jacobtomlinson is this something you think you'd have bandwidth for?
