### ISSUE TITLE
FutureWarnings with pandas 2.1.0

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8147]
CI has turned red as pandas has bumped to 2.1.0:
https://github.com/dask/distributed/actions/runs/6039745069/job/16389085693?pr=8146

ERROR distributed/protocol/tests/test_arrow.py - FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
ERROR distributed/protocol/tests/test_pandas.py - FutureWarning: Period with BDay freq is deprecated and will be removed in a future version. Use a DatetimeIndex with BDay freq instead.

CC @phofl 
CC @jrbourbeau

**Comment by crusaderky** [comment]
XREF https://github.com/dask/dask/pull/10439

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/8145
