### ISSUE TITLE
Set_index results in empty df with sort_values

### ISSUE THREAD

**Issue by manschoe** [dask/distributed#8165]
**Describe the issue**:
We're experiencing issues after setting an index on a partitioned dataset and then trying to sort_values. This results in an empty dataframe.
**Minimal Complete Verifiable Example**:

```python
#Dask cluster created above
import random
import dask.dataframe as dd
dask_df = dd.from_dict(
    {
        "a": [1, 2, 3],
        "b": [3, 1, 3],  # this breaks (unordered, with repeats)
        # "b": [1, 1, 3],  # this works (ordered)
        # "b": [1, 3, 2],  # this works (not repeating)
    },
    npartitions=2,  # works with 1 partition
)
dask_df = dask_df.set_index("b")  # works with the given index, not if we set index to [3,1,3] "b"
len(dask_df.sort_values(["a"])) # is 0
```

**Environment**:

- Dask version: 2023.9.0
- Python version: 3.10
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by fjetter** [comment]
Thanks for your report! I can reproduce the issue. Looks like this is related to the P2P shuffle method.


```python
#Dask cluster created above
import random
import dask.dataframe as dd
import dask
# This is the default. Just here for explicitness. P2P will be used for the `set_index`
dask.config.set({"dataframe.shuffle.method": "p2p"})
dask_df = dd.from_dict(
    {
        "a": [1, 2, 3],
        "b": [3, 1, 3],  # this breaks (unordered, with repeats)
        # "b": [1, 1, 3],  # this works (ordered)
        # "b": [1, 3, 2],  # this works (not repeating)
    },
    npartitions=2,  # works with 1 partition
)
dask_df = dask_df.set_index("b")  # works with the given index, not if we set index to [3,1,3] "b"

# Sorting will again perform a shuffle
dask.config.set({"dataframe.shuffle.method": "tasks"})

dask_df.sort_values(["a"]).compute()
```

cc @hendrikmakait 

---

@manschoe apart from the bug itself I would like to point out that what you are doing here seems very inefficient. Both `set_index` and `sort_values` is triggering an expensive _shuffle_ operation to sort the data. You are effectively sorting the data twice. The `sort_values` by `a` is destroying the sorting that is being done by `b`. Are you sure you want to set the index on `b`? Maybe you would rather want to do `set_index("b", sort=False)` (which basically only sets the pandas index on the individual partitions.

**Comment by hendrikmakait** [comment]
Thanks for the report, this is related to a fix I've already been working on (dask#10493).

**Comment by manschoe** [comment]
@fjetter I completely understand that, we'll take that back to our end users

**Comment by JoranDox** [comment]
@fjetter (I'm on Manu's team)
> what you are doing here seems very inefficient

This is just the minimal repro, the actual use case is data read in from a parquet file (which has a similar index with repetitions, and might be unsorted, not sure), there is no explicit set_index.

**Comment by fjetter** [comment]
> This is just the minimal repro, the actual use case is data read in from a parquet file (which has a similar index with repetitions, and might be unsorted, not sure), there is no explicit set_index.

Got it, thank you!
