### ISSUE TITLE
Fails to deserialize large object

### ISSUE THREAD

**Issue by bschreck** [dask/distributed#817]
I'm trying to persist and publish a large object consisting of several pandas dataframes (the problem is reproduced when the object contains a single large numpy array as well).

I do this with a function that loads the data from a csv, from which I create a delayed object and send to the (local) cluster.

    ds = delayed(create_dataset)(filename)
    ds = client.persist(ds)
    client.publish_dataset('name': ds)

And then try to compute and access a property:

    length = client.compute(ds.length).result()

This throws the following error (after successfully calling the create_dataset() function on the cluster)

CRITICAL:/Users/bschreck/FeatureLabs/featuretools/ENV/src/distributed/distributed/protocol/core.pyc:Failed to deserialize
Traceback (most recent call last):
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/src/distributed/distributed/protocol/core.py", line 114, in loads
    fs = merge_frames(head, fs)
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/src/distributed/distributed/protocol/utils.py", line 53, in merge_frames
    assert sum(lengths) == sum(map(len, frames))
AssertionError

When I try this with a sampled version of the files, it works fine. I printed out the lengths of the two sides of the equality in that assert statement, and got very different sizes (the left was much much smaller than the right)

**Comment by mrocklin** [comment]
Can I ask you to try the following on the object that might be causing a problem:

```python
In [1]: import distributed

In [2]: frames = distributed.protocol.dumps('my-object')

In [3]: frames
Out[3]: (b'', b'\xa9my-object')

In [4]: distributed.protocol.loads(frames)
Out[4]: 'my-object'
```

Can I also ask you to verify that versions are the same everywhere:

```python
client.get_versions(check=True)
```

**Comment by bschreck** [comment]
Okay so it couldn't serialize it, that's the problem. Not sure why.

If that check completes successfully and prints does that mean all the versions are the same? If so then yeah all the versions are the same. Otherwise I can go though and check each worker/scheduler/client. It's running locally by creating a Client() with no args so everything should be imported from the same place

**Comment by bschreck** [comment]
I think the way to go about it might be to separate the various dataframes inside and publish them separately

**Comment by mrocklin** [comment]
Yes, if `get_versions(check=True)` completes then we're fine.  Moving dataframes around independently *would* resolve this particular problem, but I'm also interested and motivated to solve the underlying issue.  Ideally dask can be robust to cases like this.  What happens exactly when you call dumps on your object?

**Comment by bschreck** [comment]
Hmm it actually seems that the individual dataframes, and even the underlying numpy array can't be serialized either. Weird.


TypeError                                 Traceback (most recent call last)
<ipython-input-40-094042a0690e> in <module>()
----> 1 frames = p.dumps(df.sample(100).values)

/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/distributed/protocol/core.pyc in dumps(msg)
     34         if isinstance(msg, (list, dict)):
     35             msg, data, bytestrings = extract_serialize(msg)
---> 36         small_header, small_payload = dumps_msgpack(msg)
     37
     38         if not data:  # fast path without serialized data

/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/distributed/protocol/core.pyc in dumps_msgpack(msg)
    134     """
    135     header = {}
--> 136     payload = msgpack.dumps(msg, use_bin_type=True)
    137
    138     fmt, payload = maybe_compress(payload)

/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/msgpack/__init__.pyc in packb(o, **kwargs)
     45     See :class:`Packer` for options.
     46     """
---> 47     return Packer(**kwargs).pack(o)
     48
     49 # alias for compatibility to simplejson/marshal/pickle.

msgpack/_packer.pyx in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)()

msgpack/_packer.pyx in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)()

msgpack/_packer.pyx in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)()

TypeError: can't serialize array([[  1.55077438e+02,   1.72770000e+04,   4.94027400e+06],
       [  1.53814484e+02,   1.52380000e+04,   4.31701200e+06],
       [  1.55041687e+02,   2.71890000e+04,   7.49538100e+06],
       [  1.55369995e+02,   5.18500000e+03,   1.46592300e+06],
       [  1.49649994e+02,   1.01150000e+04,   2.85342900e+06],

**Comment by mrocklin** [comment]
This is possibly a problem with Python 2, which has difficulty pickling large objects.

```python
In [1]: import numpy as np

In [2]: x = np.ones(int(2.5e9), dtype='u1')

In [3]: import pickle

In [4]: _ = pickle.dumps(x)
OverflowError: length too large
```

Some options:

1.  Define custom serialization for your object.  See http://distributed.readthedocs.io/en/latest/serialization.html
2.  Try Python 3

**Comment by bschreck** [comment]
Got it thanks. I'll probably just define serialization for the individual pandas dataframes. Would this have the same problem if they were Dask dataframes?

**Comment by bschreck** [comment]
Looks like nothing special is included in Distributed for dask object serialization

**Comment by mrocklin** [comment]
Dask.dataframes don't get passed around the cluster, instead their constituent pandas dataframes get passed around.  You might want to try persisting dask.dataframes.  See http://distributed.readthedocs.io/en/latest/manage-computation.html

**Comment by bschreck** [comment]
Thanks, I wrote my own serialization and it seems to work fine, however now I'm running into another problem- making a new issue.
