### ISSUE TITLE
Distributed always binds to all network interfaces even when configured to bind only to loopback (127.0.0.1)

### ISSUE THREAD

**Issue by strets123** [dask/distributed#818]
Typically when using a networked application (e.g. MongoDB) if I tell the application to bind to 127.0.0.1 it will bind only to that address and the port of the application will not be visible by port scanning the network address.

With dask-scheduler and dask-worker however this is not the case.

If in one tab I run dask scheduler I see this output:

        dask-scheduler --host 127.0.0.1
	distributed.scheduler - INFO - -----------------------------------------------
	distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:8786
	distributed.scheduler - INFO -        http at:            127.0.0.1:9786
	distributed.scheduler - INFO -       bokeh at:            127.0.0.1:8788
	distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
	distributed.scheduler - INFO - -

If I then in another tab run a port scan on my LAN IP I get this output:

        sudo nmap -p1-65535 10.11.2.80
	[sudo] password for astretton: 

	Starting Nmap 7.01 ( https://nmap.org ) at 2017-01-18 13:42 GMT
	Nmap scan report for 10.11.2.80
	Host is up (0.000012s latency).
	Not shown: 65529 closed ports
	PORT     STATE SERVICE
	22/tcp   open  ssh
	6600/tcp open  mshvlm
	8786/tcp open  unknown
	8787/tcp open  unknown
	8788/tcp open  unknown
	9786/tcp open  unknown

This means that distributed is listening to the outside world, a fact that I have confirmed by using telnet against a remote server.

**Comment by mrocklin** [comment]
Correct, the `host` keyword is the address that the scheduler tells to other members of the network (clients, workers) so that they can contact it in the future.  It is not a binding address.  So far Dask has only been used within secure environments, so binding to specific address ranges hasn't been an issue.  It's a reasonable request though.

@pitrou is rewriting much of the network infrastructure now.  He may find this issue of interest.

**Comment by pitrou** [comment]
Yes, this is something I noticed and that initially confused me during the refactor. My refactoring PR behaves differently:
```
$ python -m distributed.cli.dask_scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:         192.168.1.68:8786
distributed.scheduler - INFO -       bokeh at:         192.168.1.68:8788
distributed.scheduler - INFO -        http at:         192.168.1.68:9786
distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
^C
Interrupted, shutting down
Received SIGTERM, shutting down
distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
```
```
$ python -m distributed.cli.dask_scheduler --host 127.0.0.1
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:8786
distributed.scheduler - INFO -       bokeh at:            127.0.0.1:8788
distributed.scheduler - INFO -        http at:            127.0.0.1:9786
distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
^C
Interrupted, shutting down
Received SIGTERM, shutting down
distributed.scheduler - INFO - End scheduler at 'tcp://127.0.0.1:8786'
```

**Comment by strets123** [comment]
I understand the case for listening on all interfaces to make the tools easy to use and for most of our customers closing ports with a firewall is normal.

University departments though tend to have a policy of open ports internally across a university. This is understood by those installing software as being a secure environment but then the university admins have other ideas and run port scanners and call people out for things. 

Adding firewall rules during an install script for software seems a little messy, perhaps LocalCluster could have a default whereby bokeh, http the scheduler and all the workers all bind to 127.0.0.1. After all, it is called LocalCluster...

**Comment by mrocklin** [comment]
@strets123 I don't disagree.  

@pitrou does the upcoming rewrite enable listening for only particular IP ranges?

#810

**Comment by pitrou** [comment]
> @pitrou does the upcoming rewrite enable listening for only particular IP ranges?

The networking layer definitely does, but it's not necessary plugged in the UI (i.e. CLI or API). As my example above shows, it's done for the scheduler's main endpoint, not the ancillary services (HTTP, Bokeh).

**Comment by pitrou** [comment]
Update with the latest #810:
```
$ python -m distributed.cli.dask_scheduler --host 127.0.0.1
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:      tcp://127.0.0.1:8786
distributed.scheduler - INFO -       bokeh at:            127.0.0.1:8788
distributed.scheduler - INFO -        http at:            127.0.0.1:9786
distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://127.0.0.1:35435
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:35435
```
```
$ python -m distributed.cli.dask_worker tcp://127.0.0.1:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:40474'
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:35435
distributed.worker - INFO -              bokeh at:            127.0.0.1:8789
distributed.worker - INFO -              nanny at:            127.0.0.1:40474
distributed.worker - INFO -               http at:            127.0.0.1:43196
distributed.worker - INFO - Waiting to connect to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                    5.01 GB
distributed.worker - INFO -       Local Directory:        /tmp/nanny-sut4t0u_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:             tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Nanny 'tcp://127.0.0.1:40474' starts worker process 'tcp://127.0.0.1:35435'
```
Listening ports:
```
$ netstat -tnlp | \grep python
tcp        0      0 127.0.0.1:35435         0.0.0.0:*               LISTEN      19264/python    
tcp        0      0 127.0.0.1:8786          0.0.0.0:*               LISTEN      19050/python    
tcp        0      0 0.0.0.0:8787            0.0.0.0:*               LISTEN      19066/python    
tcp        0      0 127.0.0.1:8788          0.0.0.0:*               LISTEN      19050/python    
tcp        0      0 0.0.0.0:8789            0.0.0.0:*               LISTEN      19264/python    
tcp        0      0 127.0.0.1:40474         0.0.0.0:*               LISTEN      19239/python    
tcp        0      0 127.0.0.1:9786          0.0.0.0:*               LISTEN      19050/python    
tcp        0      0 0.0.0.0:43196           0.0.0.0:*               LISTEN      19264/python    
tcp6       0      0 :::8787                 :::*                    LISTEN      19066/python    
tcp6       0      0 :::8789                 :::*                    LISTEN      19264/python    
tcp6       0      0 :::43196                :::*                    LISTEN      19264/python    
```

So we see that only 3 ports are open on the outside: 8787, 8789 and 43196, which are the HTTP and Bokeh ports for the worker and scheduler. This is expected.

**Comment by pitrou** [comment]
PR #810 and subsequent PRs should now have fixed the issue.
