### ISSUE TITLE
Graceful shutdown should not increase suspicious counter

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8202]
When a worker dies unexpectedly, the scheduler increases a `suspicious` counter on all tasks that were computing on it at the moment, then reschedules them somewhere else. When the counter reaches `distributed.scheduler.allowed-failures`, the task is marked as failed.

Graceful worker shutdown is when the user or an agent (e.g. dynamic scaling, or Coiled reacting to the imminent demise of a EC2 spot instance) _asks_ the scheduler to terminate a worker. The worker will be shut down as soon as there are no unique keys in memory on it; if there are running tasks, the scheduler won't wait for them to finish (as they could take arbitrarily long) and just reschedules somewhere else, wasting any accrued progress.

When this happens, the scheduler is currently increasing the `suspicious` counter. This is wrong, as the reason the worker died while it was running the task is that the scheduler itself asked it to.

This is particularly glaring if the user disables retries by setting `distributed.scheduler.allowed-failures: 0`; for example this happens in 
https://github.com/coiled/benchmarks/blob/main/tests/benchmarks/test_spill.py, which just failed with

> FAILED tests/benchmarks/test_spill.py::test_dot_product_spill[compressible] - distributed.scheduler.KilledWorker: Attempted to run task ('chunk_sum-6f8083eb44862f3ee7669497a35c8a25', 8, 7, 7) on 0 different workers, but all those workers died while running it. The last worker that attempt to run the task was tls://10.0.34.36:41345. Inspecting worker logs is often a good next step to diagnose what went wrong. For more information see https://distributed.dask.org/en/stable/killed.html.

(note the off-by-one in the log - it should read `on 1 different workers`).

On the worker log I read:
```
distributed.worker - INFO - asking worker to shutdown gracefully, spot interruption at 2023-09-21T23:11:01Z
distributed.worker - INFO - Closing worker gracefully: tls://10.0.34.36:41345. Reason: instance-preemption
distributed.worker - INFO - Stopping worker at tls://10.0.34.36:41345. Reason: instance-preemption
distributed.nanny - INFO - Closing Nanny gracefully at 'tls://10.0.34.36:38745'. Reason: instance-preemption
distributed.core - INFO - Connection to tls://10.0.34.214:8786 has been closed.
distributed.worker - INFO - done asking worker to close gracefully
distributed.nanny - INFO - Worker closed
distributed.nanny - INFO - Closing Nanny at 'tls://10.0.34.36:38745'. Reason: nanny-close-gracefully
```

**Comment by crusaderky** [comment]
FYI @ntabris this should _rarely_ be an issue on Coiled with spot instances turned on, as the chances of a task hitting 3 times in a row a worker just before it's shut down are very low. However users that disabled retries for whatever reason (typically, to increase dev velocity when tasks have a tendency to go OOM) will definitely notice.

**Comment by fjetter** [comment]
Well, once upon a time this worked as expected. The graceful shutdown should close the worker using `safe=True` (which it is. Is suspect this is an ordering thing and the worker removal triggered by the closed connection happens first. I'm a bit surprised this isn't tested.
