### ISSUE TITLE
Problem with dask-ssh in combination with hostnames

### ISSUE THREAD

**Issue by malteger** [dask/distributed#824]
When starting a distributed cluster with dask-ssh, the hostnames supplied via commandline or hostfile are passed to the workers with the `--host` parameter. This might be useful for the bokeh interface on the scheduler, but in our case the worker binds to the local interface only (the hostname is listed in the `/etc/hosts` with `127.0.0.1`), so a connection from the scheduler to the worker is not possible (maybe I am wrong and this is somehow not needed, but I receive errors about failed connects).

A possible solution is to provide IP-Adresses, because with that the worker binds to the correct interface. For me this is less optimal, as I cannot easily see where I start my workers.

My quick and dirty fix was to remove the `host` option from the worker start call.

So I would like to suggest adding an option to `dask-ssh` to prevent using the `host` option when spawning a worker (as this works perfectly fine in internal networks where some open ports are not such a big problem).

If you are interested in this `dask-ssh` option, I would implement this in a proper way and create a PR.

**Comment by mrocklin** [comment]
Hi @malteger .  Adding such an option makes sense to me.  A PR would be most welcome.
