### ISSUE TITLE
Support for aiohttp 3.8.6

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8248]
`distributed/http/scheduler/tests/test_scheduler_http.py::test_api` has started failing since aiohttp was bumped from 3.8.5 to 3.8.6:

https://github.com/dask/distributed/actions/runs/6457646619/job/17529638800?pr=8246

```
>               assert (await resp.text()) == "API V1"

distributed/http/scheduler/tests/test_scheduler_http.py:419: 
[...]
E           DeprecationWarning: Automatic charset detection will be removed in 3.9, see: https://docs.aiohttp.org/en/stable/client_advanced.html#character-set-detection
```

**Comment by fjetter** [comment]
xref https://github.com/dask/distributed/pull/8249
