### ISSUE TITLE
Cancelled-error when using LocalClient() with no arguments

### ISSUE THREAD

**Issue by bschreck** [dask/distributed#825]
When I run a LocalCluster in a separate process, and connect to it using LocalClient('127.0.0.1:8786') all my code runs fine.

However, when I just initialize LocalClient() I periodically get "CancelledError"s that seem to only come up sometimes. Maybe 50-75% of the time.

**Comment by mrocklin** [comment]
LocalClient -> Client ?

**Comment by mrocklin** [comment]
If so, then calling `client = Client()` should definitely not cause cancelled errors.  

Can you provide a minimal reproducible example?

**Comment by bschreck** [comment]
Yes sorry that's what I renamed it. Let me make an example

**Comment by bschreck** [comment]
So actually it doesn't seem to be a difference between Client() and running LocalCluster() separately. But I can still reliably produce the error with the following code (around 50% of the time):

    from distributed import Client
    from dask import delayed
    import numpy as np



    class Datastore(object):
        pass
    skeleton_datastore = Datastore()

    def register_dataset(ds):
        ds.dataset = np.zeros(10)
        return ds

    client = Client()
    registered = delayed(register_dataset)(skeleton_datastore)
    persisted_datastore = client.persist(registered)
    client.publish_dataset(my_dataset = persisted_datastore)
    datastore = client.get_dataset('my_dataset')


    datastore_tmp_object = delayed('datastore-tmp')
    run_name_tmp_object = delayed('run_name-tmp')


    def get_dataset(x, datastore, run_name):
        print "X:", x
        print "Datastore:", datastore
        return datastore.dataset

    n = delayed(get_dataset)(x = 2,
                         datastore=datastore_tmp_object,
                         run_name=run_name_tmp_object)

    full_dask = n.dask
    add_params = {datastore_tmp_object.key: datastore.key,
              run_name_tmp_object.key: 'run1'}
    full_dask.update(add_params)

    results = client.get(full_dask, n.key)
    print results

When the error happens, the datastore is not computed before sending as an argument to get_dataset(), so printing it out just prints a string, and the error occurs because of trying to access `.dataset` from the string. It's relevant to note that if I remove the run_name argument, or include it just as a regular parameter instead of a delayed object, the error goes away.

**Comment by mrocklin** [comment]
For delayed objects n.dask computed, you would need to mess with the `._dasks` attribute, which has a list of constituent dictionaries.  You might be able to get away with something like the following instead:

    x._dasks = [full_dask]

However, beware that this sort of operation on private data isn't really supported.  We reserve the right to change this internal API without notice.

**Comment by mrocklin** [comment]
I'm going to go ahead and close this.  Please reopen if there is still a live issue.
