### ISSUE TITLE
Regression in `test_decide_worker_coschedule_order_neighbors`

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8255]
https://github.com/dask/dask/pull/10535 broke `test_decide_worker_coschedule_order_neighbors`:

https://github.com/dask/distributed/actions/runs/6469648247/job/17564120071?pr=8253
```
            # No more than 2 workers should have any keys
>           assert sum(any(k in w.data for k in keys) for w in workers) <= 2
E           assert 5 <= 2
```

**Comment by fjetter** [comment]
This is actually a regression in dask.order

![image](https://github.com/dask/distributed/assets/8629629/163f80bc-79e1-4bb8-baa8-072903e33e72)


I'll need to investigate a little to see how bad this is

**Comment by fjetter** [comment]
This is still failing and still marked xfailed
