### ISSUE TITLE
When running hyper tuning on multiple workers, I get the same parameters across workers.

### ISSUE THREAD

**Issue by luchinoprince** [dask/distributed#8278]
Hello to everyone!

I am trying to distribute a hyper tuning of parameters across multiple GPUs, but I am struggling with a result. To create the architecure I followed the instructions found at https://docs.rapids.ai/deployment/nightly/examples/rapids-optuna-hpo/notebook/. I hence create a Cluster with currently two workers with shared storage space.
```python
cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1", n_workers=None, threads_per_worker=1)

c = Client(cluster)
# Query the client for all connected workers
workers = c.has_what().keys()
n_workers = len(workers)
c
### Create common storage space for all workers
storage = optuna.integration.DaskStorage()
```
I then create a study

```
study = optuna.create_study(
    sampler=optuna.samplers.TPESampler(seed=None),
    study_name="demo",
    direction="minimize",
    pruner=optuna.pruners.MedianPruner(),
    storage=storage,
)
```

Finally I (think) parallelise the hyper tuning across the two workers as follows

```
futures = [
    c.submit(
        study.optimize,
        lambda trial: objective(trial),
        show_progress_bar=True,
        n_trials=2,
        pure=False,
    )
    for _ in range(n_workers)
]
wait(futures)
```

Where `objective` is defined as follows
```
def objective(trial):
    #print(f"worker-ID:{get_worker().id}, name:{get_worker().name}")
    device = int(get_worker().name)
    warnings.filterwarnings("ignore")
    param = {
            'lr' : trial.suggest_uniform('lr', 1e-5, 1e-3),
            'eta_J' : trial.suggest_uniform('eta_J', 1e-6, 1e-4),
            'eta_h' : trial.suggest_uniform('eta_h', 1e-5, 1e-3),
            'batch_size' : trial.suggest_categorical('batch_size', [16, 32, 64])
            }
    print(f"I AM STARTING A TRIAL on device: {device}")
    ## I Recreate otherwise I would risk to start the new training at the previous end.
    decoder = DLMODEL(q, n_layers, d_model, input_encoding_dim, param_embed_dim, n_heads, n_param_heads, dropout=dropout)
    decoder.to(device)

    

    test1, test2, test3 = train_and_evaluate(param, decoder, device, trial)

    ### This to try to help memory consumption
    #decoder = None
    #torch.cuda.empty_cache()
    ### I just look at the loss on the structure and superfamily test dataset. 
    return (test2+test3)/3
```

To my understanding this should splits the trials between the workers, to increase the speed. But when I look at the parameters passes I see the following: 

```
.....
.....
I AM STARTING A TRIAL on device: 0
I AM STARTING A TRIAL on device: 1
param: {'lr': 0.0006794834295579704, 'eta_J': 3.854432649260403e-05, 'eta_h': 0.00029806267838271993, 'batch_size': 32}
param: {'lr': 0.0006794834295579704, 'eta_J': 3.854432649260403e-05, 'eta_h': 0.00029806267838271993, 'batch_size': 32}
.....
.....
```

Hence basically it is testing twice the same hyperparameters on every worker, which to me makes no sense as I get no increase of speed. Here the function to optimise on a the training of a DeepLearning model, so it is very computationally heavy. 

Let me know!

**Environment**:
- Dask version: 2023.7.1
- Python version: 3.10.12
- Operating System: Linux

**Comment by luchinoprince** [comment]
Hi! Thanks for the quick response. I am sorry that I did not find the issue you where referencing, as it exactly the same problem. Yes updating Optuna does seem to solve that issue. I have other weird behaviours that I need to get on top of, but they are separate from this issue, so I guess I should(in case) create a new one? Or can I maybe add it below here?

**Comment by jrbourbeau** [comment]
No worries -- glad to hear updating resolved the issue. I'll go ahead and close this issue. Feel free to open up an issue here if you encounter something you think is a bug in dask and over in https://github.com/optuna/optuna for optuna-related issues
