### ISSUE TITLE
Bokeh System charts look strange

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#8295]
<img width="514" alt="Screenshot 2023-10-20 at 8 01 39 PM" src="https://github.com/dask/distributed/assets/306380/da5e3b9a-0649-4943-bf1d-42c03b9ae134">

**Comment by jacobtomlinson** [comment]
What version of bokeh is this?

**Comment by hendrikmakait** [comment]
It's been a while since the last activity on this issue. I'm closing it as stale, please reopen it if this is still a problem.
