### ISSUE TITLE
test_pyspark: No module named 'coiled.spark'

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8302]
This test is being skipped at all times, even if pyspark is in the environment.yml.

SKIPPED [1] tests/tpch/test_pyspark.py:5: could not import 'coiled.spark': No module named 'coiled.spark'

CC @mrocklin

**Comment by mrocklin** [comment]
That's correct.   This requries Coiled's spark capability to run, not just pyspark.  That hasn't been released, but likely will be released shortly.

**Comment by mrocklin** [comment]
@crusaderky was this intended for coiled/benchmarks?

**Comment by fjetter** [comment]
Wrong repo

**Comment by crusaderky** [comment]
> @crusaderky was this intended for coiled/benchmarks?

yes, sorry about the confusion.
