### ISSUE TITLE
Bokeh 3.3.0 uses absolute URLs and breaks proxied dashboards

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#8333]
I noticed when using `distributed==2023.10.1` with `bokeh==3.2.2` the URLs to the Bokeh JavaScript are relative.

```html
<script type="text/javascript" src="static/js/bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357"></script>
```

But when upgrading to `bokeh==3.3.0` they become absolute.

```html
<script type="text/javascript" src="/static/js/bokeh.min.js?v=39ef57c3a83533e24f961e5c27f651a61045dbccefac4b5df86a7680b1edaff31886a7c0322250ffb0d758fa14ae156c9b640f60cca99f020096b050a4dbb571"></script>
```

This breaks dashboards that are being proxied at some sub-url.

Setting `dask scheduler --dashboard-prefix ""` doesn't fix it.

### Reproducer

```
$ pip install dask distributed bokeh==3.3.0
$ dask scheduler &
$ curl localhost:8787/status | grep bokeh.min.js
```

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson -- I think something similar was reported over in `dask-kubernetes` (maybe that's what's spawning this issue). Do you have thoughts on how we might fix? Also cc @bryevdv for visibility

**Comment by bryevdv** [comment]
3.3.1 will be probably go out today. I'd try that first, if that does not fix then most likely just a bug.

**Comment by bryevdv** [comment]
cc @mattpap
