### ISSUE TITLE
Setting `distributed.scheduler.pickle=false` seems to break everything

### ISSUE THREAD

**Issue by mattjudge** [dask/distributed#8386]
The docs at https://docs.dask.org/en/latest/configuration.html#distributed.scheduler.pickle make it sound like setting `distributed.scheduler.pickle` should rarely be an issue unless attempting to run code directly on the schedular, however the following seems to indicate that the schedular relies on `distributed.scheduler.pickle` being set to `True`:

```python
with dask.config.set({"distributed.scheduler.pickle": False}):
    client = Client()
    total = client.submit(lambda x: x, 3)
    total.result()
```
```
Traceback (most recent call last):
  File "/home/.../.venv/lib/python3.11/site-packages/distributed/protocol/core.py", line 160, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/home/.../.venv/lib/python3.11/site-packages/distributed/protocol/core.py", line 154, in _decode_default
    raise ValueError(
ValueError: Unpickle on the Scheduler isn't allowed, set `distributed.scheduler.pickle=true`
```

Is my understanding incorrect?

**Environment**:

- Dask version: 2023.11.0
- Python version: 3.11.6
- Operating System: WSL
- Install method (conda, pip, source): poetry

**Comment by hendrikmakait** [comment]
@mattjudge, thanks for raising this issue.

@fjetter: From what I understand, #7564 forces us to unpickle data on the scheduler, rendering the configuration mentioned in the issue obsolete. Am I missing something here?

**Comment by fjetter** [comment]
Indeed, apologies for not documenting this or in fact keeping this option around. Disabling pickle is no longer an option since `2023.4.0`

If you want to secure your cluster the only sensible option is to use TLS encryption for your connections.

**Comment by mattjudge** [comment]
Thanks for the update. Ideally, I'd like to be able to run a worker in an untrusted environment. In this particular scenario, I'm not worried about the accuracy of results returned, but want to ensure it's not possible for a worker to invoke arbitrary code on the schedular / client. I was going to do that by forcing the schedular and workers to use a safe serialization method, and disable pickle deserialization on the schedular, but I guess that's no longer possible? Are there any alternatives that come to mind?
