### ISSUE TITLE
`isinstance(Future, Future)` evaluates to False

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dask/distributed#8406]
**Describe the issue**:

```python
from dask.distributed import Future
isinstance(Future,Future) # prints False
```

This is arguably unexpected behavior.

**Environment**:

- Dask version: 2023.12.0
- Python version: 3.10+
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by hendrikmakait** [comment]
This is expected, note that `Future` is not an _instance_ of the `Future` class, but the class itself. As such, it is an instance of the `type` class:

```python3
>>> from dask.distributed import Future
>>> type(Future)
<class 'type'>
```

**Comment by Andrew-S-Rosen** [comment]
Thanks, @hendrikmakait. I'll go ahead and close this with that in mind. I was trying to write some logic that checked whether a `Future` generated from a `client.compute()` was indeed a `Future`. Seems the `isinstance` check is not appropriate here.

**Comment by hendrikmakait** [comment]
FWIW, `issubclass(Future, Future)` evaluates to `True`.

**Comment by Andrew-S-Rosen** [comment]
Thanks! Somehow, I hadn't thought to try that one. Makes sense!
