### ISSUE TITLE
ray ignores memory limits and allocated 30 % of memory according to dashboard

### ISSUE THREAD

**Issue by chrisn-pik** [dask/distributed#8418]
**Describe the issue**:

The ray head reserves a lot of memory. According to the [docs memory management](https://docs.ray.io/en/latest/ray-core/scheduling/memory-management.html), Ray reserves 30% of available memory, when starting an instance. How can this be changed? I tried to reduce this memory by setting ```_memory=10**6, object_store_memory=10**8, _redis_max_memory =10**7 ``` when using ```ray.init()```.  However, the ray dashboard shows that still 30% of available memory is reserved. How can this be reduced? I did not see more options for ```ray.init``` in the [docs ray init](https://docs.ray.io/en/latest/ray-core/api/doc/ray.init.html)

**Minimal Complete Verifiable Example**:

```python
import ray
ray.init(_memory=10**6, object_store_memory=10**8, _redis_max_memory =10**7)
```

<img width="1177" alt="Screenshot 2023-12-18 at 11 13 28" src="https://github.com/dask/distributed/assets/89135626/586c218d-d15f-45b3-b5e2-193381d888e5">

**Anything else we need to know?**:
I want to reduce the memory usage by HEAD to avoid oom using slurm perhaps related to (https://github.com/ray-project/ray/issues/13607), but the minimum working example is unrelated to slurm, I want to understand how to reduce memory by head.

**Environment**:
- ray: 2.8.1
- Python version: 3.10
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by hendrikmakait** [comment]
@chrisn-pik: Your issue seems to be unrelated to Dask, you probably want to raise this over at https://github.com/ray-project/ray.
