### ISSUE TITLE
Explicitly retry failed tasks

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#852]
Currently if a task fails it is marked with an exception and that state is final.  If the user then changes an external reason for the failure they may want to rerun that failed task and restart all dependent tasks.

It would be convenient to have a `retry` operation that explicitly enabled this behavior.

**Comment by demianw** [comment]
It will also be convenient to set the `retry `operation depending on the exception.

**Comment by mrocklin** [comment]
cc @pitrou if you want to get into adding things into the scheduler itself, this would be a good issue.  This is one of our more-requested features.  

If I were to do this I would do the following:

-  Create a dict on the scheduler that mapped keys to the number of retries available (no key in the dict means no retries allowed)
-  In Scheduler.stimulus_task_errored we check this dict and, if it contains a positive number then we transition the task to `waiting` rather than `erred`
-  In the client add `retries=int` keywords to submit, map, and maybe compute/persist in a similar way to how it is implemented for `resources=`
-  Be sure to clean up the state at appropriate times, notably in `remove_key`  and `clear_task_state`

**Comment by pitrou** [comment]
So the retry operation would be implicit rather than explicit? Or would it be desirable to allow the user to retry a future as well?

**Comment by mrocklin** [comment]
People have asked for both.  I get the implicit request more often.

**Comment by pitrou** [comment]
Do we want to re-open this issue for an explicit `Client.retry` method?
