### ISSUE TITLE
Tensorflow Support

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#856]
Stephan (@shoyer) and I had a long chat about possible value to using Dask alongside Tensorflow.  There are a few opportunities:

0.  You can do trivial hyperparameter searches or map trained models against large amounts of data easily.  This doesn't require any special work on our part.  However it would be more convenient foolproof if we knew how to easily serialize and deserialize tensorflow graphs.
1.  We can launch Tensorflow Servers from Dask workers.  This makes it trivial to deploy distributed Tensorflow if you're already running Dask.
2.  We can feed distributed tensorflow training from data generated by dask, presumably by dataframes, arrays, etc..  The interesting part here is defining the boundary at which we hand over control that is both convenient, but also a clear and acceptable contract to both devs and users.

Launching Tensorflow servers from Dask workers
--------------------------------------

This appears to be pretty trivial.  We can break it down into the following steps:

1.  Look at the workers we have currently, probably using `client.scheduler_info()`
2.  Take input from the user to define a cluster spec:

```python
tf.train.ClusterSpec({
    "worker": [
        "worker0.example.com:2222",
        "worker1.example.com:2222",
        "worker2.example.com:2222"
    ],
    "ps": [
        "ps0.example.com:2222",
        "ps1.example.com:2222"
    ]})
```

3.  Call a function like the following to attach a tensorflow server to each worker

```python
def f(job_name=None, index=None, dask_worker=None):
    server = tf.train.Server(cluster, job_name="local", task_index=1)
    dask_worker.tensorflow_server = server
    return 'OK'

for i, worker in enumerate(client.scheduler_info()['workers']):  # TODO: do this asynchronously
    client.run(f, job_name=..., index=i)
```

The tricky parts here are how to listen to get enough information from the user on how to create a proper cluster spec.  Presumably we should take inputs like the following:

1.  None: do something naive but sensible
2.  Some number of workers per group like `{'worker': 5, 'ps': 2}`
3.  Accept a full spec

This is a bit tricky if the user doesn't know the current state of the dask cluster.

In any case, we return the resulting cluster spec, and possibly a mapping from tensorflow address to dask worker address

Feed NumPy arrays from Dask workers to Tensorflow Servers
------------------------------------------------------------

Because Dask and Tensorflow are co-located in the same process it is trivial to move data from one to the other.  

Distributed Tensorflow programs seem to be written in a manner similar to MPI programs where we send the same function to everyone to run and, based on their role in the cluster they do one of a few things.  In a typical scenario the model fits on one machine, but we want to distribute the training, synchronizing parameters somehow on special parameter server machines (which are just some of the Tensorflow servers).  

In this case we will accept a function from the user that accepts the Tensorflow server and a Queue into which Dask will deposit numpy arrays or pandas dataframes.  This function will construct the model to train and then pull from the queue to consume data.  What this function does is entirely up to the user (here is the boundary).  Dask will run this function within a long-running task separate from the normal threadpool.

Eventually it would be nice to deliver not a Python Queue, but a Tensorflow Queue.  Modern tensorflow workflows seem to involve these for easier-to-reason-about solutions.

It's worth pointing out that this is just one common workflow.  Our goal should be, again, to find a boundary/contract that is clear to implement in small/finite time and palatable enough to users so that they are not constrained.

**Comment by jcrist** [comment]
I believe this was resolved (at least partially) with https://github.com/dask/dask-tensorflow. Closing.
