### ISSUE TITLE
Problems with CPU plot on status page

### ISSUE THREAD

**Issue by abast** [dask/distributed#859]
I repeatedly noticed that the CPU plot looks strange after some time:

![cpu_plot](https://cloud.githubusercontent.com/assets/20513804/22647177/534f6b5c-ec70-11e6-94de-7d7ee5aa97b3.jpg)

Is this a known problem? Somebody else experiencing the same?

**Comment by mrocklin** [comment]
I haven't seen that behavior on the CPU plot.  However it looks like it's getting records out of order.  One approach might be to just drop any incoming piece of information that isn't in order.

**Comment by abast** [comment]
Seems to be fixed.
