### ISSUE TITLE
CI failing with pandas.errors.SettingWithCopyWarning

### ISSUE THREAD

**Issue by milesgranger** [dask/distributed#8591]
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
FAILED distributed/shuffle/tests/test_merge.py::test_merge[False-outer] - pandas.errors.SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Example run:
https://github.com/dask/distributed/actions/runs/8338285775/job/22818347973#step:20:4371

**Comment by jrbourbeau** [comment]
It looks like we're still having this failure on `main`. @fjetter @milesgranger any idea why that is? Maybe we're not installing `dask-expr` `main`? Maybe environment caching?
