### ISSUE TITLE
Asynchronous use of Distributed yields "No Scheduler Connected"

### ISSUE THREAD

**Issue by ShaneMill1** [dask/distributed#8603]
Assume that you have an existing Dask Cluster running. For the example below, I'll just use a port for a Local Cluster:

(Pdb) client=Client('0.0.0.0:5600',asynchronous=True)
<Client: No scheduler connected>

This yields "no scheduler connected".

For background, I am implementing a web service that uses Gunicorn/Gevent on the frontend, and Dask on the Backend. Dask is implemented as a Cluster using ECS. With the inability to connect to the scheduler, we are unable to scale the application like we want to.

Is this normal behavior or are we supposed to be able to connect to a remote cluster with asynchronous=True?

**Comment by mrocklin** [comment]
You'll have to await the client object in async mode I think.

**Comment by ShaneMill1** [comment]
Hey @mrocklin, that was the issue, thanks!

```
 61         async def data_async(self,ds_location_list):
 62              client=await Client('0.0.0.0:5600',asynchronous=True)
 63              import pdb; pdb.set_trace()
 64              # combined = await xr.open_mfdataset(ds_location_list, engine='zarr', chunks={}, preprocess=self.set_dims, combine='nested', compat='no_conflicts', coords='minimal', consolidated=False, parallel=False)
 65  ->          paths=ds_location_list
 66              engine='zarr'
 67              preprocess=self.set_dims
 68              combine='nested'
 69              compat='no_conflicts'
 70              coords='minimal'
(Pdb) client
<Client: 'tcp://XXX.XXX.X.XX:5600' processes=1 threads=16, memory=30.26 GiB>```
