### ISSUE TITLE
Uploading zip module

### ISSUE THREAD

**Issue by bmaisonn** [dask/distributed#865]
Hi,
I'm using distributed.upload_file to upload some .py files that i need to use in my worker.
Also I would like to import a module that I zipped.
[ZipImport](https://docs.python.org/3.5/library/zipimport.html) gives the possibility to do that easily however it's not implemented in worker.upload_file yet.
Do you mind if I had this functionality as per egg archives ?
Except if i missed something, the code is straightforward (See the change [here](https://github.com/bmaisonn/distributed/commit/08e09de63250901e2df865db02a0b5a8a279eae2))
Regards,
Bertrand

**Comment by mrocklin** [comment]
Sounds good to me.  I wasn't aware of zipimport.  Your solution looks good to me.  Is it easy to add a test for this functionality as well?

**Comment by bmaisonn** [comment]
I suppose that test_client is the right place for that, right ?
I see an 'egg' file in test folder, can I add a zip file too ?
Thx

**Comment by mrocklin** [comment]
Adding a small file there seems reasonable, yes.

**Comment by mrocklin** [comment]
Creating and reliably deleting a file (such as with the tmpfile
contextmanager) is slightly preferred if convenient.

**Comment by pitrou** [comment]
Closing after the functionality was merged in #886.
