### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by AlbertDeFusco** [dask/distributed#867]
`client.gather()` accepts an argument `errors=`. What values are allowed and what do they do?

Are there other methods to work with a collection of futures as a whole where one or more have thrown an exception?

Is there a way to instruct dask (distributed) to persist/cache the inputs to the failed key in the graph?

**Comment by mrocklin** [comment]
I've extended the docstring to include a proper parameters section.  

> Is there a way to instruct dask (distributed) to persist/cache the inputs to the failed key in the graph?

Short answer is "no"
