### ISSUE TITLE
Warn user if we encounter too many tasks groups on the scheduler

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8678]
# Problem

As described in https://github.com/dask/distributed/issues/8677, having too many task groups can become prohibitively expensive, in particular for the `TaskProgress` dashboard.

# Solution

We should warn the user if there are too many tasks groups on the scheduler. This might either be a simple threshold as mentioned in https://github.com/dask/distributed/issues/8677 or something that also involves a ratio of tasks to task groups.

**Comment by fjetter** [comment]
With https://github.com/dask/distributed/pull/8681 I hope that we won't see any more issues popping up. Having "many" task groups is still something unusual but I'm not sure how bad it really is
