### ISSUE TITLE
Exception reporting/rerunning

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#868]
When a task errors, all tasks that depend upon it also error, and the user finds this out when they do a `gather` on some end-product. Whilst the full traceback is printed, which is often enough to pinpoint the problem, the user cannot debug without running the whole graph locally using `get_sync`. 
What we would like is to be able to run just the one task that failed, locally, with the specific inputs/corner case that caused the failure, without having to run the whole computation locally. The scheduler already has the information about which task failed (i.e., erred even though none of the inputs had), and the inputs that it needed (which are probably still in memory, or can be recreated on the cluster).

One step around this is to use submit/futures instead of delayed (because futures report their status), but that is a less flexible programming paradigm, and doesn't fit with collections, nor do we know the inputs of a given future unless there is a local data structure representing the graph that delayed would have created.

**Comment by martindurant** [comment]
@mcg1969

**Comment by mrocklin** [comment]
I agree that this would be useful.

**Comment by mrocklin** [comment]
OK, so this is how I would approach this problem:

I would make a method on the client, something like "recreate_error_locally" (although there are probably better names).  Alternatively maybe this is private and we trigger it in calls like `client.gather(recreated=True)`

That client function looks a bit like the following:

```python
@gen.coroutine
def _recreate_error_locally(scheduler.stuff):
    futures = futures_of(stuff)
    deps, cause, task = yield self.scheduler.cause_of_failure(keys=[f.key for f in futures])
    function, args, kwargs = Worker._deserialize(task)

    # Inform scheduler that we want these keys.  This *may* work but I'm uncertain that it's enough.
    futures = self._graph_to_futures({}, deps)  

    # Get data from remote workers, pack into args and kwargs   
    data = yield self._gather(futures)
    data = dict(zip(deps, data))
    args = pack_data(args, data)
    kwargs = pack_data(kwargs, data)

    func(*args, **kwargs)  # run the function, hopefully trigger exception.
```

On the scheduler you will need to create the `cause_of_failure` route

```python
def cause_of_failure(self, stream=None, keys=None):
    for key in keys:
        if key in self.exceptions_blame:
            cause = self.exceptions_blame[key]
            return self.dependencies[cause], cause, self.tasks[cause]
```

You'll also need to add this to `self.handlers`
