### ISSUE TITLE
Incorrect `bokeh` installation instructions 

### ISSUE THREAD

**Issue by sjrothfuss** [dask/distributed#8716]
On the Client dashboard, the instructions for pip installing `bokeh` don't work for me as written. Am I missing something?

Webpage:
![image](https://github.com/dask/community/assets/108840392/222bbdeb-bfd7-46ac-b14d-79a346da4d5b)

Code and output:
```bash
$ pip install bokeh!=3.0.*,>=2.4.2
ERROR: Invalid requirement: 'bokeh!=3.0.*,'
```
Using `pip install bokeh==2.4.2` appears to work fine though.

**Comment by jrbourbeau** [comment]
Thanks for the issue @sjrothfuss. You'll need to add quotes around that version constraint 

```
pip install "bokeh!=3.0.*,>=2.4.2"
```

Here's a PR to fix that message https://github.com/dask/distributed/pull/8717

**Comment by sjrothfuss** [comment]
Thanks, @jrbourbeau. `pip install bokeh==2.4.2` did the trick for me before and your version with quotes works too.
