### ISSUE TITLE
Unable to install/update to newest version of msgpack-python

### ISSUE THREAD

**Issue by vivadiva81** [dask/distributed#8718]
Hi all, 
I am trying to work with Dask Distributed in June 2024. I have installed
Python 2.12
pandas 2.2
dask 2024.5.0

setting up dask distributed client
and calling daskdf.compute() produced this error.

2024-06-22 10:59:38,231 - distributed.protocol.core - CRITICAL - Failed to deserialize

This error is related to an older version of msgpack-python=1.0.3 that was auto installed when I installed dask, graphviz, python-graphviz and distributed. reading here (https://github.com/dask/distributed/issues/8038) I figured I need to update msgpack-python as it is used for serialization across cluster workers.

However this command does not allow me to update/install - it just hangs!!

(daskpy3) PS C:\Users\u0XXXXX> conda install -c conda-forge msgpack-python==1.0.8
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -

any help? ideas please?

**Comment by vivadiva81** [comment]
adding some more information here.

So I figured out that anaconda is what is preventing me from updating msgpack.

Also not sure whether the package is msgpack or msgpack-python.
This page of docs for the latest msgpack=1.0.8 says that it has been renamed to msgpack now
However, my anaconda install in June 2024 came with msgpack-python = 1.0.3

Here is the code I ran.

(daskpy3) PS C:\Users\u0XXXX> conda list msgpack
# packages in environment at C:\Users\u0625859\Anaconda3\envs\daskpy3:
#
# Name                    Version                   Build  Channel
msgpack-python            1.0.3           py312h59b6b97_0
(daskpy3) PS C:\Users\u0XXXXX> conda update msgpack-python
Collecting package metadata (current_repodata.json): done
Solving environment: \

Updating msgpack-python is constricted by

anaconda -> requires msgpack-python==1.0.3=py312h59b6b97_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

**Comment by fjetter** [comment]
I suspect you should define conda forge as an extra channel, e.g. `-c conda-forge` (see here https://conda-forge.org/docs/user/introduction/#how-can-i-install-packages-from-conda-forge)

Most tools are only publishing on `conda-forge`
