### ISSUE TITLE
Locking service and cluster-wide state

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#872]
For some complex workflows it is convenient to coordinate state between multiple long-running tasks.  Two common requirements include:

1.  Locking some external resource so that no two tasks can run related blocks of code at the same time
2.  Communicating small amounts of global state, like a stop signal or the number of times that something has occurred.

For example consider the case where we want to perform an action at most five times but never more than once at a time:

```python
c.global_state['identifier'] = 0

def f():
    with local_client() as c:
        with c.get_lock('identifier') as lock:
            if c.global_state['identifier'] >= 5:
                return
            else:
                perform_special_action()
                c.global_state['identifier'] += 1
```

Locks have come up before when people have wanted to write to NFS-stored HDF5 files (which don't support concurrent writes).  The example above is a more complex version of exactly-once semantics (relevant for side effects).  

At some point we might want to extend the locking to include different modes (read-only, concurrent writes, etc.) (See https://en.wikipedia.org/wiki/Distributed_lock_manager#Lock_modes).

Locks and cluster-wide state would be centrally managed on the scheduler as an extension.

**Comment by jreback** [comment]
this also comes up in writing to a single HDF5 where writing needs a lock

**Comment by spitz-dan-l** [comment]
This would be great. I am currently running a [multiprocessing Manager server](https://docs.python.org/3/library/multiprocessing.html#using-a-remote-manager) from the instance where the scheduler is running to provide this in an ad hoc way.

**Comment by mrocklin** [comment]
We now have locks, shared global variables, and global queues.  See http://distributed.readthedocs.io/en/latest/api.html
