### ISSUE TITLE
Repeated calls to `url_escape` take around 40% of CPU time of scheduler

### ISSUE THREAD

**Issue by jonded94** [dask/distributed#8761]
**Describe the issue**:

I'm currently running an extreme workload on Dask with around 2400 individual workers (all individual processes, no multithreading). This is because I'm using Dask as a generic task orchestration mechanism for custom GIL-locked logic, nothing about Dask dataframes.

The scheduler in principle seems to cope with that, I'm getting scheduler Tick times around ~20ms-300ms. When my workloads ends, I still have around 15k Dask tasks in-memory that only very gradually are sent to the actual client, with around ~0.8 tasks/s.

I measured that with `py-spy` and generated some speedscope metrics, with some interesting findings.

In general, around 89% of time is spent purely on `bokeh` stuff, so frontend dashboard updates, that means that only just above 10% of the time, the scheduler is doing actual scheduling. In more detail, the scheduler spends almost 40% in these `url_escape` calls sprinkled across the codebase:

- https://github.com/dask/distributed/blob/b8022373324758dbe9a19aab03a12284a7439246/distributed/dashboard/components/scheduler.py#L201
- https://github.com/dask/distributed/blob/b8022373324758dbe9a19aab03a12284a7439246/distributed/dashboard/components/scheduler.py#L1842
- https://github.com/dask/distributed/blob/b8022373324758dbe9a19aab03a12284a7439246/distributed/dashboard/components/scheduler.py#L734

These scale `O(n)` with `n` being the number of workers, so this is getting to a problem when you have a whole lot of workers.

I think this easily could be solved by hiding this call behind some caching mechanism, since the `url_escape` of all workers should not change at all basically.

![image](https://github.com/dask/distributed/assets/30271979/41023a32-3837-48a3-8a39-6175d9ecab97)

[speedscope.json](https://github.com/user-attachments/files/16180476/speedscope.json)

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.7.0
- Python version: 3.10
- Operating System: Linux, Debian
- Install method (conda, pip, source): `poetry` / `pip`

**Comment by fjetter** [comment]
This was supposed to be fixed by the cache added in https://github.com/dask/distributed/pull/8725 :/

**Comment by fjetter** [comment]
we're still iterating of course, even with the cache so what you see in your profile might be the first invocation of that

**Comment by jonded94** [comment]
This is after several *hours* of the cluster running constantly at full tilt basically, so I'd assume the caches are very much hot by that time?

**Comment by jonded94** [comment]
I'm missing the call to `lru_cache` for some reason in my profiling? It's definitely calling `url_escape` from some `distributed.utils` file though..

**Comment by jonded94** [comment]
Another FYI: With <2000 workers, the scheduler seemed to just about cope with the situation and was able to send in-memory tasks to the client. Around ~15:30, we increased to number of workers to 2400 though, then you immediately can see that the number of in-memory tasks just keeps rising and even after everything is done, all workers are stale, but the scheduler is only able to send the results extremely gradually to the calling client.

![image](https://github.com/dask/distributed/assets/30271979/576d358e-e09a-42bf-a335-f39c952c9025)

I would expect this "in-memory" curve to basically drop down to zero almost immediately.

**Comment by jonded94** [comment]
Ah, got it. `functools.lru_cache` only has 128 available cache slots. The more modern `functools.cache` (introduced in Python3.9) has an indefinite size.

So basically, even though it's using a cache here, since it's an LRU cache and only of a very small size, this workload basically is uncached the *entire* time :D

**Comment by fjetter** [comment]
> Ah, got it. `functools.lru_cache` only has 128 available cache slots. The more modern `functools.cache` (introduced in Python3.9) has an indefinite size.
> 
> So basically, even though it's using a cache here, since it's an LRU cache and only of a very small size, this workload basically is uncached the _entire_ time :D (for my amount of workers, [> 128] that is)

🤦 thanks!

Care to contribute a fix?

**Comment by fjetter** [comment]
from the documentaion https://docs.python.org/3/library/functools.html#functools.cache might be the way to go

**Comment by jonded94** [comment]
Used that in my [PR](https://github.com/dask/distributed/pull/8762), yeah.
