### ISSUE TITLE
Feature request: Worker port ranges and/with nprocs support

### ISSUE THREAD

**Issue by stuartarchibald** [dask/distributed#899]
I think it would be quite useful for `dask-worker` to support `--nprocs` with `--foo-port=[range]` so that systems with specific port ranges opened can have a number of processes opened from one call applied to a specified range opposed to having to write a shell loop to do the same.

Further, general support for port ranges and failing over to the next available port in a range if the current is taken would probably be quite useful in a similar situation as that described above.

Thanks.

**Comment by mrocklin** [comment]
Does anyone with some networking background know of a good way to ask the OS to connect to a port within a certain range?

cc @pitrou

**Comment by pitrou** [comment]
@stuartarchibald, I assume you mean `--nprocs=N --start-port=X` will bind to ports X, X+1, X+2, etc? Are you expecting a specific pattern (e.g. first all worker ports, then all Bokeh ports), or is it indifferent?

**Comment by mrocklin** [comment]
I suspect he's looking for something like `--port=5000:6000`.  Often people are told that they need to stay within a particular range of ports.

**Comment by stuartarchibald** [comment]
I think being able to express a port range for each component would be ideal thanks. Something like:
```
dask-worker --nprocs=16 --worker-port=5000:5100 --http-port=6000:6100
```
which would start 16 worker processes bound to free ports between 5000 and 5100 and the same with `http` but `s/5/6/g`. This is with view of use cases where open ports are restricted to some particular range but some external reason requires computation to be undertaken in separate processes.

**Comment by mrocklin** [comment]
I see two options:

1.  Find a way to ask the operating system for an unused port within a range
2.  Assume that the system giving us the port range has already made them free for us, and just choose an increasing sequence (erring loudly if this fails)

**Comment by stuartarchibald** [comment]
I think either of these would be fine, the latter, with consistent and accessible complaining (for easy parsing), is probably easiest place to start?

**Comment by pitrou** [comment]
If we change the syntax only slightly, we can fit this feature in the URL syntax, for example `tcp://0.0.0.0:6000-6099` would listen somewhere in the [6000, 6099] port range. What do you think?

**Comment by pelson** [comment]
The addition of a port range would be awesome. I'm in the situation where I have a range of ports opened on my firewall, and I just want to use any available port in the given range.

@pitrou - looks like a good suggestion. Looks fairly similar to the [iptables approach](https://www.cyberciti.biz/tips/linux-iptables-how-to-specify-a-range-of-ip-addresses-or-ports.html). The ```--http-port``` / ```--bokeh-port``` interface wouldn't be able to use the ```tcp://``` form though, so would need to do both (not that I need the bokeh interface in this instance).

**Comment by dhirschfeld** [comment]
This would be a very useful feature! I've just hit this limitation when trying to deploy on Azure where I'm currently using a powershell script like below:
```powershell
$ports = @(50800, 50801, 50802, 50803)
foreach ($port in $ports) {
    Start-Process -NoNewWindow dask-worker.exe -ArgumentList '--nthreads=1','--nprocs=1',"--worker-port=$port",'tcp://10.1.0.4:8786';	
}
```

**Comment by stuartarchibald** [comment]
@pitrou The suggested URL syntax form seems good to me, neat idea, also saves having custom parsers etc.

**Comment by julioasotodv** [comment]
So, I believe that this has not been implemented yet, right?

The only current way to specify ports for more than one process is to actually create multiple dask-workers in one machine...

**Comment by mrocklin** [comment]
Correct

**Comment by julioasotodv** [comment]
Ok thanks

**Comment by gdurif** [comment]
Is there any news regarding that feature ?
Thanks

**Comment by stuartarchibald** [comment]
Thanks for implementing this @jrbourbeau!
