### ISSUE TITLE
What is a correct way to submit a module function?

### ISSUE THREAD

**Issue by ygl-rg** [dask/distributed#924]
Hi All

There is a file called fetch_task.py and a function Fetch inside. It looks like:

In fetch_task.py

def Fetch():
    """logic here"""

In main.py

import fetch_task

client = Client("localhost:8789")

client.submit(fetch_task.Fetch)

I noticed following error: 

> ImportError: No module named fetch_task

a workaround I used here is to change \_\_module\_\_ attribute to \_\_main\_\_ like:

fetch_task.Fetch.\_\_module\_\_ = '\_\_main\_\_'

and submit again. 

It worked but It is not so convenient. 

I want know whether there is a way to import function without changing \_\_module\_\_

Regards

gelin yan

**Comment by mrocklin** [comment]
Your workers need to also have the code that is on your client computer.
You might want to try uploading your .py file to the workers using the
upload_file method:
http://distributed.readthedocs.io/en/latest/api.html#distributed.client.Client.upload_file

**Comment by ygl-rg** [comment]
Hi Matthew

   Thanks for your suggestion. It works as expected.

Regards

gelin yan
