### ISSUE TITLE
Since v1.15.2 default_client can be unreliable in the as_completed function

### ISSUE THREAD

**Issue by strets123** [dask/distributed#928]
With some ways of starting a client e.g. running Client() noninteractively other through Unittest, the call to default_client raises a ValueError even though what should be the default client is available

One work-around would be to ask the user to pass the loop instance through in the AsCompleted init method. The current error message does not help much in trying to do this.

    def __init__(self, futures=None, loop=None):
        if futures is None:
            futures = []
        self.futures = defaultdict(lambda: 0)
        self.queue = pyQueue()
        self.lock = Lock()
        try:
            self.loop = loop or default_client().loop
        except ValueError as e:
            e.message = e.message + """
            When you see this error calling as_completed but you believe a client is available
            try passing client.loop from the current client you are using into the as_completed function"""
            raise

**Comment by mrocklin** [comment]
Hi @strets123 are you able to say more about how to reproduce the error you've observed?  Perhaps you can provide a minimal failing example?

**Comment by strets123** [comment]
I have not been able to reproduce with a simple example so happy for this to be closed for now and I reopen if I see it again.
