### ISSUE TITLE
Bandwidth during dataframe shuffles is low

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#932]
I'm running the following experiment with partition frequencies of both '7d' and '30d'

```python
from dask.distributed import Client, wait, progress
c = Client('localhost:8786')
c

import dask.dataframe as dd
df = dd.demo.make_timeseries('2000', '2001',
                             {'x': float, 'y': float, 'id': int},
                             freq='1s', partition_freq='7d', seed=2)
df = df.persist()
wait(df)

start = time()
df2 = df.set_index('id').persist()
wait(df2)
end = time()
print(end - start)  # trying to optimize this
```

### Profiles

- [Seven day (smaller) partitions](https://cdn.rawgit.com/mrocklin/9193d8c6fbb73a7b3149b6f9cb2c4e25/raw/4bdda7b8c671eb60cfaad41282b228585a1e75df/dataframe-shuffle-7d.html)
- [Thirty day (larger) partitions](https://cdn.rawgit.com/mrocklin/9193d8c6fbb73a7b3149b6f9cb2c4e25/raw/4bdda7b8c671eb60cfaad41282b228585a1e75df/dataframe-shuffle-30d.html)

### Analysis

Bandwidths in the small case are poor.  They're close to 15MB/s per chunk.  There is a lot of overlapping though.  We tend to get somewhere around 50MB/s and 70MB/s.  (This is for the whole machine).  In the larger case they're better, around 120MB/s on average peaking up to 250MB/s.  This is all on localhost though, so we should expect better.

The time to instantiate a new connection can takes a surprising amount of time (100ms or so) with wide spread, which might contribute a bit to the poor bandwidths.  This should be at or below a millisecond.

My first guess on all of this is that our network is less responsive due to GIL-holding computations in Pandas (cc @jreback) but this is just a guess.

### Some things we can do

1.  Reduce serialization cost of pandas dataframes (see #931 and https://issues.apache.org/jira/browse/ARROW-376) (cc @wesm) 
2.  Pool inter-worker connections (will try this next)
3.  Investigate gil-free pandas operations (these computations get poor speedups in a thread pool, so this is presumably still a live issue (cc @jreback))
4.  Byte-copy-free tornado IOStreams? (cc @pitrou)

The odds of any individual issue here resolving the problem is low so individually these are all probably pretty low priority.

**Comment by jreback** [comment]
what kinds of ops are ``dd.set_index(...)`` actually doing?

**Comment by mrocklin** [comment]
> what kinds of ops are dd.set_index(...) actually doing?

Looking at the profiles may give some understanding here.  In summary:

1.  Splitting dataframes into groups

    ```python
    def shuffle_group(df, col, stage, k, npartitions):
        if col == '_partitions':
            ind = df[col].values % npartitions
        else:
            ind = partitioning_index(df[col], npartitions)
        c = ind // k ** stage % k
        g = df.groupby(c)
        return {i: g.get_group(i) if i in g.groups else df.head(0) for i in range(k)}
```
2.  Splitting those dicts into different components (just getitem)
3.  Concatenation along rows
4.  Sorting along the index (towards the end)

Step 1 is the only thing that happens during communication heavy periods and lasts for any real duration.

**Comment by jreback** [comment]
![image](https://cloud.githubusercontent.com/assets/953992/23555644/b34df9e8-fff7-11e6-8603-942af80907d2.png)

(this is on a local machine). looks like most of the bottlenecks are actually the shuffle or am I reading this wrong?

**Comment by jreback** [comment]
![image](https://cloud.githubusercontent.com/assets/953992/23555710/f756c1ce-fff7-11e6-88e9-0b8fad3ea86a.png)

**Comment by mrocklin** [comment]
I recommend starting a dask-worker with `--nprocs 8 --nthreads 1` to force inter-process communication.

**Comment by mrocklin** [comment]
A couple other anecdata points:

1.  Replacing a numeric column with a text column doubles or triples the shuffle duration.  To be clear we're not setting this text column as the index, it's just along for the ride.
2.  Sorting a Spark DataFrames with the same data is around 30% faster in the numeric case and a few times faster in the text case (at least with my current configuration).

**Comment by jreback** [comment]
![image](https://cloud.githubusercontent.com/assets/953992/23556225/d8df2220-fff9-11e6-876c-c224feca033e.png)

**Comment by jreback** [comment]
yep a bit different :>

**Comment by mrocklin** [comment]
You may also enjoy looking at the following diagnostic pages:

- http://localhost:8789/system 
- http://localhost:8789/main.html 
- http://localhost:8789/crossfilter

These give a good view of what a particular worker is doing

**Comment by jreback** [comment]
sorting is pretty much using ``np.argsort`` which is gil releasing

**Comment by mrocklin** [comment]
Any thoughts on how to improve the `shuffle_group` function?  The goal here is to hash a particular column and then separate it into different sub-dataframe components.  It might be simplified as follows

```python
def shuffle_group(df, col, stage, k, npartitions):
    ind = hash_pandas_object(df[col]) % npartitions
    c = ind // k ** stage % k
    g = df.groupby(c)
    return {i: g.get_group(i) if i in g.groups else df.head(0) for i in range(k)}
```

**Comment by jreback** [comment]
if this is my scheduler info, the workers how do I look at the worker? 
```
{'address': 'tcp://127.0.0.1:8786',
 'id': '98dfdc62-0023-11e7-a34b-6c4008997976',
 'services': {'http': 53003},
 'type': 'Scheduler',
 'workers': {'tcp://127.0.0.1:52979': {'host': '127.0.0.1',
   'last-seen': 1488554224.744344,
   'last-task': 1488553901.274083,
   'local_directory': '/var/folders/h3/mr_r3bkj5yg0pbx9fr3tk1r00000gp/T/worker-tbgc3emo',
   'memory_limit': 1288490188.0,
   'name': 'tcp://127.0.0.1:52979',
   'ncores': 1,
   'services': {},
   'time-delay': 0.006539106369018555},
```

**Comment by mrocklin** [comment]
If you have bokeh installed and start the worker with `dask-worker ...` it should come up automatically.  You would have to be using a version of dask.distributed released sometime this year.

**Comment by mrocklin** [comment]
The worker bokeh servers aren't deployed if you're using the Python `LocalClient` or `Client()` convenience setup solutions.

**Comment by jreback** [comment]
ahh, ok

``shuffle_group(df, 'A', 10, 10, 10)``

what kind of parameters are you calling this with? whats the dtype (and len) of the column? (IOW is the the actual column from a pandas DataFrame (not dask) above?)

**Comment by mrocklin** [comment]
Yes, this function is called on each partition (pandas dataframe).

The parameter `k` controls how sharded the input dataframe becomes.  It is between 1 and 100.  In the example above it would have been around 20.  

I don't think that the parameters stage and npartitions significantly affect performance, but npartitions is the number of partitions (1 to 10000?).  Stage goes between 1 and something like `log(npartitions) / log(k)`

**Comment by mrocklin** [comment]
The column is the column on which we are sorting/shuffling.  In the case above it is `'id'`

**Comment by jreback** [comment]
```
In [1]: def shuffle_group(df, col, stage, k, npartitions):
   ...:     from pandas.tools.hashing import hash_pandas_object
   ...:     ind = hash_pandas_object(df[col]) % npartitions
   ...:     c = ind // k ** stage % k
   ...:     g = df.groupby(c)
   ...:     return {i: g.get_group(i) if i in g.groups else df.head(0) for i in range(k)}
   ...: 

In [2]: df = pd.DataFrame({'A' : np.random.randn(10000000)})

In [3]: %time _ = shuffle_group(df, 'A', 1, 10, 1)
CPU times: user 1.34 s, sys: 482 ms, total: 1.82 s
Wall time: 1.82 s

```

**Comment by jreback** [comment]
this is almost all hashing cost (well some for the groupby indexer computation)
``c = ind // k ** stage % k`` mainly because its producing a bunch of intermediates

```
         3546 function calls (3509 primitive calls) in 1.890 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.386    0.193    0.461    0.230 hashing.py:71(hash_array)
        2    0.221    0.110    0.221    0.110 {built-in method _operator.mod}
        2    0.174    0.087    0.174    0.087 {method 'get_labels' of 'pandas.hashtable.Int64HashTable' objects}
        6    0.160    0.027    0.160    0.027 {method 'take' of 'numpy.ndarray' objects}
        6    0.148    0.025    0.148    0.025 {method 'astype' of 'numpy.ndarray' objects}
        2    0.135    0.068    0.135    0.068 {pandas.algos.groupsort_indexer}
        1    0.103    0.103    0.103    0.103 {built-in method _operator.floordiv}
        2    0.103    0.052    0.214    0.107 algorithms.py:166(safe_sort)
        1    0.067    0.067    0.067    0.067 {pandas.algos.take_2d_axis0_float64_float64}
        1    0.051    0.051    1.890    1.890 <string>:1(<module>)
        4    0.049    0.012    0.049    0.012 {built-in method pandas.algos.ensure_int64}
        1    0.037    0.037    0.039    0.039 indexing.py:1857(maybe_convert_indices)
       25    0.029    0.001    0.029    0.001 {method 'reduce' of 'numpy.ufunc' objects}
```

**Comment by mrocklin** [comment]
Is that within scope to accelerate within Pandas?

**Comment by jreback** [comment]
```
In [29]: def shuffle_group(df, col, stage, k, npartitions):
    ...:     from pandas.tools.hashing import hash_pandas_object
    ...:     ind = hash_pandas_object(df[col]) % npartitions
    ...:     c = ind // k ** stage % k
    ...:     g = df.groupby(c)
    ...:     return {i: g.get_group(i) if i in g.groups else df.head(0) for i in range(k)}
    ...: 

In [31]: %time _ = shuffle_group(df, 'A', 1, 10, 5)
CPU times: user 1.22 s, sys: 366 ms, total: 1.58 s
Wall time: 1.58 s

In [32]: def shuffle_group(df, col, stage, k, npartitions):
    ...:     from pandas.tools.hashing import hash_pandas_object
    ...:     ind = hash_pandas_object(df[col]) % npartitions
    ...:     c = (ind // k ** stage % k).astype('category')
    ...:     g = df.groupby(c)
    ...:     return g.groups
    ...:     
    ...:     
    ...: 

In [33]: %time _ = shuffle_group(df, 'A', 1, 10, 5)
CPU times: user 909 ms, sys: 309 ms, total: 1.22 s
Wall time: 1.22 s
```

you can get a little faster by doing this

**Comment by mrocklin** [comment]
The categories trick is welcome.  Thanks.  I'll look into if Numba can (optionally) help with the arithmetic.

**Comment by jreback** [comment]
actually this is about 2x slower than it should be.

The problem is hashing a Series *also* hashes the index. which I suspect is the same every time.

so I think you can simply pass ``index=False`` as well.

**Comment by jreback** [comment]
```
In [6]: df = pd.DataFrame({'A' : np.random.randn(10000000)})

In [7]: def shuffle_group(df, col, stage, k, npartitions):
   ...:     from pandas.tools.hashing import hash_pandas_object
   ...:     ind = hash_pandas_object(df[col]) % npartitions
   ...:     c = (ind // k ** stage % k).astype('category')
   ...:     g = df.groupby(c)
   ...:     return g.groups
   ...: 

In [8]: %time _ = shuffle_group(df, 'A', 1, 10, 5)
CPU times: user 941 ms, sys: 302 ms, total: 1.24 s
Wall time: 1.24 s

In [9]: def shuffle_group(df, col, stage, k, npartitions):
   ...:     from pandas.tools.hashing import hash_pandas_object
   ...:     ind = hash_pandas_object(df[col], index=False) % npartitions
   ...:     c = (ind // k ** stage % k).astype('category')
   ...:     g = df.groupby(c)
   ...:     return g.groups
   ...:     
   ...: 

In [10]: %time _ = shuffle_group(df, 'A', 1, 10, 5)
CPU times: user 738 ms, sys: 222 ms, total: 960 ms
Wall time: 960 ms

In [11]: 
```

**Comment by mrocklin** [comment]
Ah, I'm actually already doing that in the real/slightly more complex code.

**Comment by jreback** [comment]
yeah I think there are some things we could do withing hashing to avoid copying (which is now starting to dominate)

**Comment by jreback** [comment]
this is using ``numexpr`` internally (the eval) to eliminate some temporaries
```
In [16]: def shuffle_group(df, col, stage, k, npartitions):
    ...:     from pandas.tools.hashing import hash_pandas_object
    ...:     ind = hash_pandas_object(df[col], index=False)
    ...:     c = (pd.eval('(ind  % npartitions) / k ** stage % k')).astype('category')
    ...:     g = df.groupby(c)
    ...:     return g.groups
    ...:     
    ...:     

In [17]: %time _ = shuffle_group(df, 'A', 1, 10, 5)
CPU times: user 838 ms, sys: 277 ms, total: 1.12 s
Wall time: 827 ms

In [18]: 
```

**Comment by jreback** [comment]
so you *might* also wish to do something completely different

if you return ``g.indices`` rather than ``g.groups`` you avoid group construction altogether.

then you can simply iterate and ``.take`` (the ``indices``) are simply the indexer into the groups which is all I think you want

**Comment by mrocklin** [comment]
I like the idea of thinking about what we can do that is entirely different.  However the desired end result is a bunch (roughly 20) of separate small dataframes that we can send to different machines.  Indexes alone are not sufficient.

**Comment by jreback** [comment]
@mrocklin no my point is this. This routine simply computes the indexers. I *think* AFAIR you have a different part where you actually construct the separate frames. This would allow you to separate these things. 

Not sure if this is completely useful, but it *might* be.

**Comment by mrocklin** [comment]
Maybe.  It all happens sequentially on the same machine so I don't think that there would be much benefit here.

It looks like `pd.eval`/numexpr doesn't like floor division:

```python
In [120]: %time _ = pd.eval('(ind % npartitions) // k ** stage % k')
TypeError: unsupported operand type(s) for //: 'OpNode' and 'OpNode'
```

The category trick shaves off 10% from shuffle time.  If our data is purely numeric and partition size is large-ish then dask.dataframe shuffles narrowly beat spark dataframe shuffles.  If any of those ifs are broken then Spark dataframes pull ahead.

**Comment by mrocklin** [comment]
Rather than use numexpr or numba I'm just using numpy more intelligently.  This is no longer a significant bottleneck.  The dict comprehension is now probably the worst.  

I don't suppose there is some cython-optimized way to shard a dataframe along a pre-computed column?  Something like cut?

**Comment by jreback** [comment]
can u show an example of what you sre looking?

**Comment by mrocklin** [comment]
This is what I do now.  Line seven is slow.

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 30, 40]})

In [3]: import numpy as np

In [4]: groups = np.array([0, 2, 1, 1])

In [5]: df
Out[5]: 
   x   y
0  1  10
1  2  20
2  3  30
3  4  40

In [6]: g = df.groupby(groups)

In [7]: out = [g.get_group(i) for i in range(3)]

In [8]: out[0]
Out[8]: 
   x   y
0  1  10

In [9]: out[1]
Out[9]: 
   x   y
2  3  30
3  4  40

In [10]: out[2]
Out[10]: 
   x   y
1  2  20
```

**Comment by jreback** [comment]
the overhead associated with that is really construction of each frame. e.g. effectively this does
``{i:df.take(indexer) for i, indexer in enumerate(g.indices.values())}``

its about even with costs of: ``.take``, construction of the result frames, and the grouping

```
In [23]: df = DataFrame({'A':np.random.randn(N), 'B':np.random.randint(0,ngroups,size=N)})

In [24]: %%time
    ...: g = df.groupby('B')
    ...: _={i:g.get_group(i) for i in range(ngroups)}
    ...: 
    ...: 
CPU times: user 714 ms, sys: 102 ms, total: 816 ms
Wall time: 815 ms

```

**Comment by mrocklin** [comment]
I wonder if it might be faster to make a copy, shuffle the data around in memory using something like set_index, and then shard out the dataframes from that already allocated (and now properly aligned) data.

**Comment by mrocklin** [comment]
Naive timings say no:

```python
In [51]: df = pd.DataFrame({'A' : np.random.randn(1000000)})

In [52]: ind = hash_pandas_object(df['A'], index=False) % 50

In [53]: %time g = df.groupby(ind); groups = {i: g.get_group(i) for i in range(50)}
CPU times: user 76 ms, sys: 0 ns, total: 76 ms
Wall time: 73.7 ms

In [54]: %time df['ind'] = ind; df2 = df.sort_values('ind'); del df['ind']
CPU times: user 128 ms, sys: 100 ms, total: 228 ms
Wall time: 230 ms
```

**Comment by wesm** [comment]
@mrocklin since you are dealing with fixed cardinality integers you can do O(n) counting sort and get much better performance. Remember also that adding and removing DataFrame incurs internal BlockManager consolidation overhead

```
In [24]: from pandas.algos import groupsort_indexer

In [25]: ind64 = ind.values.view(np.int64)

In [26]: %timeit indexer, _ = groupsort_indexer(ind64, 50); df2 = df.take(indexer)
10 loops, best of 3: 31.2 ms per loop

In [27]: %timeit g = df.groupby(ind); groups = {i: g.get_group(i) for i in range(50)}
10 loops, best of 3: 78.7 ms per loop
```

**Comment by mrocklin** [comment]
That's a nice boost.  Thank you @wesm .  

Current solution here: https://github.com/dask/dask/pull/2032/files

Further optimizations welcome, but at least on my current benchmarks this has moved down out of primary-bottleneck status.

**Comment by jakirkham** [comment]
Was curious how things had progressed since this issue was opened. Unfortunately some things likes RawGit no longer exist, so don't have a clear idea where things were.

In any event tidied things up a bit and put them in [this Gist]( https://gist.github.com/jakirkham/d0a12143c551c5e935403534f6150506 ). Here's [the script I used]( https://gist.github.com/jakirkham/d0a12143c551c5e935403534f6150506#file-shuffle_script-py ) and [the performance report]( https://gistcdn.githack.com/jakirkham/d0a12143c551c5e935403534f6150506/raw/4fd93f7e2392163093d5cdafa0af23d96d217ac5/dask-report.html ).

Would be curious to know whether people think this is still slow and if so where they think it can be improved. Of course things have progressed in the past few years so the same improvements may or may not make sense.

**Comment by mrocklin** [comment]
This issue has been silent for years.  Closing.

@jakirkham I recommend raw.githack.com today

https://gist.githack.com/jakirkham/d0a12143c551c5e935403534f6150506/raw/4fd93f7e2392163093d5cdafa0af23d96d217ac5/dask-report.html

**Comment by mrocklin** [comment]
Thank you for running the experiment and posting results.  That will be helpful the next time someone takes a look at this.
