### ISSUE TITLE
Bokeh network graphs are saw-toothed

### ISSUE THREAD

**Issue by martindurant** [dask/distributed#942]
It appears that at many time-points, multiple points are being plotted for each of the two lines.

**Comment by martindurant** [comment]
![screen shot 2017-03-11 at 18 52 02](https://cloud.githubusercontent.com/assets/6042212/23827855/ed1c6f84-068b-11e7-926b-eb837f241455.png)

**Comment by martindurant** [comment]
OK, so the reason is that you get a point for each worker, but they will arrive at exactly the same time for a single-machine deployment; but transferring the messages uses the network, so you can get multiple values at the same timepoint. In the CPU and memory graph you also have duplicated points, but the y-values are equal. There should be de-duplication by time/machine somewhere.

**Comment by mrocklin** [comment]
FWIW I'm also planning to remove these plots from the main status page and replace them with others.

**Comment by martindurant** [comment]
OK, I'll leave it for now, then. It was just a minor annoyance ;)
