### ISSUE TITLE
Released version 1.16.0 on the PyPi contains critical issue

### ISSUE THREAD

**Issue by sand8080** [dask/distributed#944]
Released version 1.16.0 at https://pypi.python.org/pypi/distributed contains an error in the distributed/worker.py at line 533:

  File "/usr/local/lib/python2.7/dist-packages/distributed/worker.py", line 533, in gather
logger.warn("Could not find data", e)
NameError: global name 'e' is not defined

In the master branch it is already fixed. Please publish fixed version of the distributed package.

**Comment by mrocklin** [comment]
1.16.1 has been released.  Thank you for reporting.
