### ISSUE TITLE
client.gather(client.map(..)) results guaranteed to be in order of input iterable?

### ISSUE THREAD

**Issue by lebedov** [dask/distributed#967]
Are the results of `client.gather(client.map(func, it))` guaranteed to be in the same order as elements in the input iterable `it`? (This seems to be the case empirically.) I'm using distributed dask 1.16.0.

**Comment by mrocklin** [comment]
Yes.  If you want to go out of order then see [as_completed](http://distributed.readthedocs.io/en/latest/api.html?highlight=as_completed#distributed.client.as_completed)

**Comment by lebedov** [comment]
Great - thanks.
