### ISSUE TITLE
Issue to distribute python over docker containers

### ISSUE THREAD

**Issue by verhcedr** [dask/distributed#968]
Hi,

I try to integrate your library to distribute Python Machine Learning Algorithm (scikit learn) over multiple machines and i got an issue when submitting my script .py

My configuration is the following :
- 1 docker for the scheduler
- 3 docker for my workers
- 1 docker as a client (used to submit my jobs)

When i try to submit a simple script like the "sample_distributed.py" from the client i got the following error : 
```
root@7b62357b596a:/jobs# dask-submit 172.21.0.2:8786 sample_distributed.py
Traceback (most recent call last):
  File "/usr/local/bin/dask-submit", line 11, in <module>
    sys.exit(go())
  File "/usr/local/lib/python3.6/site-packages/distributed/cli/dask_submit.py",
line 27, in go
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __ca
ll__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invo
ke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invo
ke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/distributed/cli/dask_submit.py",
line 21, in main
    IOLoop.instance().run_sync(f)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 457, in
run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 237,
 in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1021, in ru
n
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/distributed/cli/dask_submit.py",
line 15, in f
    stdout, stderr = yield _submit(remote_client_address, filepath)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1015, in ru
n
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 237,
 in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1024, in ru
n
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/distributed/submit.py", line 87,
in _submit
    raise gen.Return((result['stdout'], result['stderr']))
TypeError: string indices must be integers
distributed.core - WARNING - rpc object <rpc to 'tcp://172.21.0.2:8786', 1 comms
> deleted with 1 open comms
```

On my scheduler, i can see some warnings :
```
root@88361b259489:/jobs# distributed.scheduler - INFO - Register tcp://172.21.0.
5:43459
distributed.scheduler - INFO - Starting worker compute stream, tcp://172.21.0.5:
43459
Traceback (most recent call last):ndler found: upload_file
  File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 246, i
n handle_comm
    handler = self.handlers[op]
KeyError: 'upload_file'
distributed.core - WARNING - No handler found: execute
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 246, i
n handle_comm
    handler = self.handlers[op]
KeyError: 'execute'
```

My dockerfile : [Dockerfile](https://github.com/dask/distributed/files/868468/Dockerfile.txt)
My script PY : [sample_distributed.py](https://github.com/dask/distributed/files/868473/sample_distributed.py.txt)

Can someone help me ? What did i do wrong ?
Thanks !

**Comment by pitrou** [comment]
Are you sure you are using the same version of Dask/distributed on each node (client, scheduler, workers)?

**Comment by mrocklin** [comment]
It looks like this is using dask-submit, a feature originally written by @hussainsultan.  He may have some insight here.  I personally haven't used this tool before.

**Comment by hussainsultan** [comment]
I will look at it over the weekend. Thanks.

**Comment by verhcedr** [comment]
@pitrou : Yes, i'm using the same dockerfile and just scale to 5 containers.
@mrocklin : Yes, i use dask-submit on the client docker container.

**Comment by verhcedr** [comment]
Versions used : 
```
root@6be177151615:/jobs# pip show dask
Name: dask
Version: 0.14.1
Summary: Parallel PyData with Task Scheduling
Home-page: http://github.com/dask/dask/
Author: Matthew Rocklin
Author-email: mrocklin@gmail.com
License: BSD
Location: /usr/local/lib/python3.6/site-packages
Requires:
root@6be177151615:/jobs# pip show distributed
Name: distributed
Version: 1.16.1
Summary: Distributed computing
Home-page: https://distributed.readthedocs.io/en/latest/
Author: Matthew Rocklin
Author-email: mrocklin@gmail.com
License: BSD
Location: /usr/local/lib/python3.6/site-packages
Requires: cloudpickle, click, sortedcollections, tblib, zict, six, dask, msgpack
-python, psutil, toolz, tornado
root@6be177151615:/jobs#
```

**Comment by mrocklin** [comment]
Have you considered not using dask-submit?  I personally don't know enough about it to support it.

**Comment by mrocklin** [comment]
In your .py file is it just me or is `client` undefined?

At a low level it looks like you're submitting something to the scheduler that was intended for dask-submit.    My guess is that you need to run `dask-remote` on the server side in order to use `dask-submit`? 

http://distributed.readthedocs.io/en/latest/submitting-applications.html

**Comment by verhcedr** [comment]
@mrocklin : Yes you right ! i forgot a line in my exemple when i copy/paste to the text file (`client = Client('172.21.0.2:8786')` just before `A = client...`)
`dask-remote` is already running on my scheduler docker container.
I see that, by default, the WebUI's port is the same as the dask-remote's port (8788) i changed it with `--port` option.

**Comment by mrocklin** [comment]
Do things run OK if you don't use dask-submit but instead connect directly to the scheduler?

The history behind dask-submit is that @hussainsultan wrote it a while ago, used it, but now is busy with other things.  No one else until you has used it, which puts you in an awkward position in that there isn't much active support on this feature.

I recommend avoiding it for now if you can.  I suspect that you'll have a smoother experience.

My guess is that you're "submitting" to the scheduler address rather than the dask-remote address or that you have a Python 2 / Python 3 mismatch.

**Comment by verhcedr** [comment]
If i run it directly with `python myscript.py`, it's OK.
If i dont use dask-submit, i need to create programmatically my scheduler ?

**Comment by mrocklin** [comment]
You need to start a scheduler and workers regardless.  

http://distributed.readthedocs.io/en/latest/setup.html

**Comment by verhcedr** [comment]
Ok, i will try without dask-submit for the moment.
An other question, when i run my python script ([dask.distributed_scikit_learn.py](https://github.com/dask/distributed/files/872624/dask.distributed_scikit_learn.py.txt)) with 3 workers, i see only one active worker (with `top` linux command)
What did I miss ?
Thanks

**Comment by mrocklin** [comment]
res.append(client.submit(lambda array: kneighbors_mp(array, nbrs), datarray[i]).result())

In this line you submit a computation, then you wait for it to complete (with `.result()`).  You probably want to submit several computations, and then gather them all at the end.

**Comment by verhcedr** [comment]
It seems to work well, i just call all submit and then call .result() on all future.
Thanks.
