### ISSUE TITLE
channel blocks on iteration and does not update data

### ISSUE THREAD

**Issue by danielb2814** [dask/distributed#976]
I have the simple task of submitting a future from a client which then another client needs to get and see if it finished. The initial client is destroyed shortly after submitting and adding the future to the channel (flask application). This seems from the documentation to be the perfect task for the channel concept. However I have the issue that the second client blocks forever when iterating over the channel:

```
def add(self, a, b):
        time.sleep(1)
        return a+b

with Client('127.0.0.1:8786') as client:
            chan = client.channel("some-id")
            future = client.submit(self.add, 2, 2)
            chan.append(future)
 
            future = client.submit(self.add, 4, 6)
            chan.append(future)
            chan.flush()

with Client('127.0.0.1:8786') as other_client:
            chan = other_client.channel("some-id")
          
            for f in chan:
                 print(f)


```

The above blocks in iterating over the channel. Interestingly chan.data is empty immediately after channel creation, i.e. the chan.data is not refreshed when connecting to an existing channel. One ugly trick is the following:

```
with Client('127.0.0.1:8786') as other_client:
        chan = other_client.channel("some-id")
          
        def foo():
            pass

        foo = self.client.submit(foo)
        chan.append(foo)
        chan.flush()
 
        # the next two lines need a long explanation
        for t in chan:
            break
 
        for f in chan.data:
            for f in chan:
                 print(f)
```

Submit a dummy future and break on the iteration on chan. This updates the chan.data with the fresh future status. However this cannot be the right way to do it.

I appreciate to know if I am using channels wrong or this behaviour is wrong.

**Comment by danielb2814** [comment]
Correct. __After__ the first client is closed (not explicitly but by exiting the scope where the client was declared) another client is created a few seconds later. This second client then connects to the channel that was created by the first client. However it does not get the proper data unless I submit another foo task which forces the channel to update. This is however only an observation I am not sure that this second behaviour is always consistent. It has been so far.

**Comment by mrocklin** [comment]
Testing this now.  Both of the following work:

```python
def test_channel_gets_updates_immediately(loop):
    with cluster() as (s, [a, b]):
        with Client(s['address']) as c:
            x = c.channel('x')
            future = c.submit(inc, 1)
            x.append(future)
            x.flush()

        with Client(s['address']) as c:
            x = c.channel('x')
            future = next(iter(x))
            assert future.result() == 2


def test_channel_gets_updates_immediately_2(loop):
    with cluster() as (s, [a, b]):
        with Client(s['address']) as c:
            x = c.channel('x')

            with Client(s['address']) as c2:
                x2 = c.channel('x')
                future = c.submit(inc, 1)
                x.append(future)
                x.flush()

            future = next(iter(x))
            assert future.result() == 2
```

Can you think of ways in which we can alter these tests to trigger the error that you're seeing?

**Comment by danielb2814** [comment]
To block loop over the channel as bellow:

```
     with cluster() as (s, [a, b]):
        with Client(s['address']) as c:
            x = c.channel('x')

            with Client(s['address']) as c2:
                x2 = c.channel('x')
                future = c2.submit(inc, 1)
                x2.append(future)
                x2.flush()

            for f in x:
               print(f)
```

Calling future.result() blocks and triggers the computation. Unfortunately I cannot do that. My use case is that the first client submits a long running task (a few minutes) and the second client keeps reconnecting, checks if the future is finished and if not disconnects. By calling result() on the future it will block and pooling is not possible. The reason for disconnecting is that Flask is killing all state at the end of request thus I can't hold on to the Client.

Any way of updating the status of a submitted future without actually calling result()? Another question: a task submitted to a channel is scheduled immediately for execution?

**Comment by mrocklin** [comment]
```python
for f in x:
    print(f)
```

Should print one future and then block on the channel, waiting for more results.  Is this not what is happening?

`future.result()` doesn't trigger the computation, calling submit does.  Futures point to in-flight computations.

You can check for the status of the future by looking at `future.status`.

**Comment by mrocklin** [comment]
Perhaps you're just looking for `channel.stop()` to issue a StopIterator?

**Comment by danielb2814** [comment]
I guess I am puzzled why the first method block after iterating over all futures while the second keeps on iterating over all futures in the channel and then jumps back to the beginning. 

The desired goal is to iterate over all futures in the channel, check the status of each and then exit the iteration.

The first version blocks while the second jumps to the beginning. I am sorry if this is a lack of iterator knowledge on my side.

```
def test_channel_gets_updates_immediately_0():
    with cluster() as (s, [a, b]):
        key = None

        with Client(s['address']) as c:
            x = c.channel('x')
            future = c.submit(inc, 1)
            key = future.key
            x.append(future)
            x.flush()

        with Client(s['address']) as c:
            x = c.channel('x')
                      
            for future in x:
                if future.status == 'finished' and future.key == key:
                    print(future)
                    print(future.result())
                    break
            c.shutdown()                    

def test_channel_gets_updates_immediately_1():
    with cluster() as (s, [a, b]):
        key = None

        with Client(s['address']) as c:
            x = c.channel('x')
            future = c.submit(inc, 1)
            key = future.key
            x.append(future)
            x.flush()

        with Client(s['address']) as c:
            x = c.channel('x')

            while True:
                future = next(iter(x))
                if future.status == 'finished' and future.key == key:
                    print(future)
                    print(future.result())
                    break
            c.shutdown() 
```

**Comment by danielb2814** [comment]
Sorry the above is stupid:

```
while True:
                future = next(iter(x))
```

always creates a new iterator. no wonder it jumps back to the beginning.

**Comment by danielb2814** [comment]
I guess this could do it:

```
x = c.channel('x')
print(x.data)
while not x.data:
  time.sleep(0)
print(x.data)  
for f in x.data:             
  print(f)
```

Wait for data and then iterate over x.data. This does not block. I hope this is the recommended way to do it.

**Comment by mrocklin** [comment]
To make sure I understand your concern.  If you start iterating over a channel before it has any futures, then it doesn't seem to make any progress, even after futures have been put into it?

**Comment by danielb2814** [comment]
No no. This is not an issue. My concern was how to iterate once over all futures in a channel and then exit. I now make the following assumptions:

- a future submitted  by a client and added to a channel is scheduled immediately and even if the client dies the future is safely kept
- when another client connects to the same channel it should first wait for the channel.data to be populated. only after this happens can the client iterate over channel.data to check the status of each future in the channel. If none finished the client exists silently and returns later.

With this piece of code (also present in the test_channels.py):

```
while not x.data:
        yield gen.sleep(0.01)
```
a connecting client  must wait for the data to be populated. Only then an iterator over data makes sense. 

I was not expecting that an iterator over a channel blocks until new futures are posted by other clients. This of course makes sense in many use cases (producer/consumer). In the case when I just want to check the status of all futures in a channels this is less optimal. I guess I might be misusing the channels as a future store for intermittent clients.

**Comment by mrocklin** [comment]
Yeah, no guarantees are made about `.data` being populated on startup.  Generally you want to iterate over a channel directly.  If you know that there is ever only going to be a single future in the channel then you probably want to send a stop signal.

```python
with Client(...) as c:
    chan = c.channel('some-id')
    future = c.submit(func, *args)
    chan.add(future)
    chan.stop()
    chan.flush()
```

```python
with Client(...) as c:
    chan = c.channel('some-id')
    for future in chan:
        result = future.result()
    # we get here because of the `chan.stop` signal above.
```
