### ISSUE TITLE
Wait/sync doesn't break on KeyboardInterrupt

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#99]
Calling a function like `wait` that uses `sync` can not be broken with `KeyboardInterrupt`.  Two questions

1.  How does one test keyboard interrupts?  Is there a way to simulate the signal?
2.  What could be happening here?  We are waiting on a threading `Event` when the `KeyboardInterrupt` *should* interrupt us.  https://github.com/blaze/distributed/blob/master/distributed/utils.py#L104

**Comment by quasiben** [comment]
For 1.) you can send the `signal.SIGINT` to the process

**Comment by mrocklin** [comment]
Hrm, so this works fine on my machine:

```python

In [1]: from distributed import Executor
e = ^[[A
In [2]: e = Executor('127.0.0.1:8786')

In [3]: from time import sleep

In [4]: futures = e.map(sleep, range(100))

In [5]: from distributed import Executor, wait

In [6]: wait(futures)
KeyboardInterrupt                         Traceback (most recent call last)

In [7]: 
```

Any thoughts on how to reproduce this?  cc @danielfrg

**Comment by danielfrg** [comment]
What didn't worked for me was the interrupt button on the jupyter notebook, note sure if thats the same signal.

**Comment by mrocklin** [comment]
OK, this all works perfectly in Python 3 and crashes in Python 2.  I can reproduce this.  Thanks!
